/* Italia in Tavola — norske regionsammendrag. Region- og hovedstadsnavn beholdes på italiensk. */
window.COURSE_NO = {
 'IT-23':{intro:"I Valle d'Aosta vokser vinrankene nedenfor isbreene. Ved Morgex og La Salle holder bøndene rankene nær steinene, som avgir varme om natten, og arbeider for hånd. Høyere oppe beiter kyrne om sommeren. Melken skal raskt i ystekaret for å bli Fontina, og derfor må ysteriet følge buskapen.",
   landmark:{name:'Castello di Fénis og Matterhorn', desc:'Et eventyrslott fra middelalderen som vokter dalen, med Cervino (Matterhorn) som reiser seg 4 478 meter i enden av dalen.'},
   pairing:'Et glass Torrette til carbonada, den langkokte oksegryten som serveres over polenta.',
   lessons:["Europas høyeste vinmarker","Hvitviner fra Alpene og rødviner fra fjellet","Fontina og bordet i Alpene","Slottene i Aostadalen"]},
 'IT-21':{intro:"I Piemonte skyter Nebbiolo knopper tidlig og modner sent. Bøndene må leve med faren for vårfrost og høstvær før druene er i hus. I åsene rundt Alba er resultatet verdt risikoen. Mellom vinmarkene ligger skogene der trøffeljegerne leter med hund, mens vin blir til vermut i Torino.",
   landmark:{name:'Mole Antonelliana, Torino', desc:'Spiret på 167 meter som definerer Torinos silhuett, påbegynt i 1863 som synagoge og i dag nasjonalt filmmuseum.'},
   pairing:'Barolo til brasato al Barolo, eller en ung Barbera til tajarin med smør og revet hvit trøffel.',
   lessons:["Nebbiolo og Langhe-åsene","Barolo og Barbaresco, landsby for landsby","Trøffel, tajarin og bagna cauda","Torino: vermut, sjokolade og Mole"]},
 'IT-42':{intro:"I Liguria kan vinmarken ligge rett over havet og likevel være vanskelig å nå. Terrassene trenger murer, og druene må fraktes ned skråningen. Havnen i Genova knytter den smale kysten til en langt større verden. Norsk tørrfisk hører hjemme på kjøkkenet her, like selvfølgelig som basilikum i pesto.",
   landmark:{name:'Lanterna di Genova og Cinque Terre', desc:'Fyrtårnet på 77 meter har ledet skip inn til Genova siden 1543; lenger øst klamrer fem pastellfargede landsbyer seg til klippene.'},
   pairing:'Kald Vermentino til trofie al pesto, eller Sciacchetrà til en skive pandolce etter middagen.',
   lessons:["Vinranker på klippene","Vermentino, Pigato og havet","Pesto, focaccia og oliven","Genova: kjøkkenet i en sjøfartsrepublikk"]},
 'IT-25':{intro:"Lombardia strekker seg fra vinmarksterrassene i Alpene til rismarkene sør for Milano. I skråningene arbeider bøndene der maskinene ikke kommer til, mens maskinene forandret arbeidet for dem som luket rismarkene. Vannet binder landskapene sammen. En gang fraktet det også marmoren til domkirken inn til Milano.",
   landmark:{name:'Duomo di Milano', desc:'Marmorkatedralen tok seks hundre år å fullføre og bugner av 135 spir og 3 400 statuer, kronet av den gylne Madonnina.'},
   pairing:'Franciacorta Satèn til risotto alla milanese; Sforzato di Valtellina til pizzoccheri.',
   lessons:["Franciacorta: Italias svar på champagne","Nebbiolo i Alpene: Valtellina","Safranrisotto og det milanesiske bordet","Domkirken og designbyen"]},
 'IT-32':{intro:"I Trentino-Alto Adige kan samme vin ha både et italiensk og et tysk navn. Handelen går gjennom dalene over Alpene. Eplehagene ligger på dalbunnen, mens vinmarker og gårder ligger i skråningene. Brødboller hører til på bordet sammen med viner som har fått et helt annet ry i løpet av én generasjon.",
   landmark:{name:'Dolomittene', desc:'Bleke kalksteinstårn som gløder rosa i solnedgangen, et UNESCO-verdensarvsted som reiser seg over vinmarker og eplehager.'},
   pairing:'Gewürztraminer til speck og oster fra Alto Adige; Lagrein til vilt og canederli.',
   lessons:["Vinmarker mellom to kulturer","Gewürztraminer, Lagrein og det aromatiske nord","Speck, brødboller og strudel","Dolomittene: fjell av stein og lys"]},
 'IT-34':{intro:"I Veneto preger tørking både druene og fisken. Druene mister vann før de blir til fyldig vin. Torsken kommer tørr fra Norge og må bløtlegges før den kan tilberedes. Venezia tok imot matvarer og ideer gjennom havnen, mens vinbøndene innenlands utviklet svært forskjellige viner i åsene.",
   landmark:{name:'Venezia: Campanile di San Marco', desc:'Klokketårnet på 99 meter over Piazza San Marco, gjenreist i 1912 etter at originalen raste sammen; gondolene glir forbi nedenfor.'},
   pairing:'Soave til risi e bisi; Amarone til lagret Asiago eller en langkokt pastissada de caval.',
   lessons:["Valpolicella og kunsten å tørke druer","Prosecco: fra åsene til glasset","Cicchetti og den venetianske bàcaro","Venezia: en republikk bygget på handel"]},
 'IT-36':{intro:"I Friuli-Venezia Giulia går en grense gjennom landskap folk lenge har delt. Vinbøndene rundt Gorizia har stilt spørsmål ved hvordan hvitvin skal lages, blant annet ved å la mosten ligge med drueskallene. Ifølge lokale fortellinger kom krydderet i fjellmaten lenger vest med omreisende selgere. I Trieste kommer kaffen gjennom havnen.",
   landmark:{name:'Castello di Miramare, Trieste', desc:'Et hvitt slott bygget i 1860 for erkehertug Maximilian på et klippenes over Adriaterhavet.'},
   pairing:'Friulano til prosciutto di San Daniele; Refosco til frico og polenta.',
   lessons:["Collio og de store italienske hvitvinene","Friulano, Ribolla og oransjevin","San Daniele, frico og det karniske kjøkkenet","Trieste: kaffe, habsburgere og bora-vinden"]},
 'IT-45':{intro:"I Emilia-Romagna er mye av maten til middagen tilberedt lenge før kokken setter i gang. Osten har modnet på trehyller, skinken har hengt til tørk, og eddiken har ligget i årevis på fat. Ved kjøkkenbordet kommer et annet arbeid i tillegg når eggpastaen kjevles ut. Tørr Lambrusco gir syre og bobler til den fyldige maten.",
   landmark:{name:'De to tårnene, Bologna', desc:'Asinelli (97 m) og det skjeve nabotårnet Garisenda, middelalderske familietårn som fortsatt rager over byen med buegangene.'},
   pairing:'Tørr Lambrusco til et brett med salumi og Parmigiano; Sangiovese di Romagna til tagliatelle al ragù.',
   lessons:["Lambrusco, vinen som var to viner","Sangiovese på Romagna-siden","Parmigiano, prosciutto og balsamico: tre beskyttede skatter","Bologna la Grassa og sfogliaen"]},
 'IT-52':{intro:"I Toscana forandrer Sangiovese seg med voksestedet og arbeidet i kjelleren. Langs kysten plantet bøndene også druer de kjente fra Bordeaux. I Firenze kan man bli kjent med regionen gjennom maten: brød brukes i suppen, og ved en bod på markedet blir kumage til lunsj.",
   landmark:{name:'Det skjeve tårnet i Pisa og Brunelleschis kuppel', desc:'Pisas klokketårn har hellet siden 1170-tallet; i Firenze er Brunelleschis kuppel fra 1436 fortsatt den største murkuppelen som noen gang er bygget.'},
   pairing:'Chianti Classico til bistecca alla fiorentina; Vin Santo til cantucci som dyppes i glasset.',
   lessons:["Sangiovese: én drue, mange ansikter","Chianti Classico og den svarte hanen","Brunello, Nobile og supertoskanerne","Brød, bønner og den florentinske biffen"]},
 'IT-55':{intro:"Umbria har ingen kyst, men maten og vinen har reist langt utenfor åsene her. Slaktere fra Norcia tok arbeid i andre byer, og bynavnet fulgte med yrket. Under Orvieto er kjellerne hogd inn i fjellet. Rundt Montefalco brukes Sagrantino både til søt vin av tørkede druer og til kraftig tørr rødvin.",
   landmark:{name:'Basilica di San Francesco, Assisi', desc:'To kirker oppå hverandre, bygget fra 1228 over graven til den hellige Frans, med fresker av Giotto og Cimabue.'},
   pairing:'Sagrantino til lammestek eller lagret pecorino; Orvieto til strangozzi al tartufo nero.',
   lessons:["Vinmarken uten kyst","Sagrantino: Italias mest tanninrike rødvin","Norcia: trøffel, salumi og norcinoen","Assisi og åsbyene"]},
 'IT-57':{intro:"I Marche forandrer maten seg mellom dalene innenlands og Adriaterhavet. Verdicchio har andre vekstvilkår ved Matelica enn i åsene rundt Jesi. Ved kysten har folk tradisjonelt dykket etter ville blåskjell på undervannsklipper. I Ascoli skjærer kokkene fruktkjøttet av olivenene i et sammenhengende bånd, slik at de kan fylle dem.",
   landmark:{name:'Palazzo Ducale, Urbino', desc:'Renessansepalasset til hertug Federico da Montefeltro, med to slanke tårn over den murkransede åsbyen.'},
   pairing:'Verdicchio til brodetto all\'anconetana; Rosso Conero til vincisgrassi.',
   lessons:["Verdicchio: en hvitvin som eldes som en rødvin","Montepulciano på Conero","Ascoli-oliven og Adriaterhavets brodetto","Urbino og idealbyen"]},
 'IT-62':{intro:"Roma får både mat og mennesker fra områdene rundt. Før kom vinen med kjerre fra åsene, og innflyttere fra Amatrice fant arbeid med å mette byen. Amatriciana bærer byens navn, men de kjente romerske pastarettene har ingen felles dokumentert opprinnelse. Utenfor hovedstaden går Lazios vinmarker fra vulkansk jord til kalksteinsåsene der Cesanese vokser.",
   landmark:{name:'Colosseum og Peterskirken, Roma', desc:'Det flaviske amfiteateret, ferdig i år 80, hadde plass til rundt 50 000 tilskuere til leker og skuespill.'},
   pairing:'Frascati til carciofi alla giudia; Cesanese til abbacchio alla romana eller amatriciana.',
   lessons:["Castelli Romani og Frascati","Cesanese: Lazios glemte rødvin","De fire romerske pastarettene","Roma: Colosseum og det evige bordet"]},
 'IT-65':{intro:"I Abruzzo ligger vinmarkene ned mot Adriaterhavet, med fjellene bak. Montepulciano kan bli mørk rødvin eller kirsebærrosa Cerasuolo, avhengig av hvor lenge mosten ligger med skallene. Innenlands har sauene og veiene de fulgte satt spor både i maten og i rikdommen til fjellbyene.",
   landmark:{name:'Rocca Calascio og Gran Sasso', desc:'En festning fra 900-tallet på 1 460 meter, den høyeste i Appenninene, under Corno Grande på 2 912 meter.'},
   pairing:'Cerasuolo til arrosticini rett fra grillen; Montepulciano til spaghetti alla chitarra e pallottine.',
   lessons:["Montepulciano: druen, ikke byen","Cerasuolo og Adriaterhavets rosé","Arrosticini og gjeterkjøkkenet","Gran Sasso og fjellfestningene"]},
 'IT-67':{intro:"Molise er lett å overse på kartet, men gjennom regionen gikk veier for store saueflokker. Osten og det konserverte svinekjøttet hører til dette jordbrukslandskapet. I vinmarkene har Tintilia kommet tilbake etter nesten å ha forsvunnet. Eldre spor finnes også, blant annet navn risset i leire ved en samnittisk helligdom.",
   landmark:{name:'Castello Monforte, Campobasso', desc:'Et slott fra normannertiden, gjenoppbygd i 1458, som våker over regionhovedstaden og drifteveiene nedenfor.'},
   pairing:'Tintilia til cavatelli al ragù di agnello og et stykke caciocavallo.',
   lessons:["En region gjenoppdaget","Tintilia: en drue reddet fra utryddelse","Caciocavallo og drifteveiene","Campobasso og åslandsbyene"]},
 'IT-72':{intro:"Kysten og åsene innenlands i Campania gir ulike viner. Sanden bidrar til å forklare de gamle upodede vinrankene nær Napoli, mens leire og kalkstein preger voksestedene lenger inne. I byen bakes deig i varme ovner, og bøffelmelk blir til ost. Funnene rundt Vesuv viser også hva folk spiste før utbruddet.",
   landmark:{name:'Vesuv og Pompeii', desc:'Vulkanen som med utbruddet i år 79 bevarte Pompeii, ruver fortsatt over Napolibukta; på skråningene dyrkes Lacryma Christi.'},
   pairing:'Falanghina til pizza margherita og fritert sjømat; Taurasi til ragù napoletano.',
   lessons:["Vulkansk jord og eldgamle druer","Taurasi, Fiano og Greco","Pizza, mozzarella og det napolitanske bordet","Vesuv, Pompeii og Amalfikysten"]},
 'IT-75':{intro:"Puglia har lenge dyrket hvete, oliven og druer for markeder langt borte. På kjøkkenet hjemme blir avlingene til brød, pasta og retter med olivenolje. Steinen som ble ryddet fra jordene, ble brukt til murer og hus. I dag påvirker vernebestemmelser for trær, brød og bygninger hva folk kan fortsette å lage.",
   landmark:{name:'Trulli i Alberobello og Castel del Monte', desc:'Kjegleformede tørrmurshus, over 1 500 av dem i Alberobello, og Fredrik IIs gåtefulle åttekantede slott fra 1240.'},
   pairing:'Salento-rosato til orecchiette con cime di rapa; Primitivo til braciole og grillet lam.',
   lessons:["Oliven, sol og Salento","Primitivo og Negroamaro","Orecchiette, burrata og brødet fra Altamura","Trulli, slott og Adriaterhavet"]},
 'IT-77':{intro:"I Basilicata venter vinbøndene i Vulture-skråningene langt utover høsten på at Aglianico skal modne. Lenger sør tørkes paprika i lenker før et kort opphold i varm olje gjør dem sprø. I Matera ble rom som var hogd inn i fjellet, brukt som boliger. Senere ble de tømt og tatt i bruk til andre formål.",
   landmark:{name:'Sassi di Matera', desc:'Huleboliger hugget inn i en kalksteinsravine, bebodd i 9 000 år og på UNESCOs verdensarvliste siden 1993.'},
   pairing:'Aglianico del Vulture til lucanica-pølse og pane di Matera gnidd med peperoni cruschi.',
   lessons:["Vulture: vin på en vulkan","Aglianico, Sør-Italias Barolo","Peperoni cruschi og brødet fra Matera","Matera: hulebyen"]},
 'IT-78':{intro:"Calabria ligger mellom to hav, med fjell like bak kysten. Et glass lys Cirò kan ha mer tannin enn fargen tyder på. På kjøkkenet blandes chili i svinekjøtt, men salt, tørking og røyk gjør mye av konserveringsarbeidet. Greske kulturminner og et levende gresk språk knytter ulike deler av regionen til fortiden.",
   landmark:{name:'Tropea og Santa Maria dell\'Isola', desc:'En by på klippekanten over hvit sand, med en klosterkirke på sin egen klippe i havet, bysantinsk lenge før benediktinerne fikk den.'},
   pairing:'Cirò Rosso til fileja og \'nduja; Greco di Bianco til fiken- og mandelsøtsaker.',
   lessons:["Magna Graecia, og hva grekerne etterlot seg","Gaglioppo og Cirò","'Nduja, chili og det calabriske spiskammeret","Tropea og Costa degli Dei"]},
 'IT-82':{intro:"På Sicilia krever en vinmark på Etna og en kjeller i Marsala ulike forklaringer. På Etna betyr høyden og vulkanens skiftende grunn mye. I Marsala tilsettes vinen alkohol og lagres. På kjøkkenet er spørsmålene like konkrete: hvordan risen holder sammen, hvorfor auberginene stekes, og når en cannolo skal fylles.",
   landmark:{name:'Etna og Tempeldalen', desc:'Etnas vulkanske landskap og de greske templene ved Agrigento.'},
   pairing:'Etna Bianco til pasta alla Norma; Nero d\'Avola til grillet sverdfisk; Passito til cannoli.',
   lessons:["Etna: vinranker på en levende vulkan","Nero d'Avola, Grillo og Marsala","Ris, auberginer og det sicilianske kjøkkenet","Templer, normannere og barokk"]},
 'IT-88':{intro:"Sardegna lager mesteparten av Italias Pecorino Romano. I mindre mengder lages også oster som Fiore Sardo, der ostemassen av rå melk røykes og lagres. Fra kysten til innlandet forandrer både jordsmonnet og språket seg. Brødet, vinen og de gamle steintårnene gir flere veier inn i historien til øya.",
   landmark:{name:'Nuraghe Su Nuraxi, Barumini', desc:'Et tørrmurt tårn av stablede kraggehvelv med en landsby omkring, den fineste av Sardinias nuragher.'},
   pairing:'Vermentino di Gallura til fregola ai frutti di mare; Cannonau til porceddu og pecorino sardo.',
   lessons:["Havnene og innlandet","Fire viner, fire bergarter","Mat som måtte holde seg","Tårnene og språket"]},
};
