/* Italia in Tavola — norske regionsammendrag. Region- og hovedstadsnavn beholdes på italiensk. */
window.COURSE_NO = {
 'IT-23':{intro:"Italias minste region klatrer fra elven Dora Baltea opp mot Matterhorn og Mont Blanc. Vinrankene klamrer seg til terrasser i opptil 1 200 meters høyde, og kjøkkenet er bygget på smør, rugbrød og fjellost.",
   landmark:{name:'Castello di Fénis og Matterhorn', desc:'Et eventyrslott fra middelalderen som vokter dalen, med Cervino (Matterhorn) som reiser seg 4 478 meter i enden av dalen.'},
   pairing:'Et glass Torrette til carbonada, den langkokte oksegryten som serveres over polenta.',
   lessons:["Europas høyeste vinmarker","Alpine hvitviner og fjellrødviner","Fontina og bordet i Alpene","Slottene i Aostadalen"]},
 'IT-21':{intro:"Ved foten av fjellene: tåkelagte Langhe-åser der Nebbiolo blir til Barolo og Barbaresco, hvit trøffel fra Alba, og en kafékultur i Torino som ga verden vermut og gianduja.",
   landmark:{name:'Mole Antonelliana, Torino', desc:'Spiret på 167 meter som definerer Torinos silhuett, påbegynt i 1863 som synagoge og i dag nasjonalt filmmuseum.'},
   pairing:'Barolo til brasato al Barolo, eller en ung Barbera til tajarin med smør og revet hvit trøffel.',
   lessons:["Nebbiolo og Langhe-åsene","Barolo og Barbaresco, landsby for landsby","Trøffel, tajarin og bagna cauda","Torino: vermut, sjokolade og Mole"]},
 'IT-42':{intro:"En smal halvmåne av kyst klemt mellom hav og fjell. Terrasserte vinmarker henger over Cinque Terre, basilikum vokser i hver vinduskarm, og Genovas havn har handlet med krydder og olivenolje i tusen år.",
   landmark:{name:'Lanterna di Genova og Cinque Terre', desc:'Fyrtårnet på 77 meter har ledet skip inn til Genova siden 1543; lenger øst klamrer fem pastellfargede landsbyer seg til klippene.'},
   pairing:'Kald Vermentino til trofie al pesto, eller Sciacchetrà til en skive pandolce etter middagen.',
   lessons:["Vinranker på klippene","Vermentino, Pigato og havet","Pesto, focaccia og oliven","Genova: kjøkkenet i en sjøfartsrepublikk"]},
 'IT-25':{intro:"Italias økonomiske motor er også et landskap av rismarker, alpesjøer og Franciacortas musserende vin laget etter tradisjonell metode. Milanos matlaging er rik på smør, safran og beinmarg.",
   landmark:{name:'Duomo di Milano', desc:'Marmorkatedralen tok seks hundre år å fullføre og bugner av 135 spir og 3 400 statuer, kronet av den gylne Madonnina.'},
   pairing:'Franciacorta Satèn til risotto alla milanese; Sforzato di Valtellina til pizzoccheri.',
   lessons:["Franciacorta: Italias svar på champagne","Nebbiolo i Alpene: Valtellina","Safranrisotto og det milanesiske bordet","Domkirken og designbyen"]},
 'IT-32':{intro:"To kulturer deler én alperegion: italiensktalende Trentino og tysktalende Südtirol. Aromatiske hvitviner vokser under de bleke Dolomitt-toppene, og speck, melboller og strudel kommer fra den østerrikske siden av spiskammeret.",
   landmark:{name:'Dolomittene', desc:'Bleke kalksteinstårn som gløder rosa i solnedgangen, et UNESCO-verdensarvsted som reiser seg over vinmarker og eplehager.'},
   pairing:'Gewürztraminer til speck og oster fra Alto Adige; Lagrein til vilt og canederli.',
   lessons:["Vinmarker mellom to kulturer","Gewürztraminer, Lagrein og det aromatiske nord","Speck, melboller og strudel","Dolomittene: fjell av stein og lys"]},
 'IT-34':{intro:"Fra Venezias lagune til Veronas amfiteater: Veneto er Italias største vinprodusent. Prosecco perler i åsene ved Valdobbiadene, mens Amarone lages av druer tørket på stråmatter.",
   landmark:{name:'Venezia: Campanile di San Marco', desc:'Klokketårnet på 99 meter over Piazza San Marco, gjenreist i 1912 etter at originalen raste sammen; gondolene glir forbi nedenfor.'},
   pairing:'Soave til risi e bisi; Amarone til lagret Asiago eller en langkokt pastissada de caval.',
   lessons:["Valpolicella og kunsten å tørke druer","Prosecco: fra åsene til glasset","Cicchetti og den venetianske bàcaro","Venezia: en republikk bygget på handel"]},
 'IT-36':{intro:"Der Italia møter Slovenia og Østerrike. Friulis hvitviner er blant landets fineste, San Daniele tørker skinken sin i brisen mellom Alpene og havet, og kafeene i Trieste føles fortsatt habsburgske.",
   landmark:{name:'Castello di Miramare, Trieste', desc:'Et hvitt slott bygget i 1860 for erkehertug Maximilian på et klippenes over Adriaterhavet.'},
   pairing:'Friulano til prosciutto di San Daniele; Refosco til frico og polenta.',
   lessons:["Collio og de store italienske hvitvinene","Friulano, Ribolla og oransjevin","San Daniele, frico og det karniske kjøkkenet","Trieste: kaffe, habsburgere og bora-vinden"]},
 'IT-45':{intro:"Italias matdal. Parmigiano Reggiano, prosciutto di Parma, balsamicoeddik fra Modena og fersk eggpasta kommer alle fra den flate Po-sletten, skylt ned med perlende, munter Lambrusco.",
   landmark:{name:'De to tårnene, Bologna', desc:'Asinelli (97 m) og det skjeve nabotårnet Garisenda, middelalderske familietårn som fortsatt rager over byen med buegangene.'},
   pairing:'Tørr Lambrusco til et brett med salumi og Parmigiano; Sangiovese di Romagna til tagliatelle al ragù.',
   lessons:["Lambrusco, riktig forstått","Sangiovese på Romagna-siden","Parmigiano, prosciutto og balsamico: tre beskyttede skatter","Bologna la Grassa og sfogliaen"]},
 'IT-52':{intro:"Sypressåser, renessansebyer og Sangiovese i alle former: Chianti Classico, Brunello di Montalcino, Vino Nobile. Matlagingen er stolt bondekost: brød, bønner, olivenolje og en tykk florentinsk biff.",
   landmark:{name:'Det skjeve tårnet i Pisa og Brunelleschis kuppel', desc:'Pisas klokketårn har hellet siden 1170-tallet; i Firenze er Brunelleschis kuppel fra 1436 fortsatt den største murkuppelen som noen gang er bygget.'},
   pairing:'Chianti Classico til bistecca alla fiorentina; Vin Santo til cantucci som dyppes i glasset.',
   lessons:["Sangiovese: én drue, mange ansikter","Chianti Classico og den svarte hanen","Brunello, Nobile og supertoskanerne","Brød, bønner og den florentinske biffen"]},
 'IT-55':{intro:"Italias grønne hjerte, den eneste regionen på halvøya uten kyst. Assisi og Orvieto kroner åsene, svart trøffel gjemmer seg ved Norcia, og Sagrantino er en av Italias mest tanninrike rødviner.",
   landmark:{name:'Basilica di San Francesco, Assisi', desc:'To kirker oppå hverandre, bygget fra 1228 over graven til den hellige Frans, med fresker av Giotto og Cimabue.'},
   pairing:'Sagrantino til lammestek eller lagret pecorino; Orvieto til strangozzi al tartufo nero.',
   lessons:["Vinmarken uten kyst","Sagrantino: Italias mest tanninrike rødvin","Norcia: trøffel, salumi og norcinoen","Assisi og åsbyene"]},
 'IT-57':{intro:"Adriaterhavsstrender, Sibillini-fjellene og renessansebyen Urbino. Verdicchio er en av Italias store lagringsdyktige hvitviner, og kysten koker en brodetto på tretten fiskeslag.",
   landmark:{name:'Palazzo Ducale, Urbino', desc:'Renessansepalasset til hertug Federico da Montefeltro, med to slanke tårn over den murkransede åsbyen.'},
   pairing:'Verdicchio til brodetto all\'anconetana; Rosso Conero til vincisgrassi.',
   lessons:["Verdicchio: en hvitvin som eldes som en rødvin","Montepulciano på Conero","Ascoli-oliven og Adriaterhavets brodetto","Urbino og idealbyen"]},
 'IT-62':{intro:"Roma ligger i sentrum: Colosseum, Forum og et fattigmannskjøkken av pecorino, guanciale og pasta som ble hele verdens favoritt. I Castelli Romani-åsene har Frascati vært byens hvitvin i århundrer.",
   landmark:{name:'Colosseum og Peterskirken, Roma', desc:'Det flaviske amfiteateret, ferdig i år 80, hadde plass til rundt 50 000 tilskuere til leker og skuespill.'},
   pairing:'Frascati til carciofi alla giudia; Cesanese til abbacchio alla romana eller amatriciana.',
   lessons:["Castelli Romani og Frascati","Cesanese: Lazios glemte rødvin","De fire romerske pastarettene","Roma: Colosseum og det evige bordet"]},
 'IT-65':{intro:"Fjellvillmark over, Adriaterhavet under. Bjørn og ulv streifer i nasjonalparken Gran Sasso, gjetere griller arrosticini over glør, og Montepulciano d'Abruzzo er hverdagsrødvinen i halve landet.",
   landmark:{name:'Rocca Calascio og Gran Sasso', desc:'En festning fra 900-tallet på 1 460 meter, den høyeste i Apenninene, under Corno Grande på 2 912 meter.'},
   pairing:'Cerasuolo til arrosticini rett fra grillen; Montepulciano til spaghetti alla chitarra e pallottine.',
   lessons:["Montepulciano: druen, ikke byen","Cerasuolo og Adriaterhavets rosé","Arrosticini og gjeterkjøkkenet","Gran Sasso og fjellfestningene"]},
 'IT-67':{intro:"Italias yngste og minst besøkte region, skilt fra Abruzzo i 1963. Eldgamle drifteveier for sau (tratturi) krysser åsene, Tintilia er den lokale rødvinsdruen, og ostene heter caciocavallo og scamorza.",
   landmark:{name:'Castello Monforte, Campobasso', desc:'Et slott fra normannertiden, gjenoppbygd i 1458, som våker over regionhovedstaden og drifteveiene nedenfor.'},
   pairing:'Tintilia til cavatelli al ragù di agnello og et stykke caciocavallo.',
   lessons:["En region gjenoppdaget","Tintilia: en drue reddet fra utryddelse","Caciocavallo og drifteveiene","Campobasso og åslandsbyene"]},
 'IT-72':{intro:"Napoli fant opp pizzaen, Vesuv begravde Pompeii, og i den vulkanske jorden vokser eldgamle druer: Aglianico til Taurasi, Fiano og Greco til hvitvin. Bøffelmozzarella, San Marzano-tomater og sitroner fullfører bildet.",
   landmark:{name:'Vesuv og Pompeii', desc:'Vulkanen som med utbruddet i år 79 bevarte Pompeii, ruver fortsatt over Napolibukta; på skråningene dyrkes Lacryma Christi.'},
   pairing:'Falanghina til pizza margherita og fritert sjømat; Taurasi til ragù napoletano.',
   lessons:["Vulkansk jord og eldgamle druer","Taurasi, Fiano og Greco","Pizza, mozzarella og det napolitanske bordet","Vesuv, Pompeii og Amalfikysten"]},
 'IT-75':{intro:"Hælen på støvelen er en solsvidd slette av oliventrær (40 % av Italias olje), hvitkalkede trulli og Primitivo- og Negroamaro-ranker. Burrata ble oppfunnet her, og pastaen formes for hånd til små ører.",
   landmark:{name:'Trulli i Alberobello og Castel del Monte', desc:'Kjegleformede tørrmurshus, over 1 500 av dem i Alberobello, og Fredrik IIs gåtefulle åttekantede slott fra 1240.'},
   pairing:'Salento-rosato til orecchiette con cime di rapa; Primitivo til braciole og grillet lam.',
   lessons:["Oliven, sol og Salento","Primitivo og Negroamaro","Orecchiette, burrata og brødet fra Altamura","Trulli, slott og Adriaterhavet"]},
 'IT-77':{intro:"Kupert, fjellrik og en gang lutfattig; i dag kjent for hulebyen Matera og Aglianico del Vulture, dyrket på en utdødd vulkan. Sprø, tørkede paprika krydrer nesten alt.",
   landmark:{name:'Sassi di Matera', desc:'Huleboliger hugget inn i en kalksteinsravine, bebodd i 9 000 år og på UNESCOs verdensarvliste siden 1993.'},
   pairing:'Aglianico del Vulture til lucanica-pølse og pane di Matera gnidd med peperoni cruschi.',
   lessons:["Vulture: vin på en vulkan","Aglianico, Sør-Italias Barolo","Peperoni cruschi og brødet fra Matera","Matera: hulebyen"]},
 'IT-78':{intro:"Tåen på Italia, voldsomt krydret og gresk i røttene. 'Nduja, rødløk fra Tropea, bergamott og lakris kommer alle herfra, og Cirò er en av verdens eldste viner.",
   landmark:{name:'Tropea og Santa Maria dell\'Isola', desc:'En by på klippekanten over hvit sand, med et benediktinerkloster på sin egen klippe i havet.'},
   pairing:'Cirò Rosso til fileja og \'nduja; Greco di Bianco til fiken- og mandelsøtsaker.',
   lessons:["Magna Graecia og den eldste vinmarken","Gaglioppo og Cirò","'Nduja, chili og det kalabriske spiskammeret","Tropea og Costa degli Dei"]},
 'IT-82':{intro:"Middelhavets største øy har vært gresk, arabisk, normannisk og spansk, og kjøkkenet viser det: couscous, sitrus, pistasj, cannoli. Etnas vulkanske vinmarker gir noen av Italias mest spennende viner.",
   landmark:{name:'Etna og Tempeldalen', desc:'Europas mest aktive vulkan (3 357 m) og, ved Agrigento, de best bevarte greske templene utenfor Hellas.'},
   pairing:'Etna Bianco til pasta alla Norma; Nero d\'Avola til grillet sverdfisk; Passito til cannoli.',
   lessons:["Etna: vinranker på en levende vulkan","Nero d'Avola, Grillo og Marsala","Arabisk Sicilia: sitrus, sukker og gatemat","Templer, normannere og barokken"]},
 'IT-88':{intro:"En øy for seg selv, med eget språk og 7 000 steintårn fra bronsealderen. Gjetere steker pattegris, baker papirtynt carasau-brød og lager pecorino; Cannonau og Vermentino er de to store druene.",
   landmark:{name:'Nuraghe Su Nuraxi, Barumini', desc:'En 3 500 år gammel steinfestning med et sentraltårn og en landsby, den fineste av Sardinias nuragher.'},
   pairing:'Vermentino di Gallura til fregola ai frutti di mare; Cannonau til porceddu og pecorino sardo.',
   lessons:["En øy av gjetere og vinranker","Cannonau og Vermentino","Porceddu, carasau og gjeterbordet","Nuragher: bronsealderens tårn"]},
};
