// Abruzzo recipes. Contract: docs/recipe-format.md. Both languages in one file; never narrated.
// Everything here follows the region's own readings (content/abruzzo.js): the shepherds' fornacella and
// castrato in lesson 3, the chitarra and Teramo's pallottine and scrippelle in the same lesson, and the
// layered, unstirred terracotta brodetto of Vasto in lesson 2.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-65'] = [

{
  id:'arrosticini', dish:'Arrosticini', course:'secondo', lesson:3, serves:4, time:{prep:40, cook:10},
  hero:'arrosticini', tags:['grill','mutton','skewers','charcoal'],
  title:{en:'Arrosticini', no:'Arrosticini'},
  blurb:{en:'Cubes of mutton on thin wooden skewers over a narrow charcoal trough. Four minutes over the coals, and nobody eats three.',
         no:'Terninger av fårekjøtt på tynne trespyd over en smal trekullrenne. Fire minutter over glørne, og ingen spiser tre.'},
  heroCaption:{en:'Arrosticini before the fire: meat and fat threaded alternately, counted out in bundles of fifty.',
               no:'Arrosticini før grillen: kjøtt og fett tredd vekselvis på spyd, talt opp i bunter på femti.'},
  wines:['Cerasuolo d\'Abruzzo'],
  headnote:{
    en:'<p>Arrosticini belong to the shepherds of the Gran Sasso. The region tells a story of two men in the hills between L\'Aquila, Teramo and Pescara in about 1830, cutting up an animal too old to sell and finding a use for every scrap, including the meat closest to the bone. True or not, the dish comes out of <strong>transhumance</strong>, the seasonal walk of the flocks south to Puglia along the <em>tratturi</em> and back again in spring, and it is built the way that life allowed: one meat, one fire, no pot.</p>'
      + '<p>The fire is the recipe. A <strong>fornacella</strong> is a long charcoal trough barely wider than the meat, so the skewers lie across it with the cubes over the coals and the wooden ends out in the air on both sides, where they cannot catch. The meat sits close over a fierce bed of embers and is done in three or four minutes, turned constantly. That is why the cubes are small, and why a piece of fat rides between them: the fat melts and runs down over the lean before the lean has time to dry.</p>'
      + '<p>The meat is the one thing not to swap. The tradition is <em>castrato</em>, a castrated ram, or plain older sheep, animals with enough fat and enough flavour to stand up to charcoal. Lamb makes a pleasant skewer and a different dish. Salt goes on as the skewers come off the fire, never before, and the only accompaniment is bread soaked in olive oil, held under the skewer to catch what drips.</p>',
    no:'<p>Arrosticini hører til gjeterne på Gran Sasso. Regionen forteller om to menn i åsene mellom L\'Aquila, Teramo og Pescara rundt 1830 som skar opp et dyr som var for gammelt til å selges, og fant bruk for hver bit, også kjøttet nærmest beinet. Enten historien er sann eller ikke, hører retten hjemme i den verdenen <strong>transhumansen</strong> skapte, den årlige vandringen der flokkene gikk sørover til Puglia langs <em>tratturi</em> og kom tilbake om våren. Retten er bygget slik det livet tillot: ett slags kjøtt, én ild, ingen gryte.</p>'
      + '<p>Ilden er selve oppskriften. En <strong>fornacella</strong> er en lang trekullrenne som så vidt er bredere enn kjøttet, slik at spydene ligger på tvers med terningene over glørne og treendene fritt ute i luften på begge sider, der de ikke kan ta fyr. Kjøttet ligger tett over en kraftig glo og blir ferdig på tre–fire minutter mens det snus hele tiden. Derfor er terningene små, og derfor sitter det en bit fett mellom dem: fettet smelter og renner ned over det magre kjøttet før det rekker å tørke ut.</p>'
      + '<p>Kjøttet er det eneste du ikke bør bytte ut. Tradisjonen er <em>castrato</em>, altså kastrert vær, eller ganske enkelt eldre sau. Slike dyr har nok fett og nok smak til å tåle trekull. Lammekjøtt gir et hyggelig spyd og en annen rett. Smaken blir mildere, og kjøttet tørker fortere. Saltet kommer på når spydene tas av ilden, aldri før, og det eneste tilbehøret er brød dyppet i olivenolje, holdt under spydet for å fange opp det som drypper.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:800, u:'g', n:{en:'boneless mutton', no:'fårekjøtt uten bein'},
     note:{en:'leg or shoulder of an older sheep, not lamb. In Norway ask the butcher for sauelår or saubog; castrato, a castrated ram, is rarely sold there',
           no:'lår eller bog av eldre sau, altså fårekjøtt og ikke lammekjøtt. Be slakteren om sauelår eller saubog. Castrato, kastrert vær, selges sjelden i Norge'}},
    {q:200, u:'g', n:{en:'sheep fat', no:'saufett'},
     note:{en:'the fat you trim off the joint, or a piece from the butcher; lamb fat will do', no:'fettet du skjærer av steken, eller et stykke fra slakteren; lammefett går også'}},
    {q:40, u:'', n:{en:'thin wooden skewers', no:'tynne trespyd'},
     note:{en:'about 25 cm long; ten a head is an ordinary helping', no:'rundt 25 cm lange; ti per person er en vanlig porsjon'}, round:'half'},
    {u:'', n:{en:'fine salt', no:'fint salt'}, scale:'none'},
    {q:250, u:'g', n:{en:'country bread', no:'grovt landbrød'},
     note:{en:'in thick slices, to hold under the skewers', no:'i tykke skiver, til å holde under spydene'}},
    {q:60, u:'ml', n:{en:'extra-virgin olive oil', no:'extra virgin olivenolje'}},
    {u:'', n:{en:'charcoal', no:'trekull'},
     note:{en:'lump charcoal, not briquettes with a starter in them', no:'rent trekull, ikke briketter med tennvæske i'}, scale:'none'},
  ]}],
  steps:[
    {en:'Soak the wooden skewers in cold water for half an hour so the ends do not char.',
     no:'Legg trespydene i kaldt vann i en halvtime, så endene ikke forkuller.'},
    {en:'Chill the meat until it is firm but not frozen. Cold meat cuts into clean little cubes; meat at room temperature tears instead.',
     no:'Sett kjøttet kaldt til det er fast, men ikke frossent. Kaldt kjøtt lar seg skjære i rene, små terninger, mens lunkent kjøtt rives opp.'},
    {en:'Trim the fat off the meat and keep it. Cut the lean into cubes of about 1 cm.',
     no:'Skjær fettet av kjøttet og ta vare på det. Skjær det magre i terninger på rundt 1 cm.'},
    {en:'Cut the fat into slightly smaller cubes, so it melts before the meat is done.',
     no:'Skjær fettet i litt mindre terninger, slik at det smelter før kjøttet er ferdig.'},
    {en:'Thread four or five cubes of lean onto each skewer with a cube of fat after every second one, and push them tight together.',
     no:'Tre fire eller fem terninger magert kjøtt på hvert spyd, med en fettbit etter annenhver, og skyv dem tett sammen.'},
    {en:'Lay the finished skewers flat, cover them and keep them cold until the fire is ready.',
     no:'Legg de ferdige spydene flatt, dekk dem til, og hold dem kalde til ilden er klar.'},
    {en:'Light the charcoal and let it burn down until the flames are gone and the coals glow grey. Rake them into a narrow strip no wider than the meat.',
     no:'Tenn trekullet og la det brenne ned til flammene er borte og glørne ligger grå av varme. Rak dem sammen til en smal stripe som ikke er bredere enn kjøttet.'},
    {en:'Lay the skewers across the strip so the meat sits over the coals and the wooden ends hang clear on both sides.',
     no:'Legg spydene på tvers av stripen, slik at kjøttet ligger over glørne og treendene stikker fritt ut på begge sider.'},
    {en:'Turn them every twenty seconds or so. They are done in three or four minutes, when the fat has melted and the edges are brown but the middle is still pink.',
     no:'Snu dem omtrent hvert tjuende sekund. De er ferdige etter tre–fire minutter, når fettet har smeltet og kantene er brune, mens midten fortsatt er rosa.'},
    {en:'Salt them as they come off the fire and stand them upright in a jug or a tall glass.',
     no:'Salt dem når de tas av ilden, og sett dem stående i en mugge eller et høyt glass.'},
    {en:'Serve at once with bread dipped in olive oil, held under the skewer so it catches what runs off.',
     no:'Server dem med en gang, med brød dyppet i olivenolje som holdes under spydet for å fange opp det som renner av.'},
  ],
  notes:[
    {title:{en:'Why the cubes are so small', no:'Hvorfor terningene er så små'},
     body:{en:'A cube of about a centimetre has enough surface to brown all over in the time the middle needs to warm through. Anything bigger forces a choice between a raw centre and a burnt crust over a fire this fierce, which is why the skewer carries many little pieces rather than three good ones, and why the whole thing is over in minutes.',
           no:'En terning på rundt en centimeter har nok overflate til å bli brun over det hele på den tiden midten trenger for å bli varm. Større biter tvinger fram et valg mellom rå kjerne og brent skorpe over en så kraftig ild. Derfor bærer spydet mange små biter og ikke tre store, og derfor er alt over på noen minutter.'}},
    {title:{en:'The fat does the basting', no:'Fettet holder kjøttet saftig'},
     body:{en:'Sheep lean has almost no marbling in it, so it dries out within seconds of being cooked. A cube of fat every second piece melts well below the temperature the meat needs and runs down over it as the skewer turns. Leave the fat out and the skewers come off dry however carefully you watch them.',
           no:'Magert sauekjøtt har nesten ingen fettmarmorering, og det tørker ut sekunder etter at det er ferdig. En fettbit etter annenhver kjøttbit smelter godt under den temperaturen kjøttet trenger, og renner ned over det mens spydet snus. Utelater du fettet, blir spydene tørre uansett hvor nøye du følger med.'}},
    {title:{en:'A fire only as wide as the meat', no:'En ild bare så bred som kjøttet'},
     body:{en:'The trough is barely wider than the cubes, and that does two things at once. Every coal sits under meat, so the heat is concentrated and the skewers cook in minutes rather than drying slowly over a broad bed. And the wooden ends rest over cool air on both sides, so they never burn through and you can turn forty skewers with your fingers.',
           no:'Rennen er så vidt bredere enn terningene, og det gjør to ting på én gang. Hver glo ligger under kjøtt, så varmen blir konsentrert og spydene blir ferdige på minutter i stedet for å tørke langsomt over et bredt kullag. Og treendene ligger over kald luft på begge sider, så de brenner aldri av, og du kan snu førti spyd med fingrene.'}},
  ],
  variations:[
    {title:{en:'Without a fornacella', no:'Uten fornacella'},
     body:{en:'Rake the coals of an ordinary kettle grill into a strip down the middle and lay two bricks or two folded rails of foil along the sides, so the skewers rest across the gap with their ends out of the heat. Indoors, a ridged cast-iron pan taken to smoking point is the fallback; it browns the meat properly, and only the charcoal is missing.',
           no:'Rak glørne i en vanlig kullgrill sammen til en stripe midt i, og legg to teglstein eller to sammenbrettede skinner av folie langs sidene, slik at spydene hviler over åpningen med endene utenfor varmen. Innendørs kommer du nærmest med en rillet støpejernspanne som varmes til den ryker. Den bruner kjøttet ordentlig, og det er bare trekullet som mangler.'}},
    {title:{en:'Lamb, where mutton is not sold', no:'Lam, der fårekjøtt ikke selges'},
     body:{en:'Lamb is the usual substitute outside Abruzzo, and it works: the technique is identical. Expect a milder, sweeter skewer that dries a little faster, so cut the cubes no smaller and give them slightly less time. Hogget, a sheep in its second year, is the closest thing to castrato most butchers can offer.',
           no:'Lam er den vanlige erstatningen utenfor Abruzzo, og det fungerer, for teknikken er den samme. Regn med et mildere og søtere spyd som tørker litt fortere. Skjær derfor ikke terningene mindre, og gi dem litt kortere tid over glørne. Av det de fleste slaktere kan skaffe, ligger kjøtt fra sau i sitt andre år nærmest castrato.'}},
    {title:{en:'What goes with them', no:'Hva som hører til'},
     body:{en:'Bread and oil, and nothing else on the plate. Cerasuolo d\'Abruzzo is the regional answer in the glass, poured cool at around 12 °C, with enough body and tannin to meet grilled fat. A board of ventricina and young pecorino before the fire is lit finishes the meal in the right order.',
           no:'Brød og olje, og ingenting annet på tallerkenen. Cerasuolo d\'Abruzzo er regionens svar i glasset, skjenket kjølig ved rundt 12 °C, med nok fylde og tannin til å møte grillet fett. Server et fat med ventricina og ung pecorino mens ilden tar seg opp, så kommer måltidet i riktig rekkefølge.'}},
  ],
},

{
  id:'spaghetti-alla-chitarra', dish:'Spaghetti alla chitarra', course:'base', lesson:3, serves:4, time:{prep:70, cook:3},
  hero:'chitarra2', tags:['pasta','egg','fresh pasta'],
  title:{en:'Spaghetti alla chitarra', no:'Spaghetti alla chitarra'},
  blurb:{en:'Egg pasta pressed through the steel wires of a wooden frame. The strand comes out square, and the square is the whole point.',
         no:'Eggpasta presset gjennom stålstrengene i en treramme. Tråden kommer ut firkantet, og det firkantede er hele poenget.'},
  heroCaption:{en:'Fresh spaghetti alla chitarra: flat faces, sharp corners and a rough surface, here under a white ragù.',
               no:'Fersk spaghetti alla chitarra: flate sider, skarpe hjørner og ru overflate, her under en hvit ragù.'},
  wines:['Montepulciano d\'Abruzzo'],
  headnote:{
    en:'<p>Abruzzo\'s pasta is named after the tool that cuts it. A <strong>chitarra</strong> is a shallow wooden box strung with steel wires. A sheet of egg pasta is laid over the wires and pressed through with a rolling pin, and the box underneath resonates as the strands drop into it, which is where the guitar comes from.</p>'
      + '<p>The wires cut instead of squeezing, and there lies the difference from a machine with rollers. A strand off a chitarra keeps the thickness of the sheet on two sides and the spacing of the wires on the other two, so it comes out square, with flat faces, four sharp corners and the rough surface of hand-rolled dough. A sauce holds on to all of it. Match the sheet to the wires: roll it about as thick as the gap between them, or the strand comes out as a ribbon.</p>'
      + '<p>The dough is the plain Abruzzese one, an egg to every hundred grams of flour, a pinch of salt and nothing else, with hard durum flour in it for bite. Knead it properly and rest it properly, or it will fight the rolling pin and tear on the wires. In Teramo the classic dressing is <strong>pallottine</strong>, meatballs the size of a hazelnut in tomato sauce, and those have a recipe of their own alongside this one.</p>',
    no:'<p>Pastaen i Abruzzo har navn etter redskapet som skjærer den. En <strong>chitarra</strong> er en grunn trekasse med stålstrenger over. En plate eggpasta legges på strengene og presses gjennom med kjevlen, og kassen under gir gjenklang når trådene faller ned i den. Derfor heter den gitar.</p>'
      + '<p>Strengene skjærer i stedet for å klemme, og der ligger forskjellen fra en maskin med valser. En tråd fra en chitarra beholder tykkelsen på deigplaten på to sider og avstanden mellom strengene på de to andre. Derfor blir den firkantet, med flate sider, fire skarpe hjørner og den ru overflaten håndkjevlet deig har. Sausen henger fast i alt sammen. Deigplaten må passe til strengene, så kjevle den omtrent like tykk som avstanden mellom dem, ellers kommer tråden ut som et bånd.</p>'
      + '<p>Deigen er den vanlige abruzzesiske, ett egg per hundre gram mel, en klype salt og ingenting annet, med hard durumhvete i for tyggemotstand. Elt den skikkelig og la den hvile skikkelig, ellers kjemper den mot kjevlen og revner på strengene. I Teramo er det klassiske tilbehøret <strong>pallottine</strong>, kjøttboller på størrelse med en hasselnøtt i tomatsaus, og de har sin egen oppskrift ved siden av denne.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:300, u:'g', n:{en:'semola rimacinata', no:'semola rimacinata'},
     note:{en:'finely milled hard durum flour', no:'finmalt durumhvete'}},
    {q:100, u:'g', n:{en:'plain white flour', no:'hvetemel'}, note:{en:'Italian 00 if you have it', no:'italiensk 00 hvis du har det'}},
    {q:4, u:'', n:{en:'eggs', no:'egg'}, note:{en:'large, at room temperature', no:'store, med romtemperatur'}, round:'half'},
    {u:'', n:{en:'salt for the dough', no:'salt i deigen'}, note:{en:'a pinch', no:'en klype'}, scale:'none'},
    {q:30, u:'g', n:{en:'coarse semolina for dusting', no:'grovt semulegryn til drysting'},
     note:{en:'so the strands do not stick to each other', no:'så trådene ikke klistrer seg sammen'}, scale:'none'},
    {q:4, u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:20, u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
  ]}],
  steps:[
    {en:'Mix the two flours on a board and make a well in the middle of the heap.',
     no:'Bland de to meltypene på en fjøl og lag en brønn midt i haugen.'},
    {en:'Break the eggs into the well, add the salt, and beat them with a fork while you draw flour in from the sides a little at a time.',
     no:'Knekk eggene i brønnen, ha i saltet, og visp dem med en gaffel mens du drar mel inn fra sidene litt om gangen.'},
    {en:'Knead for ten minutes, pushing the dough away with the heel of your hand and folding it back, until it is smooth and springs back when you press it.',
     no:'Elt i ti minutter. Skyv deigen fra deg med håndballen og brett den tilbake, til den er glatt og spretter tilbake når du trykker på den.'},
    {en:'Wrap it and let it rest at room temperature for half an hour. Durum dough is stiff, and only after the rest will it roll thin.',
     no:'Pakk den inn og la den hvile i romtemperatur i en halvtime. Durumdeig er stiv, og først etter hvilen lar den seg kjevle tynn.'},
    {en:'Cut the dough into four and keep the pieces you are not working on under a cloth.',
     no:'Del deigen i fire, og hold de bitene du ikke arbeider med, under et klede.'},
    {en:'Roll each piece into a sheet as thick as the gap between the wires of the chitarra, which is a little thicker than you would roll for tagliatelle.',
     no:'Kjevle hver bit til en plate som er like tykk som avstanden mellom strengene på chitarraen, altså litt tykkere enn du ville kjevlet til tagliatelle.'},
    {en:'Trim the sheet to the length of the frame, so nothing hangs over the ends.',
     no:'Skjær platen til så den passer lengden på rammen, slik at ingenting henger utenfor endene.'},
    {en:'Lay it on the wires and run the rolling pin over it with steady pressure until the strands drop through into the box.',
     no:'Legg den på strengene og kjør kjevlen over den med jevnt trykk til trådene faller ned i kassen.'},
    {en:'Pluck the wires to shake down whatever is still hanging on them.',
     no:'Klimpre på strengene for å riste ned det som fortsatt henger igjen på dem.'},
    {en:'Toss the strands with the coarse semolina and gather them into loose nests on a floured cloth.',
     no:'Vend trådene i det grove semulegrynet og samle dem i løse reir på et melet klede.'},
    {en:'Boil them in well-salted water for two or three minutes, until they float and still have bite, and dress them straight away.',
     no:'Kok dem i godt saltet vann i to–tre minutter, til de flyter opp og fortsatt har tyggemotstand, og vend dem i sausen med en gang.'},
  ],
  notes:[
    {title:{en:'Thickness sets the width', no:'Tykkelsen bestemmer bredden'},
     body:{en:'The wires fix one dimension of the strand and the rolling pin fixes the other, so the two have to agree. A chitarra strung about 2 mm apart wants a sheet of about 2 mm. Roll it thinner and you get a flat ribbon that behaves like tagliatelle; roll it thicker and the wires cannot cut all the way through, so the sheet drags and tears.',
           no:'Strengene bestemmer det ene målet på tråden og kjevlen det andre, så de to må stemme overens. En chitarra med rundt 2 mm mellom strengene vil ha en plate på rundt 2 mm. Kjevler du tynnere, får du et flatt bånd som oppfører seg som tagliatelle, og kjevler du tykkere, klarer ikke strengene å skjære helt gjennom, så platen sleper og revner.'}},
    {title:{en:'Why durum and not only soft flour', no:'Hvorfor durum og ikke bare hvetemel'},
     body:{en:'Semola holds the shape the wires gave it. Its protein sets firmly in the water, so the corners stay sharp and the strand keeps a real bite after two minutes of boiling. A dough of soft flour alone is easier to roll and pleasant to eat, but the edges round off in the pot and the sauce has less to grip.',
           no:'Semola holder på formen strengene ga den. Proteinet stivner fast i vannet, så hjørnene holder seg skarpe og tråden beholder ordentlig tyggemotstand etter to minutter i kok. En deig av bare hvetemel er lettere å kjevle og god å spise, men kantene rundes av i gryten, og sausen får mindre å holde seg fast i.'}},
    {title:{en:'Knead, then wait', no:'Elt, og vent etterpå'},
     body:{en:'Kneading builds a gluten network that pulls the dough back every time you stretch it. Half an hour of rest lets those bonds slip and re-form in the new shape, so the sheet stretches under the pin instead of springing back, and it reaches the wires evenly thick. Skip the rest and the sheet will be thick in the middle and torn at the edges.',
           no:'Eltingen bygger et glutennettverk som trekker deigen tilbake hver gang du strekker den. En halvtimes hvile lar bindingene gli og feste seg på nytt i den nye formen, så platen strekker seg under kjevlen i stedet for å sprette tilbake, og den kommer jevnt tykk fram til strengene. Dropper du hvilen, blir platen tykk på midten og revnet i kantene.'}},
  ],
  variations:[
    {title:{en:'Without a chitarra', no:'Uten chitarra'},
     body:{en:'Roll the sheet to the same thickness, flour it well, fold it loosely into a flat roll and cut it with a long knife into strips exactly as wide as the sheet is thick, then shake them out. The corners are less exact and the strands less even than the wires give, but a hand-cut square strand behaves like the real thing. Do not use a machine\'s tagliatelle cutter: it gives a flat ribbon, which is a different pasta.',
           no:'Kjevle platen like tykk, mel den godt, brett den løst sammen til en flat rull, og skjær den med en lang kniv i strimler nøyaktig like brede som platen er tykk. Rist dem så ut. Hjørnene blir mindre nøyaktige og trådene mindre jevne enn med strengene, men en firkantet tråd skåret for hånd oppfører seg som den ekte. Bruk ikke tagliatelleskjæreren på en pastamaskin, for den gir et flatt bånd, og det er en annen pasta.'}},
    {title:{en:'The same strand in Rome', no:'Den samme tråden i Roma'},
     body:{en:'Lazio makes a square-cut fresh strand under the name tonnarelli and serves it with cacio e pepe. Umbria and the Marche have their own versions again. The tool travelled with the shepherds along the droving roads, and so did the shape.',
           no:'Lazio lager en firkantskåret fersk tråd under navnet tonnarelli og serverer den med cacio e pepe. Umbria og Marche har sine egne utgaver. Redskapet fulgte gjeterne langs drifteveiene, og formen fulgte med.'}},
    {title:{en:'How to dress it', no:'Hva den serveres med'},
     body:{en:'Teramo\'s pallottine are the classic, and there is a recipe for them here. Elsewhere in the region a lamb or mixed-meat ragù is the usual answer, and in summer little more than tomato, garlic and a great deal of grated pecorino. The square strand suits all three, because it carries a thin sauce as well as a heavy one.',
           no:'Pallottine fra Teramo er det klassiske, og de har en egen oppskrift her. Ellers i regionen er en ragù av lam eller blandet kjøtt det vanlige svaret, og om sommeren lite annet enn tomat, hvitløk og rikelig med revet pecorino. Den firkantede tråden passer til alle tre, for den bærer en tynn saus like godt som en tung.'}},
  ],
},

{
  id:'pallottine', dish:"Pallottine", course:'primo', lesson:3, serves:4, time:{prep:45, cook:55},
  hero:'chitarra', tags:['pasta','meatballs','tomato'],
  title:{en:'Pallottine', no:'Pallottine'},
  blurb:{en:'Teramo\'s meatballs are the size of a hazelnut, so a fork of chitarra carries three or four of them. Nothing on the plate needs a knife.',
         no:'Kjøttbollene fra Teramo er på størrelse med en hasselnøtt, så en gaffel med chitarra får med seg tre eller fire av dem. Ingenting på tallerkenen trenger kniv.'},
  heroCaption:{en:'Spaghetti alla chitarra con pallottine, the classic dressing in Teramo.',
               no:'Spaghetti alla chitarra con pallottine, det klassiske tilbehøret i Teramo.'},
  wines:['Montepulciano d\'Abruzzo'],
  headnote:{
    en:'<p>In Teramo the classic dressing for spaghetti alla chitarra is <strong>pallottine</strong>, meatballs the size of a hazelnut in a plain tomato sauce. The name is a diminutive of a diminutive and is meant literally. The mince below makes the better part of a hundred of them, and rolling them is most of the work.</p>'
      + '<p>The size does the work. A ball of five grams cooks through in the time it takes to brown, so the sauce never has to be a long one, and the ball rides on the fork among the strands instead of being chased around the plate with a knife. Roll them any bigger and the dish turns into meatballs with pasta on the side, which is a different meal.</p>'
      + '<p>Two things keep them tender. Egg, grated pecorino and soaked breadcrumb make a soft paste that holds water inside the meat rather than letting it be squeezed out, and the mince is mixed only until it comes together. They are browned in oil first so they hold their shape, then finished in the sauce. The same pallottine go between the layers of Teramo\'s other great dish, the baked <strong>timballo</strong> of scrippelle.</p>',
    no:'<p>I Teramo er det klassiske tilbehøret til spaghetti alla chitarra <strong>pallottine</strong>, kjøttboller på størrelse med en hasselnøtt i en enkel tomatsaus. Navnet er en diminutiv av en diminutiv, og det skal tas bokstavelig. Kjøttdeigen nedenfor gir nesten hundre av dem, og rullingen er mesteparten av arbeidet.</p>'
      + '<p>Størrelsen gjør jobben. En bolle på fem gram blir gjennomstekt på den tiden den bruker på å bli brun, så sausen trenger aldri å koke lenge, og bollen blir liggende på gaffelen mellom pastatrådene i stedet for å bli jaget rundt tallerkenen med kniv. Ruller du dem større, blir retten kjøttboller med pasta ved siden av, og det er et annet måltid.</p>'
      + '<p>To ting holder dem møre. Egg, revet pecorino og bløtlagt brødrasp gir en myk masse som holder på vannet inne i kjøttet i stedet for å la det bli presset ut, og kjøttdeigen blandes bare til den henger sammen. Bollene brunes i olje først, slik at de holder formen, og blir ferdige i sausen. De samme pallottine ligger mellom lagene i den andre store retten fra Teramo, den ovnsbakte <strong>timballoen</strong> av scrippelle.</p>'},
  ingredients:[
    { group:{en:'For the pallottine', no:'Til pallottine'}, items:[
      {q:300, u:'g', n:{en:'minced veal', no:'kalvekjøttdeig'}, note:{en:'or beef, and not too lean', no:'eller kjøttdeig av storfe, og ikke for mager'}},
      {q:100, u:'g', n:{en:'minced pork', no:'svinekjøttdeig'}},
      {q:1, u:'', n:{en:'egg', no:'egg'}, round:'half'},
      {q:40, u:'g', n:{en:'Pecorino, finely grated', no:'pecorino, finrevet'}},
      {q:40, u:'g', n:{en:'dry breadcrumbs', no:'tørt brødrasp'}, note:{en:'soaked in water and squeezed out', no:'bløtlagt i vann og klemt tørt'}},
      {q:10, u:'g', n:{en:'flat-leaf parsley', no:'bladpersille'}, note:{en:'finely chopped', no:'finhakket'}},
      {u:'', n:{en:'nutmeg', no:'muskatnøtt'}, note:{en:'a scrape', no:'litt revet'}, scale:'none'},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
      {q:100, u:'ml', n:{en:'olive oil for frying', no:'olivenolje til steking'}, scale:'none'},
    ]},
    { group:{en:'For the sauce', no:'Til sausen'}, items:[
      {q:700, u:'g', n:{en:'peeled plum tomatoes', no:'hermetiske plommetomater'}, note:{en:'crushed by hand', no:'most med hendene'}},
      {q:1, u:'', n:{en:'small onion', no:'liten løk'}, note:{en:'finely chopped', no:'finhakket'}, round:'half'},
      {q:30, u:'ml', n:{en:'olive oil', no:'olivenolje'}},
      {u:'', n:{en:'basil', no:'basilikum'}, note:{en:'a few leaves, torn', no:'noen blader, revet i biter'}, scale:'none'},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'To serve', no:'Til servering'}, items:[
      {q:400, u:'g', n:{en:'fresh spaghetti alla chitarra', no:'fersk spaghetti alla chitarra'},
       note:{en:'one batch of the recipe alongside this one', no:'én porsjon av oppskriften ved siden av denne'}},
      {q:40, u:'g', n:{en:'Pecorino, grated', no:'pecorino, revet'}},
      {q:4, u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:20, u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
    ]},
  ],
  steps:[
    {en:'Cover the breadcrumbs with cold water, leave them a minute and squeeze them out in your hand.',
     no:'Dekk brødraspet med kaldt vann, la det stå et minutt, og klem det tørt i hånden.'},
    {en:'Put both minces in a bowl with the egg, the pecorino, the squeezed crumb, the parsley, a scrape of nutmeg and salt.',
     no:'Ha begge kjøttdeigene i en bolle sammen med egget, pecorinoen, det utklemte brødraspet, persillen, litt revet muskat og salt.'},
    {en:'Mix with your fingers only until it comes together. Work it hard and the mince goes tight and the balls turn springy.',
     no:'Bland med fingrene bare til det henger sammen. Arbeider du den hardt, blir kjøttdeigen stram og bollene seige.'},
    {en:'Cover the bowl and let it stand in the fridge for twenty minutes, so the crumb takes up the moisture evenly.',
     no:'Dekk bollen til og la den stå kaldt i tjue minutter, slik at brødraspet trekker til seg fuktigheten jevnt.'},
    {en:'Roll the mixture between your palms into balls the size of a hazelnut, keeping them all alike so they cook at the same rate.',
     no:'Rull massen mellom håndflatene til boller på størrelse med en hasselnøtt, og hold dem like store, så de blir ferdige samtidig.'},
    {en:'Heat a shallow layer of oil in a frying pan and brown the balls in batches, rolling them around, for about a minute each batch. Lift them onto kitchen paper.',
     no:'Varm et tynt lag olje i en stekepanne og brun bollene i omganger mens du triller dem rundt, omtrent ett minutt per omgang. Løft dem over på kjøkkenpapir.'},
    {en:'Pour off the frying oil. Soften the onion in fresh oil in a wide pan over low heat until it is translucent but not coloured.',
     no:'Hell av stekeoljen. La løken mykne i ny olje i en vid panne på svak varme til den er blank, men uten farge.'},
    {en:'Crush in the tomatoes, salt lightly and simmer uncovered for twenty minutes, until the sauce darkens and thickens.',
     no:'Mos tomatene ned i pannen, salt lett, og la sausen småkoke uten lokk i tjue minutter, til den mørkner og tykner.'},
    {en:'Slide the pallottine into the sauce with the basil and simmer very gently for twenty minutes more, shaking the pan now and then instead of stirring it.',
     no:'Legg pallottine forsiktig ned i sausen sammen med basilikumen, og la det småkoke svært rolig i tjue minutter til. Rist på pannen av og til i stedet for å røre i den.'},
    {en:'Cook the chitarra in well-salted water until it floats, which takes two or three minutes for fresh pasta.',
     no:'Kok chitarraen i godt saltet vann til den flyter opp, og det tar to–tre minutter for fersk pasta.'},
    {en:'Drain it, toss it with about half the sauce, and serve with the pallottine and the rest of the sauce spooned over and grated pecorino on top.',
     no:'Hell av vannet, vend pastaen med omtrent halvparten av sausen, og server den med pallottine, resten av sausen og revet pecorino på toppen.'},
  ],
  notes:[
    {title:{en:'Why they are browned first', no:'Hvorfor de brunes først'},
     body:{en:'The crust from browning sets the protein on the surface, so a ball can sit in a wet sauce for twenty minutes and still be a ball. A raw one dropped straight into tomato gives itself up to the sauce a little at a time. Browning also leaves flavour on the outside that no amount of simmering will produce.',
           no:'Skorpen fra bruningen får proteinet på overflaten til å stivne, så en bolle kan ligge i en våt saus i tjue minutter og fortsatt være en bolle. En rå bolle som legges rett i tomaten, løser seg gradvis opp i sausen. Bruningen legger dessuten igjen en smak på utsiden som ingen småkoking kan skape.'}},
    {title:{en:'What the soaked bread does', no:'Hva det bløtlagte brødet gjør'},
     body:{en:'Bread and egg do more than bind. The starch swells into a gel that holds water among the meat fibres, so the fibres can tighten as they cook without wringing themselves dry. That is why a meatball with bread in it stays soft and one of pure mince, however good the meat, does not.',
           no:'Brød og egg gjør mer enn å binde. Stivelsen sveller til en gelé som holder på vann mellom kjøttfibrene, slik at fibrene kan trekke seg sammen under stekingen uten å vri seg tørre. Derfor blir en kjøttbolle med brød i seg værende mør, mens en av ren kjøttdeig ikke gjør det, uansett hvor godt kjøttet er.'}},
    {title:{en:'A short sauce on purpose', no:'En kort saus med vilje'},
     body:{en:'Onion, tomato, basil and salt, and twenty minutes. The sauce is there to carry the meatballs and to coat the strands, not to be a ragù, and long cooking would only give the pallottine time to tighten. If it thickens too far before the pasta is ready, loosen it with a little of the pasta water.',
           no:'Løk, tomat, basilikum og salt, og tjue minutter. Sausen skal bære kjøttbollene og legge seg rundt trådene, ikke være en ragù, og lang koking ville bare gitt bollene tid til å trekke seg sammen. Tykner den for mye før pastaen er klar, kan du spe den med litt av pastavannet.'}},
  ],
  variations:[
    {title:{en:'Without the frying pan', no:'Uten stekepannen'},
     body:{en:'Drop the raw balls straight into the simmering sauce. They come out paler and softer, and the sauce takes up more of the meat flavour, which many home cooks prefer. Make the sauce a little thinner to start with, because the balls give off water as they cook.',
           no:'Legg de rå bollene rett i den småkokende sausen. De blir lysere og mykere, og sausen får mer av kjøttsmaken i seg, noe mange hjemmekokker foretrekker. Lag sausen litt tynnere fra begynnelsen, for bollene gir fra seg vann mens de koker.'}},
    {title:{en:'The mince', no:'Kjøttdeigen'},
     body:{en:'Veal and pork here, but the region\'s home cooks are not doctrinaire about it: some use beef alone, others work in lamb or a little sausage meat. The fat matters more, since a very lean mince gives hard little pellets whatever else you do.',
           no:'Her brukes kalv og svin, men hjemmekokkene i regionen er ikke firkantede på det punktet. Noen bruker bare storfe, andre blander inn lam eller litt pølsefarse. Fettet betyr mer, for en svært mager kjøttdeig gir harde små kuler uansett hva du ellers gjør.'}},
    {title:{en:'Into a timballo', no:'Inn i en timballo'},
     body:{en:'The same pallottine, layered in a dish with scrippelle instead of pasta, spinach and cheese, and baked, are Teramo\'s timballo. Make the scrippelle from the recipe alongside, keep the sauce slightly looser, and build it like a lasagne with a crêpe where each sheet would go.',
           no:'De samme pallottine, lagt lagvis i en form med scrippelle i stedet for pasta, spinat og ost, og bakt i ovnen, er timballoen fra Teramo. Lag scrippelle etter oppskriften ved siden av, hold sausen litt løsere, og bygg retten som en lasagne, med en pannekake der hver plate ellers ville ligget.'}},
  ],
},

{
  id:'brodetto-alla-vastese', dish:'Brodetto alla vastese', course:'secondo', lesson:2, serves:4, time:{prep:30, cook:40},
  hero:'brodetto', tags:['fish','stew','adriatic','terracotta'],
  title:{en:'Brodetto alla vastese', no:'Brodetto alla vastese'},
  blurb:{en:'Fish laid in a terracotta pot in layers, cooked with tomato and green pepper, and never stirred, only shaken.',
         no:'Fisk lagt lagvis i en leirgryte, kokt med tomat og grønn paprika, og aldri rørt i, bare ristet.'},
  heroCaption:{en:'Brodetto alla vastese in its terracotta pot: whole fish, cuttlefish and shellfish, tomato, and nothing else.',
               no:'Brodetto alla vastese i leirgryten: hel fisk, blekksprut og skalldyr, tomat og ingenting annet.'},
  wines:['Cerasuolo d\'Abruzzo','Pecorino'],
  headnote:{
    en:'<p>Abruzzo\'s coast is a working one, with fishing ports at Giulianova, Ortona and Vasto, and south of Ortona the <strong>Costa dei Trabocchi</strong>, where timber platforms with nets on long arms stand out from the rocks. <em>Brodetto alla vastese</em> is what the boats brought in, cooked in the pot it is served from. It has no fixed list of fish. It is a method for whatever is on the quay, as long as there are several kinds of it.</p>'
      + '<p>The pot is terracotta and the fish goes into it in layers, the slowest at the bottom. Nothing is ever stirred. A spoon dragged through whole fish reduces them to a soup of bones and shreds, so the cook takes the pot by both handles and shakes it flat on the hob, which moves the liquid without moving the fish. The clay helps twice over: it spreads the heat, so nothing scorches under the middle, and it holds that heat all the way to the table.</p>'
      + '<p>What the Vasto version leaves out counts for as much as what goes in. There is no wine, no stock and no saffron, only oil, garlic, sweet green pepper, tomato, a little water and the sea water the fish brings with it. Two or three kinds of fish will not do. The broth is made by five or six sorts giving up their different flavours at once, which is why the pot holds small whole fish and not clean fillets.</p>',
    no:'<p>Kysten i Abruzzo er en kyst i arbeid, med fiskehavner i Giulianova, Ortona og Vasto, og sør for Ortona ligger <strong>Costa dei Trabocchi</strong>, der plattformer av tømmer med nett på lange armer stikker ut fra svabergene. <em>Brodetto alla vastese</em> er det båtene kom inn med, kokt i den gryten den serveres fra. Retten har ingen fast liste over fisk. Den er en metode for det som ligger på kaia, så lenge det er flere slag.</p>'
      + '<p>Gryten er av leire, og fisken legges lagvis oppi, med det som trenger lengst tid nederst. Ingenting røres. En sleiv som dras gjennom hel fisk, gjør den om til en suppe av bein og trevler, så kokken tar gryten i begge hankene og rister den flatt på platen. Da beveger væsken seg uten at fisken gjør det. Leiren hjelper på to måter: den sprer varmen, så ingenting svir seg under midten, og den holder på varmen helt fram til bordet.</p>'
      + '<p>Det Vasto-utgaven utelater, betyr like mye som det som faktisk går i gryten. Her er det verken vin, kraft eller safran, bare olje, hvitløk, søt grønn paprika, tomat, litt vann og sjøvannet fisken har med seg. To eller tre slags fisk holder ikke. Kraften blir til ved at fem–seks sorter gir fra seg hver sin smak samtidig, og derfor ligger det små, hele fisker i gryten og ikke rene fileter.</p>'},
  ingredients:[
    { group:{en:'The fish', no:'Fisken'}, items:[
      {q:1200, u:'g', n:{en:'small whole fish, gutted and scaled', no:'små, hele fisker, sløyd og skrapt'},
       note:{en:'four or five kinds, heads on. In Italy scorfano, gallinella, triglia and small hake; in Norway ask for small uer, knurr, lysing and sei',
             no:'fire–fem slag, med hodet på. I Italia scorfano, gallinella, triglia og liten lysing; i Norge kan du be om små uer, knurr, lysing og sei'}},
      {q:400, u:'g', n:{en:'cuttlefish or squid', no:'blekksprut eller akkar'},
       note:{en:'cleaned and cut into wide strips; it goes in first and takes the longest', no:'renset og skåret i brede strimler; den går i først og trenger lengst tid'}},
      {q:300, u:'g', n:{en:'langoustines or large prawns', no:'sjøkreps eller store reker'},
       note:{en:'whole and in the shell; Vasto uses canocchie, mantis shrimp', no:'hele og med skall; i Vasto brukes canocchie, sjøknelter'}},
    ]},
    { group:{en:'In the pot', no:'I gryten'}, items:[
      {q:80, u:'ml', n:{en:'extra-virgin olive oil', no:'extra virgin olivenolje'}},
      {q:3, u:'', n:{en:'garlic cloves', no:'hvitløksfedd'}, note:{en:'lightly crushed and left whole', no:'lett knust og lagt i hele'}, round:'half'},
      {q:2, u:'', n:{en:'sweet green peppers', no:'søte grønne paprika'}, note:{en:'the long thin kind, in strips', no:'de lange, tynne, skåret i strimler'}, round:'half'},
      {q:500, u:'g', n:{en:'ripe tomatoes', no:'modne tomater'},
       note:{en:'peeled and chopped, or peeled plum tomatoes from a tin', no:'flådd og hakket, eller hermetiske plommetomater'}},
      {q:1, u:'', n:{en:'small dried chilli', no:'liten tørket chili'}, round:'half'},
      {q:15, u:'g', n:{en:'flat-leaf parsley', no:'bladpersille'}, note:{en:'chopped, added at the end', no:'hakket, has i til slutt'}},
      {q:150, u:'ml', n:{en:'water', no:'vann'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'To serve', no:'Til servering'}, items:[
      {q:250, u:'g', n:{en:'country bread', no:'grovt landbrød'}, note:{en:'in thick slices, toasted', no:'i tykke skiver, ristet'}},
    ]},
  ],
  steps:[
    {en:'Ask the fishmonger to gut and scale the fish but to leave the heads on. The heads carry most of what the broth is made of.',
     no:'Be fiskehandleren sløye og skrape fisken, men la hodene sitte på. Hodene har med seg det meste av det kraften blir til av.'},
    {en:'Warm the oil, the garlic and the chilli together in a wide terracotta pot over low heat, until the garlic smells but has taken no colour.',
     no:'Varm oljen, hvitløken og chilien sammen i en vid leirgryte på svak varme, til hvitløken dufter, men ikke har fått farge.'},
    {en:'Add the strips of green pepper and let them soften for five minutes.',
     no:'Ha i paprikastrimlene og la dem mykne i fem minutter.'},
    {en:'Lay the cuttlefish on top, cover the pot and let it cook gently for fifteen minutes, until it gives up its water and turns tender.',
     no:'Legg blekkspruten oppå, legg lokk på gryten, og la den koke rolig i femten minutter, til den gir fra seg vannet sitt og blir mør.'},
    {en:'Add the tomatoes and the water, salt lightly and bring it to a bare simmer.',
     no:'Ha i tomatene og vannet, salt lett, og la det så vidt komme til småkoking.'},
    {en:'Lay the firmest fish in a single layer, the softer ones on top of those, and the langoustines last of all. Do not press anything down.',
     no:'Legg den fasteste fisken i ett lag, den mykere oppå der igjen, og sjøkrepsen helt øverst. Ikke press noe ned.'},
    {en:'Cover the pot and cook over a low flame for twelve to fifteen minutes, until the eyes of the fish have gone white and the flesh comes away from the bone.',
     no:'Legg på lokk og la det koke på svak varme i tolv til femten minutter, til øynene på fisken er blitt hvite og kjøttet slipper beinet.'},
    {en:'Never stir. Twice while it cooks, take the pot by both handles and shake it flat on the hob, so the liquid runs down through the layers.',
     no:'Rør aldri i gryten. To ganger underveis tar du den i begge hankene og rister den flatt på platen, slik at væsken renner ned gjennom lagene.'},
    {en:'Taste the broth at the edge of the pot and correct the salt. The fish salts it as it cooks, so this belongs at the end.',
     no:'Smak på kraften ytterst i gryten og juster saltet. Fisken salter den mens den koker, så dette hører til på slutten.'},
    {en:'Scatter the parsley over, take the pot off the heat and let it stand, covered, for five minutes.',
     no:'Dryss persillen over, ta gryten av platen, og la den stå med lokk i fem minutter.'},
    {en:'Serve straight from the pot, with the toasted bread alongside. The wine belongs in the glass and not in the pan.',
     no:'Server rett fra gryten, med det ristede brødet ved siden av. Vinen hører hjemme i glasset og ikke i gryten.'},
  ],
  notes:[
    {title:{en:'The layers are a timetable', no:'Lagene er en tidsplan'},
     body:{en:'The order the fish goes in is the order it needs. Cuttlefish is muscle and wants a quarter of an hour before anything else joins it; a small whole fish wants ten minutes; a langoustine wants four. Stacking them puts each one where the heat suits it, with the top layer steaming under the lid while the bottom one sits in the liquid.',
           no:'Rekkefølgen fisken legges i, er den rekkefølgen den trenger. Blekksprut er muskel og vil ha et kvarter før noe annet kommer oppi, en liten hel fisk vil ha ti minutter, og en sjøkreps vil ha fire. Ved å stable dem gir du hver av dem den varmen den tåler, og det øverste laget dampes under lokket mens det nederste ligger i væsken.'}},
    {title:{en:'Why clay and not steel', no:'Hvorfor leire og ikke stål'},
     body:{en:'Unglazed clay conducts heat badly, and here that is exactly what is wanted. It spreads what the flame gives it instead of passing on a hot ring, so the cuttlefish at the bottom never catches, and once hot it stays hot long enough for the dish to be eaten out of the pot. A heavy cast-iron casserole is the nearest substitute. A thin steel pan is not one at all.',
           no:'Uglasert leire leder varme dårlig, og nettopp det er poenget her. Den sprer det platen gir fra seg i stedet for å sende videre en het sone, så blekkspruten i bunnen aldri svir seg, og når leiren først er varm, holder den seg varm lenge nok til at retten kan spises rett fra gryten. En tung støpejernsgryte ligger nærmest. En tynn stålpanne er ingen erstatning i det hele tatt.'}},
    {title:{en:'The broth is the dish', no:'Kraften er retten'},
     body:{en:'Nothing is added to make it: no stock, no wine, no butter. The liquid is water, tomato and whatever comes out of the heads, bones and shells. That is why several kinds of fish matter more than one very good one, and why nobody fillets anything before it goes in.',
           no:'Ingenting tilsettes for å lage den, verken kraft, vin eller smør. Væsken er vann, tomat og det som kommer ut av hoder, bein og skall. Derfor betyr flere slags fisk mer enn én svært god fisk, og derfor fileterer ingen noe før det går i gryten.'}},
  ],
  variations:[
    {title:{en:'What to buy in Norway', no:'Hva du kjøper i Norge'},
     body:{en:'Small whole redfish, gurnard, hake and small saithe give the mixture the Adriatic version needs, and a piece of monkfish tail cut thick is a good bottom layer beside the cuttlefish. Ask the fish counter for what is small and whole rather than what is expensive; a brodetto of two noble fillets is a worse dish than one of five cheap fish.',
           no:'Liten uer, knurr, lysing og små seistykker gir den blandingen adriaterutgaven trenger, og et stykke breiflabbhale skåret tykt er et godt bunnlag ved siden av blekkspruten. Spør i fiskedisken etter det som er lite og helt, ikke etter det som er dyrt. En brodetto av to edle fileter er en dårligere rett enn en av fem billige fisker.'}},
    {title:{en:'Elsewhere on the Adriatic', no:'Andre steder ved Adriaterhavet'},
     body:{en:'Brodetto changes every few kilometres up the coast. The Marche versions add vinegar at San Benedetto and saffron at Porto Recanati, and further north there is more onion and less pepper. Vasto is the tomato-and-pepper one, cooked and served in clay, and it is the most austere of them.',
           no:'Brodetto skifter karakter for hver havn oppover kysten. Utgavene i Marche har eddik i San Benedetto og safran i Porto Recanati, og lenger nord er det mer løk og mindre paprika. Vasto er utgaven med tomat og paprika, kokt og servert i leire, og den er den mest nøkterne av dem.'}},
    {title:{en:'Two courses from one pot', no:'To retter av én gryte'},
     body:{en:'Ladle the broth over slices of toasted bread in warm plates and eat that first, then bring the pot back with the fish in it. The bread does what pasta would do in a northern kitchen, and the fish is then eaten plainly, with fingers, which is how it is meant to be.',
           no:'Øs kraften over skiver av ristet brød på varme tallerkener og spis det først, og sett så gryten på bordet igjen med fisken i. Brødet gjør det pastaen ville gjort lenger nord i Italia, og fisken spises deretter helt enkelt, med fingrene, slik den er ment å spises.'}},
  ],
},

{
  id:'scrippelle-mbusse', dish:"Scrippelle 'mbusse", course:'primo', lesson:3, serves:4, time:{prep:35, cook:20},
  hero:'scrippelle', tags:['crepes','broth','pecorino'],
  title:{en:'Scrippelle \'mbusse', no:'Scrippelle \'mbusse'},
  blurb:{en:'Thin crêpes rolled around grated pecorino and drowned in boiling hen broth. It sounds like an accident and works completely.',
         no:'Tynne pannekaker rullet rundt revet pecorino og druknet i kokende hønsekraft. Det høres ut som et uhell og fungerer helt utmerket.'},
  heroCaption:{en:'Scrippelle rolled and waiting. The broth goes over them at the table, and they are eaten at once.',
               no:'Scrippelle rullet og klare. Kraften helles over ved bordet, og de spises med en gang.'},
  wines:['Trebbiano d\'Abruzzo'],
  headnote:{
    en:'<p>Teramo\'s first course is a plate of thin crêpes rolled around grated pecorino with a ladle of boiling broth poured over them. <em>\'Mbusse</em> is dialect for soaked, and the word describes the dish and the moment together: the rolls are dry when they reach the bowl and wet by the time the spoon does.</p>'
      + '<p>A scrippella is not a pancake in the ordinary sense. The batter is eggs, flour and water, thin enough to run, and each one is cooked on one side only in a barely greased pan, for less than a minute, until it sets and lifts at the edge. Cooked that lightly it stays porous, and the porosity is what lets it take up broth instead of going to paste. A thick pancake browned on both sides resists the broth first and turns rubbery afterwards.</p>'
      + '<p>The broth carries the dish, so make a proper one: a boiling hen simmered for hours with carrot, celery and onion, skimmed, strained and well salted. And serve at once. There is about a minute between soaked and ruined, which is why the broth is poured at the table and not in the kitchen.</p>',
    no:'<p>Forretten fra Teramo er en tallerken med tynne pannekaker rullet rundt revet pecorino, med en øse kokende kraft over. <em>\'Mbusse</em> er dialekt for gjennombløt, og ordet beskriver retten og øyeblikket på én gang. Rullene er tørre når de kommer i skålen og våte når skjeen kommer.</p>'
      + '<p>En scrippella er ingen pannekake i vanlig forstand. Røren består av egg, mel og vann, tynn nok til å renne, og hver enkelt stekes bare på én side i en så vidt smurt panne, i under et minutt, til den stivner og slipper i kanten. Når den stekes så lett, holder den seg porøs, og porøsiteten gjør at den suger til seg kraft i stedet for å gå i oppløsning. En tykk pannekake som er brunet på begge sider, står imot kraften først og blir gummiaktig etterpå.</p>'
      + '<p>Kraften bærer retten, så lag en ordentlig kraft. Kok en høne i flere timer med gulrot, selleri og løk, skum av, sil og salt godt. Og server med en gang. Det går omtrent et minutt fra gjennombløt til ødelagt, og derfor helles kraften over ved bordet og ikke på kjøkkenet.</p>'},
  ingredients:[
    { group:{en:'For the scrippelle', no:'Til scrippelle'}, items:[
      {q:4, u:'', n:{en:'eggs', no:'egg'}, round:'half'},
      {q:200, u:'g', n:{en:'plain white flour', no:'hvetemel'}},
      {q:450, u:'ml', n:{en:'water', no:'vann'}, note:{en:'the batter should run off the ladle in a thin stream', no:'røren skal renne av øsen i en tynn stråle'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
      {q:20, u:'g', n:{en:'lard or butter for the pan', no:'smult eller smør til pannen'},
       note:{en:'the pan is wiped with it, not coated', no:'pannen tørkes over med det, ikke smøres tykt'}, scale:'none'},
    ]},
    { group:{en:'For the filling', no:'Til fyllet'}, items:[
      {q:120, u:'g', n:{en:'Pecorino, finely grated', no:'pecorino, finrevet'},
       note:{en:'an Abruzzese sheep\'s cheese; Pecorino Romano is sharper but works', no:'en abruzzesisk saueost; Pecorino Romano er skarpere, men går fint'}},
      {u:'', n:{en:'nutmeg', no:'muskatnøtt'}, note:{en:'a scrape, optional', no:'litt revet, valgfritt'}, scale:'none'},
    ]},
    { group:{en:'For the broth', no:'Til kraften'}, items:[
      {q:1500, u:'ml', n:{en:'hen or chicken broth', no:'hønse- eller kyllingkraft'},
       note:{en:'made from a boiling hen if you can get one, strained and well salted', no:'kokt på høne om du får tak i en, silt og godt saltet'}},
    ]},
  ],
  steps:[
    {en:'Beat the eggs with the salt until they are smooth and pale.',
     no:'Visp eggene med saltet til de er jevne og lyse.'},
    {en:'Sift in the flour and beat it to a thick paste with no lumps left in it.',
     no:'Sikt melet oppi og visp det til en tykk masse uten klumper.'},
    {en:'Let the water down into the paste in a thin stream, whisking, until the batter is as thin as single cream.',
     no:'Spe massen med vann i en tynn stråle mens du visper, til røren er like tynn som kaffefløte.'},
    {en:'Cover the batter and let it stand for half an hour, so the flour swells and the crêpes do not tear.',
     no:'Dekk røren til og la den stå i en halvtime, så melet sveller og pannekakene ikke revner.'},
    {en:'Warm a small frying pan over medium heat and wipe it with lard on a piece of kitchen paper. The pan should be barely greased, not swimming.',
     no:'Varm en liten stekepanne på middels varme og tørk den over med smult på et stykke kjøkkenpapir. Pannen skal være så vidt smurt, ikke svømme i fett.'},
    {en:'Pour in a thin veil of batter and tilt the pan at once so it runs out to the edges.',
     no:'Hell i et tynt slør av røre og vipp på pannen med en gang, så den renner ut til kantene.'},
    {en:'Cook it on one side only, until the surface has set and the edge lifts, which takes under a minute. Slide it out and stack the scrippelle as they come.',
     no:'Stek den bare på én side, til overflaten har stivnet og kanten slipper, og det tar under et minutt. La den gli ut av pannen og stable scrippelle etter hvert som de blir ferdige.'},
    {en:'Scatter grated pecorino and a scrape of nutmeg over the cooked side of each one and roll it up tightly into a cigar.',
     no:'Dryss revet pecorino og litt revet muskat over den stekte siden på hver av dem, og rull dem stramt sammen til sigarer.'},
    {en:'Warm the bowls and lay three or four rolls in each of them, seam down.',
     no:'Varm skålene og legg tre eller fire ruller i hver av dem, med skjøten ned.'},
    {en:'Bring the broth to a rolling boil. The whole dish depends on it being properly hot when it goes over.',
     no:'Kok opp kraften skikkelig. Hele retten avhenger av at den er ordentlig varm når den helles over.'},
    {en:'Pour the broth over at the table and eat immediately, while the rolls are soaked through and still holding their shape.',
     no:'Hell kraften over ved bordet og spis med en gang, mens rullene er gjennombløte og fortsatt holder formen.'},
  ],
  notes:[
    {title:{en:'One side only', no:'Bare én side'},
     body:{en:'Browning builds a skin of set protein and caramelised starch that keeps liquid out. Cooking the crêpe on one side leaves the other face pale, soft and open, and that face drinks. It is also the side the cheese goes on, so the melting happens inside the roll where the broth reaches it first.',
           no:'Bruning bygger et skinn av stivnet protein og karamellisert stivelse som holder væske ute. Når pannekaken bare stekes på én side, blir den andre siden lys, myk og åpen, og det er den siden som drikker. Osten legges på samme side, så smeltingen skjer inne i rullen der kraften når den først.'}},
    {title:{en:'Boiling, not merely hot', no:'Kokende, ikke bare varmt'},
     body:{en:'A scrippella takes up broth by soaking, and heat sets the speed. Broth at a rolling boil wets the rolls through in seconds and melts the cheese as it goes. Broth that cooled on the way from the stove leaves them dry in the middle and lukewarm on the tongue. Warm the bowls for the same reason.',
           no:'En scrippella tar til seg kraft ved å suge, og varmen bestemmer farten. Kraft i fullt kok bløter rullene gjennom på sekunder og smelter osten på veien. Kraft som har kjølnet mellom komfyren og bordet, lar dem være tørre i midten og lunkne på tungen. Varm skålene av samme grunn.'}},
    {title:{en:'Water, not milk', no:'Vann, ikke melk'},
     body:{en:'The batter is made with water. Milk enriches it, and the fat and the milk sugar together give a softer, browner, more sealed crêpe, which is exactly what you do not want here. A water batter cooks up thinner and more brittle, and brittle is what soaks.',
           no:'Røren lages med vann. Melk gjør den fetere, og fettet og melkesukkeret gir sammen en mykere, brunere og mer lukket pannekake, altså nøyaktig det du ikke er ute etter her. En røre som lages med vann, steker seg tynnere og sprøere, og en sprø pannekake suger til seg kraft.'}},
  ],
  variations:[
    {title:{en:'Timballo alla teramana', no:'Timballo alla teramana'},
     body:{en:'The same scrippelle, layered in a dish with pallottine, spinach and cheese where a lasagne would have pasta, and baked, are Teramo\'s timballo. Make them a little larger so they cover the dish, and leave the nutmeg out of the filling; the meat sauce carries the seasoning instead.',
           no:'De samme scrippelle, lagt lagvis i en form med pallottine, spinat og ost der en lasagne ville hatt pasta, og bakt i ovnen, er timballoen fra Teramo. Stek dem litt større, så de dekker formen, og la muskaten være ute av fyllet. Kjøttsausen står for krydringen i stedet.'}},
    {title:{en:'Rolled and baked, without broth', no:'Bakt i ovn, uten kraft'},
     body:{en:'Elsewhere in the region the same crêpes are rolled around ham or a little ragù, laid in a dish, dusted with cheese and baked until the tops crisp. That version keeps and reheats, which the soaked one cannot do at all.',
           no:'Ellers i regionen rulles de samme pannekakene rundt skinke eller litt ragù, legges i en form, drysses med ost og bakes til toppene blir sprø. Den utgaven kan settes til side og varmes opp igjen, og det tåler den gjennombløte ikke i det hele tatt.'}},
    {title:{en:'How many to a bowl', no:'Hvor mange i hver skål'},
     body:{en:'Three rolls open a meal, five make it lunch. Either way the broth should just cover them and no more. Drowned in a deep soup plate they float apart, and the dish becomes a thin chicken soup with cheese in it.',
           no:'Tre ruller åpner et måltid, og fem gjør det til lunsj. Uansett skal kraften så vidt dekke dem og ikke mer. Drukner de i en dyp suppetallerken, flyter de fra hverandre, og retten blir en tynn hønsesuppe med ost i.'}},
  ],
},

];
