// Basilicata recipes. Bilingual in one file: the quantities are written once so English and Norwegian
// cannot drift apart. Contract: docs/recipe-format.md. Checked by tools/recipecheck.py. Never narrated.
// Everything here follows the Lucanian food reading (content/basilicata.js, lesson 3): a kitchen with
// almost nothing to buy. Durum wheat and water instead of egg pasta, dried peppers instead of meat,
// fried breadcrumbs instead of cheese, and salt cod as the only fish that could reach the mountains.
// Lucanica and caciocavallo podolico are left out on purpose: both are bought, not cooked.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-77'] = [

{
  id:'peperoni-cruschi', dish:'Peperoni cruschi', course:'antipasto', lesson:3, serves:4, time:{prep:10, cook:5},
  hero:'cruschi', tags:['pepper','fried','senise','store-cupboard'],
  title:{en:'Peperoni cruschi', no:'Peperoni cruschi'},
  blurb:{en:'Dried Senise peppers dropped into hot oil for a count of three and lifted out before they darken. Sweet, faintly smoky, and brittle enough to shatter between two fingers.',
         no:'Tørket paprika fra Senise som slippes ned i varm olje mens du teller til tre, og løftes opp før den mørkner. Søt, svakt røykpreget og så sprø at den knuses mellom to fingre.'},
  heroCaption:{en:'Peperoni cruschi a few seconds out of the oil. Still bright red, and already glassy.',
               no:'Peperoni cruschi noen sekunder etter at de kom opp av oljen. Fortsatt knallrøde, og allerede glassaktige.'},
  wines:['Aglianico del Vulture'],
  headnote:{
    en:'<p>Half of this recipe happens before you get near it. The <strong>peperone di Senise</strong>, an IGP since 1996, is a sweet pepper with flesh only one and a half to two millimetres thick and very little water in it. The crop is picked in August, threaded on strings a metre and a half to two metres long — the <em>serte</em> of the reading — and hung outdoors in the shade for weeks, until the pods are light, deep red and brittle. What you buy is the end of that. The cooking is the last ten seconds.</p>'
      + '<p>Those ten seconds are the whole dish. In hot oil the trace of water left in the flesh flashes to steam and sets the pod into a thin glassy sheet that shatters rather than bends, and the sugars in a sweet pepper caramelise at the same moment. They also burn at the same moment. Caramel and carbon are a second or two apart at this temperature, and a burnt crusco is bitter all the way through, so the batch goes in the bin. The reading puts it plainly: the frying is left to whoever in the house is trusted with it.</p>'
      + '<p>Getting the peppers is the hard part in Norway, because no supermarket sells a dried sweet pepper. Italian delicatessens stock <em>peperoni di Senise</em> IGP in packets, and Balkan, Turkish and Middle Eastern grocers hang strings of dried sweet red pods all winter. Those are usually a little fleshier, so they want a second longer and never quite shatter. Drying your own works if you start with a thin, sweet, pointed pepper and give it a low oven or a dehydrator until it rattles. Sweet paprika powder is not a substitute at all: it gives the colour and the sweetness and none of the crackle, which is the point of the thing.</p>',
    no:'<p>Halve oppskriften er gjort før du kommer til den. <strong>Peperone di Senise</strong>, IGP siden 1996, er en søt paprika med et kjøtt på bare halvannen til to millimeter og svært lite vann i seg. Avlingen plukkes i august, tres på snorer som er halvannen til to meter lange, de såkalte <em>serte</em>, og henges ute i skyggen i ukevis, til belgene er lette, dyprøde og sprø. Det du kjøper, er slutten på den prosessen. Selve matlagingen tar de siste ti sekundene.</p>'
      + '<p>De ti sekundene er hele retten. I varm olje fordamper det lille vannet som er igjen i kjøttet, og belgen stivner til et tynt, glassaktig skall som knuses i stedet for å bøye seg, samtidig som sukkeret i en søt paprika karamelliserer. Det brenner også i samme øyeblikk. Karamell og kull ligger ett eller to sekunder fra hverandre ved denne temperaturen, og en brent crusco er bitter tvers igjennom, så da ryker hele porsjonen. Lesestykket sier det rett ut: friteringen overlates til den i huset som har hånden for slikt.</p>'
      + '<p>I Norge er selve paprikaen den store hindringen, for ingen dagligvarebutikk fører tørket søt paprika. Italienske delikatessebutikker har <em>peperoni di Senise</em> IGP i pose, og balkanske og tyrkiske butikker henger snorer med tørkede søte belger hele vinteren. De siste er gjerne litt kjøttfullere, så de trenger et sekund lenger og blir aldri helt like sprø. Du kan også tørke dine egne hvis du starter med en tynn, søt spisspaprika og gir den svak ovnsvarme eller et tørkeapparat til den rasler. Søtt paprikapulver er ingen erstatning i det hele tatt. Det gir fargen og sødmen, men ikke knasingen, og knasingen er hele poenget.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:60, u:'g', n:{en:'whole dried sweet peppers', no:'hele, tørkede søte paprika'},
     note:{en:'peperoni di Senise if you can get them; count on three or four pods a person, since they weigh almost nothing',
           no:'peperoni di Senise hvis du får tak i dem. Regn tre eller fire belger per person, for de veier nesten ingenting'}},
    {u:'', n:{en:'olive oil for frying', no:'olivenolje til steking'}, scale:'none'},
    {u:'', n:{en:'fine salt', no:'fint salt'}, scale:'none'},
  ]}],
  steps:[
    {en:'Wipe each pod with a dry cloth. Never rinse them: water in the oil steams the flesh, and steamed flesh turns leathery instead of crisp.',
     no:'Tørk av hver belg med et tørt klede. Skyll dem aldri, for vann i oljen damper kjøttet, og dampet kjøtt blir seigt i stedet for sprøtt.'},
    {en:'Pull off the stalk and shake the seeds out. Seeds burn before the flesh does and taste bitter.',
     no:'Dra av stilken og rist ut frøene. Frøene brenner før kjøttet gjør det, og de smaker bittert.'},
    {en:'Snap one to check. Any pod that bends rather than breaks goes into the oven at 50 °C for a quarter of an hour first.',
     no:'Knekk én for å kjenne etter. De belgene som bøyer seg i stedet for å knekke, skal først en tur i ovnen på 50 °C i et kvarter.'},
    {en:'Set a plate lined with kitchen paper beside the stove and a tray for the finished ones. Once the oil is hot there is no time to look for anything.',
     no:'Sett en tallerken med kjøkkenpapir ved siden av platen, og et fat til de ferdige. Når oljen først er varm, rekker du ikke å lete etter noe.'},
    {en:'Pour oil into a small deep pan to about three centimetres and heat it to 170 °C.',
     no:'Hell olje i en liten, dyp kjele til den står omtrent tre centimeter høyt, og varm den til 170 °C.'},
    {en:'Test it with a torn corner of a pod. It should sizzle at once and change colour within two seconds; if it sits still, the oil is too cold, and if it darkens instantly it is too hot.',
     no:'Prøv med et avrevet hjørne av en belg. Det skal frese med en gang og skifte farge i løpet av et par sekunder. Ligger det stille, er oljen for kald, og mørkner det med en gang, er den for varm.'},
    {en:'Lower one pod in, count to three, turn it over, count to two and lift it out. Fry one or two at a time and never crowd the pan.',
     no:'Senk ned én belg, tell til tre, snu den, tell til to, og løft den opp. Friter én eller to om gangen, og fyll aldri kjelen.'},
    {en:'Take each one out while it is still bright red. The colour goes on deepening after it leaves the oil, so a pod that looks right in the pan has already gone too far.',
     no:'Ta opp hver enkelt mens den fortsatt er knallrød. Fargen mørkner videre etter at belgen er løftet opp, så en belg som ser riktig ut i kjelen, har allerede gått for langt.'},
    {en:'Stand them hollow side down on the paper so the oil runs out of them, and salt them while they are hot.',
     no:'Sett dem med den hule siden ned på papiret, slik at oljen renner ut av dem, og salt dem mens de er varme.'},
    {en:'Leave them alone for a minute before you touch one. They crisp as they cool, not in the oil.',
     no:'La dem ligge i ro et minutt før du tar på dem. De blir sprø mens de kjølner, ikke i oljen.'},
    {en:'Taste one. Bitterness means the oil was too hot or the count too long, and nothing rescues it, so lower the heat and shorten the count for the next.',
     no:'Smak på én. Bitter smak betyr at oljen var for varm eller at du talte for lenge, og det lar seg ikke redde, så skru ned varmen og tell kortere på neste.'},
    {en:'Eat them the same day. In a jar with a lid they keep their crackle for a day or two and then soften.',
     no:'Spis dem samme dag. På glass med lokk holder de på sprøheten et døgn eller to, og så blir de myke.'},
  ],
  notes:[
    {title:{en:'The trick is the missing water', no:'Trikset ligger i vannet som mangler'},
     body:{en:'A Senise pepper has flesh of one and a half to two millimetres and hardly any water in it. The little that remains leaves as steam within seconds, and the flesh sets into a thin, glassy sheet. A fleshy pepper spends those same seconds steaming itself and comes out limp. The variety exists for this one purpose, which is why the reading treats the pepper and the dish as the same subject.',
           no:'En paprika fra Senise har et kjøtt på halvannen til to millimeter og nesten ikke vann i seg. Det lille som er igjen, forsvinner som damp i løpet av sekunder, og kjøttet stivner til et tynt, glassaktig skall. En kjøttfull paprika bruker de samme sekundene på å dampe seg selv og kommer opp slapp. Sorten finnes for dette ene formålet, og derfor behandler lesestykket paprikaen og retten som samme sak.'}},
    {title:{en:'Bitterness is burnt sugar', no:'Bitterheten er brent sukker'},
     body:{en:'The pod is sweet, and it is the sugar that browns. At 170 °C caramel and carbon are a second apart, and carbon tastes bitter right through the flesh. Nothing later in the dish covers it, so the count matters more than any other number here. Fry a single test pod before you commit the rest.',
           no:'Belgen er søt, og det er sukkeret som brunes. På 170 °C ligger karamell og kull ett sekund fra hverandre, og kull smaker bittert tvers gjennom kjøttet. Ingenting senere i retten dekker over det, så tellingen betyr mer enn noe annet tall her. Friter én prøvebelg før du ofrer resten.'}},
    {title:{en:'They set in the air', no:'De stivner i luften'},
     body:{en:'Straight out of the pan a crusco still bends a little; thirty seconds later it snaps. The structure sets as the last steam leaves and the sugar cools, exactly as a fritter does, so judge them by colour and by the count and never by biting one in the pan.',
           no:'Rett fra kjelen bøyer en crusco seg fortsatt litt, og tretti sekunder senere knekker den. Strukturen stivner mens den siste dampen slipper ut og sukkeret kjølner, akkurat som når noe annet friteres, så bedøm dem etter farge og telling, og aldri ved å bite i en mens den ligger i kjelen.'}},
  ],
  variations:[
    {title:{en:'Zafarana, the powder', no:'Zafarana, pulveret'},
     body:{en:'The other thing Senise does with the dried crop is grind it into a sweet red powder, called <em>zafarana</em> locally for its likeness to saffron. It goes on potatoes, on eggs, on beans and into sausage meat, and it keeps far longer than a fried pod does. A coffee grinder does the job in ten seconds.',
           no:'Senise gjør også noe annet med den tørkede avlingen. Den males til et søtt rødt pulver som folk her kaller <em>zafarana</em>, fordi det ligner safran. Pulveret brukes på poteter, på egg, på bønner og i pølsefarse, og det holder seg langt lenger enn en fritert belg. En kaffekvern gjør jobben på ti sekunder.'}},
    {title:{en:'In the oven, to learn the colour', no:'I ovnen, for å lære fargen'},
     body:{en:'Lay the pods on a tray, brush them very lightly with oil and give them five to seven minutes at 150 °C, turning once. They come out drier and duller, with a thicker crunch than the glassy one, but the oven is slow enough that you can watch the colour arrive. Learn it there, then risk the oil.',
           no:'Legg belgene på et brett, pensle dem svært lett med olje, og gi dem fem til sju minutter på 150 °C. Snu dem én gang. De blir tørrere og mattere, med en grovere knasing enn den glassaktige, men ovnen går langsomt nok til at du rekker å se fargen komme. Lær den der, og våg deg så på oljen.'}},
    {title:{en:'Where they go', no:'Hvor de havner'},
     body:{en:'The reading lists four uses and they are all worth having: eaten whole with a glass of Aglianico, crumbled over strascinati with fried breadcrumbs, laid on salt cod, or broken into scrambled eggs at the very last second. In every one of them the pepper goes on at the end, because it softens the moment it meets anything wet.',
           no:'Lesestykket nevner fire bruksmåter, og alle er verdt å prøve. Belgene spises hele til et glass Aglianico, smuldres over strascinati med ristede brødsmuler, legges på klippfisk eller brekkes ned i eggerøre helt til slutt. I alle tilfellene kommer paprikaen på til sist, for den blir myk i samme øyeblikk den møter noe vått.'}},
  ],
},

{
  id:'strascinati-con-peperoni-cruschi', dish:'Strascinati con peperoni cruschi e mollica', course:'primo', lesson:3, serves:4, time:{prep:60, cook:15},
  hero:'strascinati', tags:['pasta','pepper','breadcrumbs','no-egg'],
  title:{en:'Strascinati con peperoni cruschi e mollica', no:'Strascinati con peperoni cruschi e mollica'},
  blurb:{en:'The region’s signature plate: hand-dragged durum pasta, fried breadcrumbs where the cheese would be, and crumbled crisp peppers thrown on at the last second.',
         no:'Regionens signaturrett. Dradd durumpasta, ristede brødsmuler der osten ellers ville vært, og smuldret sprø paprika som strøs over helt til slutt.'},
  heroCaption:{en:'Strascinati con peperoni cruschi e mollica. Three cheap things, and one of the best plates in the south.',
               no:'Strascinati con peperoni cruschi e mollica. Tre billige råvarer, og en av de beste rettene i sør.'},
  wines:['Aglianico del Vulture'],
  headnote:{
    en:'<p>The reading calls this the region’s signature plate and lists its three ingredients: dragged pasta, crumbled fried peppers and toasted crumbs. None of them cost anything. The pasta is durum semolina and water, without egg, because eggs were sold rather than eaten. The peppers were hanging on the wall. And the crumbs are last week’s bread.</p>'
      + '<p><em>Mollica</em> is the mechanism worth understanding. Grated cheese does two things on a plate of pasta: it carries fat and it carries salt. Cheese cost money here, so stale bread was torn up and fried in oil instead, and fried crumb does both of those things and adds a third, a toasted flavour and a crunch that cheese cannot give. It has one more advantage nobody planned: crumb does not melt, so the plate stays dry and the peppers on top stay crisp. Southern Italy calls it <em>the poor man’s cheese</em>, and on this particular dish it is simply better than cheese.</p>'
      + '<p>Two things decide the result, and both are about timing. The crumbs go from gold to black inside the pan after you take it off the heat, so they are tipped straight out onto a cold plate. And the peppers go on at the table end of the process, never into the pan, because they soften the instant they touch anything wet.</p>',
    no:'<p>Lesestykket kaller dette regionens signaturrett og nevner de tre råvarene: dradd pasta, smuldret fritert paprika og ristede smuler. Ingen av dem kostet noe. Pastaen er durumsemule og vann, uten egg, for eggene ble solgt i stedet for spist. Paprikaen hang på veggen. Og smulene er brødet fra forrige uke.</p>'
      + '<p><em>Mollica</em> er mekanismen som er verdt å forstå. Revet ost gjør to ting på en tallerken pasta: den tilfører fett, og den tilfører salt. Ost kostet penger her, så gammelt brød ble revet opp og stekt i olje i stedet, og stekte smuler gjør begge deler og legger til en tredje ting, nemlig en ristet smak og en knasing osten ikke kan gi. De har dessuten en fordel ingen hadde planlagt. Smuler smelter ikke, så tallerkenen holder seg tørr og paprikaen på toppen holder seg sprø. I Sør-Italia kalles de fattigmannens ost, og på akkurat denne retten er de rett og slett bedre enn ost.</p>'
      + '<p>To ting avgjør resultatet, og begge handler om timing. Smulene går fra gyllent til svart inne i pannen etter at du har tatt den av platen, så de helles rett over på en kald tallerken. Og paprikaen kommer på helt til slutt, aldri ned i pannen, for den blir myk i samme sekund den møter noe vått.</p>'},
  ingredients:[
    { group:{en:'The pasta', no:'Pastaen'}, items:[
      {q:400, u:'g', n:{en:'durum semolina', no:'durumsemule'},
       note:{en:'the finely milled kind, semola rimacinata. Norwegian shops sell coarse semulegryn, which is not the same; ask an Italian or Turkish grocer for finely milled durum',
             no:'den finmalte typen, semola rimacinata. Norske butikker selger grovt semulegryn, og det er ikke det samme. Spør en italiensk eller tyrkisk butikk om finmalt durumhvete'}},
      {q:200, u:'ml', n:{en:'warm water', no:'varmt vann'}},
      {q:5, u:'g', n:{en:'salt', no:'salt'}},
    ]},
    { group:{en:'The mollica', no:'Mollicaen'}, items:[
      {q:120, u:'g', n:{en:'stale durum bread', no:'gammelt durumbrød'},
       note:{en:'crust cut off, torn or grated into uneven crumbs. Pane di Matera two or three days old is the original; any dense sourdough will do, but not a soft sandwich loaf',
             no:'skorpen skåret av, revet eller smuldret til ujevne smuler. Pane di Matera på to eller tre dager er originalen. Et hvilket som helst fast surdeigsbrød går an, men ikke et mykt formbrød'}},
      {q:60, u:'ml', n:{en:'olive oil', no:'olivenolje'}},
      {q:2, u:'', n:{en:'cloves of garlic', no:'hvitløksfedd'}, round:'half'},
    ]},
    { group:{en:'To finish', no:'Til servering'}, items:[
      {q:30, u:'g', n:{en:'whole dried sweet peppers', no:'hele, tørkede søte paprika'},
       note:{en:'peperoni di Senise; the first recipe in this chapter says where to find them and how to fry them',
             no:'peperoni di Senise. Den første oppskriften i dette kapitlet sier hvor du finner dem, og hvordan de friteres'}},
      {u:'', n:{en:'olive oil for frying the peppers', no:'olivenolje til å fritere paprikaen i'}, scale:'none'},
      {q:4, u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:25, u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
    ]},
  ],
  steps:[
    {en:'Work the semolina, the warm water and the salt into a firm dough and knead it for ten minutes, until it is smooth and slow to spring back. Rest it covered for half an hour.',
     no:'Arbeid semulen, det varme vannet og saltet til en fast deig, og elt den i ti minutter, til den er glatt og langsomt fjærer tilbake. La den hvile tildekket i en halvtime.'},
    {en:'Roll pieces of the dough into ropes about as thick as a finger and cut them into lengths of two centimetres.',
     no:'Rull deigbiter til pølser omtrent så tykke som en finger, og skjær dem i biter på to centimeter.'},
    {en:'Press each piece against the board with two fingers and drag it towards you, so that it curls over into a rough cup with a ridged back. Lay the finished ones on a semolina-dusted cloth without letting them touch.',
     no:'Trykk hver bit mot brettet med to fingre og dra den mot deg, slik at den krøller seg til en ru skål med rillet rygg. Legg de ferdige på et klede drysset med semule, uten at de rører hverandre.'},
    {en:'Tear or grate the bread into uneven crumbs. Even crumbs behave like sand and disappear into the oil; uneven ones stay visible on the plate.',
     no:'Riv eller smuldre brødet til ujevne smuler. Jevne smuler oppfører seg som sand og forsvinner i oljen, mens ujevne smuler blir liggende synlige på tallerkenen.'},
    {en:'Warm the oil with the sliced garlic over low heat until the garlic smells and is pale gold, then lift the garlic out and keep it.',
     no:'Varm oljen med den skivede hvitløken på svak varme til hvitløken dufter og er lysegyllen, og løft den så ut og ta vare på den.'},
    {en:'Turn the crumbs into the same oil over medium heat and stir them without stopping for three or four minutes, until they are deep gold and smell of toast.',
     no:'Ha smulene i den samme oljen på middels varme, og rør uten å stoppe i tre eller fire minutter, til de er dypt gyllenbrune og lukter ristet brød.'},
    {en:'Tip them straight out onto a cold plate. Left in the pan they go from gold to black on the stored heat alone.',
     no:'Hell dem rett over på en kald tallerken. Blir de liggende i pannen, går de fra gyllent til svart på ettervarmen alene.'},
    {en:'Fry the peppers for three seconds a side at 170 °C, drain them hollow side down, salt them and break most of them into pieces the size of a thumbnail.',
     no:'Friter paprikaen ved 170 °C i tre sekunder på hver side, la den renne av med den hule siden ned, salt den, og brekk det meste av den i biter på størrelse med en tommelnegl.'},
    {en:'Bring the water to the boil, salt it and cook the pasta for five to seven minutes, until the pieces float and the thick ridge is tender.',
     no:'Kok opp vannet, salt det, og kok pastaen i fem til sju minutter, til bitene flyter opp og den tykke rillen er myk.'},
    {en:'Keep a cupful of the cooking water back and drain the pasta.',
     no:'Ta vare på litt av kokevannet, og hell av pastaen.'},
    {en:'Turn the pasta with the garlic oil and a splash of the cooking water in a wide pan with the pan off the heat, until every piece is glossy.',
     no:'Vend pastaen med hvitløksoljen og en skvett kokevann i en vid panne, med pannen av platen, til hver bit skinner av olje.'},
    {en:'Stir half the crumbs through it, put it on warm plates, and scatter the rest of the crumbs and all the peppers over the top.',
     no:'Rør halvparten av smulene inn i den, fordel pastaen på varme tallerkener, og strø resten av smulene og all paprikaen over.'},
    {en:'Carry it out at once. The crumbs are crisp for about five minutes and the peppers for rather less.',
     no:'Bær den ut med en gang. Smulene er sprø i omtrent fem minutter, og paprikaen i enda kortere tid.'},
  ],
  notes:[
    {title:{en:'Why crumb beats cheese here', no:'Derfor slår smulene osten her'},
     body:{en:'Grated cheese gives fat and salt and then melts, which wets the plate. Fried crumb gives the same fat and salt, adds the flavour of toasted wheat, and stays dry. On a dish whose whole point is a crisp pepper sitting on top, the dry topping is the better one, and the poverty that produced it turned out to be an improvement. Keep a jar of it in the cupboard; it goes on anything.',
           no:'Revet ost gir fett og salt, og så smelter den, og da blir tallerkenen våt. Stekte smuler gir det samme fettet og saltet, legger til smaken av ristet hvete, og holder seg tørre. På en rett som handler om en sprø paprika på toppen, er det tørre toppdrysset det beste, og fattigdommen som skapte det, viste seg å være en forbedring. Ha et glass av det stående i skapet, for det passer på det meste.'}},
    {title:{en:'What the drag does', no:'Hva draget gjør'},
     body:{en:'<em>Strascinare</em> means to drag. Pulling the dough down the board thins one wall, roughens the outside against the wood and leaves a curved shell with a thick ridge along the back. The hollow catches oil and crumbs, the rough surface holds them, and the ridge gives the bite that a semolina-and-water dough needs if it is not to eat like a noodle. This is why the shape is made by hand and not by a machine.',
           no:'<em>Strascinare</em> betyr å dra. Når deigen dras nedover brettet, blir den ene veggen tynnere og utsiden ru mot treverket, og resultatet er et buet skall med en tykk rille langs ryggen. Hulrommet fanger olje og smuler, den ru overflaten holder på dem, og rillen gir den tyggemotstanden som en deig av semule og vann trenger for ikke å spises som en nudel. Derfor formes pastaen for hånd og ikke med maskin.'}},
    {title:{en:'The peppers go on last', no:'Paprikaen kommer på til slutt'},
     body:{en:'A crusco is dry sugar and dry flesh, and it drinks moisture out of the air, never mind out of a hot pan. Fold it through the pasta and within a minute it is a soft red rag. Break it over the plate at the table end instead, and keep a few whole ones on top so that people can see what they are eating.',
           no:'En crusco er tørt sukker og tørt kjøtt, og den trekker til seg fuktighet fra luften, for ikke å snakke om fra en varm panne. Vender du den inn i pastaen, er den en myk rød fille etter et minutt. Brekk den heller over tallerkenen helt til slutt, og la noen hele ligge på toppen, slik at folk ser hva de spiser.'}},
  ],
  variations:[
    {title:{en:'Other shapes from the same dough', no:'Andre former av samme deig'},
     body:{en:'The reading names three: strascinati, cavatelli, and <em>ferricelli</em> rolled around an iron rod. Cavatelli are the same pieces hollowed with the thumb instead of dragged, and ferricelli are ropes wound around a knitting needle and slipped off. Bought orecchiette will carry the sauce well enough if you have no hour to spare, and nobody in Basilicata would mind.',
           no:'Lesestykket nevner tre: strascinati, cavatelli og <em>ferricelli</em>, som rulles rundt en jernpinne. Cavatelli er de samme bitene hulet ut med tommelen i stedet for dradd, og ferricelli er deigpølser viklet rundt en strikkepinne og trukket av. Kjøpte orecchiette bærer sausen godt nok om du ikke har en time til overs, og ingen i Basilicata ville hatt noe imot det.'}},
    {title:{en:'With an anchovy', no:'Med ansjos'},
     body:{en:'Melt a salted anchovy or two into the warm garlic oil before the crumbs go in and let it dissolve completely. The dish gains depth and loses nothing, and it is what a household does when there is no cheese and the peppers have run low.',
           no:'La en eller to saltede ansjoser smelte i den varme hvitløksoljen før smulene kommer i, og rør til de er helt oppløst. Retten får mer dybde og mister ingenting, og slik gjør en husholdning det når osten mangler og paprikaen begynner å ta slutt.'}},
    {title:{en:'The version with cheese', no:'Utgaven med ost'},
     body:{en:'Restaurants now serve it with grated pecorino or a spoon of soft <em>cacioricotta</em> under the pasta. It is richer and it tastes good, but the crumbs then have to fight the cheese for the same job, and the peppers soften faster on a wet plate. Try it once, both ways, on the same evening.',
           no:'Restauranter serverer den i dag med revet pecorino eller en skje myk <em>cacioricotta</em> under pastaen. Den blir fyldigere og smaker godt, men da må smulene kjempe med osten om den samme jobben, og paprikaen blir fortere myk på en våt tallerken. Prøv begge deler samme kveld.'}},
  ],
},

{
  id:'pane-di-matera', dish:'Pane di Matera', course:'base', lesson:3, serves:8, time:{prep:180, cook:60},
  hero:'pane', tags:['bread','sourdough','durum','oven'],
  title:{en:'Pane di Matera', no:'Pane di Matera'},
  blurb:{en:'Durum semolina, a sourdough mother, salt and water. A tall, almost black-crusted loaf with a straw-yellow crumb, built to stay good for a week.',
         no:'Durumsemule, en surdeigskultur, salt og vann. Et høyt brød med nesten svart skorpe og stråfarget krumme, som er laget for å holde seg godt i en uke.'},
  heroCaption:{en:'Pane di Matera on a table outside a shop. The high crest and the near-black ridges come from the shaping and a very hot oven, not from a slash.',
               no:'Pane di Matera på et bord utenfor en butikk. Den høye kammen og de nesten svarte ryggene kommer av formingen og en svært varm ovn, ikke av et snitt.'},
  wines:['Matera DOC Primitivo'],
  headnote:{
    en:'<p>Pane di Matera has been an IGP since 2008, and the rules are short: durum semolina from local wheats, a natural sourdough mother, salt and water, and nothing else. The loaf weighs one to two kilos, it is shaped either as a high dome or as a <em>cornetto</em>, a horn, and the crust must be at least three millimetres thick. Inside it is straw yellow and full of irregular holes. A one-kilo loaf keeps a week and a two-kilo loaf nine days, which was the entire point: families baked once a week in the communal oven and stamped each loaf with a carved seal so that the loaves could be told apart coming out.</p>'
      + '<p>Be honest about what this is. It is a two-day bake with a sourdough that has to be awake, a dough of pure durum that handles like nothing you are used to, and an oven that cannot match a wood-fired chamber holding heat in its floor. A domestic oven can get close with a cast-iron pot, which traps the loaf’s own steam for the first half hour and gives the bottom heat that makes the crust. What it cannot do is a two-kilo loaf, so this recipe makes one of about a kilo.</p>'
      + '<p>Durum is the part to respect. It drinks water slowly, so it wants a rest before the kneading starts; its gluten is strong but short, so it takes longer to come smooth and it never becomes springy like a bread-flour dough; and its pigment is what makes the crumb yellow. It is also why the loaf keeps. Semolina holds moisture longer than white wheat flour, the acidity of the sourdough slows staling further, and a crust three millimetres thick is a wall the water cannot cross.</p>',
    no:'<p>Pane di Matera har vært IGP siden 2008, og reglene er korte: durumsemule av lokale hvetesorter, en naturlig surdeigskultur, salt og vann, og ikke noe annet. Brødet veier én til to kilo, det formes enten som en høy kuppel eller som en <em>cornetto</em>, et horn, og skorpen skal være minst tre millimeter tykk. Inni er brødet stråfarget og fullt av ujevne hull. Et brød på én kilo holder seg en uke, og et på to kilo i ni dager, og det var hele poenget. Familiene bakte én gang i uken i den felles ovnen og stemplet hvert brød med et utskåret segl, slik at brødene kunne skilles fra hverandre når de kom ut.</p>'
      + '<p>La oss være ærlige om hva dette er. Det er en bakst over to dager, med en surdeig som må være i full gang, en deig av ren durum som oppfører seg helt annerledes enn det du er vant til, og en stekeovn som ikke kan måle seg med et vedfyrt bakerom som holder på varmen i gulvet. En vanlig stekeovn kommer et stykke på vei med en støpejernsgryte, som holder på brødets egen damp den første halvtimen og gir undervarmen skorpen trenger. Et brød på to kilo klarer den likevel ikke, så denne oppskriften gir ett på omtrent en kilo.</p>'
      + '<p>Durumen krever respekt. Den drikker vann langsomt og vil derfor ha en hvil før eltingen begynner. Glutenet er sterkt, men kort, så deigen bruker lengre tid på å bli glatt og blir aldri spenstig slik en deig av sterkt hvetemel blir. Fargestoffet i durumen gjør krummen gul. Durumen er også grunnen til at brødet holder seg. Semule holder lenger på fuktigheten enn siktet hvetemel, syren fra surdeigen bremser tørkingen ytterligere, og en skorpe på tre millimeter er en vegg vannet ikke kommer gjennom.</p>'},
  ingredients:[
    { group:{en:'The starter, the evening before', no:'Fordeigen, kvelden før'}, items:[
      {q:150, u:'g', n:{en:'durum semolina', no:'durumsemule'}},
      {q:90, u:'ml', n:{en:'lukewarm water', no:'lunkent vann'}},
      {q:30, u:'g', n:{en:'active sourdough starter', no:'aktiv surdeigskultur'},
       note:{en:'refreshed twice in the two days before, so that it doubles within six hours. A sleepy starter cannot lift a durum dough',
             no:'matet to ganger i løpet av de to foregående dagene, slik at den dobler seg i løpet av seks timer. En treg surdeig klarer ikke å heve en durumdeig'}},
    ]},
    { group:{en:'The dough', no:'Deigen'}, items:[
      {q:500, u:'g', n:{en:'durum semolina', no:'durumsemule'},
       note:{en:'semola rimacinata, the finely reground kind. Norwegian semulegryn is milled far too coarse and gives a gritty crumb; ask an Italian or Turkish grocer for finely milled durum, or use half strong wheat flour for a first attempt',
             no:'semola rimacinata, den finmalte typen. Norsk semulegryn er malt altfor grovt og gir en grynet krumme. Spør en italiensk eller tyrkisk butikk om finmalt durumhvete, eller bruk halvt om halvt med sterkt hvetemel første gangen'}},
      {q:330, u:'ml', n:{en:'water', no:'vann'}, note:{en:'at about 25 °C', no:'på omtrent 25 °C'}},
      {q:14, u:'g', n:{en:'salt', no:'salt'}},
      {u:'', n:{en:'semolina for the cloth and the board', no:'semule til kledet og bakebordet'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Stir the starter into the lukewarm water the evening before, work in the semolina for it, cover the bowl and leave it at room temperature for ten to twelve hours, until it has domed and smells sharp rather than sour.',
     no:'Rør surdeigskulturen ut i det lunkne vannet kvelden før, arbeid inn semulen som hører til, dekk bollen, og la den stå i romtemperatur i ti til tolv timer, til den hvelver seg og lukter friskt og syrlig, ikke surt.'},
    {en:'In the morning mix the semolina for the dough with all but a little of the water, and leave it covered for half an hour without kneading. Durum needs that time to take the water up.',
     no:'Om morgenen blander du semulen til deigen med alt vannet bortsett fra en liten rest, og lar den stå tildekket i en halvtime uten å elte. Durum trenger den tiden på å ta opp vannet.'},
    {en:'Work the risen starter into the dough until no streaks are left, then add the salt with the last of the water.',
     no:'Arbeid den hevede fordeigen inn i deigen til det ikke er striper igjen, og ha så i saltet sammen med resten av vannet.'},
    {en:'Knead for twelve to fifteen minutes. The dough turns from crumbly to smooth and dense, and it will feel tighter and less elastic than a wheat dough; that is durum behaving normally.',
     no:'Elt i tolv til femten minutter. Deigen går fra smuldrete til glatt og tett, og den kjennes fastere og mindre elastisk ut enn en hvetedeig. Slik oppfører durum seg normalt.'},
    {en:'Cover it and let it rise for three to four hours at about 24 °C, folding it over on itself once an hour for the first two hours, until it has doubled and the surface is domed and blistered.',
     no:'Dekk deigen til og la den heve i tre til fire timer på omtrent 24 °C. Brett den over seg selv én gang i timen de to første timene, til den har doblet seg og overflaten er hvelvet og full av blemmer.'},
    {en:'Turn it onto a lightly floured board, flatten it into an oval, fold the far third over the middle and then the near third over that, and let it rest for twenty minutes.',
     no:'Tipp den ut på et lett melet bakebord, klapp den flat til en oval, brett den fjerneste tredjedelen inn over midten og deretter den nærmeste tredjedelen over den igjen, og la den hvile i tjue minutter.'},
    {en:'Roll it up tightly from the long side into a thick cylinder, pinch the seam shut, then fold the cylinder over on itself so that it stands high and short rather than long.',
     no:'Rull den stramt sammen fra langsiden til en tykk sylinder, klyp sømmen igjen, og brett så sylinderen over seg selv, slik at deigen står høy og kort i stedet for lang.'},
    {en:'Set it seam upwards in a basket or bowl lined with a cloth and dusted heavily with semolina, cover it and prove it for an hour and a half to two hours, until a fingertip leaves a dent that fills back slowly.',
     no:'Sett den med sømmen opp i en kurv eller bolle kledd med et klede og drysset godt med semule, dekk den til, og la den heve i halvannen til to timer, til et fingertrykk etterlater en fordypning som langsomt fyller seg igjen.'},
    {en:'Heat the oven to 250 °C with a cast-iron pot and its lid inside, and give it a full hour. The stored heat in the iron is the nearest a kitchen gets to a stone floor.',
     no:'Varm ovnen til 250 °C med en støpejernsgryte og lokket til den inni, og gi den en hel time. Varmen som lagres i jernet, er det nærmeste et kjøkken kommer et steingulv.'},
    {en:'Tip the loaf seam downwards into the hot pot, put the lid on and bake for twenty-five minutes. Do not slash it: the crest opens along the fold by itself.',
     no:'Vipp brødet med sømmen ned i den varme gryten, legg på lokket, og stek i tjuefem minutter. Ikke snitt det, for kammen åpner seg langs bretten av seg selv.'},
    {en:'Take the lid off, drop the heat to 220 °C and bake for another thirty to thirty-five minutes, until the crust is dark brown and nearly black along the ridges and the base sounds hollow.',
     no:'Ta av lokket, skru ned til 220 °C, og stek videre i tretti til trettifem minutter, til skorpen er mørkebrun og nesten svart langs ryggene, og bunnen høres hul ut.'},
    {en:'Cool it on a rack for at least four hours before it is cut. The crumb is still setting, and a loaf opened hot goes gummy and then stales in a day.',
     no:'La brødet kjølne på rist i minst fire timer før du skjærer i det. Krummen holder fortsatt på å stivne, og et brød som åpnes varmt, blir klissent og tørker ut i løpet av et døgn.'},
  ],
  notes:[
    {title:{en:'The crust is the preservative', no:'Skorpen er konserveringsmiddelet'},
     body:{en:'Bread goes stale because water leaves the crumb and because the starch recrystallises. A big loaf has little surface for its volume, and a crust three millimetres thick is a barrier the water crosses slowly, which is why the rule is written as a thickness and why the IGP grades the keeping time by weight. Bake this dough as four small rolls and it will be dry the next morning.',
           no:'Brød tørker ut fordi vannet forlater krummen, og fordi stivelsen krystalliserer seg på nytt. Et stort brød har lite overflate i forhold til volumet, og en skorpe på tre millimeter er en barriere vannet bare langsomt kommer gjennom. Derfor er regelen skrevet som en tykkelse, og derfor gir IGP-en ulik holdbarhet etter vekt. Baker du den samme deigen som fire små rundstykker, er de tørre neste morgen.'}},
    {title:{en:'Sourdough, not yeast', no:'Surdeig, ikke gjær'},
     body:{en:'The mother is in the rules, and not only for flavour. The acids a sourdough leaves behind slow the staling of the starch and hold mould off for days, which is what lets a household bake once a week. Baker’s yeast would raise this dough in a third of the time and give you a loaf that is ordinary on the third day.',
           no:'Surdeigskulturen står i regelverket, og ikke bare for smakens skyld. Syrene som en surdeig legger igjen, bremser tørkingen av stivelsen og holder mugg unna i dagevis, og nettopp det gjør at en husholdning kan bake én gang i uken. Bakegjær ville hevet deigen på en tredjedel av tiden og gitt deg et brød som er helt alminnelig på tredje dagen.'}},
    {title:{en:'Steam first, then dry heat', no:'Først damp, så tørr varme'},
     body:{en:'Under the lid the loaf boils off its own water, the surface stays damp and elastic, and the bread can rise to its full height before anything sets. Off comes the lid and the same surface dries, browns and thickens into the crust. Run it dry from the start and the skin sets in the first five minutes, and the loaf tears at the side instead of opening at the crest.',
           no:'Under lokket blir brødets eget vann til damp, overflaten holder seg fuktig og elastisk, og brødet rekker å heve seg til full høyde før noe stivner. Når lokket går av, tørker den samme overflaten, brunes og tykner til skorpe. Steker du tørt fra starten, stivner overflaten de første fem minuttene, og brødet revner på siden i stedet for å åpne seg i kammen.'}},
  ],
  variations:[
    {title:{en:'The cornetto', no:'Cornettoen'},
     body:{en:'The horn is the older of the two shapes. Roll the dough into a thick cylinder, taper both ends, curve it into a wide crescent and prove it on a cloth with the curve held open. It bakes faster than the dome because it is thinner, and it gives more crust for the same weight of dough, which some households preferred.',
           no:'Hornet er den eldste av de to formene. Rull deigen til en tykk sylinder, gjør begge endene smalere, bøy den til en vid halvmåne, og la den heve på et klede med buen holdt åpen. Den steker fortere enn kuppelen fordi den er tynnere, og den gir mer skorpe på samme deigmengde, noe enkelte husholdninger satte pris på.'}},
    {title:{en:'Half durum for a first attempt', no:'Halvt om halvt første gangen'},
     body:{en:'Replace half the semolina in the dough with strong wheat flour. The dough handles like bread dough, rises higher and is far harder to ruin; the crumb comes out paler and the keeping quality drops to three or four days. Bake it once that way to learn the shaping, then go back to pure durum.',
           no:'Bytt ut halvparten av semulen i deigen med sterkt hvetemel. Deigen oppfører seg som en vanlig brøddeig, hever høyere og er langt vanskeligere å ødelegge. Krummen blir lysere, og holdbarheten faller til tre eller fire dager. Bak den slik én gang for å lære formingen, og gå så tilbake til ren durum.'}},
    {title:{en:'When it is a week old', no:'Når det er en uke gammelt'},
     body:{en:'Nothing is thrown away. Torn up and fried in oil, the crumb becomes the <em>mollica</em> that goes on the strascinati in this same chapter, and the crust softened in water and oil is the base of half the region’s salads and soups. A loaf this size is not really finished until the day it becomes something else.',
           no:'Ingenting kastes. River du opp krummen og steker den i olje, får du den <em>mollicaen</em> som strøs over strascinatiene i det samme kapitlet. Skorpen, som bløtes opp i vann og olje, er grunnlaget for halvparten av salatene og suppene i regionen. Et brød av denne størrelsen er egentlig ikke ferdig før den dagen det blir til noe annet.'}},
  ],
},

{
  id:'lagane-e-ceci', dish:'Lagane e ceci', course:'primo', lesson:3, serves:4, time:{prep:50, cook:120},
  hero:'lagane', tags:['pasta','chickpeas','no-egg','one-pot'],
  title:{en:'Lagane e ceci', no:'Lagane e ceci'},
  blurb:{en:'Wide hand-cut ribbons of durum pasta cooked in the chickpeas’ own broth, so that the pasta thickens its own sauce. No meat, no cheese, no stock.',
         no:'Brede, håndskårne bånd av durumpasta kokt i kraften fra kikertene, slik at pastaen tykner sin egen saus. Uten kjøtt, uten ost og uten buljong.'},
  heroCaption:{en:'Lagane e ceci photographed at Cosenza, just over the Calabrian border. The plate is shared across the whole south and the Lucanian one looks the same.',
               no:'Lagane e ceci fotografert i Cosenza, like over grensen til Calabria. Retten er felles for hele Sør-Italia, og den lucanske utgaven ser lik ut.'},
  wines:['Grottino di Roccanova'],
  headnote:{
    en:'<p>The food reading for Basilicata is about the dried peppers, the bread of Matera and the pig. It does not mention this dish, and it should be said plainly rather than glossed over. What the reading does give is everything the dish is made of: pasta of durum and water without egg, rolled or dragged by hand, and a kitchen in which a pulse stood in for the meat that was not there.</p>'
      + '<p>The name is the oldest thing on the table. <em>Laganum</em> was a sheet of dough in Latin, and the poet <strong>Horace</strong>, born at Venosa in this region in 65 BC, wrote of going home to a bowl of leeks, chickpeas and <em>lagana</em>. Whether that dish was boiled or baked is argued over, but the word survived in the south as the name of a wide, flat, hand-cut ribbon, and it is still cut that way: short lengths a couple of centimetres across, thick enough to stand up to a long-cooked pulse.</p>'
      + '<p>The method is the part that matters. There is no cheese in this and no stock cube. The pasta is boiled in the chickpea broth itself, so the starch that would have gone down the sink thickens the pot instead, and the chickpea water — which carries all the flavour the chickpeas gave up in two hours — becomes the sauce. Drain the pasta separately and you are eating pasta with chickpeas on it, which is a different and much thinner thing.</p>',
    no:'<p>Lesestykket om maten i Basilicata handler om den tørkede paprikaen, brødet fra Matera og grisen. Denne retten er ikke nevnt der, og det er bedre å si det rett ut enn å gå rundt det. Lesestykket gir likevel alt som retten er laget av: pasta av durum og vann uten egg, kjevlet eller dradd for hånd, og et kjøkken der belgfrukter måtte tre inn for kjøttet som ikke fantes.</p>'
      + '<p>Navnet er det eldste på bordet. <em>Laganum</em> var en deigplate på latin, og dikteren <strong>Horats</strong>, som ble født i Venosa i denne regionen i år 65 f.Kr., skrev om å komme hjem til en skål med purre, kikerter og <em>lagana</em>. De lærde strides om den retten ble kokt eller bakt, men ordet overlevde i sør som navn på et bredt, flatt bånd som skjæres for hånd. Slik skjæres det fortsatt, i korte lengder som er et par centimeter brede og tykke nok til å tåle en belgfrukt som har kokt lenge.</p>'
      + '<p>Metoden betyr mest. Retten har verken ost eller buljongterning. Pastaen kokes i selve kikertkraften, slik at stivelsen som ellers ville havnet i vasken, tykner gryten i stedet, og kikertvannet, som bærer all smaken kikertene har gitt fra seg på to timer, blir sausen. Koker du pastaen for seg og heller av, spiser du pasta med kikerter oppå, og det er noe annet og langt tynnere.</p>'},
  ingredients:[
    { group:{en:'The chickpeas', no:'Kikertene'}, items:[
      {q:300, u:'g', n:{en:'dried chickpeas', no:'tørkede kikerter'},
       note:{en:'soaked for twelve hours in plenty of cold water. Old chickpeas never soften, so buy from a shop that sells a lot of them',
             no:'lagt i bløt i tolv timer i rikelig kaldt vann. Gamle kikerter blir aldri myke, så kjøp dem et sted der de selger mange av dem'}},
      {q:1.5, u:'l', n:{en:'water', no:'vann'}},
      {q:2, u:'', n:{en:'cloves of garlic', no:'hvitløksfedd'}, round:'half'},
      {q:2, u:'', n:{en:'bay leaves', no:'laurbærblader'}, round:'half'},
      {q:1, u:'', n:{en:'small dried chilli', no:'liten tørket chili'}, round:'half'},
      {q:40, u:'ml', n:{en:'olive oil', no:'olivenolje'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'The lagane', no:'Lagane'}, items:[
      {q:250, u:'g', n:{en:'durum semolina', no:'durumsemule'},
       note:{en:'finely milled durum, semola rimacinata. Ask for it at an Italian or Turkish grocer; Norwegian semulegryn is too coarse',
             no:'finmalt durumhvete, semola rimacinata. Spør etter den i en italiensk eller tyrkisk butikk, for norsk semulegryn er for grovt'}},
      {q:125, u:'ml', n:{en:'warm water', no:'varmt vann'}},
      {q:4, u:'g', n:{en:'salt', no:'salt'}},
    ]},
    { group:{en:'To finish', no:'Til servering'}, items:[
      {q:30, u:'ml', n:{en:'olive oil', no:'olivenolje'}, note:{en:'raw, over the bowl', no:'rå, over skålen'}},
      {q:20, u:'g', n:{en:'whole dried sweet peppers', no:'hele, tørkede søte paprika'},
       note:{en:'optional but Lucanian: fried for seconds as in the first recipe and crumbled on top', no:'valgfritt, men lucansk. De friteres i sekunder som i den første oppskriften og smuldres over'}},
    ]},
  ],
  steps:[
    {en:'Drain the soaked chickpeas and rinse them, then put them in a heavy pot with the fresh water, the garlic, the bay and the chilli.',
     no:'Hell av bløtvannet og skyll kikertene, og legg dem i en tykkbunnet gryte med friskt vann, hvitløk, laurbær og chili.'},
    {en:'Bring them to a bare simmer and cook them covered for an hour and a half to two hours, skimming the foam off in the first ten minutes. They are done when one crushes to a cream between two fingers.',
     no:'Kok opp forsiktig og la dem trekke under lokk i halvannen til to timer. Skum av de første ti minuttene. De er ferdige når én lar seg mose til en krem mellom to fingre.'},
    {en:'Salt them only in the last quarter of an hour, and keep anything acid out of the pot until they are soft. Tomato or lemon added early leaves the skins tough for good.',
     no:'Salt dem først det siste kvarteret, og hold alt som er surt, unna gryten til de er myke. Tomat eller sitron som kommer i for tidlig, gjør skallene seige for godt.'},
    {en:'While they cook, work the semolina, the warm water and the salt for the pasta into a firm dough, knead it for ten minutes and let it rest covered for half an hour.',
     no:'Mens de koker, arbeider du semulen, det varme vannet og saltet til en fast pastadeig. Elt den i ti minutter, og la den hvile tildekket i en halvtime.'},
    {en:'Roll the dough out to about a millimetre and a half, dust it well, fold it loosely and cut ribbons two centimetres wide, then cut across them into lengths of about six centimetres.',
     no:'Kjevle deigen ut til rundt halvannen millimeter, mel den godt, brett den løst sammen, og skjær bånd på to centimeter. Skjær så på tvers i lengder på omtrent seks centimeter.'},
    {en:'Shake the ribbons apart on a cloth dusted with semolina and leave them in a single layer. Stacked, they weld together within the hour.',
     no:'Rist båndene fra hverandre på et klede drysset med semule, og la dem ligge i ett lag. Stabler du dem, klistrer de seg sammen i løpet av en time.'},
    {en:'Lift a ladleful of the cooked chickpeas out, crush them to a paste and stir them back in. That is all the thickening the dish gets before the pasta.',
     no:'Ta opp en øse med ferdigkokte kikerter, mos dem til en jevn masse, og rør dem tilbake i gryten. Retten får ikke mer jevning enn det før pastaen kommer i.'},
    {en:'Fish out the bay and the garlic, pour in the olive oil and taste the broth. It should taste finished on its own, because nothing else is coming.',
     no:'Fisk opp laurbæret og hvitløken, hell i olivenoljen, og smak på kraften. Den skal smake ferdig i seg selv, for det kommer ikke noe mer.'},
    {en:'Loosen the pot with hot water until the chickpeas swim freely. The pasta needs room and it will drink a good deal as it cooks.',
     no:'Spe gryten med varmt vann til kikertene flyter fritt. Pastaen trenger plass, og den drikker en god del mens den koker.'},
    {en:'Bring it back to a gentle boil, slide the lagane in a few at a time, stirring, and cook them for five or six minutes, until they are tender and the broth has turned silky.',
     no:'Kok opp igjen på rolig varme, og la lagane gli ned noen få om gangen mens du rører. Kok dem i fem eller seks minutter, til de er myke og kraften er blitt silkeaktig.'},
    {en:'Take the pot off the heat and let it stand for two minutes. It thickens as it settles, so stop while it still looks a shade too loose.',
     no:'Ta gryten av platen og la den stå i to minutter. Den tykner mens den faller til ro, så stopp mens den fortsatt ser en anelse for løs ut.'},
    {en:'Serve it in warm bowls with raw olive oil poured over, and crumble a fried pepper on each if you have them.',
     no:'Server retten i varme skåler med rå olivenolje over, og smuldre en fritert paprika over hver porsjon om du har noen.'},
  ],
  notes:[
    {title:{en:'Why the pasta cooks in the pot', no:'Derfor kokes pastaen i gryten'},
     body:{en:'There is no cheese here, no butter and no meat, so the body of the dish has to come from starch. Pasta boiled in a separate pan gives that starch to the drain; pasta boiled in the chickpea broth gives it to the broth, which turns from cloudy water into something that coats a spoon. It is the same principle as risotto, worked with a pulse instead of rice.',
           no:'Retten har verken ost, smør eller kjøtt, så fylden må komme fra stivelse. Pasta som kokes i en egen kjele, gir stivelsen til vasken, mens pasta som kokes i kikertkraften, gir den til kraften, som går fra grumsete vann til noe som legger seg rundt skjeen. Prinsippet er det samme som i risotto, bare med belgfrukter i stedet for ris.'}},
    {title:{en:'Wide and thick on purpose', no:'Brede og tykke med vilje'},
     body:{en:'A ribbon two centimetres across and a millimetre and a half thick takes five or six minutes and survives being stirred in a heavy pot. Tagliatelle would be soft in two and would break into threads among the chickpeas. The shape is cut to match the thing it is cooked with, which is true of nearly every pasta worth making by hand.',
           no:'Et bånd på to centimeter i bredden og halvannen millimeter i tykkelsen bruker fem eller seks minutter og tåler å bli rørt rundt i en tung gryte. Tagliatelle ville vært myk på to minutter og gått i tråder blant kikertene. Formen er skåret for å passe det den kokes sammen med, og det gjelder nesten all pasta som er verdt å lage for hånd.'}},
    {title:{en:'Salt late, acid later still', no:'Salt sent, syre enda senere'},
     body:{en:'A chickpea skin is pectin, and acid sets pectin hard. Tomato, vinegar or lemon in the pot before the pulse is soft will keep it firm however long it boils, which is the usual reason chickpeas are blamed for being old. Salt is less dangerous than that reputation suggests, but adding it late costs nothing and lets you taste the broth as it concentrates.',
           no:'Skallet på en kikert består av pektin, og syre stivner pektin. Tomat, eddik eller sitron i gryten før belgfrukten er myk, holder den fast uansett hvor lenge den koker, og det er den vanligste grunnen til at kikerter får skylden for å være gamle. Salt er mindre farlig enn ryktet vil ha det til, men å ha det i sent koster ingenting og lar deg smake på kraften mens den trekker seg sammen.'}},
  ],
  variations:[
    {title:{en:'From a tin, honestly', no:'Fra boks, ærlig talt'},
     body:{en:'Tinned chickpeas cook in five minutes and give you no broth, which is the whole sauce. If that is the evening you are having, crush a third of them into a light vegetable stock, simmer it for a quarter of an hour with the garlic, bay and chilli to give it something to say, and cook the pasta in that. It is a good supper and it is not the same dish.',
           no:'Kikerter på boks er ferdige på fem minutter og gir ingen kraft, og kraften er hele sausen. Er det en slik kveld, kan du mose en tredjedel av dem ut i en lys grønnsakskraft, la den småkoke et kvarter med hvitløk, laurbær og chili så den får noe å si, og koke pastaen i den. Det blir et godt kveldsmåltid, men det er ikke den samme retten.'}},
    {title:{en:'Lagane e fagioli', no:'Lagane e fagioli'},
     body:{en:'The same plate with borlotti or cannellini beans instead, which cook faster and break down further, so the broth comes out creamier and paler. Everything else is unchanged. In the mountains the two were made from whatever the household had dried that year.',
           no:'Den samme retten med borlotti- eller cannellinibønner i stedet. De koker fortere og faller mer fra hverandre, så kraften blir kremet og lysere. Alt annet er likt. I fjellene laget husholdningene den ene eller den andre ut fra hva de hadde tørket det året.'}},
    {title:{en:'The Lucanian finish', no:'Den lucanske avslutningen'},
     body:{en:'A crumbled crusco on top is what makes this plate belong here rather than anywhere else in the south, and a spoon of fried breadcrumbs beside it does the same job the other way. Both go on at the table, and neither should ever be stirred in.',
           no:'En smuldret crusco på toppen gjør at retten hører hjemme nettopp her og ikke et annet sted i sør, og en skje ristede brødsmuler ved siden av gjør den samme jobben på en annen måte. Begge deler kommer på ved bordet, og ingen av dem skal røres inn.'}},
  ],
},

{
  id:'baccala-con-peperoni-cruschi', dish:'', course:'secondo', lesson:3, serves:4, time:{prep:30, cook:20},
  hero:'baccala', tags:['salt cod','pepper','olive oil','klippfisk'],
  title:{en:'Baccalà con peperoni cruschi', no:'Baccalà con peperoni cruschi'},
  blurb:{en:'Salt cod poached slowly in olive oil and garlic, with crisp Senise peppers laid over it at the last moment. A mountain region’s way with the only fish that could reach it.',
         no:'Klippfisk trukket langsomt i olivenolje og hvitløk, med sprø paprika fra Senise lagt over helt til slutt. Slik bruker en fjellregion den eneste fisken som nådde fram til den.'},
  heroCaption:{en:'Baccalà with cruschi as Basilicata serves it: white flakes, garlic, oil and whole peppers laid on top.',
               no:'Baccalà med cruschi slik Basilicata serverer den, med hvite flak, hvitløk, olje og hele paprika lagt oppå.'},
  wines:['Aglianico del Vulture'],
  headnote:{
    en:'<p>The reading lists four things Lucanians do with a fried crusco, and one of them is to scatter it on salt cod. That is the one that turns the pepper into a course. It also explains itself geographically: Basilicata is mountain and hill, it has barely any coast, and fresh fish did not travel up those roads. Salt cod did, because salt cod travels anywhere.</p>'
      + '<p>A Norwegian cook is unusually well placed here, since a large share of the cod on Italian plates left Norway as <em>klippfisk</em> in the first place. Buy the thick loin rather than the tail, and give it the soaking it needs: thirty-six to forty-eight hours in cold water in the fridge, changed four or five times. The fish takes back about a third of its weight in water while the salt leaves, and the only way to know it is ready is to poach a sliver and taste it.</p>'
      + '<p>Then keep the heat down. Salt has already denatured the protein in the fish, so it is halfway cooked before it meets the pan; boil it and the flakes contract and go stringy. Warm oil at a temperature where nothing moves on the surface will cook it through in ten minutes and leave it in sheets you can lift whole. The peppers are fried afterwards in the same oil, in seconds, and laid on at the table. Nothing else belongs on the plate except bread.</p>',
    no:'<p>Lesestykket nevner fire ting folk i Lucania gjør med en fritert crusco, og én av dem er å strø den over klippfisk. Nettopp den bruken gjør paprikaen til en hovedrett. Geografien forklarer resten. Basilicata er fjell og ås, regionen har knapt kystlinje, og fersk fisk kom seg ikke opp de veiene. Klippfisken kom, for klippfisk kommer fram overalt.</p>'
      + '<p>En norsk kokk står uvanlig godt rustet her, siden en stor del av torsken på italienske tallerkener opprinnelig forlot Norge som <em>klippfisk</em>. Kjøp den tykke ryggfileten og ikke spordstykket, og gi den utvanningen den trenger: trettiseks til førtiåtte timer i kaldt vann i kjøleskapet, med vannskift fire eller fem ganger. Fisken tar tilbake omtrent en tredjedel av vekten sin i vann mens saltet går ut, og den eneste måten å vite at den er klar på, er å trekke en liten flis og smake.</p>'
      + '<p>Hold så varmen nede. Saltet har allerede denaturert proteinet i fisken, så den er halvveis tilberedt før den møter pannen. Koker du den, trekker flakene seg sammen og blir trådete. Varm olje som ligger helt stille i overflaten, gjør den gjennomvarm på ti minutter og etterlater flak du kan løfte hele. Paprikaen friteres etterpå i den samme oljen, på sekunder, og legges på ved bordet. Ingenting annet hører hjemme på tallerkenen bortsett fra brød.</p>'},
  ingredients:[
    { group:{en:'', no:''}, items:[
      {q:800, u:'g', n:{en:'salt cod', no:'klippfisk'},
       note:{en:'thick loin, soaked for thirty-six to forty-eight hours in cold water in the fridge with four or five changes. The weight is that of the dry fish before soaking',
             no:'tykk ryggfilet, utvannet i trettiseks til førtiåtte timer i kaldt vann i kjøleskapet med fire eller fem vannskift. Vekten gjelder den tørre fisken før utvanningen'}},
      {q:150, u:'ml', n:{en:'olive oil', no:'olivenolje'},
       note:{en:'enough to lie a centimetre deep under the fish; it is the cooking medium, not a dressing',
             no:'nok til å ligge en centimeter dypt under fisken. Den er kokemediet, ikke en dressing'}},
      {q:4, u:'', n:{en:'cloves of garlic', no:'hvitløksfedd'}, round:'half', note:{en:'sliced thin', no:'skåret i tynne skiver'}},
      {q:2, u:'', n:{en:'bay leaves', no:'laurbærblader'}, round:'half'},
      {q:30, u:'g', n:{en:'whole dried sweet peppers', no:'hele, tørkede søte paprika'},
       note:{en:'peperoni di Senise; the first recipe in this chapter covers where to find them',
             no:'peperoni di Senise. Den første oppskriften i dette kapitlet sier hvor du finner dem'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Soak the fish skin up in cold water in the fridge for thirty-six to forty-eight hours, changing the water four or five times. Skin up, so that the salt falls away from it rather than through it.',
     no:'Legg fisken i bløt med skinnet opp i kaldt vann i kjøleskapet i trettiseks til førtiåtte timer, og skift vann fire eller fem ganger. Skinnet skal ligge opp, slik at saltet synker bort fra kjøttet i stedet for gjennom det.'},
    {en:'Poach a sliver in a little water and taste it before you go further. It should be seasoned, not salty; if it bites, give the piece another six hours.',
     no:'Trekk en liten flis i litt vann og smak på den før du går videre. Den skal være passe salt, og ikke mer. Biter den fra seg, gir du stykket seks timer til.'},
    {en:'Drain it, pat it thoroughly dry and cut it into four pieces, pulling out any pin bones with tweezers.',
     no:'Hell av vannet, tørk fisken godt, og skjær den i fire stykker. Trekk ut eventuelle bein med en pinsett.'},
    {en:'Warm the oil with the sliced garlic and the bay in a wide pan over the lowest heat you have, until the garlic is pale gold and smells sweet.',
     no:'Varm oljen med hvitløkskivene og laurbæret i en vid panne på den svakeste varmen du har, til hvitløken er lysegyllen og dufter søtt.'},
    {en:'Lay the fish in skin down and leave it alone for seven or eight minutes, spooning the warm oil over the top now and then. Nothing should bubble.',
     no:'Legg fisken i med skinnet ned, og la den ligge i ro i sju eller åtte minutter mens du øser den varme oljen over den innimellom. Ingenting skal boble.'},
    {en:'Turn each piece once with a fish slice and give it four or five minutes more, until a knife tip slides into the thickest part and the flakes separate.',
     no:'Snu hvert stykke én gang med en stekespade, og gi det fire eller fem minutter til, til en knivspiss glir inn i det tykkeste partiet og flakene slipper hverandre.'},
    {en:'Lift the fish onto a warm dish and let it sit while you deal with the peppers.',
     no:'Løft fisken over på et varmt fat, og la den ligge mens du tar deg av paprikaen.'},
    {en:'Take the garlic and bay out of the pan, raise the oil to 170 °C and fry the peppers for three seconds a side. Lift them out while they are still bright red.',
     no:'Ta hvitløken og laurbæret ut av pannen, varm oljen til 170 °C, og friter paprikaen i tre sekunder på hver side. Løft den opp mens den fortsatt er knallrød.'},
    {en:'Stand them hollow side down on kitchen paper and salt them at once.',
     no:'Sett dem med den hule siden ned på kjøkkenpapir, og salt dem med en gang.'},
    {en:'Spoon a little of the pepper oil over the fish, put the garlic slices back on top and check whether the dish wants any salt at all. Usually it does not.',
     no:'Øs litt av paprikaoljen over fisken, legg hvitløkskivene tilbake på toppen, og vurder om retten trenger salt i det hele tatt. Som oftest gjør den ikke det.'},
    {en:'Lay the peppers over the fish whole, break one or two of them across it, and take it to the table with bread and nothing else.',
     no:'Legg belgene hele over fisken, brekk én eller to av dem over retten, og bær den til bordet med brød og ikke noe annet.'},
  ],
  notes:[
    {title:{en:'Salt has already cooked it once', no:'Saltet har alt gjort halve jobben'},
     body:{en:'Curing pulls water out of the muscle and unravels the proteins, which is why salt cod is firm and opaque before any heat reaches it. The fibres are therefore much closer to contracting than fresh cod is, and a simmer finishes that job and squeezes the water back out in threads. Oil held below a bubble raises the temperature slowly and stops well short of it.',
           no:'Saltingen trekker vann ut av muskelen og løser opp proteinene, og derfor er klippfisk fast og hvit før den har møtt varme i det hele tatt. Fibrene er dermed langt nærmere å trekke seg sammen enn i fersk torsk, og et oppkok fullfører den jobben og presser vannet ut igjen i tråder. Olje som holdes under kokepunktet, varmer fisken langsomt og kommer aldri i nærheten av det punktet.'}},
    {title:{en:'Taste, do not count', no:'Smak, ikke tell'},
     body:{en:'Salt cod is cured to no fixed standard, and a heavily salted loin can want twice as long in water as a light one. The clock is a guide and the tongue is the instrument. Under-soaked fish cannot be rescued on the plate, and over-soaked fish turns woolly, so the slice you poach and taste is the most useful thing you will do all day.',
           no:'Klippfisk saltes ikke etter noen fast norm, og en kraftig saltet rygg kan trenge dobbelt så lang tid i vann som en som er lett saltet. Klokken er en pekepinn, og tungen er instrumentet. Fisk som er for lite utvannet, lar seg ikke redde på tallerkenen, og fisk som er for mye utvannet, blir ullen, så smakstesten er det nyttigste du gjør den dagen.'}},
    {title:{en:'One pan, two temperatures', no:'Én panne, to temperaturer'},
     body:{en:'The oil is the whole sauce, and frying the peppers in it at the end is what joins the two halves of the dish: the oil takes a little sweetness and colour from the pods, and the pods take the garlic and the fish. Fry them first and they sit and soften while the cod cooks, and you have thrown that away for the sake of tidiness.',
           no:'Oljen er hele sausen, og når du friterer paprikaen i den helt til slutt, binder du de to halvdelene av retten sammen. Oljen får litt sødme og farge fra belgene, og belgene får smak av hvitløk og fisk. Friterer du dem først, blir de liggende og mykne mens torsken steker, og da har du kastet det bort for ordens skyld.'}},
  ],
  variations:[
    {title:{en:'With potatoes, in the oven', no:'Med poteter, i ovnen'},
     body:{en:'The winter version. Line a dish with sliced potatoes and onion, pour over half the oil, lay the soaked fish on top and bake it covered at 180 °C for about forty minutes, then uncovered for ten. The peppers still go on at the very end, and the potatoes underneath take up everything that comes out of the fish.',
           no:'Vinterutgaven. Dekk bunnen av en form med potet- og løkskiver, hell over halvparten av oljen, legg den utvannede fisken oppå, og stek retten tildekket på 180 °C i omtrent førti minutter og deretter ti minutter uten lokk. Paprikaen kommer fortsatt på helt til slutt, og potetene under tar opp alt som kommer ut av fisken.'}},
    {title:{en:'Stoccafisso instead', no:'Tørrfisk i stedet'},
     body:{en:'Air-dried cod without salt, the Norwegian <em>tørrfisk</em>, is used in parts of the south for the same dish. It wants three or four days in water changed twice a day, it is firmer and more fibrous when cooked, and it tastes far more strongly of the fish itself. Softer flavours, salt cod; a stronger plate, stoccafisso.',
           no:'Lufttørket torsk uten salt, altså tørrfisk, brukes til den samme retten i deler av Sør-Italia. Den trenger tre eller fire døgn i vann som skiftes to ganger om dagen, den blir fastere og mer trevlet når den er ferdig, og den smaker langt sterkere av fisken selv. Vil du ha mildere smak, velger du klippfisk, og vil du ha en kraftigere rett, velger du tørrfisk.'}},
    {title:{en:'A glass of rosato', no:'Et glass rosato'},
     body:{en:'Aglianico del Vulture also comes as a deep pink <em>rosato</em>, made by running the same grape off its skins after a few hours, and it has the body and the acidity to sit beside oily fish and sweet fried peppers where the red would flatten them. Look for it under the same appellation; it is a summer bottle in Basilicata and it costs very little.',
           no:'Aglianico del Vulture finnes også som en dyprosa <em>rosato</em>. Den lages av den samme druen, der mosten tappes av skallene etter bare noen timer. Den har fylden og syren som trengs ved siden av fet fisk og søt fritert paprika, der rødvinen ville lagt seg over dem. Se etter den under den samme betegnelsen. Den er en sommervin i Basilicata, og den koster svært lite.'}},
  ],
},

];
