// Calabria recipes. Bilingual in one file: the quantities are written once so English and Norwegian
// cannot drift apart. Contract: docs/recipe-format.md. Checked by tools/recipecheck.py. Never narrated.
// Everything here follows the Calabrian food reading (content/calabria.js, lesson 3): a preserving
// kitchen with chilli in most of it. 'Nduja is bought and cooked with, never made at home; fileja is
// the everyday pasta, rolled around a reed; the swordfish comes from the Strait of Messina; and the
// red onion of Tropea is sweet enough to eat raw. Four of the region's six chips are things you buy or
// grow rather than cook, so the dishes below are the ones the reading actually describes.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-78'] = [

{
  id:'fileja', dish:'Fileja', course:'base', lesson:3, serves:4, time:{prep:45, cook:6},
  hero:'ferretto', tags:['pasta','semolina','handmade'],
  title:{en:'Fileja', no:'Fileja'},
  blurb:{en:'The everyday pasta of Calabria: semolina and water, rolled around a knitting needle so that every piece keeps a hole down the middle.',
         no:'Hverdagspastaen i Calabria. Semule og vann rulles rundt en strikkepinne slik at hver bit beholder et hull gjennom midten.'},
  heroCaption:{en:'Ferrazzuoli, the long cousin of fileja, being rolled on a ferretto in a Calabrian kitchen. Same dough, same needle, same hole.',
               no:'Ferrazzuoli, den lange slektningen av fileja, blir rullet på en ferretto i et calabrisk kjøkken. Samme deig, samme pinne, samme hull.'},
  wines:['Cirò Rosso (Gaglioppo)'],
  headnote:{
    en:'<p>The everyday pasta of Calabria is flour and water and nothing else. The reading describes it exactly: a short length of dough rolled around a thin reed or a knitting needle to make a loose spiral with a hole through it, so that it catches a heavy sauce. There is no egg in the dough and no oil. A reed pulled from a riverbank did the work for centuries, and a steel knitting needle does it slightly better.</p>'
      + '<p>Durum does the rest. Semola rimacinata is durum wheat reground fine: high in protein, slow to take up water, and stiff when it is worked. That stiffness holds the hole open in boiling water. A dough of ordinary soft wheat flour goes slack in the pot and the spiral closes on itself.</p>'
      + '<p>Three things are not negotiable. The dough is firmer than feels right, almost dry to the hand. It has to rest, or the ropes spring back as fast as you roll them. And each piece dries for half an hour before it goes near water, so that the surface sets and the shape survives the boil.</p>',
    no:'<p>Hverdagspastaen i Calabria er mel og vann, og ikke noe mer. Lesteksten beskriver den nøyaktig: en bit deig rullet rundt en tynn sivpinne eller en strikkepinne til en løs spiral med et hull tvers gjennom, slik at den fanger en tung saus. Deigen inneholder verken egg eller olje. En sivpinne fra en elvebredd gjorde jobben i århundrer, og en strikkepinne av stål gjør den litt bedre.</p>'
      + '<p>Durumhveten gjør resten. Semola rimacinata er malt av durumhvete, har mye protein og tar opp vannet langsomt, og deigen blir stiv når den arbeides. Nettopp stivheten holder hullet åpent i kokende vann. En deig av vanlig hvetemel blir slapp i kjelen, og spiralen klapper sammen.</p>'
      + '<p>Tre ting må sitte. Deigen skal være fastere enn du tror, nesten tørr å ta i. Den må hvile, ellers spretter pølsene tilbake like fort som du ruller dem. Og hver bit skal tørke en halvtime før den kommer i nærheten av vann, slik at overflaten setter seg og formen overlever kokingen.</p>'},
  ingredients:[
    { group:{en:'The dough', no:'Deigen'}, items:[
      {q:400, u:'g', n:{en:'semola rimacinata', no:'semola rimacinata'},
       note:{en:'finely reground durum semolina, sold by Italian shops and the larger groceries. Ordinary Norwegian semulegryn is far coarser and will not knead smooth',
             no:'finmalt durumsemule, som selges i italienske butikker og i de større dagligvarebutikkene. Vanlige norske semulegryn er langt grovere og lar seg ikke elte glatte'}},
      {q:200, u:'ml', n:{en:'warm water', no:'lunkent vann'},
       note:{en:'hold some back. Semola varies, and the dough wants to be firm rather than smooth at this stage',
             no:'hold igjen litt. Semula varierer, og deigen skal være fast heller enn glatt på dette stadiet'}},
      {u:'', n:{en:'a pinch of salt', no:'en klype salt'}, scale:'none'},
      {u:'', n:{en:'semola for the cloth', no:'semule til kjøkkenhåndkleet'}, scale:'none'},
    ]},
    { group:{en:'To cook', no:'Til kokingen'}, items:[
      {q:4, u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:30, u:'g', n:{en:'salt', no:'salt'}, scale:'sub'},
    ]},
  ],
  steps:[
    {en:'Tip the semola onto a board, stir the salt through it and make a well in the middle.',
     no:'Hell semulaen ut på en fjøl, rør saltet inn i den, og lag en brønn i midten.'},
    {en:'Pour most of the warm water into the well and draw the flour in with your fingertips until it is all in damp lumps.',
     no:'Hell mesteparten av det lunkne vannet i brønnen, og dra melet inn med fingertuppene til alt ligger i fuktige klumper.'},
    {en:'Add the rest of the water a few drops at a time, only until the lumps join. The dough should feel firm and slightly dry.',
     no:'Tilsett resten av vannet noen dråper om gangen, bare til klumpene henger sammen. Deigen skal kjennes fast og litt tørr.'},
    {en:'Knead for ten minutes on an unfloured board, pushing down and away with the heel of your hand, until the surface is smooth.',
     no:'Elt i ti minutter på en fjøl uten mel, og skyv fra deg med håndroten til overflaten er glatt.'},
    {en:'Wrap the dough and leave it to rest for half an hour, so that the gluten relaxes and the semola finishes drinking.',
     no:'Pakk inn deigen, og la den hvile i en halvtime, slik at glutenet slapper av og semulaen blir ferdig med å drikke.'},
    {en:'Cut off a piece the size of an egg and keep the rest covered; a dough this dry skins over in minutes.',
     no:'Skjær av et stykke på størrelse med et egg, og hold resten tildekket. En så tørr deig får skinn på seg i løpet av minutter.'},
    {en:'Roll the piece under your palms into a rope as thick as a pencil.',
     no:'Rull stykket under håndflatene til en pølse så tykk som en blyant.'},
    {en:'Cut the rope into lengths as long as your index finger.',
     no:'Del pølsen i biter så lange som pekefingeren din.'},
    {en:'Lay a knitting needle diagonally across one length and roll it under your fingers, so that the dough winds round the needle and the edges close.',
     no:'Legg en strikkepinne på skrå over en bit, og rull den under fingrene slik at deigen vikler seg rundt pinnen og kantene lukker seg.'},
    {en:'Slide the pasta off the needle and lay it on a cloth dusted with semola, keeping the pieces apart so they do not stick to one another.',
     no:'Trekk pastaen av pinnen, og legg den på et kjøkkenhåndkle strødd med semule. Hold bitene fra hverandre, ellers kleber de seg sammen.'},
    {en:'Leave them to dry for half an hour, turning them once, until the surface no longer feels damp.',
     no:'La dem tørke i en halvtime, og snu dem én gang, til overflaten ikke lenger kjennes fuktig.'},
    {en:'Cook them in plenty of boiling salted water for four to six minutes, until they rise and are firm where the dough overlaps, and keep back a ladle of the water as you drain them.',
     no:'Kok dem i rikelig kokende saltet vann i fire til seks minutter, til de stiger opp og er faste der deigen ligger dobbelt, og hold igjen en øse av vannet når du heller dem av.'},
  ],
  notes:[
    {title:{en:'Semolina, not flour', no:'Semule, ikke hvetemel'},
     body:{en:'Durum semolina takes up water slowly and holds a strong, inelastic gluten, which is why the dough can be worked this dry and still come smooth. That is the property the shape depends on: a hollow spiral has to stay open through eight minutes of turbulence. Soft wheat flour makes a slack, stretchy dough that seals its own hole in the pan.',
           no:'Durumsemule tar opp vann langsomt og har et sterkt og lite elastisk gluten, og derfor kan deigen arbeides så tørr og likevel bli glatt. Formen hviler på nettopp den egenskapen, for en hul spiral må holde seg åpen gjennom åtte minutter i kokende vann. Vanlig hvetemel gir en slapp og strekkbar deig som lukker hullet sitt selv i kjelen.'}},
    {title:{en:'What the hole is for', no:'Hva hullet er til for'},
     body:{en:'The reading puts it plainly: the shape is made so that it catches a heavy sauce. A ragù or a fat-rich sauce like \'nduja and tomato needs somewhere to sit, and a fileja gives it a channel inside and a rough seam outside. Smooth extruded pasta of the same length carries perhaps half as much.',
           no:'Lesteksten sier det rett ut: formen lages for å fange en tung saus. En ragù eller en fettrik saus av \'nduja og tomat trenger et sted å sitte, og en fileja gir den en kanal på innsiden og en ru skjøt på utsiden. Glatt, presset pasta av samme lengde bærer kanskje halvparten så mye.'}},
    {title:{en:'Dried a little, not dried out', no:'Litt tørket, ikke knusktørr'},
     body:{en:'Half an hour on the cloth sets the surface so the pieces keep their shape and stop sticking. Left for days they become dried pasta, which is fine but wants twelve minutes and a bigger pot. Fresh ones keep a day in the fridge under a cloth, or freeze on a tray and go into the water from frozen.',
           no:'En halvtime på kjøkkenhåndkleet setter overflaten, slik at bitene beholder formen og slutter å klebe. Blir de liggende i dagevis, er de blitt tørrpasta, og det går helt fint, men da trenger de tolv minutter og en større kjele. Ferske holder seg et døgn i kjøleskapet under et håndkle, eller de kan fryses på brett og gå i vannet rett fra fryseren.'}},
  ],
  variations:[
    {title:{en:'Ferrazzuoli', no:'Ferrazzuoli'},
     body:{en:'The same dough and the same needle, but the rope is rolled along its whole length instead of being cut into short pieces, which gives a long hollow macaroni. Calabria calls it maccheroni al ferretto and eats it with the same sauces.',
           no:'Samme deig og samme pinne, men pølsen rulles i hele sin lengde i stedet for å deles i korte biter, og resultatet blir en lang, hul makaroni. Calabria kaller den maccheroni al ferretto og spiser den til de samme sausene.'}},
    {title:{en:'Bought fileja', no:'Kjøpt fileja'},
     body:{en:'Dried fileja is sold by Italian shops and is an honest product. Failing that, busiate or casarecce are the nearest shapes in a Norwegian supermarket, both of them twisted and hollow enough to hold a ragù.',
           no:'Tørket fileja selges i italienske butikker og er en ærlig vare. Finner du den ikke, er busiate eller casarecce de nærmeste formene i en norsk butikk, og begge er vridde og hule nok til å holde på en ragù.'}},
    {title:{en:'With tomato and hard ricotta', no:'Med tomat og hard ricotta'},
     body:{en:'The plainest dressing the reading names. A simple tomato sauce, then ricotta salata grated over at the table. It is what the pasta is eaten with on days when there is no meat in the house.',
           no:'Den enkleste sausen lesteksten nevner. En enkel tomatsaus, og så ricotta salata revet over ved bordet. Slik spises pastaen de dagene det ikke finnes kjøtt i huset.'}},
  ],
},

{
  id:'fileja-nduja', dish:"'Nduja", course:'primo', lesson:3, serves:4, time:{prep:10, cook:30},
  hero:'filejanduja', tags:['pasta','pork','chilli','tomato'],
  title:{en:"Fileja con 'nduja", no:"Fileja con 'nduja"},
  blurb:{en:"The region's plate of choice: the spreadable salame of Spilinga melted into oil at the start, tomato after it, and pasta with a hole to carry it.",
         no:"Regionens foretrukne tallerken. Den smørbare salamien fra Spilinga smelter i oljen først, tomaten kommer etter, og pastaen har et hull å bære den i."},
  heroCaption:{en:"Fileja with 'nduja and tomato. The sauce is red because the fat is, not because of the tomato alone.",
               no:"Fileja med 'nduja og tomat. Sausen er rød fordi fettet er det, ikke bare på grunn av tomaten."},
  wines:['Cirò Rosso (Gaglioppo)'],
  headnote:{
    en:"<p>'Nduja is bought, never made at home. The reading says what it is: pork trimmings and fatback worked together with a very large quantity of sun-dried Calabrian chilli, packed into a wide casing, lightly smoked and aged for three to six months at Spilinga, below Monte Poro in the province of Vibo Valentia. No domestic kitchen ferments meat for a season in order to dress a plate of pasta.</p>"
      + "<p>Roughly half of it is fat, and the fat is the mechanism. Dropped into warm oil it melts in under a minute and turns the whole pan red; the chilli heat, the salt and the smoked pork come out of the casing together and coat everything added after them. That is why the reading describes it going into the pan at the start, so that everything after it tastes of pork and fire.</p>"
      + "<p>Two rules follow. Keep the heat low while it melts, because hard frying scorches the chilli and leaves a bitter edge that no amount of tomato covers. And taste before you commit: 'nduja is sold in Norway now, but the heat runs from mild to ferocious depending on the maker, so melt in half of it, finish the sauce, and add the rest only if the sauce will carry it.</p>",
    no:"<p>'Nduja kjøpes, den lages aldri hjemme. Lesteksten sier hva den er: avskjær og ryggfett av svin arbeidet sammen med en svært stor mengde soltørket calabrisk chili, stappet i et vidt skinn, lettrøkt og modnet i tre til seks måneder i Spilinga, under Monte Poro i provinsen Vibo Valentia. Ikke noe hjemmekjøkken modner kjøtt en hel sesong for å kle en tallerken pasta.</p>"
      + "<p>Omtrent halvparten er fett, og fettet er mekanismen. Slipper du 'nduja i varm olje, smelter den på under et minutt og farger hele pannen rød. Chilistyrken, saltet og det røkte svinekjøttet kommer ut av skinnet samtidig og legger seg på alt som tilsettes etterpå. Derfor beskriver lesteksten at den går i pannen først, slik at alt som kommer etter, smaker svin og ild.</p>"
      + "<p>To regler følger av dette. Hold varmen lav mens den smelter, for hard steking svir chilien og etterlater en besk kant som ingen mengde tomat dekker over. Og smak før du bestemmer deg. 'Nduja selges i Norge nå, men styrken varierer voldsomt fra produsent til produsent, så smelt inn halvparten, gjør sausen ferdig, og ta resten bare hvis sausen tåler den.</p>"},
  ingredients:[
    { group:{en:'', no:''}, items:[
      {q:400, u:'g', n:{en:'fileja', no:'fileja'},
       note:{en:'fresh from the recipe above, or dried; busiate and casarecce are the nearest supermarket shapes',
             no:'ferske fra oppskriften over, eller tørkede. Busiate og casarecce er de nærmeste formene i butikken'}},
      {q:80, u:'g', n:{en:"'nduja", no:"'nduja"},
       note:{en:'the heat varies enormously between makers. Taste a little on bread before you decide how much goes in',
             no:'styrken varierer voldsomt mellom produsenter. Smak litt på brød før du bestemmer hvor mye som skal i'}},
      {q:400, u:'g', n:{en:'peeled plum tomatoes', no:'hermetiske plommetomater'},
       note:{en:'crushed by hand; a passata will do', no:'most med hendene. En passata går også'}},
      {q:1, u:'', n:{en:'red onion', no:'rødløk'}, round:'half',
       note:{en:'a Tropea onion if you have one', no:'gjerne en Tropea-løk hvis du har en'}},
      {q:1, u:'', n:{en:'clove of garlic', no:'hvitløksfedd'}, round:'half'},
      {q:30, u:'ml', n:{en:'olive oil', no:'olivenolje'}},
      {q:40, u:'g', n:{en:'ricotta salata or pecorino crotonese', no:'ricotta salata eller pecorino crotonese'},
       note:{en:'grated at the table. Any hard, salty sheep cheese does the job',
             no:'revet ved bordet. Enhver hard og salt sauost gjør jobben'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
      {q:4, u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:30, u:'g', n:{en:'salt for the pasta water', no:'salt til pastavannet'}, scale:'sub'},
    ]},
  ],
  steps:[
    {en:'Put the water on to boil in a large pot and salt it.',
     no:'Sett vannet over i en stor kjele, og salt det.'},
    {en:'Slice the onion thinly and soften it in the oil in a wide pan over low heat for about eight minutes, without letting it take colour.',
     no:'Skjær løken i tynne skiver, og la den mykne i oljen i en vid panne på svak varme i rundt åtte minutter, uten at den tar farge.'},
    {en:'Flatten the garlic with the side of a knife, let it cook until it smells, then lift it out.',
     no:'Knus hvitløken med siden av en kniv, la den steke til den dufter, og løft den så ut.'},
    {en:"Drop in half the 'nduja and break it up against the bottom of the pan with a wooden spoon.",
     no:"Slipp halvparten av mengden 'nduja i pannen, og del den opp mot bunnen med en tresleiv."},
    {en:'Keep the heat low while it melts. A minute is enough, and the oil should turn red rather than brown.',
     no:'Hold varmen lav mens den smelter. Et minutt holder, og oljen skal bli rød og ikke brun.'},
    {en:'Crush in the tomatoes, season lightly and simmer for twenty minutes, until the fat rises red on the surface.',
     no:'Mos tomatene ned i pannen, salt lett, og la det småkoke i tjue minutter, til fettet legger seg rødt på overflaten.'},
    {en:"Taste, and work in as much of the remaining 'nduja as the sauce will carry.",
     no:"Smak, og rør inn så mye av resten som sausen tåler."},
    {en:'Cook the pasta: four to six minutes if it is fresh, twelve to fourteen if it is dried.',
     no:'Kok pastaen. Fersk trenger fire til seks minutter, tørket tolv til fjorten.'},
    {en:'Lift the pasta into the sauce with a slotted spoon so that some of the cooking water goes with it.',
     no:'Løft pastaen over i sausen med en hullsleiv, slik at litt av kokevannet følger med.'},
    {en:'Toss it over medium heat for a minute, adding pasta water until the sauce clings to the pasta and no loose oil is left in the pan.',
     no:'Vend den på middels varme i et minutt, og spe med pastavann til sausen henger ved pastaen og det ikke ligger løs olje igjen i pannen.'},
    {en:'Take the pan off the heat, grate the cheese over and serve at once.',
     no:'Ta pannen av platen, riv osten over, og server med en gang.'},
  ],
  notes:[
    {title:{en:'Why the fat goes in first', no:'Derfor går fettet i først'},
     body:{en:"Capsaicin and most of the aromatic compounds in 'nduja dissolve in fat, not in water. Melted into the oil at the start they are carried into every drop of the sauce and onto every piece of pasta. Stirred in at the end, the same sausage stays in red specks and the dish is hot in patches rather than hot all through.",
           no:"Capsaicin og de fleste aromastoffene i 'nduja løser seg i fett, ikke i vann. Smelter du dem inn i oljen med en gang, følger de med i hver dråpe saus og på hver bit pasta. Rører du den samme pølsen inn til slutt, blir den liggende i røde prikker, og retten er sterk i flekker i stedet for sterk tvers igjennom."}},
    {title:{en:'Pasta water is the glue', no:'Pastavannet er limet'},
     body:{en:'The starch that comes off the pasta lets fat and water hold together, so a ladle of the cooking water turns a greasy pan into a sauce that coats. Add it a little at a time while the pan is still on the heat and keep tossing; poured in cold at the end it just makes the plate wet.',
           no:'Stivelsen som løsner fra pastaen, gjør at fett og vann holder sammen, og en øse kokevann gjør en fettete panne om til en saus som legger seg rundt pastaen. Spe litt om gangen mens pannen fortsatt står på platen, og vend hele tiden. Heller du vannet i kaldt til slutt, blir tallerkenen bare våt.'}},
    {title:{en:'Salt arrives with the sausage', no:'Saltet kommer med pølsen'},
     body:{en:"'Nduja is a cured meat and carries a lot of salt, and the cheese at the end carries more. Season the tomatoes lightly, then taste again once the sauce has reduced and before the cheese goes near it.",
           no:"'Nduja er spekemat og bærer med seg mye salt, og osten til slutt bærer med seg enda mer. Smak til tomatene forsiktig, og smak på nytt når sausen har kokt inn, før osten kommer i nærheten av den."}},
  ],
  variations:[
    {title:{en:'On bread', no:'På brød'},
     body:{en:"The reading calls this how most Calabrians first meet it, and it needs no recipe: grill or toast good bread, spread the 'nduja on while the bread is warm enough to melt it slightly, and stop there.",
           no:"Lesteksten sier at det er slik de fleste calabrere møter 'nduja første gang, og det trenger ingen oppskrift. Rist godt brød, smør på 'nduja mens brødet er varmt nok til å smelte den litt, og la det bli med det."}},
    {title:{en:'Over a ripe cheese', no:'Over en moden ost'},
     body:{en:"The reading's other everyday use. Warm slices of caciocavallo silano in a dry pan until they slump, then spoon the 'nduja over so that it melts into the cheese.",
           no:"Den andre hverdagsbruken lesteksten nevner. Varm skiver av caciocavallo silano i en tørr panne til de siger sammen, og skje 'nduja over slik at den smelter inn i osten."}},
    {title:{en:'If you cannot get it', no:'Hvis du ikke får tak i den'},
     body:{en:"There is no honest substitute. A soft cooking chorizo with a little chilli paste gives colour and heat, but it is a fresh sausage with paprika in it, not a meat aged for months under chilli, and the dish becomes a different one. Order the real thing instead; it keeps for weeks in the fridge.",
           no:"Det finnes ingen ærlig erstatning. En myk chorizo til steking med litt chilipuré gir farge og styrke, men det er en fersk pølse med paprika i, ikke kjøtt som er modnet i månedsvis under chili, og retten blir en annen. Bestill heller den ekte varen, for den holder seg i ukevis i kjøleskapet."}},
  ],
},

{
  id:'ragu-di-capra', dish:'Fileja col ragù di capra', course:'primo', lesson:3, serves:6, time:{prep:30, cook:210},
  hero:'capre', tags:['goat','ragu','pasta','slow'],
  title:{en:'Fileja col ragù di capra', no:'Fileja col ragù di capra'},
  blurb:{en:'The mountain dressing for fileja: goat on the bone, red wine, tomato and chilli, held at a bare simmer until the meat leaves the bone. One pot, two courses.',
         no:'Fjellsausen til fileja. Geit på beinet, rødvin, tomat og chili trekker så vidt under kokepunktet til kjøttet slipper beinet. Én gryte, to retter.'},
  heroCaption:{en:'No free photograph of the dish exists. These are the animals, out above the Ionian valleys at the end of a Calabrian summer day.',
               no:'Det finnes ikke noe fritt bilde av retten. Dette er dyrene, på beite over de joniske dalene på slutten av en calabrisk sommerdag.'},
  wines:['Cirò Rosso (Gaglioppo)'],
  headnote:{
    en:"<p>The reading gives fileja three dressings: 'nduja, tomato with hard ricotta, and a ragù of goat or pork. The goat one belongs to the mountains. The Sila is pasture and forest at around 1,300 metres and the Aspromonte rises straight out of the sea at the end of the peninsula, and an animal that has walked all its life for a living has lean, dark, sinewy meat that is worth nothing cooked quickly and a great deal cooked slowly.</p>"
      + '<p>Goat carries very little fat and a great deal of connective tissue. Held for three hours just below a simmer, the collagen turns to gelatine and the meat comes off the bone at a touch; boiled hard, the same fibres contract and squeeze out their water, and no extra hour repairs stringy meat. That gelatine is also what gives the sauce its body, because there is no cream and no butter anywhere in it.</p>'
      + '<p>One pot makes two courses, which is how it is eaten. The sauce dresses the pasta and the meat follows it to the table with bread. Cook it the day before if you can: it is better on the second day, and the fat lifts off in a sheet once it is cold.</p>',
    no:"<p>Lesteksten nevner tre sauser til fileja: 'nduja, tomat med hard ricotta, og en ragù av geit eller svin. Geiteragùen hører fjellet til. Sila er beite og skog rundt 1 300 meter over havet, og Aspromonte reiser seg rett opp av sjøen bak den. Et dyr som har gått for føden hele livet, har magert, mørkt og senete kjøtt som ikke er verdt noe når det stekes fort, og svært mye når det kokes langsomt.</p>"
      + '<p>Geit har lite fett og mye bindevev. Holder du gryten så vidt under kokepunktet i tre timer, gjør kollagenet seg om til gelatin, og kjøttet slipper beinet ved en berøring. Fosskoker du den, trekker de samme fibrene seg sammen og presser ut vannet, og ingen ekstra time reparerer trevlete kjøtt. Gelatinen gir også sausen fylde, for verken fløte eller smør hører hjemme i den.</p>'
      + '<p>Én gryte gir to retter, og slik spises den også. Sausen kler pastaen, og kjøttet følger etter til bordet med brød. Lag den dagen før hvis du kan. Den blir bedre den andre dagen, og fettet lar seg løfte av i ett stykke når det er kaldt.</p>'},
  ingredients:[
    { group:{en:'The ragù', no:'Ragùen'}, items:[
      {q:1.2, u:'kg', n:{en:'goat or kid on the bone, in large pieces', no:'geit eller kje på beinet, i store stykker'},
       note:{en:'kje appears in Norwegian butchers around Easter and goat is sold by farm shops and halal butchers the year round. Lamb shoulder is the everyday stand-in, and the region grills lamb and kid alike',
             no:'kje dukker opp hos norske slaktere rundt påske, og geitekjøtt selges hele året i gårdsutsalg og hos halalslaktere. Lammebog er den vanlige erstatningen, og regionen griller lam og kje om hverandre'}},
      {q:30, u:'ml', n:{en:'olive oil', no:'olivenolje'}},
      {q:1, u:'', n:{en:'onion', no:'løk'}, round:'half'},
      {q:2, u:'', n:{en:'cloves of garlic', no:'hvitløksfedd'}, round:'half'},
      {q:200, u:'ml', n:{en:'Cirò Rosso or another dry red', no:'Cirò Rosso eller en annen tørr rødvin'},
       note:{en:'a tannic, savoury red rather than a soft fruity one; what goes in the pot should go in the glass',
             no:'en tanninrik og smaksrik rødvin heller enn en myk og fruktig. Den som går i gryten, bør også gå i glasset'}},
      {q:700, u:'g', n:{en:'passata or peeled tomatoes', no:'passata eller hermetiske tomater'}},
      {u:'', n:{en:'dried chilli', no:'tørket chili'}, scale:'none',
       note:{en:'crumbled. The reading is clear that chilli goes into most of the cooking here',
             no:'smuldret. Lesteksten er tydelig på at chili går i det meste av matlagingen her'}},
      {u:'', n:{en:'dried oregano', no:'tørket oregano'}, scale:'none'},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'To serve', no:'Til servering'}, items:[
      {q:500, u:'g', n:{en:'fileja', no:'fileja'}},
      {q:60, u:'g', n:{en:'pecorino crotonese', no:'pecorino crotonese'},
       note:{en:'hard and sharp, from the Ionian pastures. Pecorino Romano is saltier, so hold back on the salt',
             no:'hard og skarp, fra de joniske beitene. Pecorino Romano er saltere, så hold igjen på saltet'}},
      {q:5, u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:40, u:'g', n:{en:'salt for the pasta water', no:'salt til pastavannet'}, scale:'sub'},
    ]},
  ],
  steps:[
    {en:'Pat the meat dry and salt it. Wet meat steams instead of browning.',
     no:'Tørk kjøttet, og salt det. Vått kjøtt damper i stedet for å brunes.'},
    {en:'Brown it hard in the oil in a heavy pot, a few pieces at a time so the pot stays hot, and lift each batch out as it colours.',
     no:'Brun det kraftig i oljen i en tykkbunnet gryte, noen få stykker om gangen slik at gryten holder varmen, og løft hver omgang ut etter hvert som den får farge.'},
    {en:'Turn the heat down, chop the onion and let it soften in the fat left behind, scraping the brown from the bottom as it goes.',
     no:'Skru ned varmen, hakk løken, og la den mykne i fettet som er igjen, mens du skraper løs det brune i bunnen.'},
    {en:'Add the chopped garlic and the crumbled chilli and give them half a minute, no more.',
     no:'Tilsett hakket hvitløk og smuldret chili, og gi dem et halvt minutt, ikke mer.'},
    {en:'Pour in the wine, raise the heat and let it boil until only a syrupy film is left on the bottom.',
     no:'Hell i vinen, skru opp varmen, og la den koke inn til bare en sirupsaktig hinne er igjen i bunnen.'},
    {en:'Return the meat with any juices, add the tomatoes and the oregano, and pour in water until the meat is barely covered.',
     no:'Legg kjøttet tilbake med kraften det har avgitt, tilsett tomatene og oreganoen, og hell på vann til kjøttet så vidt er dekket.'},
    {en:'Bring it up to the point where a bubble breaks the surface every few seconds, then set the lid ajar.',
     no:'Varm opp til det bryter en boble gjennom overflaten med noen sekunders mellomrom, og legg lokket på gløtt.'},
    {en:'Leave it there for three hours, turning the pieces two or three times, until the meat comes away from the bone at a touch.',
     no:'La den stå slik i tre timer, snu stykkene to eller tre ganger, og kok til kjøttet slipper beinet ved en berøring.'},
    {en:'Lift the meat out onto a dish and let the sauce reduce, uncovered, until it thickens enough to sit on a spoon.',
     no:'Løft kjøttet over på et fat, og la sausen koke inn uten lokk til den er tykk nok til å bli liggende på en skje.'},
    {en:'Pull the meat off the bones in shreds and return about half of it to the sauce; keep the rest warm for the second course.',
     no:'Plukk kjøttet av beina i trevler, og legg omtrent halvparten tilbake i sausen. Hold resten varm til hovedretten.'},
    {en:'Cook the fileja in plenty of boiling salted water, then lift it into the sauce with some of its water and toss it for a minute.',
     no:'Kok pastaen i rikelig kokende saltet vann, løft den over i sausen med litt av kokevannet, og vend den i et minutt.'},
    {en:'Grate the pecorino over with the pot off the heat, and bring the meat to the table afterwards with bread.',
     no:'Riv pecorinoen over med gryten av platen, og sett kjøttet på bordet etterpå, med brød.'},
  ],
  notes:[
    {title:{en:'A bare simmer, not a boil', no:'Så vidt under kokepunktet'},
     body:{en:'Collagen converts to gelatine from about 70 °C, and it needs hours rather than heat. A rolling boil drives the meat fibres well past that, and they contract and wring out their own water, which is exactly the stringy dry result people blame on the animal. Watch the surface rather than the clock: a bubble every few seconds is right.',
           no:'Kollagen gjør seg om til gelatin fra rundt 70 °C, og det trenger timer heller enn høy varme. Fosskoking driver kjøttfibrene langt forbi det punktet, og de trekker seg sammen og vrir ut sitt eget vann, som er nettopp det trevlete og tørre resultatet folk skylder på dyret. Følg med på overflaten heller enn på klokken. En boble med noen sekunders mellomrom er riktig.'}},
    {title:{en:'Browning is flavour, not a seal', no:'Bruningen er smak, ikke en forsegling'},
     body:{en:'Searing does not keep juices in — a browned piece loses as much water as a pale one. What it does is build hundreds of new aromatic compounds on the surface, and those dissolve into the sauce over three hours. That is why the pot is scraped after the onion goes in, and why the meat goes back with every drop it has given up.',
           no:'Bruningen holder ikke saften inne, for et brunet stykke mister like mye vann som et ubrunet. Den bygger derimot hundrevis av nye aromastoffer på overflaten, og de løser seg opp i sausen i løpet av tre timer. Derfor skraper du gryten etter at løken er i, og derfor går kjøttet tilbake med hver dråpe det har avgitt.'}},
    {title:{en:'Better on the second day', no:'Bedre den andre dagen'},
     body:{en:'Cooled overnight, the fat sets in a sheet on top and can be lifted off whole, which leaves a sauce that tastes of meat rather than of fat. The gelatine stiffens the whole pot to a wobble, which is the sign it worked. Reheat it gently with a little water.',
           no:'Kjøler du den natten over, stivner fettet til et lag på toppen og kan løftes av i ett stykke, slik at sausen som blir igjen, smaker kjøtt heller enn fett. Gelatinen stivner hele gryten til en skjelvende masse, og det er tegnet på at den har lykkes. Varm den forsiktig opp igjen med litt vann.'}},
  ],
  variations:[
    {title:{en:'Lamb shoulder', no:'Lammebog'},
     body:{en:'Available everywhere in Norway and cooked exactly the same way, though it carries more fat and is ready half an hour sooner. Skim more, and taste for salt at the end because lamb fat carries the seasoning differently.',
           no:'Lammebog fås overalt i Norge og lages på nøyaktig samme måte, men den har mer fett og er ferdig en halvtime tidligere. Skum av mer fett, og smak til med salt på slutten, for lammefettet bærer krydderet annerledes.'}},
    {title:{en:'Pork', no:'Svin'},
     body:{en:'The reading names a ragù of goat or pork, and pork shoulder on the bone is the easier of the two to buy. It is fatter and sweeter, so add the chilli with a heavier hand and keep the wine dry.',
           no:'Lesteksten nevner en ragù av geit eller svin, og svinebog på beinet er den letteste av de to å få tak i. Den er fetere og søtere, så ta hardere i med chilien, og hold vinen tørr.'}},
    {title:{en:"A piece of 'nduja at the end", no:"Et stykke 'nduja til slutt"},
     body:{en:"Calabrian cooks reach for it the way others reach for pepper. Melt a small piece into the finished sauce off the heat; it adds heat, salt and a smoked edge without any of the tomato freshness being cooked away.",
           no:"Calabriske kokker griper etter den slik andre griper etter pepper. Smelt et lite stykke inn i den ferdige sausen med gryten av platen. Den gir styrke, salt og et røykpreg uten at noe av friskheten i tomaten kokes bort."}},
  ],
},

{
  id:'pesce-spada-alla-bagnarese', dish:'Swordfish alla bagnarese', course:'secondo', lesson:3, serves:4, time:{prep:15, cook:5},
  hero:'spada', tags:['fish','grill','lemon','oregano'],
  title:{en:'Pesce spada alla bagnarese', no:'Pesce spada alla bagnarese'},
  blurb:{en:'Thin slices of swordfish off a fierce grill, dressed while they are hot with oil, lemon and oregano beaten to an emulsion.',
         no:'Tynne skiver sverdfisk fra en glovarm grill, overhelt mens de er varme med olje, sitron og oregano pisket til en emulsjon.'},
  heroCaption:{en:'Swordfish on the grill at a festival on the Sicilian shore of the strait, and the dish of oil and oregano standing ready behind it.',
               no:'Sverdfisk på grillen under en festival på den sicilianske siden av stredet, og fatet med olje og oregano står klart bak.'},
  wines:['Cirò Bianco (Greco Bianco)'],
  headnote:{
    en:'<p>Swordfish is the fish of the Strait of Messina, and the reading describes the fishery that takes it: boats with a mast for the spotter and a walkway thirty metres out over the bow for the harpooner, a direct descendant of a fishery the Greeks wrote about. The name of this dish points at Bagnara Calabra, a town on the Calabrian shore of the strait.</p>'
      + '<p>The treatment is the one the reading gives: thin slices with lemon, oil and oregano. The dressing has a name on both sides of the water, salmoriglio, and it is the whole dish. It is not a marinade. It goes onto hot fish at the end, where the heat opens it out and drives the oregano into the room.</p>'
      + '<p>Swordfish is lean and dense, with almost no fat to forgive a cook. It is juicy at the moment the centre turns opaque and dry a minute later. So the slices are cut thin, the grill is properly hot, and the fish comes off it a shade before you think it should. In Norway the fish is expensive and mostly sold frozen; a thick halibut steak takes the same treatment, and so does tuna.</p>',
    no:'<p>Sverdfisken hører Messinastredet til, og lesteksten beskriver fisket som henter den: båter med utkikksmast og en gangbro tretti meter ut over baugen for harpuneren, en direkte etterkommer av et fiske grekerne skrev om. Navnet på retten peker mot Bagnara Calabra, en by på den calabriske siden av stredet.</p>'
      + '<p>Behandlingen er den lesteksten gir: tynne skiver med sitron, olje og oregano. Sausen heter salmoriglio på begge sider av vannet, og den er hele retten. Den er ingen marinade, for den går på varm fisk til slutt, der varmen åpner den opp og driver oreganoduften ut i rommet.</p>'
      + '<p>Sverdfisken er mager og fast, og har nesten ikke fett som kan tilgi en kokk. Den er saftig i det øyeblikket kjernen blir ugjennomsiktig, og tørr et minutt senere. Derfor skjæres skivene tynne, grillen skal være skikkelig varm, og fisken tas av et hakk før du tror den er ferdig. I Norge er fisken dyr og selges stort sett frossen. En tykk skive kveite tåler den samme behandlingen, og det gjør tunfisk også.</p>'},
  ingredients:[
    { group:{en:'The fish', no:'Fisken'}, items:[
      {q:600, u:'g', n:{en:'swordfish, in slices about a centimetre thick', no:'sverdfisk, i skiver på rundt en centimeter'},
       note:{en:'ask for centre cut of even thickness. Frozen and slowly thawed is honest here; kveite or tuna will stand in, and both want the same short time over the heat',
             no:'be om midtstykker med jevn tykkelse. Frossen og langsomt tint er helt ærlig her. Kveite eller tunfisk kan tre inn i stedet, og begge vil ha den samme korte tiden over varmen'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'Salmoriglio', no:'Salmoriglio'}, items:[
      {q:100, u:'ml', n:{en:'olive oil', no:'olivenolje'}},
      {q:50, u:'ml', n:{en:'lemon juice', no:'sitronsaft'}},
      {q:30, u:'ml', n:{en:'hot water', no:'varmt vann'}},
      {q:1, u:'', n:{en:'clove of garlic', no:'hvitløksfedd'}, round:'half'},
      {u:'', n:{en:'dried oregano', no:'tørket oregano'}, scale:'none',
       note:{en:'dried, not fresh. Southern oregano is dried in bunches and its aroma is concentrated rather than green',
             no:'tørket, ikke fersk. Oreganoen i sør tørkes i knipper, og duften blir konsentrert heller enn grønn'}},
      {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
      {q:1, u:'', n:{en:'lemon, to serve', no:'sitron, til servering'}, round:'half'},
    ]},
  ],
  steps:[
    {en:'Take the fish out of the fridge twenty minutes before it cooks, so the centre is not cold when it goes on the heat.',
     no:'Ta fisken ut av kjøleskapet tjue minutter før den skal stekes, slik at kjernen ikke er kald når den går på varmen.'},
    {en:'Crush the garlic with a little salt to a smooth paste, in a mortar or under the flat of a knife.',
     no:'Knus hvitløken med litt salt til en jevn masse, i morter eller under den flate siden av en kniv.'},
    {en:'Whisk the lemon juice into the garlic in a bowl.',
     no:'Visp sitronsaften inn i hvitløken i en bolle.'},
    {en:'Pour the oil in slowly, whisking all the time, until the sauce thickens and turns cloudy.',
     no:'Hell oljen i langsomt mens du visper hele tiden, til sausen tykner og blir uklar.'},
    {en:'Whisk in the hot water. This is what holds the sauce together instead of letting the oil float off on its own.',
     no:'Visp inn det varme vannet. Det holder sausen samlet i stedet for å la oljen flyte av gårde for seg selv.'},
    {en:'Crumble the dried oregano between your palms straight into the sauce and grind in pepper.',
     no:'Smuldre den tørkede oreganoen mellom håndflatene rett ned i sausen, og kvern over pepper.'},
    {en:'Heat a ridged grill pan or a barbecue until a drop of water skitters across it and vanishes.',
     no:'Varm en grillpanne med riller eller en kullgrill til en vanndråpe farer over den og forsvinner.'},
    {en:'Brush the slices with a little of the sauce and salt them on both sides.',
     no:'Pensle skivene med litt av sausen, og salt dem på begge sider.'},
    {en:'Grill them for about ninety seconds a side. The centre should just turn opaque, and the slices should still give under a finger.',
     no:'Grill dem i rundt nitti sekunder på hver side. Kjernen skal så vidt bli ugjennomsiktig, og skivene skal fortsatt gi etter under en finger.'},
    {en:'Move them to a warm dish and spoon the rest of the sauce over while they are hot.',
     no:'Legg dem over på et varmt fat, og skje resten av sausen over mens de er varme.'},
    {en:'Let them stand for two minutes so the sauce warms through, then serve with lemon.',
     no:'La dem stå i to minutter, slik at sausen blir gjennomvarm, og server med sitron.'},
  ],
  notes:[
    {title:{en:'Why the hot water matters', no:'Derfor betyr det varme vannet mye'},
     body:{en:'Oil and lemon juice separate the moment you stop whisking. Hot water, beaten in last, gives the mixture enough water phase to hold a loose emulsion for the few minutes it needs, so the sauce coats the fish evenly instead of leaving lemon underneath and oil on top. It is also why salmoriglio is made just before it is used and never kept.',
           no:'Olje og sitronsaft skiller seg i det øyeblikket du slutter å vispe. Varmt vann, pisket inn til slutt, gir blandingen nok vannfase til å holde en løs emulsjon de minuttene den trenger, og sausen legger seg jevnt på fisken i stedet for å etterlate sitron under og olje over. Derfor lages salmoriglio rett før den skal brukes, og aldri på forhånd.'}},
    {title:{en:'Thin and fast', no:'Tynt og fort'},
     body:{en:'Swordfish muscle holds little fat and little connective tissue, so there is nothing to melt and nothing to lubricate it. Past about 60 °C in the centre the proteins contract and push out water, and a slice that was juicy becomes cotton. A thin slice over fierce heat spends less time in that danger zone than a thick one over moderate heat.',
           no:'Muskelen i sverdfisk har lite fett og lite bindevev, så det finnes ingenting som smelter og ingenting som smører. Over rundt 60 °C i kjernen trekker proteinene seg sammen og presser ut vann, og en skive som var saftig, blir til bomull. En tynn skive over sterk varme tilbringer mindre tid i den faresonen enn en tykk skive over moderat varme.'}},
    {title:{en:'Dried oregano, rubbed', no:'Tørket oregano, gnidd'},
     body:{en:'The aroma sits in oil glands on the leaf, and rubbing the dry leaves between your palms breaks them open on the way into the bowl. Fresh oregano is wetter and milder and disappears against grilled fish; the south dries it for a reason.',
           no:'Duften sitter i oljekjertler på bladet, og når du gnir de tørre bladene mellom håndflatene, brytes kjertlene opp på veien ned i bollen. Fersk oregano er våtere og mildere og forsvinner mot grillet fisk. Sør i Italia tørkes den av en grunn.'}},
  ],
  variations:[
    {title:{en:'Involtini', no:'Involtini'},
     body:{en:'The reading names the other treatment: slices rolled around breadcrumbs and capers. Beat the slices thinner, fill them with breadcrumbs fried in oil with capers and chopped parsley, roll them, hold each with a cocktail stick and grill them for a minute a side.',
           no:'Lesteksten nevner den andre behandlingen: skiver rullet rundt brødsmuler og kapers. Bank skivene tynnere, fyll dem med brødsmuler stekt i olje med kapers og hakket persille, rull dem sammen, fest hver av dem med en tannpirker, og grill dem et minutt på hver side.'}},
    {title:{en:'Kveite or tuna', no:'Kveite eller tunfisk'},
     body:{en:'Both are dense enough to cut in even slices and lean enough to behave the same way, and both are easier to buy fresh in Norway. Tuna wants even less time and is best left frankly rare in the middle.',
           no:'Begge er faste nok til å skjæres i jevne skiver og magre nok til å oppføre seg likt, og begge er lettere å få tak i ferske i Norge. Tunfisk vil ha enda kortere tid, og den er best når den får være tydelig lite stekt i midten.'}},
    {title:{en:'The same sauce elsewhere', no:'Den samme sausen til andre retter'},
     body:{en:'Salmoriglio belongs to anything that comes off a grill: lamb chops, chicken, thick slices of aubergine, or a head of grilled spring onions. Make it in the same order and use it the same way, hot and at the last moment.',
           no:'Salmoriglio hører til alt som kommer av en grill: lammekoteletter, kylling, tykke skiver aubergine eller et knippe grillet vårløk. Lag den i samme rekkefølge, og bruk den på samme måte, varm og i siste øyeblikk.'}},
  ],
},

{
  id:'cipolle-di-tropea-ripiene', dish:'Cipolla rossa di Tropea', course:'contorno', lesson:3, serves:4, time:{prep:35, cook:45},
  hero:'venditore', tags:['onion','baked','breadcrumbs','pecorino'],
  title:{en:'Cipolle di Tropea ripiene', no:'Cipolle di Tropea ripiene'},
  blurb:{en:'Red onions blanched, hollowed and baked with a filling of their own centres, breadcrumbs, pecorino and oregano.',
         no:'Rødløk som forvelles, hules ut og bakes med et fyll av sine egne midtpartier, brødsmuler, pecorino og oregano.'},
  heroCaption:{en:'No free photograph of the dish exists. This is where it starts: Tropea onions in plaited strings, sold from a three-wheeler on the coast road.',
               no:'Det finnes ikke noe fritt bilde av retten. Her begynner den: Tropea-løk i flettede kranser, solgt fra en trehjuling langs kystveien.'},
  wines:['Cirò Bianco (Greco Bianco)'],
  headnote:{
    en:'<p>The Cipolla Rossa di Tropea Calabria is a long purple-red onion grown on the sandy coastal strip between Nicotera and Campora San Giovanni, IGP since 2008 and sweetest around Briatico and Capo Vaticano. The reading gives the Italian explanation of why: a winter without sharp swings in temperature, moderated by the sea, and cool silty soils. It names three things the onion is used for, and this is the third of them, stuffed and baked.</p>'
      + "<p>An onion's bite comes from sulphur compounds that are only released when the cells are cut, and heat breaks them down while the sugars stay where they are. So the oven does to any onion some of what the Tropea winter does for nothing. The shells have to be blanched first, though. A raw onion cup is still hard at the point where the filling on top has burnt, because the outer layers insulate the ones behind them.</p>"
      + '<p>Tropea onions are not sold in Norway. Use the largest and flattest red onions in the shop. They are sharper and hold less water, so give them longer in the pot, take the softening of the chopped centres seriously, and expect a firmer and more assertive dish than the one they eat on the coast road.</p>',
    no:'<p>Cipolla Rossa di Tropea Calabria er en avlang, purpurrød løk som dyrkes på den sandholdige kyststripen mellom Nicotera og Campora San Giovanni, IGP siden 2008 og søtest rundt Briatico og Capo Vaticano. Lesteksten gir den italienske forklaringen: en vinter uten brå temperatursvingninger, dempet av havet, og kjølig, siltholdig jord. Den nevner tre ting løken brukes til, og dette er den tredje av dem, fylt og bakt i ovn.</p>'
      + '<p>Skarpheten i en løk kommer fra svovelforbindelser som først frigjøres når cellene skjæres over, og varme bryter dem ned mens sukkeret blir liggende. En ovn kan derfor gi hvilken som helst løk noe av den sødmen vinteren i Tropea gir gratis. Men løkskallene må forvelles først. Et rått løkbeger er fortsatt hardt i det øyeblikket fyllet på toppen har brent seg, for de ytre lagene isolerer dem som ligger innenfor.</p>'
      + '<p>Tropea-løk selges ikke i Norge. Bruk de største og flateste rødløkene butikken har. De er skarpere og inneholder mindre vann, så gi dem lengre tid i kjelen, ta surringen av de utskrapte midtpartiene på alvor, og regn med en fastere og mer pågående rett enn den de spiser langs kystveien.</p>'},
  ingredients:[
    { group:{en:'', no:''}, items:[
      {q:4, u:'', n:{en:'large red onions', no:'store rødløk'}, round:'half',
       note:{en:'Tropea onions if you ever find them; otherwise the biggest and flattest red onions on the shelf, about 200 g each',
             no:'Tropea-løk hvis du noen gang finner dem. Ellers de største og flateste rødløkene i hyllen, på rundt 200 g hver'}},
      {q:80, u:'g', n:{en:'dry breadcrumbs', no:'tørre brødsmuler'},
       note:{en:'from stale bread, coarse rather than sandy. Fresh crumbs turn the filling to paste',
             no:'av tørt brød, grove heller enn fine som sand. Ferske smuler gjør fyllet til en klissen masse'}},
      {q:60, u:'g', n:{en:'pecorino crotonese', no:'pecorino crotonese'},
       note:{en:'grated; any hard sheep cheese does. Pecorino Romano is saltier, so use less salt',
             no:'revet. Enhver hard sauost går. Pecorino Romano er saltere, så bruk mindre salt'}},
      {q:1, u:'', n:{en:'egg', no:'egg'}, round:'half'},
      {q:15, u:'g', n:{en:'flat-leaf parsley', no:'bladpersille'}, note:{en:'chopped', no:'hakket'}},
      {q:50, u:'ml', n:{en:'olive oil', no:'olivenolje'}},
      {q:100, u:'ml', n:{en:'water for the dish', no:'vann til formen'}},
      {u:'', n:{en:'dried oregano', no:'tørket oregano'}, scale:'none'},
      {u:'', n:{en:'salt and pepper', no:'salt og pepper'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Heat the oven to 190 °C.',
     no:'Varm ovnen til 190 °C.'},
    {en:'Peel the onions and trim the root end flat, leaving the base itself attached so the layers hold together.',
     no:'Skrell løkene, og skjær rotenden flat, men la selve rotfestet sitte igjen slik at lagene henger sammen.'},
    {en:'Boil them whole in salted water for about twelve minutes, until a knife slides into the outer layers but meets resistance further in.',
     no:'Kok dem hele i saltet vann i rundt tolv minutter, til en kniv glir inn i de ytre lagene, men møter motstand lenger inne.'},
    {en:'Drain them upside down and leave them until you can handle them.',
     no:'Hell av vannet, sett dem opp ned, og la dem stå til du kan ta i dem.'},
    {en:'Cut each onion in half across its middle, not through the root.',
     no:'Del hver løk i to på tvers over midten, ikke gjennom roten.'},
    {en:'Scoop out the centres with a small spoon, leaving a cup two or three layers thick.',
     no:'Skrap ut midten med en liten skje, og la det stå igjen et beger på to eller tre lag.'},
    {en:'Chop the scooped centres finely.',
     no:'Hakk de utskrapte midtpartiene fint.'},
    {en:'Soften them in a little of the oil over low heat until they are translucent and taste sweet, then let them cool.',
     no:'La dem mykne i litt av oljen på svak varme til de er blanke, myke og søte på smak, og la dem så kjølne.'},
    {en:'Mix them with the breadcrumbs, the cheese, the parsley, the oregano and the egg, and season carefully.',
     no:'Bland dem med brødsmulene, osten, persillen, oreganoen og egget, og smak forsiktig til.'},
    {en:'Fill the cups, mounding the filling a little above the rim.',
     no:'Fyll begrene, og la fyllet hvelve seg litt over kanten.'},
    {en:'Sit them in an oiled dish, pour the water around them and trickle the rest of the oil over the tops.',
     no:'Sett dem i en oljet ildfast form, hell vannet rundt dem, og drypp resten av oljen over toppene.'},
    {en:'Bake for about thirty minutes, until the tops are brown and crisp and a knife goes through the side without resistance, and let them cool to warm before they go to the table.',
     no:'Stek i rundt tretti minutter, til toppene er brune og sprø og en kniv går gjennom siden uten motstand, og la dem kjølne til de er lune før de settes på bordet.'},
  ],
  notes:[
    {title:{en:'Why this onion can be eaten raw', no:'Derfor kan denne løken spises rå'},
     body:{en:'Pungency is not a fixed property of the bulb. It is made at the moment of cutting, when an enzyme meets sulphur compounds stored separately in the cell, and how much there is to meet depends on the sulphur in the soil and on how the plant grew. The mild winter and cool silty soils the reading describes give a bulb with less of it and more water, which is why Tropea goes into a salad and a Norwegian storage onion does not.',
           no:'Skarpheten er ingen fast egenskap ved løken. Den oppstår i det øyeblikket løken skjæres, når et enzym møter svovelforbindelser som ligger lagret hver for seg i cellen, og hvor mye som møtes, avhenger av svovelet i jorden og av hvordan planten har vokst. Den milde vinteren og den kjølige, siltholdige jorden lesteksten beskriver, gir en løk med mindre av det og mer vann, og derfor går Tropea-løken i en salat mens en norsk lagringsløk ikke gjør det.'}},
    {title:{en:'Blanch, then bake', no:'Forvell først, stek etterpå'},
     body:{en:'Each onion layer insulates the ones inside it, so a raw cup cooks from the outside at a crawl while the breadcrumbs on top are exposed to the full heat of the oven. Twelve minutes in water gets the shell most of the way there and lets the oven do nothing but brown the filling and finish the last layers.',
           no:'Hvert løklag isolerer dem som ligger innenfor, og et rått beger varmes derfor opp utenfra i sneglefart mens brødsmulene på toppen ligger utsatt for ovnens fulle varme. Tolv minutter i vann bringer skallet mesteparten av veien, og ovnen får da ikke annet å gjøre enn å brune fyllet og gjøre de siste lagene ferdige.'}},
    {title:{en:'Warm beats hot', no:'Lunt slår rykende varmt'},
     body:{en:'Baked onions taste sweeter and smell of more once they have come down from oven heat, and the filling sets enough to be lifted out in one piece. The same dish is very good cold the next day, which is how a Calabrian kitchen would treat it anyway.',
           no:'Bakt løk smaker søtere og dufter av mer når den har kommet ned fra ovnsvarmen, og fyllet stivner nok til at det kan løftes ut i ett stykke. Den samme retten er svært god kald dagen etter, og slik ville et calabrisk kjøkken uansett ha behandlet den.'}},
  ],
  variations:[
    {title:{en:'The salad', no:'Salaten'},
     body:{en:'The simplest of the three uses the reading names. Slice the onion as thinly as you can, salt it, leave it ten minutes, then dress it with oil and dried oregano. Made with a Norwegian red onion, rinse the slices in cold water first and dry them.',
           no:'Den enkleste av de tre bruksmåtene lesteksten nevner. Skjær løken så tynt du klarer, salt den, la den stå i ti minutter, og bland den så med olje og tørket oregano. Bruker du norsk rødløk, skyll skivene i kaldt vann først, og tørk dem.'}},
    {title:{en:'The jam', no:'Syltetøyet'},
     body:{en:'The reading mentions a jam eaten with cheese. Cook sliced onions down slowly with sugar and red wine vinegar until they are sticky and dark, jar them hot, and serve them with caciocavallo silano or an aged pecorino.',
           no:'Lesteksten nevner et syltetøy som spises til ost. Kok løk i skiver langsomt inn med sukker og rødvinseddik til massen er mørk og seig, fyll den varm på glass, og server den til caciocavallo silano eller en lagret pecorino.'}},
    {title:{en:"'Nduja in the filling", no:"'Nduja i fyllet"},
     body:{en:"A Calabrian addition that costs nothing: work a small piece into the softened onion centres while they are still warm, so that it melts through the breadcrumbs. Then leave the cheese out, or the filling turns salty.",
           no:"Et calabrisk tilskudd som ikke koster noe. Arbeid et lite stykke inn i den surrede løken mens den fortsatt er varm, slik at den smelter gjennom brødsmulene. Da kan du sløyfe osten, ellers blir fyllet salt."}},
  ],
},

];
