// campania recipes. Contract: docs/recipe-format.md. Both languages in one file; never narrated.
// Everything here follows the Campania food reading (content/campania.js, lesson 3): the written rules of
// pizza napoletana, buffalo mozzarella as a wet fresh cheese, Gragnano pasta, the Sunday ragù of whole cuts,
// and the semolina-and-ricotta filling that both kinds of sfogliatella share.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-72'] = [

{
  id:'pizza-napoletana', dish:'Pizza napoletana', course:'primo', lesson:3, serves:4, time:{prep:40, cook:10},
  hero:'pizza', tags:['pizza','dough','tomato'],
  title:{en:'Pizza napoletana', no:'Pizza napoletana'},
  blurb:{en:'Four ingredients in the dough, eight hours of rising and no rolling pin. Soft and foldable, not crisp.',
         no:'Fire ingredienser i deigen, åtte timers heving og ikke noe kjevle. Myk og brettbar, ikke sprø.'},
  heroCaption:{en:'A margherita in a Neapolitan wood oven: sixty to ninety seconds at 485 °C, and the rim blisters and chars.',
               no:'En margherita i en napolitansk vedovn: seksti til nitti sekunder på 485 °C, og kanten blemmer og svartner.'},
  wines:['Falanghina'],
  headnote:{
    en:'<p>The rules are written down, which is rare for a folk dish. The <em>Associazione Verace Pizza Napoletana</em>, founded in 1984, and the EU’s Traditional Speciality Guaranteed status of 2010 say what a <strong>pizza napoletana</strong> is: soft wheat flour, water, salt and yeast and nothing else; at least eight hours of rising; shaped by hand, never with a rolling pin; a rim of one to two centimetres; a wood-fired dome oven at about 485 °C; sixty to ninety seconds of baking.</p>'
      + '<p>Every one of those rules is doing a job. The long rise relaxes the gluten so the disc can be stretched thin without tearing, and the same hours make the pizza light to eat. Shaping with the fingertips from the middle outwards drives the gas into the rim instead of squashing it out, which is why a rolling pin is banned and why the <em>cornicione</em> puffs. The ferocious oven then sets that rim before the base has time to dry, and the result is soft, foldable and blistered black in spots, eaten with a knife and fork or folded in four as a <em>portafoglio</em>.</p>'
      + '<p>What a home kitchen cannot supply is the heat, so the method below buys as much of it as possible: a steel or a stone soaked in the oven’s full heat for an hour, and the grill on. The two classic toppings are marinara — tomato, garlic, oregano, oil, no cheese, and the older of the two — and margherita. The tomatoes are crushed raw and never cooked first, and the buffalo mozzarella is drained, because it is a wet cheese and will otherwise flood the pizza.</p>',
    no:'<p>Reglene er nedskrevet, og det er sjelden for en folkerett. <em>Associazione Verace Pizza Napoletana</em>, grunnlagt i 1984, og EU-merkingen garantert tradisjonell spesialitet fra 2010 sier hva en <strong>pizza napoletana</strong> er: bare hvetemel, vann, salt og gjær; minst åtte timers heving; formet for hånd og aldri med kjevle; en kant på én til to centimeter; en vedfyrt kuppelovn på rundt 485 °C; seksti til nitti sekunders steking.</p>'
      + '<p>Hver eneste regel gjør en jobb. Den lange hevingen mykner glutenet, slik at leiven kan strekkes tynn uten å revne, og de samme timene gjør pizzaen lett å spise. Når du former den med fingertuppene fra midten og utover, presses gassen ut i kanten i stedet for ut av deigen, og derfor er kjevlet bannlyst og derfor sveller <em>cornicione</em>. Den glohete ovnen setter kanten før bunnen rekker å tørke ut, og resultatet er mykt og brettbart, med svarte blemmer her og der. Det spises med kniv og gaffel eller brettet i fire som en <em>portafoglio</em>.</p>'
      + '<p>Varmen er det et hjemmekjøkken ikke kan skaffe, og derfor kjøper metoden nedenfor så mye av den som mulig: et bakestål eller en stein som får ligge en time i ovnens fulle varme, og grillelementet på. De to klassiske utgavene er marinara, med tomat, hvitløk, oregano og olje, uten ost, og den eldste av de to, og margherita. Tomatene moses rå og kokes aldri på forhånd, og mozzarellaen renner av seg, for den er en våt ost og vil ellers oversvømme pizzaen.</p>'},
  ingredients:[{ group:{en:'For the dough', no:'Til deigen'}, items:[
    {q:600, u:'g', n:{en:'soft wheat flour', no:'hvetemel'}, note:{en:'tipo 00, a strong one if you can find it', no:'tipo 00, gjerne et sterkt mel'}},
    {q:370, u:'ml', n:{en:'water', no:'vann'}, note:{en:'at room temperature', no:'med romtemperatur'}},
    {q:17, u:'g', n:{en:'fine salt', no:'fint salt'}},
    {q:1, u:'g', n:{en:'dry yeast', no:'tørrgjær'}, note:{en:'or three times as much fresh yeast; less yeast, longer rise, better pizza', no:'eller tre ganger så mye fersk gjær; mindre gjær gir lengre heving og bedre pizza'}},
  ]}, { group:{en:'For the topping', no:'Til pålegget'}, items:[
    {q:400, u:'g', n:{en:'peeled plum tomatoes', no:'hermetiske plommetomater'}, note:{en:'San Marzano DOP if you find them; crushed by hand, never cooked', no:'San Marzano DOP hvis du finner dem; moses for hånd og kokes aldri'}},
    {q:250, u:'g', n:{en:'mozzarella di bufala', no:'mozzarella di bufala'}, note:{en:'torn and drained; fior di latte is the drier everyday choice', no:'revet i biter og avrent; fior di latte er det tørrere hverdagsvalget'}},
    {q:12, u:'', n:{en:'basil leaves', no:'basilikumblader'}},
    {q:30, u:'ml', n:{en:'extra virgin olive oil', no:'ekstra virgin olivenolje'}},
    {u:'', n:{en:'salt for the tomatoes', no:'salt til tomatene'}, scale:'none'},
  ]}],
  steps:[
    {en:'Stir the salt into the water in a large bowl until it dissolves.',
     no:'Rør saltet ut i vannet i en stor bolle til det er oppløst.'},
    {en:'Whisk in about a tenth of the flour, then the yeast. Salt kills yeast on direct contact, so let them meet in dilution.',
     no:'Visp inn omtrent en tidel av melet, og deretter gjæren. Salt tar livet av gjær ved direkte kontakt, så la dem møtes i fortynnet form.'},
    {en:'Work in the rest of the flour a handful at a time, then knead for ten minutes until the dough is smooth and springs back when you press it.',
     no:'Arbeid inn resten av melet en neve om gangen, og elt så i ti minutter til deigen er glatt og spretter tilbake når du trykker på den.'},
    {en:'Cover the bowl and leave the dough at room temperature for two hours.',
     no:'Dekk til bollen, og la deigen stå i romtemperatur i to timer.'},
    {en:'Divide it into four equal balls, tucking the edges underneath so each is taut on top. Set them apart on a floured tray, cover, and leave them for six hours more.',
     no:'Del den i fire like kuler, og brett kantene inn under slik at hver kule blir stram på oversiden. Sett dem med god avstand på et melet brett, dekk dem til, og la dem stå i seks timer til.'},
    {en:'An hour before you bake, put a baking steel or a pizza stone on the top shelf and heat the oven as high as it will go. The stone has to be as hot as the air around it.',
     no:'Sett et bakestål eller en pizzastein øverst i ovnen en time før du steker, og varm ovnen så høyt den går. Steinen må bli like varm som luften rundt den.'},
    {en:'Crush the tomatoes with your hands and salt them lightly. They go on raw; cooking them first is a Roman habit, not a Neapolitan one.',
     no:'Mos tomatene med hendene, og salt dem lett. De skal på rå, for å koke dem først er en romersk vane og ikke en napolitansk.'},
    {en:'Tear the mozzarella into strips and leave it to drain in a sieve while the oven heats.',
     no:'Riv mozzarellaen i strimler, og la den renne av seg i et dørslag mens ovnen varmes opp.'},
    {en:'Flatten one ball on a floured surface with your fingertips, working from the middle outwards and leaving the outer two centimetres untouched, then stretch it over your knuckles to about thirty centimetres.',
     no:'Trykk ut én kule på et melet underlag med fingertuppene. Arbeid fra midten og utover, la de ytterste to centimeterne være urørt, og strekk leiven over knokene til den måler rundt tretti centimeter.'},
    {en:'Spread a thin spiral of tomato over it, leaving the rim bare, scatter over some of the mozzarella and a few basil leaves, and trickle oil across.',
     no:'Legg et tynt lag tomat utover i en spiral, la kanten være bar, strø over litt av mozzarellaen og noen basilikumblader, og hell olje over i en tynn stråle.'},
    {en:'Slide the pizza onto the hot stone, turn the grill on, and bake for five to seven minutes until the rim is puffed and spotted black. Eat it at once, and top the next one while it bakes.',
     no:'Dra pizzaen over på den varme steinen, slå på grillelementet, og stek i fem til sju minutter til kanten er svulmet opp og har svarte flekker. Spis den med en gang, og legg pålegg på den neste mens den steker.'},
  ],
  notes:[
    {title:{en:'Eight hours is not a suggestion', no:'Åtte timer er ikke et forslag'},
     body:{en:'A long, cool rise does two things a short one cannot: enzymes slacken the gluten so the disc stretches thin without tearing, and the fermentation breaks down sugars and proteins that would otherwise sit heavily. A dough rushed with extra yeast can be made round, but it fights back, tears in the middle and lies in the stomach.',
           no:'En lang og kjølig heving gjør to ting en kort heving ikke klarer: enzymene mykner glutenet slik at leiven lar seg strekke tynn uten å revne, og gjæringen bryter ned sukker og proteiner som ellers ligger tungt. En deig som forseres med mer gjær, lar seg nok formes rund, men den strammer seg imot, revner på midten og blir tung å fordøye.'}},
    {title:{en:'The rim is made of trapped gas', no:'Kanten er innestengt gass'},
     body:{en:'Pressing from the centre outwards pushes the bubbles into the outer two centimetres, where the heat of the oven expands them all at once. A rolling pin drives that gas out of the dough altogether, which is why the rule against it is absolute and why nothing at all goes on the rim.',
           no:'Når du trykker fra midten og utover, presses boblene ut i de ytterste to centimeterne, der ovnsvarmen utvider dem alle på én gang. Et kjevle presser gassen helt ut av deigen, og derfor er forbudet mot kjevle absolutt, og derfor skal det ikke ligge noe som helst på kanten.'}},
    {title:{en:'Buffalo mozzarella is wet', no:'Mozzarella di bufala er våt'},
     body:{en:'It is kept in its own whey and gives that whey up the moment it warms. Tearing it and draining it beforehand is the difference between a pizza and a puddle; many Neapolitan pizzerias sidestep the problem by using the drier fior di latte and saving the buffalo for a cold plate.',
           no:'Den oppbevares i sin egen myse og gir fra seg mysen i det øyeblikket den blir varm. River du den opp og lar den renne av på forhånd, får du en pizza og ikke en pytt. Mange napolitanske pizzeriaer går utenom problemet ved å bruke den tørrere fior di latte og spare bøffelmozzarellaen til et kaldt fat.'}},
  ],
  variations:[
    {title:{en:'Marinara', no:'Marinara'},
     body:{en:'The older of the two classics and the cheaper: tomato, a sliced clove of garlic, oregano and oil, and no cheese at all. It is the better test of a dough, because there is nothing on top to hide behind.',
           no:'Den eldste av de to klassikerne og den rimeligste: tomat, et oppskåret hvitløksfedd, oregano og olje, uten ost. Den er den beste prøven på en deig, for det ligger ingenting oppå som deigen kan gjemme seg bak.'}},
    {title:{en:'Pizza fritta', no:'Pizza fritta'},
     body:{en:'The wartime pizza, sold when there was no fuel for the ovens: the same dough folded round ricotta, provola and a little tomato, sealed and deep-fried. Naples still eats it, and it needs no oven at all.',
           no:'Krigstidens pizza, solgt da det ikke fantes brensel til ovnene: den samme deigen brettet rundt ricotta, provola og litt tomat, klemt igjen og frityrstekt. Napoli spiser den fortsatt, og den trenger ingen ovn.'}},
    {title:{en:'A pan instead of a stone', no:'Panne i stedet for stein'},
     body:{en:'With no steel and no stone, start the pizza in a dry cast-iron pan on the hob until the base sets, then slide the pan under a hot grill to finish the top. It is a workaround, and it gets you closer than a baking sheet does.',
           no:'Har du verken stål eller stein, kan du starte pizzaen i en tørr støpejernspanne på platen til bunnen setter seg, og så sette pannen under en varm grill for å gjøre toppen ferdig. Det er en nødløsning, men den kommer nærmere enn et stekebrett.'}},
  ],
},

{
  id:'ragu-napoletano', dish:'Ragù napoletano', course:'primo', lesson:3, serves:6, time:{prep:30, cook:300},
  hero:'ragu', tags:['sauce','beef','pork','sunday'],
  title:{en:'Ragù napoletano', no:'Ragù napoletano'},
  blurb:{en:'The Sunday sauce: whole cuts of beef and pork muttering in tomato for five hours. The sauce dresses the pasta, the meat follows.',
         no:'Søndagssausen: hele stykker av okse- og svinekjøtt som mumler i tomat i fem timer. Sausen går på pastaen, kjøttet kommer etter.'},
  heroCaption:{en:'Paccheri under Neapolitan ragù, the meat shredded into a sauce that has gone dark with hours.',
               no:'Paccheri under napolitansk ragù, med kjøtt som er trukket fra hverandre i en saus som har mørknet av timene.'},
  wines:['Taurasi (Aglianico)'],
  headnote:{
    en:'<p>This is not the ragù of Bologna, and Neapolitans mind the confusion. There is no mince in it. Whole cuts of beef and pork go in, browned and then left in tomato for four to six hours until the sauce is dark and the meat falls apart. Some cooks roll and tie slices of beef around garlic and parsley as <em>braciole</em> and put those in too.</p>'
      + '<p>It is a two-course dish out of one pot, and that is its whole economy. The sauce dresses the pasta as a first course, the meat is carried in afterwards as the second, and a family that could afford one piece of beef a week ate from it twice. It is started early on Sunday morning, and by ten the whole stairwell knows.</p>'
      + '<p>The one thing that cannot be hurried is the heat. Neapolitans say the sauce should <em>pippiare</em>, mutter, and they mean it literally: a bubble breaking every few seconds at the edge of the pot, never a rolling boil. Below the boil the collagen in a hard-working cut turns slowly to gelatin, and that gelatin is what makes the finished sauce cling. Above it, the fibres tighten and squeeze out their water, and five hours gives you dry meat in thin tomato.</p>',
    no:'<p>Dette er ikke ragùen fra Bologna, og napolitanerne liker dårlig at de blandes sammen. Her er det ikke kjøttdeig. Hele stykker av okse- og svinekjøtt brunes og trekker så i tomat i fire til seks timer, til sausen er mørk og kjøttet faller fra hverandre. Noen ruller og binder skiver av oksekjøtt rundt hvitløk og persille som <em>braciole</em> og legger dem i også.</p>'
      + '<p>Retten gir to retter av én gryte, og det er hele økonomien i den. Sausen går på pastaen som første rett, kjøttet bæres inn etterpå som hovedrett, og en familie som hadde råd til ett stykke oksekjøtt i uken, spiste av det to ganger. Gryten settes over tidlig søndag morgen, og ved titiden vet hele oppgangen om det.</p>'
      + '<p>Det eneste som ikke lar seg forsere, er varmen. Napolitanerne sier at sausen skal <em>pippiare</em>, mumle, og de mener det bokstavelig: en boble som brister med noen sekunders mellomrom i kanten av gryten, aldri fossekok. Under kokepunktet gjør bindevevet i et arbeidsomt kjøttstykke seg langsomt om til gelatin, og gelatinen er det som får den ferdige sausen til å henge. Over kokepunktet strammer fibrene seg og presser ut vannet, og da gir fem timer tørt kjøtt i tynn tomat.</p>'},
  ingredients:[{ group:{en:'For the sauce', no:'Til sausen'}, items:[
    {q:800, u:'g', n:{en:'braising beef in one piece', no:'grytekjøtt av okse i ett stykke'}, note:{en:'chuck or shoulder; a cut with connective tissue in it', no:'høyrygg eller bog, altså et stykke med bindevev i seg'}},
    {q:500, u:'g', n:{en:'pork ribs', no:'ribbespjell av svin'}, note:{en:'tracchie, cut apart between the bones', no:'tracchie, delt fra hverandre mellom beina'}},
    {q:400, u:'g', n:{en:'onions', no:'løk'}, note:{en:'sliced as finely as you can', no:'skåret så tynt du klarer'}},
    {q:40, u:'ml', n:{en:'extra virgin olive oil', no:'ekstra virgin olivenolje'}, note:{en:'or the same weight of lard, which is the older choice', no:'eller like mye svinefett, som er det eldre valget'}},
    {q:200, u:'ml', n:{en:'dry red wine', no:'tørr rødvin'}},
    {q:100, u:'g', n:{en:'tomato concentrate', no:'tomatpuré'}},
    {q:1500, u:'g', n:{en:'passata', no:'passata'}, note:{en:'sieved tomato; San Marzano if the shelf has it', no:'silt tomat; San Marzano hvis butikken har det'}},
    {q:10, u:'', n:{en:'basil leaves', no:'basilikumblader'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
  ]}, { group:{en:'To serve', no:'Til servering'}, items:[
    {q:600, u:'g', n:{en:'ziti spezzati', no:'ziti spezzati'}, note:{en:'long ziti snapped by hand; paccheri or rigatoni do the same job', no:'lang ziti brukket for hånd; paccheri eller rigatoni gjør samme nytten'}},
    {q:5, u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:25, u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
  ]}],
  steps:[
    {en:'Dry the beef and the ribs well and season them. Wet meat steams instead of browning.',
     no:'Tørk oksekjøttet og ribbespjellene godt, og salt og pepre dem. Vått kjøtt damper i stedet for å bli brunt.'},
    {en:'Brown them hard in the oil in a heavy pot, a few pieces at a time so the pot stays hot, and lift them out onto a plate.',
     no:'Brun dem kraftig i oljen i en tykkbunnet gryte, noen stykker om gangen så gryten holder på varmen, og løft dem over på et fat.'},
    {en:'Turn the heat down, put the onions into the same fat with a pinch of salt, and let them soften for forty minutes until they collapse and turn sweet. They should barely colour.',
     no:'Skru ned varmen, ha løken i det samme fettet med en klype salt, og la den mykne i førti minutter til den faller sammen og blir søt. Den skal knapt få farge.'},
    {en:'Return the meat, pour in the wine and let it boil away, scraping the brown from the bottom of the pot as it goes.',
     no:'Ha kjøttet tilbake, hell i vinen og la den koke bort mens du skraper det brune løs fra bunnen av gryten.'},
    {en:'Stir the concentrate into the onions and fry it for three or four minutes, until it darkens from red to brick. This is where the colour of the finished sauce comes from.',
     no:'Rør tomatpuréen inn i løken, og stek den i tre–fire minutter til den mørkner fra rødt til teglrødt. Det er her fargen på den ferdige sausen blir til.'},
    {en:'Pour in the passata, rinse the jar with a little water and add that too, and drop in the basil.',
     no:'Hell i passataen, skyll flasken med litt vann og ha det i også, og legg basilikumbladene oppi.'},
    {en:'Bring it to the point where one bubble breaks every few seconds, set the lid ajar and leave it there. Do not let it boil at any stage.',
     no:'Varm opp til det brister én boble med noen sekunders mellomrom, legg lokket på gløtt, og la gryten stå slik. Den skal ikke koke på noe tidspunkt.'},
    {en:'Stir every half hour with a wooden spoon, right across the bottom, and cook for at least four hours. The sauce turns from red to brown and the fat rises to the surface.',
     no:'Rør hver halvtime med tresleiv, godt langs bunnen, og la det stå i minst fire timer. Sausen går fra rødt til brunt, og fettet legger seg på overflaten.'},
    {en:'Skim off most of that fat, taste for salt and pepper, and lift the meat out onto a warm dish.',
     no:'Skum av det meste av fettet, smak til med salt og pepper, og løft kjøttet over på et varmt fat.'},
    {en:'Boil the pasta in well salted water, drain it a minute early and turn it through a ladleful of the sauce in the pot so it finishes in the sauce rather than under it.',
     no:'Kok pastaen i godt saltet vann, hell av vannet ett minutt før tiden, og vend den i en øse saus i gryten, slik at den blir ferdig i sausen og ikke under den.'},
    {en:'Serve the pasta first, then carry in the meat with the rest of the sauce over it as the second course.',
     no:'Server pastaen først, og bær så inn kjøttet med resten av sausen over som hovedrett.'},
  ],
  notes:[
    {title:{en:'Why it must mutter', no:'Hvorfor den må mumle'},
     body:{en:'Collagen turns to gelatin from about 70 °C and takes hours to do it. Kept below the boil, a working cut of beef goes soft and lends the sauce a body that no amount of reduction gives it. Boiled, the muscle fibres contract and wring out their water first, and the meat is dry long before the collagen has finished.',
           no:'Bindevev gjør seg om til gelatin fra rundt 70 °C, og det tar timer. Holdes gryten under kokepunktet, blir et arbeidsomt oksestykke mørt og gir sausen en fylde som ingen innkoking kan skaffe. Koker den, trekker muskelfibrene seg sammen og vrir ut vannet først, og kjøttet er tørt lenge før bindevevet er ferdig.'}},
    {title:{en:'Fry the concentrate', no:'Stek tomatpuréen'},
     body:{en:'Three minutes in hot fat browns the sugars and proteins in tomato concentrate and takes away its tinny edge. Stirred straight into liquid it stays raw and sharp for hours. The same trick is worth carrying to any long-cooked tomato sauce.',
           no:'Tre minutter i varmt fett bruner sukkeret og proteinene i tomatpuréen og tar bort den metalliske kanten. Røres den rett i væsken, blir den værende rå og skarp i timevis. Det samme grepet er verdt å ta med seg til enhver langkokt tomatsaus.'}},
    {title:{en:'One pot, two courses', no:'Én gryte, to retter'},
     body:{en:'The sauce and the meat are not a sauce with meat in it. They are a first course and a second, served in order, which is how one Sunday joint fed a household. Serving them together on the same plate is the mistake a Neapolitan grandmother will comment on.',
           no:'Sausen og kjøttet er ikke en saus med kjøtt i. De er en forrett og en hovedrett som serveres i rekkefølge, og slik mettet én søndagsstek et helt hushold. Setter du dem sammen på samme tallerken, er det den feilen en napolitansk bestemor kommenterer.'}},
  ],
  variations:[
    {title:{en:'Braciole', no:'Braciole'},
     body:{en:'Beat thin slices of beef out, lay garlic, parsley, pine nuts, raisins and grated pecorino on them, roll them up and tie them with string, then brown and cook them with the rest. They come out sweet and savoury at once and are the piece everyone at the table wants.',
           no:'Bank ut tynne skiver oksekjøtt, legg hvitløk, persille, pinjekjerner, rosiner og revet pecorino på dem, rull dem sammen og bind dem med hyssing, og brun og kok dem sammen med resten. De blir søte og smaksrike på én gang, og alle rundt bordet vil ha nettopp den biten.'}},
    {title:{en:'The Genovese', no:'Genovese'},
     body:{en:'Despite the name it is Neapolitan, and it is the same idea without tomato: beef under a mountain of sliced onions, cooked for hours until both collapse into a sweet brown sauce. Use three times the onion and leave out the passata and the concentrate.',
           no:'Tross navnet er den napolitansk, og den bygger på samme idé uten tomat: oksekjøtt under et fjell av skåret løk, kokt i timevis til begge deler faller sammen til en søt, brun saus. Bruk tre ganger så mye løk, og sløyf passataen og tomatpuréen.'}},
    {title:{en:'What to do with the rest', no:'Hva du gjør med resten'},
     body:{en:'A pot this size leaves sauce over, and it is better on the second day. Neapolitans use it for lasagne di carnevale, for baked pasta, and on a slice of bread standing at the stove while nobody is looking.',
           no:'En gryte av denne størrelsen gir saus til overs, og den er bedre dagen etter. Napolitanerne bruker den til lasagne di carnevale, til pasta al forno, og på en brødskive stående ved komfyren når ingen ser det.'}},
  ],
},

{
  id:'pasta-e-patate', dish:'Pasta e patate', course:'primo', lesson:3, serves:4, time:{prep:15, cook:40},
  hero:'pastapatate', tags:['pasta','potato','provola'],
  title:{en:'Pasta e patate con la provola', no:'Pasta e patate con la provola'},
  blurb:{en:'Pasta and potatoes cooked in one pot until they thicken each other, with smoked provola melted through at the end.',
         no:'Pasta og poteter kokt i én gryte til de tykner hverandre, med røkt provola smeltet inn på slutten.'},
  heroCaption:{en:'Pasta e patate: neither soup nor solid, and the spoon should stand up in it slowly.',
               no:'Pasta e patate: verken suppe eller fast rett, og skjeen skal reise seg langsomt i den.'},
  wines:['Lacryma Christi del Vesuvio'],
  headnote:{
    en:'<p>This is the cheapest dish in the Neapolitan repertoire and one of the best loved: pasta, potatoes, a soffritto and water, in one pot. It is the definition of comfort food, and it comes from the same habit of mind as the rest of the city’s cooking — almost no money, and everything got out of what there is.</p>'
      + '<p>The pasta is cooked in the pot rather than drained into it, which is the whole mechanism. Starch from the potatoes and starch from the pasta stay in the liquid and thicken it, so what binds the dish is not cream or butter but the ingredients giving themselves up. Naples has a word for the result — <em>azzeccata</em>, stuck together — and the test is a spoon standing up in the middle and slowly falling over.</p>'
      + '<p>The provola goes in at the end with the pot off the heat, in dice, and it should melt into threads without cooking. Smoked provola is the version everybody means; it brings the only strong flavour in the dish, and it must not be boiled or it splits and goes rubbery.</p>',
    no:'<p>Dette er den rimeligste retten i det napolitanske repertoaret og en av de mest avholdte: pasta, poteter, en soffritto og vann, i én gryte. Den er selve definisjonen på trøstemat, og den kommer av den samme tankegangen som resten av bymaten — nesten ingen penger, og alt hentet ut av det som finnes.</p>'
      + '<p>Pastaen kokes i gryten i stedet for å bli kokt for seg og helt over i den, og det er hele mekanismen. Stivelse fra potetene og stivelse fra pastaen blir værende i væsken og tykner den, så det som binder retten, er verken fløte eller smør, men råvarene som gir fra seg det de har. Napoli har et ord for resultatet, <em>azzeccata</em>, altså sammenklebet, og prøven er at skjeen står i midten og langsomt velter.</p>'
      + '<p>Provolaen går i til slutt med gryten av platen, i terninger, og den skal smelte til tråder uten å koke. Røkt provola er den utgaven alle mener, og den står for den eneste kraftige smaken i retten. Koker den, skiller den seg og blir gummiaktig.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:320, u:'g', n:{en:'pasta mista', no:'pasta mista'}, note:{en:'mixed short shapes; the different cooking times are the point, and a bag of odds and ends is the original', no:'blandede korte former; de ulike koketidene er nettopp poenget, og en pose med rester er originalen'}},
    {q:700, u:'g', n:{en:'floury potatoes', no:'melne poteter'}, note:{en:'peeled and cut into pieces of about 1.5 cm', no:'skrelt og skåret i biter på rundt 1,5 cm'}},
    {q:150, u:'g', n:{en:'provola affumicata', no:'provola affumicata'}, note:{en:'smoked provola, in dice; smoked scamorza will do', no:'røkt provola, i terninger; røkt scamorza gjør nytten'}},
    {q:100, u:'g', n:{en:'onion', no:'løk'}, note:{en:'chopped fine', no:'finhakket'}},
    {q:60, u:'g', n:{en:'carrot', no:'gulrot'}, note:{en:'chopped fine', no:'finhakket'}},
    {q:60, u:'g', n:{en:'celery', no:'stangselleri'}, note:{en:'chopped fine', no:'finhakket'}},
    {q:40, u:'ml', n:{en:'extra virgin olive oil', no:'ekstra virgin olivenolje'}},
    {q:1, u:'', n:{en:'piece of Parmigiano rind', no:'stykke skorpe av Parmigiano'}, note:{en:'optional, and the reason to keep the ends', no:'valgfritt, og grunnen til å ta vare på endestykkene'}, round:'half'},
    {q:1200, u:'ml', n:{en:'hot water', no:'varmt vann'}, note:{en:'added a little at a time, as for a risotto', no:'has i litt om gangen, som til en risotto'}},
    {q:4, u:'', n:{en:'basil leaves', no:'basilikumblader'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
  ]}],
  steps:[
    {en:'Chop the onion, carrot and celery as finely as you have patience for. They are meant to disappear into the dish, not to be met in it.',
     no:'Hakk løken, gulroten og sellerien så fint du orker. De skal forsvinne inn i retten, ikke møtes i den.'},
    {en:'Soften them in the oil over low heat for ten minutes without letting them colour.',
     no:'La dem mykne i oljen på svak varme i ti minutter uten å få farge.'},
    {en:'Add the potatoes and turn them in the fat for a few minutes so the outsides pick up a little of it.',
     no:'Ha i potetene, og vend dem i fettet i et par minutter så utsiden får med seg litt av det.'},
    {en:'Pour in enough hot water to cover, drop in the cheese rind and the basil, and simmer for fifteen minutes until the edges of the potato start to go soft.',
     no:'Hell på nok varmt vann til å dekke, legg i osteskorpen og basilikumbladene, og la det småkoke i femten minutter til kantene på potetbitene begynner å bli myke.'},
    {en:'Crush some of the potato against the side of the pot with the back of the spoon. That is the cream in this dish.',
     no:'Mos noen av potetbitene mot siden av gryten med baksiden av sleiven. Den mosede poteten er kremen i denne retten.'},
    {en:'Tip in the pasta and add hot water to cover it by a finger. Stir often from now on; the starch that thickens the dish will also stick it to the bottom.',
     no:'Ha i pastaen, og fyll på varmt vann så det dekker den med en fingerbredde. Rør ofte fra nå av, for stivelsen som tykner retten, fester den også til bunnen.'},
    {en:'Cook it like a risotto, adding hot water in small amounts whenever it tightens, until the pasta is al dente and the liquid has gone thick and glossy.',
     no:'Kok det som en risotto, og spe med litt varmt vann hver gang det strammer seg, til pastaen er al dente og væsken er blitt tykk og blank.'},
    {en:'Fish out the cheese rind, take the pot off the heat and let it stand for half a minute.',
     no:'Fisk ut osteskorpen, ta gryten av platen, og la den stå et halvt minutt.'},
    {en:'Stir in the diced provola until it pulls into threads. It must not boil after this.',
     no:'Rør inn provolaterningene til de trekker seg ut i tråder. Nå skal det ikke koke mer.'},
    {en:'Taste for salt, grind pepper over and let it rest for two minutes before serving. It should be neither soup nor solid: a spoon stood in the middle falls over slowly.',
     no:'Smak til med salt, kvern pepper over, og la retten hvile i to minutter før servering. Den skal verken være suppe eller fast: en skje som settes midt i, velter langsomt.'},
  ],
  notes:[
    {title:{en:'Why the pasta cooks in the pot', no:'Hvorfor pastaen kokes i gryten'},
     body:{en:'Boiled separately and drained, pasta throws its starch down the sink. Cooked in a small amount of liquid it leaves that starch behind, where it meets the starch already released by the potato, and the two thicken the dish into a sauce of its own making. The same principle is behind every risotto and behind pasta e fagioli.',
           no:'Koker du pastaen for seg og heller av vannet, går stivelsen i vasken. Koker du den i en liten mengde væske, blir stivelsen igjen, der den møter stivelsen poteten allerede har gitt fra seg, og sammen tykner de retten til en saus den lager selv. Det samme prinsippet ligger under enhver risotto og under pasta e fagioli.'}},
    {title:{en:'Cheese off the heat, again', no:'Ost med gryten av platen, igjen'},
     body:{en:'Provola is a stretched-curd cheese, and stretched curd above a simmer contracts and squeezes out its fat, so the dish turns greasy with rubbery lumps in it. Added to a pot that has stood for half a minute it melts into threads instead. The rule is the same one the Roman pastas live by.',
           no:'Provola er en ost av strukket ostemasse, og strukket ostemasse trekker seg sammen og presser ut fettet hvis den kommer over småkokende varme, så retten blir fet med gummiaktige klumper i seg. Has den i en gryte som har stått et halvt minutt, smelter den til tråder i stedet. Regelen er den samme som de romerske pastarettene lever etter.'}},
    {title:{en:'Mixed pasta is not a compromise', no:'Blandet pasta er ingen nødløsning'},
     body:{en:'Pasta mista began as the broken ends swept up in the shop and sold cheap, but the mixture is now made on purpose: the small shapes go soft and give up starch while the larger ones are still firm, and the dish gets both textures out of one pot.',
           no:'Pasta mista begynte som de knuste endene som ble feid sammen i butikken og solgt billig, men blandingen lages nå med vilje: de små formene blir myke og gir fra seg stivelse mens de større fortsatt har tyggemotstand, og retten får begge deler ut av én gryte.'}},
  ],
  variations:[
    {title:{en:'Bianca, without the provola', no:'Bianca, uten provolaen'},
     body:{en:'Left out, the dish becomes quieter and more everyday, seasoned only by the soffritto and the rind, and it is what many households eat on a weekday. A spoonful of grated Parmigiano at the table takes its place.',
           no:'Sløyfer du den, blir retten stillere og mer hverdagslig, smaksatt bare av soffritton og osteskorpen, og det er den mange hushold spiser på en ukedag. Litt revet Parmigiano ved bordet tar plassen dens.'}},
    {title:{en:'With a piece of pork', no:'Med et stykke svinekjøtt'},
     body:{en:'A strip of prosciutto rind or a little pancetta, put in with the soffritto, gives the water something to become a broth on. It was the standard way of getting flavour into a pot with no meat to speak of in it.',
           no:'En stripe prosciuttosvor eller litt pancetta som legges i sammen med soffritton, gir vannet noe å bli kraft av. Det var den vanlige måten å få smak i en gryte som knapt inneholdt kjøtt.'}},
    {title:{en:'The day after', no:'Dagen etter'},
     body:{en:'Cold, it sets solid. Cut it into squares, fry them in a little oil until the outsides crisp and eat them with your fingers; Naples wastes nothing, and this is better than it has any right to be.',
           no:'Kald stivner den helt. Skjær den i firkanter, stek dem i litt olje til de blir sprø utenpå, og spis dem med fingrene. Napoli kaster ingenting, og dette er bedre enn det har noen rett til å være.'}},
  ],
},

{
  id:'spaghetti-alle-vongole', dish:'Spaghetti alle vongole', course:'primo', lesson:3, serves:4, time:{prep:20, cook:15},
  hero:'vongole', tags:['pasta','seafood','clams'],
  title:{en:'Spaghetti alle vongole', no:'Spaghetti alle vongole'},
  blurb:{en:'Clams, garlic, oil, parsley and pasta water, and never any cheese. Fifteen minutes once the sand is out.',
         no:'Vongole, hvitløk, olje, persille og pastavann, og aldri ost. Femten minutter når sanden er ute.'},
  heroCaption:{en:'Spaghetti alle vongole: the clams come out of the pan while the pasta finishes, and go back at the end.',
               no:'Spaghetti alle vongole: skjellene tas ut av pannen mens pastaen blir ferdig, og går tilbake til slutt.'},
  wines:['Falanghina'],
  headnote:{
    en:'<p>The small clams of the bay of Naples, garlic, oil and parsley, and a pasta the city industrialised: the dish is four ingredients and a technique, and there is not much more to it. <strong>Gragnano</strong>, on a windy slope above the coast, had the right climate for drying pasta and eighty workshops by 1800, and its bronze-drawn spaghetti is what this is made with — the rough surface holds a thin sauce that a smooth one lets run off.</p>'
      + '<p>The sauce is an emulsion, like every good Neapolitan and Roman pasta. Olive oil, the juice the clams give up and starchy pasta water are shaken together in the pan until they turn cloudy and cling. Nothing is added to thicken them, and cheese never goes near the dish; it would flatten the shellfish and every cook in the city would tell you so.</p>'
      + '<p>Two things go wrong, and both are avoidable. Sand, which is dealt with by purging the clams in salted water and then straining their juice through cloth, and rubber, which is what a clam becomes after three minutes in a hot pan. Take each one out as it opens and put them all back at the very end, off the heat.</p>',
    no:'<p>De små skjellene fra bukten ved Napoli, hvitløk, olje og persille, og en pasta byen industrialiserte: retten er fire råvarer og en teknikk, og stort mer er den ikke. <strong>Gragnano</strong>, i en vindfull skråning over kysten, hadde det rette klimaet for å tørke pasta og hadde åtti verksteder rundt år 1800, og det er den bronsetrukne spaghettien derfra retten lages med. Den ru overflaten holder på en tynn saus som renner av en glatt.</p>'
      + '<p>Sausen er en emulsjon, slik alle gode napolitanske og romerske pastaretter er. Olivenolje, kraften skjellene gir fra seg, og stivelsesrikt pastavann ristes sammen i pannen til de blir uklare og henger. Ingenting tilsettes for å tykne dem, og ost kommer aldri i nærheten av retten. Den ville flatet ut skjellsmaken, og enhver kokk i byen ville sagt det samme.</p>'
      + '<p>To ting kan gå galt, og begge lar seg unngå. Sand, som du blir kvitt ved å la skjellene stå i saltvann og deretter sile kraften gjennom klede, og gummi, som er det et skjell blir etter tre minutter i en varm panne. Ta hvert skjell ut etter hvert som det åpner seg, og ha dem alle tilbake helt til slutt, med pannen av platen.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:400, u:'g', n:{en:'spaghetti', no:'spaghetti'}, note:{en:'bronze-drawn, from Gragnano if you can', no:'bronsetrukket, gjerne fra Gragnano'}},
    {q:1000, u:'g', n:{en:'vongole veraci', no:'vongole veraci'}, note:{en:'live, in the shell; discard any that will not close when tapped', no:'levende, i skallet; kast dem som ikke lukker seg når du banker på dem'}},
    {q:60, u:'ml', n:{en:'extra virgin olive oil', no:'ekstra virgin olivenolje'}},
    {q:2, u:'', n:{en:'garlic cloves', no:'hvitløksfedd'}, note:{en:'lightly crushed, left whole', no:'lett knust og lagt i hele'}, round:'half'},
    {q:1, u:'', n:{en:'small dried chilli', no:'liten tørket chili'}, round:'half'},
    {q:20, u:'g', n:{en:'flat-leaf parsley', no:'bladpersille'}, note:{en:'chopped at the last moment', no:'hakket i siste liten'}},
    {q:60, u:'ml', n:{en:'dry white wine', no:'tørr hvitvin'}, note:{en:'optional; many Neapolitan cooks leave it out', no:'valgfritt; mange napolitanske kokker sløyfer den'}},
    {q:4, u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:12, u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, note:{en:'less than usual: the clams bring salt of their own', no:'mindre enn vanlig, for skjellene har med seg salt selv'}, scale:'sub'},
    {u:'', n:{en:'salt for purging the clams', no:'salt til utvanning av skjellene'}, note:{en:'enough to make the water taste of the sea', no:'nok til at vannet smaker av sjø'}, scale:'none'},
  ]}],
  steps:[
    {en:'Set the clams in a colander standing inside a bowl of cold water salted like the sea, and leave them for two hours. The colander keeps them out of the sand they spit.',
     no:'Sett skjellene i et dørslag som står i en bolle med kaldt vann saltet som sjøvann, og la dem stå i to timer. Dørslaget holder dem unna sanden de spytter ut.'},
    {en:'Throw away any clam that stays open when you tap it and any with a broken shell.',
     no:'Kast de skjellene som blir liggende åpne når du banker på dem, og de som har knust skall.'},
    {en:'Warm the oil in a wide pan with the garlic and the chilli until the garlic just turns pale gold. Browned garlic is bitter and there is nothing here to cover it.',
     no:'Varm oljen i en vid panne med hvitløken og chilien til hvitløken så vidt blir lysegyllen. Brunet hvitløk er bitter, og her finnes ingenting som dekker over den.'},
    {en:'Tip in the clams, raise the heat, add the wine if you are using it and put the lid on.',
     no:'Ha i skjellene, skru opp varmen, tilsett vinen hvis du bruker den, og legg på lokket.'},
    {en:'Lift the lid after two minutes and take out each clam as it opens, into a bowl. Any still shut after five minutes goes in the bin.',
     no:'Løft lokket etter to minutter, og ta ut hvert skjell etter hvert som det åpner seg, over i en bolle. De som fortsatt er lukket etter fem minutter, går i søpla.'},
    {en:'Pour the liquid left in the pan through a fine sieve lined with a cloth, and wipe the pan out. Whatever sand there is has settled in the bottom of that liquid.',
     no:'Hell væsken som er igjen i pannen, gjennom en fin sil med et kjøkkenhåndkle i, og tørk ut pannen. Den sanden som måtte være der, har lagt seg i bunnen av væsken.'},
    {en:'Fish out the garlic and the chilli, return the strained juice to the pan and let it bubble down for a minute.',
     no:'Fisk ut hvitløken og chilien, hell den silte kraften tilbake i pannen, og la den koke inn et minutt.'},
    {en:'Boil the spaghetti in lightly salted water and drain it two minutes before it is done, keeping some of the water.',
     no:'Kok spaghettien i lett saltet vann, og hell av vannet to minutter før den er ferdig. Ta vare på noe av kokevannet.'},
    {en:'Finish the pasta in the pan with a ladle of the cooking water over lively heat, tossing hard for two minutes until the liquid turns cloudy and coats every strand.',
     no:'La pastaen bli ferdig i pannen med en øse kokevann på god varme, mens du vender kraftig i to minutter til væsken blir uklar og legger seg rundt hver tråd.'},
    {en:'Take the pan off the heat, return the clams with any juice in the bowl, shower with parsley and toss once. Serve at once, and put no cheese on the table.',
     no:'Ta pannen av platen, ha skjellene tilbake sammen med kraften i bollen, strø over persille, og vend én gang. Server med en gang, og sett ikke ost på bordet.'},
  ],
  notes:[
    {title:{en:'The clams leave and come back', no:'Skjellene ut og inn igjen'},
     body:{en:'A clam is cooked the second it opens and turns to rubber a minute later. Taking each one out as it goes and returning them all off the heat is the same logic as lifting the guanciale out of an amatriciana: the flavour is already in the pan, and the thing itself only has to be warm at the end.',
           no:'Et skjell er ferdig i det øyeblikket det åpner seg, og et minutt senere er det gummi. Tar du ut hvert enkelt skjell etter hvert og har dem alle tilbake med pannen av platen, følger du samme logikk som når guancialen løftes ut av en amatriciana: smaken ligger allerede i pannen, og selve skjellet trenger bare å være varmt til slutt.'}},
    {title:{en:'Oil, juice and starch', no:'Olje, kraft og stivelse'},
     body:{en:'Olive oil and clam juice will not mix on their own; starchy pasta water holds them together, and the hard tossing is what forces the emulsion. When the liquid goes from clear to cloudy the sauce has formed, and that moment is the only thing to watch for.',
           no:'Olivenolje og skjellkraft blander seg ikke av seg selv. Stivelsesrikt pastavann holder dem sammen, og det er den kraftige vendingen som tvinger fram emulsjonen. Når væsken går fra klar til uklar, er sausen ferdig, og det øyeblikket er det eneste du trenger å følge med på.'}},
    {title:{en:'Salt the water lightly', no:'Salt vannet lett'},
     body:{en:'The clams and their juice are seawater, and they season the finished dish on their own. Pasta water salted at the usual rate pushes the whole thing over, and there is no cheese or cream here to absorb the mistake.',
           no:'Skjellene og kraften deres er sjøvann, og de krydrer den ferdige retten alene. Pastavann saltet som vanlig skyver hele retten over kanten, og her finnes verken ost eller fløte som kan ta opp i seg feilen.'}},
  ],
  variations:[
    {title:{en:'In rosso', no:'In rosso'},
     body:{en:'A dozen cherry tomatoes, halved and softened in the oil before the clams go in, make the red version. Naples eats both and argues about neither; the white one tastes more of the sea.',
           no:'Et dusin cherrytomater som deles i to og mykner i oljen før skjellene går i, gir den røde utgaven. Napoli spiser begge og krangler om ingen av dem, men den hvite smaker mest av hav.'}},
    {title:{en:'Lupini or veraci', no:'Lupini eller veraci'},
     body:{en:'Vongole veraci are the ridged clams with the two little siphons and the most meat. The smaller lupini of the bay give less to chew and more flavour to the juice, and many Neapolitans prefer them for exactly that reason.',
           no:'Vongole veraci er de ribbede skjellene med de to små rørene og mest kjøtt. De mindre lupini fra bukten gir mindre å tygge på og mer smak til kraften, og mange napolitanere foretrekker dem nettopp derfor.'}},
    {title:{en:'Shelled or in the shell', no:'Med eller uten skall'},
     body:{en:'Restaurants sometimes shell most of the clams and keep a few in the shell for the look of it, which makes the dish easier to eat. Naples serves them all in the shell and hands out an extra plate for the empties.',
           no:'Restauranter tar iblant skallet av de fleste skjellene og lar noen ligge igjen med skall for utseendets skyld, og det gjør retten lettere å spise. I Napoli serveres alle med skall, og det settes fram en ekstra tallerken til de tomme.'}},
  ],
},

{
  id:'sfogliatella-frolla', dish:'Sfogliatella', course:'dolce', lesson:3, serves:12, time:{prep:40, cook:35},
  hero:'sfogliatellafrolla', tags:['pastry','ricotta','dolce'],
  title:{en:'Sfogliatella frolla', no:'Sfogliatella frolla'},
  blurb:{en:'The semolina and ricotta filling of the famous ribbed pastry, in a shortcrust a home kitchen can actually make.',
         no:'Fyllet av semule og ricotta fra det berømte ribbede bakverket, i en mørdeig et hjemmekjøkken faktisk klarer.'},
  heroCaption:{en:'Sfogliatella frolla, cut open: semolina, ricotta and candied peel in a lard shortcrust.',
               no:'Sfogliatella frolla, delt: semule, ricotta og kandisert skall i en mørdeig med svinefett.'},
  wines:[],
  headnote:{
    en:'<p>Neapolitan pastry comes in two versions of the same idea. The <em>riccia</em> is the famous one, a ribbed shell of hundreds of crisp leaves, made by rolling a sheet of dough until you can read a newspaper through it, winding it into a log, cutting the log into discs and pushing each disc out into a cone — days of work and a machine. The <em>frolla</em> holds exactly the same filling in shortcrust, and it is what a home kitchen makes.</p>'
      + '<p>The filling is the point of both, and it is not simply sweetened ricotta. Semolina is cooked in water into a stiff porridge first, and that porridge gives the ricotta a body that holds its shape in the oven and stops it weeping into the pastry. Candied orange peel, cinnamon and vanilla are what turn it from a curd into a Neapolitan one.</p>'
      + '<p>Two habits make the difference. Let the filling rest in the fridge before you use it, because the semolina goes on absorbing and firming for an hour. And use lard rather than butter in the pastry if you can: <em>strutto</em> is the traditional shortening, it makes a sandier, less puffy crust, and it does not compete with the ricotta.</p>',
    no:'<p>Napolitansk bakverk finnes i to utgaver av samme idé. <em>Riccia</em> er den berømte, et ribbet skall av hundrevis av sprø lag, laget ved å kjevle en deigplate så tynn at du kan lese en avis gjennom den, kveile den til en pølse, skjære pølsen i skiver og presse hver skive ut til en kjegle. Det tar dager og krever maskin. <em>Frolla</em> har nøyaktig det samme fyllet i mørdeig, og det er den et hjemmekjøkken lager.</p>'
      + '<p>Fyllet er poenget i begge, og det er ikke bare søtet ricotta. Semulen kokes først i vann til en fast grøt, og grøten gir ricottaen en fasthet som holder formen i ovnen og hindrer at den trekker ut i deigen. Kandisert appelsinskall, kanel og vanilje er det som gjør den fra en ostemasse til en napolitansk en.</p>'
      + '<p>To vaner avgjør resultatet. La fyllet hvile i kjøleskapet før du bruker det, for semulen fortsetter å trekke til seg væske og stivne i en times tid. Og bruk svinefett framfor smør i deigen hvis du får tak i det: <em>strutto</em> er det tradisjonelle fettet, det gir en mer sandaktig og mindre luftig deig, og det konkurrerer ikke med ricottaen.</p>'},
  ingredients:[{ group:{en:'For the filling', no:'Til fyllet'}, items:[
    {q:250, u:'ml', n:{en:'water', no:'vann'}},
    {q:90, u:'g', n:{en:'fine semolina', no:'fin semule'}, note:{en:'semola di grano duro, the fine grind', no:'semola di grano duro, den fint malte'}},
    {q:250, u:'g', n:{en:'ricotta', no:'ricotta'}, note:{en:'drained overnight in a sieve if it is wet', no:'avrent i en sil natten over hvis den er våt'}},
    {q:100, u:'g', n:{en:'sugar', no:'sukker'}},
    {q:1, u:'', n:{en:'egg', no:'egg'}, round:'half'},
    {q:60, u:'g', n:{en:'candied orange peel', no:'kandisert appelsinskall'}, note:{en:'chopped small', no:'finhakket'}},
    {q:2, u:'g', n:{en:'ground cinnamon', no:'malt kanel'}},
    {q:1, u:'', n:{en:'vanilla pod', no:'vaniljestang'}, note:{en:'the seeds only', no:'bare frøene'}, round:'half'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
  ]}, { group:{en:'For the pastry', no:'Til deigen'}, items:[
    {q:300, u:'g', n:{en:'plain flour', no:'hvetemel'}},
    {q:110, u:'g', n:{en:'lard', no:'svinefett'}, note:{en:'strutto, soft but not melted; butter works and gives a puffier crust', no:'strutto, mykt men ikke smeltet; smør fungerer og gir en luftigere deig'}},
    {q:100, u:'g', n:{en:'sugar', no:'sukker'}},
    {q:1, u:'', n:{en:'egg', no:'egg'}, round:'half'},
    {q:30, u:'ml', n:{en:'cold water', no:'kaldt vann'}, note:{en:'only if the dough will not come together', no:'bare hvis deigen ikke vil samle seg'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {u:'', n:{en:'icing sugar to finish', no:'melis til slutt'}, scale:'none'},
  ]}],
  steps:[
    {en:'Bring the water to the boil with a pinch of salt, then rain the semolina in with one hand while you whisk with the other.',
     no:'Kok opp vannet med en klype salt, og dryss semulen ned i en tynn stråle med den ene hånden mens du visper med den andre.'},
    {en:'Cook it for three or four minutes, stirring, until it comes away from the sides of the pan in one mass, then spread it on a plate to cool.',
     no:'Kok den i tre–fire minutter under omrøring, til den slipper kantene på kjelen i én masse, og bre den så utover på et fat for å kjølne.'},
    {en:'Push the ricotta through a sieve with the sugar and work it to a smooth cream.',
     no:'Press ricottaen gjennom en sil sammen med sukkeret, og arbeid den til en jevn masse.'},
    {en:'Beat in the egg, then the cooled semolina, then the candied peel, the cinnamon and the vanilla seeds. Cover it and leave it in the fridge for an hour.',
     no:'Visp inn egget, deretter den avkjølte semulen, og til slutt det kandiserte skallet, kanelen og vaniljefrøene. Dekk til, og sett fyllet kaldt i en time.'},
    {en:'Rub the lard into the flour, sugar and salt with your fingertips until the mixture looks like coarse sand.',
     no:'Smuldre svinefettet inn i melet, sukkeret og saltet med fingertuppene til blandingen ser ut som grov sand.'},
    {en:'Add the egg and bring the dough together in as few movements as you can, with a little cold water only if it stays crumbly. Kneading it makes it tough.',
     no:'Ha i egget, og samle deigen med så få bevegelser som mulig. Bruk litt kaldt vann bare hvis den ikke vil henge sammen. Elter du den, blir den seig.'},
    {en:'Wrap it and rest it in the fridge for half an hour. Heat the oven to 180 °C.',
     no:'Pakk den inn, og la den hvile i kjøleskapet i en halvtime. Varm ovnen til 180 °C.'},
    {en:'Roll the pastry out three millimetres thick and cut discs of about nine centimetres.',
     no:'Kjevle ut deigen tre millimeter tykk, og stikk ut sirkler på rundt ni centimeter.'},
    {en:'Put a mound of filling in the middle of each disc, fold the pastry over it into a half-moon and press the edges shut, then round the parcel in your palms into a dome.',
     no:'Legg en haug med fyll midt på hver sirkel, brett deigen over til en halvmåne, klem kantene igjen, og form pakken rund i håndflatene til en kuppel.'},
    {en:'Set them on a lined tray with room between them and bake for thirty to thirty-five minutes, until deep gold.',
     no:'Sett dem på et brett med bakepapir og god avstand, og stek dem i tretti til trettifem minutter til de er dypt gylne.'},
    {en:'Cool them for ten minutes, dust with icing sugar and eat them the same day, while the pastry is still short and the filling still warm.',
     no:'La dem kjølne i ti minutter, sikt melis over, og spis dem samme dag, mens deigen fortsatt er mør og fyllet fortsatt varmt.'},
  ],
  notes:[
    {title:{en:'The semolina is the structure', no:'Semulen er strukturen'},
     body:{en:'Ricotta on its own is loose and full of water, and it would soak the pastry from the inside and slump in the oven. Cooked semolina traps that water in a starch gel, so the filling keeps its shape and stays creamy rather than grainy. It is the same trick as the flour in a crème pâtissière.',
           no:'Ricotta alene er løs og vannholdig, og den ville bløtt opp deigen innenfra og sunket sammen i ovnen. Kokt semule binder vannet i en stivelsesgelé, så fyllet holder formen og blir kremet i stedet for kornete. Det er det samme grepet som melet i en crème pâtissière.'}},
    {title:{en:'Why the filling rests', no:'Hvorfor fyllet må hvile'},
     body:{en:'Semolina goes on drinking for an hour after it comes off the heat. Used straight away the filling is slack and runs out at the seam; an hour in the fridge and it holds a shape on the spoon, which is also when it is easiest to close the pastry around it.',
           no:'Semule fortsetter å trekke til seg væske en time etter at kjelen er tatt av platen. Brukes fyllet med en gang, er det løst og renner ut i skjøten. Etter en time i kjøleskapet holder det formen på skjeen, og det er også da det er lettest å lukke deigen rundt det.'}},
    {title:{en:'Short means barely handled', no:'Mør betyr knapt håndtert'},
     body:{en:'Fat rubbed into flour coats the grains and keeps water from building gluten, which is what makes shortcrust crumble. Every extra minute of kneading develops the gluten anyway and gives you a biscuit that bends instead of breaking, so bring the dough together and stop.',
           no:'Fett som smuldres inn i mel, legger seg rundt melkornene og hindrer vannet i å bygge gluten, og det er derfor mørdeig smuldrer. Hvert ekstra minutt med elting bygger likevel gluten og gir en kake som bøyer seg i stedet for å brekke, så samle deigen og stopp der.'}},
  ],
  variations:[
    {title:{en:'The riccia', no:'Riccia'},
     body:{en:'The same filling in the ribbed shell of hundreds of leaves. The dough is rolled until it is translucent, brushed with lard, wound into a tight log, rested overnight, sliced and coaxed out into cones by hand. It is a professional’s pastry, and buying it in Naples is not a defeat.',
           no:'Det samme fyllet i det ribbede skallet av hundrevis av lag. Deigen kjevles til den er gjennomskinnelig, pensles med svinefett, kveiles til en stram pølse, hviler natten over, skjæres i skiver og lirkes ut til kjegler for hånd. Det er et bakverk for fagfolk, og det er ikke noe nederlag å kjøpe den i Napoli.'}},
    {title:{en:'Wheat berries instead of semolina', no:'Hvetekorn i stedet for semule'},
     body:{en:'Cooked wheat berries, which Naples uses in the Easter pastiera, can replace part of the semolina and give the filling something to chew on. Orange flower water in place of the vanilla takes it further in the same direction.',
           no:'Kokte hvetekorn, som Napoli bruker i påsketerten pastiera, kan erstatte deler av semulen og gi fyllet noe å tygge på. Appelsinblomstvann i stedet for vaniljen tar det enda et skritt i samme retning.'}},
    {title:{en:'Chocolate, and other heresies', no:'Sjokolade og andre kjetterier'},
     body:{en:'Neapolitan bakers now sell them filled with pistachio cream, chocolate or lemon. Purists object, and the objection is worth taking seriously only if the semolina is still doing its job underneath.',
           no:'Napolitanske bakere selger dem nå med fyll av pistasjkrem, sjokolade eller sitron. Puristene protesterer, og protesten er verdt å ta på alvor bare dersom semulen fortsatt gjør jobben sin under fyllet.'}},
  ],
},

];
