// emiliaromagna recipes. Contract: docs/recipe-format.md. Both languages in one file; never narrated.
// Everything here follows the region's own readings: the sfoglia of lesson 4 (flour and eggs only, one egg
// to 100 g of flour, rolled with a mattarello, tagliatelle cut to the registered 8 mm), the ragù that is a
// slow braise with milk rather than a tomato sauce, the capon broth of the tortellino, the piadina and
// squacquerone of Romagna in lesson 2, and the gnocco fritto of lesson 1.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-45'] = [

{
  id:'tagliatelle-al-ragu', dish:'Tagliatelle al ragù', course:'primo', lesson:4, serves:4,
  time:{prep:45, cook:210}, hero:'tagliatelle', tags:['pasta','egg','beef'],
  title:{en:'Tagliatelle al ragù', no:'Tagliatelle al ragù'},
  blurb:{en:'Bologna’s own dish: hand-rolled ribbons eight millimetres wide, and a meat sauce that has cooked for three hours. Milk does the work, not tomato.',
         no:'Bolognas egen rett: håndkjevlede bånd på åtte millimeter og en kjøttsaus som har kokt i tre timer. Melken gjør jobben, ikke tomaten.'},
  heroCaption:{en:'Tagliatelle al ragù in a Bologna trattoria. The sauce clings to the rough ribbon in a way it never would to spaghetti.',
               no:'Tagliatelle al ragù i en trattoria i Bologna. Sausen henger på det ru båndet slik den aldri ville gjort på spaghetti.'},
  wines:['Sangiovese di Romagna','Lambrusco Grasparossa'],
  headnote:{
    en:'<p>The dish the rest of the world calls spaghetti bolognese does not exist in Bologna. The city serves its ragù on tagliatelle, and the Chamber of Commerce has held the official recipe for the <strong>tagliatella</strong> since 1972: a cooked width fixed at 8 mm, said to be the 12,270th part of the height of the Asinelli tower. The recipe for <strong>ragù alla bolognese</strong> was deposited in the same place in 1982.</p>'
      + '<p>A ragù is a slow braise, not a tomato sauce. A little tomato brings acidity and colour, but what tenderises the meat is three hours below a simmer, and what rounds it off is the milk added towards the end. That is why a real ragù is brick-brown rather than red, and why it tastes sweet rather than sharp.</p>'
      + '<p>Everything starts with the sfoglia. Flour is heaped on a board, eggs are broken into a well in the middle, and the dough is rolled out with a metre-long <em>mattarello</em> until you can see the board through it. The ratio is one egg to every 100 g of flour, and it is not open to negotiation.</p>',
    no:'<p>Retten som resten av verden kaller spaghetti bolognese, finnes ikke i Bologna. Byen serverer ragùen sin på tagliatelle, og handelskammeret har hatt den offisielle oppskriften på <strong>tagliatella</strong> siden 1972: kokt bredde fastsatt til 8 mm, angivelig en 12 270-del av høyden på Asinelli-tårnet. Oppskriften på <strong>ragù alla bolognese</strong> ble deponert samme sted i 1982.</p>'
      + '<p>En ragù er en langsom braisering og ingen tomatsaus. Litt tomat gir syre og farge, men tre timer under kokepunktet gjør kjøttet mørt, og melken som spes i mot slutten, runder det av. Derfor er en ekte ragù teglbrun og ikke rød, og derfor smaker den søtt og ikke skarpt.</p>'
      + '<p>Alt begynner med sfogliaen. Mel legges i en haug på et brett, egg knuses i en fordypning i midten, og deigen kjevles ut med en meterlang <em>mattarello</em> til du ser brettet gjennom den. Forholdet er ett egg per 100 g mel, og det er ikke til forhandling.</p>'},
  ingredients:[
    { group:{en:'For the ragù', no:'Til ragùen'}, items:[
      {q:300, u:'g', n:{en:'beef', no:'oksekjøtt'}, note:{en:'skirt or chuck, minced once and coarsely, or chopped by hand', no:'bibringe eller høyrygg, grovmalt én gang, eller finhakket for hånd'}},
      {q:150, u:'g', n:{en:'pancetta', no:'pancetta'}, note:{en:'bought in one piece and chopped fine', no:'kjøpt i ett stykke og finhakket'}},
      {q:60,  u:'g', n:{en:'onion', no:'løk'}},
      {q:60,  u:'g', n:{en:'carrot', no:'gulrot'}},
      {q:60,  u:'g', n:{en:'celery', no:'stilkselleri'}},
      {q:300, u:'g', n:{en:'tomato passata', no:'tomatpassata'}, note:{en:'or peeled plum tomatoes crushed by hand; here the tomato is a seasoning, not the body of the sauce', no:'eller hermetiske plommetomater most for hånd; her er tomaten et krydder og ikke selve sausen'}},
      {q:100, u:'ml', n:{en:'dry white wine', no:'tørr hvitvin'}},
      {q:250, u:'ml', n:{en:'whole milk', no:'helmelk'}, note:{en:'added a little at a time over the last hour', no:'spes i litt om gangen den siste timen'}},
      {q:250, u:'ml', n:{en:'meat broth', no:'kjøttkraft'}, note:{en:'water will do; it is only there to keep the pot from drying out', no:'vann gjør nytten; det er bare til for å hindre at gryten tørker inn'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
      {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
    ]},
    { group:{en:'For the sfoglia', no:'Til sfogliaen'}, items:[
      {q:400, u:'g', n:{en:'‘00’ flour', no:'mel type 00'}, note:{en:'plain wheat flour works; a dusting of semolina makes the sheet easier to handle', no:'vanlig hvetemel gjør nytten, og litt semulegryn gjør platen lettere å håndtere'}},
      {q:4,   u:'', n:{en:'eggs', no:'egg'}, round:'half', note:{en:'one egg to every 100 g of flour, as Bologna has it', no:'ett egg per 100 g mel, slik Bologna vil ha det'}},
      {q:4,   u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:20,  u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
    ]},
    { group:{en:'To serve', no:'Til servering'}, items:[
      {q:60,  u:'g', n:{en:'Parmigiano Reggiano', no:'Parmigiano Reggiano'}, note:{en:'finely grated', no:'finrevet'}},
    ]},
  ],
  steps:[
    {en:'Chop the onion, carrot, celery and pancetta as fine as you can. A soffritto cut coarse never disappears into the sauce.',
     no:'Hakk løk, gulrot, selleri og pancetta så fint du klarer. Et grovhakket soffritto forsvinner aldri inn i sausen.'},
    {en:'Melt the pancetta in a heavy pot over low heat, until the fat runs and the pieces turn pale gold.',
     no:'Smelt pancettaen i en tykkbunnet gryte på svak varme, til fettet renner og bitene blir lyst gylne.'},
    {en:'Add the soffritto and let it soften for about 10 minutes, until it is sweet and yielding but has taken no colour.',
     no:'Ha i soffritten og la den mykne i omtrent 10 minutter, til den er søt og bløt uten å ha tatt farge.'},
    {en:'Add the beef, break it up with a spoon and stir until it has just lost its raw colour. Do not brown it hard; this is a braise and not a fry.',
     no:'Tilsett oksekjøttet, del det opp med en sleiv og rør til det akkurat har mistet den rå fargen. Ikke brun det hardt, for dette er en braisering og ingen steking.'},
    {en:'Pour in the wine and let it evaporate completely.',
     no:'Hell i vinen og la den fordampe helt.'},
    {en:'Stir in the passata, season with salt and pepper, and bring the pot down to the barest tremble.',
     no:'Rør inn passataen, smak til med salt og pepper, og la gryten så vidt skjelve.'},
    {en:'Cook uncovered for three hours, stirring now and then and adding broth by the ladleful whenever the surface dries out.',
     no:'La den koke uten lokk i tre timer. Rør av og til, og spe med kraft en øse om gangen hver gang overflaten tørker inn.'},
    {en:'Pour in the milk over the last hour, a little at a time, letting each addition disappear before the next. The sauce should end up thick, brick-brown and glossy, with the fat sitting on top.',
     no:'Spe med melken den siste timen, litt om gangen, og la hver skvett forsvinne før den neste. Sausen skal ende opp tykk, teglbrun og blank, med fettet liggende øverst.'},
    {en:'Meanwhile heap the flour on a board, break the eggs into a well in the middle and work them in. Knead for 10 minutes until the dough is smooth and springs back, then wrap it and rest it for half an hour.',
     no:'Legg imens melet i en haug på et brett, knus eggene i en fordypning i midten og arbeid dem inn. Elt i 10 minutter til deigen er glatt og spretter tilbake, pakk den inn og la den hvile en halvtime.'},
    {en:'Roll the dough out with a long pin, turning and stretching, until you can see the board through it. Let the sheet dry for a quarter of an hour, roll it up loosely and cut ribbons 8 mm wide.',
     no:'Kjevle deigen ut med en lang kjevle mens du snur og strekker, til du ser brettet gjennom den. La platen tørke et kvarter, rull den løst sammen og skjær bånd på 8 mm.'},
    {en:'Boil the tagliatelle in well-salted water for two or three minutes, until they float and are tender, then drain them and toss them with the ragù in a warm bowl. Serve with the Parmigiano.',
     no:'Kok pastaen i godt saltet vann i to–tre minutter, til båndene flyter opp og er møre. Hell av vannet og vend dem sammen med ragùen i en varm bolle. Server med Parmigiano.'},
  ],
  notes:[
    {title:{en:'One egg to a hundred grams', no:'Ett egg per hundre gram'},
     body:{en:'An egg is about three-quarters water, so the Bolognese ratio gives a dough far drier and stiffer than bread dough; it should feel almost too dry when you begin. Ten minutes of kneading works that water evenly through the flour and builds the gluten that lets the sheet stretch to translucence without tearing. The half-hour rest then lets the gluten relax so the pin can do its work.',
           no:'Et egg er omtrent tre firedeler vann, så det bolognesiske forholdet gir en deig som er langt tørrere og stivere enn brøddeig. Den skal føles nesten for tørr når du begynner. Ti minutters elting fordeler vannet jevnt i melet og bygger glutenet som lar platen strekke seg gjennomskinnelig uten å revne, og halvtimen med hvile lar glutenet slappe av så kjevlen får gjort jobben sin.'}},
    {title:{en:'Milk, not more tomato', no:'Melk, ikke mer tomat'},
     body:{en:'Ragù alla bolognese is a braise. The tomato is there for acidity and colour and is measured in small amounts. Three hours below a simmer make the meat tender, and the milk rounds it off: its sugars brown slowly and its proteins soften the meat fibres. That is why the finished sauce is brick-brown rather than red, and why doubling the tomato gives you a different dish rather than a stronger one.',
           no:'Ragù alla bolognese er en braisering. Tomaten er der for syre og farge og måles i små mengder. Tre timer under kokepunktet gjør kjøttet mørt, og melken runder det av: melkesukkeret bruner langsomt, og proteinene mykner kjøttfibrene. Derfor er den ferdige sausen teglbrun og ikke rød, og derfor gir dobbel mengde tomat en annen rett og ikke en kraftigere.'}},
    {title:{en:'Why not spaghetti', no:'Hvorfor ikke spaghetti'},
     body:{en:'A meat sauce needs a surface to hold on to. Hand-rolled egg pasta is porous and slightly rough, and an eight-millimetre ribbon gives it a wide flat face to cling to. Round, smooth, dried durum spaghetti sheds it to the bottom of the plate, which is why Bologna does not serve the dish that half the world has named after the city.',
           no:'En kjøttsaus trenger en overflate å henge fast i. Håndkjevlet eggpasta er porøs og litt ru, og et bånd på åtte millimeter gir en bred, flat flate å klamre seg til. Rund, glatt spaghetti av tørket durumhvete slipper den ned i bunnen av tallerkenen, og det er derfor Bologna ikke serverer retten som halve verden har oppkalt etter byen.'}},
  ],
  variations:[
    {title:{en:'Tagliatelle from a packet', no:'Tagliatelle fra pakken'},
     body:{en:'Good dried egg tagliatelle from Emilia is an honest substitute on a weekday, and it cooks in five or six minutes instead of two. The sauce notices, but not much. What you cannot substitute is the three hours.',
           no:'God tørket eggtagliatelle fra Emilia er et hederlig alternativ på en hverdag, og den koker på fem–seks minutter i stedet for to. Sausen merker forskjellen, men ikke mye. De tre timene lar seg derimot ikke erstatte.'}},
    {title:{en:'Chicken livers, or a little pork', no:'Kyllinglever, eller litt svinekjøtt'},
     body:{en:'Older Bolognese ragù often had chicken livers in it, chopped fine and added near the end, and many families use half beef and half pork. Both make the sauce rounder and neither is thought a heresy in the city.',
           no:'Eldre bolognesiske ragùer hadde ofte kyllinglever i, finhakket og tilsatt mot slutten, og mange familier bruker halvt oksekjøtt og halvt svinekjøtt. Begge deler gjør sausen fyldigere, og ingen av dem regnes som kjetteri i byen.'}},
    {title:{en:'What is left over', no:'Det som blir til overs'},
     body:{en:'The ragù is better the next day and freezes without complaint. Make double and the lasagne verdi is already half done.',
           no:'Ragùen er bedre dagen etter og tåler frysing uten videre. Lager du dobbel porsjon, er lasagne verdi allerede halvveis ferdig.'}},
  ],
},

{
  id:'tortellini-in-brodo', dish:'Tortellini in brodo', course:'primo', lesson:4, serves:4,
  time:{prep:120, cook:210}, hero:'tortellini', tags:['pasta','egg','pork','broth'],
  title:{en:'Tortellini in brodo', no:'Tortellini in brodo'},
  blurb:{en:'The Christmas dish of Bologna: thumbnail parcels of pork folded around a fingertip, in a clear capon broth and nothing else.',
         no:'Julematen i Bologna: bittesmå pakker med svinefyll brettet rundt en fingertupp, i klar kapunkraft og ingenting annet.'},
  heroCaption:{en:'Tortellini in brodo. The broth is the whole sauce, so it can hide nothing.',
               no:'Tortellini in brodo. Kraften er hele sausen, så den kan ikke skjule noe.'},
  wines:['Lambrusco di Sorbara'],
  headnote:{
    en:'<p>The tortellino has a legend, contested between Bologna and Modena. An innkeeper at Castelfranco Emilia, midway between the two, peeps through a keyhole at Venus asleep and, overcome, rushes to the kitchen to reproduce her navel in pasta. The two cities also disagree about the filling and the size, and the recipe deposited at the Bologna Chamber of Commerce in 1974 was an attempt to settle it.</p>'
      + '<p>That filling is pork loin browned in butter, prosciutto, mortadella and Parmigiano, minced together and bound with egg and nutmeg. It wants a night in the fridge before you use it, so the salt from three salty ingredients has time to spread and the fat has time to set.</p>'
      + '<p>The broth decides everything else. It is made from capon and beef, started in cold water, and it must never boil hard: a rolling boil beats the fat back into the liquid and the broth is cloudy for good. Nothing lies in the bowl but tortellini and broth, so both have to bear looking at.</p>',
    no:'<p>Tortellinoen har en legende, som Bologna og Modena strides om. En vertshusholder i Castelfranco Emilia, midt mellom de to byene, kikker gjennom et nøkkelhull på en sovende Venus og blir så overveldet at han løper til kjøkkenet for å gjenskape navlen hennes i pasta. De to byene er også uenige om fyllet og størrelsen, og oppskriften som ble deponert hos handelskammeret i Bologna i 1974, var et forsøk på å avgjøre saken.</p>'
      + '<p>Fyllet er svinefilet brunet i smør, prosciutto, mortadella og Parmigiano, kvernet sammen og bundet med egg og muskat. Det bør stå en natt i kjøleskapet før du bruker det, så saltet fra tre salte råvarer rekker å spre seg og fettet rekker å stivne.</p>'
      + '<p>Kraften avgjør resten. Den kokes på kapun og oksekjøtt, settes over i kaldt vann og må aldri fosskoke, for fosskok pisker fettet inn i væsken igjen og gjør kraften uklar for godt. I skålen ligger det ikke annet enn tortellini og kraft, så begge deler må tåle å bli sett på.</p>'},
  ingredients:[
    { group:{en:'For the broth', no:'Til kraften'}, items:[
      {q:800, u:'g', n:{en:'capon', no:'kapun'}, note:{en:'on the bone and with the skin; a boiling fowl, or half a chicken and half a capon, will also do', no:'på beinet og med skinnet på; en suppehøne, eller halvt kylling og halvt kapun, gjør også nytten'}},
      {q:300, u:'g', n:{en:'beef for boiling', no:'kokekjøtt av okse'}, note:{en:'shin or chuck, on the bone if you can', no:'skank eller høyrygg, helst på beinet'}},
      {q:1,   u:'', n:{en:'onion', no:'løk'}, round:'half'},
      {q:1,   u:'', n:{en:'carrot', no:'gulrot'}, round:'half'},
      {q:1,   u:'', n:{en:'stick of celery', no:'stang stilkselleri'}, round:'half'},
      {q:3,   u:'l', n:{en:'cold water', no:'kaldt vann'}, scale:'sub'},
      {u:'', n:{en:'salt', no:'salt'}, note:{en:'added towards the end, never at the start', no:'tilsettes mot slutten, aldri i begynnelsen'}, scale:'none'},
    ]},
    { group:{en:'For the filling', no:'Til fyllet'}, items:[
      {q:100, u:'g', n:{en:'pork loin', no:'svinefilet'}, note:{en:'in one piece', no:'i ett stykke'}},
      {q:20,  u:'g', n:{en:'butter', no:'smør'}},
      {q:100, u:'g', n:{en:'Prosciutto di Parma', no:'Prosciutto di Parma'}, note:{en:'in one thick slice, not shaved', no:'i én tykk skive, ikke høvlet'}},
      {q:100, u:'g', n:{en:'Mortadella Bologna', no:'Mortadella Bologna'}, note:{en:'likewise in one piece', no:'også i ett stykke'}},
      {q:150, u:'g', n:{en:'Parmigiano Reggiano', no:'Parmigiano Reggiano'}, note:{en:'finely grated, 24 months or more', no:'finrevet, 24 måneder eller mer'}},
      {q:1,   u:'', n:{en:'egg', no:'egg'}, round:'half'},
      {u:'', n:{en:'nutmeg', no:'muskatnøtt'}, note:{en:'grated fresh, a good pinch', no:'nyrevet, en god klype'}, scale:'none'},
    ]},
    { group:{en:'For the sfoglia', no:'Til sfogliaen'}, items:[
      {q:200, u:'g', n:{en:'‘00’ flour', no:'mel type 00'}},
      {q:2,   u:'', n:{en:'eggs', no:'egg'}, round:'half', note:{en:'one egg to every 100 g of flour', no:'ett egg per 100 g mel'}},
    ]},
  ],
  steps:[
    {en:'Put the capon, the beef and the vegetables in a tall pot, cover them with cold water and bring it up very slowly. A cold start draws the gelatine out of the bones; a hot one seals the meat and gives you nothing.',
     no:'Legg kapunen, oksekjøttet og grønnsakene i en høy gryte, dekk dem med kaldt vann og varm det opp svært langsomt. Kald start trekker gelatinen ut av beina, mens en varm start forsegler kjøttet og gir deg ingenting.'},
    {en:'Skim the grey foam off as it gathers. Once the surface is clear, hold the pot at the barest tremble for three hours and never let it boil.',
     no:'Fjern det grå skummet etter hvert som det samler seg. Når overflaten er klar, holder du gryten så vidt skjelvende i tre timer, og den må aldri koke.'},
    {en:'Salt the broth towards the end, strain it through a cloth and chill it, so the fat sets on top and can be lifted off.',
     no:'Salt kraften mot slutten, sil den gjennom et klede og sett den kaldt, så fettet stivner på toppen og kan løftes av.'},
    {en:'Brown the pork loin in the butter over low heat until it is cooked through, then let it cool completely.',
     no:'Brun svinefileten i smøret på svak varme til den er gjennomstekt, og la den bli helt kald.'},
    {en:'Mince the pork, the prosciutto and the mortadella together, twice, until the mixture is smooth.',
     no:'Kvern svinekjøttet, prosciuttoen og mortadellaen sammen to ganger, til blandingen er glatt.'},
    {en:'Work in the Parmigiano, the egg and a good grating of nutmeg to a firm paste that holds its shape, cover it and leave it in the fridge overnight.',
     no:'Arbeid inn Parmigianoen, egget og rikelig revet muskat til en fast masse som holder formen, dekk den til og la den stå i kjøleskapet over natten.'},
    {en:'Make the sfoglia from the flour and the eggs, knead it for 10 minutes, rest it for half an hour and roll it out until you can read through it.',
     no:'Lag sfogliaen av melet og eggene, elt i 10 minutter, la deigen hvile en halvtime og kjevle den ut til du kan lese gjennom den.'},
    {en:'Cut squares about 3 cm across, working with a quarter of the sheet at a time and keeping the rest under a cloth. A sheet that has dried will not seal.',
     no:'Skjær ruter på rundt 3 cm. Arbeid med en fjerdedel av platen om gangen og hold resten under et klede, for en plate som har tørket, lar seg ikke lukke.'},
    {en:'Put a dab of filling the size of a pea in the middle of each square, fold it into a triangle and press the edges shut, pushing the air out as you go.',
     no:'Legg en klatt fyll på størrelse med en ert midt på hver rute, brett den til en trekant og klem kantene sammen mens du presser ut luften.'},
    {en:'Wrap the long side around your fingertip, press the two points together and turn the little collar back. Lay them out on a floured cloth to dry for half an hour.',
     no:'Legg langsiden rundt fingertuppen, press de to spissene sammen og brett kraven tilbake. Legg dem utover på et melet klede og la dem tørke en halvtime.'},
    {en:'Bring the broth to a bare simmer, drop the tortellini in and cook them for three or four minutes, until they rise. Serve them in the broth, with Parmigiano at the table and nothing else in the bowl.',
     no:'Varm kraften til den så vidt skjelver, ha i tortellini og kok dem i tre–fire minutter, til de stiger opp. Server dem i kraften, med Parmigiano på bordet og ingenting annet i skålen.'},
  ],
  notes:[
    {title:{en:'The broth is the sauce', no:'Kraften er sausen'},
     body:{en:'Nothing else is in the bowl, so the broth carries the dish. A capon is a castrated cockerel, fatter and sweeter than a chicken and rich in the collagen that dissolves into gelatine and gives the broth body in the mouth. The whole method protects clarity: cold water, so the proteins leach out slowly and coagulate into a foam you can skim off, and a surface that trembles rather than boils, because agitation emulsifies the fat back in and no amount of straining will take it out again.',
           no:'Det ligger ikke annet i skålen, så kraften bærer hele retten. Kapun er kastrert hane, fetere og søtere enn kylling og rik på kollagenet som løser seg opp til gelatin og gir kraften fylde i munnen. Hele metoden er lagt opp for å bevare klarheten: kaldt vann, så proteinene siver langsomt ut og koagulerer til et skum du kan fjerne, og en overflate som skjelver i stedet for å koke, for bevegelse emulgerer fettet inn igjen, og ingen sil får det ut.'}},
    {title:{en:'Rest the filling', no:'La fyllet hvile'},
     body:{en:'The filling is salted three times over, by the prosciutto, the mortadella and the Parmigiano, and none of that salt has moved when you first mix it. A night in the fridge spreads it through the paste and lets the fat set, so the filling tastes of one thing rather than three and is firm enough to lift on the point of a knife.',
           no:'Fyllet er saltet tre ganger, av prosciuttoen, mortadellaen og Parmigianoen, og ingenting av det saltet har flyttet på seg når du nettopp har blandet det. En natt i kjøleskapet sprer saltet gjennom massen og lar fettet stivne, så fyllet smaker av én ting og ikke av tre, og er fast nok til å løftes på knivspissen.'}},
    {title:{en:'Small is the point', no:'Små er poenget'},
     body:{en:'A tortellino should disappear in one mouthful, and the ratio a Bolognese is after leaves more pasta than filling — the opposite of what a raviolo aims at. Roll the sheet thinner than feels sensible. The filling is rich enough that a thick wrapper makes the whole plate heavy.',
           no:'En tortellino skal forsvinne i én munnfull, og forholdet en bolognese er ute etter, gir mer pasta enn fyll — det motsatte av hva en raviolo vil. Kjevle platen tynnere enn det føles fornuftig. Fyllet er rikt nok til at et tykt hylster gjør hele tallerkenen tung.'}},
  ],
  variations:[
    {title:{en:'The cappelletti of Romagna', no:'Cappelletti fra Romagna'},
     body:{en:'East of Bologna the same idea is made bigger and filled with cheese rather than meat, and those little hats go into capon broth at Christmas too.',
           no:'Øst for Bologna lages det samme, bare større og med ostefyll i stedet for kjøtt. Også de små hattene går i kapunkraft til jul.'}},
    {title:{en:'Out of the bowl', no:'Utenfor skålen'},
     body:{en:'Outside Bologna tortellini are served drained, with butter and Parmigiano or with cream. In the city that counts as a waste of both the broth and the tortellino.',
           no:'Utenfor Bologna serveres tortellini avsilt, med smør og Parmigiano eller med fløte. I byen regnes det som sløsing både med kraften og med tortellinoen.'}},
    {title:{en:'Freezing them', no:'Frysing'},
     body:{en:'Freeze them in a single layer on the cloth they were folded on, then bag them. They go straight from the freezer into the broth and want a minute longer.',
           no:'Frys dem i ett lag på kledet de ble brettet på, og legg dem så i pose. De går rett fra fryseren ned i kraften og trenger ett minutt ekstra.'}},
  ],
},

{
  id:'piadina-romagnola', dish:'Piadina', course:'base', lesson:2, serves:4,
  time:{prep:45, cook:15}, hero:'piadina', tags:['bread','romagna'],
  title:{en:'Piadina romagnola', no:'Piadina romagnola'},
  blurb:{en:'The flatbread of Romagna, baked on a dry hot plate and folded around squacquerone, prosciutto and rocket. Flour to table in under an hour.',
         no:'Flatbrødet fra Romagna, stekt på tørr, varm plate og brettet rundt squacquerone, prosciutto og ruccola. Fra mel til bord på under en time.'},
  heroCaption:{en:'Piadina romagnola filled with prosciutto and cheese. It has to be soft enough to fold without cracking, and it is eaten warm.',
               no:'Piadina romagnola fylt med prosciutto og ost. Den må være myk nok til å brettes uten å sprekke, og den spises varm.'},
  wines:['Sangiovese di Romagna'],
  headnote:{
    en:'<p>Piadina is the bread of Romagna. It is cooked on a hot plate, folded around prosciutto, rocket and the soft, sour <strong>squacquerone</strong>, and eaten standing up at kiosks along the coast from Ravenna to Rimini. No oven is involved and nothing is proved.</p>'
      + '<p>The dough is flour, lard, salt and water, with a little bicarbonate of soda for a breath of air. The lard is the part that matters. Fat coats the flour and keeps the gluten strands short, so the bread stays tender and folds without cracking. Olive oil does nearly the same job and is the modern version.</p>'
      + '<p>The heat decides the rest. The traditional <em>testo</em> is a disc of earthenware or iron that holds a great deal of heat, and it goes on the fire dry — not a drop of fat in the pan. A piadina bakes; it does not fry.</p>',
    no:'<p>Piadina er brødet i Romagna. Det stekes på en varm plate, brettes rundt prosciutto, ruccola og den myke, syrlige osten <strong>squacquerone</strong>, og spises stående ved kiosker langs kysten fra Ravenna til Rimini. Ingen ovn er involvert, og ingenting heves.</p>'
      + '<p>Deigen er mel, smult, salt og vann, med litt natron som gir et pust av luft. Smultet er det viktige. Fett legger seg rundt melet og holder glutentrådene korte, så brødet blir mørt og lar seg brette uten å sprekke. Olivenolje gjør nesten samme nytten og er den moderne varianten.</p>'
      + '<p>Varmen avgjør resten. Den tradisjonelle <em>testoen</em> er en skive av leire eller jern som holder svært mye varme, og den settes på tørr — ikke en dråpe fett i pannen. En piadina bakes, den stekes ikke.</p>'},
  ingredients:[
    { group:{en:'For the dough', no:'Til deigen'}, items:[
      {q:500, u:'g', n:{en:'‘00’ flour', no:'mel type 00'}},
      {q:100, u:'g', n:{en:'lard', no:'smult'}, note:{en:'strutto, soft and at room temperature; olive oil is the modern substitute', no:'strutto, mykt og med romtemperatur; olivenolje er den moderne erstatningen'}},
      {q:5,   u:'g', n:{en:'bicarbonate of soda', no:'natron'}, note:{en:'baking powder in the same weight also works', no:'bakepulver i samme mengde gjør også nytten'}},
      {q:10,  u:'g', n:{en:'salt', no:'salt'}},
      {q:220, u:'ml', n:{en:'water', no:'vann'}, note:{en:'lukewarm; flours differ, so hold a little back', no:'lunkent; mel er ulikt, så hold igjen litt'}},
    ]},
    { group:{en:'To fill', no:'Til fyll'}, items:[
      {q:200, u:'g', n:{en:'squacquerone', no:'squacquerone'}, note:{en:'soft, fresh and sour; a young stracchino is the nearest thing abroad', no:'myk, fersk og syrlig; en ung stracchino er det nærmeste du kommer i utlandet'}},
      {q:120, u:'g', n:{en:'Prosciutto di Parma', no:'Prosciutto di Parma'}, note:{en:'sliced thin', no:'tynt skåret'}},
      {q:60,  u:'g', n:{en:'rocket', no:'ruccola'}},
    ]},
  ],
  steps:[
    {en:'Rub the lard into the flour with your fingertips, until the mixture looks like coarse crumbs and no lumps of fat are left.',
     no:'Smuldre smultet inn i melet med fingertuppene, til blandingen ser ut som grove smuler og ingen klumper av fett er igjen.'},
    {en:'Dissolve the salt and the bicarbonate in the lukewarm water.',
     no:'Løs opp saltet og natronet i det lunkne vannet.'},
    {en:'Pour the liquid into the flour a little at a time and gather it into a soft dough. Stop while it is still faintly tacky.',
     no:'Hell væsken i melet litt om gangen og samle det til en myk deig. Stopp mens den fortsatt er så vidt klebrig.'},
    {en:'Knead for 10 minutes on the board, until the dough is smooth and springs back when you press it.',
     no:'Elt i 10 minutter på brettet, til deigen er glatt og spretter tilbake når du trykker på den.'},
    {en:'Divide the dough into balls the size of a small fist, one for each piadina, cover them and rest them for half an hour.',
     no:'Del deigen i emner på størrelse med en liten knyttneve, ett til hver piadina, dekk dem til og la dem hvile en halvtime.'},
    {en:'Roll each ball out into a disc about 25 cm across and 3 mm thick, turning it a quarter turn between passes so it stays round.',
     no:'Kjevle hvert emne ut til en leiv på rundt 25 cm i tverrmål og 3 mm tykkelse, og drei den en kvart omdreining mellom hvert drag så den holder seg rund.'},
    {en:'Heat a heavy, dry pan or a flat griddle over a good medium heat. No fat goes in the pan: the piadina bakes, it does not fry.',
     no:'Varm en tykk, tørr panne eller en stekeplate på god middels varme. Det skal ikke fett i pannen, for piadinaen bakes og stekes ikke.'},
    {en:'Lay a disc on and cook it for about a minute, pricking the biggest bubbles with a fork. Turn it, cook the other side, and turn it two or three times more, until it is dry and spotted with brown.',
     no:'Legg på en leiv og stek den i omtrent ett minutt mens du stikker hull på de største boblene med en gaffel. Snu den, stek den andre siden, og snu den så to–tre ganger til, til den er tørr og flekket med brunt.'},
    {en:'Stack the piadine as they come off the heat and lay a cloth over them, so the steam keeps them soft.',
     no:'Stable piadinaene etter hvert som de er ferdige, og legg et klede over dem, så holder dampen dem myke.'},
    {en:'Spread the squacquerone over the warm bread, lay the prosciutto and the rocket on top, fold it in half and eat it standing up.',
     no:'Bre squacquerone utover det varme brødet, legg prosciutto og ruccola oppå, brett det dobbelt og spis det stående.'},
  ],
  notes:[
    {title:{en:'Lard, not oil, and no yeast', no:'Smult, ikke olje, og ingen gjær'},
     body:{en:'Fat coats the flour and keeps the gluten strands short, which is what makes the bread tender enough to fold without cracking. Lard is solid at room temperature and does that better than an oil, which is why the old recipe calls for it. Nothing is proved: the bicarbonate gives up its gas the moment it meets the heat of the pan, so a piadina goes from flour to table in under an hour. That is the whole point of a bread that was baked on the hearth for whoever came home.',
           no:'Fett legger seg rundt melet og holder glutentrådene korte, og det er derfor brødet blir mørt nok til å brettes uten å sprekke. Smult er fast ved romtemperatur og gjør den jobben bedre enn en olje, og derfor står det i den gamle oppskriften. Ingenting heves: natronet gir fra seg gassen sin i det øyeblikket det møter varmen i pannen, så en piadina går fra mel til bord på under en time. Det er hele poenget med et brød som ble stekt på grua til den som kom hjem.'}},
    {title:{en:'A dry pan, and a hot one', no:'Tørr panne, og varm'},
     body:{en:'The testo is earthenware or iron because both hold heat, and heat is what decides the result. If the pan is too cool the water leaves slowly and the bread dries into a cracker. If it is hot enough the surface sets while the inside is still steaming, and the piadina stays pliable. Turning it several times keeps either face from drying out before the other is done.',
           no:'Testoen er av leire eller jern fordi begge deler holder på varmen, og varmen avgjør resultatet. Er pannen for kald, siver vannet langsomt ut og brødet tørker til en kjeks. Er den varm nok, setter overflaten seg mens innsiden fortsatt damper, og piadinaen holder seg bøyelig. Flere vendinger hindrer at den ene siden tørker ut før den andre er ferdig.'}},
  ],
  variations:[
    {title:{en:'Thick or thin', no:'Tykk eller tynn'},
     body:{en:'Around Rimini the piadina is rolled thin and supple. Further inland and to the north it is thicker and more like bread. The dough is the same.',
           no:'Rundt Rimini kjevles piadinaen tynn og bøyelig, mens den lenger inn i landet og nordover er tykkere og mer brødaktig. Deigen er den samme.'}},
    {title:{en:'Without the lard', no:'Uten smult'},
     body:{en:'Olive oil in place of the lard gives a piadina that suits a vegetarian table. It is a little less tender and dries faster, so eat it straight from the pan.',
           no:'Olivenolje i stedet for smult gir en piadina som passer på et vegetarisk bord. Den blir litt mindre mør og tørker fortere, så den bør spises rett fra pannen.'}},
    {title:{en:'Cassone', no:'Cassone'},
     body:{en:'Fold the filling into the raw disc, seal the edge and cook it closed, and you have a cassone, also called a crescione, sold at the same kiosks. Wild greens or squash are the usual fillings, and the cheese goes in with them.',
           no:'Brett fyllet inn i den rå leiven, klem kanten igjen og stek den lukket, så har du en cassone, også kalt crescione, som selges i de samme kioskene. Villurter eller gresskar er det vanlige fyllet, og osten går i sammen med dem.'}},
  ],
},

{
  id:'lasagne-verdi-bolognese', dish:'Lasagne verdi', course:'primo', lesson:4, serves:6,
  time:{prep:75, cook:40}, hero:'lasagne', tags:['pasta','egg','beef','oven'],
  title:{en:'Lasagne verdi alla bolognese', no:'Lasagne verdi alla bolognese'},
  blurb:{en:'Green sheets of sfoglia, ragù and béchamel in six thin layers. Bologna’s Sunday dish, and what a pot of ragù naturally turns into.',
         no:'Grønne plater av sfoglia, ragù og béchamel i seks tynne lag. Bolognas søndagsrett, og det en gryte ragù naturlig blir til.'},
  heroCaption:{en:'Lasagne verdi. The spinach colours the sheet green, and the béchamel binds the layers into one slice.',
               no:'Lasagne verdi. Spinaten farger platen grønn, og béchamelen binder lagene til én skive.'},
  wines:['Sangiovese di Romagna','Lambrusco Grasparossa'],
  headnote:{
    en:'<p>The same sfoglia that becomes tagliatelle also becomes lasagne verdi. The sheet is coloured green with spinach, layered with ragù and béchamel and baked, and the result is Bologna’s Sunday food and the obvious next move when there is a pot of ragù already standing on the stove.</p>'
      + '<p>In the north the dairy is cow’s milk and butter, and the béchamel binds the layers where the south would use ricotta or mozzarella. Flour cooked in butter and let down with milk sets into a gel as it cools, and that gel is what turns a dozen loose sheets into a slice you can lift.</p>'
      + '<p>Every layer should be thin. The sheet should show through the sauce, and the dish should come out of the oven as six distinct layers rather than as a casserole. And it has to stand for a quarter of an hour before it is cut.</p>',
    no:'<p>Den samme sfogliaen som blir til tagliatelle, blir også til lasagne verdi. Platen farges grønn med spinat, legges lagvis med ragù og béchamel og stekes i ovnen. Resultatet er Bolognas søndagsmat og det opplagte neste trekket når en gryte ragù allerede står på komfyren.</p>'
      + '<p>Nord i Italia er meieriet kumelk og smør, og béchamelen binder lagene der man i sør ville brukt ricotta eller mozzarella. Mel som kokes i smør og spes med melk, stivner til en gelé når den kjølner, og den geleen gjør et dusin løse plater til en skive du kan løfte.</p>'
      + '<p>Hvert lag skal være tynt. Platen skal skinne gjennom sausen, og retten skal komme ut av ovnen som seks tydelige lag og ikke som en gryterett. Og den må stå et kvarter før den skjæres.</p>'},
  ingredients:[
    { group:{en:'For the green sfoglia', no:'Til den grønne sfogliaen'}, items:[
      {q:300, u:'g', n:{en:'‘00’ flour', no:'mel type 00'}},
      {q:2,   u:'', n:{en:'eggs', no:'egg'}, round:'half', note:{en:'one fewer than the usual ratio, because the spinach brings water of its own', no:'ett færre enn det vanlige forholdet, siden spinaten bringer med seg vann selv'}},
      {q:400, u:'g', n:{en:'spinach', no:'spinat'}, note:{en:'cooked, squeezed bone dry and chopped very fine; it comes down to about a quarter of its weight', no:'kokt, klemt helt tørr og svært finhakket; den krymper til omtrent en firedel av vekten'}},
      {q:4,   u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:20,  u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
    ]},
    { group:{en:'For the ragù', no:'Til ragùen'}, items:[
      {q:900, u:'g', n:{en:'ragù alla bolognese', no:'ragù alla bolognese'}, note:{en:'made as in the tagliatelle al ragù recipe, and better for being made the day before', no:'laget som i oppskriften på tagliatelle al ragù, og bedre av å lages dagen før'}},
    ]},
    { group:{en:'For the béchamel', no:'Til béchamelen'}, items:[
      {q:1,  u:'l', n:{en:'whole milk', no:'helmelk'}},
      {q:80, u:'g', n:{en:'butter', no:'smør'}},
      {q:80, u:'g', n:{en:'flour', no:'hvetemel'}},
      {u:'', n:{en:'nutmeg', no:'muskatnøtt'}, note:{en:'grated fresh', no:'nyrevet'}, scale:'none'},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'To assemble', no:'Til montering'}, items:[
      {q:150, u:'g', n:{en:'Parmigiano Reggiano', no:'Parmigiano Reggiano'}, note:{en:'finely grated', no:'finrevet'}},
      {q:30,  u:'g', n:{en:'butter', no:'smør'}, note:{en:'for the dish and the top', no:'til formen og til toppen'}},
    ]},
  ],
  steps:[
    {en:'Wilt the spinach in the water still clinging to its leaves, then squeeze it in a cloth until nothing more comes out and chop it very fine. Wet spinach is the one thing that will ruin the dough.',
     no:'La spinaten falle sammen i vannet som henger igjen på bladene, klem den så i et klede til det ikke kommer mer, og hakk den svært fint. Våt spinat er det ene som ødelegger deigen.'},
    {en:'Heap the flour on a board, break the eggs into a well, add the spinach and work it all into a firm green dough. Knead for 10 minutes, wrap it and rest it for half an hour.',
     no:'Legg melet i en haug på et brett, knus eggene i en fordypning, ha i spinaten og arbeid alt til en fast, grønn deig. Elt i 10 minutter, pakk den inn og la den hvile en halvtime.'},
    {en:'Roll the sheet out thin enough to see the board through it, and cut it into rectangles that fit your dish.',
     no:'Kjevle platen ut så tynn at du ser brettet gjennom den, og skjær den i firkanter som passer formen din.'},
    {en:'Blanch the rectangles a few at a time in boiling salted water for half a minute, lift them into cold water, and lay them out flat on clean cloths.',
     no:'Forvell firkantene noen om gangen i kokende, saltet vann i et halvt minutt, løft dem over i kaldt vann og legg dem flatt utover på rene kleder.'},
    {en:'Melt the butter in a pan, stir in the flour and cook it for two minutes without letting it colour.',
     no:'Smelt smøret i en kjele, rør inn melet og la det koke i to minutter uten å ta farge.'},
    {en:'Pour in the milk in a thin stream, whisking, and simmer for about 10 minutes until the sauce coats the back of a spoon. Season with salt and a good grating of nutmeg.',
     no:'Hell melken i en tynn stråle mens du visper, og la sausen småkoke i omtrent 10 minutter til den dekker baksiden av en skje. Smak til med salt og rikelig revet muskat.'},
    {en:'Butter the dish and spread a thin film of béchamel over the bottom, so the first sheet does not stick.',
     no:'Smør formen og bre et tynt lag béchamel i bunnen, så den første platen ikke setter seg fast.'},
    {en:'Build six layers: pasta, a thin coat of ragù, a thin coat of béchamel, a dusting of Parmigiano. Keep every layer mean; the sheet should show through the sauce.',
     no:'Bygg seks lag: plate, et tynt lag ragù, et tynt lag béchamel og litt revet Parmigiano. Hold hvert lag knapt, for platen skal skinne gjennom sausen.'},
    {en:'Finish with béchamel and the last of the Parmigiano, and dot the top with butter.',
     no:'Avslutt med béchamel og resten av Parmigianoen, og legg klatter av smør på toppen.'},
    {en:'Bake at 190 °C for 35 to 40 minutes, until the surface is brown in patches and the edges bubble.',
     no:'Stek ved 190 °C i 35 til 40 minutter, til overflaten er brun i flekker og det bobler i kantene.'},
    {en:'Let the dish stand for a quarter of an hour before you cut it.',
     no:'La formen stå et kvarter før du skjærer i den.'},
  ],
  notes:[
    {title:{en:'The béchamel is the binder', no:'Béchamelen er bindemiddelet'},
     body:{en:'Flour cooked in butter and let down with milk sets into a starch gel as it cools, and that gel holds the layers in place. In the south ricotta or mozzarella does the same job, but in the north the dairy is cow’s milk and butter, and the lasagne is built accordingly. It also explains why a thin béchamel gives a lasagne that slumps: there is not enough starch in it to set.',
           no:'Mel som kokes i smør og spes med melk, stivner til en stivelsesgelé når den kjølner, og den geleen holder lagene på plass. I sør gjør ricotta eller mozzarella den samme jobben, men nord i Italia er meieriet kumelk og smør, og lasagnen er bygget deretter. Det forklarer også hvorfor en tynn béchamel gir en lasagne som siger sammen: den har for lite stivelse til å stivne.'}},
    {title:{en:'Why the spinach costs you an egg', no:'Hvorfor spinaten koster deg et egg'},
     body:{en:'A Bolognese sfoglia is one egg to every hundred grams of flour. Squeezed spinach is still mostly water, and it brings enough of it to stand in for an egg. Put both in and the dough goes slack and the sheet tears on the pin. Squeeze harder than feels necessary: the colour stays behind, the water does not.',
           no:'En bolognesisk sfoglia er ett egg per hundre gram mel. Utklemt spinat er fortsatt for det meste vann, og den bringer med seg nok til å erstatte et egg. Har du med begge deler, blir deigen slapp og platen revner på kjevlen. Klem hardere enn det føles nødvendig: fargen blir igjen, vannet gjør ikke det.'}},
    {title:{en:'Rest it before you cut it', no:'La den hvile før du skjærer'},
     body:{en:'Straight from the oven the béchamel is liquid and the slice collapses. As it falls towards 60 °C the starch gel firms, the layers stop sliding and the lasagne cuts clean. The same quarter of an hour stops the top being too hot to taste.',
           no:'Rett fra ovnen er béchamelen flytende, og skiven faller sammen. Når den synker mot 60 °C, stivner stivelsesgeleen, lagene slutter å gli, og lasagnen lar seg skjære rent. Det samme kvarteret gjør at toppen ikke lenger er for varm til å smake noe.'}},
  ],
  variations:[
    {title:{en:'Lasagne bianche', no:'Lasagne bianche'},
     body:{en:'Leave the tomato out of the ragù and the lasagne comes out white, paler and rounder in flavour. That is the older form, from before the tomato arrived.',
           no:'Lages ragùen uten tomat, blir lasagnen hvit, blekere og rundere i smaken. Det er den eldre formen, fra før tomaten kom.'}},
    {title:{en:'Yellow sheets', no:'Gule plater'},
     body:{en:'The spinach is Bologna’s idea. A plain yellow sfoglia gives lasagne al forno, which is what the rest of Italy builds, and nothing else changes.',
           no:'Spinaten er Bolognas påfunn. En vanlig gul sfoglia gir lasagne al forno, slik resten av Italia bygger den, og ingenting annet endres.'}},
    {title:{en:'A day ahead', no:'Dagen før'},
     body:{en:'Assemble it, cover the dish and keep it cold overnight. Bake it straight from the fridge and give it 10 minutes more. Both the ragù and the béchamel are better for the wait.',
           no:'Sett lasagnen sammen, dekk formen til og la den stå kaldt over natten. Stek den rett fra kjøleskapet og gi den 10 minutter ekstra. Både ragùen og béchamelen blir bedre av å vente.'}},
  ],
},

{
  id:'gnocco-fritto', dish:'Gnocco fritto', course:'antipasto', lesson:1, serves:4,
  time:{prep:80, cook:20}, hero:'gnocco', tags:['fried','bread','salumi'],
  title:{en:'Gnocco fritto', no:'Gnocco fritto'},
  blurb:{en:'Pillows of fried dough, torn open while they are still too hot to hold and stuffed with prosciutto or salame. The Emilian aperitivo, with cold Lambrusco.',
         no:'Puter av fritert deig som rives opp mens de fortsatt er for varme å holde i, og fylles med prosciutto eller salame. Aperitivoen i Emilia, med kald Lambrusco til.'},
  heroCaption:{en:'Gnocco fritto, salame and Lambrusco: fried dough, cured pork and a cold, frothy red.',
               no:'Gnocco fritto, salame og Lambrusco: fritert deig, spekemat av svin og en kald, skummende rødvin.'},
  wines:['Lambrusco di Sorbara'],
  headnote:{
    en:'<p>Emilia starts the meal with fried dough. Gnocco fritto are pillows that billow up in hot fat, are torn open while they are still steaming and are filled with prosciutto, salame or culatello. Dry Lambrusco is what goes with them, cold, from a tumbler.</p>'
      + '<p>The puff is steam, not yeast. The dough is rolled thin, the fat is hot enough to set the outside in a couple of seconds, and the water inside then has nowhere to go, so it forces the two faces apart. If the fat is too cool the steam escapes before the crust has formed, and what comes out is flat, heavy and greasy.</p>'
      + '<p>Emilia fries in lard because Emilia has it. The region that makes the prosciutto renders the rest of the pig as well. Sunflower oil is the practical substitute; olive oil pushes its own flavour into a bread that should not have one.</p>',
    no:'<p>Emilia begynner måltidet med fritert deig. Gnocco fritto er puter som blåser seg opp i varmt fett, rives opp mens de fortsatt damper og fylles med prosciutto, salame eller culatello. Tørr Lambrusco er det som hører til, kald, av et vannglass.</p>'
      + '<p>Dampen blåser den opp, ikke gjæren. Deigen kjevles tynn, fettet er varmt nok til at overflaten setter seg på et par sekunder, og vannet inni har da ingen vei ut. Det river de to flatene fra hverandre. Er fettet for kaldt, slipper dampen ut før skorpen har dannet seg, og resultatet blir flatt, tungt og fett.</p>'
      + '<p>Emilia friterer i smult fordi Emilia har det. Regionen som lager prosciutto, smelter også ned resten av grisen. Solsikkeolje er den praktiske erstatningen, mens olivenolje presser sin egen smak inn i et brød som ikke skal ha noen.</p>'},
  ingredients:[
    { group:{en:'For the dough', no:'Til deigen'}, items:[
      {q:500, u:'g', n:{en:'‘00’ flour', no:'mel type 00'}},
      {q:50,  u:'g', n:{en:'lard', no:'smult'}, note:{en:'strutto, soft; butter or olive oil will do', no:'strutto, mykt; smør eller olivenolje gjør nytten'}},
      {q:10,  u:'g', n:{en:'fresh yeast', no:'fersk gjær'}, note:{en:'or a third of the weight in dried yeast', no:'eller en tredel av vekten i tørrgjær'}},
      {q:250, u:'ml', n:{en:'milk', no:'melk'}, note:{en:'lukewarm; water is the older version and gives a crisper gnocco', no:'lunken; vann er den eldre varianten og gir en sprøere gnocco'}},
      {q:10,  u:'g', n:{en:'salt', no:'salt'}},
    ]},
    { group:{en:'For frying', no:'Til fritering'}, items:[
      {q:1, u:'kg', n:{en:'lard for frying', no:'smult til fritering'}, note:{en:'what Emilia fries in; sunflower oil is the usual substitute', no:'det Emilia friterer i; solsikkeolje er den vanlige erstatningen'}, scale:'none'},
      {u:'', n:{en:'salt for the fried dough', no:'salt til den friterte deigen'}, scale:'none'},
    ]},
    { group:{en:'To serve', no:'Til servering'}, items:[
      {q:200, u:'g', n:{en:'salumi', no:'salumi'}, note:{en:'Prosciutto di Parma, salame felino, culatello, mortadella — whatever is on the board', no:'Prosciutto di Parma, salame felino, culatello, mortadella — det som ligger på fjøla'}},
      {q:150, u:'g', n:{en:'squacquerone or stracchino', no:'squacquerone eller stracchino'}, note:{en:'not obligatory, but good against the salt', no:'ikke obligatorisk, men godt mot saltet'}},
    ]},
  ],
  steps:[
    {en:'Crumble the yeast into the lukewarm milk and stir until it has dissolved.',
     no:'Smuldre gjæren i den lunkne melken og rør til den er løst opp.'},
    {en:'Rub the lard into the flour and the salt with your fingertips, until nothing greasy is left in lumps.',
     no:'Smuldre smultet inn i melet og saltet med fingertuppene, til det ikke ligger igjen klumper av fett.'},
    {en:'Pour in the milk and work it to a soft, smooth dough, then knead it for 8 minutes.',
     no:'Hell i melken og arbeid alt sammen til en myk, glatt deig, og elt den så i 8 minutter.'},
    {en:'Cover the bowl and leave the dough somewhere warm for an hour, until it has nearly doubled.',
     no:'Dekk bollen til og la deigen stå lunt i en time, til den nesten har doblet seg.'},
    {en:'Roll it out on a floured board to about 3 mm, no thicker, and cut it into diamonds or squares about the size of a palm.',
     no:'Kjevle den ut på et melet brett til rundt 3 mm, ikke tykkere, og skjær den i rombeformer eller ruter på størrelse med en håndflate.'},
    {en:'Heat the frying fat to 175 °C in a deep pan. Below that the gnocco soaks it up; above it, the outside colours before the inside has puffed.',
     no:'Varm frityrfettet til 175 °C i en dyp gryte. Under det suger gnoccoen til seg fett, og over det tar overflaten farge før innsiden har blåst seg opp.'},
    {en:'Slide in three or four pieces at a time and hold them under the surface for a moment with a slotted spoon. They should billow up almost at once.',
     no:'Slipp i tre–fire biter om gangen og hold dem et øyeblikk under overflaten med en hullsleiv. De skal blåse seg opp nesten med en gang.'},
    {en:'Turn them when the underside is pale gold, after about a minute, and give the other side the same.',
     no:'Snu dem når undersiden er lyst gylden, etter omtrent ett minutt, og gi den andre siden like lang tid.'},
    {en:'Lift them onto paper, salt them very lightly and keep frying. A gnocco waits for nobody.',
     no:'Løft dem over på papir, salt dem svært lett, og fortsett å fritere. En gnocco venter ikke på noen.'},
    {en:'Pile them on the table while they are still too hot to hold, tear them open and stuff them with the salumi and the cheese. Pour the Lambrusco cold.',
     no:'Sett dem på bordet mens de fortsatt er for varme å holde i, riv dem opp og fyll dem med salumi og ost. Skjenk Lambruscoen kald.'},
  ],
  notes:[
    {title:{en:'Why it puffs', no:'Hvorfor den blåser seg opp'},
     body:{en:'The sheet is thin and the fat is hot enough to set its surface in seconds. The water inside then turns to steam with nowhere to escape, and it forces the two faces apart into a pillow. The order of events is everything: fat that is too cool lets the steam out before the crust has formed, and what surfaces is flat and greasy. A thermometer earns its place here.',
           no:'Platen er tynn, og fettet er varmt nok til at overflaten setter seg på sekunder. Vannet inni går da over til damp uten noen vei ut, og det river de to flatene fra hverandre til en pute. Rekkefølgen avgjør alt: er fettet for kaldt, slipper dampen ut før skorpen har dannet seg, og resultatet blir flatt og fett. Et steketermometer gjør nytte for seg her.'}},
    {title:{en:'Yeast for texture, not for lift', no:'Gjær for tekstur, ikke for heving'},
     body:{en:'An hour is not long enough to leaven much, and it is not meant to be. The yeast is there to slacken the gluten, so the dough rolls thin without pulling back, and to give a faint bready flavour. The lift in a gnocco fritto comes from steam, never from gas.',
           no:'En time er ikke lenge nok til å heve stort, og det er heller ikke meningen. Gjæren er der for å slakke glutenet, så deigen lar seg kjevle tynn uten å trekke seg tilbake, og for å gi et snev av brødsmak. Løftet i en gnocco fritto kommer fra damp og aldri fra gass.'}},
    {title:{en:'The fat of the same pig', no:'Fettet fra den samme grisen'},
     body:{en:'Lard carries less flavour of its own into the dough than olive oil does, which is why a gnocco fried in it tastes of dough. Emilia has lard because Emilia raises the pigs that give it the prosciutto, and using both is the same thrift that put the whey from the cheese into the pigs’ feed.',
           no:'Smult bærer mindre egen smak inn i deigen enn olivenolje gjør, og derfor smaker en gnocco som er fritert i smult, av deig. Emilia har smult fordi Emilia holder grisene som gir den prosciuttoen, og den som bruker begge deler, følger den samme nøysomheten som la mysen fra osten i grisefôret.'}},
  ],
  variations:[
    {title:{en:'Tigelle and crescentine', no:'Tigelle og crescentine'},
     body:{en:'The same table, a different heat: small discs of a related dough baked between hot moulds of iron or terracotta, split and filled the same way. In the hills above Modena they are called tigelle.',
           no:'Det samme bordet, en annen varme. Små leiver av en beslektet deig bakes mellom varme former av jern eller leire, deles og fylles på samme måte. I åsene over Modena kalles de tigelle.'}},
    {title:{en:'The name changes with the miles', no:'Navnet skifter med milene'},
     body:{en:'Along the Via Emilia it is gnocco fritto in Modena and Reggio, torta fritta in Parma, chisulén in Piacenza and crescentine in Bologna. The dough is the same everywhere.',
           no:'Langs Via Emilia heter den gnocco fritto i Modena og Reggio, torta fritta i Parma, chisulén i Piacenza og crescentine i Bologna. Deigen er den samme overalt.'}},
    {title:{en:'Milk or water', no:'Melk eller vann'},
     body:{en:'Water gives a crisper, lighter gnocco and milk a softer, paler one. The farmhouse recipes used water and whatever else was to hand.',
           no:'Vann gir en sprøere og lettere gnocco, melk en mykere og blekere. Gårdsoppskriftene brukte vann og det som ellers fantes.'}},
  ],
},

];
