// friuli recipes. Contract: docs/recipe-format.md. Both languages in one file; never narrated.
// Everything here follows the Friuli food reading (content/friuli.js, lesson 3): Montasio fried into
// frico, the sweet-and-savoury cjarsons of Carnia, brovada fermented in grape marc and served with
// musetto, the bean-and-sauerkraut jota of Trieste, and the gubana of the Natisone valleys.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-36'] = [

{
  id:'frico', dish:'Frico', course:'secondo', lesson:3, serves:4, time:{prep:20, cook:40},
  hero:'frico', tags:['cheese','potato','montasio'],
  title:{en:'Frico con patate', no:'Frico con patate'},
  blurb:{en:'Montasio, potato and onion fried into a single golden cake with a crust on both sides. No egg, no flour: the cheese is the binder.',
         no:'Montasio, potet og løk stekt til én gyllen kake med skorpe på begge sider. Verken egg eller mel, for osten er bindemiddelet.'},
  heroCaption:{en:'Frico with potatoes on a village table in Friuli, cut in wedges and eaten with soft polenta.',
               no:'Frico med poteter på et landsbybord i Friuli, skåret i båter og spist med myk polenta.'},
  wines:['Refosco dal Peduncolo Rosso'],
  headnote:{
    en:'<p>Montasio has been made in these mountains since the thirteenth century, when the monks of the abbey of Moggio organised the dairies of Carnia: a firm, pale cow’s-milk cheese, mild at two months and sharp and crystalline at two years. Frico is what Friuli does with it. Grated Montasio fried slowly with sliced potato and onion sets into a golden cake, crisp outside and melting inside, and it goes to the table with soft polenta. It was the dish shepherds and woodcutters carried up the mountain; it is now on every menu in Udine.</p>'
      + '<p>There is no egg here and no flour. The cheese is the binder — its fat and its protein melt into the potato starch and hold everything together, and the layer touching the pan dries and browns into the crust most people remember the dish by. That is also why the potato has to be cooked through before the cheese arrives: once the cheese has melted around it, no steam can reach it and nothing softens any further.</p>'
      + '<p>Every trattoria claims its own proportion of cheese to potato, and the argument is as fierce as any about ragù in Bologna. Equal weights sit in the middle of it and are a good place to start. Stillness is the part that is not negotiable: the cake must be left alone over moderate heat long enough to build its crust, and turned exactly once.</p>',
    no:'<p>Montasio er laget i disse fjellene siden 1200-tallet, da munkene i klosteret Moggio organiserte meieriene i Carnia. Det er en fast, lys ost av kumelk, mild etter to måneder, skarp og full av krystaller etter to år. Friuli bruker den til frico. Revet Montasio som stekes langsomt med potetskiver og løk, setter seg til en gyllen kake som er sprø utenpå og smeltende inni, og den kommer på bordet med myk polenta. Gjetere og tømmerhoggere tok den med seg opp i fjellet, og nå står den på hver eneste meny i Udine.</p>'
      + '<p>Her er det verken egg eller mel. Osten er bindemiddelet: fettet og proteinet smelter inn i potetstivelsen og holder kaken sammen, og det laget som ligger mot pannen, tørker og brunes til den skorpen folk husker retten for. Derfor må poteten være gjennomkokt før osten går i. Når osten først har smeltet rundt den, slipper ingen damp inn, og ingenting blir mykere.</p>'
      + '<p>Hver trattoria hevder å ha sitt eget forhold mellom ost og potet, og striden er like hard som noen om ragù i Bologna. Like mye av hver ligger midt mellom ytterpunktene og er et godt sted å begynne. Én ting kan du ikke slurve med: kaken må ligge i fred over middels varme lenge nok til å bygge skorpen, og den skal snus nøyaktig én gang.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:400, u:'g', n:{en:'floury potatoes', no:'melne poteter'}, note:{en:'peeled and sliced about 3 mm thick', no:'skrelt og skåret i skiver på rundt 3 mm'}},
    {q:400, u:'g', n:{en:'Montasio mezzano', no:'Montasio mezzano'}, note:{en:'five to ten months old, coarsely grated, at room temperature', no:'fem til ti måneder gammel, grovrevet, med romtemperatur'}},
    {q:1, u:'', n:{en:'onion', no:'løk'}, note:{en:'sliced thin', no:'skåret i tynne skiver'}, round:'half'},
    {q:40, u:'g', n:{en:'butter', no:'smør'}, note:{en:'lard is the older fat and gives a deeper crust', no:'smult er det eldre fettet og gir dypere skorpe'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, note:{en:'ground over at the end', no:'kvernet over til slutt'}, scale:'none'},
    {u:'', n:{en:'soft polenta, to serve', no:'myk polenta, til servering'}, scale:'none'},
  ]}],
  steps:[
    {en:'Peel the potatoes and slice them thinly. Choose a floury variety: it breaks down at the edges and lends the cake its starch, while a waxy potato stays as separate discs that slide apart under the knife.',
     no:'Skrell potetene og skjær dem i tynne skiver. Velg en melen sort, for den faller fra hverandre i kantene og gir kaken stivelsen sin, mens en fast potet blir liggende som løse skiver som sklir fra hverandre under kniven.'},
    {en:'Slice the onion thinly and melt the butter in a heavy pan about 24 cm across over low heat.',
     no:'Skjær løken i tynne skiver, og smelt smøret i en tung panne på rundt 24 cm over svak varme.'},
    {en:'Cook the onion gently until it is soft and pale gold, about ten minutes. Do not let it brown; the sweetness you want here is mild.',
     no:'Stek løken forsiktig til den er myk og lysegyllen, omtrent ti minutter. La den ikke bli brun, for søtheten du er ute etter, skal være mild.'},
    {en:'Add the potato, salt it lightly, cover the pan and cook over low heat for fifteen to twenty minutes, turning now and then, until a slice crushes easily against the side. Add a splash of water if it starts to catch.',
     no:'Ha i poteten, salt den lett, legg på lokk, og la den steke på svak varme i femten til tjue minutter mens du vender innimellom, til en skive lar seg mose lett mot kanten. Spe med en skvett vann hvis det begynner å feste seg.'},
    {en:'Crush roughly a third of the potato with the back of a spoon and leave the rest in pieces. The crushed part is the glue, the rest is the texture.',
     no:'Mos omtrent en tredel av poteten med baksiden av en skje, og la resten ligge i biter. Den mosede delen er limet, og resten gir kaken konsistens.'},
    {en:'Grate the Montasio coarsely. Cold cheese straight from the fridge melts unevenly, so let it stand out while the potato cooks.',
     no:'Riv Montasioen grovt. Kald ost rett fra kjøleskapet smelter ujevnt, så la den stå framme mens poteten koker.'},
    {en:'Scatter the cheese over the potato, fold it through once or twice only, and press the whole thing flat into an even layer that reaches the edge of the pan.',
     no:'Strø osten over poteten, vend den inn bare én eller to ganger, og press det hele flatt til et jevnt lag som når helt ut i kanten av pannen.'},
    {en:'Raise the heat to medium-low and leave the cake completely alone for eight to ten minutes, until the underside is a deep gold crust and the edge lifts cleanly with a palette knife.',
     no:'Skru opp til middels svak varme, og la kaken ligge helt i fred i åtte til ti minutter, til undersiden er en dyp gyllen skorpe og kanten slipper rent når du løfter den med en palettkniv.'},
    {en:'Slide the cake onto a plate or a flat lid, invert it back into the pan and brown the second side for six to eight minutes.',
     no:'La kaken gli over på en tallerken eller et flatt lokk, vend den tilbake i pannen, og brun den andre siden i seks til åtte minutter.'},
    {en:'Grind pepper over it, let it rest for five minutes so the cheese sets, then cut it into wedges and serve with soft polenta.',
     no:'Kvern pepper over, la den hvile i fem minutter så osten setter seg, skjær den så i båter, og server med myk polenta.'},
  ],
  notes:[
    {title:{en:'The cheese has to be the right age', no:'Osten må ha riktig alder'},
     body:{en:'A very young Montasio is still wet and elastic: it strings rather than binds, and the cake weeps. A stravecchio of eighteen months has lost enough water that its fat separates and fries instead of melting. Mezzano, five to ten months, has fat and protein in the proportion that turns to a crust rather than to oil, which is why it is the frico cheese.',
           no:'En helt ung Montasio er fortsatt våt og elastisk. Den trekker tråder i stedet for å binde, og kaken blir vassen. En stravecchio på atten måneder har mistet så mye vann at fettet skiller seg ut og freser i stedet for å smelte. Mezzano på fem til ti måneder har fett og protein i det forholdet som gir skorpe og ikke olje, og derfor er det den som brukes til frico.'}},
    {title:{en:'A crust is built by not touching it', no:'Skorpen bygges ved at du lar den være'},
     body:{en:'The crust forms where melted cheese sits against hot metal long enough to dry out and brown. Every stir puts wet cheese back over the dry layer and starts the clock again. Moderate heat matters just as much: too high and the fat breaks out of the cheese and fries the surface before it has had time to set.',
           no:'Skorpen dannes der smeltet ost ligger mot varmt metall lenge nok til å tørke og brunes. Hver gang du rører, legger du våt ost tilbake over det tørre laget og starter klokken på nytt. Middels varme betyr like mye, for blir det for varmt, skiller fettet seg ut av osten og steker overflaten før den har rukket å sette seg.'}},
    {title:{en:'Cook the potato first, all the way', no:'Kok poteten ferdig først'},
     body:{en:'Melted cheese seals the potato in a coat of fat that steam cannot cross. Whatever is still firm when the cheese goes in will still be firm on the plate, however long the cake fries afterwards.',
           no:'Smeltet ost lukker poteten inne i et lag fett som damp ikke kommer gjennom. Alt som fortsatt er hardt når osten går i, er like hardt på tallerkenen, uansett hvor lenge kaken steker etterpå.'}},
  ],
  variations:[
    {title:{en:'Frico croccante, the crisp version', no:'Frico croccante, den sprø utgaven'},
     body:{en:'The other frico is cheese alone. Scatter a thin, even handful of grated Montasio into a dry non-stick pan over medium heat, let it melt, bubble and stop bubbling, and lift the lace-gold disc out with a spatula after about three minutes. Drape it over a rolling pin while it is warm and it sets into a curved wafer for the aperitivo.',
           no:'Den andre fricoen er bare ost. Strø en tynn, jevn håndfull revet Montasio i en tørr, slippbelagt panne på middels varme, la den smelte, boble og slutte å boble, og løft den gyllenblonde skiven ut med en stekespade etter omtrent tre minutter. Legg den over en kjevle mens den er varm, så stivner den til et buet flak til aperitivoen.'}},
    {title:{en:'The ratio is the argument', no:'Striden står om forholdet'},
     body:{en:'Tip the balance towards the cheese and you get a softer, stringier frico that is closer to a fondue with potato in it. Tip it towards the potato and you get a firm cake that slices cleanly and takes a longer, better crust. Both are orthodox in their own valley.',
           no:'Vipper du balansen mot osten, får du en mykere og trådigere frico som ligner mer på en fondue med potet i. Vipper du den mot poteten, får du en fast kake som lar seg skjære pent og tåler den lange stekingen som gir best skorpe. Begge er ortodokse i hver sin dal.'}},
    {title:{en:'If you cannot find Montasio', no:'Hvis du ikke får tak i Montasio'},
     body:{en:'Look for a firm cow’s-milk mountain cheese aged at least five months with a fat content around 45 per cent: Asiago mezzano, a young Gruyère or Comté, or a well-matured alpine-style cheese from a local dairy. Avoid anything that stretches like mozzarella and anything sweet or brown; neither will build a crust.',
           no:'Se etter en fast fjellost av kumelk som er lagret minst fem måneder og har rundt 45 prosent fett, for eksempel Asiago mezzano, en ung Gruyère eller Comté, eller en godt lagret norsk fjellost fra et lite meieri. Hold deg unna oster som trekker tråder slik mozzarella gjør, og alt som er søtt eller brunt, for ingen av delene bygger skorpe.'}},
  ],
},

{
  id:'cjarsons', dish:'Cjarsons', course:'primo', lesson:3, serves:4, time:{prep:75, cook:15},
  hero:'cjarsons', tags:['pasta','carnia','sweet-savoury'],
  title:{en:'Cjarsons', no:'Cjarsons'},
  blurb:{en:'The filled pasta of Carnia: potato dough around ricotta, raisins, cocoa and mint, dressed with browned butter and smoked ricotta. Sweet and savoury in the same mouthful.',
         no:'Den fylte pastaen fra Carnia: potetdeig rundt ricotta, rosiner, kakao og mynte, med brunet smør og røykt ricotta over. Søtt og salt i samme munnfull.'},
  heroCaption:{en:'Cjarsons from Carnia under grated smoked ricotta and browned butter.',
               no:'Cjarsons fra Carnia under revet røykt ricotta og brunet smør.'},
  wines:['Friulano'],
  headnote:{
    en:'<p>Carnia is the mountainous north-west of the region, a knot of poor Friulian-speaking valleys under the Carnic Alps, and for centuries its men left every spring to work as pedlars in Austria and Germany and came home in autumn with spices, sugar and raisins. That history is the filling of the cjarsons. They are the valley’s ravioli, and they are unlike any pasta south of the Alps: potato or bread dough around a mixture that can hold spinach, ricotta, raisins, cocoa, cinnamon, apricot jam, mint and lemon, boiled and dressed with melted butter and grated smoked ricotta.</p>'
      + '<p>There is no single correct cjarsons. The filling changes from village to village and from house to house, and arguing about it is part of the dish. What follows keeps to the elements the course names, in proportions that hold together, and it is meant to be adjusted rather than copied.</p>'
      + '<p>Two things do the work. The sugar has to stay small enough to read as a scent rather than as a dessert, and the smoked ricotta grated over the top has to be salty and dry enough to push back against it. Take the smoked ricotta away and the plate collapses into pudding; that is why it is not a garnish.</p>',
    no:'<p>Carnia er den fjellrike nordvestlige delen av regionen, en klynge fattige, friulisktalende daler under De karniske alper. I århundrer dro mennene derfra hver vår for å arbeide som kramkarer i Østerrike og Tyskland, og de kom hjem om høsten med krydder, sukker og rosiner. Den historien ligger i fyllet til cjarsons. De er dalens ravioli, og de ligner ingen pasta sør for Alpene: en deig av potet eller brød rundt en blanding som kan romme spinat, ricotta, rosiner, kakao, kanel, aprikossyltetøy, mynte og sitron, kokt og servert med smeltet smør og revet røykt ricotta.</p>'
      + '<p>Det finnes ingen fasit for cjarsons. Fyllet skifter fra landsby til landsby og fra hus til hus, og striden om det hører med til retten. Oppskriften under holder seg til de ingrediensene kurset nevner, i mengder som henger sammen, og den er ment å justeres, ikke kopieres.</p>'
      + '<p>To ting avgjør retten. Mengden sukker må være så liten at den kjennes som en duft og ikke som en dessert, og den røykte ricottaen på toppen må være salt og tørr nok til å svare på det. Tar du bort den røykte ricottaen, faller tallerkenen sammen til pudding, og derfor er den ingen pynt.</p>'},
  ingredients:[
    { group:{en:'For the dough', no:'Til deigen'}, items:[
      {q:500, u:'g', n:{en:'floury potatoes', no:'melne poteter'}, note:{en:'boiled in their skins and peeled while hot', no:'kokt med skallet på og skrelt mens de er varme'}},
      {q:150, u:'g', n:{en:'plain flour', no:'hvetemel'}, note:{en:'plus a little for the work surface', no:'og litt til arbeidsbenken'}},
      {q:1, u:'', n:{en:'egg', no:'egg'}, round:'half'},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'For the filling', no:'Til fyllet'}, items:[
      {q:250, u:'g', n:{en:'ricotta', no:'ricotta'}, note:{en:'drained in a sieve for an hour', no:'avrent i en sil i en time'}},
      {q:100, u:'g', n:{en:'spinach', no:'spinat'}, note:{en:'cooked, squeezed very dry and chopped fine', no:'kokt, klemt godt tørr og finhakket'}},
      {q:50, u:'g', n:{en:'raisins', no:'rosiner'}, note:{en:'soaked in warm water or grappa and drained', no:'bløtlagt i varmt vann eller grappa og avrent'}},
      {q:30, u:'g', n:{en:'sugar', no:'sukker'}},
      {q:30, u:'g', n:{en:'apricot jam', no:'aprikossyltetøy'}},
      {q:8, u:'g', n:{en:'unsweetened cocoa', no:'kakao uten sukker'}},
      {q:2, u:'g', n:{en:'ground cinnamon', no:'malt kanel'}},
      {q:5, u:'g', n:{en:'fresh mint', no:'fersk mynte'}, note:{en:'leaves only, chopped', no:'bare bladene, hakket'}},
      {q:1, u:'', n:{en:'lemon', no:'sitron'}, note:{en:'the zest only', no:'bare det revne skallet'}, round:'half'},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'To finish', no:'Til servering'}, items:[
      {q:80, u:'g', n:{en:'butter', no:'smør'}},
      {q:60, u:'g', n:{en:'smoked ricotta', no:'røykt ricotta'}, note:{en:'ricotta affumicata, grated; see the note below if there is none to be had', no:'ricotta affumicata, revet; se notatet under hvis den ikke er å oppdrive'}},
      {q:4, u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:20, u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
    ]},
  ],
  steps:[
    {en:'Boil the potatoes whole in their skins until a knife slides through without resistance, about twenty-five minutes, and peel them while they are still too hot to hold comfortably.',
     no:'Kok potetene hele med skallet på til en kniv glir gjennom uten motstand, omtrent tjuefem minutter, og skrell dem mens de fortsatt er nesten for varme å holde i.'},
    {en:'Rice or mash them onto the work surface and spread them out to let the steam go. A wet mash swallows flour and turns the dough heavy.',
     no:'Press dem gjennom en potetpresse eller mos dem ut på benken, og bre dem utover så dampen slipper ut. En våt mos suger til seg mel og gjør deigen tung.'},
    {en:'Work in the flour, the egg and a pinch of salt while the potato is still warm, adding flour only until the dough stops sticking to your hand. Stop there: every extra spoonful of flour makes the wrapper you can roll a little thicker.',
     no:'Arbeid inn melet, egget og en klype salt mens poteten fortsatt er lun, og tilsett bare så mye mel at deigen slutter å klistre seg til hånden. Stopp der, for jo mer mel du tilsetter, desto tykkere blir deigveggen du klarer å kjevle.'},
    {en:'Shape the dough into a ball, cover it with a cloth and let it rest for twenty minutes while you make the filling.',
     no:'Form deigen til en ball, dekk den med et klede, og la den hvile i tjue minutter mens du lager fyllet.'},
    {en:'Squeeze the cooked spinach until no more water comes out of it, then chop it fine. Wet filling tears a potato dough from the inside.',
     no:'Klem den kokte spinaten til det ikke kommer mer vann ut av den, og hakk den fin. Vått fyll river en potetdeig i stykker innenfra.'},
    {en:'Mix the drained raisins with the ricotta, spinach, sugar, jam, cocoa, cinnamon, mint, lemon zest and a little salt into a smooth paste, then taste it. It should be faintly sweet and clearly herbal, and it should make you want a second spoonful.',
     no:'Bland de avrente rosinene med ricotta, spinat, sukker, syltetøy, kakao, kanel, mynte, revet sitronskall og litt salt til en jevn masse, og smak på den. Den skal være svakt søt og tydelig urteaktig, og den skal få deg til å ville ha en skje til.'},
    {en:'Roll the dough out on a floured surface as thinly as you dare, two to three millimetres, and cut discs about seven centimetres across.',
     no:'Kjevle ut deigen på en melet benk så tynt du tør, to til tre millimeter, og stikk ut sirkler på omtrent sju centimeter.'},
    {en:'Put a walnut of filling on each disc, fold it into a half-moon, press the edge closed with a damp finger and pleat it. Squeeze the air out as you go; a trapped bubble bursts the seam in the water.',
     no:'Legg en valnøttstor klatt fyll på hver sirkel, brett den til en halvmåne, klem kanten igjen med en fuktig finger, og legg den i små folder. Press ut luften underveis, for en innestengt boble sprenger sømmen i kokevannet.'},
    {en:'Bring the water to the boil, salt it, and cook the cjarsons in batches so they are never crowded. They are done a minute or two after they rise to the surface.',
     no:'Kok opp vannet, salt det, og kok cjarsons i puljer så de aldri ligger trangt. De er ferdige et minutt eller to etter at de har flytt opp.'},
    {en:'While they cook, melt the butter in a wide pan over medium heat until the milk solids turn hazel and it smells of nuts, then take the pan off the heat.',
     no:'Mens de koker, smelter du smøret i en vid panne på middels varme til melkerestene blir nøttebrune og det dufter av nøtter. Ta så pannen av platen.'},
    {en:'Lift the cjarsons out with a slotted spoon, let them drain for a moment and turn them gently in the warm butter.',
     no:'Løft cjarsons opp med hullsleiv, la dem renne av seg et øyeblikk, og vend dem forsiktig i det varme smøret.'},
    {en:'Grate the smoked ricotta thickly over the top and serve at once, before the butter cools and the dough tightens.',
     no:'Riv den røykte ricottaen rikelig over, og server med en gang, før smøret kjølner og deigen strammer seg.'},
  ],
  notes:[
    {title:{en:'Why there is sugar in a savoury pasta', no:'Hvorfor det er sukker i en salt pasta'},
     body:{en:'Carnia was poor and its men worked the empire as pedlars. What they brought home in autumn was small, light and expensive — cinnamon, cocoa, sugar, raisins — and those went into the feast-day dish rather than into a cake. The sweetness in a cjarson is a record of a trade route, and it should register as perfume against the salt, not as dessert.',
           no:'Carnia var fattig, og mennene der arbeidet som kramkarer i keiserriket. Det de bar med seg hjem om høsten, var smått, lett og dyrt — kanel, kakao, sukker og rosiner — og det gikk i festretten og ikke i en kake. Søtheten i en cjarson er et spor etter en handelsvei, og den skal kjennes som parfyme mot saltet, ikke som dessert.'}},
    {title:{en:'Smoked ricotta is the counterweight', no:'Den røykte ricottaen er motvekten'},
     body:{en:'Ricotta affumicata is dried hard, salted and cold-smoked until it grates like a hard cheese. It brings salt, smoke and dryness all at once, and that is the only thing on the plate holding the sweetness in check. Anything you put in its place has to do the same three jobs.',
           no:'Ricotta affumicata er tørket hard, saltet og kaldrøykt til den lar seg rive som en fast ost. Den gir salt, røyk og tørrhet på én gang, og den er det eneste på tallerkenen som holder søtheten i sjakk. Alt du setter i stedet, må gjøre de samme tre jobbene.'}},
    {title:{en:'Potato dough will not take a beating', no:'Potetdeig tåler ikke å bli banket'},
     body:{en:'Potato starch has already been cooked, so kneading develops gluten in the flour without any of the elasticity a bread dough would gain. The less flour and the less working, the more tender the result and the thinner you can roll it — but the faster you have to move before it goes slack.',
           no:'Potetstivelsen er allerede kokt, så elting bare utvikler gluten i melet uten at deigen får den spensten en brøddeig ville fått. Jo mindre mel og jo mindre arbeid, desto mørere blir resultatet og desto tynnere kan du kjevle den ut, men desto raskere må du også jobbe før deigen blir slapp.'}},
  ],
  variations:[
    {title:{en:'The filling belongs to the house', no:'Fyllet hører huset til'},
     body:{en:'Spinach, cocoa and apricot jam are one household’s answer. Others use pear, sultanas, crushed dry biscuits, candied citron, a spoon of honey, or mint and cinnamon with nothing else. Keep the shape of the thing — a fresh cheese, something sweet and dried, a green herb, a warm spice — and change the details freely.',
           no:'Spinat, kakao og aprikossyltetøy er svaret i ett hus. Andre bruker pære, sultanarosiner, knuste tørre kjeks, litt sukat, en skje honning, eller mynte og kanel og ingenting mer. Behold formen på retten — en fersk ost, noe søtt og tørket, en grønn urt og et varmt krydder — og bytt ut detaljene fritt.'}},
    {title:{en:'The bread dough version', no:'Utgaven med brøddeig'},
     body:{en:'Where potatoes were short, the wrapper was made from stale bread soaked in milk, squeezed out and bound with flour and egg. It is softer, quicker and greyer, and it wants a slightly firmer filling because it holds less well.',
           no:'Der potetene var få, ble deigen laget av tørt brød som ble bløtlagt i melk, klemt tørt og bundet med mel og egg. Den er mykere, raskere og gråere, og den vil ha et litt fastere fyll, for den holder dårligere på det.'}},
    {title:{en:'If there is no smoked ricotta', no:'Hvis du ikke får røykt ricotta'},
     body:{en:'Salt fresh ricotta lightly, press it under a weight in the fridge for two days until it is firm enough to grate, and season it with a pinch of smoked salt. Dry, salty ricotta salata with the same pinch does the job too. Steer clear of sweet smoked cheeses and of anything brown and caramel-tasting: they add to the sugar instead of answering it.',
           no:'Salt fersk ricotta lett, press den under et lodd i kjøleskapet i to døgn til den er fast nok til å rives, og smak den til med en klype røykesalt. Tørr, salt ricotta salata med den samme klypen gjør også nytten. Hold deg unna søte røkte oster og alt som er brunt og smaker karamell, for de bygger på søtheten i stedet for å svare på den.'}},
  ],
},

{
  id:'jota', dish:'Jota', course:'primo', lesson:3, serves:4, time:{prep:25, cook:150},
  hero:'jota', tags:['soup','beans','sauerkraut','winter'],
  title:{en:'Jota', no:'Jota'},
  blurb:{en:'Beans, sauerkraut, potato and smoked pork, cooked apart and married at the end, thick enough to stand a spoon in. Trieste’s winter soup, and the best of it is eaten the next day.',
         no:'Bønner, syrnet kål, potet og røkt svin kokes hver for seg og settes sammen til slutt, og suppen blir tykk nok til at skjeen står. Den er Triestes vintermat, og beste porsjon spises dagen etter.'},
  heroCaption:{en:'A bowl of jota: beans, sauerkraut and potato in a thick, smoky broth.',
               no:'En skål jota: bønner, syrnet kål og potet i en tykk, røykfylt kraft.'},
  wines:['Refosco dal Peduncolo Rosso'],
  headnote:{
    en:'<p>The winter table of Friuli is Austrian in spirit, and jota is the clearest case of it: the soup of Trieste and the Karst, made of beans, sauerkraut, potato and smoked pork, and thick enough to stand a spoon in. It belongs to the same cold border country as brovada and musetto, and it tastes far more of Central Europe than of Italy.</p>'
      + '<p>The method is the whole dish. Three things are cooked separately and only brought together at the end, because they want different times and different liquids — and because acid stops beans from softening. Sauerkraut in the pot from the beginning will leave you with beans that stay hard however long you boil them.</p>'
      + '<p>There is no cream in a jota and no stock cube. The body comes from three starches: beans crushed against the side of the pot, potato boiled until it dissolves, and flour cooked in fat until it smells toasted. The smoke comes from the pork, the salt largely comes with it, and the sourness is the cabbage. Season at the very end, or you will oversalt it.</p>',
    no:'<p>Vinterbordet i Friuli er østerriksk i ånden, og jota er det tydeligste eksempelet. Suppen fra Trieste og Karst er laget av bønner, syrnet kål, potet og røkt svin, og den er tykk nok til at skjeen står. Den hører til det samme kalde grenselandet som brovada og musetto, og den smaker langt mer av Sentral-Europa enn av Italia.</p>'
      + '<p>Framgangsmåten er hele retten. Tre ting kokes hver for seg og møtes først til slutt, fordi de vil ha ulik tid og ulik væske, og fordi syre hindrer bønner i å bli myke. Har du kålen i gryten fra starten, sitter du igjen med bønner som forblir harde uansett hvor lenge du koker dem.</p>'
      + '<p>Det går verken fløte eller buljongterning i en jota. Fylden kommer fra tre stivelser: bønner som moses mot gryteveggen, potet som kokes til den løser seg opp, og mel som stekes i fett til det dufter ristet. Røyken kommer fra svinekjøttet, saltet kommer stort sett med det, og syren er kålen. Smak til helt til slutt, ellers blir suppen for salt.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:250, u:'g', n:{en:'dried borlotti beans', no:'tørkede borlottibønner'}, note:{en:'soaked in cold water for twelve hours', no:'bløtlagt i kaldt vann i tolv timer'}},
    {q:400, u:'g', n:{en:'sauerkraut', no:'syrnet kål'}, note:{en:'fermented sour cabbage, drained but not rinsed; read the note below before you buy it', no:'melkesyregjæret kål, avrent, men ikke skylt; les notatet under før du kjøper'}},
    {q:400, u:'g', n:{en:'floury potatoes', no:'melne poteter'}, note:{en:'peeled, in rough pieces', no:'skrelt, i grove biter'}},
    {q:250, u:'g', n:{en:'smoked pork', no:'røkt svinekjøtt'}, note:{en:'a smoked rib rack, a hock, or a piece of smoked pancetta in one piece', no:'et stykke røkt ribbe, en knoke eller et helt stykke røkt pancetta'}},
    {q:1, u:'', n:{en:'onion', no:'løk'}, note:{en:'finely chopped', no:'finhakket'}, round:'half'},
    {q:2, u:'', n:{en:'garlic cloves', no:'hvitløksfedd'}, round:'half'},
    {q:40, u:'g', n:{en:'lard', no:'smult'}, note:{en:'butter or olive oil will do', no:'smør eller olivenolje gjør også nytten'}},
    {q:25, u:'g', n:{en:'plain flour', no:'hvetemel'}},
    {q:2, u:'', n:{en:'bay leaves', no:'laurbærblad'}, round:'half'},
    {q:3, u:'g', n:{en:'caraway or cumin seed', no:'karve eller spisskummen'}, note:{en:'Trieste leans towards cumin, the Karst towards caraway', no:'Trieste heller mot spisskummen, Karst mot karve'}},
    {q:2, u:'l', n:{en:'water', no:'vann'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
  ]}],
  steps:[
    {en:'Soak the beans in plenty of cold water overnight, then drain them and throw the soaking water away.',
     no:'Bløtlegg bønnene i rikelig kaldt vann natten over, hell dem så av, og kast bløtevannet.'},
    {en:'Cover the beans with fresh water in a large pot, add one bay leaf, bring them to a bare simmer and cook until tender, an hour to an hour and a half. Keep the lid ajar and top up with hot water as needed.',
     no:'Dekk bønnene med friskt vann i en stor kjele, ha i det ene laurbærbladet, la det så vidt småkoke, og kok dem møre i én til halvannen time. Hold lokket på gløtt, og spe med varmt vann underveis.'},
    {en:'Lower the smoked pork into the beans for the last forty-five minutes, so the broth takes the smoke and the meat gives up its gelatine.',
     no:'Legg det røkte svinekjøttet ned i bønnene de siste førtifem minuttene, slik at kraften tar opp røyken og kjøttet gir fra seg gelatinen sin.'},
    {en:'Meanwhile, put the sauerkraut in a second pan with the remaining bay leaf, the caraway and just enough water to cover, and simmer it for forty minutes until it has lost its raw, aggressive edge. Keep it in its liquid.',
     no:'Samtidig legger du den syrnede kålen i en annen kjele med det andre laurbærbladet, karven og akkurat nok vann til å dekke, og lar den småkoke i førti minutter til den har mistet den rå skarpheten. La den bli liggende i væsken sin.'},
    {en:'Boil the potato in a third pan in water that barely covers it, until the pieces fall apart at a touch, then crush half of them into their own water.',
     no:'Kok poteten i en tredje kjele i vann som så vidt dekker, til bitene faller fra hverandre ved berøring, og mos så halvparten av dem ut i sitt eget vann.'},
    {en:'Melt the lard in a small pan and cook the onion and garlic gently until they are soft and pale gold.',
     no:'Smelt smultet i en liten panne, og la løken og hvitløken surre forsiktig til de er myke og lysegylne.'},
    {en:'Stir the flour into the fat and cook it, stirring all the while, for three or four minutes until it smells toasted and turns the colour of straw.',
     no:'Rør melet inn i fettet, og la det steke i tre til fire minutter mens du rører hele tiden, til det dufter ristet og får farge som halm.'},
    {en:'Whisk a ladle of the hot bean liquid into the flour until it is a smooth cream with no lumps, then scrape the whole thing into the bean pot.',
     no:'Visp en øse med den varme bønnekraften inn i melet til det er en jevn krem uten klumper, og skrap så alt sammen ned i bønnegryten.'},
    {en:'Lift out the pork, take the meat off the bone, chop it coarsely and return it to the pot; leave the bone in as well if there is room.',
     no:'Ta opp kjøttet, skjær det av beinet, hakk det grovt, og ha det tilbake i gryten. La gjerne beinet bli med hvis det er plass.'},
    {en:'Tip in the potato with its water and the cabbage with its liquid, and let everything simmer together for at least twenty minutes so the flavours stop being three separate things.',
     no:'Hell i poteten med vannet sitt og kålen med væsken sin, og la alt småkoke sammen i minst tjue minutter, så smakene slutter å være tre atskilte ting.'},
    {en:'Crush some of the beans against the side of the pot until the soup holds the mark of a spoon drawn through it.',
     no:'Mos noen av bønnene mot gryteveggen til suppen beholder sporet etter skjeen når du drar den gjennom.'},
    {en:'Grind in plenty of pepper, taste, and only now add salt. Let the pot stand off the heat for an hour before serving, or better, cook it a day ahead and reheat it.',
     no:'Kvern i rikelig med pepper, smak til, og salt først nå. La kjelen stå av platen i en time før servering, eller enda bedre: lag suppen dagen før og varm den opp igjen.'},
  ],
  notes:[
    {title:{en:'Buy the right cabbage', no:'Kjøp riktig kål'},
     body:{en:'The sourness in a jota is lactic acid made by bacteria on raw cabbage, salted and left to ferment. That is what German Sauerkraut, Italian crauti and Polish kapusta kiszona all are, and the ingredients list should say cabbage and salt and nothing else. Sweetened, vinegared or caraway-cooked cabbage is a different dish altogether and will turn the soup sweet.',
           no:'Syren i en jota er melkesyre. Den lages av bakterier på rå kål som er saltet og satt til å gjære. Tysk Sauerkraut, italiensk crauti og polsk kapusta kiszona er nettopp dette, og innholdsfortegnelsen skal si kål og salt og ingenting annet. Norsk surkål er noe helt annet, nemlig kokt kål med karve, sukker og eddik, og den gjør suppen søt. Se etter melkesyregjæret kål i kjøledisken eller på glass fra en tysk eller polsk hylle.'}},
    {title:{en:'Acid goes in last', no:'Syren skal i sist'},
     body:{en:'Pectin in a bean skin dissolves in hot water but not in acid, so beans cooked in a sour liquid stay firm no matter how long they boil. Cook the beans on their own until they are properly tender, and let the cabbage in only once they are.',
           no:'Pektinet i et bønneskall løser seg opp i varmt vann, men ikke i syre, så bønner som kokes i sur væske, forblir harde uansett hvor lenge det står på. Kok bønnene alene til de er ordentlig møre, og slipp kålen til først da.'}},
    {title:{en:'Three starches, no cream', no:'Tre stivelser, ingen fløte'},
     body:{en:'Crushed beans, dissolved potato and a flour cooked in fat each thicken in a different way and at a different speed, which is exactly why they are cooked in separate pans. The cooked flour also does something the other two cannot: browning it drives off its raw taste and gives the soup its toasted background.',
           no:'Mosede bønner, oppløst potet og mel som er stekt i fett, tykner hver på sin måte og i sitt eget tempo, og nettopp derfor kokes de i hver sin kjele. Det stekte melet gjør dessuten noe de to andre ikke kan: bruningen driver bort den rå melsmaken og gir suppen den ristede bunntonen.'}},
  ],
  variations:[
    {title:{en:'Barley instead of potato', no:'Bygg i stedet for potet'},
     body:{en:'On the Slovene side of the Karst the potato is often replaced by pearl barley, simmered with the beans until it swells and gives up its starch. The soup comes out chewier and rounder, and it thickens further overnight.',
           no:'På den slovenske siden av Karst byttes poteten ofte ut med perlebygg, som småkoker sammen med bønnene til det sveller og gir fra seg stivelsen. Suppen får mer tyggemotstand og blir rundere i smaken, og den tykner ytterligere over natten.'}},
    {title:{en:'Jota with brovada', no:'Jota med brovada'},
     body:{en:'Inland, where brovada is made, the fermented turnip goes into the pot in place of the sauerkraut. It is sourer, winier and pinker, and the soup wants a little longer on the heat to soften it.',
           no:'Lenger inn i landet, der brovada lages, går den gjærede nepen i gryten i stedet for kålen. Den er syrligere, mer vinaktig og rosa i fargen, og suppen trenger litt lengre koketid for å myke den opp.'}},
    {title:{en:'A slice of musetto on top', no:'En skive musetto på toppen'},
     body:{en:'Simmer a musetto or a cotechino separately, cut it into thick slices and lay one on each bowl. It turns a starter into the whole of dinner, and the sausage keeps its own texture instead of falling apart in the soup.',
           no:'Trekk en musetto eller en cotechino for seg, skjær den i tykke skiver, og legg en skive i hver skål. Det gjør en forrett om til hele middagen, og pølsen beholder sin egen konsistens i stedet for å falle fra hverandre i suppen.'}},
  ],
},

{
  id:'brovada', dish:'Brovada', course:'contorno', lesson:3, serves:4, time:{prep:40, cook:90},
  hero:'brovada', tags:['fermented','turnip','christmas','dop'],
  title:{en:'Brovada e musetto', no:'Brovada e musetto'},
  blurb:{en:'Turnips fermented whole in grape marc, grated into shreds and stewed slowly, with a coarse boiled pork sausage on top. Friuli’s Christmas Eve plate.',
         no:'Hele neper gjærer i pressrester fra druer, blir revet i strimler og stuet lenge, og serveres med en grov kokt svinepølse på toppen. Retten Friuli spiser på julaften.'},
  heroCaption:{en:'A plate of grated brovada, pink and translucent from its month in the grape marc.',
               no:'En tallerken revet brovada, rosa og gjennomskinnelig etter måneden i pressrestene fra druene.'},
  wines:['Refosco dal Peduncolo Rosso'],
  headnote:{
    en:'<p>Brovada is the region’s answer to sauerkraut and one of the strangest protected foods in Italy. Turnips are buried in grape pomace after the harvest, left to ferment for a month or more, then grated and stewed until sour and winey. They go to the table with musetto, the coarse boiled sausage made from the meat of the pig’s snout, on Christmas Eve and at New Year, with polenta alongside.</p>'
      + '<p>Nothing sour is added. The marc comes out of the press still wet with wine and still carrying sugar and the yeasts and lactic bacteria of the skins, and it ferments around the turnips, sealing them from the air as it goes. The turnips take up acid and colour, and the white flesh turns translucent and pink through to the core. It is a ferment, not a pickle, which is why brovada tastes of wine rather than of vinegar.</p>'
      + '<p>Two things cannot be hurried. The pack has to stay cool and completely covered for weeks, and the stew has to be long — an hour at the very least — because the acid needs cooking down before the dish becomes comfortable to eat. Everything else here is a matter of what fat you have and how much pepper you like.</p>',
    no:'<p>Brovada er regionens svar på syrnet kål og en av de merkeligste beskyttede matvarene i Italia. Neper graves ned i pressrester fra druene etter innhøstingen, får gjære i en måned eller mer, og rives og stues så til de er syrlige og vinaktige. De kommer på bordet med musetto, den grove kokte pølsen av kjøtt fra grisens tryne, på julaften og nyttårsaften, med polenta ved siden av.</p>'
      + '<p>Ingenting surt tilsettes. Pressrestene kommer ut av pressen fortsatt våte av vin og bærer med seg både sukker og gjærsoppene og melkesyrebakteriene fra skallene. Massen gjærer rundt nepene og stenger dem samtidig ute fra luften. Nepene tar opp syre og farge, og det hvite kjøttet blir gjennomskinnelig og rosa helt inn til kjernen. Dette er en gjæring og ingen sylting, og derfor smaker brovada av vin og ikke av eddik.</p>'
      + '<p>To ting lar seg ikke forsere. Nedleggingen må stå kjølig og være helt tildekket i flere uker, og stuingen må vare lenge, minst en time, for syren må kokes ned før retten blir god å spise. Alt annet her er et spørsmål om hvilket fett du har, og hvor mye pepper du liker.</p>'},
  ingredients:[
    { group:{en:'For the ferment', no:'Til nedleggingen'}, items:[
      {q:1, u:'kg', n:{en:'white turnips', no:'hvite neper'}, note:{en:'firm, unwaxed and whole; turnips, not swedes', no:'faste, uvoksede og hele; neper, ikke kålrot'}},
      {q:2, u:'kg', n:{en:'red grape pomace', no:'pressrester fra røde druer'}, note:{en:'straight from the press at vintage, still moist; ask a winery', no:'rett fra pressen i innhøstingen, fortsatt fuktige; spør et vinhus'}},
    ]},
    { group:{en:'For the pan', no:'Til gryten'}, items:[
      {q:60, u:'g', n:{en:'smoked pancetta', no:'røkt pancetta'}, note:{en:'in small dice; lard alone is the older version', no:'i små terninger; bare smult er den eldre utgaven'}},
      {q:1, u:'', n:{en:'onion', no:'løk'}, note:{en:'sliced thin', no:'skåret i tynne skiver'}, round:'half'},
      {q:1, u:'', n:{en:'bay leaf', no:'laurbærblad'}, round:'half'},
      {q:300, u:'ml', n:{en:'light stock or water', no:'lys kraft eller vann'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
      {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
    ]},
    { group:{en:'To serve', no:'Til servering'}, items:[
      {q:600, u:'g', n:{en:'musetto', no:'musetto'}, note:{en:'or cotechino: a coarse raw pork sausage that has to be simmered', no:'eller cotechino, en grov rå svinepølse som må trekkes'}},
      {u:'', n:{en:'soft polenta', no:'myk polenta'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Wash the turnips and leave them whole and unpeeled. Trim the leaves off but do not cut into the crown: broken skin lets in the rot that the ferment is meant to keep out.',
     no:'Vask nepene, og la dem være hele og uskrelte. Skjær av bladene, men ikke ned i toppen, for skadet skall slipper inn den råten gjæringen skal holde ute.'},
    {en:'Pack them into a clean tub or crock and bury them completely in fresh grape marc, pressing it down so that no turnip anywhere touches air.',
     no:'Legg dem tett i et rent kar eller en krukke, og grav dem helt ned i ferske pressrester mens du presser massen sammen, slik at ingen nepe noe sted er i kontakt med luft.'},
    {en:'Weight the surface, cover the tub loosely so gas can escape, and leave it somewhere cool, around 10 to 15 °C, for at least a month and up to three.',
     no:'Legg et lodd på toppen, dekk karet løst til så gassen slipper ut, og sett det kjølig, rundt 10 til 15 °C, i minst en måned og opptil tre.'},
    {en:'Test one after four weeks: rinse it, cut it in half, and look at the cut face. It is ready when the flesh is translucent and pink right through and smells sour and winey rather than earthy.',
     no:'Prøv en etter fire uker. Skyll den, del den i to, og se på snittflaten. Den er klar når kjøttet er gjennomskinnelig og rosa helt inn og lukter syrlig og vinaktig framfor jordaktig.'},
    {en:'Rinse the turnips well under cold water, top and tail them, and grate them on the coarse side of a grater into long shreds.',
     no:'Skyll nepene godt under kaldt vann, skjær av topp og bunn, og riv dem på den grove siden av rivjernet til lange strimler.'},
    {en:'Squeeze the shreds lightly and taste one. If it makes you flinch, soak them briefly in cold water and squeeze them again; a second batch will teach you how long to ferment next time.',
     no:'Klem strimlene lett, og smak på en. Rykker du til, legger du dem kort i kaldt vann og klemmer dem en gang til. Neste omgang lærer deg hvor lenge de bør gjære.'},
    {en:'Render the diced pancetta in a wide pan over low heat until the fat runs clear, then add the onion and cook it until soft.',
     no:'Smelt fettet ut av pancettaterningene i en vid panne på svak varme til det renner klart, ha så i løken, og stek den myk.'},
    {en:'Add the brovada and the bay leaf and turn everything in the fat for a few minutes so every shred is coated.',
     no:'Ha i brovadaen og laurbærbladet, og vend alt i fettet i et par minutter, så hver strimmel er dekket.'},
    {en:'Pour in the stock, cover the pan, and stew over the lowest heat for an hour or more, adding a little water whenever it dries, until the shreds are tender and the pan is almost dry again.',
     no:'Hell i kraften, legg på lokk, og la det stue på svakest mulig varme i en time eller mer mens du sper med litt vann hver gang det tørker inn, til strimlene er møre og pannen igjen er nesten tørr.'},
    {en:'Meanwhile prick the musetto all over, cover it with cold water in a separate pan, bring it barely to a simmer and cook it gently for about two hours, or as long as the butcher tells you.',
     no:'Samtidig stikker du hull i musettoen over det hele, dekker den med kaldt vann i en egen kjele, lar det så vidt trekke, og koker den forsiktig i omtrent to timer, eller så lenge slakteren sier.'},
    {en:'Grind pepper over the brovada and taste it before you add any salt at all: the pancetta and the sausage bring a great deal with them.',
     no:'Kvern pepper over brovadaen, og smak på den før du salter i det hele tatt, for pancettaen og pølsen har med seg rikelig av det.'},
    {en:'Slice the musetto thickly, lay it on the brovada and serve it with soft polenta and a glass of Refosco.',
     no:'Skjær musettoen i tykke skiver, legg dem på brovadaen, og server med myk polenta og et glass Refosco.'},
  ],
  notes:[
    {title:{en:'A ferment, not a pickle', no:'En gjæring, ikke en sylting'},
     body:{en:'No vinegar goes anywhere near a brovada. The sourness is lactic acid produced by bacteria living on the grape skins, feeding on the sugar left in the marc, under a cover of spent pomace that keeps oxygen out. That is why it tastes of wine and why the pack has to stay covered and cool: warm it up or let air in and you get spoilage instead of acid.',
           no:'Det kommer ikke eddik i nærheten av en brovada. Syren er melkesyre. Bakteriene som lever på drueskallene, lager den av sukkeret som er igjen i massen, under et dekke av pressrester som holder oksygenet ute. Derfor smaker den av vin, og derfor må nedleggingen stå tildekket og kjølig. Blir det varmt, eller slipper det inn luft, får du råte i stedet for syre.'}},
    {title:{en:'Grate, do not slice', no:'Riv, ikke skjær'},
     body:{en:'Long shreds present far more surface to the fat and the stock, so they take on flavour and lose their sharpness in an hour, and they collapse into a soft tangle that holds the sausage. Slices keep their own shape and stay squeaky and sour however long they cook.',
           no:'Lange strimler vender mye mer overflate mot fettet og kraften, så de tar opp smak og mister skarpheten på en time, og de faller sammen til en myk floke som holder på pølsen. Skiver beholder formen sin og forblir seige og sure uansett hvor lenge de koker.'}},
    {title:{en:'Salt at the end, not the start', no:'Salt til slutt, ikke i starten'},
     body:{en:'Cured pork, the sausage broth and the ferment itself all carry salt, and an hour of stewing concentrates whatever is in the pan. Season only when the liquid has gone, when what you taste is what you will eat.',
           no:'Både speket svinekjøtt, kraften fra pølsen og selve gjæringen har salt i seg, og en times stuing konsentrerer alt som er i pannen. Smak til først når væsken er borte, for da smaker du på det du faktisk skal spise.'}},
  ],
  variations:[
    {title:{en:'If there is no winery nearby', no:'Hvis du ikke har et vinhus i nærheten'},
     body:{en:'Ferment the turnips in brine instead: peeled and quartered, submerged under a three per cent salt brine with a glass of red wine and a handful of dried grape skins, weighted down and left cool for a month. It is not brovada DOP and it comes out paler, but it is sour and winey and it stews into the same dish.',
           no:'Gjær nepene i lake i stedet. Skrell og del dem i båter, hold dem nede under en lake med tre prosent salt som du tilsetter et glass rødvin og en håndfull tørkede drueskall, legg på et lodd, og sett det kjølig i en måned. Det blir ikke brovada DOP, og fargen blir lysere, men den blir syrlig og vinaktig, og stuingen gir den samme retten.'}},
    {title:{en:'With smoked ribs', no:'Med røkt ribbe'},
     body:{en:'Lay a rack of smoked pork ribs on the brovada for the last half hour of the stew instead of boiling a sausage. The meat softens into the shreds and the smoke goes right through the pan, and the dish becomes a single pot rather than two.',
           no:'Legg et stykke røkt ribbe oppå brovadaen den siste halvtimen av stuingen i stedet for å koke en pølse. Kjøttet mykner ned i strimlene, og røyken går gjennom hele pannen, så retten blir én gryte i stedet for to.'}},
    {title:{en:'Brovada in the soup', no:'Brovada i suppen'},
     body:{en:'A handful of the grated ferment can go into a jota in place of the sauerkraut. It is sourer and sweeter at once, and it stains the broth pink.',
           no:'En håndfull av den revne nepen kan gå i en jota i stedet for den syrnede kålen. Den er syrligere og søtere på én gang, og den farger kraften rosa.'}},
  ],
},

{
  id:'gubana', dish:'Gubana', course:'dolce', lesson:3, serves:10, time:{prep:75, cook:50},
  hero:'gubana', tags:['baking','walnuts','yeast','grappa'],
  title:{en:'Gubana', no:'Gubana'},
  blurb:{en:'A rope of enriched yeast dough rolled around walnuts, raisins, pine nuts and grappa, then coiled into a snail so every slice cuts through a dozen turns.',
         no:'Et langt tau av søt gjærdeig rulles rundt valnøtter, rosiner, pinjekjerner og grappa og snurres til en snegle, slik at hver skive skjærer gjennom et dusin lag.'},
  heroCaption:{en:'Gubana from the Natisone valleys, cut to show the spiral of dough and nut filling.',
               no:'Gubana fra Natisone-dalene, skåret opp så spiralen av deig og nøttefyll kommer fram.'},
  wines:['Picolit'],
  headnote:{
    en:'<p>The sweet things of Friuli come from the Slovene border, and the gubana comes from the Natisone valleys above Cividale: a spiral of yeast dough rolled around walnuts, raisins, pine nuts and grappa. Trieste’s strucolo, its strudel, is the other one. A gubana is baked for Easter, for Christmas and for weddings, and it keeps for a week, which is part of the point.</p>'
      + '<p>It is two things at once. The dough is enriched with butter, egg and sugar and behaves like a brioche, but it is rolled out paper-thin and treated like a pastry, so the finished cake is bread by structure and pastry by section. A gubana is judged on how many turns a slice shows, and every extra millimetre of dough is one turn fewer.</p>'
      + '<p>The filling has to be wet enough to stay moist through nearly an hour in the oven and dry enough not to soak the dough it sits on. Breadcrumbs or crushed dry biscuits hold the balance, and the grappa is not decoration: alcohol carries aromatic compounds that water leaves behind, and it keeps the raisins plump instead of letting them scorch.</p>',
    no:'<p>Det søte i Friuli kommer fra grensen mot Slovenia, og gubanaen kommer fra Natisone-dalene ovenfor Cividale. Den er en spiral av gjærdeig som er rullet rundt valnøtter, rosiner, pinjekjerner og grappa. Strucolo, strudelen fra Trieste, er den andre. En gubana bakes til påske, til jul og til bryllup, og den holder seg i en uke, noe som er en del av poenget.</p>'
      + '<p>Den er to ting på én gang. Deigen er beriket med smør, egg og sukker og oppfører seg som en brioche, men den kjevles papirtynn og behandles som butterdeig, så den ferdige kaken er brød i oppbygning og bakverk i snitt. En gubana bedømmes etter hvor mange omdreininger en skive viser, og hver ekstra millimeter deig er én omdreining mindre.</p>'
      + '<p>Fyllet må være vått nok til å holde seg saftig gjennom nesten en time i ovnen, og tørt nok til ikke å bløte opp deigen det ligger på. Griljermel eller knuste tørre kjeks holder den balansen, og grappaen er ingen pynt. Alkohol bærer aromastoffer som vann lar ligge, og den holder rosinene fyldige i stedet for å la dem svi seg.</p>'},
  ingredients:[
    { group:{en:'For the dough', no:'Til deigen'}, items:[
      {q:400, u:'g', n:{en:'strong white flour', no:'hvetemel'}, note:{en:'a flour with a high protein content holds the spiral', no:'et mel med høyt proteininnhold holder på spiralen'}},
      {q:100, u:'ml', n:{en:'whole milk', no:'helmelk'}, note:{en:'warmed to blood heat', no:'varmet til kroppstemperatur'}},
      {q:15, u:'g', n:{en:'fresh yeast', no:'fersk gjær'}, note:{en:'or a third of the weight in dried yeast', no:'eller en tredel av vekten i tørrgjær'}},
      {q:60, u:'g', n:{en:'sugar', no:'sukker'}},
      {q:100, u:'g', n:{en:'butter', no:'smør'}, note:{en:'soft, in pieces', no:'romtemperert, i biter'}},
      {q:2, u:'', n:{en:'egg yolks', no:'eggeplommer'}, round:'half'},
      {q:1, u:'', n:{en:'egg', no:'egg'}, round:'half'},
      {q:1, u:'', n:{en:'lemon', no:'sitron'}, note:{en:'the zest only', no:'bare det revne skallet'}, round:'half'},
      {q:5, u:'g', n:{en:'salt', no:'salt'}},
    ]},
    { group:{en:'For the filling', no:'Til fyllet'}, items:[
      {q:250, u:'g', n:{en:'walnuts', no:'valnøtter'}, note:{en:'chopped by hand to gravel, never ground to powder', no:'hakket for hånd til grus, aldri malt til pulver'}},
      {q:60, u:'g', n:{en:'pine nuts', no:'pinjekjerner'}},
      {q:100, u:'g', n:{en:'raisins', no:'rosiner'}},
      {q:60, u:'ml', n:{en:'grappa', no:'grappa'}, note:{en:'for soaking the raisins', no:'til å bløtlegge rosinene i'}},
      {q:80, u:'g', n:{en:'sugar', no:'sukker'}},
      {q:50, u:'g', n:{en:'dry breadcrumbs', no:'griljermel'}, note:{en:'or crushed dry biscuits', no:'eller knuste tørre kjeks'}},
      {q:50, u:'g', n:{en:'butter', no:'smør'}, note:{en:'melted', no:'smeltet'}},
      {q:40, u:'g', n:{en:'candied orange peel', no:'sukret appelsinskall'}, note:{en:'finely chopped', no:'finhakket'}},
      {q:1, u:'', n:{en:'egg white', no:'eggehvite'}, round:'half'},
      {q:3, u:'g', n:{en:'ground cinnamon', no:'malt kanel'}},
      {q:1, u:'', n:{en:'orange', no:'appelsin'}, note:{en:'the zest only', no:'bare det revne skallet'}, round:'half'},
    ]},
    { group:{en:'To finish', no:'Til pensling'}, items:[
      {q:1, u:'', n:{en:'egg', no:'egg'}, note:{en:'beaten, for the glaze', no:'sammenvispet, til pensling'}, round:'half'},
      {q:20, u:'g', n:{en:'sugar', no:'sukker'}, note:{en:'coarse, for scattering', no:'perlesukker eller grovt sukker, til å strø over'}},
    ]},
  ],
  steps:[
    {en:'Warm the milk to blood heat, crumble the yeast into it with a spoonful of the sugar, and leave it for ten minutes until it foams.',
     no:'Varm melken til kroppstemperatur, smuldre gjæren opp i den sammen med en skje av sukkeret, og la det stå i ti minutter til det skummer.'},
    {en:'Mix the flour with the rest of the sugar, the salt and the lemon zest, then work in the yeast milk, the yolks and the whole egg to a shaggy dough.',
     no:'Bland melet med resten av sukkeret, saltet og det revne sitronskallet, og arbeid så inn gjærmelken, eggeplommene og det hele egget til en grov deig.'},
    {en:'Knead until it is smooth and elastic, then add the soft butter a piece at a time, kneading each piece in fully before the next goes in, until the dough is glossy and pulls away from the bowl.',
     no:'Elt den glatt og elastisk, og tilsett så det romtempererte smøret bit for bit mens du elter hver bit helt inn før den neste går i, til deigen er blank og slipper bollen.'},
    {en:'Cover the bowl and let the dough rise until doubled, an hour and a half to two hours, then chill it for half an hour so it rolls without springing back.',
     no:'Dekk bollen til, og la deigen heve til dobbel størrelse, halvannen til to timer. Sett den så kaldt i en halvtime, så den lar seg kjevle uten å trekke seg sammen igjen.'},
    {en:'Soak the raisins in the grappa while the dough rises, and chop the walnuts by hand to gravel. Chunks are what a slice of gubana should show; a food processor turns them to oily paste.',
     no:'Bløtlegg rosinene i grappaen mens deigen hever, og hakk valnøttene for hånd til grus. En skive gubana skal vise fram biter og ikke pulver, mens en kjøkkenmaskin gjør nøttene til en oljete masse.'},
    {en:'Mix the walnuts and pine nuts with the raisins and their grappa, the sugar, breadcrumbs, cinnamon, orange zest, candied peel, melted butter and the egg white into a moist, spreadable paste.',
     no:'Bland valnøttene og pinjekjernene med rosinene og grappaen deres, sukkeret, griljermelet, kanelen, det revne appelsinskallet, det sukrede appelsinskallet, det smeltede smøret og eggehviten til en fuktig masse som lar seg bre utover.'},
    {en:'Roll the dough out on a floured cloth into a long rectangle as thin as you dare, two to three millimetres. Work from the middle outwards and let it rest a minute if it fights you.',
     no:'Kjevle deigen ut på et melet klede til et langt rektangel, så tynt du tør, to til tre millimeter. Arbeid fra midten og utover, og la den hvile et minutt hvis den setter seg imot.'},
    {en:'Spread the filling over the sheet in an even layer, leaving a clear border along the far long edge so the roll can seal.',
     no:'Bre fyllet jevnt utover deigen, men la det stå en ren stripe langs den bortre langsiden, slik at rullen kan lukke seg.'},
    {en:'Roll the sheet up from the near long edge into a tight rope, using the cloth to lift it, and pinch the seam closed.',
     no:'Rull deigen sammen fra den nærmeste langsiden til et stramt tau mens du bruker kledet til å løfte med, og klyp sømmen igjen.'},
    {en:'Coil the rope into a spiral in a buttered round tin about 24 cm across, tuck the end underneath, cover it and let it prove until puffy, about forty-five minutes.',
     no:'Snurr tauet til en spiral i en smurt rund form på rundt 24 cm, brett enden inn under, dekk den til, og la den etterheve til den er luftig, omtrent førtifem minutter.'},
    {en:'Brush it with beaten egg, scatter sugar over it and bake at 180 °C for forty-five to fifty minutes, laying foil over the top if it colours too fast. Push a skewer into the dough: it should come out dry.',
     no:'Pensle den med sammenvispet egg, strø sukker over, og stek den ved 180 °C i førtifem til femti minutter. Legg folie over hvis den får for mye farge. Stikk en pinne ned i deigen, og den skal komme tørr opp.'},
    {en:'Let it cool completely in the tin before you cut it. Warm gubana tears along the spiral, and the grappa only comes up in the nose once the cake is cold.',
     no:'La den kjøle seg helt ned i formen før du skjærer i den. Varm gubana revner langs spiralen, og grappaen kommer først fram i duften når kaken er kald.'},
  ],
  notes:[
    {title:{en:'Thin dough, many turns', no:'Tynn deig, mange omdreininger'},
     body:{en:'A gubana is read in cross-section, and the number of alternating bands of dough and filling is the whole aesthetic. Rolling twice as thin doubles them without changing a single quantity, which is why the rolling, not the recipe, is where the skill sits.',
           no:'En gubana leses i snitt, og antallet vekslende bånd av deig og fyll er hele estetikken. Kjevler du den dobbelt så tynt, dobler du dem uten å endre en eneste mengde, og derfor ligger håndverket i kjevlingen og ikke i oppskriften.'}},
    {title:{en:'What the breadcrumbs are for', no:'Hva griljermelet gjør'},
     body:{en:'Chopped nuts release oil and the raisins release syrup, and both would run out of the roll and fry the base of the cake. Dry crumbs absorb them and hold the filling where it was put, so the layer stays a layer instead of becoming a puddle at the bottom of the tin.',
           no:'Hakkede nøtter gir fra seg olje, og rosinene gir fra seg sirup, og begge deler ville rent ut av rullen og stekt bunnen av kaken. Tørt griljermel suger det opp og holder fyllet der det ble lagt, så laget blir liggende som et lag i stedet for som en pøl i bunnen av formen.'}},
    {title:{en:'Grappa does more than flavour', no:'Grappaen gjør mer enn å smake'},
     body:{en:'Alcohol dissolves aromatic compounds that water cannot reach, so a raisin soaked in grappa carries scent into the middle of the roll rather than sitting on the surface. It also keeps the fruit soft: a dry raisin at the edge of a slice burns before the dough is baked through.',
           no:'Alkohol løser opp aromastoffer som vann ikke når fram til, så en rosin som har ligget i grappa, bærer duft inn i midten av rullen framfor å legge seg på overflaten. Den holder også frukten myk, for en tørr rosin ytterst i en skive svir seg lenge før deigen er gjennomstekt.'}},
  ],
  variations:[
    {title:{en:'Strucolo, the Trieste cousin', no:'Strucolo, fetteren fra Trieste'},
     body:{en:'Trieste makes the strudel version of the same idea: the same sort of nut and fruit filling in a thin unleavened pastry, rolled into a log rather than coiled into a snail, and baked straight rather than in a tin. It is lighter, quicker and eats better on the day it is made.',
           no:'Trieste lager strudelutgaven av den samme ideen. Der legges et lignende fyll av nøtter og frukt i en tynn deig uten gjær, som rulles til en stokk i stedet for å snurres til en snegle, og som stekes rett på stekeplaten. Den er lettere, går raskere og smaker best samme dag.'}},
    {title:{en:'A quicker gubana', no:'En raskere gubana'},
     body:{en:'The same filling wrapped in bought puff pastry and baked as a coil gives you a cake in an afternoon. The section is flakier and shows fewer turns, and it goes stale in a day or two rather than keeping for a week.',
           no:'Ruller du det samme fyllet inn i ferdig butterdeig og steker det som en spiral, har du en kake i løpet av en ettermiddag. Snittet blir mer flakete og viser færre omdreininger, og den blir tørr etter et døgn eller to i stedet for å holde seg i en uke.'}},
    {title:{en:'What else goes in the filling', no:'Hva mer som kan gå i fyllet'},
     body:{en:'Households add dried figs, prunes, a spoonful of honey, a little cocoa or a splash of rum in place of some of the grappa. Keep walnuts as the clear majority of the nuts and the rest is open; they are what makes the filling taste of these valleys.',
           no:'Noen husholdninger har i tørkede fikener, svisker, en skje honning, litt kakao eller en skvett rom i stedet for noe av grappaen. Hold valnøttene som det klare flertallet av nøttene, så er resten åpent. Valnøttene gir fyllet smaken av disse dalene.'}},
  ],
},

];
