// Lazio recipes. Bilingual in one file: the quantities are written once so English and Norwegian
// cannot drift apart. Contract: docs/recipe-format.md. Checked by tools/recipecheck.py. Never narrated.
// Everything here follows the Lazio food reading (content/lazio.js, lesson 3): guanciale, Pecorino
// Romano and black pepper are the three constants, the sauce is an emulsion of rendered fat, starchy
// water and cheese, and the cheese goes in off the heat.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-62'] = [

{
  id:'gricia', dish:'Gricia', course:'primo', lesson:3, serves:4, time:{prep:10, cook:20},
  hero:'gricia', tags:['pasta','guanciale'],
  title:{en:'Gricia', no:'Gricia'},
  blurb:{en:'The mother of the four Roman pastas: guanciale, pecorino and pepper, and nothing else. Learn this one and the other three follow.',
         no:'Moren til de fire romerske pastarettene: guanciale, pecorino og pepper, og ingenting annet. Lærer du denne, følger de tre andre av seg selv.'},
  heroCaption:{en:'Gricia, sometimes called amatriciana bianca: the same dish as it was before tomatoes arrived.',
               no:'Gricia kalles iblant amatriciana bianca. Det er den samme retten, slik den var før tomatene kom.'},
  wines:['Frascati Superiore'],
  headnote:{
    en:'<p>Gricia is the oldest of the four Roman pastas and the one to cook first, because everything the other three need is already in it: guanciale rendered slowly, sheep’s cheese, cracked pepper, and enough starchy water to hold them together. Take the pork away and you have cacio e pepe. Add tomato and you have amatriciana. Add egg and you have carbonara.</p>'
      + '<p>Where the name comes from is argued over. Some derive it from <strong>Grisciano</strong>, a hamlet a few kilometres from Amatrice; others from the <em>gricio</em>, the old Roman word for the bread and grocery sellers who came down from the Swiss Grisons. It is also called <em>amatriciana bianca</em>, white amatriciana, which is the most useful description of all: the same dish as it was before tomatoes reached the mountains.</p>'
      + '<p>There is nothing to hide behind here. Three ingredients and one technique, and the whole thing stands or falls on two things — how slowly the fat comes out of the guanciale, and how cool the pan is when the cheese goes in.</p>',
    no:'<p>Gricia er den eldste av de fire romerske pastarettene, og den man bør lage først, for alt de tre andre trenger, ligger allerede i den: guanciale som er smeltet sakte, saueost, knust pepper og nok stivelsesrikt vann til å holde det sammen. Tar du bort svinekjøttet, har du cacio e pepe. Tilsetter du tomat, har du amatriciana. Tilsetter du egg, har du carbonara.</p>'
      + '<p>Hvor navnet kommer fra, krangles det om. Noen utleder det fra <strong>Grisciano</strong>, en grend noen kilometer fra Amatrice, andre fra <em>gricio</em>, det gamle romerske ordet for brød- og kolonialhandlerne som kom ned fra sveitsiske Graubünden. Den kalles også <em>amatriciana bianca</em>, hvit amatriciana, og det er den mest opplysende beskrivelsen: den samme retten slik den var før tomatene nådde fjellene.</p>'
      + '<p>Her er det ingenting å gjemme seg bak. Tre ingredienser og én teknikk, og alt avhenger av to ting — hvor sakte fettet kommer ut av guancialen, og hvor kald pannen er når osten går i.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:400, u:'g', n:{en:'rigatoni or mezze maniche', no:'rigatoni eller mezze maniche'}, note:{en:'spaghetti does the job too', no:'spaghetti gjør også nytten'}},
    {q:200, u:'g', n:{en:'guanciale', no:'guanciale'}, note:{en:'cured pork jowl, bought in one piece and cut at home', no:'speket svinekjake, kjøpt i ett stykke og skåret hjemme'}},
    {q:80,  u:'g', n:{en:'Pecorino Romano', no:'Pecorino Romano'}, note:{en:'finely grated, at room temperature', no:'finrevet, med romtemperatur'}},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, note:{en:'whole corns, cracked coarsely, a generous amount', no:'hele korn, grovknust, rikelig'}, scale:'none'},
    {q:3, u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:15, u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
  ]}],
  steps:[
    {en:'Bring the water to the boil and salt it lightly. Pecorino Romano is salted hard and seasons the dish on its own, so use less salt than you would for a tomato sauce.',
     no:'Kok opp vannet og salt det lett. Pecorino Romano er kraftig saltet og krydrer retten alene, så bruk mindre salt enn du ville gjort til en tomatsaus.'},
    {en:'Cut the guanciale into batons about 6 mm thick, leaving the fat on. It is the fat you are after; the meat is almost a garnish.',
     no:'Skjær guancialen i staver på rundt 6 mm, og la fettet sitte på. Det er fettet du er ute etter, og kjøttet er nesten bare pynt.'},
    {en:'Put the batons in a wide, dry pan while it is still cold and set it over the lowest heat you have. They should sigh rather than sizzle.',
     no:'Legg stavene i en vid, tørr panne mens den fortsatt er kald, og sett den på den svakeste varmen du har. De skal sukke, ikke frese.'},
    {en:'Let the fat render for 8 to 10 minutes, until it runs clear and the batons are golden at the edges but still soft in the middle. Lift them out with a slotted spoon and leave every drop of the fat in the pan.',
     no:'La fettet smelte ut i 8 til 10 minutter, til det er klart og stavene er gylne i kantene, men fortsatt myke i midten. Løft dem ut med hullsleiv, og la hver dråpe av fettet bli igjen i pannen.'},
    {en:'Crack the peppercorns coarsely and toast them in the warm fat for half a minute, until the kitchen smells of them.',
     no:'Knus pepperkornene grovt, og rist dem i det varme fettet i et halvt minutt, til hele kjøkkenet lukter av dem.'},
    {en:'Cook the pasta and drain it two minutes before the packet says. Keep some of the cooking water; you will need more of it than you expect.',
     no:'Kok pastaen, og hell av vannet to minutter før pakken sier. Ta vare på noe av kokevannet; du trenger mer av det enn du tror.'},
    {en:'Turn the heat to medium under the fat, add the pasta and a ladle of the water, and toss for a minute or two until the liquid thickens and coats every piece.',
     no:'Skru opp til middels varme under fettet, ha i pastaen og en øse med kokevann, og vend det i et par minutter til væsken tykner og legger seg rundt hver bit.'},
    {en:'Take the pan off the heat and let it stand for half a minute. Then add the pecorino, tossing hard, and loosen with cooking water a spoonful at a time until the sauce turns glossy and runs.',
     no:'Ta pannen av platen og la den stå et halvt minutt. Ha så i pecorinoen mens du vender kraftig, og spe med kokevann en skje om gangen til sausen blir blank og renner.'},
    {en:'Return the guanciale, toss once more and serve straight away, with more pepper on top.',
     no:'Ha guancialen tilbake, vend én gang til, og server med en gang, med mer pepper på toppen.'},
  ],
  notes:[
    {title:{en:'Start the pan cold', no:'Start med kald panne'},
     body:{en:'Guanciale is fattier than pancetta and its fat is the base of the sauce. A cold pan and low heat melt that fat out clear and sweet; a hot pan fries the outside, seals the piece and locks the rest in. Ten patient minutes here decide the dish.',
           no:'Guanciale er fetere enn pancetta, og fettet er selve grunnlaget for sausen. Kald panne og svak varme smelter fettet ut klart og søtt, mens en varm panne steker overflaten, forsegler stykket og låser resten inne. Ti tålmodige minutter her avgjør hele retten.'}},
    {title:{en:'The cheese goes in off the heat', no:'Osten skal i med kjelen av platen'},
     body:{en:'Pecorino above roughly 65 °C tightens into rubbery threads instead of going into the starchy water. Everything else can be hot; the moment the cheese arrives, the pan must be off the flame and have stood for a few seconds.',
           no:'Over omtrent 65 °C trekker pecorinoen seg sammen til gummiaktige tråder i stedet for å gå opp i det stivelsesrike vannet. Alt annet kan være varmt, men i det øyeblikket osten kommer i, må kjelen være av platen og ha stått noen sekunder.'}},
  ],
  variations:[
    {title:{en:'The shape of the pasta', no:'Pastaformen'},
     body:{en:'Rigatoni and mezze maniche are the usual Roman choice, because the ridges and the hollow hold a sauce this thin. Spaghetti is perfectly orthodox and is what most photographs of the dish show.',
           no:'Rigatoni og mezze maniche er det vanlige romerske valget, fordi rillene og hulrommet holder på en saus som er så tynn. Spaghetti er fullt ut ortodoks, og det er den de fleste bildene av retten viser.'}},
    {title:{en:'A splash of wine', no:'En skvett vin'},
     body:{en:'Some Roman cooks deglaze the rendered fat with a little dry white wine and let it evaporate before the pasta goes in. It sharpens the dish and moves it a step towards amatriciana; purists leave it out.',
           no:'Noen romerske kokker koker ut det smeltede fettet med litt tørr hvitvin og lar den fordampe før pastaen går i. Det skjerper retten og flytter den et hakk mot amatriciana, men puristene lar det være.'}},
    {title:{en:'If you cannot find guanciale', no:'Hvis du ikke får tak i guanciale'},
     body:{en:'Pancetta is the least bad substitute: belly rather than jowl, leaner and milder, so use a little more and render it just as slowly. Bacon is smoked, and smoke is not part of this dish.',
           no:'Pancetta er den minst dårlige erstatningen. Den er sideflesk og ikke kjake, magrere og mildere, så bruk litt mer og smelt fettet like sakte ut. Bacon er røkt, og røyk hører ikke hjemme i denne retten.'}},
  ],
},

{
  id:'cacio-e-pepe', dish:'Cacio e pepe', course:'primo', lesson:3, serves:4, time:{prep:5, cook:15},
  hero:'cacio', tags:['pasta','vegetarian'],
  title:{en:'Cacio e pepe', no:'Cacio e pepe'},
  blurb:{en:'Cheese and pepper, and famously easy to get wrong. The secret is starch, and keeping the pan off the heat.',
         no:'Ost og pepper, og notorisk lett å mislykkes med. Hemmeligheten er stivelse, og at kjelen må være av platen.'},
  heroCaption:{en:'When it goes right the pecorino and the pasta water form a cream without any cream.',
               no:'Når det lykkes, danner pecorinoen og pastavannet en krem uten fløte.'},
  wines:['Frascati Superiore'],
  headnote:{
    en:'<p>Two ingredients and no fat to hide behind, which is why cacio e pepe has a reputation it deserves. What binds it is not butter or cream but starch: pasta water carries enough dissolved starch to hold grated cheese in a smooth emulsion, and the less water you boil the pasta in, the more of it you have. Roman cooks use a pot that looks too small.</p>'
      + '<p>The cheese is not a detail. <strong>Pecorino Romano</strong> is sheep’s milk, salted hard and aged at least five months, sharp enough to season a dish on its own. Despite the name, most of it is now made in Sardinia, which the DOP allows alongside Lazio and the province of Grosseto. Parmigiano is cow’s milk, sweeter and softer, and it turns this into something else.</p>'
      + '<p>There are exactly two ways to fail. Too hot, and the cheese seizes into rubbery clumps. Too little water, and it stays grainy and never comes together. Everything below is arranged to keep you away from both.</p>',
    no:'<p>To ingredienser og ikke noe fett å gjemme seg bak, og derfor har cacio e pepe et rykte den fortjener. Den bindes verken av smør eller fløte, men av stivelse: pastavann inneholder nok oppløst stivelse til å holde revet ost i en jevn emulsjon, og jo mindre vann du koker pastaen i, jo mer av den får du. Romerske kokker bruker en kjele som ser altfor liten ut.</p>'
      + '<p>Osten er ingen detalj. <strong>Pecorino Romano</strong> er laget av sauemelk, kraftig saltet og lagret i minst fem måneder, skarp nok til å krydre en rett alene. Til tross for navnet lages det meste av den nå på Sardinia, som DOP-en tillater sammen med Lazio og provinsen Grosseto. Parmigiano er kumelk, søtere og mykere, og gjør dette til en annen rett.</p>'
      + '<p>Det finnes nøyaktig to måter å mislykkes på. For varmt, og osten klumper seg til gummi. For lite vann, og den forblir kornete og går aldri sammen. Alt nedenfor er lagt opp for å holde deg unna begge.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:400, u:'g', n:{en:'tonnarelli', no:'tonnarelli'}, note:{en:'square-cut fresh egg spaghetti; dried spaghetti also works', no:'firkantskåret fersk eggspaghetti; tørket spaghetti går også'}},
    {q:200, u:'g', n:{en:'Pecorino Romano', no:'Pecorino Romano'}, note:{en:'grated as finely as you can, at room temperature', no:'revet så fint du klarer, med romtemperatur'}},
    {q:6,   u:'g', n:{en:'black peppercorns', no:'sorte pepperkorn'}},
    {q:2,   u:'l', n:{en:'water', no:'vann'}, note:{en:'a small pot: less water, more starch', no:'liten kjele: mindre vann, mer stivelse'}, scale:'sub'},
    {q:8,   u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
  ]}],
  steps:[
    {en:'Grate the pecorino as finely as you can and leave it out of the fridge. Cold cheese in coarse shreds is the commonest reason the sauce goes grainy.',
     no:'Riv pecorinoen så fint du klarer, og la den stå framme. Kald ost i grove strimler er den vanligste grunnen til at sausen blir kornete.'},
    {en:'Crack the peppercorns coarsely in a mortar or with the base of a heavy pan. Ready-ground pepper has lost the oils that carry the flavour.',
     no:'Knus pepperkornene grovt i morter eller med bunnen av en tung panne. Ferdigmalt pepper har mistet oljene som bærer smaken.'},
    {en:'Boil the pasta in as little water as will just cover it, lightly salted. The less water, the more starch dissolves into it, and the starch is what binds the sauce.',
     no:'Kok pastaen i så lite vann at det akkurat dekker den, lett saltet. Jo mindre vann, desto mer stivelse løser seg i det, og stivelsen er det som binder sausen.'},
    {en:'Toast the pepper in a dry wide pan over medium heat for half a minute, until it smells. Add a ladle of the pasta water and let it bubble down to a syrupy film.',
     no:'Rist pepperen i en tørr, vid panne på middels varme i et halvt minutt, til den dufter. Ha i en øse med pastavann, og la det koke inn til en sirupsaktig hinne.'},
    {en:'In a bowl, work the grated cheese with lukewarm pasta water, a spoonful at a time, into a thick smooth paste with no lumps left. Lukewarm, not hot: hot water seizes the cheese here just as it would in the pan.',
     no:'Rør den revne osten sammen med lunkent pastavann i en bolle, en skje om gangen, til en tykk og jevn masse uten klumper. Lunkent, ikke varmt: varmt vann får osten til å klumpe seg her like lett som i pannen.'},
    {en:'Drain the pasta a minute before al dente and finish it in the peppered pan with a little more water, tossing until it is coated.',
     no:'Hell av pastaen ett minutt før den er al dente, og la den bli ferdig i pepperpannen med litt mer vann mens du vender til den er dekket.'},
    {en:'Take the pan off the heat and count to thirty. This pause is the whole recipe.',
     no:'Ta pannen av platen og tell til tretti. Denne pausen er hele oppskriften.'},
    {en:'Add the cheese paste and toss until every strand turns glossy. Loosen with cooking water whenever it tightens, and serve immediately; it stiffens on the plate.',
     no:'Ha i ostemassen og vend til hver tråd blir blank. Spe med kokevann hver gang den strammer seg, og server med en gang, for den stivner på tallerkenen.'},
  ],
  notes:[
    {title:{en:'Starch, not cream', no:'Stivelse, ikke fløte'},
     body:{en:'Pasta water from a small pot carries enough dissolved starch to hold fat and cheese in a smooth emulsion. That is the entire sauce. Cream is not a shortcut to it; it is a different dish wearing the same name.',
           no:'Pastavann fra en liten kjele inneholder nok oppløst stivelse til å holde fett og ost i en jevn emulsjon. Det er hele sausen. Fløte er ingen snarvei dit, men en annen rett med samme navn.'}},
    {title:{en:'What went wrong', no:'Hva som gikk galt'},
     body:{en:'Rubbery threads mean the pan was too hot when the cheese went in — start again with the pan off the heat for longer. Grainy and thin means too little starch: next time use a smaller pot, and meanwhile add hot pasta water a spoonful at a time and keep tossing.',
           no:'Gummiaktige tråder betyr at pannen var for varm da osten kom i; prøv igjen med pannen lenger av platen. Kornete og tynn betyr for lite stivelse: bruk en mindre kjele neste gang, og ha i mellomtiden i varmt pastavann en skje om gangen mens du fortsetter å vende.'}},
  ],
  variations:[
    {title:{en:'Tonnarelli or spaghetti', no:'Tonnarelli eller spaghetti'},
     body:{en:'Tonnarelli is the traditional shape: fresh egg pasta cut square, with a rough surface that holds the sauce. Dried spaghetti works and gives starchier water, which is a real advantage for a beginner.',
           no:'Tonnarelli er den tradisjonelle formen: fersk eggpasta skåret firkantet, med en ru overflate som holder på sausen. Tørket spaghetti fungerer og gir mer stivelsesrikt vann, noe som er en reell fordel for en nybegynner.'}},
    {title:{en:'The bowl or the pan', no:'Bollen eller pannen'},
     body:{en:'The paste made in a bowl, as here, is the safe method. Confident cooks build the emulsion straight in the pan by adding cheese and water alternately off the heat. There is less to wash up and much more to go wrong.',
           no:'Massen som røres i en bolle, slik det gjøres her, er den trygge metoden. Erfarne kokker bygger emulsjonen rett i pannen ved å ha i ost og vann annenhver gang, med pannen av platen. Det blir mindre oppvask og langt mer som kan gå galt.'}},
  ],
},

{
  id:'amatriciana', dish:'Amatriciana', course:'primo', lesson:3, serves:4, time:{prep:10, cook:30},
  hero:'amatriciana', tags:['pasta','guanciale','tomato'],
  title:{en:"Bucatini all'amatriciana", no:"Bucatini all'amatriciana"},
  blurb:{en:'Gricia with tomato in it. The town of Amatrice wrote the recipe down and left out the onion and the garlic; so does this one.',
         no:'Gricia med tomat i tillegg. Byen Amatrice skrev ned oppskriften og utelot løk og hvitløk, og det gjør denne også.'},
  heroCaption:{en:'Bucatini is the Roman shape for it; in Amatrice itself they use spaghetti.',
               no:'Bucatini er den romerske formen til retten; i selve Amatrice bruker de spaghetti.'},
  wines:['Cesanese del Piglio'],
  headnote:{
    en:'<p>Amatriciana is gricia with tomato in it, and unlike the other three it has a hometown. <strong>Amatrice</strong> sits in the north-east corner of Lazio, high in the mountains, and belonged to Abruzzo until 1927; the shepherds who made the white version carried guanciale and pecorino because both keep. Tomatoes reached the dish in the eighteenth or nineteenth century and never left.</p>'
      + '<p>The town has an official recipe, and it is short: guanciale, pecorino, tomato, a splash of dry white wine, a little chilli. It excludes onion and garlic in so many words. Roman restaurants add onion anyway and the town does not forgive them. In 2020 the European Union registered <em>Amatriciana tradizionale</em> as a Traditional Speciality Guaranteed, the first pasta sauce ever protected that way.</p>'
      + '<p>The dish carries some weight now. After the earthquake that destroyed Amatrice in 2016, restaurants across Italy and beyond put it on their menus and sent the money north. Cooking it properly is a small courtesy to a town that lost almost everything.</p>',
    no:'<p>Amatriciana er gricia med tomat i, og til forskjell fra de tre andre har den en hjemby. <strong>Amatrice</strong> ligger i det nordøstlige hjørnet av Lazio, høyt i fjellene, og tilhørte Abruzzo fram til 1927. Gjeterne som laget den hvite versjonen, bar med seg guanciale og pecorino fordi begge deler holder seg. Tomatene kom til retten på 1700- eller 1800-tallet og ble værende.</p>'
      + '<p>Byen har en offisiell oppskrift, og den er kort: guanciale, pecorino, tomat, en skvett tørr hvitvin og litt chili. Den utelukker løk og hvitløk med rene ord. Romerske restauranter har løk i likevel, og byen tilgir dem ikke. I 2020 registrerte EU <em>Amatriciana tradizionale</em> som garantert tradisjonell spesialitet, den første pastasausen som noen gang har fått den beskyttelsen.</p>'
      + '<p>Retten bærer et alvor i dag. Etter jordskjelvet som ødela Amatrice i 2016, satte restauranter over hele Italia og utenfor den på menyen og sendte pengene nordover. Å lage den riktig er en liten høflighet mot en by som mistet nesten alt.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:400, u:'g', n:{en:'bucatini', no:'bucatini'}, note:{en:'or spaghetti, as in Amatrice', no:'eller spaghetti, som i Amatrice'}},
    {q:150, u:'g', n:{en:'guanciale', no:'guanciale'}, note:{en:'in batons about 1 cm', no:'i staver på rundt 1 cm'}},
    {q:400, u:'g', n:{en:'peeled plum tomatoes', no:'hermetiske plommetomater'}, note:{en:'San Marzano if you can find them; crush them with your hands', no:'San Marzano hvis du får tak i dem; mos dem med hendene'}},
    {q:50,  u:'ml', n:{en:'dry white wine', no:'tørr hvitvin'}},
    {q:1,   u:'', n:{en:'small dried chilli', no:'liten tørket chili'}, round:'half'},
    {q:80,  u:'g', n:{en:'Pecorino Romano', no:'Pecorino Romano'}, note:{en:'finely grated', no:'finrevet'}},
    {q:3,   u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:15,  u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
  ]}],
  steps:[
    {en:'Cut the guanciale into batons about 1 cm thick — heavier than for gricia, because they have to survive a wet sauce.',
     no:'Skjær guancialen i staver på rundt 1 cm, altså grovere enn til gricia, siden de skal tåle en våt saus.'},
    {en:'Render them in a cold, dry pan over low heat for 8 to 10 minutes, until the fat runs clear and the edges colour.',
     no:'Smelt fettet ut av dem i en kald, tørr panne på svak varme i 8 til 10 minutter, til fettet er klart og kantene får farge.'},
    {en:'Pour in the wine and let it evaporate, scraping the bottom of the pan as it goes.',
     no:'Hell i vinen og la den fordampe mens du skraper bunnen av pannen.'},
    {en:'Lift the guanciale out and set it aside. Left in the sauce it goes soft and leathery, and its job is already done.',
     no:'Løft ut guancialen og sett den til side. Blir den liggende i sausen, blir den myk og seig, og jobben er allerede gjort.'},
    {en:'Crush the tomatoes into the fat with your hands, drop in the chilli whole, and simmer over low heat for about 15 minutes, until the sauce darkens and the fat separates out at the edges.',
     no:'Mos tomatene ned i fettet med hendene, legg chilien i hel, og la sausen småkoke på svak varme i omtrent 15 minutter, til den mørkner og fettet skiller seg ut i kantene.'},
    {en:'Meanwhile boil the bucatini and drain it a minute before al dente, keeping some of the water.',
     no:'Kok imens bucatinien, og hell av vannet ett minutt før den er al dente. Ta vare på noe av kokevannet.'},
    {en:'Fish out the chilli, return the guanciale to the pan, add the pasta and toss over the heat for a minute, loosening with pasta water.',
     no:'Fisk ut chilien, ha guancialen tilbake i pannen, tilsett pastaen og vend det over varmen i ett minutt mens du speer med pastavann.'},
    {en:'Take the pan off the heat and stir in half the pecorino. Serve with the rest on top.',
     no:'Ta pannen av platen og rør inn halvparten av pecorinoen. Server med resten på toppen.'},
  ],
  notes:[
    {title:{en:'No onion, no garlic', no:'Verken løk eller hvitløk'},
     body:{en:'Both are excluded by the official recipe of the comune of Amatrice, and both blur a sauce whose whole character comes from pork fat, tomato and sheep’s cheese. If you want the Roman trattoria version, soften a little onion in the fat before the tomatoes; just do not call it traditional in Amatrice.',
           no:'Begge deler er utelukket i den offisielle oppskriften fra kommunen Amatrice, og begge sløver en saus som får hele sin karakter fra svinefett, tomat og saueost. Vil du ha versjonen fra de romerske trattoriaene, kan du la litt løk mykne i fettet før tomatene, men ikke kall den tradisjonell i Amatrice.'}},
    {title:{en:'Why the guanciale comes out', no:'Hvorfor guancialen tas ut'},
     body:{en:'A quarter of an hour in a wet sauce turns crisp guanciale soft again. Its fat belongs in the sauce from the first minute; the meat itself belongs back in at the last.',
           no:'Et kvarter i en våt saus gjør sprø guanciale myk igjen. Fettet hører hjemme i sausen fra første minutt, men selve kjøttet skal først tilbake helt til slutt.'}},
  ],
  variations:[
    {title:{en:'Bucatini or spaghetti', no:'Bucatini eller spaghetti'},
     body:{en:'Bucatini, the thick hollow spaghetti, is the Roman shape and the one that splashes. Amatrice uses spaghetti, and rigatoni is common in the city too. The sauce does not mind.',
           no:'Bucatini, den tykke, hule spaghettien, er den romerske formen, og den som spruter. Amatrice bruker spaghetti, og rigatoni er også vanlig i byen. Sausen bryr seg ikke.'}},
    {title:{en:'How much chilli', no:'Hvor mye chili'},
     body:{en:'One small dried chilli, left whole and fished out, gives warmth without heat. Split it if you want the dish to bite; Amatrice would not object.',
           no:'Én liten tørket chili som legges i hel og fiskes ut, gir varme uten styrke. Del den hvis du vil at retten skal bite fra seg, og Amatrice vil ikke ha noe imot det.'}},
  ],
},

{
  id:'carbonara', dish:'Carbonara', course:'primo', lesson:3, serves:4, time:{prep:10, cook:15},
  hero:'carbonara', tags:['pasta','guanciale','egg'],
  title:{en:'Carbonara', no:'Carbonara'},
  blurb:{en:'Gricia with egg in it. The heat left in the pasta thickens the yolks into a sauce; there is no cream in it and never was.',
         no:'Gricia med egg i tillegg. Restvarmen i pastaen tykner plommene til en saus, og fløte har aldri hørt hjemme i den.'},
  heroCaption:{en:'Carbonara: egg, pecorino, guanciale and black pepper, and nothing else.',
               no:'Carbonara: egg, pecorino, guanciale og sort pepper, og ingenting annet.'},
  wines:['Frascati Superiore'],
  headnote:{
    en:'<p>Carbonara is the youngest of the four Roman pastas and the one that travelled furthest. The name points at the <em>carbonai</em>, the charcoal burners of the Apennines, and there is a pleasing story about a one-pot dish cooked over a fire in the woods. The written record does not support it. No recipe appears before the Second World War, and the most plausible account is that the dish took shape in Rome in 1944, when American rations of bacon and powdered egg met Roman pasta and pecorino. Eighty years later it is the most cooked Italian dish in the world, and the one Italians most love to see ruined abroad.</p>'
      + '<p>Mechanically it is gricia with egg. Guanciale renders into a clear, sweet fat; yolks beaten with pecorino go in off the heat, and what thickens them is nothing but the warmth still in the pasta and the pan. Get that temperature right and you have a sauce that clings and shines. Get it wrong in one direction and it stays raw and thin, in the other and it scrambles. Everything below is about staying between the two.</p>'
      + '<p>Four things are not negotiable: guanciale rather than bacon or pancetta, Pecorino Romano rather than Parmigiano, whole peppercorns cracked at the last moment, and no cream. The rest — yolks or whole eggs, spaghetti or rigatoni, how much pepper — is a matter of which Roman you ask.</p>',
    no:'<p>Carbonara er den yngste av de fire romerske pastarettene og den som har reist lengst. Navnet peker mot <em>carbonai</em>, kullbrennerne i Apenninene, og det finnes en tiltalende historie om en rett som ble laget i én gryte over bål i skogen. Kildene støtter den ikke. Ingen oppskrift dukker opp før andre verdenskrig, og den mest sannsynlige forklaringen er at retten tok form i Roma i 1944, da amerikanske rasjoner av bacon og eggepulver møtte romersk pasta og pecorino. Åtti år senere er den den italienske retten som lages oftest i verden, og den italienere ergrer seg mest over å se ødelagt i utlandet.</p>'
      + '<p>Teknisk sett er den gricia med egg. Guancialen gir fra seg et klart og søtt fett, plommene piskes med pecorino og går i med kjelen av platen, og det eneste som tykner dem, er varmen som fortsatt sitter i pastaen og pannen. Treffer du den temperaturen, får du en saus som henger og skinner. Bommer du den ene veien, blir den rå og tynn; bommer du den andre, blir den eggerøre. Alt nedenfor handler om å holde seg mellom de to.</p>'
      + '<p>Fire ting er det ikke rom for å endre: guanciale i stedet for bacon eller pancetta, Pecorino Romano i stedet for Parmigiano, hele pepperkorn som knuses i siste liten, og ingen fløte. Resten — plommer eller hele egg, spaghetti eller rigatoni, hvor mye pepper — kommer an på hvilken romer du spør.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:400, u:'g', n:{en:'spaghetti', no:'spaghetti'}, note:{en:'a bronze-drawn dry pasta holds the sauce better', no:'tørket pasta som er trukket gjennom bronseformer, holder bedre på sausen'}},
    {q:150, u:'g', n:{en:'guanciale', no:'guanciale'}, note:{en:'in batons about 6 mm; buy it in one piece and cut it yourself', no:'i staver på rundt 6 mm; kjøp den i ett stykke og skjær den selv'}},
    {q:4,   u:'', n:{en:'egg yolks', no:'eggeplommer'}, round:'half'},
    {q:1,   u:'', n:{en:'whole egg', no:'helt egg'}, round:'half'},
    {q:80,  u:'g', n:{en:'Pecorino Romano', no:'Pecorino Romano'}, note:{en:'finely grated, at room temperature', no:'finrevet, med romtemperatur'}},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, note:{en:'whole corns, cracked coarsely at the last moment', no:'hele korn, grovknust i siste liten'}, scale:'none'},
    {q:3,   u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:10,  u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
  ]}],
  steps:[
    {en:'Take the eggs and the cheese out of the fridge half an hour ahead. Cold yolks meeting hot pasta is one of the two ways this dish fails.',
     no:'Ta eggene og osten ut av kjøleskapet en halvtime i forveien. Kalde plommer som møter varm pasta, er den ene av de to måtene retten mislykkes på.'},
    {en:'Cut the guanciale into batons about 6 mm thick, leaving the fat on. Put them in a wide, dry pan while it is cold and set it over the lowest heat you have.',
     no:'Skjær guancialen i staver på rundt 6 mm, og la fettet sitte på. Legg dem i en vid, tørr panne mens den er kald, og sett den på den svakeste varmen du har.'},
    {en:'Let the fat render for 8 to 10 minutes, until it runs clear and the batons are golden at the edges but still yielding in the middle. Take the pan off the heat and leave it to cool a little.',
     no:'La fettet smelte ut i 8 til 10 minutter, til det er klart og stavene er gylne i kantene, men fortsatt myke i midten. Ta pannen av platen, og la den kjølne litt.'},
    {en:'Crack the peppercorns coarsely and toast them for half a minute in a dry corner of the pan, or in a small pan of their own, until the kitchen smells of them.',
     no:'Knus pepperkornene grovt, og rist dem et halvt minutt i en tørr del av pannen eller i en liten panne for seg, til hele kjøkkenet lukter av dem.'},
    {en:'Beat the yolks and the whole egg with the pecorino and most of the pepper. Work it until it is a thick, dark, glossy cream with no lumps of cheese left in it.',
     no:'Visp plommene og det hele egget sammen med pecorinoen og mesteparten av pepperen. Jobb det til en tykk, mørk og blank krem uten klumper av ost.'},
    {en:'Boil the spaghetti in lightly salted water — the guanciale and the pecorino bring salt of their own — and drain it al dente, keeping some of the water.',
     no:'Kok spaghettien i lett saltet vann, for guancialen og pecorinoen har med seg salt selv, og hell av vannet når den er al dente. Ta vare på noe av det.'},
    {en:'Slacken the egg cream with two spoonfuls of the hot pasta water, pouring in a thin stream and stirring hard. This is the step most recipes leave out and the one that makes the difference.',
     no:'Spe eggekremen med to skjeer varmt pastavann. Hell i en tynn stråle mens du rører kraftig. Dette trinnet er det de fleste oppskrifter hopper over, og det er det som avgjør.'},
    {en:'Tip the pasta into the pan of fat, off the heat, and toss until every strand shines.',
     no:'Ha pastaen over i pannen med fettet, med pannen av platen, og vend til hver tråd skinner.'},
    {en:'Count to thirty, pour in the egg cream and toss without stopping for about a minute. The sauce goes from loose to clinging quite suddenly. If it stays thin, hold the pan over a warm ring for a few seconds at a time, never on it.',
     no:'Tell til tretti, hell i eggekremen, og vend uten å stoppe i omtrent ett minutt. Sausen går ganske brått fra løs til klebrig. Blir den værende tynn, kan du holde pannen over en varm plate noen sekunder om gangen, aldri oppå den.'},
    {en:'Loosen with pasta water until it runs off the spoon. Serve at once, with the guanciale and the last of the pepper on top; carbonara does not wait.',
     no:'Spe med pastavann til den renner av skjeen. Server med en gang, med guancialen og resten av pepperen på toppen. Carbonara venter ikke.'},
  ],
  notes:[
    {title:{en:'The temperature window', no:'Temperaturvinduet'},
     body:{en:'Egg yolk begins to set at about 65 °C and is firm by 70. The sauce has to reach the first number and not the second, which is why the pan comes off the heat, why the cream is tempered first, and why you keep tossing: moving pasta sheds heat evenly instead of cooking the egg where it touches the metal.',
           no:'Eggeplomme begynner å stivne ved rundt 65 °C og er fast ved 70. Sausen må nå det første tallet og ikke det andre, og derfor tas pannen av platen, derfor spes kremen først, og derfor fortsetter du å vende: pasta i bevegelse gir fra seg varmen jevnt i stedet for å steke egget der det ligger mot metallet.'}},
    {title:{en:'No cream, ever', no:'Aldri fløte'},
     body:{en:'The sauce is egg yolk, cheese, rendered fat and a little starchy water. In other countries cream is added to make the dish forgiving, and it is the single thing Italians most love to see done wrong.',
           no:'Sausen består av eggeplomme, ost, smeltet fett og litt stivelsesrikt vann. I utlandet tilsettes fløte for å gjøre retten lettere å lykkes med, og det er nettopp det italienere ergrer seg mest over.'}},
    {title:{en:'What went wrong', no:'Hva som gikk galt'},
     body:{en:'Grainy and yellow means the pan was too hot. Thin and pale means it was too cool, or the pasta was too dry when you drained it — add hot water and keep tossing. Greasy means too much fat and too little starchy water. Rubbery threads of cheese mean the pecorino went in before the pan had cooled.',
           no:'Kornete og gul betyr at pannen var for varm. Tynn og blek betyr at den var for kald, eller at pastaen ble for tørr da du hellte av vannet — ha i varmt vann og fortsett å vende. Fet betyr for mye fett og for lite stivelsesrikt vann. Gummiaktige tråder av ost betyr at pecorinoen kom i før pannen hadde kjølnet.'}},
  ],
  variations:[
    {title:{en:'Yolks or whole eggs', no:'Plommer eller hele egg'},
     body:{en:'Four yolks and one whole egg for four people is a middle course. All yolks give a deeper, sleeker sauce that sets faster and needs more care; whole eggs give a lighter one that is easier to save.',
           no:'Fire plommer og ett helt egg til fire personer er en mellomting. Bare plommer gir en dypere og glattere saus som stivner raskere og krever mer oppmerksomhet, mens hele egg gir en lettere saus som er lettere å redde.'}},
    {title:{en:'The shape of the pasta', no:'Pastaformen'},
     body:{en:'Spaghetti is the Roman default. Rigatoni and mezze maniche catch more of the sauce inside them and are what many trattorias in the city actually serve.',
           no:'Spaghetti er standarden i Roma. Rigatoni og mezze maniche fanger mer av sausen inni seg, og er det mange trattoriaer i byen faktisk serverer.'}},
    {title:{en:'If you cannot find guanciale', no:'Hvis du ikke får tak i guanciale'},
     body:{en:'Pancetta is the least bad substitute: it is belly rather than jowl, leaner and milder, so use a little more and render it just as slowly. Bacon is smoked, and smoke is not part of this dish.',
           no:'Pancetta er den minst dårlige erstatningen. Den er sideflesk og ikke kjake, magrere og mildere, så bruk litt mer og smelt fettet like sakte ut. Bacon er røkt, og røyk hører ikke hjemme i denne retten.'}},
  ],
},

{
  id:'carciofi-alla-giudia', dish:'Carciofi alla giudia', course:'antipasto', lesson:4, serves:4, time:{prep:40, cook:25},
  hero:'carciofi', tags:['fried','vegetarian','artichoke','ghetto'],
  title:{en:'Carciofi alla giudia', no:'Carciofi alla giudia'},
  blurb:{en:'A whole artichoke fried twice in olive oil, gently first and then fiercely, until the leaves open and set like a bronze flower.',
         no:'En hel artisjokk friteres to ganger i olivenolje, først lunkent og så glovarmt, til bladene åpner seg og stivner som en bronseblomst.'},
  heroCaption:{en:'Carciofi alla giudia, eaten with the fingers, leaf by leaf, with a cold glass of Frascati.',
               no:'Carciofi alla giudia spises med fingrene, blad for blad, med et kaldt glass Frascati.'},
  wines:['Frascati Superiore'],
  headnote:{
    en:'<p>This is the signature dish of the Roman <strong>Ghetto</strong>, the few streets where the city’s Jews were confined by papal decree from 1555 until 1870. A whole artichoke is trimmed, flattened and fried twice in olive oil, once slowly to cook it through and once at high heat to crisp the outer leaves. It is eaten with the fingers, leaf by leaf, and it wants a cold glass of Frascati beside it.</p>'
      + '<p>The artichoke itself is half the recipe. Rome uses <em>mammole</em>, the round thornless Romanesco, picked young enough that the hairy choke has barely formed and the leaves are tender almost to the tip. They are not sold in Norway. The substitute is the big green globe artichoke from the greengrocer, and it behaves differently: it has a choke that has to come out, and a thicker skirt of tough outer leaves. Expect the trimming to take longer than the cooking.</p>'
      + '<p>Two temperatures are the whole technique. The first bath barely murmurs; the second is hot enough to dry the leaves in seconds. Fry only once and you get either a scorched flower with a raw base or a soft, oil-logged artichoke — never the thing you came for.</p>',
    no:'<p>Dette er signaturretten fra <strong>gettoen</strong> i Roma, de få gatene der byens jøder var innesperret ved pavelig dekret fra 1555 til 1870. En hel artisjokk renses, flates ut og friteres to ganger i olivenolje, én gang sakte for å bli gjennomkokt og én gang på høy varme for at de ytre bladene skal bli sprø. Den spises med fingrene, blad for blad, og den vil ha et kaldt glass Frascati ved siden av.</p>'
      + '<p>Selve artisjokken er halve oppskriften. Roma bruker <em>mammole</em>, den runde, tornefrie Romanesco-artisjokken, som høstes så ung at det lodne høyet så vidt har dannet seg og bladene er møre nesten helt ut. Den selges ikke i Norge. Erstatningen er den store grønne artisjokken fra grønnsakshandleren, og den oppfører seg annerledes. Den har høy som må ut, og et tykkere skjørt av seige ytterblader. Regn med at rensingen tar lengre tid enn stekingen.</p>'
      + '<p>To temperaturer utgjør hele teknikken. Det første badet så vidt mumler, og det andre er varmt nok til å tørke bladene på sekunder. Friterer du bare én gang, ender du enten med en svidd blomst med rå bunn eller med en myk artisjokk full av olje, og aldri med det du var ute etter.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:4, u:'', n:{en:'globe artichokes', no:'artisjokker'}, note:{en:'Roman mammole if you ever see them; otherwise the heaviest, tightest-headed green ones you can find', no:'romerske mammole hvis du noen gang ser dem, ellers de tyngste grønne med fastest lukkede hoder'}, round:'half'},
    {q:1, u:'', n:{en:'lemon', no:'sitron'}, note:{en:'for the water the trimmed artichokes wait in', no:'til vannet de rensede artisjokkene venter i'}, round:'half'},
    {u:'', n:{en:'olive oil for frying', no:'olivenolje til fritering'}, note:{en:'a mild one, not a peppery extra virgin; enough to stand them in head down', no:'en mild olje, ikke en peprete ekstra virgin; nok til at de står i den med hodet ned'}, scale:'none'},
    {u:'', n:{en:'salt', no:'salt'}, note:{en:'flaky, and mostly at the end', no:'flaksalt, og mest til slutt'}, scale:'none'},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
  ]}],
  steps:[
    {en:'Fill a bowl with cold water and squeeze the lemon into it. A cut artichoke browns within a minute, and each one sits in this water until the last is trimmed.',
     no:'Fyll en bolle med kaldt vann og press sitronen oppi. En oppskåret artisjokk blir brun i løpet av et minutt, og hver av dem ligger i dette vannet til den siste er renset.'},
    {en:'Snap the tough outer leaves off one at a time, bending each one backwards until it breaks at the base, and keep going well past the point where it starts to feel wasteful. Stop when the leaves you reach are pale yellow-green at the bottom.',
     no:'Brekk av de seige ytterbladene ett om gangen ved å bøye hvert blad bakover til det knekker ved roten, og fortsett et godt stykke forbi der det begynner å føles som sløsing. Stopp når bladene du kommer til, er lysegrønne nederst.'},
    {en:'Cut the stem back to about 5 cm and pare it with a small knife until only the pale core is left. The stem is the best part of the artichoke and most people throw it away.',
     no:'Skjær stilken ned til rundt 5 cm og skrell den med en liten kniv til bare den lyse kjernen er igjen. Stilken er den beste biten av artisjokken, og de fleste kaster den.'},
    {en:'Lay the artichoke on its side and slice the top third of the leaf cone straight off with a serrated knife. The rest should look like a tulip.',
     no:'Legg artisjokken på siden og skjær den øverste tredjedelen av bladkronen rett av med en brødkniv. Resten skal ligne en tulipan.'},
    {en:'Hold it by the stem and turn it against the blade of a small sharp knife, spiralling upward from the base, until no dark green is left anywhere on the outside. Drop it into the lemon water and start the next one.',
     no:'Hold den i stilken og drei den mot bladet på en liten skarp kniv, i spiral oppover fra bunnen, til det ikke er noe mørkegrønt igjen på utsiden. Legg den i sitronvannet og begynn på neste.'},
    {en:'Open the leaves out with your thumbs and scrape the hairy choke from the middle with the tip of a spoon. Roman mammole are picked before it forms; the artichokes sold here are older, and it has to come out.',
     no:'Åpne bladene ut med tomlene og skrap ut det lodne høyet i midten med spissen av en skje. Romerske mammole høstes før det dannes, men artisjokkene som selges her, er eldre, og høyet må ut.'},
    {en:'Drain the artichokes and dry them thoroughly, inside the leaves as well as out. Water trapped between the leaves will throw the oil out of the pan.',
     no:'Renn av artisjokkene og tørk dem grundig, både inne mellom bladene og utenpå. Vann som blir sittende mellom bladene, kaster oljen ut av kjelen.'},
    {en:'Season down inside the leaves with salt and pepper, then press each artichoke head first against the work surface so the leaves splay open.',
     no:'Krydre ned mellom bladene med salt og pepper, og press så hver artisjokk med hodet først mot benken, slik at bladene spriker ut.'},
    {en:'Heat the oil to 130 °C in a pan deep enough to cover them, stand them in head down, and fry for 10 to 12 minutes, until a knife slides into the base with no resistance. The oil should barely murmur.',
     no:'Varm oljen til 130 °C i en kjele som er dyp nok til å dekke dem, sett dem ned med hodet først, og friter dem i 10 til 12 minutter, til en kniv går uten motstand inn i bunnen. Oljen skal så vidt mumle.'},
    {en:'Lift them out and stand them upside down on paper to drain. They can wait an hour or two here, which is exactly what the Ghetto restaurants do.',
     no:'Løft dem opp og sett dem opp ned på papir for å renne av. De kan stå slik i en time eller to, og det er nettopp det restaurantene i gettoen gjør.'},
    {en:'Bring the oil to 180 °C. Press each artichoke open against the work surface once more, flick a few drops of cold water over the leaves, and lower it in head down at arm’s length, because it spits hard.',
     no:'Varm oljen til 180 °C. Press hver artisjokk åpen mot benken en gang til, skvett noen dråper kaldt vann over bladene, og senk den ned med hodet først og strak arm, for den spruter kraftig.'},
    {en:'Fry for a minute or two, until the outer leaves are stiff, crisp and the colour of old bronze. Drain, salt, and serve at once; they soften as they cool.',
     no:'Friter i et par minutter, til ytterbladene er stive, sprø og har fargen av gammel bronse. La dem renne av, strø over salt og server med en gang, for de blir myke når de kjølner.'},
  ],
  notes:[
    {title:{en:'Two baths, two jobs', no:'To bad, to oppgaver'},
     body:{en:'The first bath is a poach in oil. At 130 °C the heart cooks through by conduction while the leaves stay limp, because water leaves them slowly and the oil is nowhere near hot enough to colour anything. The second bath is a shock. At 180 °C the thin outer leaves lose their water in seconds, and a leaf that dries that fast curls outward and sets rigid — that is the flower, and it cannot be made any other way.',
           no:'Det første badet er en posjering i olje. Ved 130 °C blir hjertet gjennomkokt av varmeledning mens bladene holder seg slappe, for vannet forlater dem langsomt, og oljen er langt fra varm nok til å gi farge. Det andre badet er et sjokk. Ved 180 °C mister de tynne ytterbladene vannet på sekunder, og et blad som tørker så fort, krøller seg utover og stivner. Det er blomsten, og den kan ikke lages på noen annen måte.'}},
    {title:{en:'The artichoke you can actually buy', no:'Artisjokken du faktisk får kjøpt'},
     body:{en:'A Romanesco mammola is round, thornless and young, with almost no choke and leaves that are tender nearly to the tip. The globe artichokes on sale in Norway are bigger, older and tougher: more of the outside has to come off, the choke has to be dug out, and the first fry needs the longer end of the time. Choose by weight rather than by size, and reject any head that has begun to open.',
           no:'En Romanesco-mammola er rund, tornefri og ung, nesten uten høy, og med blader som er møre nesten helt ut. Artisjokkene som selges i Norge, er større, eldre og seigere. Mer av utsiden må bort, høyet må graves ut, og det første frityrbadet trenger den lengste tiden. Velg etter vekt heller enn størrelse, og la hoder som har begynt å åpne seg, ligge.'}},
    {title:{en:'Trimming is the recipe', no:'Rensingen er selve oppskriften'},
     body:{en:'Almost every complaint about this dish — chewy leaves, a stringy base, a mouthful of bitterness — comes from taking off too little rather than too much. A trimmed artichoke weighs about a third of what it did in the shop. Beginners stop far too early because the waste looks obscene; the cooks in the Ghetto do not.',
           no:'Nesten alle klager på denne retten, enten det gjelder seige blader, trevlete bunn eller en bitter munnfull, kommer av at det er tatt bort for lite og ikke for mye. En renset artisjokk veier omtrent en tredjedel av det den gjorde i butikken. Nybegynnere stopper altfor tidlig fordi svinnet ser ublu ut, men kokkene i gettoen gjør ikke det.'}},
  ],
  variations:[
    {title:{en:'Carciofi alla romana', no:'Carciofi alla romana'},
     body:{en:'The other Roman artichoke, and the one to make when a pan of frying oil feels like too much trouble. The same trimmed artichoke is stuffed with mint, garlic and parsley and braised stem upwards in oil and water until it collapses. Same vegetable, opposite method, and it is eaten warm rather than hot.',
           no:'Den andre romerske artisjokkretten, og den du lager når en kjele frityrolje føles som for mye styr. Den samme rensede artisjokken fylles med mynte, hvitløk og persille og breseres med stilken opp i olje og vann til den faller sammen. Samme grønnsak, motsatt metode, og den spises lunken i stedet for varm.'}},
    {title:{en:'Small artichokes', no:'Små artisjokker'},
     body:{en:'The little purple artichokes sometimes sold in bunches with their stems on can be fried exactly this way and need about half the time in the first bath. Reckon three or four of them for one large one.',
           no:'De små lilla artisjokkene som iblant selges i bunter med stilken på, kan friteres på nøyaktig samme måte og trenger omtrent halve tiden i det første badet. Regn tre eller fire av dem for én stor.'}},
    {title:{en:'Which oil', no:'Hvilken olje'},
     body:{en:'The Ghetto fries in olive oil and the flavour of the dish depends on it, but a peppery new-pressed extra virgin turns bitter at frying heat. A mild olive oil for both baths is the honest compromise; a neutral oil for the first and olive oil for the second is the thrifty one.',
           no:'I gettoen friteres det i olivenolje, og smaken i retten avhenger av det, men en peprete, nypresset ekstra virgin blir bitter i frityrvarme. En mild olivenolje i begge bad er det ærlige kompromisset, og nøytral olje i det første og olivenolje i det andre er det sparsommelige.'}},
  ],
},

{
  id:'suppli', dish:'Supplì', course:'antipasto', lesson:4, serves:4, time:{prep:30, cook:45},
  hero:'suppli', tags:['fried','rice','street food','mozzarella'],
  title:{en:'Supplì al telefono', no:'Supplì al telefono'},
  blurb:{en:'Rome’s rice croquette: risotto bound with a little ragù, a baton of mozzarella inside, breaded and fried until the cheese pulls into a wire.',
         no:'Romas riskrokett. Risotto bundet med litt ragù, en stav mozzarella inni, panert og fritert til osten trekker seg ut i en tråd.'},
  heroCaption:{en:'Break one open and the mozzarella stretches like a telephone cord — hence supplì al telefono.',
               no:'Del en i to, og mozzarellaen strekker seg som en telefonledning. Derav supplì al telefono.'},
  wines:['Frascati Superiore'],
  headnote:{
    en:'<p>Romans eat between meals standing at a <em>friggitoria</em> counter, and the essential order is a supplì: a croquette of risotto rice bound with a little ragù, stuffed with mozzarella, breaded and fried. Pull one apart and the cheese stretches into a long thin wire, which is where the full name comes from — <em>supplì al telefono</em>, from the days when a telephone had a cord.</p>'
      + '<p>It began as a way of using yesterday’s rice and stopped being one. The rice is cooked like a risotto but deliberately drier and firmer than anything you would put on a plate, then spread out and chilled until it can be moulded in the hand. Warm risotto will not hold a shape and bursts in the oil; cold risotto behaves like putty. The ragù is a binder and a seasoning rather than a sauce, so it is cooked down almost dry and the rice is cooked in it.</p>'
      + '<p>Two things are not negotiable. The rice must be properly cold, and the mozzarella must be properly dry. A split crust, a croquette that unravels, a pool of white cheese in the bottom of the pan — all of it comes from one of those two.</p>',
    no:'<p>Romerne spiser mellom måltidene stående ved disken i en <em>friggitoria</em>, og den obligatoriske bestillingen er en supplì, altså en krokett av risottoris bundet med litt ragù, fylt med mozzarella, panert og fritert. Del en i to, og osten strekker seg til en lang, tynn tråd. Derfra kommer det fulle navnet, <em>supplì al telefono</em>, fra den tiden en telefon hadde ledning.</p>'
      + '<p>Retten begynte som en måte å bruke opp gårsdagens ris på, og sluttet å være det. Risen kokes som en risotto, men med vilje tørrere og fastere enn noe du ville satt på et fat, og så bres den utover og kjøles til den lar seg forme i hånden. Varm risotto holder ikke på formen og sprekker i oljen, mens kald risotto oppfører seg som kitt. Ragùen er et bindemiddel og en krydring mer enn en saus, så den kokes nesten tørr, og risen kokes i den.</p>'
      + '<p>To ting er det ikke rom for å slurve med. Risen må være ordentlig kald, og mozzarellaen må være ordentlig tørr. En sprukken panering, en krokett som løser seg opp, en dam av hvit ost i bunnen av kjelen — alt sammen kommer av én av de to.</p>'},
  ingredients:[
    { group:{en:'The rice', no:'Risen'}, items:[
      {q:320, u:'g', n:{en:'risotto rice', no:'risottoris'}, note:{en:'Carnaroli or Arborio; long-grain rice will not bind', no:'Carnaroli eller Arborio; langkornet ris binder ikke'}},
      {q:150, u:'g', n:{en:'minced beef', no:'kjøttdeig av storfe'}, note:{en:'beef or veal, coarsely minced', no:'okse- eller kalvekjøtt, grovmalt'}},
      {q:1,   u:'', n:{en:'onion', no:'løk'}, note:{en:'finely chopped', no:'finhakket'}, round:'half'},
      {q:200, u:'g', n:{en:'peeled plum tomatoes', no:'hermetiske plommetomater'}, note:{en:'crushed by hand', no:'most med hendene'}},
      {q:50,  u:'ml', n:{en:'dry white wine', no:'tørr hvitvin'}},
      {q:900, u:'ml', n:{en:'meat or chicken stock', no:'kjøtt- eller kyllingkraft'}, note:{en:'kept hot beside the pan', no:'holdes varm ved siden av kjelen'}},
      {q:30,  u:'ml', n:{en:'olive oil', no:'olivenolje'}},
      {q:60,  u:'g', n:{en:'Pecorino Romano', no:'Pecorino Romano'}, note:{en:'finely grated', no:'finrevet'}},
      {q:1,   u:'', n:{en:'egg', no:'egg'}, note:{en:'beaten, to bind the rice at the end', no:'sammenvispet, for å binde risen til slutt'}, round:'half'},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
      {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
    ]},
    { group:{en:'To fill and fry', no:'Til fyll og fritering'}, items:[
      {q:200, u:'g', n:{en:'mozzarella', no:'mozzarella'}, note:{en:'fior di latte, cut into batons and drained on paper; buffalo mozzarella holds far too much water', no:'fior di latte, skåret i staver og lagt på papir for å renne av; bøffelmozzarella holder på altfor mye vann'}},
      {q:2,   u:'', n:{en:'eggs', no:'egg'}, note:{en:'beaten, for coating', no:'sammenvispet, til panering'}, round:'half'},
      {q:150, u:'g', n:{en:'fine dry breadcrumbs', no:'griljermel'}, note:{en:'plain, not seasoned', no:'uten krydder'}},
      {u:'', n:{en:'oil for frying', no:'olje til fritering'}, note:{en:'a neutral oil, deep enough for them to float', no:'nøytral olje, dypt nok til at de flyter'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Soften the onion in the olive oil over low heat until it is translucent but has taken no colour.',
     no:'La løken mykne i olivenoljen på svak varme til den er blank, men ikke har fått farge.'},
    {en:'Turn the heat up, add the mince, break it apart, and cook until the liquid it gives off has gone and the meat begins to catch on the pan.',
     no:'Skru opp varmen, ha i kjøttdeigen, del den opp, og stek til væsken den gir fra seg, er borte og kjøttet begynner å feste seg i pannen.'},
    {en:'Pour in the wine and let it evaporate, then crush in the tomatoes and simmer for 20 minutes, until the ragù is dark and thick enough to hold the mark of a spoon.',
     no:'Hell i vinen og la den fordampe, mos så tomatene oppi og la det småkoke i 20 minutter, til ragùen er mørk og så tykk at den holder på sporet etter en skje.'},
    {en:'Stir the rice into the ragù and toast it for a minute, until the grains are hot and glassy at the edges.',
     no:'Rør risen inn i ragùen og rist den i ett minutt, til kornene er varme og glassaktige i kantene.'},
    {en:'Add the hot stock a ladleful at a time, stirring, for about 16 minutes — but stop while the rice is still firm in the middle and much drier than a risotto you would eat. It has to stand up on the spoon.',
     no:'Spe med varm kraft, en øse om gangen, mens du rører, i omtrent 16 minutter. Stopp likevel mens risen fortsatt er fast i midten og langt tørrere enn en risotto du ville spist. Den skal stå av seg selv på skjeen.'},
    {en:'Take the pan off the heat, stir in the pecorino, taste for salt and pepper, and beat in the egg.',
     no:'Ta kjelen av platen, rør inn pecorinoen, smak til med salt og pepper, og visp inn egget.'},
    {en:'Spread the rice out in a thin layer on a tray and let it cool, then chill it until it is cold and stiff. Two hours is the minimum and overnight is better.',
     no:'Bre risen utover et brett i et tynt lag og la den kjølne, og sett den så kaldt til den er kald og stiv. To timer er et minimum, og natten over er bedre.'},
    {en:'Cut the mozzarella into batons the length of a thumb and leave them on paper while the rice chills.',
     no:'Skjær mozzarellaen i staver på lengde med en tommel, og la dem ligge på papir mens risen kjøles.'},
    {en:'Take a handful of the cold rice, flatten it in your palm, lay a baton of cheese along the middle, and close the rice around it into a cylinder with no seam left open.',
     no:'Ta en håndfull kald ris, flat den ut i hånden, legg en ostestav langs midten, og lukk risen rundt den til en sylinder uten åpne skjøter.'},
    {en:'Roll each one through the beaten egg and then through the breadcrumbs, pressing the crumb on firmly, and chill them again for half an hour.',
     no:'Rull hver av dem gjennom det sammenvispede egget og deretter i griljermelet, og press paneringen godt fast. Sett dem kaldt igjen i en halvtime.'},
    {en:'Heat the oil to 175 °C and fry four or five at a time for three to four minutes, until they are deep gold all over. More than that in the pan at once drops the temperature, and then they drink oil instead of frying.',
     no:'Varm oljen til 175 °C og friter fire eller fem om gangen i tre til fire minutter, til de er dypt gylne over det hele. Flere enn det i kjelen samtidig senker temperaturen, og da suger de til seg olje i stedet for å bli fritert.'},
    {en:'Drain them on paper, wait a minute so nobody burns their mouth, and break one open to see the wire.',
     no:'La dem renne av på papir, vent et minutt så ingen brenner seg, og del en i to for å se tråden.'},
  ],
  notes:[
    {title:{en:'Cold rice, or nothing holds', no:'Kald ris, ellers holder ingenting'},
     body:{en:'Hot risotto is loose because its starch is swollen with water and still mobile. As the rice cools, that starch retrogrades: the chains lock back together and the mass turns firm, sliceable and mouldable. A supplì shaped from warm rice slumps on the tray, splits in the oil and lets the cheese out. Nothing hurries this but the fridge, and rice spread thin on a tray cools several times faster than rice left in a bowl.',
           no:'Varm risotto er løs fordi stivelsen er oppsvulmet av vann og fortsatt i bevegelse. Når risen kjøles, går stivelsen tilbake: kjedene låser seg sammen igjen, og massen blir fast, lar seg skjære og lar seg forme. En supplì formet av varm ris siger ut på brettet, sprekker i oljen og slipper osten løs. Ingenting framskynder dette annet enn kjøleskapet, og ris som er bredt tynt utover et brett, kjøles flere ganger raskere enn ris som blir liggende i en bolle.'}},
    {title:{en:'Why 175 °C', no:'Hvorfor 175 °C'},
     body:{en:'The crust has to set before the inside warms up, and the inside only needs to reach the melting point of mozzarella. At 175 °C the breadcrumb dries and browns in well under a minute and then works as a shell, while the rice behind it heats gently. Cooler oil soaks in before any crust forms, and you get a greasy supplì with solid cheese; hotter oil gives you a black crust and the same solid cheese.',
           no:'Paneringen må stivne før innsiden blir varm, og innsiden trenger bare å nå smeltepunktet til mozzarellaen. Ved 175 °C tørker og brunes griljermelet på godt under et minutt og virker deretter som et skall, mens risen innenfor varmes forsiktig. Kaldere olje trekker inn før det dannes noen skorpe, og du sitter igjen med en fet supplì og fast ost. Varmere olje gir svart skorpe og like fast ost.'}},
    {title:{en:'The ragù is glue', no:'Ragùen er lim'},
     body:{en:'A Roman supplì is not a rice ball with sauce inside it. The ragù is reduced until it is nearly dry and the rice is then cooked in it, so the meat and the tomato season every grain and add nothing loose. A wet ragù stirred through at the end leaves the rice too soft to shape and puts the flavour in patches.',
           no:'En romersk supplì er ingen riskule med saus inni. Ragùen kokes inn til den nesten er tørr, og risen kokes deretter i den, slik at kjøttet og tomaten krydrer hvert korn uten å tilføre noe løst. En våt ragù som røres inn til slutt, gir ris som er for myk til å formes, og legger smaken i flekker.'}},
  ],
  variations:[
    {title:{en:'Supplì in bianco', no:'Supplì in bianco'},
     body:{en:'Leave the meat and the tomato out altogether: cook the rice in stock with butter and a good deal of pecorino, chill it and fill it the same way. Plainer, paler, and a better test of whether your rice is dry enough, because there is no ragù to help it hold.',
           no:'Utelat kjøttet og tomaten helt. Kok risen i kraft med smør og rikelig pecorino, kjøl den ned og fyll den på samme måte. Enklere, lysere, og en bedre prøve på om risen din er tørr nok, for her finnes ingen ragù som kan hjelpe den å holde.'}},
    {title:{en:'Supplì cacio e pepe', no:'Supplì cacio e pepe'},
     body:{en:'Roman friggitorie now sell supplì flavoured like the city’s pastas — cacio e pepe, amatriciana, carbonara. They are a recent invention and none the worse for it. The rice and the method do not change; only the seasoning and what goes in the middle.',
           no:'Friggitoriaene i Roma selger nå supplì med smak av byens egne pastaretter, altså cacio e pepe, amatriciana og carbonara. Det er en ny oppfinnelse, og den er ikke dårligere av den grunn. Risen og metoden er de samme, og bare krydringen og det som ligger i midten, endrer seg.'}},
    {title:{en:'Not an arancino', no:'Ikke en arancino'},
     body:{en:'Sicily’s arancini are a different dish: bigger, round or conical, made with saffron rice and filled with ragù and peas or with ham and cheese. A supplì is smaller, oval, and is really about the cheese in the middle.',
           no:'Arancini fra Sicilia er en annen rett. De er større, runde eller koniske, laget med safranris og fylt med ragù og erter eller med skinke og ost. En supplì er mindre og oval, og handler egentlig om osten i midten.'}},
  ],
},

{
  id:'saltimbocca', dish:'Saltimbocca alla romana', course:'secondo', lesson:4, serves:4, time:{prep:15, cook:10},
  hero:'saltimbocca', tags:['veal','sage','prosciutto','quick'],
  title:{en:'Saltimbocca alla romana', no:'Saltimbocca alla romana'},
  blurb:{en:'Veal, prosciutto and a sage leaf, pinned flat and cooked in under two minutes. The name means it jumps in the mouth.',
         no:'Kalvekjøtt, prosciutto og et salvieblad, festet flatt sammen og stekt på under to minutter. Navnet betyr at den hopper i munnen.'},
  heroCaption:{en:'Saltimbocca alla romana: the Roman version lies flat and is never rolled.',
               no:'Saltimbocca alla romana. Den romerske versjonen ligger flatt og rulles aldri.'},
  wines:['Frascati Superiore'],
  headnote:{
    en:'<p>No reading in this course describes saltimbocca. The Lazio lessons walk from the Colosseum to the friggitoria, west into the Ghetto for the artichoke, and south to Testaccio for the <em>quinto quarto</em>, the fifth quarter of the animal that the slaughterhouse workers were partly paid in. That is the Roman kitchen the course tells you about: thrift, offal, fried vegetables, and four pasta dishes made of almost nothing.</p>'
      + '<p>Saltimbocca stands at the other end of the same city. It is a trattoria <em>secondo</em> cut from the butcher’s best and dearest meat, and it sits on Roman menus a line or two below the oxtail. It earns its place here by being the fastest good thing in the chapter: veal beaten thin, a slice of prosciutto crudo, a sage leaf, a cocktail stick through all three, and a minute and a half in foaming butter. <em>Salta in bocca</em> — it jumps in the mouth.</p>'
      + '<p>Three things decide it. The veal has to be beaten genuinely thin, so that it is cooked before it is dry. The ham side goes into the pan first. And no salt touches the meat at any point, because the prosciutto is the seasoning and anything on top of it makes the dish inedible.</p>',
    no:'<p>Ingen av lesetekstene i dette kurset beskriver saltimbocca. Leksjonene om Lazio går fra Colosseum til friggitoriaen, vestover inn i gettoen etter artisjokken og sørover til Testaccio etter <em>quinto quarto</em>, den femte fjerdedelen av dyret som slakteriarbeiderne fikk som en del av lønnen. Det er det romerske kjøkkenet kurset forteller om: nøysomhet, innmat, friterte grønnsaker og fire pastaretter laget av nesten ingenting.</p>'
      + '<p>Saltimbocca hører hjemme i den andre enden av den samme byen. Retten er en <em>secondo</em> fra trattoriaen, skåret av det beste og dyreste kjøttet slakteren har, og den står på romerske menyer en linje eller to under oksehalen. Den fortjener plassen sin her fordi den er det raskeste gode i dette kapittelet: kalvekjøtt banket tynt, en skive prosciutto crudo, et salvieblad, en tannpirker gjennom alle tre og halvannet minutt i skummende smør. <em>Salta in bocca</em>, den hopper i munnen.</p>'
      + '<p>Tre ting avgjør resultatet. Kalvekjøttet må bankes virkelig tynt, så det er ferdig før det tørker ut. Skinkesiden skal ned i pannen først. Og kjøttet skal ikke saltes på noe tidspunkt, for prosciuttoen er krydringen, og alt salt i tillegg gjør retten uspiselig.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:8, u:'', n:{en:'veal escalopes', no:'kalveschnitzler'}, note:{en:'about 60 g each, from the topside; in Norway ask for kalveschnitzel — few shops keep veal, but a butcher will cut it if you order ahead', no:'rundt 60 g hver, fra innerlåret; spør etter kalveschnitzel, for få butikker har kalvekjøtt, men en slakter skjærer det hvis du bestiller i forveien'}, round:'half'},
    {q:8, u:'', n:{en:'slices of prosciutto crudo', no:'skiver prosciutto crudo'}, note:{en:'Parma or San Daniele, sliced thin. Norwegian spekeskinke is a different cure, drier and sharper, and will not do here; buy the Italian ham.', no:'Parma eller San Daniele, tynt skåret. Norsk spekeskinke er speket på en annen måte, tørrere og skarpere, og duger ikke her. Kjøp den italienske skinken.'}, round:'half'},
    {q:8, u:'', n:{en:'fresh sage leaves', no:'ferske salvieblader'}, note:{en:'large ones; dried sage is a different herb and does nothing here', no:'store blader; tørket salvie er en annen urt og gjør ingenting her'}, round:'half'},
    {q:50, u:'g', n:{en:'butter', no:'smør'}, note:{en:'keep a third of it back for the sauce', no:'hold en tredjedel av det tilbake til sausen'}},
    {q:20, u:'g', n:{en:'plain flour', no:'hvetemel'}, note:{en:'for dusting the veal side only', no:'til å strø bare på kjøttsiden'}},
    {q:100, u:'ml', n:{en:'dry white wine', no:'tørr hvitvin'}, note:{en:'a Frascati, if you are opening one anyway', no:'en Frascati, hvis du likevel åpner en'}},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
  ]}],
  steps:[
    {en:'Lay each escalope between two sheets of baking paper and beat it out with a rolling pin or the base of a heavy pan until you can almost see the paper through it, working from the middle outward.',
     no:'Legg hver kalveschnitzel mellom to ark bakepapir og bank den ut med en kjevle eller bunnen av en tung panne til du nesten skimter papiret gjennom den. Arbeid fra midten og utover.'},
    {en:'Trim each slice of prosciutto so that it covers the veal without hanging over the edge. Ham that touches the pan instead of the meat burns.',
     no:'Skjær hver prosciuttoskive til, så den dekker kjøttet uten å henge utenfor kanten. Skinke som ligger mot pannen i stedet for mot kjøttet, blir svidd.'},
    {en:'Lay the ham on the veal, put a sage leaf on top of the ham, and pin the three together with a wooden cocktail stick pushed in and out again so that it lies flat.',
     no:'Legg skinken på kjøttet, legg et salvieblad oppå skinken, og fest de tre sammen med en tannpirker av tre som stikkes inn og ut igjen, slik at den ligger flatt.'},
    {en:'Grind pepper over the veal side and add no salt at all. The prosciutto is salty enough for both of them.',
     no:'Kvern pepper over kjøttsiden, og ikke ha i salt i det hele tatt. Prosciuttoen er salt nok for begge deler.'},
    {en:'Dust the veal side only with flour and shake off what does not stick. The ham has to go into the pan dry.',
     no:'Strø mel bare på kjøttsiden, og rist av det som ikke fester seg. Skinken skal ned i pannen tørr.'},
    {en:'Melt most of the butter in a wide pan over a fairly high heat, and wait until the foam has risen and begun to fall again.',
     no:'Smelt mesteparten av smøret i en vid panne på nokså høy varme, og vent til skummet har steget og begynt å legge seg igjen.'},
    {en:'Lay them in ham and sage side down, in a single layer, and cook for about a minute, until the ham has darkened at the edges and the sage can be smelled across the kitchen.',
     no:'Legg dem i med skinke- og salviesiden ned, i ett lag, og stek i omtrent ett minutt, til skinken har mørknet i kantene og duften av salvie fyller kjøkkenet.'},
    {en:'Turn them and give the veal side thirty to forty seconds, no more. Lift them onto a warm plate the moment the last pink leaves the edge.',
     no:'Snu dem og gi kjøttsiden tretti til førti sekunder, ikke mer. Løft dem over på et varmt fat i det øyeblikket det siste rosa forsvinner fra kanten.'},
    {en:'Pour the wine into the hot pan and let it bubble down to a syrup, scraping the flour and the browned butter off the bottom as it goes.',
     no:'Hell vinen i den varme pannen og la den koke inn til sirup mens du skraper mel og brunet smør løs fra bunnen.'},
    {en:'Take the pan off the heat, drop in the butter you kept back, and swing the pan round until the sauce turns glossy and thick enough to cling to a spoon.',
     no:'Ta pannen av platen, ha i smøret du holdt tilbake, og sving pannen rundt til sausen blir blank og tykk nok til å henge ved en skje.'},
    {en:'Pour the sauce over, pull the cocktail sticks out or warn the table that they are there, and serve at once with bread and nothing else.',
     no:'Hell sausen over, trekk ut tannpirkerne eller si fra til bordet at de er der, og server med en gang, med brød og ingenting annet.'},
  ],
  notes:[
    {title:{en:'Ham side down first', no:'Skinkesiden ned først'},
     body:{en:'Prosciutto crudo is thin, lean and already cured, so it needs heat only long enough for its fat to render and its surface to dry against the metal, which is about a minute. In that minute the veal above it barely warms. Turn the parcel the other way round and the veal has to sit in the pan long enough to heat the ham through from behind, which is roughly twice as long as veal this thin can stand. The sage gains from the same order: when the leaf lies pressed between the ham and the hot pan, its oils go straight into the butter.',
           no:'Prosciutto crudo er tynn, mager og allerede speket, så den trenger varme bare lenge nok til at fettet smelter og overflaten tørker mot metallet, altså rundt ett minutt. I løpet av det minuttet blir kjøttet over den så vidt varmt. Snur du pakken motsatt vei, må kjøttet ligge i pannen lenge nok til å varme skinken gjennom bakfra, og det er omtrent dobbelt så lenge som så tynt kalvekjøtt tåler. Salvien tjener på den samme rekkefølgen, for når bladet ligger presset mellom skinken og den varme pannen, går oljene rett ut i smøret.'}},
    {title:{en:'A minute and a half in all', no:'Halvannet minutt til sammen'},
     body:{en:'A veal escalope beaten down to a couple of millimetres carries almost no fat and almost no connective tissue to protect it. Its muscle fibres contract as they pass about 65 °C and squeeze their water out, and from there the meat goes from tender to dry in seconds. This dish has none of the margin a braise gives you: hot pan, short time, and out of the pan before you are quite sure.',
           no:'En kalveschnitzel banket ned til et par millimeter har nesten ikke fett og nesten ikke bindevev som kan beskytte den. Muskelfibrene trekker seg sammen når de passerer rundt 65 °C og presser ut vannet, og derfra går kjøttet fra mørt til tørt på sekunder. Denne retten har ikke det slingringsmonnet en bresering gir. Varm panne, kort tid, og opp av pannen før du er helt sikker.'}},
    {title:{en:'Flour on one side only', no:'Mel bare på den ene siden'},
     body:{en:'The flour on the veal does two jobs: it dries the surface so that it browns instead of steaming, and what is left behind in the pan thickens the wine into a sauce. Flour on the prosciutto would only go pasty and smother the one thing the ham is in the pan to do, which is crisp.',
           no:'Melet på kjøttet gjør to ting. Det tørker overflaten så den brunes i stedet for å dampe, og det som blir igjen i pannen, tykner vinen til en saus. Mel på prosciuttoen ville bare blitt klissete og kvalt det eneste skinken ligger i pannen for å gjøre, nemlig å bli sprø.'}},
  ],
  variations:[
    {title:{en:'Flat, not rolled', no:'Flat, ikke rullet'},
     body:{en:'Outside Rome saltimbocca is often rolled around the ham and the sage into a small bundle and pinned shut. That is a decent dish and a different one: a roll needs three or four minutes to heat through, and by then the veal has done what veal does. The Roman version lies flat for a reason.',
           no:'Utenfor Roma rulles saltimbocca ofte rundt skinken og salvien til en liten rull som festes igjen. Det er en grei rett, men en annen rett. En rull trenger tre til fire minutter for å bli gjennomvarm, og da har kalvekjøttet gjort det kalvekjøtt gjør. Den romerske versjonen ligger flatt av en grunn.'}},
    {title:{en:'If you cannot find veal', no:'Hvis du ikke får tak i kalvekjøtt'},
     body:{en:'Veal is thin on the ground in Norwegian shops. A slice of pork loin beaten just as thin comes closest and needs perhaps twenty seconds more on the meat side. Turkey breast works; chicken breast does not, because it dries out before the ham has crisped. Whatever you use, beat it thinner than looks sensible.',
           no:'Det er smått med kalvekjøtt i norske butikker. En skive svinefilet banket like tynt kommer nærmest og trenger kanskje tjue sekunder mer på kjøttsiden. Kalkunbryst går bra, mens kyllingbryst ikke gjør det, for det tørker ut før skinken er sprø. Uansett hva du bruker, må du banke det tynnere enn det ser fornuftig ut.'}},
    {title:{en:'Marsala, or nothing at all', no:'Marsala, eller ingenting'},
     body:{en:'Some Roman kitchens finish the pan with Marsala instead of white wine, which makes the sauce rounder and faintly sweet. Others use nothing but the butter and a spoonful of water. Both are orthodox; cream is not.',
           no:'Noen romerske kjøkken koker ut pannen med Marsala i stedet for hvitvin, og sausen blir rundere og så vidt søt. Andre bruker ikke annet enn smøret og en skje vann. Begge deler er like riktige, men fløte hører ikke hjemme her.'}},
  ],
},

];
