// Liguria recipes. Contract: docs/recipe-format.md. Both languages in one file; never narrated.
// Everything here follows the Liguria food reading (content/liguria.js, lesson 3): the seven-ingredient
// pesto and its mortar, focaccia di Recco as two unleavened sheets around fresh cheese, farinata as
// chickpea flour and a very hot pan, and the wild greens of the preboggion under a walnut sauce.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-42'] = [

{
  id:'pesto-alla-genovese', dish:'Pesto alla genovese', course:'base', lesson:3, serves:4, time:{prep:25, cook:0},
  hero:'pesto', tags:['sauce','basil','vegetarian','no-cook'],
  title:{en:'Pesto alla genovese', no:'Pesto alla genovese'},
  blurb:{en:'Seven ingredients and a mortar. Nothing is cooked, and the order things go in is part of the method.',
         no:'Sju ingredienser og en morter. Ingenting kokes, og rekkefølgen tingene går i, hører med til metoden.'},
  heroCaption:{en:'Basil, garlic, pine nuts, two cheeses, oil and salt, worked to a green cream against the sides of a marble mortar.',
               no:'Basilikum, hvitløk, pinjekjerner, to oster, olje og salt, arbeidet til en grønn krem mot sidene av en marmormorter.'},
  wines:['Pigato'],
  headnote:{
    en:'<p>Pesto alla genovese is seven ingredients and a mortar. The basil is <strong>Basilico Genovese DOP</strong>, protected since 2005, the small-leaved sweet variety grown on the terraces at <strong>Pra\'</strong> west of Genoa and picked young, before the leaves take on the mint flavour that basil from anywhere else has. The oil is Ligurian, pale and almost without bitterness, because its job is to carry the basil and not to argue with it.</p>'
      + '<p>The mortar is not nostalgia. A pestle crushes the leaf against stone and presses the aromatic oil out of it whole; a steel blade cuts and tears the tissue instead, and torn tissue browns as its enzymes meet the air. The blade also spins fast enough to warm what it is cutting, and warmth is the one thing basil will not take. Purists say a blender bruises the leaves and turns the sauce black, and they are describing exactly this.</p>'
      + '<p>The first written recipe is in Giovanni Battista Ratto\'s <em>La Cuciniera Genovese</em> of 1863, and Genoa holds a world championship every two years in which entrants are judged on their mortar technique. Two things are not negotiable: nothing here is cooked, and the sauce is loosened with pasta water rather than with more oil.</p>',
    no:'<p>Pesto alla genovese er sju ingredienser og en morter. Basilikumen er <strong>Basilico Genovese DOP</strong>, beskyttet siden 2005, den småbladede, søte sorten som dyrkes på terrassene ved <strong>Pra\'</strong> vest for Genova og plukkes ung, før bladene får den myntesmaken basilikum fra alle andre steder har. Oljen er ligurisk, lys og nesten uten bitterhet, for den skal bære basilikumen og ikke krangle med den.</p>'
      + '<p>Morteren er ikke nostalgi. En støter knuser bladet mot stein og presser den aromatiske oljen hel ut av det, mens et stålblad skjærer og river opp vevet, og revet vev brunes når enzymene i det møter luft. Kniven går dessuten fort nok til å varme opp det den kutter, og varme er det eneste basilikum ikke tåler. Puristene sier at en stavmikser knuser bladene og gjør sausen svart, og det er nettopp dette de beskriver.</p>'
      + '<p>Den første nedskrevne oppskriften står i Giovanni Battista Rattos <em>La Cuciniera Genovese</em> fra 1863, og Genova arrangerer et verdensmesterskap annethvert år der deltakerne bedømmes på morterteknikk. To ting er det ikke rom for å endre: ingenting her kokes, og sausen spes med pastavann og ikke med mer olje.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:50, u:'g', n:{en:'basil leaves', no:'basilikumblader'}, note:{en:'Genoese basil if you can get it; young small leaves, picked off the stems', no:'genovesisk basilikum hvis du får tak i den; unge, små blader, plukket av stilkene'}},
    {q:1,  u:'', n:{en:'garlic clove', no:'hvitløksfedd'}, note:{en:'young, with the green shoot taken out', no:'ungt, med den grønne spiren fjernet'}, round:'half'},
    {q:15, u:'g', n:{en:'pine nuts', no:'pinjekjerner'}},
    {q:45, u:'g', n:{en:'Parmigiano Reggiano', no:'Parmigiano Reggiano'}, note:{en:'finely grated', no:'finrevet'}},
    {q:20, u:'g', n:{en:'aged pecorino', no:'lagret pecorino'}, note:{en:'a hard Sardinian one is what Genoa uses', no:'Genova bruker en hard sardisk ost'}},
    {q:6,  u:'g', n:{en:'coarse sea salt', no:'grovt havsalt'}, note:{en:'the grains are the abrasive, so fine salt will not do the same work', no:'kornene er selve slipemiddelet, så fint salt gjør ikke den samme jobben'}},
    {q:70, u:'ml', n:{en:'Ligurian extra-virgin olive oil', no:'ligurisk extra virgin olivenolje'}, note:{en:'mild and sweet; a peppery Tuscan oil takes the sauce over', no:'mild og søt; en pepret toscansk olje overdøver sausen'}},
  ]}],
  steps:[
    {en:'Pick the leaves off the stems and keep the smallest. A coarse old leaf carries the mint note that the Genoese pick early to avoid.',
     no:'Plukk bladene av stilkene og behold de minste. Et grovt, gammelt blad bærer den myntetonen genoveserne plukker tidlig for å unngå.'},
    {en:'Rinse the leaves in cold water and dry them on a cloth without pressing them. Water left on a leaf thins the sauce and speeds the browning.',
     no:'Skyll bladene i kaldt vann og tørk dem på et klede uten å trykke på dem. Vann som blir sittende på bladet, tynner sausen og gjør at den brunes raskere.'},
    {en:'Crush the garlic with the coarse salt in a marble mortar until it is a smooth paste.',
     no:'Støt hvitløken sammen med det grove saltet i en marmormorter til en jevn masse.'},
    {en:'Add the pine nuts and work them in until the paste turns creamy.',
     no:'Ha i pinjekjernene og arbeid dem inn til massen blir kremet.'},
    {en:'Add the basil a handful at a time and crush it against the sides of the mortar with a circular motion, turning the pestle rather than hammering with it, until the leaves give up a green cream.',
     no:'Ha i basilikumen en håndfull om gangen og knus den mot sidene av morteren med sirkelbevegelser. Vri støteren rundt i stedet for å hamre med den, til bladene gir fra seg en grønn krem.'},
    {en:'Work in the two cheeses a little at a time, keeping the paste thick.',
     no:'Arbeid inn de to ostene litt om gangen, og hold massen tykk.'},
    {en:'Pour the oil in a thin stream, stirring with the pestle rather than beating, until the sauce holds together and falls slowly off the spoon.',
     no:'Hell oljen i en tynn stråle mens du rører med støteren i stedet for å piske, til sausen henger sammen og faller langsomt av skjeen.'},
    {en:'Taste and correct the salt. The cheeses bring salt of their own, so do this at the end and not before.',
     no:'Smak til med salt. Ostene har med seg salt selv, så gjør dette til slutt og ikke før.'},
    {en:'Serve it as it is, at room temperature, loosened with a spoonful of hot pasta water and with the pan off the heat. It is never cooked and never goes into a hot pan.',
     no:'Server den som den er, med romtemperatur, spedd med en skje varmt pastavann og med kjelen av platen. Den kokes aldri og skal aldri i en varm panne.'},
    {en:'To keep it, press it into a jar, cover the surface with a film of oil and refrigerate it for up to a week.',
     no:'Vil du ta vare på den, presser du den ned i et glass, dekker overflaten med en hinne olje og setter den kaldt i inntil en uke.'},
  ],
  notes:[
    {title:{en:'Crushing, not cutting', no:'Knusing, ikke kutting'},
     body:{en:'The aroma of basil sits in oil cells just under the surface of the leaf. A stone mortar presses those cells open and the oil runs out whole. A steel blade cuts the leaf into pieces instead, which exposes far more torn edge to the air, and the enzymes in torn tissue brown the sauce within minutes. The blade also heats what it spins. If a machine is the only option, chill the bowl and the blades, work in short bursts, and stir the cheese in by hand at the end.',
           no:'Aromaen i basilikum sitter i oljeceller like under overflaten av bladet. En morter av stein presser cellene opp, og oljen renner hel ut. Et stålblad skjærer bladet i biter i stedet, og da blir langt mer revet kant utsatt for luft, slik at enzymene i vevet gjør sausen brun i løpet av få minutter. Kniven blir dessuten varm av farten, og varmen går rett i sausen. Er en maskin den eneste utveien, kjøler du bollen og knivene, kjører i korte støt og rører inn osten for hånd til slutt.'}},
    {title:{en:'The order is the method', no:'Rekkefølgen er metoden'},
     body:{en:'Garlic and salt go first because the salt grains are the abrasive that breaks the clove down, and because a mortar with something in it already grips the next thing. The pine nuts come second: their fat lines the stone and softens the blow the leaves take. The cheese follows and the oil comes last, because fat coats the crushed leaf and shuts the air out of it. Reverse the order and you get a green sauce that is grey by the time it reaches the table.',
           no:'Hvitløk og salt går først, fordi saltkornene er slipemiddelet som bryter feddet ned, og fordi en morter som allerede har noe i seg, får bedre tak på det neste. Pinjekjernene kommer som nummer to, for fettet i dem kler steinen og demper støtet bladene får. Så følger osten, og oljen kommer til slutt, fordi fett legger seg rundt det knuste bladet og stenger luften ute. Snur du rekkefølgen, får du en grønn saus som er grå når den kommer på bordet.'}},
    {title:{en:'Pasta water, not more oil', no:'Pastavann, ikke mer olje'},
     body:{en:'Pesto that is too stiff for the pasta is loosened with a spoonful of the water the pasta boiled in. The dissolved starch holds oil and cheese in an emulsion that clings to every strand, where extra oil only slides off and gathers in the bottom of the bowl.',
           no:'Er pestoen for stiv til pastaen, spes den med en skje av vannet pastaen kokte i. Den oppløste stivelsen holder olje og ost i en emulsjon som henger ved hver tråd, mens mer olje bare glir av og samler seg i bunnen av bollen.'}},
  ],
  variations:[
    {title:{en:'The two cheeses', no:'De to ostene'},
     body:{en:'Genoa uses Parmigiano for sweetness and a hard aged pecorino for the salty edge, in roughly two parts to one. Some families use Parmigiano alone, which gives a rounder and milder sauce. Nobody uses pecorino alone.',
           no:'Genova bruker Parmigiano for sødmen og en hard, lagret pecorino for det salte draget, omtrent to deler mot én. Noen familier bruker bare Parmigiano, og da blir sausen rundere og mildere. Ingen bruker pecorino alene.'}},
    {title:{en:'How much garlic', no:'Hvor mye hvitløk'},
     body:{en:'One clove to a good handful of basil is the Genoese measure, and it is milder than most people expect. Cooks in the hills behind the city use two or three. If raw garlic sits badly with you, drop the clove into boiling water for a minute first.',
           no:'Ett fedd til en god håndfull basilikum er det genovesiske målet, og det er mildere enn de fleste venter seg. Kokker i åsene bak byen bruker to eller tre. Tåler du rå hvitløk dårlig, legger du feddet i kokende vann et minutt først.'}},
    {title:{en:'Freezing it', no:'Frysing'},
     body:{en:'Pesto freezes well in small portions if the cheese is left out, and the cheese is grated in when it thaws. Frozen with the cheese already in it, the sauce comes back grainy.',
           no:'Pesto lar seg fryse godt i små porsjoner hvis osten holdes utenfor, og osten rives i når den tines. Fryser du den med osten i, kommer sausen tilbake kornete.'}},
  ],
},

{
  id:'trofie-al-pesto', dish:'Trofie', course:'primo', lesson:3, serves:4, time:{prep:60, cook:15},
  hero:'trofie', tags:['pasta','pesto','potato','vegetarian'],
  title:{en:'Trofie al pesto', no:'Trofie al pesto'},
  blurb:{en:'The twisted pasta of the Golfo Paradiso, boiled in one pot with potato and green beans and turned through pesto off the heat.',
         no:'Den vridde pastaen fra Golfo Paradiso, kokt i én gryte med poteter og grønne bønner og vendt i pesto med kjelen av platen.'},
  heroCaption:{en:'Trofie rolled by hand: a pinch of dough pushed across the board with the palm until it twists and tapers at both ends.',
               no:'Trofie rullet for hånd. En klype deig skyves over brettet med håndflaten til den vrir seg og blir spiss i begge ender.'},
  wines:['Vermentino'],
  headnote:{
    en:'<p>Trofie is a shape rather than a dish. The small twisted curls come from <strong>Recco</strong> and the villages of the Golfo Paradiso east of Genoa, they are made of nothing but flour and water, and they are rolled one at a time between the palm and the board. In Liguria they are eaten with one sauce above all others, and the plate has a name of its own, <em>trofie al pesto</em>.</p>'
      + '<p>The twist is the whole point. A ridged spiral holds a thin, oily sauce that would slide straight off a smooth shape, and the tapered ends cook through while the thick middle stays firm, so a single piece has two textures in it. None of that survives a floured board, because the curl comes from friction between the dough and the wood.</p>'
      + '<p>The potatoes and the green beans go into the same pot, a habit written down for trenette and kept for trofie. The potato softens and carries the sauce, the bean stays crisp, and the starch the two of them leave behind thickens the water that later loosens the pesto. The sauce itself is never heated; it meets the pasta in a warm bowl, away from the stove.</p>',
    no:'<p>Trofie er en form mer enn en rett. De små vridde krøllene kommer fra <strong>Recco</strong> og landsbyene i Golfo Paradiso øst for Genova, de lages av ingenting annet enn mel og vann, og de rulles én om gangen mellom håndflaten og brettet. I Liguria spises de med én saus framfor noen annen, og retten har fått sitt eget navn, <em>trofie al pesto</em>.</p>'
      + '<p>Vridningen er hele poenget. En spiral med riller holder på en tynn og oljete saus som ville glidd rett av en glatt form, og de spisse endene blir gjennomkokte mens den tykke midten holder seg fast, slik at én og samme bit har to konsistenser i seg. Ingenting av dette overlever et melet brett, for krøllen kommer av friksjonen mellom deigen og treverket.</p>'
      + '<p>Potetene og de grønne bønnene går i den samme gryten. Vanen er skrevet ned for trenette og holdt i hevd for trofie: poteten blir myk og bærer sausen, bønnen holder seg sprø, og stivelsen de to gir fra seg, tykner vannet som senere sper pestoen. Selve sausen varmes aldri, men møter pastaen i en varm bolle, borte fra platen.</p>'},
  ingredients:[
    { group:{en:'For the trofie', no:'Til trofiene'}, items:[
      {q:400, u:'g', n:{en:'‘00’ flour', no:'mel type 00'}, note:{en:'a fifth of it durum semolina gives more bite', no:'en femtedel durumsemule gir mer tyggemotstand'}},
      {q:200, u:'ml', n:{en:'water', no:'vann'}, note:{en:'lukewarm; hold a little back, flours differ', no:'lunkent; hold igjen litt, for mel er ulikt'}},
      {q:5,   u:'g', n:{en:'salt', no:'salt'}},
    ]},
    { group:{en:'In the pot', no:'I gryten'}, items:[
      {q:300, u:'g', n:{en:'waxy potatoes', no:'faste poteter'}, note:{en:'peeled and cut in dice of about 1 cm', no:'skrelt og skåret i terninger på omkring 1 cm'}},
      {q:150, u:'g', n:{en:'green beans', no:'grønne bønner'}, note:{en:'topped and snapped in half', no:'renset og brukket i to'}},
      {q:4,   u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:20,  u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
    ]},
    { group:{en:'To finish', no:'Til servering'}, items:[
      {q:250, u:'g', n:{en:'pesto alla genovese', no:'pesto alla genovese'}, note:{en:'one batch of the recipe before this one', no:'én porsjon av oppskriften foran denne'}},
      {q:30,  u:'g', n:{en:'Parmigiano Reggiano', no:'Parmigiano Reggiano'}, note:{en:'grated, at the table', no:'revet, ved bordet'}},
    ]},
  ],
  steps:[
    {en:'Stir the salt into the water, pour it into the flour a little at a time and gather it into a firm dough. It should be harder than an egg pasta and just short of dry.',
     no:'Rør saltet ut i vannet, hell det i melet litt om gangen, og samle det til en fast deig. Den skal være hardere enn en eggpasta og så vidt ikke tørr.'},
    {en:'Knead for 10 minutes, until the surface is smooth and no dry flour is left in it.',
     no:'Elt i 10 minutter, til overflaten er glatt og det ikke er tørt mel igjen i deigen.'},
    {en:'Cover the dough and rest it for half an hour, so the gluten relaxes and the pieces roll instead of springing back.',
     no:'Dekk deigen til og la den hvile en halvtime, så gluten slapper av og bitene lar seg rulle i stedet for å sprette tilbake.'},
    {en:'Pinch off a piece the size of a chickpea, lay it on a wooden board with no flour on it, and push it away from you with the base of your palm while drawing your hand slightly sideways.',
     no:'Klyp av en bit på størrelse med en kikert, legg den på et trebrett uten mel, og skyv den fra deg med undersiden av håndflaten mens du trekker hånden litt til siden.'},
    {en:'Keep the board bare. The curl comes from friction, and on a floured board the dough only slides.',
     no:'Hold brettet fritt for mel. Krøllen kommer av friksjon, og på et melet brett glir deigen bare.'},
    {en:'Lay the finished trofie on a floured cloth as you make them and leave them to dry for 20 minutes.',
     no:'Legg de ferdige trofiene på et melet klede etter hvert som de blir til, og la dem tørke i 20 minutter.'},
    {en:'Bring the water to the boil, salt it, and put the potatoes in first. Give them 5 minutes.',
     no:'Kok opp vannet, salt det, og ha potetene i først. Gi dem 5 minutter.'},
    {en:'Add the beans, cook for 4 minutes more, then add the trofie, which need 4 to 5 minutes and are done when they float and the twist is tender to the tooth.',
     no:'Ha i bønnene, kok videre i 4 minutter, og ha så i trofiene, som trenger 4 til 5 minutter og er ferdige når de flyter opp og vridningen er mør mot tannen.'},
    {en:'Warm a wide serving bowl and loosen the pesto in it with two spoonfuls of the cooking water, taken from the pot and not from the tap.',
     no:'Varm en vid serveringsbolle og spe pestoen i den med to skjeer av kokevannet, tatt fra gryten og ikke fra springen.'},
    {en:'Lift everything out with a spider, or drain it while keeping some of the water back.',
     no:'Løft alt opp med en hullsleiv, eller hell av vannet og ta vare på noe av det.'},
    {en:'Turn the pasta, the potato and the beans through the pesto in the bowl, loosening with more water until the sauce coats everything, and serve at once with Parmigiano. The bowl never goes back on the heat.',
     no:'Vend pasta, poteter og bønner i pestoen i bollen, spe med mer vann til sausen dekker alt, og server med en gang med Parmigiano. Bollen skal aldri tilbake på platen.'},
  ],
  notes:[
    {title:{en:'Why the board is bare', no:'Derfor er brettet uten mel'},
     body:{en:'A trofia is neither cut nor moulded; it is rolled, and the dough has to grip the wood at one end while the palm drags the other. Flour breaks that grip and you get a smooth worm with no spiral in it. If the dough sticks instead of curling it is too wet, and the answer is to work a little more flour into the whole batch rather than onto the board.',
           no:'En trofia blir verken skåret eller formet, men rullet, og deigen må ha tak i treverket i den ene enden mens håndflaten drar den andre. Mel bryter det taket, og da får du en glatt orm uten spiral i seg. Klistrer deigen seg i stedet for å krølle seg, er den for våt, og da elter du litt mer mel inn i hele porsjonen, ikke på brettet.'}},
    {title:{en:'One pot, three things', no:'Én gryte, tre ting'},
     body:{en:'The potato is not filler. It breaks down a little at the edges and thickens the water, which is the liquid that later emulsifies the pesto, and it carries sauce in a way pasta cannot, so a forkful has soft, firm and crisp in it at once. Cut it small enough to finish with the pasta and the arithmetic of the pot takes care of itself.',
           no:'Poteten er ikke fyllmasse. Den løser seg litt opp i kantene og tykner vannet, og denne væsken binder pestoen senere. Den bærer også saus på en måte pasta ikke kan, slik at én gaffel har mykt, fast og sprøtt i seg på én gang. Skjærer du den liten nok til å bli ferdig samtidig med pastaen, ordner regnestykket i gryten seg selv.'}},
    {title:{en:'The sauce meets the pasta, not the pan', no:'Sausen møter pastaen, ikke pannen'},
     body:{en:'Basil above about 50 °C goes dark and flat, and the cheese in the pesto strings instead of melting into the water. A warmed bowl and hot cooking water give all the heat the dish needs. Anything more and the sauce turns from green to olive on the way to the table.',
           no:'Over omtrent 50 °C blir basilikumen mørk og flat, og osten i pestoen trekker seg til tråder i stedet for å gå opp i vannet. En varm bolle og varmt kokevann gir all den varmen retten trenger. Mer enn det, og sausen går fra grønn til oliven på vei til bordet.'}},
  ],
  variations:[
    {title:{en:'Trenette and mandilli', no:'Trenette og mandilli'},
     body:{en:'Pesto is at home on three shapes. Trenette, a flat ribbon, is the older partner for the potatoes and the beans, while <em>mandilli de sæa</em>, the silk handkerchiefs of thin egg pasta, are the grand version and are served with the sauce alone.',
           no:'Pesto hører hjemme på tre former. Trenette, et flatt bånd, er den eldste følgesvennen til potetene og bønnene, mens <em>mandilli de sæa</em>, silkelommetørklær av tynn eggpasta, er den staselige varianten og serveres med sausen alene.'}},
    {title:{en:'Dried trofie', no:'Tørkede trofie'},
     body:{en:'Ligurian dried trofie are sold well outside the region and are a fair substitute. They need 12 to 15 minutes, so they go into the pot before the potatoes rather than after them.',
           no:'Liguriske tørkede trofie selges langt utenfor regionen og er en grei erstatning. De trenger 12 til 15 minutter, så de går i gryten før potetene og ikke etter dem.'}},
    {title:{en:'Without the vegetables', no:'Uten grønnsakene'},
     body:{en:'Trofie with nothing but pesto is perfectly Genoese and lets the sauce speak. You then need a little more of it, and the pasta water matters more, because the potato is no longer thickening it.',
           no:'Trofie med bare pesto er fullt ut genovesisk og lar sausen komme til orde. Da trenger du litt mer av den, og pastavannet betyr mer, siden poteten ikke lenger tykner det.'}},
  ],
},

{
  id:'focaccia-di-recco', dish:'Focaccia di Recco', course:'antipasto', lesson:3, serves:4, time:{prep:50, cook:8},
  hero:'recco', tags:['bread','cheese','oven','no-yeast'],
  title:{en:'Focaccia di Recco col formaggio', no:'Focaccia di Recco col formaggio'},
  blurb:{en:'Two sheets of unleavened dough stretched until you can read through them, with fresh cheese between and blisters from the hottest oven you have.',
         no:'To plater ugjæret deig strukket så tynne at du kan lese gjennom dem, med fersk ost imellom og blemmer fra den varmeste ovnen du har.'},
  heroCaption:{en:'Focaccia di Recco col formaggio: the top sheet blisters and browns in patches, and the cheese bubbles up through the holes.',
               no:'Focaccia di Recco col formaggio. Den øverste platen får blemmer og flekkvis farge, og osten bobler opp gjennom hullene.'},
  wines:['Vermentino'],
  headnote:{
    en:'<p>Genoa eats focaccia. In <strong>Recco</strong>, a town on the coast to the east, the same word means something else entirely. There is no yeast in it and nothing rises. Two sheets of dough are stretched until they are translucent, fresh cheese goes between them in lumps, and the whole thing spends a few minutes in an oven hot enough to blister the top before the cheese can run out of the sides.</p>'
      + '<p>It has protected status as <strong>Focaccia di Recco col formaggio IGP</strong>, granted in 2015, and it may only be made in Recco and three neighbouring towns. The rules cover the cheese, the thinness of the sheets and the pan, which is tinned copper. The cheese is <em>crescenza</em>, fresh, soft and faintly sour, sold across most of Europe under its other name, stracchino.</p>'
      + '<p>Two things decide the result at home. The dough has to be relaxed enough to stretch to paper without tearing, which comes from resting it rather than from working it harder, and the oven has to be as hot as it will go, because a sheet this thin must set and colour within minutes or it dries into a cracker.</p>',
    no:'<p>Genova spiser focaccia. I <strong>Recco</strong>, en by på kysten lenger øst, betyr det samme ordet noe helt annet. Det er ingen gjær i den, og ingenting hever. To deigplater strekkes til de er gjennomskinnelige, fersk ost legges imellom i klumper, og det hele står noen minutter i en ovn som er varm nok til å gi toppen blemmer før osten rekker å renne ut i sidene.</p>'
      + '<p>Den har beskyttet status som <strong>Focaccia di Recco col formaggio IGP</strong> fra 2015 og kan bare lages i Recco og tre nabobyer. Reglene dekker osten, hvor tynne platene skal være, og pannen, som er av fortinnet kobber. Osten er <em>crescenza</em>, fersk, myk og så vidt syrlig, og den selges i det meste av Europa under det andre navnet sitt, stracchino.</p>'
      + '<p>To ting avgjør resultatet hjemme. Deigen må være avslappet nok til å strekkes papirtynn uten å revne, og det får du ved å la den hvile, ikke ved å elte hardere. Ovnen må være så varm som den kan bli, for en så tynn plate må sette seg og få farge i løpet av minutter, ellers tørker den til en kjeks.</p>'},
  ingredients:[
    { group:{en:'For the dough', no:'Til deigen'}, items:[
      {q:500, u:'g', n:{en:'‘00’ flour', no:'mel type 00'}, note:{en:'a strong flour stretches further before it tears', no:'et sterkt mel lar seg strekke lenger før det revner'}},
      {q:250, u:'ml', n:{en:'water', no:'vann'}, note:{en:'lukewarm', no:'lunkent'}},
      {q:30,  u:'ml', n:{en:'extra-virgin olive oil', no:'extra virgin olivenolje'}},
      {q:10,  u:'g', n:{en:'salt', no:'salt'}},
    ]},
    { group:{en:'The cheese and the top', no:'Osten og toppen'}, items:[
      {q:500, u:'g', n:{en:'crescenza', no:'crescenza'}, note:{en:'stracchino is the same cheese under another name; keep it cold until it goes in', no:'stracchino er den samme osten under et annet navn; hold den kald til den skal i'}},
      {u:'', n:{en:'olive oil for the pan and the top', no:'olivenolje til pannen og toppen'}, scale:'none'},
      {u:'', n:{en:'coarse salt', no:'grovt salt'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Work the flour, water, oil and salt into a dough and knead it for 10 minutes, until it is smooth and elastic.',
     no:'Arbeid mel, vann, olje og salt sammen til en deig, og elt den i 10 minutter til den er glatt og elastisk.'},
    {en:'Divide it in two, one piece a little larger than the other. The larger one becomes the base.',
     no:'Del den i to, med det ene stykket litt større enn det andre. Det største blir bunnen.'},
    {en:'Oil both pieces, cover them and leave them at room temperature for half an hour. Nothing rises here; the rest is only there to relax the gluten so the dough will stretch.',
     no:'Pensle begge stykkene med olje, dekk dem til, og la dem stå med romtemperatur i en halvtime. Ingenting hever her, og hvilen er bare der for å slappe av gluten, slik at deigen lar seg strekke.'},
    {en:'Heat the oven as high as it will go, at least 270 °C, with a baking tray or a pizza stone on a low shelf. The pan you assemble in goes on top of that.',
     no:'Varm ovnen så høyt den går, minst 270 °C, med et stekebrett eller en pizzastein på en lav rille. Pannen du legger opp i, settes oppå den.'},
    {en:'Roll the larger piece out thin, then lift it onto the backs of your hands and stretch it outwards until it is translucent and you can see the grain of the board through it.',
     no:'Kjevle det største stykket tynt, løft det så over på håndbakene og strekk det utover til det er gjennomskinnelig og du kan se treverket i brettet gjennom det.'},
    {en:'Lay the sheet in an oiled pan with the surplus hanging over the rim, and leave it untrimmed for now.',
     no:'Legg platen i en oljet panne med det overflødige hengende utenfor kanten, og la det henge inntil videre.'},
    {en:'Dot the cheese over it in lumps the size of a walnut, a few centimetres apart. It is not spread out: the gaps are where the two sheets weld together.',
     no:'Legg osten utover i klumper på størrelse med en valnøtt, med noen centimeter mellom seg. Den skal ikke smøres utover, for i mellomrommene sveiser de to platene seg sammen.'},
    {en:'Stretch the second piece the same way, lay it over the top and press it down between the lumps.',
     no:'Strekk det andre stykket på samme måte, legg det over og trykk det ned mellom klumpene.'},
    {en:'Pinch small holes in the top sheet between the lumps, roll the two edges together against the rim and cut off what hangs over.',
     no:'Klyp små hull i den øverste platen mellom klumpene, rull de to kantene sammen mot pannekanten, og skjær av det som henger utenfor.'},
    {en:'Brush the top with oil and scatter a little coarse salt over it.',
     no:'Pensle toppen med olje og strø litt grovt salt over.'},
    {en:'Set the pan on the hot tray and bake for 6 to 8 minutes, until the surface is blistered and browned in patches and the cheese is bubbling at the holes. Cut it into squares with scissors and eat it hot.',
     no:'Sett pannen på det varme brettet og stek i 6 til 8 minutter, til overflaten har blemmer og flekkvis farge og osten bobler i hullene. Klipp den i firkanter med saks og spis den varm.'},
  ],
  notes:[
    {title:{en:'No yeast, and no waiting', no:'Ingen gjær, og ingen venting'},
     body:{en:'The whole architecture rests on there being nothing in the dough that can rise. Two unleavened sheets stay thin, so what you taste is cheese with a crisp skin on either side rather than bread with cheese in it. Steam from the cheese lifts the top sheet into blisters, and that is why the holes have to be there. Sealed shut, the sheet balloons and then splits wherever it likes.',
           no:'Hele oppbyggingen hviler på at det ikke finnes noe i deigen som kan heve. To ugjærede plater holder seg tynne, så du smaker ost med et sprøtt skall på hver side og ikke brød med ost i. Damp fra osten løfter den øverste platen til blemmer, og derfor må hullene være der. Er platen tett, blåser den seg opp og sprekker der den selv vil.'}},
    {title:{en:'Rest it, do not fight it', no:'La den hvile, ikke kjemp mot den'},
     body:{en:'A dough that springs back has not been kneaded too little; it has been rested too little. Gluten strands pulled tight need half an hour to slacken, and a rested dough then stretches to paper with almost no force. If a sheet tears while you are pulling it, stop, cover it and give it ten minutes more.',
           no:'En deig som spretter tilbake, er ikke for lite eltet, men for lite hvilt. Glutentråder som er strukket stramme, trenger en halvtime på å slakne, og en uthvilt deig lar seg da strekke papirtynn nesten uten makt. Revner platen mens du drar i den, stopper du, dekker den til og gir den ti minutter til.'}},
    {title:{en:'Heat, and more of it', no:'Varme, og mer av den'},
     body:{en:'A sheet this thin holds almost no water, so it has only minutes before it goes from crisp to dry. A very hot oven and a preheated tray colour the surface while the cheese is still molten. In Recco the pan is tinned copper for the same reason: copper takes heat straight into the base.',
           no:'En så tynn plate holder nesten ikke på vann, så den har bare minutter på seg før den går fra sprø til tørr. En svært varm ovn og et forvarmet brett gir overflaten farge mens osten fortsatt er smeltet. I Recco er pannen av fortinnet kobber av samme grunn, for kobber fører varmen rett inn i bunnen.'}},
  ],
  variations:[
    {title:{en:'The cheese', no:'Osten'},
     body:{en:'Crescenza and stracchino are the same fresh, faintly sour cheese, and that is what the rules ask for. Mozzarella carries too much water and floods the sheets, ricotta turns grainy in the heat, and a firm cream cheese never runs at all.',
           no:'Crescenza og stracchino er den samme ferske, så vidt syrlige osten, og det er den reglene krever. Mozzarella har for mye vann i seg og oversvømmer platene, ricotta blir kornete i varmen, og en fast kremost renner aldri ut.'}},
    {title:{en:'Outside Recco', no:'Utenfor Recco'},
     body:{en:'The IGP covers Recco and three neighbouring towns, so the same thing made anywhere else is simply <em>focaccia col formaggio</em>. It is sold that way up and down the Ligurian coast and nobody is offended.',
           no:'IGP-en dekker Recco og tre nabobyer, så det samme laget andre steder heter rett og slett <em>focaccia col formaggio</em>. Den selges slik langs hele den liguriske kysten, og ingen tar anstøt.'}},
    {title:{en:'Not the other focaccia', no:'Ikke den andre focacciaen'},
     body:{en:'Focaccia genovese is a different bread altogether: a yeasted slab about a centimetre thick, dimpled with the fingertips and flooded with oil and brine before it is baked. Genoa eats it for breakfast, dipped in a cappuccino.',
           no:'Focaccia genovese er et helt annet brød, en gjærbakt plate på omkring en centimeter, der gropene trykkes inn med fingertuppene og fylles med olje og saltlake før steking. Genova spiser den til frokost, dyppet i en cappuccino.'}},
  ],
},

{
  id:'farinata', dish:'Farinata', course:'antipasto', lesson:3, serves:4, time:{prep:15, cook:20},
  hero:'farinata', tags:['chickpea','street food','oven','vegan'],
  title:{en:'Farinata di ceci', no:'Farinata di ceci'},
  blurb:{en:'Chickpea flour, water, oil and salt, rested for hours and baked shallow in a very hot oven until the top blisters and the middle stays soft.',
         no:'Kikertmel, vann, olje og salt, hvilt i timevis og stekt tynt i en svært varm ovn til toppen får blemmer og midten holder seg myk.'},
  heroCaption:{en:'Farinata straight out of the pan: brown and crisp on top, custardy underneath, eaten hot with black pepper.',
               no:'Farinata rett ut av pannen. Den er brun og sprø på toppen, kremet under, og spises varm med sort pepper.'},
  wines:['Pigato'],
  headnote:{
    en:'<p>Farinata is chickpea flour, water, oil and salt, and it is older than either of Liguria\'s focacce. It is baked in a wide copper pan in a wood oven and sold by the slice from the bakery window, hot, with black pepper ground over it. Genoa has a story about where it came from: sacks of chickpeas in the hold of a galley coming home from the battle of Meloria in 1284 were soaked in seawater, and the crew dried the paste in the sun. The story is a story, but the dish is genuinely a poor one, made from the cheapest flour there was.</p>'
      + '<p>Chickpea flour has no gluten and nothing in it to develop, so the technique is entirely about water and heat. The batter is thin, three parts water to one of flour by weight, and it has to stand for hours. The flour takes up water slowly, and a grey foam rises to the top which is skimmed off and thrown away.</p>'
      + '<p>Then comes the heat. The pan goes into an oven at 250 °C or hotter, the batter goes in only a few millimetres deep, and it bakes until the top is brown and blistered while the inside is still soft enough to be called custardy. Shallow and hot is the rule. Deep or slow gives a dense yellow cake, and that is what most farinata made outside Liguria turns out to be.</p>',
    no:'<p>Farinata er kikertmel, vann, olje og salt, og den er eldre enn begge de liguriske focacciaene. Den stekes i en bred kobberpanne i vedovn og selges i skiver fra bakerivinduet, varm, med sort pepper malt over. Genova har en historie om hvor den kom fra: sekker med kikerter i lasterommet på en galei på vei hjem fra slaget ved Meloria i 1284 ble gjennomvåte av sjøvann, og mannskapet tørket massen i solen. Historien får stå for byens egen regning, men retten er virkelig fattigmannskost, laget av det billigste melet som fantes.</p>'
      + '<p>Kikertmel har ingen gluten og ingenting i seg som skal utvikles, så teknikken handler bare om vann og varme. Røren er tynn, tre deler vann mot én del mel etter vekt, og den må stå i timevis. Melet trekker til seg vann langsomt, og et grått skum stiger opp som skummes av og kastes.</p>'
      + '<p>Så kommer varmen. Pannen settes inn i en ovn på 250 °C eller mer, røren skal ikke være mer enn noen millimeter dyp, og den stekes til toppen er brun og full av blemmer mens innsiden fortsatt er så myk at den kan kalles kremet. Tynt og varmt er regelen. Dypt eller langsomt gir en tett, gul kake, og slik er det meste av farinataen som lages utenfor Liguria.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:250, u:'g', n:{en:'chickpea flour', no:'kikertmel'}, note:{en:'sifted; lumps do not dissolve later', no:'siktet, for klumper løser seg ikke opp senere'}},
    {q:750, u:'ml', n:{en:'water', no:'vann'}, note:{en:'three parts water to one of flour, by weight', no:'tre deler vann mot én del mel, etter vekt'}},
    {q:8,   u:'g', n:{en:'salt', no:'salt'}},
    {q:60,  u:'ml', n:{en:'extra-virgin olive oil', no:'extra virgin olivenolje'}, note:{en:'Ligurian and mild; most goes into the batter, the rest into the pan', no:'ligurisk og mild; det meste går i røren, resten i pannen'}},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, note:{en:'ground over it at the table', no:'malt over ved bordet'}, scale:'none'},
  ]}],
  steps:[
    {en:'Sift the chickpea flour into a bowl and whisk the water in a little at a time, so that no lumps form. The batter should be as thin as pouring cream.',
     no:'Sikt kikertmelet i en bolle og visp inn vannet litt om gangen, så det ikke danner seg klumper. Røren skal være tynn som kaffefløte.'},
    {en:'Stir in the salt, cover the bowl and leave it at room temperature for at least 4 hours, or overnight.',
     no:'Rør inn saltet, dekk bollen til, og la den stå med romtemperatur i minst 4 timer, gjerne natten over.'},
    {en:'Take the grey foam off the surface with a spoon and throw it away. It carries the raw, soapy taste that makes a bad farinata bitter.',
     no:'Ta det grå skummet av overflaten med en skje og kast det. Det bærer den rå, såpeaktige smaken som gjør en dårlig farinata bitter.'},
    {en:'Heat the oven as high as it will go, at least 250 °C, and put a wide, heavy metal pan in to heat with it.',
     no:'Varm ovnen så høyt den går, minst 250 °C, og sett inn en vid, tung metallpanne som varmes opp med den.'},
    {en:'Whisk most of the oil into the batter; it will have separated while it stood.',
     no:'Visp mesteparten av oljen inn i røren, for den har skilt seg mens den sto.'},
    {en:'Take the hot pan out, pour the rest of the oil into it and tilt it so the base is covered.',
     no:'Ta den varme pannen ut, hell resten av oljen i den, og vipp pannen rundt til bunnen er dekket.'},
    {en:'Pour in the batter to a depth of no more than 5 mm and stir it once with a fork, so the oil marbles through it.',
     no:'Hell i røren så den ikke blir dypere enn 5 mm, og rør én gang med en gaffel, så oljen marmorerer seg gjennom den.'},
    {en:'Bake high in the oven for 15 to 20 minutes, until the surface is brown in patches and blistered and the edges pull away from the pan.',
     no:'Stek høyt i ovnen i 15 til 20 minutter, til overflaten er flekkvis brun og full av blemmer og kantene slipper pannen.'},
    {en:'Test the middle with the tip of a knife. It should be set but still soft, never dry.',
     no:'Kjenn på midten med en knivspiss. Den skal være satt, men fortsatt myk, aldri tørr.'},
    {en:'Slide it out, grind black pepper over it, cut it into rough wedges and eat it hot, standing up, as they do in Genoa.',
     no:'Skyv den ut, mal sort pepper over, skjær den i grove biter, og spis den varm og stående, slik de gjør i Genova.'},
  ],
  notes:[
    {title:{en:'The rest is not idleness', no:'Hvilen er ikke lediggang'},
     body:{en:'Chickpea flour has no gluten to develop, but it does take up water slowly, and a batter used straight away tastes raw and feels gritty. Standing gives the starch and the protein time to swell, and it lets the saponins in the chickpea, the substances that make the grey foam, rise to where they can be skimmed off. Four hours is the minimum, a night is better, and the difference shows in the aftertaste.',
           no:'Kikertmel har ingen gluten som skal utvikles, men det tar opp vann langsomt, og en røre som brukes med en gang, smaker rått og kjennes grynete. Hvilen gir stivelse og protein tid til å svelle, og den lar saponinene i kikertene, stoffene som lager det grå skummet, stige opp dit de kan skummes av. Fire timer er minimum, en natt er bedre, og forskjellen viser seg i ettersmaken.'}},
    {title:{en:'Shallow and hot', no:'Tynt og varmt'},
     body:{en:'Farinata has two textures at once, and only heat gives you both. In a very hot oven the surface dries and browns within minutes while the batter underneath is still setting, so you get a crisp lid over a soft middle. In a cooler oven the whole depth cooks at the same rate and the result is a firm, even, dull cake. The pan in Genoa is copper because copper moves heat fast; a heavy steel or cast-iron pan, preheated, is the substitute.',
           no:'Farinata har to konsistenser på én gang, og bare varmen gir deg begge. I en svært varm ovn tørker og brunes overflaten i løpet av minutter mens røren under fortsatt setter seg, og da får du et sprøtt lokk over en myk midt. I en kaldere ovn stekes hele dybden i samme tempo, og resultatet blir en fast, jevn og kjedelig kake. Pannen i Genova er av kobber fordi kobber flytter varme fort, og en tung panne av stål eller støpejern, forvarmet, er erstatningen.'}},
    {title:{en:'Oil in the pan, not only in the batter', no:'Olje i pannen, ikke bare i røren'},
     body:{en:'The film of oil in a preheated pan fries the underside on contact and gives farinata its brown, faintly crisp base. Batter poured into a dry pan steams instead, sticks, and comes out pale. It is the same trick as a well-oiled focaccia tin, and it is worth carrying to anything baked shallow.',
           no:'Hinnen av olje i en forvarmet panne steker undersiden med en gang og gir farinataen den brune, litt sprø bunnen. Røre som helles i en tørr panne, damper i stedet, setter seg fast og kommer ut blek. Trikset er det samme som en godt oljet focacciaform, og det er verdt å ta med seg til alt som stekes tynt.'}},
  ],
  variations:[
    {title:{en:'Rosemary and onion', no:'Rosmarin og løk'},
     body:{en:'Ligurian bakeries sell it plain, with rosemary needles scattered over the batter, or with onion sliced paper-thin and laid on top. Both go on just before it goes into the oven, and neither should be more than a scatter.',
           no:'Liguriske bakerier selger den naturell, med rosmarinnåler strødd over røren, eller med papirtynn løk lagt oppå. Begge deler går på like før den settes i ovnen, og ingen av dem bør være mer enn et dryss.'}},
    {title:{en:'Panissa', no:'Panissa'},
     body:{en:'The same batter, cooked on the stove until it thickens like polenta and then left to set in a dish, becomes panissa. Cut cold into batons and fried, it is the Ligurian street snack that Sicily makes as panelle. One batter, two dishes, and the difference is only where the heat comes from.',
           no:'Koker du den samme røren på platen til den tykner som polenta og lar den stivne i en form, får du panissa. Skjærer du den kald i staver og steker den, har du den liguriske gatematen som Sicilia lager som panelle. Én røre, to retter, og forskjellen ligger bare i hvor varmen kommer fra.'}},
    {title:{en:'The size of the pan', no:'Størrelsen på pannen'},
     body:{en:'Farinata is judged on how thin it is, so a wider pan is always better than a deeper one. If yours is small, bake the batter in two goes rather than in one thick layer.',
           no:'Farinata bedømmes på hvor tynn den er, så en videre panne er alltid bedre enn en dypere. Har du bare en liten, steker du røren i to omganger i stedet for i ett tykt lag.'}},
  ],
},

{
  id:'pansoti-con-salsa-di-noci', dish:'Pansoti con salsa di noci', course:'primo', lesson:3, serves:4, time:{prep:90, cook:20},
  hero:'pansoti', tags:['pasta','greens','walnut','vegetarian'],
  title:{en:'Pansoti con salsa di noci', no:'Pansoti con salsa di noci'},
  blurb:{en:'Triangular parcels of wild greens under a walnut sauce that looks like cream and contains none.',
         no:'Trekantede pakker med ville urter under en valnøttsaus som ser ut som fløte og ikke inneholder noe av den.'},
  heroCaption:{en:'Pansoti in salsa di noci. The green of the filling shows through the pasta, and the sauce is pounded, never cooked.',
               no:'Pansoti i salsa di noci. Det grønne fyllet skinner gjennom pastaen, og sausen støtes, den kokes aldri.'},
  wines:['Vermentino'],
  headnote:{
    en:'<p>Pansoti are Liguria\'s own filled pasta, and the name is dialect for pot-bellied. There is no meat in them and no egg in the dough — the sheet is flour, water and a little white wine — because they belong to a kitchen built on the garden rather than on the sea. The filling is <strong>preboggion</strong>, the mixed wild herbs of the Ligurian hills: borage, chard, dandelion, chervil and a dozen others, gathered in spring and folded into the pies and the pasta fillings of the whole region.</p>'
      + '<p>The sauce is the other half of the dish. <em>Salsa di noci</em> is walnuts pounded in the same mortar the pesto comes out of, with garlic, a little bread soaked in milk, fresh cheese and marjoram, and loosened with oil. It is pale and thick and looks like a cream sauce, but Ligurian cooking reaches for marjoram rather than oregano and for nuts rather than cream, and what binds this one is walnut oil and swollen crumb.</p>'
      + '<p>Two things go wrong. A wet filling tears the pasta and waters the sauce, so the greens have to be wrung out hard; and walnut skins are bitter, so they come off before the nuts go into the mortar. As with pesto, the sauce is never heated.</p>',
    no:'<p>Pansoti er Ligurias egen fylte pasta, og navnet betyr tykkmaget på dialekt. Det er verken kjøtt i dem eller egg i deigen, for platen er mel, vann og litt hvitvin, og de hører hjemme i et kjøkken bygget på hagen mer enn på havet. Fyllet er <strong>preboggion</strong>, de blandede ville urtene fra de liguriske åsene: agurkurt, mangold, løvetann, kjørvel og et dusin andre, sanket om våren og brettet inn i paier og pastafyll i hele regionen.</p>'
      + '<p>Sausen er den andre halvdelen av retten. <em>Salsa di noci</em> er valnøtter støtt i den samme morteren som pestoen kommer ut av, med hvitløk, litt brød lagt i melk, fersk ost og merian, spedd med olje. Den er lys og tykk og ser ut som en fløtesaus, men ligurisk matlaging griper etter merian framfor oregano og etter nøtter framfor fløte, og denne bindes av valnøttolje og oppbløtt brødkrumme.</p>'
      + '<p>To ting går galt. Et vått fyll river opp pastaen og vanner ut sausen, så urtene må vris hardt tørre. Skallet på valnøttene er bittert, så det tas av før nøttene går i morteren. Som med pesto varmes heller ikke denne sausen.</p>'},
  ingredients:[
    { group:{en:'For the pasta', no:'Til pastaen'}, items:[
      {q:300, u:'g', n:{en:'‘00’ flour', no:'mel type 00'}},
      {q:130, u:'ml', n:{en:'water', no:'vann'}, note:{en:'lukewarm', no:'lunkent'}},
      {q:20,  u:'ml', n:{en:'dry white wine', no:'tørr hvitvin'}, note:{en:'traditional in the dough, and it makes the sheet easier to roll thin', no:'tradisjonelt i deigen, og det gjør platen lettere å kjevle tynn'}},
      {q:4,   u:'g', n:{en:'salt', no:'salt'}},
    ]},
    { group:{en:'For the filling', no:'Til fyllet'}, items:[
      {q:700, u:'g', n:{en:'mixed leafy greens', no:'blandede bladgrønnsaker'}, note:{en:'preboggion in Liguria; elsewhere chard, spinach, borage and something bitter such as dandelion', no:'preboggion i Liguria; ellers mangold, spinat, agurkurt og noe bittert, for eksempel løvetann'}},
      {q:150, u:'g', n:{en:'ricotta', no:'ricotta'}, note:{en:'in Genoa the fresh curd prescinsêua; drain it if it is wet', no:'i Genova brukes den ferske osten prescinsêua; la den renne av seg hvis den er våt'}},
      {q:50,  u:'g', n:{en:'Parmigiano Reggiano', no:'Parmigiano Reggiano'}, note:{en:'grated', no:'revet'}},
      {q:1,   u:'', n:{en:'egg', no:'egg'}, round:'half'},
      {u:'', n:{en:'marjoram', no:'merian'}, note:{en:'fresh and chopped; oregano is a different plant and too strong here', no:'fersk og hakket; oregano er en annen plante og for kraftig her'}, scale:'none'},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'For the salsa di noci', no:'Til salsa di noci'}, items:[
      {q:200, u:'g', n:{en:'shelled walnuts', no:'valnøttkjerner'}},
      {q:15,  u:'g', n:{en:'pine nuts', no:'pinjekjerner'}},
      {q:1,   u:'', n:{en:'garlic clove', no:'hvitløksfedd'}, round:'half'},
      {q:40,  u:'g', n:{en:'white bread', no:'loff'}, note:{en:'the crumb only, no crust', no:'bare det innerste, uten skorpe'}},
      {q:80,  u:'ml', n:{en:'milk', no:'melk'}},
      {q:50,  u:'g', n:{en:'ricotta', no:'ricotta'}},
      {q:30,  u:'g', n:{en:'Parmigiano Reggiano', no:'Parmigiano Reggiano'}, note:{en:'grated', no:'revet'}},
      {q:70,  u:'ml', n:{en:'extra-virgin olive oil', no:'extra virgin olivenolje'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'To cook', no:'Til koking'}, items:[
      {q:4,  u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:20, u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
    ]},
  ],
  steps:[
    {en:'Work the flour, water, wine and salt into a firm dough, knead it for 10 minutes and rest it under a bowl for half an hour.',
     no:'Arbeid mel, vann, vin og salt til en fast deig, elt den i 10 minutter, og la den hvile under en bolle en halvtime.'},
    {en:'Wash the greens and cook them in a covered pan with only the water still clinging to the leaves, until they collapse.',
     no:'Vask urtene og kok dem under lokk med bare det vannet som henger igjen på bladene, til de faller sammen.'},
    {en:'Drain them, let them cool, then squeeze them dry in your hands as hard as you can and chop them finely.',
     no:'Hell av vannet, la dem kjølne, klem dem så tørre i hendene så hardt du klarer, og hakk dem fint.'},
    {en:'Mix the greens with the ricotta, the Parmigiano, the egg, the marjoram and a little salt. The filling should hold its shape on a spoon.',
     no:'Bland urtene med ricotta, Parmigiano, egg, merian og litt salt. Fyllet skal holde formen på en skje.'},
    {en:'Drop the walnuts into boiling water for a minute and rub the brown skins off in a cloth. The bitterness sits in the skin.',
     no:'Legg valnøttene i kokende vann i ett minutt og gni de brune skallene av i et klede. Bitterheten sitter i skallet.'},
    {en:'Soak the bread in the milk, squeeze it out and keep it.',
     no:'Bløt brødet i melken, klem det ut, og ta vare på det.'},
    {en:'Crush the walnuts, the pine nuts and the garlic in a mortar with a pinch of salt until they are a paste, then work in the bread, the ricotta and the Parmigiano.',
     no:'Støt valnøttene, pinjekjernene og hvitløken i en morter med en klype salt til en jevn masse, og arbeid så inn brødet, ricottaen og Parmigianoen.'},
    {en:'Pour the oil in a thin stream and stir until the sauce is thick, pale and smooth. Set it aside; it is not cooked.',
     no:'Hell oljen i en tynn stråle og rør til sausen er tykk, lys og jevn. Sett den til side, for den skal ikke kokes.'},
    {en:'Roll the dough out until you can read through it, and cut it into squares of about 7 cm.',
     no:'Kjevle deigen til du kan lese gjennom den, og skjær den i ruter på omkring 7 cm.'},
    {en:'Put a small spoonful of filling on each square, fold it corner to corner into a triangle, press the air out from the middle towards the edges and seal the two sides with a damp fingertip.',
     no:'Legg en liten skje fyll på hver rute, brett den hjørne mot hjørne til en trekant, press luften ut fra midten mot kantene, og lukk de to sidene med en fuktig fingertupp.'},
    {en:'Boil them in salted water for 4 to 5 minutes, until they float and the sealed edge is tender. Loosen the sauce in a warm bowl with a spoonful of the cooking water, turn the drained pansoti through it and serve at once.',
     no:'Kok dem i saltet vann i 4 til 5 minutter, til de flyter opp og den lukkede kanten er mør. Spe sausen i en varm bolle med en skje kokevann, vend pansotiene i den så snart vannet har rent av, og server med en gang.'},
  ],
  notes:[
    {title:{en:'Wring the greens out', no:'Vri urtene tørre'},
     body:{en:'Cooked leaves hold a surprising amount of water, and every drop of it works against you. The water softens the pasta from the inside until the parcel splits in the pot, it dilutes the sauce on the plate, and it leaves the filling tasting of nothing in particular. Squeeze until no more comes out, then squeeze again. The same rule governs every spinach filling in Italy.',
           no:'Kokte blader holder på overraskende mye vann, og hver dråpe arbeider mot deg. Vannet mykner pastaen innenfra til pakken sprekker i gryten, det tynner ut sausen på tallerkenen, og det gjør at fyllet ikke smaker noe bestemt. Klem til det ikke kommer mer, og klem så en gang til. Den samme regelen gjelder alle spinatfyll i Italia.'}},
    {title:{en:'A cream sauce with no cream', no:'En fløtesaus uten fløte'},
     body:{en:'Walnuts are roughly two thirds oil, and pounding them releases it. The soaked bread supplies starch and swollen crumb, which hold that oil and the milk together in a pale emulsion, and the cheese thickens it further. Add cream and you have covered the walnut instead of carrying it. If the sauce splits, a spoonful of hot pasta water and a hard stir bring it back.',
           no:'Valnøtter er omtrent to tredeler olje, og støtingen frigjør den. Det oppbløtte brødet gir stivelse og svellet brødkrumme, som holder oljen og melken sammen i en lys emulsjon, og osten tykner den ytterligere. Har du fløte i, dekker du til valnøtten i stedet for å bære den fram. Skiller sausen seg, får du den tilbake med en skje varmt pastavann og kraftig røring.'}},
    {title:{en:'The skins come off', no:'Skallet skal av'},
     body:{en:'The brown skin of a walnut carries the tannin that makes the nut astringent, and a mortar drives it straight into the sauce. A minute in boiling water loosens it enough to rub off in a cloth, and the sauce goes from grey-brown and drying to pale and sweet. That minute is worth spending on any nut sauce.',
           no:'Det brune skallet på en valnøtt bærer garvestoffene som gjør nøtten snerpende, og en morter driver dem rett inn i sausen. Ett minutt i kokende vann løsner skallet nok til at det lar seg gni av i et klede, og sausen går fra gråbrun og tørkende til lys og søt. Det minuttet er verdt å bruke på enhver nøttesaus.'}},
  ],
  variations:[
    {title:{en:'What goes in the filling', no:'Hva som går i fyllet'},
     body:{en:'Preboggion is a gathered mixture and never the same twice. Something bitter — dandelion, borage, wild chicory — has to stand against the sweetness of the chard and the cheese. A filling of spinach alone is pleasant and flat.',
           no:'Preboggion er en sanket blanding og aldri den samme to ganger. Viktigst er det at noe bittert står mot sødmen fra mangolden og osten, enten det er løvetann, agurkurt eller sikori. Et fyll av bare spinat blir hyggelig og flatt.'}},
    {title:{en:'The sauce on other things', no:'Sausen til annet'},
     body:{en:'Salsa di noci is not tied to pansoti. It goes on trofie, on plain ravioli and on gnocchi, and a spoonful of it thinned with pasta water makes a sauce for boiled green vegetables.',
           no:'Salsa di noci er ikke bundet til pansoti. Den går på trofie, på vanlige ravioli og på gnocchi, og en skje av den, spedd med pastavann, blir en saus til kokte grønne grønnsaker.'}},
    {title:{en:'If you have no mortar', no:'Har du ingen morter'},
     body:{en:'A food processor does less damage here than it does to pesto, because there is no leaf to bruise and nothing green to oxidise. Work the nuts in short bursts, stopping short of a paste, and finish by hand with the bread and the cheese so the sauce keeps some texture.',
           no:'En foodprosessor gjør mindre skade her enn i pesto, for det finnes ikke noe blad å knuse og ikke noe grønt som kan oksidere. Kjør nøttene i korte støt til de nesten er en masse, og gjør resten for hånd med brødet og osten, så sausen beholder litt tyggemotstand.'}},
  ],
},

];
