// Lombardia recipes. Bilingual in one file: the quantities are written once so English and Norwegian
// cannot drift apart. Contract: docs/recipe-format.md. Checked by tools/recipecheck.py. Never narrated.
// Everything here follows the Lombardia readings (content/lombardia.js): the fat is butter, the rice is
// Carnaroli from the plain around Pavia, the saffron goes in near the end, risotto and ossobuco are one
// course, and pizzoccheri belong to the Valtellina reading rather than the Milanese one.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-25'] = [

{
  id:'risotto-alla-milanese', dish:'Risotto alla milanese', course:'primo', lesson:3, serves:4,
  time:{prep:15, cook:30}, hero:'risotto', tags:['rice','saffron','butter'],
  title:{en:'Risotto alla milanese', no:'Risotto alla milanese'},
  blurb:{en:'Milan on a plate: Carnaroli toasted in butter with marrow, stock a ladle at a time, and saffron that goes in at the end.',
         no:'Milano på en tallerken: Carnaroli ristet i smør med beinmarg, kraft én øse om gangen, og safran som går i mot slutten.'},
  heroCaption:{en:'Risotto allo zafferano served on its own. In Milan it is more often the bed for an ossobuco.',
               no:'Risotto allo zafferano servert alene. I Milano ligger den oftere under en ossobuco.'},
  wines:['Franciacorta'],
  headnote:{
    en:'<p>The city’s dish is <strong>risotto giallo</strong>, yellow with saffron, and it is built on rice from the flooded plain around Pavia. <strong>Carnaroli</strong>, bred in 1945, has the firmest grain and gives up its starch slowly, which is why it is the cook’s choice. Vialone Nano and Arborio both work and are both easier to cook to mush.</p>'
      + '<p>The legend attaches the saffron to the Duomo. In 1574 a Flemish glass painter working on the cathedral windows, Valerio di Fiandra, had an apprentice nicknamed Zafferano for his habit of adding saffron to his pigments, and at the master’s daughter’s wedding the apprentice put it in the rice as a joke. The first printed recipe is from 1809, and everything that defines the dish is already in it: rice toasted in butter with onion, stock added a ladle at a time, <strong>bone marrow</strong> for richness, saffron near the end and grated cheese to finish.</p>'
      + '<p>Two things are not open to negotiation. The saffron goes in near the end rather than at the start, and the butter and cheese are beaten in with the pan off the heat. The texture should be <em>all’onda</em>, a wave that moves when the plate is tilted; a risotto that sits still has been cooked dry. In Milan the dish belongs with ossobuco, and the two are served as one course.</p>',
    no:'<p>Byens rett er <strong>risotto giallo</strong>, gul av safran, og den bygger på ris fra den oversvømte sletten rundt Pavia. <strong>Carnaroli</strong>, som ble fremavlet i 1945, har det fasteste kornet og gir fra seg stivelsen langsomt, og derfor er den kokkenes valg. Vialone Nano og Arborio går også, men begge er lettere å koke i stykker.</p>'
      + '<p>Legenden knytter safranen til Duomo. I 1574 hadde den flamske glassmaleren Valerio di Fiandra, som arbeidet med katedralens vinduer, en lærling med tilnavnet Zafferano fordi han pleide å blande safran i pigmentene sine, og i bryllupet til mesterens datter puttet lærlingen den i risen som en spøk. Den første trykte oppskriften er fra 1809, og alt som definerer retten, står allerede der: ris ristet i smør med løk, kraft tilsatt én øse om gangen, <strong>beinmarg</strong> for fylde, safran mot slutten og revet ost til slutt.</p>'
      + '<p>To ting er ikke til forhandling. Safranen skal i mot slutten og ikke i begynnelsen, og smøret og osten røres inn med kjelen av platen. Konsistensen skal være <em>all’onda</em>, en bølge som beveger seg når tallerkenen vippes; en risotto som blir liggende stille, er kokt for tørr. I Milano hører retten sammen med ossobuco, og de to serveres som én rett.</p>'},
  ingredients:[
    { group:{en:'', no:''}, items:[
      {q:320, u:'g', n:{en:'Carnaroli rice', no:'Carnaroli-ris'}, note:{en:'Vialone Nano or Arborio at a pinch; never a long grain', no:'Vialone Nano eller Arborio om nødvendig, men aldri en langkornet ris'}},
      {q:50,  u:'g', n:{en:'beef bone marrow', no:'beinmarg'}, note:{en:'scooped out of a sawn marrow bone and chopped fine', no:'skrapt ut av et saget margbein og finhakket'}},
      {q:60,  u:'g', n:{en:'onion', no:'løk'}, note:{en:'chopped as fine as you can', no:'hakket så fint du klarer'}},
      {q:30,  u:'g', n:{en:'butter for the base', no:'smør til bunnen'}},
      {q:60,  u:'g', n:{en:'cold butter for the mantecatura', no:'kaldt smør til mantecaturaen'}, note:{en:'straight from the fridge, in small cubes', no:'rett fra kjøleskapet, i små terninger'}},
      {q:100, u:'ml', n:{en:'dry white wine', no:'tørr hvitvin'}},
      {q:1.2, u:'l', n:{en:'meat stock', no:'kjøttkraft'}, note:{en:'kept at a bare simmer beside the risotto pan', no:'holdes så vidt småkokende ved siden av risottopannen'}},
      {q:60,  u:'', n:{en:'saffron threads', no:'safrantråder'}, note:{en:'a good pinch; a sachet of powdered saffron does the job too', no:'en god klype; en pose safranpulver gjør også nytten'}},
      {q:60,  u:'g', n:{en:'Grana Padano', no:'Grana Padano'}, note:{en:'finely grated, at room temperature', no:'finrevet, med romtemperatur'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Heat the stock and hold it just below a simmer. Cold stock poured onto hot rice stops the cooking and swells the grain unevenly.',
     no:'Varm kraften og hold den rett under kokepunktet. Kald kraft som helles over varm ris, stopper kokingen og får kornet til å svelle ujevnt.'},
    {en:'Crush the saffron threads between your fingers into a small bowl and cover them with a little of the hot stock. Leave them to bleed while you cook.',
     no:'Knus safrantrådene mellom fingrene ned i en liten bolle og dekk dem med litt av den varme kraften. La dem trekke mens du lager resten.'},
    {en:'Melt the marrow with the butter for the base in a wide, heavy pan over low heat, then soften the onion in it for about eight minutes without letting it colour.',
     no:'Smelt margen sammen med smøret til bunnen i en vid, tykkbunnet panne på svak varme, og la løken mykne i den i omtrent åtte minutter uten å ta farge.'},
    {en:'Turn the heat up, tip in the rice and stir it for two or three minutes until the grains are hot to the touch, glassy at the edge and still chalky white in the middle.',
     no:'Skru opp varmen, ha i risen og rør i to–tre minutter til kornene er varme å ta på, glassaktige i kanten og fortsatt kritthvite i midten.'},
    {en:'Pour in the wine and stir until it has evaporated completely and the pan smells of rice rather than alcohol.',
     no:'Hell i vinen og rør til den er helt fordampet og pannen lukter ris og ikke alkohol.'},
    {en:'Add a ladle of hot stock, enough to barely cover the rice, and stir. As each ladle is drunk up, add the next, keeping the rice loose and moving.',
     no:'Ha i en øse med varm kraft, akkurat nok til å dekke risen, og rør. Etter hvert som hver øse er sugd opp, sper du med den neste, slik at risen holder seg løs og i bevegelse.'},
    {en:'Keep going for about sixteen minutes, tasting from the twelfth. The grain should end firm at the centre but with no chalk left in it.',
     no:'Fortsett i omtrent seksten minutter, og smak fra det tolvte minuttet. Kornet skal til slutt være fast i midten, men uten kritt igjen.'},
    {en:'Stir in the soaked saffron with the last ladle of stock, three or four minutes before the rice is done, and let the colour spread evenly.',
     no:'Rør inn den bløtlagte safranen sammen med den siste øsen kraft, tre–fire minutter før risen er ferdig, og la fargen fordele seg jevnt.'},
    {en:'Stop while the risotto is wetter than you want to serve it. It tightens on the way to the table.',
     no:'Stopp mens risottoen er våtere enn du vil servere den. Den strammer seg på veien til bordet.'},
    {en:'Take the pan off the heat, wait half a minute, then beat in the cold butter and the Grana hard until the risotto turns glossy and pulls together in one mass. Season with salt.',
     no:'Ta pannen av platen, vent et halvt minutt, og pisk så inn det kalde smøret og Granaen kraftig til risottoen blir blank og henger sammen. Smak til med salt.'},
    {en:'Let it rest for a minute, then serve on warm flat plates, shaking each one so the rice spreads out in a wave.',
     no:'La den hvile ett minutt, og server på varme, flate tallerkener. Rist på hver tallerken så risen legger seg utover i en bølge.'},
  ],
  notes:[
    {title:{en:'Why the rice is toasted first', no:'Hvorfor risen ristes først'},
     body:{en:'Two or three minutes in hot fat sets the outside of each grain, so it survives twenty minutes of stirring instead of dissolving. The starch then leaves the grain slowly, through the whole cooking, which is what builds the cream. Rice that goes straight into stock without that toasting gives up its starch all at once and ends as porridge with a hard centre.',
           no:'To–tre minutter i varmt fett fester overflaten på hvert korn, slik at det tåler tjue minutter med røring i stedet for å løse seg opp. Stivelsen slipper da ut langsomt gjennom hele kokingen, og den bygger kremen. Ris som går rett i kraften uten risting, gir fra seg all stivelsen på én gang og ender som grøt med hard kjerne.'}},
    {title:{en:'The mantecatura', no:'Mantecaturaen'},
     body:{en:'The last minute is a technique with its own name. Cold butter and grated cheese, beaten in with the pan off the heat, emulsify the starch the rice has already released into a glossy cream. Over the flame the same fat splits out and leaves you with buttery grains sitting in a puddle. It is the same physics that governs pecorino in the Roman pastas: cheese needs to be below roughly 65 °C to go into the sauce instead of into strings.',
           no:'Det siste minuttet er en teknikk med eget navn. Pisker du kaldt smør og revet ost inn med kjelen av platen, blir stivelsen risen allerede har gitt fra seg, til en blank krem. Over platen skiller det samme fettet seg ut og etterlater smørete korn i en dam. Det er den samme fysikken som styrer pecorinoen i de romerske pastarettene: osten må være under omtrent 65 °C for å gå opp i sausen i stedet for å trekke seg sammen til tråder.'}},
    {title:{en:'When the saffron goes in', no:'Når safranen skal i'},
     body:{en:'Saffron gives its colour in minutes and its perfume grudgingly. Twenty minutes of simmering drives off the volatile aromas and leaves the bitterness behind, which is why the 1809 recipe puts it near the end. Soaking it in hot stock first draws out the colour so the whole pan turns yellow from a small amount.',
           no:'Safran gir fra seg fargen på minutter, men duften kommer motvillig. Tjue minutter med koking driver av de flyktige aromaene og lar bitterheten bli igjen, og derfor kommer safranen mot slutten i oppskriften fra 1809. Bløtlegging i varm kraft trekker ut fargen først, slik at hele pannen blir gul av en liten mengde.'}},
  ],
  variations:[
    {title:{en:'With ossobuco', no:'Med ossobuco'},
     body:{en:'In Milan this is half a dish. The risotto goes on the plate and the braised veal shin sits on top of it, with a spoonful of the braising juices and the gremolata, and the two are eaten as a single course. Marrow appears twice, once stirred into the rice and once in the bone.',
           no:'I Milano er dette en halv rett. Risottoen legges på tallerkenen, og den braiserte kalveskanken legges oppå, med en skje kraft fra gryten og gremolataen. De to spises som én rett. Margen dukker opp to ganger, én gang rørt inn i risen og én gang i beinet.'}},
    {title:{en:'Without the marrow', no:'Uten margen'},
     body:{en:'Leave the marrow out and use a little more butter, and the dish becomes risotto allo zafferano, which is what most Milanese restaurants serve when it comes on its own. It is lighter and cleaner; the marrow is what makes the version that goes under the shin taste of the same pot.',
           no:'Utelater du margen og bruker litt mer smør, får du risotto allo zafferano, og det er den de fleste restaurantene i Milano serverer når retten kommer alene. Den blir lettere og renere i smaken, men margen er grunnen til at utgaven under skanken smaker av den samme gryten.'}},
    {title:{en:'Risotto al salto', no:'Risotto al salto'},
     body:{en:'What is left over is a Milanese dish in its own right. Chill it, press it into a small buttered pan in a thin cake and fry it slowly on both sides until a crisp crust forms and the inside is soft again. Nothing else does as much with cold risotto.',
           no:'Restene er en milanesisk rett i seg selv. Avkjøl dem, press dem ut som en tynn kake i en liten, smurt panne, og stek langsomt på begge sider til det danner seg en sprø skorpe og innsiden er myk igjen. Ingenting annet gjør så mye ut av kald risotto.'}},
  ],
},

{
  id:'ossobuco', dish:'Ossobuco', course:'secondo', lesson:3, serves:4,
  time:{prep:25, cook:105}, hero:'ossobuco', tags:['veal','braise','marrow'],
  title:{en:'Ossobuco alla milanese', no:'Ossobuco alla milanese'},
  blurb:{en:'Veal shin braised on the bone until the marrow can be spooned out, with a raw gremolata of parsley, garlic and lemon at the end.',
         no:'Kalveskank braisert på beinet til margen kan skjes ut, med en rå gremolata av persille, hvitløk og sitron til slutt.'},
  heroCaption:{en:'Ossobuco with its ring of marrow intact. The string has been cut off after cooking, not before.',
               no:'Ossobuco med margringen i behold. Hyssingen er klippet av etter kokingen, ikke før.'},
  wines:['Valtellina Superiore (Nebbiolo)','Oltrepò Pavese Pinot Nero'],
  headnote:{
    en:'<p><strong>Ossobuco</strong> means "bone with a hole", and the marrow inside is the point of the dish. The shin is sawn across the bone into slices about four centimetres thick, each with its ring of marrow, and cooked slowly until the meat lets go of the bone and the marrow can be spooned out.</p>'
      + '<p>The dish finishes with <em>gremolata</em>, parsley, garlic and lemon zest chopped fine and scattered over raw. It is not a garnish but the seasoning: a long braise cooks away everything fresh, and the gremolata puts it back.</p>'
      + '<p>Three things decide the result. The membrane around each slice has to be nicked, or it shrinks and pulls the meat into a cup. The slices are tied so they keep their shape and the marrow stays where it belongs. And the pot must never boil; it should barely tremble, or the meat comes out dry and stringy on the far side of the same two hours.</p>',
    no:'<p><strong>Ossobuco</strong> betyr «bein med hull», og margen inni er poenget med retten. Kalveskanken sages på tvers av beinet i skiver på rundt fire centimeter, hver med sin ring av marg, og kokes langsomt til kjøttet slipper beinet og margen kan skjes ut.</p>'
      + '<p>Retten avsluttes med <em>gremolata</em>, finhakket persille, hvitløk og sitronskall som strøs over rå. Den er ingen pynt, men selve krydderet: en lang braisering koker bort alt som er friskt, og gremolataen setter det tilbake.</p>'
      + '<p>Tre ting avgjør resultatet. Hinnen rundt hver skive må snittes, ellers krymper den og trekker kjøttet sammen til en skål. Skivene bindes med hyssing så de holder formen og margen blir liggende. Og gryten må aldri fosskoke; den skal så vidt skjelve, ellers blir kjøttet tørt og trevlete etter de samme to timene.</p>'},
  ingredients:[
    { group:{en:'', no:''}, items:[
      {q:4,   u:'', n:{en:'slices of veal shin', no:'skiver av kalveskank'}, round:'half', note:{en:'about 4 cm thick, cut across the bone from the hind shin, each with a ring of marrow', no:'rundt 4 cm tykke, skåret på tvers av beinet fra bakskanken, hver med en margring'}},
      {q:40,  u:'g', n:{en:'plain flour', no:'hvetemel'}, note:{en:'for dusting; what does not stick is shaken off', no:'til å vende i; det som ikke fester seg, ristes av'}},
      {q:60,  u:'g', n:{en:'butter', no:'smør'}},
      {q:80,  u:'g', n:{en:'onion', no:'løk'}, note:{en:'finely chopped', no:'finhakket'}},
      {q:40,  u:'g', n:{en:'carrot', no:'gulrot'}, note:{en:'finely chopped', no:'finhakket'}},
      {q:40,  u:'g', n:{en:'celery', no:'stilkselleri'}, note:{en:'finely chopped', no:'finhakket'}},
      {q:150, u:'ml', n:{en:'dry white wine', no:'tørr hvitvin'}},
      {q:400, u:'ml', n:{en:'meat stock', no:'kjøttkraft'}, note:{en:'hot, with more standing by in case the pan dries out', no:'varm, og ha mer klar i tilfelle gryten tørker inn'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
      {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
    ]},
    { group:{en:'For the gremolata', no:'Til gremolataen'}, items:[
      {q:20, u:'g', n:{en:'flat-leaf parsley', no:'bladpersille'}, note:{en:'leaves only', no:'bare bladene'}},
      {q:1,  u:'', n:{en:'garlic clove', no:'hvitløksfedd'}, round:'half'},
      {q:1,  u:'', n:{en:'unwaxed lemon', no:'ubehandlet sitron'}, round:'half', note:{en:'the zest only, taken off in fine shreds', no:'bare skallet, revet i fine strimler'}},
    ]},
  ],
  steps:[
    {en:'Cut through the membrane around the edge of each slice in three or four places, right down to the meat. It shrinks faster than the muscle and will curl the slice if you leave it whole.',
     no:'Snitt hinnen rundt kanten på hver skive på tre–fire steder, helt inn til kjøttet. Den krymper raskere enn muskelen og krøller skiven sammen hvis den får være hel.'},
    {en:'Tie a length of kitchen string around the rim of each slice, snug but not tight, so the meat stays on the bone and the marrow stays in the hole.',
     no:'Bind en hyssing rundt kanten på hver skive, tett, men ikke stramt, slik at kjøttet blir sittende på beinet og margen blir liggende i hullet.'},
    {en:'Season the slices, turn them in the flour and shake off everything that does not stick.',
     no:'Krydre skivene, vend dem i melet og rist av alt som ikke fester seg.'},
    {en:'Melt the butter in a heavy pan wide enough to hold the slices in one layer, and brown them on both sides until deep gold. Lift them out.',
     no:'Smelt smøret i en tykkbunnet gryte som er vid nok til å ta skivene i ett lag, og brun dem på begge sider til de er dypt gylne. Løft dem ut.'},
    {en:'Soften the onion, carrot and celery in the same butter over low heat for about ten minutes, until they are sweet and pale and have taken no colour.',
     no:'La løk, gulrot og selleri mykne i det samme smøret på svak varme i omtrent ti minutter, til de er søte og bleke uten å ha tatt farge.'},
    {en:'Return the slices to the pan, pour in the wine and let it evaporate, scraping the bottom as it goes.',
     no:'Legg skivene tilbake i gryten, hell i vinen og la den fordampe mens du skraper bunnen.'},
    {en:'Add hot stock until it comes about two-thirds of the way up the meat, bring the pan to the barest tremble and cover it.',
     no:'Spe med varm kraft til den står omtrent to tredeler opp på kjøttet, la gryten så vidt skjelve, og legg på lokk.'},
    {en:'Braise for an hour and a half over the lowest heat, or in the oven at 150 °C, turning the slices once and adding stock whenever the pan threatens to dry out.',
     no:'Braiser i halvannen time på svakest mulig varme, eller i ovnen på 150 °C. Snu skivene én gang, og spe med kraft hver gang gryten truer med å tørke inn.'},
    {en:'Test with a fork: it should slide into the meat without resistance, and the marrow should be soft all through.',
     no:'Prøv med en gaffel. Den skal gli inn i kjøttet uten motstand, og margen skal være myk tvers igjennom.'},
    {en:'Chop the parsley, garlic and lemon zest together as fine as you can, and do it now rather than an hour ago. Gremolata loses its edge within the hour.',
     no:'Hakk persille, hvitløk og sitronskall sammen så fint du klarer, og gjør det nå og ikke for en time siden. Gremolata mister spissen i løpet av en time.'},
    {en:'Lift the slices out, snip off the strings and reduce the juices over higher heat until they coat the back of a spoon.',
     no:'Løft ut skivene, klipp av hyssingen, og kok inn kraften på høyere varme til den legger seg som et belegg på baksiden av en skje.'},
    {en:'Spoon the sauce over the meat, scatter the gremolata on top and serve each portion on a bed of risotto alla milanese, with a small spoon for the marrow.',
     no:'Øs sausen over kjøttet, strø gremolataen på, og server hver porsjon på en seng av risotto alla milanese, med en liten skje til margen.'},
  ],
  notes:[
    {title:{en:'Why the shins are tied', no:'Hvorfor skankene bindes'},
     body:{en:'A shin slice is muscle wrapped in a ring of connective tissue with a hollow bone in the middle, and both parts move as they cook. Nicking the membrane stops it contracting into a cup; the string holds the whole slice flat so the meat does not fall off the bone and the marrow does not float out into the sauce. Cut the string only when the meat is on the plate.',
           no:'En skankeskive er muskel pakket inn i en ring av bindevev, med et hult bein i midten, og begge deler beveger seg under kokingen. Snittene i hinnen hindrer at den trekker seg sammen til en skål, og hyssingen holder hele skiven flat, slik at kjøttet ikke faller av beinet og margen ikke flyter ut i sausen. Klipp hyssingen først når kjøttet ligger på tallerkenen.'}},
    {title:{en:'Low, and long', no:'Svakt, og lenge'},
     body:{en:'The shin is full of collagen, and collagen turns to gelatine only after a long stretch between about 80 and 90 °C. A boiling pot goes past that: the muscle fibres tighten and squeeze out their water before the collagen has had time to melt, so the same ninety minutes give you dry meat in a thin sauce. If you can see more than the occasional bubble, the heat is too high.',
           no:'Skanken er full av kollagen, og kollagen blir til gelatin først etter lang tid mellom omtrent 80 og 90 °C. En gryte som fosskoker, går forbi det: muskelfibrene strammer seg og presser ut vannet før kollagenet har rukket å smelte, og da gir halvannen time tørt kjøtt i tynn saus. Ser du mer enn en boble i ny og ne, er varmen for høy.'}},
    {title:{en:'Gremolata is seasoning, not garnish', no:'Gremolata er krydder, ikke pynt'},
     body:{en:'Raw garlic, lemon zest and parsley carry volatile oils that a braise drives off within minutes. Chopped at the last moment and added off the heat, they give back the top notes the pot has lost, which is why a dish this rich tastes light. Cook the gremolata in the sauce and you have wasted it.',
           no:'Rå hvitløk, sitronskall og persille bærer flyktige oljer som en braisering driver av på minutter. Hakker du dem i siste liten og strør dem på med gryten av platen, gir de tilbake de høye tonene gryten har mistet, og derfor smaker en så fyldig rett lett. Koker du gremolataen i sausen, er den bortkastet.'}},
  ],
  variations:[
    {title:{en:'With tomato, or without', no:'Med tomat, eller uten'},
     body:{en:'The version above is <em>in bianco</em>, without tomato, and it is the one that suits saffron risotto. Many Milanese kitchens crush a little peeled tomato in with the stock, which darkens the sauce and sweetens it. Gremolata belongs to the white version; where the tomato goes in, the lemon often comes out.',
           no:'Utgaven over er <em>in bianco</em>, uten tomat, og det er den som passer til safranrisotto. Mange kjøkken i Milano moser litt hermetisk tomat ned i kraften, noe som gjør sausen mørkere og søtere. Gremolata hører til den hvite utgaven, og der tomaten går i, ryker sitronen ofte ut.'}},
    {title:{en:'Anchovy in the gremolata', no:'Ansjos i gremolataen'},
     body:{en:'Some families mash a salted anchovy fillet into the parsley and garlic. It disappears entirely and leaves behind a savoury depth that the lemon then cuts through. Try it on the second slice rather than the first.',
           no:'Noen familier moser en saltet ansjosfilet inn i persillen og hvitløken. Det forsvinner helt og etterlater en smaksrik dybde som sitronen skjærer gjennom. Prøv det på den andre skiven heller enn den første.'}},
    {title:{en:'Beef shin instead of veal', no:'Oksekjøtt i stedet for kalv'},
     body:{en:'Beef shin is cheaper, the slices are wider and the marrow ring is bigger, and the flavour is stronger and less delicate. Give it an extra hour and check the pan more often. Veal is what Milan means by the word, but a beef shin makes a better weekday pot.',
           no:'Okseskank er rimeligere, skivene er bredere og margringen større, og smaken er kraftigere og mindre fin. Gi den en time ekstra og se oftere til gryten. Kalvekjøtt er det Milano mener med ordet, men okseskanken gir en bedre hverdagsgryte.'}},
  ],
},

{
  id:'cotoletta-alla-milanese', dish:'Cotoletta alla milanese', course:'secondo', lesson:3, serves:4,
  time:{prep:20, cook:20}, hero:'cotoletta', tags:['veal','fried','butter'],
  title:{en:'Cotoletta alla milanese', no:'Cotoletta alla milanese'},
  blurb:{en:'A veal chop on the bone, breadcrumbed and fried in clarified butter until the crust is gold and the meat by the bone is still pink.',
         no:'En kalvekotelett på beinet, panert og stekt i klarnet smør til skorpen er gyllen og kjøttet inn mot beinet fortsatt er rosa.'},
  heroCaption:{en:'The chop keeps its bone, and the plate carries nothing but a wedge of lemon.',
               no:'Koteletten beholder beinet, og tallerkenen bærer ikke annet enn en sitronbåt.'},
  wines:['Franciacorta','Oltrepò Pavese Pinot Nero'],
  headnote:{
    en:'<p><strong>Cotoletta alla milanese</strong> is a veal rib chop on the bone, dipped in egg and breadcrumbs and fried in clarified butter until the crust is gold and the meat still pink. A document of 1134 from the canons of Sant’Ambrogio lists <em>lombolos cum panitio</em>, loin with breadcrumbs, and Milan takes that as its birth certificate. Vienna claims the schnitzel was born there and that Field Marshal Radetzky merely carried the Milanese version home; Milan says the opposite.</p>'
      + '<p>The butter is the whole argument, and it has to be clarified. The milk solids in ordinary butter start to burn at around 150 °C, while the clear fat left when they are removed will take nearly 200, and a breadcrumb crust needs that heat. The same crust turns gold in four minutes in clarified butter and black in two in butter straight from the packet.</p>'
      + '<p>The bone stays on. The modern <em>orecchia d’elefante</em>, a boneless cutlet beaten thin and fried until it hangs over the plate, is a restaurant invention of the last few decades and purists disapprove. This one is a chop: a finger thick, pink at the bone, and served with a wedge of lemon and nothing else.</p>',
    no:'<p><strong>Cotoletta alla milanese</strong> er en kalvekotelett på beinet, dyppet i egg og brødsmuler og stekt i klarnet smør til skorpen er gyllen og kjøttet fortsatt rosa. Et dokument fra 1134 fra kannikene ved Sant’Ambrogio nevner <em>lombolos cum panitio</em>, kam med brødsmuler, og Milano regner det som rettens fødselsattest. Wien hevder at schnitzelen ble født der, og at feltmarskalk Radetzky bare tok den milanesiske utgaven med hjem. Milano sier det motsatte.</p>'
      + '<p>Smøret er hele saken, og det må klarnes. Melketørrstoffet i vanlig smør begynner å svi seg rundt 150 °C, mens det klare fettet som blir igjen når tørrstoffet er fjernet, tåler nærmere 200, og en panert skorpe trenger den varmen. Den samme skorpen blir gyllen på fire minutter i klarnet smør og svart på to i smør rett fra pakken.</p>'
      + '<p>Beinet skal sitte på. Den moderne <em>orecchia d’elefante</em>, en beinfri kotelett banket tynn og stekt til den henger utover tallerkenen, er en restaurantoppfinnelse fra de siste tiårene, og puristene misliker den. Denne er en kotelett. Den er tykk som en finger og rosa inn mot beinet, og den serveres med en sitronbåt og ingenting annet.</p>'},
  ingredients:[
    { group:{en:'', no:''}, items:[
      {q:4,   u:'', n:{en:'veal rib chops on the bone', no:'kalvekoteletter på beinet'}, round:'half', note:{en:'about 2 cm thick, with the bone scraped clean at the end', no:'rundt 2 cm tykke, med beinet skrapt rent ytterst'}},
      {q:2,   u:'', n:{en:'eggs', no:'egg'}, round:'half', note:{en:'beaten with a pinch of salt', no:'vispet med en klype salt'}},
      {q:200, u:'g', n:{en:'fine dry breadcrumbs', no:'fine, tørre brødsmuler'}, note:{en:'grated from stale white bread, not the coarse orange kind', no:'revet av tørt loff, ikke den grove, oransje typen'}},
      {q:250, u:'g', n:{en:'butter for frying', no:'smør til steking'}, note:{en:'to be clarified; what is left over keeps in the fridge for weeks', no:'skal klarnes; det som blir til overs, holder seg i kjøleskapet i uker'}, scale:'none'},
      {q:1,   u:'', n:{en:'lemon', no:'sitron'}, round:'half', note:{en:'in wedges, to serve', no:'i båter, til servering'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Clarify the butter: melt it slowly without stirring, skim off the foam and pour the clear yellow fat away from the milky sediment at the bottom. Throw the sediment out; it is what burns.',
     no:'Klarne smøret: smelt det langsomt uten å røre, skum av det som legger seg på toppen, og hell det klare, gule fettet av det melkeaktige bunnfallet. Kast bunnfallet, for det er det som svir seg.'},
    {en:'Trim the chops, leaving a rim of fat, and nick that rim in two or three places so it cannot pull the meat out of shape in the pan.',
     no:'Renskjær kotelettene, men la en kant av fett sitte igjen, og snitt kanten på to–tre steder så den ikke trekker kjøttet ut av fasong i pannen.'},
    {en:'Press the eye of the meat out gently with the flat of your hand to an even thickness. This is a chop, not a scaloppina; it should not get thinner, only flatter.',
     no:'Press kjøttet forsiktig ut til jevn tykkelse med flat hånd. Dette er en kotelett og ingen scaloppina; den skal ikke bli tynnere, bare flatere.'},
    {en:'Beat the eggs in a wide dish and spread the breadcrumbs in another.',
     no:'Visp eggene i et vidt fat, og bre brødsmulene utover i et annet.'},
    {en:'Turn each chop in the egg and let the excess run off, then lay it in the crumbs and press them on hard, on both sides and right up to the bone. Crumbs that are not pressed on fall off in the pan.',
     no:'Vend hver kotelett i egget og la det renne av, legg den så i smulene og press dem godt fast på begge sider og helt inn til beinet. Smuler som ikke er presset fast, faller av i pannen.'},
    {en:'Leave the breaded chops in the fridge for a quarter of an hour so the crust sets against the meat.',
     no:'La de panerte kotelettene stå et kvarter i kjøleskapet, slik at skorpen fester seg til kjøttet.'},
    {en:'Heat the clarified butter in a heavy pan until a crumb dropped in sizzles briskly. It should come about halfway up the side of the chop.',
     no:'Varm det klarnede smøret i en tykkbunnet panne til en brødsmule freser friskt når du slipper den i. Det skal stå omtrent halvveis opp på siden av koteletten.'},
    {en:'Fry one chop, or at most two, at a time. A crowded pan drops the temperature of the fat and the crust soaks it up instead of sealing.',
     no:'Stek én kotelett om gangen, eller høyst to. En overfylt panne senker temperaturen i fettet, og skorpen suger det til seg i stedet for å tette seg.'},
    {en:'Give the first side about four minutes without moving it, until the crust is deep gold and lifts cleanly.',
     no:'Gi den første siden omtrent fire minutter uten å flytte på den, til skorpen er dypt gyllen og slipper pannen lett.'},
    {en:'Turn once and fry the second side for three or four minutes. The chop is done when the meat next to the bone is still faintly pink.',
     no:'Snu én gang, og stek den andre siden i tre–fire minutter. Koteletten er ferdig når kjøttet inn mot beinet fortsatt er svakt rosa.'},
    {en:'Lift it onto kitchen paper for a moment and salt it while the crust is still hot, so the salt sticks.',
     no:'Løft den over på kjøkkenpapir et øyeblikk, og salt mens skorpen fortsatt er varm, slik at saltet fester seg.'},
    {en:'Serve straight away with a wedge of lemon. In Milan the plate carries nothing else.',
     no:'Server med en gang, med en sitronbåt. I Milano bærer tallerkenen ikke annet.'},
  ],
  notes:[
    {title:{en:'Why the butter is clarified', no:'Hvorfor smøret klarnes'},
     body:{en:'Butter is fat, water and milk solids. The solids are protein and milk sugar, and they brown and then burn at around 150 °C, well below the temperature a breadcrumb crust wants. Melting the butter and pouring the clear fat off the sediment removes them and lifts the smoke point towards 200 °C, so you get the flavour of butter with the working heat of oil. Nothing else fries a crust like it.',
           no:'Smør består av fett, vann og melketørrstoff. Tørrstoffet er protein og melkesukker, og det bruner seg og svir seg rundt 150 °C, godt under den varmen en panert skorpe vil ha. Smelter du smøret og heller det klare fettet av bunnfallet, forsvinner tørrstoffet og røykpunktet stiger mot 200 °C, slik at du får smaken av smør med arbeidsvarmen til olje. Ingenting annet steker en skorpe på samme måte.'}},
    {title:{en:'What the bone is for', no:'Hva beinet gjør'},
     body:{en:'Bone conducts heat slowly, so the meat lying against it is the last to cook and stays pink while the crust is already done. It also holds the chop flat, keeps the juices in the thick part and gives you something to pick the last of it up by. The boneless orecchia d’elefante trades all three for surface area and a bigger plate.',
           no:'Bein leder varmen langsomt, så kjøttet som ligger inntil det, blir sist ferdig og holder seg rosa mens skorpen allerede er stekt. Beinet holder også koteletten flat, holder på saften i den tykke delen og gir deg noe å ta i når du vil ha med deg det siste. Den beinfrie orecchia d’elefante bytter alle tre bort mot større overflate og en større tallerken.'}},
    {title:{en:'One at a time', no:'Én om gangen'},
     body:{en:'A cold chop dropped into hot fat takes heat out of it. Two of them take out twice as much, and below about 160 °C the crumb stops sealing and starts drinking, which is the difference between a crisp crust and a greasy one. Fry them in turn and keep the finished ones warm in the oven with the door ajar.',
           no:'En kald kotelett som legges i varmt fett, tar varme ut av det. To tar ut dobbelt så mye, og under omtrent 160 °C slutter smulene å tette seg og begynner å drikke fettet, og der ligger forskjellen mellom en sprø og en fet skorpe. Stek dem etter tur, og hold de ferdige varme i ovnen med døren på gløtt.'}},
  ],
  variations:[
    {title:{en:'Orecchia d’elefante', no:'Orecchia d’elefante'},
     body:{en:'The elephant’s ear is the chop boned, beaten out until it covers the plate and fried until crisp all the way through. It is the version most Milan restaurants now serve, it is much quicker, and it is a different dish: all crust and no pink. The reading calls it an invention of the last decades, and so it is.',
           no:'Elefantøret er koteletten uten bein, banket ut til den dekker tallerkenen og stekt til den er sprø tvers igjennom. Det er den utgaven de fleste restaurantene i Milano serverer i dag, den går mye raskere, og den er en annen rett: bare skorpe og ikke noe rosa. Lesteksten kaller den en oppfinnelse fra de siste tiårene, og det er den.'}},
    {title:{en:'The crumbs', no:'Smulene'},
     body:{en:'Milanese cooks grate their own from stale white bread, which gives a fine, close crust that sits tight on the meat. Japanese panko gives a spikier, lighter crust that fries beautifully and is not Milanese. Ready-made orange crumbs are neither.',
           no:'Kokkene i Milano river sine egne av tørt loff, og det gir en fin, tett skorpe som sitter stramt på kjøttet. Japansk panko gir en piggere og lettere skorpe som steker seg nydelig, men den er ikke milanesisk. Ferdige oransje smuler er ingen av delene.'}},
    {title:{en:'And Vienna’s version', no:'Og utgaven fra Wien'},
     body:{en:'Wiener Schnitzel is veal too, but boneless, beaten thin, floured before the egg, and fried in enough fat to float so the crust puffs away from the meat. Milan keeps the bone and lets the crust cling. Which came first is an argument neither city intends to lose.',
           no:'Wienerschnitzel er også kalvekjøtt, men uten bein, banket tynn, vendt i mel før egget og stekt i så mye fett at den flyter, slik at skorpen buler ut fra kjøttet. Milano beholder beinet og lar skorpen sitte fast. Hvilken som kom først, er en strid ingen av byene har tenkt å tape.'}},
  ],
},

{
  id:'pizzoccheri', dish:'Pizzoccheri', course:'primo', lesson:2, serves:4,
  time:{prep:40, cook:25}, hero:'pizzoccheri', tags:['pasta','buckwheat','cheese','cabbage'],
  title:{en:'Pizzoccheri della Valtellina', no:'Pizzoccheri della Valtellina'},
  blurb:{en:'Buckwheat ribbons boiled with potato and cabbage, layered with Valtellina Casera and finished with butter browned with garlic and sage.',
         no:'Bokhvetebånd kokt sammen med potet og kål, lagt i lag med Valtellina Casera og avsluttet med smør brunet med hvitløk og salvie.'},
  heroCaption:{en:'A dish of pizzoccheri as it comes to the table, layered rather than stirred.',
               no:'En form med pizzoccheri slik den kommer på bordet, lagt i lag og ikke rørt sammen.'},
  wines:['Valtellina Superiore (Nebbiolo)'],
  headnote:{
    en:'<p><strong>Pizzoccheri</strong> are short, thick ribbons of buckwheat pasta from the Valtellina, cooked with potato and cabbage, layered with <strong>Valtellina Casera</strong> cheese and finished with butter, garlic and sage. The town of Teglio keeps an academy to defend the recipe, which tells you how seriously the valley takes it.</p>'
      + '<p>Buckwheat is a seed and not a grain, and it has no gluten. A dough of buckwheat alone falls apart in the water, which is why a share of wheat flour goes in with it, and why the sheet is rolled thicker than egg pasta. The ribbons never go al dente the way durum pasta does; they are meant to be soft.</p>'
      + '<p>Everything cooks in the same pot. The potatoes go in first, the cabbage after them and the pasta last, so that all three are ready at the same moment. The cheese melts from the heat held in the dish rather than over the flame, the browned butter goes over the top, and nothing is stirred: the dish is built in layers and carried to the table in it.</p>',
    no:'<p><strong>Pizzoccheri</strong> er korte, tykke bånd av bokhvetepasta fra Valtellina, kokt sammen med potet og kål, lagt i lag med osten <strong>Valtellina Casera</strong> og avsluttet med smør, hvitløk og salvie. Byen Teglio har et eget akademi som verner om oppskriften, og det sier noe om hvor alvorlig dalen tar den.</p>'
      + '<p>Bokhvete er et frø og ikke et korn, og den har ikke gluten. En deig av bokhvete alene faller fra hverandre i vannet, og derfor blandes den med en del hvetemel, og derfor kjevles platen tykkere enn til eggpasta. Båndene blir aldri al dente slik durumpasta blir; de skal være myke.</p>'
      + '<p>Alt koker i samme kjele. Potetene går i først, kålen etter dem og pastaen sist, slik at alle tre er ferdige samtidig. Osten smelter av varmen som ligger i retten og ikke over platen, det brunede smøret helles over, og ingenting røres sammen: retten bygges i lag og bæres til bordet i formen.</p>'},
  ingredients:[
    { group:{en:'For the pasta', no:'Til pastaen'}, items:[
      {q:400, u:'g', n:{en:'buckwheat flour', no:'bokhvetemel'}},
      {q:100, u:'g', n:{en:'plain wheat flour', no:'hvetemel'}, note:{en:'the gluten that holds the ribbon together', no:'glutenet som holder båndet sammen'}},
      {q:250, u:'ml', n:{en:'warm water', no:'lunkent vann'}, note:{en:'worked in a little at a time; the dough should stay firm', no:'arbeides inn litt om gangen; deigen skal holde seg fast'}},
    ]},
    { group:{en:'For the dish', no:'Til retten'}, items:[
      {q:300, u:'g', n:{en:'floury potatoes', no:'melne poteter'}, note:{en:'peeled and cut into chunks about 2 cm', no:'skrelt og skåret i biter på rundt 2 cm'}},
      {q:300, u:'g', n:{en:'savoy cabbage', no:'savoykål'}, note:{en:'or chard; thick stalks taken out, leaves in wide ribbons', no:'eller mangold; de tykkeste stilkene fjernes, og bladene skjæres i brede bånd'}},
      {q:250, u:'g', n:{en:'Valtellina Casera', no:'Valtellina Casera'}, note:{en:'in thin slices; a young Bitto or a Fontina melts the same way', no:'i tynne skiver; en ung Bitto eller en Fontina smelter på samme måte'}},
      {q:80,  u:'g', n:{en:'Grana Padano', no:'Grana Padano'}, note:{en:'finely grated', no:'finrevet'}},
      {q:150, u:'g', n:{en:'butter', no:'smør'}},
      {q:2,   u:'', n:{en:'garlic cloves', no:'hvitløksfedd'}, round:'half', note:{en:'peeled and left whole, to be fished out again', no:'skrelt og hele, og fiskes ut igjen'}},
      {q:8,   u:'', n:{en:'sage leaves', no:'salvieblader'}, round:'half'},
      {q:4,   u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:20,  u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
      {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Mix the two flours on a board, work in the warm water a little at a time and knead for about five minutes into a firm, smooth dough. Wrap it and let it rest for half an hour.',
     no:'Bland de to meltypene på et brett, arbeid inn det lunkne vannet litt om gangen, og elt i omtrent fem minutter til en fast og glatt deig. Pakk den inn og la den hvile en halvtime.'},
    {en:'Roll the dough out to a sheet about 3 mm thick, thicker than you would for egg pasta, because there is little gluten to hold a thin sheet together.',
     no:'Kjevle deigen ut til en plate på rundt 3 mm, tykkere enn du ville gjort med eggpasta, siden det er lite gluten som kan holde en tynn plate sammen.'},
    {en:'Cut the sheet into strips a hand wide, stack them and cut across into ribbons about 1 cm wide. Spread them out on a floured cloth.',
     no:'Skjær platen i strimler så brede som en hånd, legg dem oppå hverandre og skjær på tvers i bånd på rundt 1 cm. Bre dem utover på et melet klede.'},
    {en:'Bring the salted water to the boil in a large pot and cook the potatoes on their own for five minutes.',
     no:'Kok opp det saltede vannet i en stor kjele, og kok potetene alene i fem minutter.'},
    {en:'Add the cabbage and let it go for three minutes more, until the leaves have collapsed.',
     no:'Ha i kålen og la den koke tre minutter til, til bladene har falt sammen.'},
    {en:'Slide the pizzoccheri in and cook everything together for about eight minutes, until the ribbons float and a knife goes into a potato without resistance.',
     no:'Ha i pastaen og kok alt sammen i omtrent åtte minutter, til båndene flyter opp og en kniv går uten motstand inn i en potet.'},
    {en:'Meanwhile put the butter in a small pan with the whole garlic cloves and the sage, and heat it gently until it foams, quietens and smells of hazelnuts. Take the garlic out before it darkens.',
     no:'Legg imens smøret i en liten panne med de hele hvitløksfeddene og salvien, og varm det forsiktig til det bruser opp, faller til ro og lukter hasselnøtt. Ta ut hvitløken før den blir mørk.'},
    {en:'Warm the serving dish. Lift out a third of the pasta and vegetables with a slotted spoon, letting them drain well, and spread them in the bottom.',
     no:'Varm serveringsformen. Løft ut en tredel av pastaen og grønnsakene med hullsleiv, la dem renne godt av, og legg dem i bunnen.'},
    {en:'Cover with slices of Casera and a scattering of Grana, then build two more layers the same way and finish with cheese.',
     no:'Dekk med skiver av Casera og litt Grana, bygg to lag til på samme måte, og avslutt med ost.'},
    {en:'Pour the browned butter and the sage over the top and grind on pepper.',
     no:'Hell det brunede smøret og salvien over, og kvern over pepper.'},
    {en:'Let the dish stand for two or three minutes so the cheese melts through, then take it to the table and serve it without stirring.',
     no:'La formen stå i to–tre minutter så osten smelter gjennom, bær den så til bordet og server uten å røre.'},
  ],
  notes:[
    {title:{en:'Buckwheat is not wheat', no:'Bokhvete er ikke hvete'},
     body:{en:'Buckwheat is the seed of a plant related to rhubarb, and it contains no gluten at all. That is why the dough is bound with wheat flour, why the sheet has to stay thick, why the ribbons are short, and why they cook in eight minutes and are soft rather than al dente. Push the buckwheat share higher and the pasta tastes better and breaks up in the pot; the classic proportion is the compromise the valley settled on.',
           no:'Bokhvete er frøet til en plante i samme familie som rabarbra, og den inneholder ikke gluten i det hele tatt. Derfor bindes deigen med hvetemel, derfor må platen holdes tykk, derfor er båndene korte, og derfor koker de på åtte minutter og blir myke i stedet for al dente. Øker du andelen bokhvete, smaker pastaen bedre og går i stykker i kjelen, og det klassiske forholdet er kompromisset dalen har landet på.'}},
    {title:{en:'One pot, three timers', no:'Én kjele, tre klokker'},
     body:{en:'Potato, cabbage and pasta need different times, so they go in at different moments and come out together. The water ends up thick with buckwheat and potato starch, and the little of it that clings to the pasta is what lets the cheese melt into a sauce instead of sitting in a pool of butter. Drain well, but not bone dry.',
           no:'Potet, kål og pasta trenger ulik tid, så de går i til ulike tider og kommer opp samtidig. Vannet ender tykt av bokhvete- og potetstivelse, og den lille mengden som blir hengende på pastaen, er grunnen til at osten smelter til en saus i stedet for å ligge i en dam av smør. La vannet renne godt av, men ikke la pastaen bli helt tørr.'}},
    {title:{en:'Browned butter, and the garlic that leaves', no:'Brunet smør, og hvitløken som går ut'},
     body:{en:'Butter held over the heat past the point where its water has boiled off lets the milk solids toast, and that toasting is the hazelnut smell. Garlic and sage put into cold butter give up their oils slowly as it warms, which is why they go in at the start; but garlic left in past the colour change turns bitter and takes the whole dish with it, so it comes out before it browns.',
           no:'Når vannet i smøret har kokt bort, begynner melketørrstoffet å riste seg, og den ristingen er hasselnøttlukten. Hvitløk og salvie som legges i kaldt smør, gir fra seg oljene langsomt mens det varmes, og derfor går de i fra starten. Men hvitløk som blir liggende forbi fargeskiftet, blir bitter og drar hele retten med seg, så den tas ut før den bruner.'}},
  ],
  variations:[
    {title:{en:'The green', no:'Det grønne'},
     body:{en:'Savoy cabbage is the winter version and the one Teglio writes down. Chard is the summer answer, and some households use whatever green the garden has, including green beans. The cabbage version is heavier and sweeter; chard keeps the dish lighter.',
           no:'Savoykål er vinterutgaven og den Teglio skriver ned. Mangold er sommersvaret, og noen husholdninger bruker det grønne hagen har å by på, også grønne bønner. Kålutgaven er tyngre og søtere, mens mangold holder retten lettere.'}},
    {title:{en:'The cheese', no:'Osten'},
     body:{en:'Valtellina Casera is the valley’s own semi-hard cheese and melts into strings without going oily. A young Bitto, made in summer on the high pastures, is richer and much rarer, and is what a good restaurant in Sondrio will use. Fontina melts as well but tastes of the Aosta valley instead.',
           no:'Valtellina Casera er dalens egen halvfaste ost, og den smelter til tråder uten å bli oljete. En ung Bitto, laget om sommeren på høyfjellsbeitene, er fyldigere og langt sjeldnere, og det er den en god restaurant i Sondrio bruker. Fontina smelter like godt, men smaker av Aostadalen i stedet.'}},
    {title:{en:'From a packet', no:'Fra pakken'},
     body:{en:'Dried pizzoccheri are made in Teglio and sold across Lombardy, and they cook in the same pot in the same order, in ten minutes rather than eight. Rolling the sheet yourself is a Sunday job; the rest of the dish is the same either way.',
           no:'Tørkede pizzoccheri lages i Teglio og selges over hele Lombardia, og de kokes i samme kjele i samme rekkefølge, på ti minutter i stedet for åtte. Den som vil kjevle platen selv, må sette av en søndag, men resten av retten er den samme uansett.'}},
  ],
},

{
  id:'cassoeula', dish:'Cassoeula', course:'secondo', lesson:3, serves:4,
  time:{prep:30, cook:150}, hero:'cassoeula', tags:['pork','cabbage','braise','winter'],
  title:{en:'Cassoeula', no:'Cassoeula'},
  blurb:{en:'The Lombard winter pot: pork ribs, rind and sausage cooked down with savoy cabbage until the whole thing binds itself.',
         no:'Den lombardiske vintergryten: svineribbe, svor og pølse kokt sammen med savoykål til hele gryten binder seg selv.'},
  heroCaption:{en:'Cassoeula in the pot it is named after. The cabbage has collapsed into the sauce and holds everything together.',
               no:'Cassoeula i gryten den har navn etter. Kålen har falt sammen i sausen og holder alt sammen.'},
  wines:['Oltrepò Pavese Pinot Nero'],
  headnote:{
    en:'<p><strong>Cassoeula</strong> is Lombardy’s winter pot: pork ribs, rind, trotter and small sausages cooked with savoy cabbage, eaten around the feast of Sant’Antonio on 17 January. It is made from the parts of the pig that were left when the good cuts had been sold or cured, and the cabbage is the counterweight that makes them worth eating.</p>'
      + '<p>The date is not decoration. A savoy that has stood through a frost converts part of its starch to sugar and its leaves soften, so it cooks down sweeter and faster. That is why the dish belongs to January rather than to October, and why out of season you want the dark outer leaves and more time.</p>'
      + '<p>Two things decide whether the pot is good or merely heavy. The rind is almost pure collagen, and an hour and a half below a simmer turns it into the gelatine that gives cassoeula its body — no flour is involved, and none is wanted. The fat that renders out, on the other hand, has to be skimmed, more than once. Cooks who leave it in are the reason the dish has a reputation for sitting like a stone.</p>',
    no:'<p><strong>Cassoeula</strong> er vintergryten i Lombardia: svineribbe, svor, griselabb og små pølser kokt sammen med savoykål, spist rundt festdagen for Sant’Antonio 17. januar. Den er satt sammen av de delene av grisen som ble til overs når de gode stykkene var solgt eller spekt, og kålen er motvekten som gjør dem verdt å spise.</p>'
      + '<p>Datoen er ingen pynt. En savoykål som har stått gjennom frost, gjør om en del av stivelsen til sukker, og bladene mykner, slik at den koker seg søtere og raskere. Derfor hører retten til i januar og ikke i oktober, og derfor vil du utenom sesongen ha de mørke ytterbladene og bedre tid.</p>'
      + '<p>To ting avgjør om gryten blir god eller bare tung. Svoren er nesten bare kollagen, og halvannen time under kokepunktet gjør den om til gelatinet som gir cassoeula fylde. Det er ikke mel i gryten, og det trengs ikke. Fettet som smelter ut, må derimot skummes av, og mer enn én gang. Kokker som lar det bli igjen, har gitt retten et rykte for å ligge som en stein.</p>'},
  ingredients:[
    { group:{en:'', no:''}, items:[
      {q:800, u:'g', n:{en:'pork ribs', no:'svineribbe'}, note:{en:'cut into single ribs', no:'delt i enkeltbein'}},
      {q:200, u:'g', n:{en:'pork rind', no:'svor'}, note:{en:'scraped clean; it is what thickens the pot', no:'skrapt ren; det er den som gir gryten fylde'}},
      {q:1,   u:'', n:{en:'pig’s trotter', no:'griselabb'}, round:'half', note:{en:'split lengthways by the butcher', no:'delt på langs av slakteren'}},
      {q:250, u:'g', n:{en:'luganega or small pork sausages', no:'luganega eller små svinepølser'}, note:{en:'in short lengths, pricked', no:'i korte lengder, prikket med gaffel'}},
      {q:1000, u:'g', n:{en:'savoy cabbage', no:'savoykål'}, note:{en:'after the first frost if you can get it; the dark outer leaves matter most', no:'etter første frost hvis du får tak i den; de mørke ytterbladene betyr mest'}},
      {q:100, u:'g', n:{en:'onion', no:'løk'}, note:{en:'finely chopped', no:'finhakket'}},
      {q:60,  u:'g', n:{en:'carrot', no:'gulrot'}, note:{en:'finely chopped', no:'finhakket'}},
      {q:60,  u:'g', n:{en:'celery', no:'stilkselleri'}, note:{en:'finely chopped', no:'finhakket'}},
      {q:40,  u:'g', n:{en:'butter', no:'smør'}},
      {q:200, u:'ml', n:{en:'dry white wine', no:'tørr hvitvin'}},
      {q:400, u:'ml', n:{en:'meat stock', no:'kjøttkraft'}, note:{en:'water will do; the pot makes its own', no:'vann gjør nytten, for gryten lager sin egen'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
      {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Blanch the rind and the trotter in boiling water for ten minutes, then drain and rinse them. This takes off the strongest of the pork smell and starts the collagen moving.',
     no:'Forvell svoren og griselabben i kokende vann i ti minutter, hell av og skyll. Det tar bort det sterkeste av svinelukten og setter kollagenet i gang.'},
    {en:'Cut the rind into strips about a finger wide.',
     no:'Skjær svoren i strimler så brede som en finger.'},
    {en:'Brown the ribs in the butter in a heavy pot until they have colour on every side, then lift them out.',
     no:'Brun ribben i smøret i en tykkbunnet gryte til den har farge på alle sider, og løft den ut.'},
    {en:'Brown the sausages briefly in the same fat and set them aside. They go back in near the end, or they fall apart.',
     no:'Brun pølsene raskt i det samme fettet og sett dem til side. De går i igjen mot slutten, ellers faller de fra hverandre.'},
    {en:'Soften the onion, carrot and celery in the fat over low heat for about ten minutes, until they are sweet and have taken no colour.',
     no:'La løk, gulrot og selleri mykne i fettet på svak varme i omtrent ti minutter, til de er søte og ikke har tatt farge.'},
    {en:'Return the ribs and add the rind and the trotter, pour in the wine and let it evaporate.',
     no:'Legg ribben tilbake, ha i svoren og griselabben, hell i vinen og la den fordampe.'},
    {en:'Add stock to come halfway up the meat, cover, and cook at the barest simmer for an hour and a half, until the rind cuts with the edge of a spoon.',
     no:'Spe med kraft til den står halvveis opp på kjøttet, legg på lokk, og la det så vidt småkoke i halvannen time, til svoren lar seg dele med kanten av en skje.'},
    {en:'Skim the fat off the surface, and be ruthless about it. There will be a great deal, and the dish is judged on how much of it you take away.',
     no:'Skum fettet av overflaten, og vær nådeløs. Det blir mye av det, og retten bedømmes på hvor mye du får bort.'},
    {en:'Strip out the thickest stalks of the cabbage, cut the leaves into wide ribbons and pile them on top of the meat. They collapse within a few minutes.',
     no:'Fjern de tykkeste stilkene i kålen, skjær bladene i brede bånd og legg dem i en haug oppå kjøttet. De faller sammen i løpet av noen minutter.'},
    {en:'Add the sausages, cover again and cook for another forty minutes, stirring now and then, until the cabbage has gone soft enough to hold the whole pot together.',
     no:'Ha i pølsene, legg på lokk igjen og kok videre i førti minutter. Rør av og til, til kålen er blitt myk nok til å holde hele gryten sammen.'},
    {en:'Season with salt and pepper, let the pot stand off the heat for a quarter of an hour, and serve it with polenta.',
     no:'Smak til med salt og pepper, la gryten stå et kvarter av platen, og server den med polenta.'},
  ],
  notes:[
    {title:{en:'Why the frost matters', no:'Hvorfor frosten betyr noe'},
     body:{en:'A savoy that has been through a cold night breaks part of its starch down into sugar, which is a defence against freezing, and its cell walls give way sooner. The practical result is a cabbage that cooks down sweeter, faster and to a softer mass. An October cabbage will get there in the end, but it needs longer and it stays greener in flavour.',
           no:'En savoykål som har stått gjennom en kald natt, bryter en del av stivelsen ned til sukker som forsvar mot frost, og celleveggene gir raskere etter. Resultatet i gryten er en kål som koker seg søtere, raskere og til en mykere masse. En oktoberkål kommer dit til slutt, men den trenger lengre tid og smaker grønnere.'}},
    {title:{en:'The rind is the thickener', no:'Svoren er jevningen'},
     body:{en:'Pork rind is almost pure collagen, and an hour and a half between 80 and 90 °C turns it into gelatine that dissolves into the liquid. That is what gives cassoeula its sticky, lip-coating body, and it is why the pot sets solid in the fridge overnight. Leave the rind out and you have a cabbage stew that needs flour; leave it in and it needs nothing.',
           no:'Svor er nesten bare kollagen, og halvannen time mellom 80 og 90 °C gjør den om til gelatin som løser seg i væsken. Den gir cassoeula den klebrige fylden som legger seg på leppene, og derfor stivner gryten i kjøleskapet over natten. Utelater du svoren, sitter du med en kålgryte som trenger jevning; har du den i, trenger den ingenting.'}},
    {title:{en:'Skim, cool, skim again', no:'Skum, avkjøl, skum igjen'},
     body:{en:'Rendered pork fat floats, and the easiest way to remove it is to let the pot go cold so the fat sets in a sheet you can lift off whole. Cassoeula made the day before and reheated is both lighter and better tasting, because the cabbage goes on breaking down while it stands. Cook it on the Saturday and eat it on the Sunday.',
           no:'Smeltet svinefett flyter opp, og den enkleste måten å få det bort på er å la gryten bli kald, slik at fettet stivner til en plate du kan løfte av i ett stykke. Cassoeula som lages dagen før og varmes opp igjen, blir både lettere og bedre på smak, for kålen fortsetter å bryte seg ned mens den står. Lag den på lørdag og spis den på søndag.'}},
  ],
  variations:[
    {title:{en:'How much of the pig', no:'Hvor mye av grisen'},
     body:{en:'The reading names ribs, rind, trotters and small sausages, and that is the working minimum. Households that keep the older version add ear, snout and tail, all of them for gelatine rather than for meat. Others leave the trotter out because nobody at the table wants to be the one to eat it.',
           no:'Lesteksten nevner ribbe, svor, griselabb og små pølser, og det er minimumet man klarer seg med. Husholdninger som holder på den eldre utgaven, har med øre, tryne og hale, alt sammen for gelatinens skyld og ikke for kjøttet. Andre lar griselabben være, fordi ingen ved bordet vil være den som spiser den.'}},
    {title:{en:'A little tomato', no:'Litt tomat'},
     body:{en:'Some families stir a spoonful of tomato in with the stock. The pot then looks like a stew, red-brown instead of pale, and tastes a shade sweeter. Neither version is wrong, but the tomato covers the cabbage, which is the thing the dish is actually about.',
           no:'Noen familier rører inn en skje tomat sammen med kraften. Gryten ser da ut som en stuing, rødbrun i stedet for lys, og smaker en anelse søtere. Ingen av utgavene er feil, men retten handler egentlig om kålen, og tomaten legger seg over den.'}},
    {title:{en:'What to put beside it', no:'Hva som skal ved siden av'},
     body:{en:'Polenta, and nothing much else — soft from the pot rather than set and grilled, so it takes up the juices. For a glass, the region’s own answer is the frothy red Bonarda of the Oltrepò Pavese, which has the acidity and the fizz to cut through pork fat; a Pinot Nero from the same hills does the more elegant version of the same job.',
           no:'Polenta, og lite annet. Den skal være myk rett fra gryten og ikke stivnet og grillet, slik at den suger til seg kraften. I glasset er regionens eget svar den perlende røde Bonardaen fra Oltrepò Pavese, som har syren og kullsyren til å skjære gjennom svinefettet; en Pinot Nero fra de samme åsene gjør den samme jobben på en mer elegant måte.'}},
  ],
},

];
