// Marche recipes. Contract: docs/recipe-format.md. Both languages in one file; never narrated.
// Everything here follows the Marche food reading (content/marche.js, lesson 3): the Ascolana tenera
// olive stoned in a spiral, the brodetto whose rules change from port to port, the vincisgrassi that is
// older than the general it is named after, and the crescia cooked on a hot stone. The stoccafisso is
// named in the Verdicchio reading as a pairing and is marked as such in its headnote.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-57'] = [

{
  id:'olive-allascolana', dish:'Olive all\'ascolana', course:'antipasto', lesson:3, serves:4, time:{prep:90, cook:20},
  hero:'olive', tags:['fried','olive','meat','antipasto'],
  title:{en:'Olive all\'ascolana', no:'Olive all\'ascolana'},
  blurb:{en:'Big green olives stoned in a spiral, wound back around a meat filling, breaded and fried. The hardest thing in this book, and worth an afternoon.',
         no:'Store grønne oliven utsteinet i spiral, viklet tilbake rundt et kjøttfyll, panert og fritert. Det vanskeligste i denne boken, og verdt en ettermiddag.'},
  heroCaption:{en:'Olive all\'ascolana straight out of the oil: the size of a walnut, crisp outside, salty olive around a warm meat filling.',
               no:'Olive all\'ascolana rett opp av oljen. De er på størrelse med en valnøtt, sprø utenpå, med salt oliven rundt et varmt kjøttfyll.'},
  wines:['Verdicchio dei Castelli di Jesi'],
  headnote:{
    en:'<p>The olive is a particular one. <strong>Ascolana tenera</strong> is unusually large, thin-skinned and mild, grown around Ascoli Piceno and Fermo and protected since 2005 as <strong>Oliva Ascolana del Piceno DOP</strong>, which covers both the brined olive and the stuffed one. A smaller, sharper olive fights the filling instead of carrying it.</p>'
      + '<p>The craft is in the stoning. A small sharp knife goes in at the stalk end and cuts round the stone in one spiral, so the flesh comes away as a single ribbon that can be wound back around a nut of filling. It is slow, and the first ten are ugly. That is exactly why Ascoli sells them ready-made by the kilo, and there is an honest shortcut further down.</p>'
      + '<p>The filling is beef, pork and often chicken, cooked with wine and chopped fine afterwards, bound with egg and Parmigiano. Flour, egg, breadcrumb and hot oil do the rest. Done properly they are the size of a walnut, and the salt of the olive cuts the richness of the meat. They are eaten standing up, as an antipasto, and as part of the <em>fritto misto all\'ascolana</em> with lamb chops, courgettes and squares of custard.</p>',
    no:'<p>Oliven er en bestemt sort. <strong>Ascolana tenera</strong> er uvanlig stor, tynnskallet og mild, dyrkes rundt Ascoli Piceno og Fermo og er beskyttet siden 2005 som <strong>Oliva Ascolana del Piceno DOP</strong>, som dekker både oliven i lake og den fylte utgaven. En mindre og skarpere oliven kjemper mot fyllet i stedet for å bære det.</p>'
      + '<p>Håndverket ligger i utsteiningen. En liten, skarp kniv går inn i stilkenden og skjærer rundt steinen i én spiral, slik at fruktkjøttet løsner som en sammenhengende strimmel som kan vikles tilbake rundt en klump fyll. Det går sakte, og de ti første blir stygge. Nettopp derfor selger Ascoli dem ferdige på kiloen, og lenger nede finner du en ærlig snarvei.</p>'
      + '<p>Fyllet er oksekjøtt, svinekjøtt og ofte kylling, kokt med vin og finhakket etterpå, bundet med egg og Parmigiano. Mel, egg, griljermel og varm olje gjør resten. Gjøres de ordentlig, er de på størrelse med en valnøtt, og saltet i oliven skjærer gjennom det fete kjøttet. De spises stående, som forrett, og som del av <em>fritto misto all\'ascolana</em> sammen med lammekoteletter, squash og firkanter av vaniljekrem.</p>'},
  ingredients:[
    { group:{en:'For the filling', no:'Til fyllet'}, items:[
      {q:150, u:'g', n:{en:'beef shoulder', no:'høyrygg av okse'}, note:{en:'in small dice', no:'i små terninger'}},
      {q:150, u:'g', n:{en:'pork shoulder', no:'svinebog'}, note:{en:'in small dice', no:'i små terninger'}},
      {q:100, u:'g', n:{en:'chicken breast', no:'kyllingbryst'}, note:{en:'optional, and traditional in Ascoli', no:'valgfritt, og tradisjonelt i Ascoli'}},
      {q:80,  u:'g', n:{en:'onion, carrot and celery', no:'løk, gulrot og selleri'}, note:{en:'finely chopped, in roughly equal parts', no:'finhakket, i omtrent like deler'}},
      {q:40,  u:'ml', n:{en:'olive oil', no:'olivenolje'}},
      {q:80,  u:'ml', n:{en:'dry white wine', no:'tørr hvitvin'}, note:{en:'Verdicchio, and drink the rest of the bottle with them', no:'Verdicchio, og drikk resten av flasken til'}},
      {q:60,  u:'g', n:{en:'Parmigiano Reggiano', no:'Parmigiano Reggiano'}, note:{en:'finely grated', no:'finrevet'}},
      {u:'', n:{en:'nutmeg and grated lemon zest', no:'muskat og revet sitronskall'}, note:{en:'a scrape of each; they lift the meat without being tasted separately', no:'litt av hver; de løfter kjøttet uten å kjennes hver for seg'}, scale:'none'},
      {u:'', n:{en:'salt and black pepper', no:'salt og sort pepper'}, scale:'none'},
    ]},
    { group:{en:'To stuff and fry', no:'Til fylling og fritering'}, items:[
      {q:40, u:'', n:{en:'large green olives in brine', no:'store grønne oliven i lake'}, note:{en:'Ascolana tenera if you can find them, otherwise the largest and mildest green olives your shop has', no:'Ascolana tenera hvis du finner dem, ellers de største og mildeste grønne olivenene butikken har'}, round:'half'},
      {q:3,  u:'', n:{en:'eggs', no:'egg'}, note:{en:'one binds the filling, the others are beaten for the breading', no:'ett binder fyllet, de andre piskes til paneringen'}, round:'half'},
      {q:60, u:'g', n:{en:'plain flour', no:'hvetemel'}},
      {q:150, u:'g', n:{en:'fine breadcrumbs', no:'griljermel'}},
      {u:'', n:{en:'oil for deep-frying', no:'olje til fritering'}, note:{en:'a neutral one with a high smoke point, such as sunflower', no:'en nøytral olje som tåler høy varme, for eksempel solsikkeolje'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Brown the diced beef, pork and chicken in the oil with the chopped vegetables, in a pan wide enough to hold them in one layer.',
     no:'Brun terningene av okse, svin og kylling i oljen sammen med de hakkede grønnsakene, i en panne som er vid nok til å holde alt i ett lag.'},
    {en:'Pour in the wine, let it steam off, then cover the pan and cook the meat over a low heat until it falls apart under a fork, about an hour.',
     no:'Hell i vinen, la den dampe av, legg på lokk, og la kjøttet koke på svak varme til det faller fra hverandre under en gaffel, omtrent en time.'},
    {en:'Let the meat cool in its own juices, then chop it very finely or put it through a mincer. Cooking first and mincing afterwards is what keeps the filling from weeping.',
     no:'La kjøttet kjølne i sin egen kraft, og finhakk det så, eller kjør det gjennom en kjøttkvern. Når kjøttet kokes først og kvernes etterpå, holder fyllet på væsken.'},
    {en:'Work in the Parmigiano, one egg, the nutmeg, the lemon zest, salt and pepper, until the filling holds its shape when you roll a little of it between your palms.',
     no:'Arbeid inn Parmigianoen, ett egg, muskaten, sitronskallet, salt og pepper, til fyllet holder formen når du triller litt av det mellom håndflatene.'},
    {en:'Rinse the olives and dry them. Hold one between finger and thumb, set the point of a small sharp knife at the stalk end, and cut round the stone in a spiral, turning the olive against the blade.',
     no:'Skyll olivenene og tørk dem. Hold én mellom tommel og pekefinger, sett spissen av en liten, skarp kniv i stilkenden, og skjær rundt steinen i spiral mens du dreier oliven mot bladet.'},
    {en:'Keep going until the flesh comes away in one ribbon and the stone drops out. Work over a bowl and expect to eat the first few failures.',
     no:'Fortsett til fruktkjøttet løsner i én strimmel og steinen faller ut. Arbeid over en bolle, og regn med å spise opp de første forsøkene.'},
    {en:'Roll a nut of filling in your palm and wind the ribbon back around it, closing the olive into its own shape again, a little fatter than it started.',
     no:'Trill en klump fyll i håndflaten og vikle strimmelen tilbake rundt den, så oliven lukker seg i sin egen form igjen, litt fetere enn den var.'},
    {en:'Roll each one in flour, then in beaten egg, then in breadcrumbs, and give the thin-looking ones a second turn through egg and crumb.',
     no:'Vend hver av dem i mel, så i sammenpisket egg og til slutt i griljermel, og gi dem som ser tynne ut, en runde til i egg og griljermel.'},
    {en:'Chill the breaded olives for half an hour, so the crust sets and stays on in the oil.',
     no:'Sett de panerte olivenene kaldt i en halvtime, så skorpen setter seg og blir sittende i oljen.'},
    {en:'Heat the frying oil to 170 °C and fry them a handful at a time for two to three minutes, until they are deep gold and float.',
     no:'Varm friteringsoljen til 170 °C og friter dem en håndfull om gangen i to til tre minutter, til de er dypt gylne og flyter opp.'},
    {en:'Lift them onto paper, salt them lightly and eat them hot, while the crust still crackles.',
     no:'Løft dem opp på papir, salt dem lett, og spis dem varme mens skorpen fortsatt knaser.'},
  ],
  notes:[
    {title:{en:'Cook the meat, chop it afterwards', no:'Kok kjøttet, hakk det etterpå'},
     body:{en:'A filling made from raw mince releases water as it fries. The water turns to steam inside a sealed olive and the crust splits at the seam. Meat that has already given up its liquid in the pan and been chopped afterwards is dry enough to hold together, and it tastes of the braise rather than of the pan.',
           no:'Et fyll av rått kvernet kjøtt slipper væske under friteringen. Vannet blir til damp inne i en lukket oliven, og skorpen sprekker i skjøten. Kjøtt som allerede har gitt fra seg væsken i pannen og blir hakket etterpå, er tørt nok til å henge sammen, og det smaker av gryten og ikke av pannen.'}},
    {title:{en:'The temperature of the oil', no:'Temperaturen i oljen'},
     body:{en:'Below about 165 °C the breadcrumb drinks oil before it seals, and the olive comes out heavy. Above 185 °C the crust is dark before the filling is warm. Fry a few at a time: a full pan drops the temperature by twenty degrees, and everything after that is a slow fry.',
           no:'Under omtrent 165 °C drikker griljermelet olje før det får satt seg, og oliven blir tung. Over 185 °C er skorpen mørk før fyllet er varmt. Friter noen få om gangen, for en full panne mister tjue grader, og alt som kommer etterpå, blir langsom steking.'}},
    {title:{en:'Why the ribbon works', no:'Derfor virker strimmelen'},
     body:{en:'A spiral cut leaves the skin of the olive on the outside along its whole length, so the parcel holds together with no join to burst, and the flesh stays the thickness it grew. Two halves pressed around a ball of filling also work, but they leave a seam where the crumb has to do the sealing, and that seam is what gives away an olive that came out of a bag.',
           no:'Et spiralsnitt lar skinnet på oliven ligge ytterst i hele lengden, slik at pakken henger sammen uten en skjøt som kan sprekke, og fruktkjøttet beholder tykkelsen det vokste med. To halvdeler trykket rundt en kule fyll fungerer også, men de etterlater en skjøt der griljermelet må gjøre tetningsjobben, og den skjøten røper en oliven som kom fra en pose.'}},
  ],
  variations:[
    {title:{en:'The shortcut', no:'Snarveien'},
     body:{en:'Large pitted green olives from a jar take the filling piped in with a bag, and that is how most bars in Italy outside Ascoli do it. The result is rounder and blunter, and it is still a good thing to eat.',
           no:'Store, ferdig utsteinede grønne oliven på glass tar imot fyll sprøytet inn med en sprøytepose, og slik gjør de fleste barer i Italia utenfor Ascoli det. Resultatet blir rundere og mer anonymt, men det er fortsatt godt.'}},
    {title:{en:'Fritto misto all\'ascolana', no:'Fritto misto all\'ascolana'},
     body:{en:'The olives are one element of a larger fried plate that also holds lamb chops, courgettes, artichokes and squares of thick custard, all breaded and fried in the same oil. The custard is not a joke: sweet and savoury on one plate is the point of the dish.',
           no:'Olivenene er ett element på en større tallerken med fritert mat, sammen med lammekoteletter, squash, artisjokk og firkanter av tykk vaniljekrem, alt panert og fritert i den samme oljen. Vaniljekremen er ingen spøk, for søtt og salt på samme tallerken er nettopp poenget.'}},
    {title:{en:'Freezing them', no:'Frysing'},
     body:{en:'Breaded and unfried, they freeze well on a tray and go into the oil straight from the freezer, with a minute more and a slightly cooler pan. Fried first and reheated later, they are a different and sadder thing.',
           no:'Er de panert, men ikke friterte, lar de seg fryse godt på et brett, og de går rett fra fryseren ned i oljen, med ett minutt ekstra og litt lavere temperatur. Friterer du dem først og varmer dem opp igjen, får du noe annet og tristere.'}},
  ],
},

{
  id:'brodetto-allanconetana', dish:'Brodetto', course:'secondo', lesson:3, serves:4, time:{prep:40, cook:45},
  hero:'brodetto', tags:['fish','shellfish','one pot','coast'],
  title:{en:'Brodetto all\'anconetana', no:'Brodetto all\'anconetana'},
  blurb:{en:'The Adriatic fish stew as Ancona makes it: everything goes into one wide pan in the order it needs, and nothing is stirred.',
         no:'Adriaterhavets fiskegryte slik Ancona lager den. Alt går i én vid panne i den rekkefølgen det trenger, og ingenting røres.'},
  heroCaption:{en:'A brodetto of mussels, langoustines and white fish, with grilled bread to take up the broth.',
               no:'En brodetto med blåskjell, sjøkreps og hvit fisk, med grillet brød til å ta opp kraften.'},
  wines:['Verdicchio dei Castelli di Jesi'],
  headnote:{
    en:'<p>Brodetto is what the Adriatic fishermen could not sell: the bony, the small and the odd, cooked in one pan on the boat or on the quay. Every port on the Marche coast has its own rules and defends them, and Ancona\'s is the version the region is known for.</p>'
      + '<p>The order of the pan is the whole mechanism. Squid and cuttlefish need twenty minutes and go in first, thick white fish needs eight, and langoustines and mussels need three. Put everything in at once and you get either rubber or porridge. Nothing is stirred either: the pan is shaken by the handles, because a spoon breaks cooked fish into the broth.</p>'
      + '<p>The broth thickens itself. Squid and shellfish give out gelatine and their own salty liquor, and that is where the body comes from; there is no flour and no stock cube in it. In the mix it matters more that firm stands against soft and oily against lean than which species, or how many of them, are in the pan. Buy what the counter has that day, and make sure of one firm fish, one oily one and something with a shell.</p>',
    no:'<p>Brodetto er det fiskerne på Adriaterhavet ikke fikk solgt, alt som var for beinete, for smått eller for rart, kokt i én panne om bord eller på kaia. Hver havn på kysten i Marche har sine egne regler og forsvarer dem, og utgaven fra Ancona er den som regionen er kjent for.</p>'
      + '<p>Rekkefølgen i pannen er hele mekanismen. Akkar og blekksprut trenger tjue minutter og går i først, tykk hvit fisk trenger åtte, og sjøkreps og blåskjell trenger tre. Legger du alt i samtidig, får du enten gummi eller grøt. Ingenting røres heller. Du tar i håndtakene og rister pannen, for en skje river kokt fisk i stykker.</p>'
      + '<p>Kraften tykner av seg selv. Akkar og skalldyr gir fra seg gelatin og sin egen salte kraft, og det gir retten fylde. Her er det verken mel eller buljongterning. I blandingen betyr kontrasten mellom fast og løst, fet og mager, mer enn hvilke arter du bruker eller hvor mange av dem. Kjøp det disken har den dagen, og sørg for én fast fisk, én fet og noe med skall.</p>'},
  ingredients:[
    { group:{en:'From the fish counter', no:'Fra fiskedisken'}, items:[
      {q:800, u:'g', n:{en:'firm white fish', no:'fast hvit fisk'}, note:{en:'monkfish, gurnard or a thick loin of cod, on the bone if you can; cut into pieces a spatula can lift whole', no:'breiflabb, steinbit eller en tykk torskeloin, gjerne med bein i; skåret i stykker som en stekespade kan løfte hele'}},
      {q:300, u:'g', n:{en:'squid or cuttlefish', no:'akkar eller blekksprut'}, note:{en:'cleaned, the bodies in wide rings', no:'renset, kroppene skåret i vide ringer'}},
      {q:250, u:'g', n:{en:'small oily fish', no:'fet fisk'}, note:{en:'sardines, or mackerel fillet; they carry the fat a lean pan misses', no:'sardiner eller makrellfilet, som gir fettet en mager panne savner'}},
      {q:8,   u:'', n:{en:'langoustines', no:'sjøkreps'}, round:'half'},
      {q:600, u:'g', n:{en:'mussels', no:'blåskjell'}, note:{en:'scrubbed and bearded; throw out any that stay open when you tap them', no:'skrubbet og uten skjegg; kast dem som blir stående åpne når du banker på dem'}},
    ]},
    { group:{en:'In the pan', no:'I pannen'}, items:[
      {q:120, u:'g', n:{en:'onion', no:'løk'}, note:{en:'sliced thin', no:'skåret i tynne skiver'}},
      {q:2,   u:'', n:{en:'garlic cloves', no:'hvitløksfedd'}, round:'half'},
      {q:60,  u:'ml', n:{en:'extra-virgin olive oil', no:'extra virgin olivenolje'}},
      {q:400, u:'g', n:{en:'ripe tomatoes', no:'modne tomater'}, note:{en:'peeled and chopped, or passata from a bottle', no:'flådde og hakkede, eller passata på flaske'}},
      {q:150, u:'ml', n:{en:'dry white wine', no:'tørr hvitvin'}, note:{en:'Verdicchio', no:'Verdicchio'}},
      {u:'', n:{en:'parsley', no:'persille'}, note:{en:'chopped, half in the pan and half at the table', no:'hakket, halvparten i pannen og halvparten ved bordet'}, scale:'none'},
      {u:'', n:{en:'salt and black pepper', no:'salt og sort pepper'}, scale:'none'},
      {q:4, u:'', n:{en:'thick slices of bread', no:'tykke brødskiver'}, note:{en:'grilled, and not rubbed with garlic', no:'grillet, og ikke gnidd med hvitløk'}, round:'half'},
    ]},
  ],
  steps:[
    {en:'Scrub the mussels under cold water and pull the beards off. Throw away any shell that will not close when you tap it.',
     no:'Skrubb blåskjellene under kaldt vann og dra av skjegget. Kast alle skjell som ikke lukker seg når du banker på dem.'},
    {en:'Steam the mussels open in a covered pan over a high heat, lift them out and strain their liquor through a cloth. That liquor seasons the whole dish, so keep it.',
     no:'Damp blåskjellene åpne under lokk på sterk varme, løft dem ut, og sil kraften gjennom et klede. Denne kraften gir hele retten smak, så ta vare på den.'},
    {en:'Lay the fish out on a board in the order it will go into the pan: squid first, then the white fish, then the oily fish and the langoustines.',
     no:'Legg fisken utover på en fjøl i den rekkefølgen den skal i pannen: akkar først, så den hvite fisken, og til slutt den fete fisken og sjøkrepsen.'},
    {en:'Soften the onion and the garlic in the oil in a wide, shallow pan, without letting them colour.',
     no:'La løken og hvitløken mykne i oljen i en vid, lav panne, uten at de tar farge.'},
    {en:'Add the squid, turn it in the oil and let it stew for twenty minutes, until a piece gives under a knife.',
     no:'Ha i akkaren, vend den i oljen, og la den småkoke i tjue minutter, til en bit gir etter for kniven.'},
    {en:'Pour in the wine, let it boil hard for a minute, then add the tomatoes and simmer for ten minutes.',
     no:'Hell i vinen, la den fosskoke et minutt, ha så i tomatene, og la det trekke i ti minutter.'},
    {en:'Lay the white fish in one layer, skin side down, and pour in the mussel liquor and enough hot water to come halfway up the fish.',
     no:'Legg den hvite fisken i ett lag med skinnsiden ned, og hell over blåskjellkraften og nok varmt vann til at det når halvveis opp på fisken.'},
    {en:'Simmer for five minutes without a lid, shaking the pan by the handles instead of stirring it.',
     no:'La det trekke i fem minutter uten lokk, og rist pannen i håndtakene i stedet for å røre i den.'},
    {en:'Tuck the oily fish and the langoustines in among the pieces and give them three or four minutes more.',
     no:'Legg den fete fisken og sjøkrepsen inn mellom stykkene, og gi dem tre-fire minutter til.'},
    {en:'Return the mussels in their shells, scatter half the parsley over, taste the broth for salt and take the pan off the heat.',
     no:'Legg blåskjellene tilbake i pannen med skallene på, strø over halvparten av persillen, smak til kraften med salt, og ta pannen av platen.'},
    {en:'Let it stand for five minutes, grill the bread, and serve the brodetto in wide bowls with the bread beside it rather than under it.',
     no:'La det hvile i fem minutter, grill brødet, og server brodettoen i vide boller med brødet ved siden av og ikke under.'},
  ],
  notes:[
    {title:{en:'A timetable, not a recipe', no:'En timeplan, ikke en oppskrift'},
     body:{en:'Squid muscle is collagen and needs twenty minutes to go from rubber to tender; a thick white fillet is done in eight and falls apart in twelve; a langoustine is cooked in three. The pan is really a timetable, and once you can read a fish for how long it needs, you can build a brodetto out of whatever the counter has.',
           no:'Muskelen i akkar er kollagen og trenger tjue minutter på å gå fra gummi til mør, en tykk hvit filet er ferdig på åtte og faller fra hverandre på tolv, og en sjøkreps er kokt på tre. Pannen er egentlig en timeplan, og når du kan lese hvor lang tid en fisk trenger, kan du bygge en brodetto av hva som helst disken har.'}},
    {title:{en:'Shake, never stir', no:'Rist, aldri rør'},
     body:{en:'Cooked fish holds together right up until something pushes it. Move the pan by the handles, in short flat shakes, so the pieces slide against each other instead of being levered apart. It is the same reason the fish goes in in a single layer: a stack has to be turned, and turning is what ruins it.',
           no:'Kokt fisk henger sammen helt til noe dytter borti den. Ta i håndtakene og rist pannen kort og flatt, slik at bitene glir mot hverandre i stedet for å bli brukket opp. Av samme grunn legges fisken i ett lag, for en stabel må vendes, og vendingen ødelegger den.'}},
    {title:{en:'Where the body comes from', no:'Hvor fylden kommer fra'},
     body:{en:'Nothing thickens this stew except the fish. Squid and shellfish give out gelatine, the mussel liquor brings concentrated salt and iodine, and the oily fish leaves fat that the tomato holds in suspension. Flour or stock covers all three. If the broth tastes thin, boil a ladleful of it down on its own and pour it back rather than adding anything new.',
           no:'Ingenting annet enn fisken selv tykner denne gryten. Akkar og skalldyr gir fra seg gelatin, blåskjellkraften har med seg konsentrert salt og jod, og den fete fisken legger igjen fett som tomaten holder svevende. Mel eller buljong dekker over alle tre. Smaker kraften tynn, koker du en øse av den inn for seg og heller den tilbake, i stedet for å tilsette noe nytt.'}},
  ],
  variations:[
    {title:{en:'Porto Recanati', no:'Porto Recanati'},
     body:{en:'This port goes its own way: no tomato in the pan at all, and a broth turned yellow with saffron, which makes a pale, almost delicate stew. Leave the tomato out, put a good pinch of saffron in the wine, and let the fish keep its own colour.',
           no:'Denne havnen går sin egen vei. Det er ingen tomat i gryten i det hele tatt, og kraften er gul av safran, som gir en lys og nesten forsiktig gryte. Sløyf tomaten, ha en god klype safran i vinen, og la fisken beholde sin egen farge.'}},
    {title:{en:'San Benedetto del Tronto', no:'San Benedetto del Tronto'},
     body:{en:'Furthest south, and sharper. There is no ripe tomato here either, sometimes a green one, vinegar takes the place of the wine, and sweet peppers are cooked down into the base.',
           no:'Lengst sør, og skarpere. Heller ikke her brukes moden tomat, av og til en grønn tomat, eddik tar plassen til vinen, og søt paprika kokes inn i bunnen.'}},
    {title:{en:'Fano', no:'Fano'},
     body:{en:'On the northern coast the base is tomato paste and vinegar, which gives a darker and tighter broth than Ancona\'s, one that stands up to a slice of bread laid straight into it.',
           no:'På den nordlige kysten er bunnen tomatpuré og eddik, og det gir en mørkere og strammere kraft enn i Ancona, en kraft som tåler en brødskive lagt rett oppi.'}},
  ],
},

{
  id:'vincisgrassi', dish:'Vincisgrassi', course:'primo', lesson:3, serves:6, time:{prep:120, cook:60},
  hero:'vincisgrassi', tags:['pasta','oven','meat','feast'],
  title:{en:'Vincisgrassi', no:'Vincisgrassi'},
  blurb:{en:'The feast-day baked pasta of the Marche: chopped meat instead of mince, chicken livers, a stiff béchamel and a breath of clove.',
         no:'Festdagspastaen i Marche, med hakket kjøtt i stedet for kvernet, kyllinglever, en fast bechamel og et pust av nellik.'},
  heroCaption:{en:'Vincisgrassi baked until the top layer crisps. It is cut only after it has rested.',
               no:'Vincisgrassi bakt til det øverste laget blir sprøtt. Den skjæres først etter at den har hvilt.'},
  wines:['Rosso Conero'],
  headnote:{
    en:'<p>Vincisgrassi looks like lasagne and is not. The ragù is chopped meat rather than mince, traditionally with chicken livers and other giblets in it and sometimes sweetbreads; the béchamel is stiffer; and the spicing runs to cloves and nutmeg rather than to herbs.</p>'
      + '<p>The name is supposed to honour the Austrian general Alfred zu Windisch-Graetz, besieged in Ancona in 1799, and the story says a cook in the city invented the dish for him. Antonio Nebbia printed a recipe for <em>lasagna in princisgras</em> in <em>Il cuoco maceratese</em> twenty years earlier, in 1779, which settles the matter. His version has prosciutto and truffles in it and neither béchamel nor giblets: the dish began at the top of the table and came down to the family one later.</p>'
      + '<p>Two things carry it. Meat chopped by hand keeps its grain and its juices where mince packs into a paste, and the béchamel is a binder rather than a sauce, stiff enough that a cut square stands up on the plate. Everything else — the number of layers, the giblets, the truffle — is open to argument.</p>',
    no:'<p>Vincisgrassi ser ut som lasagne og er det ikke. Ragùen er hakket kjøtt og ikke kvernet, tradisjonelt med kyllinglever og annen innmat i, av og til brissel. Bechamelen er fastere, og krydringen går mot nellik og muskat framfor urter.</p>'
      + '<p>Navnet skal hedre den østerrikske generalen Alfred zu Windisch-Graetz, som ble beleiret i Ancona i 1799, og historien sier at en kokk i byen fant opp retten til ham. Antonio Nebbia trykte en oppskrift på <em>lasagna in princisgras</em> i <em>Il cuoco maceratese</em> tjue år tidligere, i 1779, og dermed er saken avgjort. Utgaven hans har prosciutto og trøffel i seg og verken bechamel eller innmat. Retten begynte øverst ved bordet og kom ned til familiebordet senere.</p>'
      + '<p>To ting bærer den. Kjøtt som er hakket for hånd, beholder både struktur og kraft, mens kvernet kjøtt pakker seg til en masse, og bechamelen er et bindemiddel og ikke en saus, fast nok til at en oppskåret firkant står av seg selv på tallerkenen. Om alt annet kan man diskutere, enten det gjelder antall lag, innmaten eller trøffelen.</p>'},
  ingredients:[
    { group:{en:'For the pasta', no:'Til pastaen'}, items:[
      {q:400, u:'g', n:{en:'‘00’ flour', no:'mel type 00'}},
      {q:4,   u:'', n:{en:'eggs', no:'egg'}, round:'half'},
      {q:20,  u:'ml', n:{en:'vin cotto or sweet wine', no:'vin cotto eller søt vin'}, note:{en:'traditional in Macerata and optional; it colours the sheet and softens it', no:'tradisjonelt i Macerata og valgfritt; det farger platen og gjør den mykere'}},
      {q:5,   u:'g', n:{en:'salt', no:'salt'}},
    ]},
    { group:{en:'For the ragù', no:'Til ragùen'}, items:[
      {q:300, u:'g', n:{en:'beef shoulder', no:'høyrygg av okse'}, note:{en:'chopped by hand into dice of about 5 mm', no:'hakket for hånd i terninger på omkring 5 mm'}},
      {q:300, u:'g', n:{en:'pork shoulder', no:'svinebog'}, note:{en:'chopped the same way', no:'hakket på samme måte'}},
      {q:150, u:'g', n:{en:'chicken livers', no:'kyllinglever'}, note:{en:'trimmed of anything green and of sinew, then chopped', no:'renset for alt grønt og alle sener, og deretter hakket'}},
      {q:100, u:'g', n:{en:'prosciutto crudo', no:'prosciutto crudo'}, note:{en:'in small dice, fat and all', no:'i små terninger, med fettet på'}},
      {q:150, u:'g', n:{en:'onion, carrot and celery', no:'løk, gulrot og selleri'}, note:{en:'finely chopped', no:'finhakket'}},
      {q:50,  u:'ml', n:{en:'olive oil', no:'olivenolje'}},
      {q:150, u:'ml', n:{en:'red wine', no:'rødvin'}, note:{en:'Rosso Conero, and open the bottle you mean to drink', no:'Rosso Conero, og åpne flasken du skal drikke'}},
      {q:400, u:'g', n:{en:'tomato passata', no:'passata'}},
      {q:300, u:'ml', n:{en:'meat stock', no:'kjøttkraft'}},
      {u:'', n:{en:'cloves and nutmeg', no:'nellik og muskat'}, note:{en:'two cloves and a scrape of nutmeg; more than that takes the dish over', no:'to nellikspiker og litt revet muskat; mer enn det overdøver retten'}, scale:'none'},
      {u:'', n:{en:'salt and black pepper', no:'salt og sort pepper'}, scale:'none'},
    ]},
    { group:{en:'For the béchamel', no:'Til bechamelen'}, items:[
      {q:80,  u:'g', n:{en:'butter', no:'smør'}},
      {q:80,  u:'g', n:{en:'plain flour', no:'hvetemel'}},
      {q:800, u:'ml', n:{en:'whole milk', no:'helmelk'}},
    ]},
    { group:{en:'To assemble', no:'Til å legge opp'}, items:[
      {q:150, u:'g', n:{en:'Parmigiano Reggiano', no:'Parmigiano Reggiano'}, note:{en:'grated', no:'revet'}},
      {q:30,  u:'g', n:{en:'butter for the dish and the top', no:'smør til formen og toppen'}},
      {q:5,   u:'l', n:{en:'water for the pasta', no:'vann til pastaen'}, scale:'sub'},
      {q:25,  u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
    ]},
  ],
  steps:[
    {en:'Work the flour, the eggs, the sweet wine and the salt into a firm dough, knead it for ten minutes and rest it under a bowl for half an hour.',
     no:'Arbeid melet, eggene, den søte vinen og saltet til en fast deig, elt den i ti minutter, og la den hvile under en bolle en halvtime.'},
    {en:'Chop the beef and the pork by hand into small dice. A mincer is quicker and gives you a different dish.',
     no:'Hakk okse- og svinekjøttet for hånd i små terninger. En kjøttkvern går fortere og gir deg en annen rett.'},
    {en:'Soften the chopped vegetables and the prosciutto in the oil, then raise the heat and brown the meat in two batches, so that it colours instead of steaming.',
     no:'La de hakkede grønnsakene og prosciuttoen mykne i oljen, skru så opp varmen og brun kjøttet i to omganger, så det får farge i stedet for å dampe.'},
    {en:'Pour in the wine and let it boil away, then add the passata, the cloves, the nutmeg and half the stock.',
     no:'Hell i vinen og la den koke bort, ha så i passataen, nelliken, muskaten og halvparten av kraften.'},
    {en:'Simmer the ragù uncovered for two hours at a bare tremble, adding stock whenever it tightens. It should end up thick enough to sit on a spoon.',
     no:'La ragùen stå og småkoke uten lokk i to timer, akkurat så det bobler, og spe med kraft hver gang den blir stram. Til slutt skal den være tykk nok til å bli sittende på en skje.'},
    {en:'Fry the chopped livers hard in a dry pan for a minute and stir them into the ragù for the last quarter of an hour, so they stay tender.',
     no:'Stek den hakkede leveren raskt i en tørr panne i ett minutt, og rør den inn i ragùen det siste kvarteret, slik at den holder seg mør.'},
    {en:'Roll the dough out thin, cut it into sheets the width of your dish, and boil them a few at a time in salted water for a minute. Lift them into cold water and lay them out on cloths.',
     no:'Kjevle deigen tynn, skjær den i plater som passer bredden på formen, og kok dem noen få om gangen i saltet vann i ett minutt. Løft dem over i kaldt vann og legg dem utover på kleder.'},
    {en:'Make a béchamel with the butter, the flour and the milk, and cook it until it holds the mark of a spoon. Season it with salt and nutmeg.',
     no:'Lag en bechamel av smøret, melet og melken, og kok den til den holder på merket etter en skje. Smak til med salt og muskat.'},
    {en:'Butter the dish and start with a thin layer of ragù, so the first sheet does not stick.',
     no:'Smør formen og begynn med et tynt lag ragù, så den første platen ikke setter seg fast.'},
    {en:'Build six layers of pasta, ragù, béchamel and Parmigiano, and press each one flat before the next goes on.',
     no:'Bygg seks lag med pasta, ragù, bechamel og Parmigiano, og trykk hvert lag flatt før det neste legges på.'},
    {en:'Finish with béchamel and Parmigiano alone, dot the top with butter, and let the assembled dish stand for an hour, or overnight in the fridge.',
     no:'Avslutt med bare bechamel og Parmigiano, sett smørklatter på toppen, og la den ferdige formen stå en time, eller natten over i kjøleskapet.'},
    {en:'Bake at 180 °C for 45 minutes, until the top is brown and crisp at the corners, and let it rest for ten minutes before you cut it.',
     no:'Stek ved 180 °C i 45 minutter, til toppen er brun og sprø i hjørnene, og la den hvile i ti minutter før du skjærer i den.'},
  ],
  notes:[
    {title:{en:'Chopped, not minced', no:'Hakket, ikke kvernet'},
     body:{en:'A mincer crushes the muscle fibre and squeezes the juice out of it, and what comes back in the pan is a paste that tastes of one thing. Dice cut with a knife keep their edges through two hours of simmering, so a forkful has meat in it that has to be chewed. Here lies the difference between vincisgrassi and lasagne, and this is the one step not worth skipping.',
           no:'En kjøttkvern knuser muskelfibrene og presser kraften ut av dem, og det som kommer tilbake i pannen, er en masse som smaker én ting. Terninger skåret med kniv holder kantene gjennom to timers småkoking, slik at en gaffel har kjøtt i seg som må tygges. Her ligger forskjellen mellom vincisgrassi og lasagne, og dette er trinnet det ikke lønner seg å hoppe over.'}},
    {title:{en:'A binder, not a sauce', no:'Et bindemiddel, ikke en saus'},
     body:{en:'The béchamel here is cooked further than the one that goes into lasagne, until it barely pours. In the oven it loosens as the milk warms, and a sauce that was already loose turns to soup and runs out of the cut. A stiff béchamel also keeps the layers apart, which is why the top crisps instead of steaming.',
           no:'Bechamelen her kokes lenger enn den som går i lasagne, til den så vidt lar seg helle. I ovnen løsner den når melken blir varm, og en saus som allerede var løs, blir til suppe og renner ut av snittet. En fast bechamel holder også lagene fra hverandre, og derfor blir toppen sprø i stedet for å dampe.'}},
    {title:{en:'Clove and nutmeg', no:'Nellik og muskat'},
     body:{en:'The spicing survives from the aristocratic kitchen the dish came out of, when pepper, clove and cinnamon marked a rich table. Used sparingly they sit under the meat and read as warmth rather than as spice. Two cloves too many, and the whole dish tastes of Christmas.',
           no:'Krydringen er en levning fra det aristokratiske kjøkkenet retten kom fra, da pepper, nellik og kanel viste at bordet var rikt. Brukt varsomt legger de seg under kjøttet og kjennes som varme mer enn som krydder. To nellikspiker for mye, og hele retten smaker jul.'}},
  ],
  variations:[
    {title:{en:'Nebbia\'s princisgras', no:'Nebbias princisgras'},
     body:{en:'The 1779 version has prosciutto and truffles in it and neither béchamel nor giblets, and it is closer to a rich baked pasta than to what Macerata bakes today. To taste the older dish, leave the livers out and shave black truffle over every layer.',
           no:'Utgaven fra 1779 har prosciutto og trøffel i seg og verken bechamel eller innmat, og den ligger nærmere en rik ovnsbakt pasta enn det Macerata baker i dag. Vil du smake den eldre retten, sløyfer du leveren og høvler sort trøffel over hvert lag.'}},
    {title:{en:'Without the giblets', no:'Uten innmaten'},
     body:{en:'Many families now make it with beef and pork alone. The dish loses the iron note the livers give and becomes rounder and more familiar, and it stops being an argument with the children.',
           no:'Mange familier lager den i dag med bare okse- og svinekjøtt. Retten mister jerntonen fra leveren og blir rundere og mer velkjent, og den slutter å være en krangel med barna.'}},
    {title:{en:'Assembled a day ahead', no:'Lagt opp dagen før'},
     body:{en:'Vincisgrassi is better put together the day before and baked cold from the fridge. The sheets take up moisture from the ragù overnight, the layers settle, and a cut square holds together instead of sliding apart.',
           no:'Vincisgrassi blir bedre av å legges opp dagen før og stekes rett fra kjøleskapet. Platene trekker til seg fuktighet fra ragùen over natten, lagene setter seg, og en oppskåret firkant henger sammen i stedet for å skli fra hverandre.'}},
  ],
},

{
  id:'crescia-sfogliata', dish:'Crescia', course:'antipasto', lesson:3, serves:4, time:{prep:60, cook:20},
  hero:'crescia', tags:['bread','griddle','lard','street food'],
  title:{en:'Crescia sfogliata di Urbino', no:'Crescia sfogliata di Urbino'},
  blurb:{en:'The flatbread of Urbino: egg and lard rolled into the sheet in layers, cooked dry on a hot plate and split while it steams.',
         no:'Flatbrødet fra Urbino. Egg og smult rulles inn i platen i lag, den stekes tørt på en varm takke og deles mens den damper.'},
  heroCaption:{en:'A crescia split while hot and filled with ham and cheese. The photograph shows its Umbrian twin, the torta al testo, cooked on the same kind of stone.',
               no:'En crescia delt mens den er varm og fylt med skinke og ost. Bildet viser tvillingen fra Umbria, torta al testo, stekt på den samme typen stein.'},
  wines:['Lacrima di Morro d\'Alba'],
  headnote:{
    en:'<p>Crescia is the flatbread of the Marche, cooked on a hot stone rather than in an oven, and the version from Urbino is layered and rich with egg and lard. It is split while it is still steaming and filled with ham and cheese, and the region eats it at a stall, in a paper napkin, standing up.</p>'
      + '<p><em>Sfogliata</em> means divided into leaves, and the leaves are put there on purpose. The rolled sheet is spread with soft lard, rolled up into a rope, wound into a flat coil and rolled out again, so the fat ends up as dozens of thin films between dozens of thin sheets. On the hot plate the water in the dough turns to steam, and the steam pushes the sheets apart into layers you can peel.</p>'
      + '<p>The lard is no detail. It stays solid at the temperature of the dough and separates the layers instead of blending into them, and it fries the inner surfaces as the bread cooks. Butter is softer, melts in while you roll and gives a flat, cakey bread. The plate has to be dry as well, because oil in the pan turns a griddle bread into a fried one.</p>',
    no:'<p>Crescia er flatbrødet i Marche, stekt på varm stein i stedet for i ovn, og utgaven fra Urbino er lagvis og rik på egg og smult. Den deles mens den fortsatt damper og fylles med skinke og ost, og folk her spiser den ved en bod, i en papirserviett, stående.</p>'
      + '<p><em>Sfogliata</em> betyr at noe er delt i blader, og bladene legges inn med vilje. Den utkjevlede platen smøres med bløtt smult, rulles til et tau, snurres til en flat snegle og kjevles ut på nytt, slik at fettet havner som dusinvis av tynne hinner mellom like mange tynne plater. På den varme takken blir vannet i deigen til damp, og dampen skyver platene fra hverandre til lag du kan flerre av.</p>'
      + '<p>Smultet er ingen detalj. Det holder seg i fast form ved deigens temperatur og skiller lagene i stedet for å gå opp i dem, og det steker flatene på innsiden mens brødet baker. Smør er bløtere, smelter inn mens du kjevler, og gir et flatt og kakeaktig brød. Takken må dessuten være tørr, for olje i pannen gjør et takkebrød til et stekt brød.</p>'},
  ingredients:[
    { group:{en:'For the dough', no:'Til deigen'}, items:[
      {q:400, u:'g', n:{en:'plain flour', no:'hvetemel'}, note:{en:'a strong ‘0’ or ordinary bread flour; ‘00’ tears when you roll it thin', no:'et sterkt mel type 0 eller vanlig hvetemel; type 00 revner når du kjevler tynt'}},
      {q:2,   u:'', n:{en:'eggs', no:'egg'}, round:'half'},
      {q:120, u:'ml', n:{en:'water', no:'vann'}, note:{en:'lukewarm; hold a little back, flours differ', no:'lunkent; hold igjen litt, for mel er ulikt'}},
      {q:30,  u:'g', n:{en:'lard', no:'smult'}, note:{en:'worked into the dough', no:'arbeides inn i deigen'}},
      {q:7,   u:'g', n:{en:'salt', no:'salt'}},
      {u:'', n:{en:'black pepper', no:'sort pepper'}, note:{en:'coarsely ground, and more than you think; the crescia of Urbino is peppery', no:'grovmalt, og mer enn du tror, for crescia fra Urbino er pepret'}, scale:'none'},
    ]},
    { group:{en:'For the layers', no:'Til lagene'}, items:[
      {q:60, u:'g', n:{en:'lard', no:'smult'}, note:{en:'soft enough to spread with a finger', no:'bløtt nok til å smøres utover med en finger'}},
    ]},
    { group:{en:'To fill', no:'Til fyll'}, items:[
      {q:150, u:'g', n:{en:'prosciutto crudo', no:'prosciutto crudo'}},
      {q:150, u:'g', n:{en:'casciotta d\'Urbino', no:'casciotta d\'Urbino'}, note:{en:'or another mild semi-soft cheese that melts', no:'eller en annen mild, halvfast ost som smelter'}},
    ]},
  ],
  steps:[
    {en:'Work the flour, the eggs, the water, the lard for the dough, the salt and a lot of pepper into a firm dough.',
     no:'Arbeid melet, eggene, vannet, smultet til deigen, saltet og rikelig med pepper sammen til en fast deig.'},
    {en:'Knead it for ten minutes, until it is smooth and springs back slowly, then cover it and rest it for half an hour.',
     no:'Elt den i ti minutter, til den er glatt og spretter langsomt tilbake. Dekk den så til og la den hvile en halvtime.'},
    {en:'Divide the dough into four and roll each piece out as thin as you can, into a rough round.',
     no:'Del deigen i fire og kjevle hvert stykke så tynt du klarer, til en omtrentlig rund plate.'},
    {en:'Spread the soft lard over the whole surface with your fingers, right out to the edge.',
     no:'Smør det bløte smultet utover hele flaten med fingrene, helt ut til kanten.'},
    {en:'Roll the sheet up into a tight rope, wind the rope into a flat coil like a snail and tuck the end underneath.',
     no:'Rull platen sammen til et stramt tau, snurr tauet til en flat snegle, og brett enden inn under.'},
    {en:'Rest the coils for twenty minutes. The gluten slackens, and the coil then rolls out without unwinding.',
     no:'La sneglene hvile i tjue minutter. Gluten slakner, og sneglen lar seg da kjevle ut uten å rulle seg opp.'},
    {en:'Roll each coil out into a disc about the thickness of a coin, pressing straight down rather than dragging the pin, so the layers stay stacked.',
     no:'Kjevle hver snegle ut til en plate omtrent så tykk som en mynt, og press rett ned i stedet for å dra kjevlen, så lagene blir liggende oppå hverandre.'},
    {en:'Heat a heavy dry pan, a griddle or a baking stone until a drop of water skips across it.',
     no:'Varm en tung, tørr panne, en takke eller en bakestein til en vanndråpe danser over den.'},
    {en:'Cook each crescia for two to three minutes a side, pressing it flat with a spatula, until it is blistered and brown in patches.',
     no:'Stek hver crescia i to til tre minutter på hver side mens du trykker den flat med en stekespade, til den har blemmer og flekkvis brun farge.'},
    {en:'Split it through the middle with a knife while it is still too hot to hold.',
     no:'Del den gjennom midten med en kniv mens den fortsatt er for varm til å holde i.'},
    {en:'Fill it with ham and cheese, fold it over and eat it at once, before the cheese sets again.',
     no:'Fyll den med skinke og ost, brett den sammen, og spis den med en gang, før osten stivner igjen.'},
  ],
  notes:[
    {title:{en:'The coil makes the layers', no:'Sneglen lager lagene'},
     body:{en:'Rolling the greased sheet into a rope and winding the rope up turns one film of fat into a spiral of dozens. Every turn of the spiral becomes a layer, and steam pushes the layers apart in the pan. Roll the sheet flat with the lard merely spread on it and you get one seam and a heavy bread.',
           no:'Når du ruller den smurte platen til et tau og snurrer tauet sammen, blir én hinne fett til en spiral av dusinvis. Hver omdreining i spiralen blir et lag, og dampen skyver lagene fra hverandre i pannen. Kjevler du platen flat med smultet bare smurt utover, får du én skjøt og et tungt brød.'}},
    {title:{en:'Lard, not butter', no:'Smult, ikke smør'},
     body:{en:'Lard is nearly all fat and melts at a higher temperature than butter, so it survives the rolling as a solid film. Butter carries water, goes soft in the hand, blends into the flour and steams instead of frying, and the bread it gives is even and dull. The same reasoning runs through most of the old flatbreads of the Apennines.',
           no:'Smult er nesten bare fett og smelter ved høyere temperatur enn smør, så det overlever kjevlingen som en fast hinne. Smør har vann i seg, blir bløtt i hånden, går opp i melet og damper i stedet for å steke, og brødet det gir, blir jevnt og kjedelig. Den samme tankegangen går igjen i de fleste gamle flatbrødene i Apenninene.'}},
    {title:{en:'A dry plate, and a hot one', no:'Tørr takke, og varm'},
     body:{en:'A crescia is done in four or five minutes and takes all its colour from contact with the stone. A cold plate dries it out before it browns, and oil in the pan fries the outside and shuts the steam in, so the layers never open. Wipe the pan between breads, because burnt flour turns bitter and marks the next one.',
           no:'En crescia er ferdig på fire-fem minutter og henter all fargen fra kontakten med steinen. En kald takke tørker den ut før den blir brun, og olje i pannen steker utsiden og stenger dampen inne, slik at lagene aldri åpner seg. Tørk av pannen mellom hvert brød, for svidd mel blir bittert og setter merker i det neste.'}},
  ],
  variations:[
    {title:{en:'The plain crescia', no:'Den enkle cresciaen'},
     body:{en:'Away from Urbino the bread is simpler: flour, water, lard and salt, no eggs and no coiling, rolled out and cooked on the same hot stone. That is the everyday version, and it is the one that belongs with ciauscolo.',
           no:'Utenfor Urbino er brødet enklere, med mel, vann, smult og salt, uten egg og uten snegle, kjevlet ut og stekt på den samme varme steinen. Det er hverdagsutgaven, og den hører sammen med ciauscolo.'}},
    {title:{en:'What goes inside', no:'Hva som går inni'},
     body:{en:'Ham and casciotta d\'Urbino is the classic pairing, but the stalls also fill it with ciauscolo spread straight onto the hot bread, with grilled sausage, or with bitter greens cooked in oil and garlic.',
           no:'Skinke og casciotta d\'Urbino er den klassiske kombinasjonen, men bodene fyller den også med ciauscolo smurt rett på det varme brødet, med grillet pølse, eller med bitre bladgrønnsaker kokt i olje og hvitløk.'}},
    {title:{en:'The neighbours', no:'Naboene'},
     body:{en:'The same bread turns up on either side of the Marche under other names: piadina in Romagna, thinner and without egg, and torta al testo in Umbria, cooked on the flat stone called the <em>testo</em>. The Urbino version is the richest of the three.',
           no:'Det samme brødet dukker opp på begge sider av Marche under andre navn. I Romagna heter det piadina, som er tynnere og uten egg, og i Umbria torta al testo, stekt på den flate steinen som kalles <em>testo</em>. Utgaven fra Urbino er den rikeste av de tre.'}},
  ],
},

{
  id:'stoccafisso-allanconetana', dish:"Stoccafisso all'anconetana", course:'secondo', lesson:1, serves:6, time:{prep:30, cook:180},
  hero:'stoccafisso', tags:['fish','stockfish','slow','one pot'],
  title:{en:'Stoccafisso all\'anconetana', no:'Stoccafisso all\'anconetana'},
  blurb:{en:'Norwegian dried cod, potatoes, tomato and a great deal of olive oil, layered in one pot and left alone for three hours.',
         no:'Norsk tørrfisk, poteter, tomat og rikelig med olivenolje, lagt i lag i én gryte og latt i fred i tre timer.'},
  heroCaption:{en:'Stoccafisso all\'anconetana: the fish falls into flakes, and the potato holds the oil and the broth together.',
               no:'Stoccafisso all\'anconetana. Fisken faller i flak, og poteten holder oljen og kraften sammen.'},
  wines:['Verdicchio dei Castelli di Jesi','Verdicchio di Matelica'],
  headnote:{
    en:'<p>The Verdicchio reading names this dish beside brodetto as what the wine is drunk with, and leaves it there; the method below is the standard Ancona one rather than anything the course has said. It deserves a Norwegian cook\'s attention for an obvious reason: the fish is <strong>tørrfisk</strong>. Cod split, hung on racks in the cold sea air of Lofoten and dried without any salt has gone south to the Adriatic for centuries, and Ancona built a dish on it.</p>'
      + '<p>Drying takes about four fifths of the water out of the fish and concentrates everything else, so cooking it is mostly a matter of putting the water back. The fish soaks in cold water for three or four days, with the water changed twice a day, until it swells and gives under a finger. Nothing else in the recipe can make up for a short soak.</p>'
      + '<p>Then it is layered — onion, potato, fish, tomato, oil — covered, and left over the lowest heat for three hours with no spoon going into it. The potato falls apart at the edges and thickens the liquid, the oil and the gelatine from the fish come together into something between a stew and a sauce, and the pot is shaken rather than stirred, because after three hours the fish holds together only as long as nothing pushes it.</p>',
    no:'<p>Verdicchio-teksten nevner denne retten ved siden av brodetto som det vinen drikkes til, og lar det bli med det. Framgangsmåten nedenfor er den vanlige fra Ancona og ikke noe kurset selv har fortalt. For en norsk kokk er retten interessant av en åpenbar grunn, for fisken er <strong>tørrfisk</strong>. Torsk som er flekket, hengt på hjell i den kalde havluften i Lofoten og tørket helt uten salt, har gått sørover til Adriaterhavet i århundrer, og Ancona bygget en rett på den.</p>'
      + '<p>Tørkingen tar omtrent fire femdeler av vannet ut av fisken og konsentrerer alt det andre, så matlagingen handler mest om å få vannet tilbake. Fisken ligger i kaldt vann i tre-fire dager, og vannet skiftes to ganger om dagen, til den sveller og gir etter for en finger. Ingenting annet i oppskriften kan veie opp for en for kort utvanning.</p>'
      + '<p>Så legges alt i lag med løk, potet, fisk, tomat og olje, med lokk på, og står på svakest mulig varme i tre timer uten at en skje kommer i nærheten. Poteten faller fra hverandre i kantene og tykner væsken, oljen og gelatinen fra fisken går sammen til noe mellom en gryterett og en saus, og gryten ristes i stedet for å røres, for etter tre timer henger fisken sammen bare så lenge ingenting dytter borti den.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:1, u:'kg', n:{en:'soaked stockfish', no:'utvannet tørrfisk'}, note:{en:'from about 400 g of dried fish; ask for thick loin pieces, and buy it ready-soaked if the counter has it', no:'av omtrent 400 g tørr vare; be om tykke loinstykker, og kjøp den ferdig utvannet hvis disken har den'}},
    {q:1, u:'kg', n:{en:'waxy potatoes', no:'faste poteter'}, note:{en:'peeled and cut in thick slices', no:'skrelt og skåret i tykke skiver'}},
    {q:300, u:'g', n:{en:'onion', no:'løk'}, note:{en:'sliced thin', no:'skåret i tynne skiver'}},
    {q:400, u:'g', n:{en:'ripe tomatoes', no:'modne tomater'}, note:{en:'peeled and chopped', no:'flådde og hakkede'}},
    {q:4, u:'', n:{en:'anchovy fillets', no:'ansjosfileter'}, note:{en:'salted or in oil, rinsed; they salt the fish, which has none of its own', no:'ekte sardeller i salt eller olje, ikke norsk krydret ansjos; de salter fisken, som ikke har salt i seg selv'}, round:'half'},
    {q:2, u:'', n:{en:'garlic cloves', no:'hvitløksfedd'}, round:'half'},
    {q:150, u:'ml', n:{en:'extra-virgin olive oil', no:'extra virgin olivenolje'}, note:{en:'more than feels right; it is half the sauce', no:'mer enn det føles riktig, for den er halve sausen'}},
    {q:150, u:'ml', n:{en:'dry white wine', no:'tørr hvitvin'}, note:{en:'Verdicchio', no:'Verdicchio'}},
    {u:'', n:{en:'marjoram, rosemary and parsley', no:'merian, rosmarin og persille'}, note:{en:'a sprig of each, and the parsley chopped', no:'en kvast av hver, og persillen hakket'}, scale:'none'},
    {u:'', n:{en:'salt and black pepper', no:'salt og sort pepper'}, note:{en:'salt only at the end, once the anchovy has had its say', no:'salt først til slutt, når ansjosen har fått sagt sitt'}, scale:'none'},
  ]}],
  steps:[
    {en:'Soak the dried fish in a bowl of cold water in the fridge for three to four days, changing the water morning and evening, until it is swollen and springs back under a finger.',
     no:'Legg tørrfisken i en bolle med kaldt vann i kjøleskapet i tre-fire dager, og skift vannet morgen og kveld, til den er svellet og spretter tilbake under en finger.'},
    {en:'Drain it, pull the bones out with pliers and cut it into pieces the size of a matchbox. Leave the skin on: it holds the piece together and thickens the pot.',
     no:'Hell av vannet, dra ut beina med en tang, og skjær fisken i stykker på størrelse med en fyrstikkeske. La skinnet sitte på, for det holder stykket sammen og tykner gryten.'},
    {en:'Chop the anchovies and the garlic together and mash them into a little of the oil.',
     no:'Hakk ansjosen og hvitløken sammen, og mos dem ut i litt av oljen.'},
    {en:'Oil the base of a heavy pot and lay in half the onion, then half the potato slices in one layer.',
     no:'Olje bunnen av en tung gryte, og legg i halvparten av løken og deretter halvparten av potetskivene i ett lag.'},
    {en:'Put the fish on top, skin side down, and spread the anchovy paste and the herbs over it.',
     no:'Legg fisken oppå med skinnsiden ned, og fordel ansjosmosen og urtene over den.'},
    {en:'Cover it with the rest of the onion and potato and with the chopped tomato.',
     no:'Dekk den med resten av løken og poteten og med de hakkede tomatene.'},
    {en:'Pour the wine and the rest of the oil over, and add water until you can just see the liquid between the layers.',
     no:'Hell over vinen og resten av oljen, og spe med vann til du så vidt ser væsken mellom lagene.'},
    {en:'Bring it slowly to the barest simmer, put the lid on and leave it over the lowest heat for three hours.',
     no:'Kok det langsomt opp til det så vidt trekker, legg på lokk, og la det stå på svakest mulig varme i tre timer.'},
    {en:'Do not stir it. If it looks dry, shake the pot by the handles and pour a little hot water down the side.',
     no:'Ikke rør i den. Ser den tørr ut, rister du gryten i håndtakene og heller litt varmt vann ned langs kanten.'},
    {en:'It is done when the potato gives to a knife and the fish comes apart into flakes at a touch.',
     no:'Den er ferdig når poteten gir etter for kniven og fisken faller i flak ved en lett berøring.'},
    {en:'Taste for salt now, scatter the parsley over, and let it stand with the pot off the heat for twenty minutes. Serve it warm rather than piping hot.',
     no:'Smak til med salt nå, strø over persillen, og la retten stå med gryten av platen i tjue minutter. Server den lun og ikke rykende varm.'},
  ],
  notes:[
    {title:{en:'The soak is the recipe', no:'Utvanningen er oppskriften'},
     body:{en:'Drying removes most of the water and locks the muscle fibres together, and the soak has to work water back into a solid block, which happens slowly from the outside in. Cold water and a fridge keep the fish from spoiling over the days it takes, and the changes carry off the strong smell that puts people off stockfish. A piece still hard in the middle after three days is not ready, and heat will not rescue it.',
           no:'Tørkingen fjerner det meste av vannet og låser muskelfibrene sammen, og utvanningen må få vannet inn igjen i en fast blokk, noe som skjer langsomt utenfra og inn. Kaldt vann og kjøleskap hindrer at fisken blir dårlig i løpet av dagene det tar, og skiftene tar med seg den sterke lukten som skremmer folk fra tørrfisk. Et stykke som fortsatt er hardt i midten etter tre dager, er ikke klart, og varmen redder det ikke.'}},
    {title:{en:'Why nothing is stirred', no:'Derfor røres det ikke'},
     body:{en:'After three hours the fish is held together by gelatine alone, and a spoon turns the pot into porridge. The layers do the work a spoon would otherwise do: onion under the fish keeps it off the base, potato above holds it down, and the liquid moves by itself. If something has to be moved, shake the pot flat and short.',
           no:'Etter tre timer holdes fisken sammen bare av gelatin, og en skje gjør gryten til grøt. Lagene gjør jobben skjeen ellers ville gjort, for løken under fisken holder den fra bunnen, poteten over holder den nede, og væsken flytter på seg selv. Må du flytte noe, tar du i håndtakene og rister gryten kort og flatt.'}},
    {title:{en:'Oil, not butter or cream', no:'Olje, ikke smør eller fløte'},
     body:{en:'Stockfish is almost pure protein, and the oil is what makes the dish rich. It emulsifies with the gelatine and the potato starch into a thick, glossy liquid that coats the flakes. Cut the oil back and you get a dry, stringy pot with a thin broth in the bottom. The Norwegian instinct to reach for butter or cream gives a different and much heavier dish.',
           no:'Tørrfisk er nesten rent protein, og oljen er det som gjør retten fyldig. Den emulgerer med gelatinen og potetstivelsen til en tykk, blank væske som legger seg rundt flakene. Kutter du ned på oljen, får du en tørr og trevlete gryte med tynn kraft i bunnen. Den norske innskytelsen om å gripe etter smør eller fløte gir en annen og mye tyngre rett.'}},
  ],
  variations:[
    {title:{en:'Salt cod instead', no:'Klippfisk i stedet'},
     body:{en:'Klippfisk, cod salted rather than dried, works in the same pot and needs a shorter soak: a day and a half in cold water, changed often, to take the salt out. It cooks in half the time, so it goes in when the potato is already half done, and the anchovy is left out.',
           no:'Klippfisk, altså torsk som er saltet i stedet for tørket, fungerer i den samme gryten og trenger kortere utvanning, halvannet døgn i kaldt vann som skiftes ofte for å få ut saltet. Den koker på halve tiden, så den går i når poteten er halvveis ferdig, og ansjosen sløyfes.'}},
    {title:{en:'Better the next day', no:'Bedre dagen etter'},
     body:{en:'Like most slow pots it improves overnight, once the oil and the broth have settled. Reheat it very gently with a spoonful of water, and still without stirring.',
           no:'Som de fleste langtidsgryter blir den bedre dagen etter, når oljen og kraften har fått satt seg. Varm den svært forsiktig med en skje vann, og fortsatt uten å røre.'}},
    {title:{en:'What to serve with it', no:'Hva som hører til'},
     body:{en:'Ancona eats it with grilled bread, and further inland it comes with soft polenta. Boiled potatoes beside it are a mistake, since the pot is full of potato already.',
           no:'Ancona spiser den med grillet brød, og lenger inn i landet kommer den med bløt polenta. Kokte poteter ved siden av er en tabbe, for det ligger poteter i gryten fra før.'}},
  ],
},

];
