// Molise recipes. Contract: docs/recipe-format.md. Both languages in one file; never narrated.
// Everything here follows the region's own food reading (content/molise.js, lesson 3): cavatelli of
// semolina and water dragged with two fingers, the slow lamb or mutton ragu with a piece of pork in it,
// beans as the winter sauce, pampanella from San Martino in Pensilis, and scamorza on the grill.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-67'] = [

{
  id:'cavatelli', dish:'Cavatelli', course:'base', lesson:3, serves:4, time:{prep:45, cook:5},
  hero:'cavatelli', tags:['pasta','semolina','eggless','handmade'],
  title:{en:'Cavatelli', no:'Cavatelli'},
  blurb:{en:'Semolina, water and two fingers. Molise\'s everyday pasta carries no egg, and the hollow it is dragged into is the whole point.',
         no:'Semule, vann og to fingre. Hverdagspastaen i Molise inneholder ikke egg, og den hule formen den dras til, er hele poenget.'},
  heroCaption:{en:'Fresh cavatelli on the board. The rope is cut into pieces and each piece dragged into a shell.',
               no:'Ferske cavatelli på fjøla. Pølsen skjæres i biter, og hver bit dras ut til et skjell.'},
  wines:['Tintilia del Molise'],
  headnote:{
    en:'<p>Cavatelli are the pasta of Molise and of the drove roads that made it. Durum semolina and water, no egg. The dough costs almost nothing, needs no fresh ingredient that could spoil, and can be made on a board in a kitchen with one pot. The region\'s reading calls them cousins of Puglia\'s orecchiette, and the kinship is real: both are dragged rather than rolled, and both are built to carry a sauce rather than to be admired.</p>'
      + '<p>The shape does the work. A piece of dough dragged under two fingers curls over on itself and comes off the board as a small hollow shell with a slightly rough outside. The roughness is semolina and the hollow is a trap, so ragù, beans or oil and garlic sit inside instead of sliding off. That is why a cavatello carries more sauce than a smooth commercial pasta of the same weight.</p>'
      + '<p>Two things are not negotiable. The flour must be fine-ground durum semolina, because soft wheat has neither the protein to hold a shape without egg nor the bite afterwards. And the water must be warm, because warm water lets semolina hydrate in minutes instead of an hour. You decide the width of the rope, the number of fingers, and whether you reach for a knife.</p>',
    no:'<p>Cavatelli er pastaen i Molise og på drifteveiene som formet regionen. Durumsemule og vann, uten egg. Deigen koster nesten ingenting, trenger ingen ferske råvarer som kan bli dårlige, og kan lages på en fjøl i et kjøkken med én gryte. Lesteksten for regionen kaller dem søskenbarn av orecchiette fra Puglia, og slektskapet er reelt. Begge dras ut i stedet for å kjevles, og begge er bygget for å bære saus.</p>'
      + '<p>Formen gjør jobben. En bit deig som dras under to fingre, krøller seg over seg selv og løsner fra fjøla som et lite hult skjell med litt ru overflate. Ruheten kommer fra semulen, og hulrommet er en felle, så ragù, bønner eller olje og hvitløk legger seg inni i stedet for å gli av. Derfor bærer en cavatello mer saus enn en glatt kjøpepasta av samme vekt.</p>'
      + '<p>To ting kan du ikke endre på. Melet må være finmalt durumsemule, for hvetemel har verken proteinet som trengs for å holde formen uten egg, eller tyggemotstanden etterpå. Og vannet må være varmt, for varmt vann lar semulen trekke til seg væske på minutter i stedet for på en time. Hvor tykk pølsen er, hvor mange fingre du bruker og om du tar kniven til hjelp, avgjør du selv.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:400, u:'g', n:{en:'durum semolina', no:'durumsemule'},
     note:{en:'fine-ground, sold as semola di grano duro rimacinata. Plain wheat flour will not hold the shape',
           no:'finmalt, selges som semola di grano duro rimacinata. Vanlig hvetemel holder ikke på formen'}},
    {q:200, u:'ml', n:{en:'warm water', no:'varmt vann'},
     note:{en:'at about 40 °C, poured in a little at a time', no:'på rundt 40 °C, tilsatt litt om gangen'}},
    {q:5, u:'g', n:{en:'fine salt', no:'fint salt'},
     note:{en:'for the dough', no:'til deigen'}},
    {u:'', n:{en:'extra semolina', no:'ekstra semule'},
     note:{en:'for the board and the tray', no:'til fjøla og brettet'}, scale:'none'},
    {q:4, u:'l', n:{en:'water for boiling', no:'kokevann'}, scale:'sub'},
    {q:30, u:'g', n:{en:'coarse salt for the water', no:'grovt salt til kokevannet'}, scale:'sub'},
  ]}],
  steps:[
    {en:'Tip the semolina onto a board and make a well in the middle of it.',
     no:'Ha semulen ut på en fjøl, og lag en grop midt i haugen.'},
    {en:'Dissolve the fine salt in the warm water.',
     no:'Løs opp det fine saltet i det varme vannet.'},
    {en:'Pour a third of the water into the well and draw the semolina in from the sides with your fingertips.',
     no:'Hell en tredel av vannet i gropen, og dra semulen innover fra sidene med fingertuppene.'},
    {en:'Add the rest of the water a little at a time until the dough comes together in a shaggy mass.',
     no:'Tilsett resten av vannet litt om gangen, til deigen samler seg i en ujevn klump.'},
    {en:'Knead for ten minutes, pushing the dough away with the heel of your hand and folding it back, until it is smooth and firm.',
     no:'Elt i ti minutter. Skyv deigen fra deg med håndroten og brett den tilbake, til den er glatt og fast.'},
    {en:'Wrap the dough and let it rest for half an hour at room temperature, so the semolina finishes drinking the water.',
     no:'Pakk deigen inn, og la den hvile en halvtime i romtemperatur, så semulen rekker å trekke til seg resten av vannet.'},
    {en:'Cut off a piece the size of an egg and keep the rest covered so it does not skin over.',
     no:'Skjær av et stykke på størrelse med et egg, og hold resten tildekket så den ikke tørker i overflaten.'},
    {en:'Roll the piece under your palms into a rope about as thick as a pencil.',
     no:'Rull stykket under håndflatene til en pølse omtrent så tykk som en blyant.'},
    {en:'Cut the rope into pieces of about 1.5 cm.',
     no:'Skjær pølsen i biter på rundt 1,5 cm.'},
    {en:'Press each piece with the tips of two fingers and drag it towards you along the board, so it curls into a hollow shell.',
     no:'Trykk hver bit med tuppen av to fingre, og dra den mot deg langs fjøla, slik at den krøller seg til et hult skjell.'},
    {en:'Lay the finished cavatelli on a tray dusted with semolina, not touching each other, and work through the rest of the dough.',
     no:'Legg de ferdige cavatelli på et brett strødd med semule, uten at de ligger inntil hverandre, og arbeid deg gjennom resten av deigen.'},
    {en:'Boil them in well-salted water until they float and the centre has lost its chalky bite, three to five minutes, then lift them straight into the sauce.',
     no:'Kok dem i godt saltet vann til de flyter opp og kjernen ikke lenger er melen, altså tre til fem minutter, og løft dem rett over i sausen.'},
  ],
  notes:[
    {title:{en:'Why there is no egg', no:'Hvorfor det ikke er egg i deigen'},
     body:{en:'Egg pasta belongs to regions with grain to spare and hens in the yard; the tratturi belonged to people carrying flour. Semolina and water give a dough that dries hard, keeps for weeks on a shelf and boils up firm, where egg dough turns soft and has to be eaten within days. The bite of a cavatello, slightly chewy where the shell is thickest, comes from that absence.',
           no:'Eggpasta hører hjemme i landsdeler med korn til overs og høner i gården, mens drifteveiene hørte til folk som bar med seg mel. Semule og vann gir en deig som tørker hard, holder seg i ukevis på en hylle og koker opp fast, mens eggdeig blir myk og må spises i løpet av noen dager. Tyggemotstanden i en cavatello, litt seig der skjellet er tykkest, kommer nettopp av at egget mangler.'}},
    {title:{en:'The rough surface is not a flaw', no:'Den ru overflaten er ingen feil'},
     body:{en:'Semolina dragged across wood comes away with a fine grain on the outside, the texture that industrial bronze dies are built to imitate. Sauce grips it. Lift the pasta straight from the pot into the pan with a little of its water, and the starch on that rough skin binds the sauce; pour it into a colander and rinse it, and the sauce slides off a smooth, cold shell.',
           no:'Semule som dras over tre, får en fin ruhet på utsiden, den samme overflaten som industrielle bronsematriser er laget for å etterligne. Sausen fester seg til den. Løfter du pastaen rett fra gryta over i panna med litt av kokevannet, binder sausen seg til den ru overflaten. Heller du den i et dørslag og skyller den, glir sausen av et glatt og kaldt skjell.'}},
    {title:{en:'Warm water, and why the dough rests', no:'Varmt vann, og hvorfor deigen hviler'},
     body:{en:'Semolina is milled coarser than flour and takes its time to hydrate. Warm water speeds that up and the half-hour rest finishes it: a dough that felt dry and crumbly when you stopped kneading will be smooth and obedient when you come back to it. Shape it too early and the pieces crack at the edge as you drag them.',
           no:'Semule er malt grovere enn mel og bruker tid på å trekke til seg vann. Varmt vann setter fart på det, og hvilen på en halvtime gjør resten. En deig som kjentes tørr og smuldrete da du sluttet å elte, er glatt og føyelig når du kommer tilbake til den. Former du bitene for tidlig, sprekker de i kanten mens du drar dem ut.'}},
  ],
  variations:[
    {title:{en:'With a knife, or on a ridged board', no:'Med kniv, eller på rillebrett'},
     body:{en:'Many Molisan cooks drag the dough with the blunt edge of a small knife instead of two fingers, which makes a longer, narrower shell, and a ridged wooden gnocchi board gives the same shell with a striped back. All three hold sauce. Use whichever gives you an even result at speed, because the only real enemy is a tray of pieces of different thickness that cook at different rates.',
           no:'Mange kokker i Molise drar deigen med den butte siden av en liten kniv i stedet for med to fingre, og da blir skjellet lengre og smalere. Et riflet gnocchibrett av tre gir det samme skjellet med striper på ryggen. Alle tre holder på saus. Bruk den måten som gir jevnt resultat i fart, for den eneste virkelige fienden er et brett med biter av ulik tykkelse som blir ferdige til ulik tid.'}},
    {title:{en:'Drying them, and keeping them', no:'Tørking og oppbevaring'},
     body:{en:'Spread the cavatelli in one layer on a semolina-dusted tray and leave them out for a day, turning them once, until they snap rather than bend. They then keep in a paper bag for a month and want a minute or two longer in the water. To freeze them, freeze the tray first and bag them once they are hard, then boil them straight from the freezer.',
           no:'Legg cavatelli i ett lag på et brett strødd med semule, og la dem stå framme et døgn. Snu dem én gang underveis, til de knekker i stedet for å bøye seg. Da holder de seg i en papirpose i en måned og trenger ett eller to minutter ekstra i vannet. Vil du fryse dem, setter du brettet i fryseren først og pakker dem i pose når de er harde. Kok dem rett fra frossen tilstand.'}},
    {title:{en:'The three sauces of the region', no:'De tre sausene i regionen'},
     body:{en:'The reading names them: a slow lamb or mutton ragù for feast days, beans for winter, and garlic, oil and chilli for a weekday. None of them needs cream or butter. Grate aged caciocavallo over the first two and nothing at all over the third.',
           no:'Lesteksten nevner dem alle tre: en langkokt ragù av lam eller sau til festdager, bønner om vinteren, og hvitløk, olje og chili på en hverdag. Ingen av dem trenger fløte eller smør. Riv moden caciocavallo over de to første, og ingenting over den tredje.'}},
  ],
},

{
  id:'cavatelli-al-ragu-di-agnello', dish:'Cavatelli al ragù di agnello', course:'primo', lesson:3, serves:4, time:{prep:25, cook:180},
  hero:'ragu', tags:['pasta','lamb','ragu','feast'],
  title:{en:'Cavatelli al ragù di agnello', no:'Cavatelli al ragù di agnello'},
  blurb:{en:'The feast-day plate of Molise: lamb and a piece of pork cooked down all morning, tossed through cavatelli and dusted with aged caciocavallo.',
         no:'Festdagsretten i Molise. Lam og et stykke svin koker hele formiddagen, og ragùen vendes inn i cavatelli og drysses med moden caciocavallo.'},
  heroCaption:{en:'A portion of cavatelli al ragù from a tray at a village sagra, with bread beside it.',
               no:'En porsjon cavatelli al ragù fra et brett på en landsbysagra, med brød ved siden av.'},
  wines:['Tintilia del Molise'],
  headnote:{
    en:'<p>The region\'s food reading is blunt about what goes on cavatelli: most often a slow lamb or mutton ragù, and on feast days a ragù that has cooked all morning with a piece of pork in it. That second sentence is the recipe. The lamb gives the sauce its flavour and the pork gives it body, and neither is there for the sake of variety. A shepherd\'s household had mutton because it had sheep, and pork because everyone had a pig.</p>'
      + '<p>This is a southern ragù, which means very little tomato in relation to the meat and a great deal of time. The meat browns first, in pieces on the bone, then goes back into a low pot with onion, a glass of red and passata, and is left for three hours until it falls off the bone by itself. Nothing is minced and nothing is added at the end to thicken it. The sauce thickens because the connective tissue in a shoulder and a rib turns to gelatine.</p>'
      + '<p>Two things from the reading are worth keeping. The pasta is eggless semolina cavatelli, which stand up to three hours\' worth of sauce where a soft egg pasta would collapse. And the cheese on top is caciocavallo at a year or more, when it has gone firm, straw-yellow and savoury: young caciocavallo melts into strings and disappears.</p>',
    no:'<p>Lesteksten om mat er tydelig på hva som havner på cavatelli: som oftest en langkokt ragù av lam eller sau, og på festdager en ragù som har kokt hele formiddagen med et stykke svin oppi. Den siste setningen er selve oppskriften. Lammet gir sausen smak og svinet gir den fylde, og ingen av delene er der for variasjonens skyld. En gjeterfamilie hadde sauekjøtt fordi den hadde sauer, og svinekjøtt fordi alle hadde en gris.</p>'
      + '<p>Dette er en søritaliensk ragù, altså lite tomat i forhold til kjøttmengden og svært mye tid. Kjøttet brunes først, i stykker med bein i, og går så tilbake i en lav gryte sammen med løk, et glass rødvin og passata, og blir stående i tre timer til det faller av beinet av seg selv. Ingenting kvernes, og ingenting tilsettes til slutt for å jevne sausen. Den tykner fordi bindevevet i bog og ribbe blir til gelatin.</p>'
      + '<p>To ting fra lesteksten er verdt å holde på. Pastaen er cavatelli av semule uten egg, og de tåler tre timers saus der en myk eggpasta ville falt fra hverandre. Og osten på toppen er caciocavallo på et år eller mer, når den er fast, stråfarget og smaksrik. Ung caciocavallo smelter til tråder og forsvinner.</p>'},
  ingredients:[
    { group:{en:'The ragù', no:'Ragùen'}, items:[
      {q:800, u:'g', n:{en:'lamb shoulder on the bone', no:'lammebog med bein'},
       note:{en:'in large pieces. Hogget or mutton is closer to the original and wants another half-hour; in Norway ask for saubog',
             no:'i store stykker. Kjøtt fra eldre sau ligger nærmere originalen og trenger en halvtime til; be slakteren om saubog'}},
      {q:300, u:'g', n:{en:'pork ribs', no:'svineribbe'},
       note:{en:'one thick piece, or two or three ribs. They are in the pot for gelatine, not for the meat',
             no:'ett tykt stykke, eller to–tre ribbein. De ligger i gryta for gelatinen, ikke for kjøttets skyld'}},
      {q:60, u:'ml', n:{en:'extra-virgin olive oil', no:'extra virgin olivenolje'}},
      {q:1, u:'', n:{en:'onion', no:'løk'}, note:{en:'finely chopped', no:'finhakket'}, round:'half'},
      {q:2, u:'', n:{en:'garlic cloves', no:'hvitløksfedd'},
       note:{en:'crushed flat but left whole', no:'knust flate, men hele'}, round:'half'},
      {q:150, u:'ml', n:{en:'dry red wine', no:'tørr rødvin'},
       note:{en:'Tintilia if you have it open, otherwise any dry southern red', no:'Tintilia hvis du har en åpen, ellers en hvilken som helst tørr rødvin fra Sør-Italia'}},
      {q:700, u:'g', n:{en:'passata', no:'passata'},
       note:{en:'plain sieved tomato, not a seasoned sauce', no:'siktet tomat uten krydder, ikke ferdig saus'}},
      {q:1, u:'', n:{en:'dried chilli', no:'tørket chili'},
       note:{en:'whole, fished out before serving', no:'hel, fiskes opp før servering'}, round:'half'},
      {q:2, u:'', n:{en:'bay leaves', no:'laurbærblad'}, round:'half'},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
      {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
    ]},
    { group:{en:'To finish', no:'Til servering'}, items:[
      {q:600, u:'g', n:{en:'fresh cavatelli', no:'ferske cavatelli'},
       note:{en:'the recipe above. Dried cavatelli or orecchiette also work and want a few minutes longer',
             no:'oppskriften over. Tørkede cavatelli eller orecchiette fungerer også og trenger noen minutter lenger'}},
      {q:80, u:'g', n:{en:'aged caciocavallo', no:'moden caciocavallo'},
       note:{en:'a year old or more, grated. Aged pecorino is the nearest thing on a Norwegian counter',
             no:'et år gammel eller mer, revet. Moden pecorino er det nærmeste du finner i en norsk ostedisk'}},
      {q:4, u:'l', n:{en:'water for boiling', no:'kokevann'}, scale:'sub'},
      {q:30, u:'g', n:{en:'coarse salt for the water', no:'grovt salt til kokevannet'}, scale:'sub'},
    ]},
  ],
  steps:[
    {en:'Dry the lamb and the pork with paper and salt them on every side.',
     no:'Tørk lammet og svinet med papir, og salt kjøttet på alle sider.'},
    {en:'Heat the oil in a heavy pot over a high flame and brown the meat in batches until it is dark all over.',
     no:'Varm oljen i en tykkbunnet gryte på sterk varme, og brun kjøttet i omganger til det er mørkt på alle sider.'},
    {en:'Lift the meat out and pour off the fat, leaving only a film in the pot.',
     no:'Ta kjøttet opp, og hell av fettet slik at bare en hinne blir igjen i gryta.'},
    {en:'Turn the heat down, add the onion and garlic and cook them soft and golden, about ten minutes.',
     no:'Skru ned varmen, ha i løk og hvitløk, og la det surre mykt og gyllent i ti minutter.'},
    {en:'Pour in the wine and let it boil until the smell of alcohol is gone and the pot is almost dry.',
     no:'Hell i vinen, og la den koke til alkohollukten er borte og gryta nesten er tørr.'},
    {en:'Return the meat with any juice that ran out of it, add the passata, the chilli and the bay, and rinse the passata bottle out into the pot with a little water.',
     no:'Legg kjøttet tilbake sammen med kraften som har rent av, tilsett passata, chili og laurbær, og skyll passataflasken med litt vann som du heller i gryta.'},
    {en:'Bring it to a bare simmer, set the lid ajar and leave it for three hours, stirring every half-hour so nothing catches.',
     no:'La det så vidt småkoke med lokket på gløtt i tre timer, og rør hver halvtime så ingenting brenner seg.'},
    {en:'Lift the meat out, pull it off the bones in shreds, and discard the bones, the chilli and the bay.',
     no:'Ta opp kjøttet, plukk det i trevler av beina, og kast bein, chili og laurbær.'},
    {en:'Return the shredded meat to the sauce, taste it for salt and pepper, and hold it over the lowest heat.',
     no:'Ha det plukkede kjøttet tilbake i sausen, smak til med salt og pepper, og hold den varm på svakeste varme.'},
    {en:'Boil the cavatelli in well-salted water until they float and are still firm in the middle.',
     no:'Kok cavatelli i godt saltet vann til de flyter opp og fortsatt er faste i kjernen.'},
    {en:'Lift them into the sauce with a ladle of their water and toss them over the heat for a minute, so the sauce coats every shell.',
     no:'Løft dem over i sausen med en øse av kokevannet, og vend dem over varmen et minutt, så sausen legger seg rundt hvert skjell.'},
    {en:'Serve with grated caciocavallo, and leave the rest of the cheese on the table.',
     no:'Server med revet caciocavallo, og la resten av osten stå på bordet.'},
  ],
  notes:[
    {title:{en:'Bone, not mince', no:'Bein, ikke kvern'},
     body:{en:'A ragù built on minced meat is done in forty minutes and tastes mostly of tomato. Pieces on the bone take three hours because that is how long collagen needs to become gelatine, and the gelatine is what makes the sauce cling to the pasta without flour or cream. The pork rib sits in the pot for that reason alone.',
           no:'En ragù laget på kvernet kjøtt er ferdig på førti minutter og smaker mest av tomat. Stykker med bein tar tre timer, for så lang tid trenger kollagenet på å bli til gelatin, og gelatinen får sausen til å legge seg rundt pastaen uten mel eller fløte. Svineribba ligger i gryta bare av den grunn.'}},
    {title:{en:'Why so little tomato', no:'Hvorfor det er så lite tomat'},
     body:{en:'In the south a ragù is a meat sauce with tomato in it, not a tomato sauce with meat in it. Keep the passata to roughly the weight of the meat and let it reduce for hours: the colour goes from red to brick, the acidity cooks out, and the sauce ends up tasting of lamb. Double the tomato and three hours will not rescue it.',
           no:'I Sør-Italia er en ragù en kjøttsaus med tomat i, ikke en tomatsaus med kjøtt i. Hold mengden passata omtrent på vekten av kjøttet, og la den koke inn i timevis. Fargen går fra rød til teglrød, syren koker bort, og til slutt smaker sausen av lam. Dobler du tomaten, hjelper det ikke med tre timer.'}},
    {title:{en:'The pasta water is an ingredient', no:'Kokevannet er en ingrediens'},
     body:{en:'Cavatelli shed starch into the water, and a ladle of that water tipped into the pan turns a thick ragù into something that coats rather than sits on top. Add it a little at a time while tossing over the heat, and stop when the sauce leaves a clean trail across the bottom of the pan.',
           no:'Cavatelli gir fra seg stivelse til kokevannet, og en øse av det vannet i panna gjør en tykk ragù til en saus som legger seg rundt pastaen i stedet for å bli liggende oppå. Tilsett litt om gangen mens du vender over varmen, og stopp når sausen etterlater et rent spor i bunnen av panna.'}},
  ],
  variations:[
    {title:{en:'Mutton, as it was', no:'Sauekjøtt, slik det opprinnelig var'},
     body:{en:'The reading says lamb or mutton, and mutton is the older answer, because the animals that walked the tratturi were not spring lambs. Norwegian butchers sell saubog and saulår, and they give a deeper, gamier sauce that wants another half-hour and a little more wine. Trim the hard fat before browning, or the sauce turns waxy as it cools.',
           no:'Lesteksten sier lam eller sau, og sau er det opprinnelige svaret. Dyrene som gikk langs drifteveiene, var ikke vårlam. Norske slaktere selger saubog og saulår, og de gir en dypere og mer viltsmakende saus som trenger en halvtime til og litt mer vin. Skjær bort det harde fettet før bruningen, ellers blir sausen voksaktig når den kjølner.'}},
    {title:{en:'Without three hours', no:'Uten tre timer'},
     body:{en:'A pressure cooker gets the meat to the same place in about an hour, but the sauce comes out thin, because nothing evaporates under a sealed lid. Cook the meat under pressure, shred it, then boil the sauce down uncovered for twenty minutes before the two go back together.',
           no:'En trykkoker gjør kjøttet like mørt på rundt en time, men sausen blir tynn fordi ingenting fordamper under et tett lokk. Kok kjøttet under trykk, plukk det i trevler, og kok sausen inn uten lokk i tjue minutter før de to går sammen igjen.'}},
    {title:{en:'What to drink with it', no:'Hva du skal drikke til'},
     body:{en:'Tintilia del Molise is the regional answer and the wine the course pairs with this plate: peppery, full of sour cherry, with enough acidity to cut three hours of lamb fat. Serve it at 16–18 °C. Biferno Rosso, the Montepulciano and Aglianico blend from the river valley, is the softer alternative and the easier bottle to find.',
           no:'Tintilia del Molise er regionens eget svar og den vinen kurset setter til denne retten. Den er pepret, har surkirsebær og nok syre til å skjære gjennom tre timer med lammefett. Skjenk den ved 16–18 °C. Biferno Rosso, blandingen av Montepulciano og Aglianico fra elvedalen, er det mykere alternativet og den flasken som er lettest å få tak i.'}},
  ],
},

{
  id:'cavatelli-e-fagioli', dish:'', course:'primo', lesson:3, serves:4, time:{prep:15, cook:120},
  hero:'fagioli', tags:['pasta','beans','winter','one-pot'],
  title:{en:'Cavatelli e fagioli', no:'Cavatelli e fagioli'},
  blurb:{en:'Beans, a little cured pork and cavatelli in one pot. The reading calls beans one of the three sauces of Molise, and this is the winter one.',
         no:'Bønner, litt spekemat og cavatelli i én gryte. Lesteksten kaller bønner en av de tre sausene i Molise, og dette er vinterutgaven.'},
  heroCaption:{en:'Pasta e fagioli as it is eaten all along the Apennines. There is no free photograph of the Molisan version, which uses cavatelli.',
               no:'Pasta e fagioli slik den spises langs hele Apenninene. Det finnes ikke noe fritt bilde av utgaven fra Molise, som bruker cavatelli.'},
  wines:['Biferno Rosso'],
  headnote:{
    en:'<p>Molise\'s food reading lists three things that go on cavatelli: a slow lamb ragù, garlic and chilli, and beans. Beans are the winter one, and they answer a question the region kept asking. What do you eat in a hill village in February, when the flocks are away on the plain and the garden is finished? Dried beans keep from one harvest to the next, and a piece of preserved pork keeps alongside them.</p>'
      + '<p>The dish is built so that the beans become the sauce. A third of them are blended into the cooking liquid, which thickens it to something between a soup and a dressing, and the rest stay whole. The pasta then boils in that liquid instead of in a separate pot, so the starch it gives off stays in the dish. That is why a bowl of this is glossy rather than watery, and it is also why the pot needs watching: the same starch catches on the bottom if it is left alone.</p>'
      + '<p>Everything else is what a cold house had. Olive oil from the hills behind the coast, a dried chilli, a bay leaf, garlic, and either a rind of caciocavallo or a piece of cured pork for depth. Leave the meat out and the dish is still complete; leave out the rosemary or the celery and nobody in Molise will notice.</p>',
    no:'<p>Lesteksten om mat i Molise nevner tre ting som havner på cavatelli: en langkokt ragù av lam, hvitløk og chili, og bønner. Bønner er vinterutgaven, og de svarer på et spørsmål regionen stilte gang på gang. Hva spiser man i en åsbygd i februar, når flokkene er nede på sletta og hagen er ferdig for året? Tørkede bønner holder seg fra én høst til den neste, og et stykke konservert svinekjøtt holder seg sammen med dem.</p>'
      + '<p>Retten er bygget slik at bønnene blir sausen. En tredel av dem kjøres glatte i kokekraften, som da tykner til noe mellom en suppe og en saus, mens resten får ligge hele. Pastaen koker deretter i den kraften i stedet for i en egen gryte, så stivelsen den gir fra seg, blir værende i retten. Derfor blir en skål av dette blank og ikke vannete, og derfor må du følge med på gryta, for den samme stivelsen brenner seg i bunnen hvis den får stå i fred.</p>'
      + '<p>Resten er det som fantes i et kaldt hus. Olivenolje fra åsene bak kysten, en tørket chili, et laurbærblad, hvitløk, og enten en osteskorpe av caciocavallo eller et stykke spekemat for dybde. Utelater du kjøttet, er retten like fullstendig. Utelater du rosmarinen eller selleristilken, er det ingen i Molise som merker det.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:300, u:'g', n:{en:'dried beans', no:'tørkede bønner'},
     note:{en:'borlotti or cannellini, soaked overnight in plenty of cold water. Tinned beans let you skip the first four steps, but the cooking liquid is half the dish',
           no:'borlotti eller cannellini, lagt i bløt over natten i rikelig med kaldt vann. Bønner på boks lar deg hoppe over de fire første trinnene, men kokekraften er halve retten'}},
    {q:1.5, u:'l', n:{en:'water for the beans', no:'vann til bønnene'},
     note:{en:'topped up with boiling water as it reduces', no:'fylles på med kokende vann etter hvert som det koker inn'}, scale:'sub'},
    {q:1, u:'', n:{en:'onion', no:'løk'},
     note:{en:'peeled and dropped in whole, then thrown away', no:'skrelt og lagt hel oppi, og kastet etterpå'}, round:'half'},
    {q:1, u:'', n:{en:'celery stick', no:'selleristilk'}, round:'half'},
    {q:1, u:'', n:{en:'bay leaf', no:'laurbærblad'}, round:'half'},
    {q:2, u:'', n:{en:'garlic cloves', no:'hvitløksfedd'},
     note:{en:'one for the beans, one crushed flat for the pan', no:'ett til bønnene, ett knust flatt til panna'}, round:'half'},
    {q:1, u:'', n:{en:'dried chilli', no:'tørket chili'}, round:'half'},
    {u:'', n:{en:'rosemary', no:'rosmarin'},
     note:{en:'one sprig, taken out before the pasta goes in', no:'en kvist, som tas opp før pastaen has i'}, scale:'none'},
    {q:60, u:'ml', n:{en:'extra-virgin olive oil', no:'extra virgin olivenolje'},
     note:{en:'and more to pour over at the table', no:'og mer til å helle over ved bordet'}},
    {q:80, u:'g', n:{en:'pancetta or ventricina', no:'pancetta eller ventricina'},
     note:{en:'in small dice. A rind of caciocavallo or pecorino does the same work without meat',
           no:'i små terninger. En osteskorpe av caciocavallo eller pecorino gjør den samme jobben uten kjøtt'}},
    {q:300, u:'g', n:{en:'fresh cavatelli', no:'ferske cavatelli'},
     note:{en:'the recipe above. Dried cavatelli want longer and should go in earlier', no:'oppskriften over. Tørkede cavatelli trenger lenger tid og må i tidligere'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
  ]}],
  steps:[
    {en:'Drain the soaked beans and rinse them under cold water.',
     no:'Hell av bløtvannet, og skyll bønnene i kaldt vann.'},
    {en:'Put them in a deep pot with the water, the whole onion, the celery, the bay leaf and one garlic clove, and bring them slowly to a simmer.',
     no:'Legg dem i en dyp gryte med vannet, den hele løken, selleristilken, laurbærbladet og det ene hvitløksfeddet, og la det langsomt komme til småkoking.'},
    {en:'Cook them at a bare simmer, without salt, until the skins are soft and a bean crushes between your fingers, an hour to an hour and a half depending on their age.',
     no:'La dem så vidt småkoke uten salt til skallene er myke og en bønne lar seg knuse mellom fingrene, altså i en til halvannen time alt etter hvor gamle de er.'},
    {en:'Salt them only now, and let them stand in their liquid with the pot off the heat.',
     no:'Salt dem først nå, og la dem stå i kraften med gryta av platen.'},
    {en:'Fish out the onion, the celery and the bay leaf and throw them away.',
     no:'Fisk opp løken, selleristilken og laurbærbladet, og kast dem.'},
    {en:'Lift a third of the beans out with some of their liquid, blend them smooth and stir the purée back into the pot.',
     no:'Ta opp en tredel av bønnene med litt av kraften, kjør dem glatte, og rør puréen tilbake i gryta.'},
    {en:'Warm the oil in a wide pan with the crushed garlic clove, the chilli, the rosemary and the diced pancetta, until the fat has rendered and the garlic is pale gold.',
     no:'Varm oljen i en vid panne med det knuste hvitløksfeddet, chilien, rosmarinen og pancettaterningene, til fettet har smeltet ut og hvitløken er lyst gyllen.'},
    {en:'Pour the beans and their liquid into the pan and bring it back to a simmer. It should look loose, because the pasta will drink a good deal of it.',
     no:'Hell bønnene og kraften over i panna, og la det komme til småkoking igjen. Det skal se tynt ut, for pastaen kommer til å drikke mye av det.'},
    {en:'Slide in the cavatelli and cook them in the bean liquid, stirring often so nothing sticks, until they are firm in the middle.',
     no:'Ha cavatelli i, og kok dem i bønnekraften mens du rører ofte så ingenting setter seg, til de er faste i kjernen.'},
    {en:'Take out the rosemary and the chilli, and add boiling water if the pan tightens before the pasta is done.',
     no:'Ta opp rosmarinen og chilien, og spe med kokende vann hvis panna tykner før pastaen er ferdig.'},
    {en:'Pull the pan off the heat, cover it and leave it for five minutes so the pasta and the beans settle together.',
     no:'Trekk panna av platen, legg på lokk, og la det stå i fem minutter så pasta og bønner faller til ro sammen.'},
    {en:'Serve in warm bowls with pepper ground over and a thread of raw olive oil on each one.',
     no:'Server i varme skåler med pepper kvernet over og en stråle rå olivenolje på hver porsjon.'},
  ],
  notes:[
    {title:{en:'Acid late, salt late', no:'Syren sent, saltet sent'},
     body:{en:'Acid keeps a bean skin tough. A little tomato or a splash of vinegar early in the pot leaves the skins leathery long after the insides have gone to mush, so cook the beans in plain water with aromatics only and add anything sour once they are soft. When you salt at the end the beans can also cool in their liquid and take the salt right through, which a drained bean never does.',
           no:'Syre holder bønneskallet seigt. Litt tomat eller en skvett eddik tidlig i gryta gjør at skallene blir læraktige lenge etter at innmaten har gått i grøt, så kok bønnene i rent vann med bare urter og grønnsaker oppi, og tilsett alt surt etter at de er myke. Når du salter til slutt, kan bønnene dessuten kjølne i kraften og trekke saltet helt inn, og det gjør aldri en avsilt bønne.'}},
    {title:{en:'Why the pasta cooks in the beans', no:'Hvorfor pastaen koker i bønnene'},
     body:{en:'Boil the cavatelli separately and spoon them into the beans, and you are left with two good things that never meet. Cooked in the bean liquid they give up their starch where it is wanted and take on the flavour of the pot: the liquid thickens, the pasta seasons itself, and the bowl holds together instead of separating into pasta and soup. The price is attention, because starch on the bottom of a pot burns.',
           no:'Koker du cavatelli for seg og øser dem over i bønnene, sitter du igjen med to gode ting som aldri møtes. Koker de derimot i bønnekraften, gir de fra seg stivelsen der den trengs, og de tar til seg smaken fra gryta. Kraften tykner, pastaen salter seg selv, og skålen henger sammen i stedet for å skille seg i pasta og suppe. Prisen er at du må følge med, for stivelse i bunnen av en gryte brenner seg.'}},
    {title:{en:'A third puréed, the rest whole', no:'En tredel most, resten hel'},
     body:{en:'The purée is the sauce and the whole beans are the texture. Make the dish from only one of them and you get either a paste or a thin soup with things floating in it. A third of the pot blended is the usual ratio: blend more if the beans were old and refused to break down, less if they collapsed on their own.',
           no:'Puréen er sausen og de hele bønnene er tyggemotstanden. Lager du retten med bare den ene delen, ender du enten med en grøt eller med en tynn suppe med bønner i. En tredel av gryta kjørt glatt er det vanlige forholdet. Kjør mer hvis bønnene var gamle og ikke ville koke ut, og mindre hvis de falt fra hverandre av seg selv.'}},
  ],
  variations:[
    {title:{en:'With tomato', no:'Med tomat'},
     body:{en:'Many houses add a little passata or a few dried tomatoes along with the oil and garlic, which turns the bowl pink and sharpens it. Put it in the pan and not in the beans while they cook, for the reason in the first note. Keep the quantity small, because the beans should still be the loudest thing in the bowl.',
           no:'Mange hus har i litt passata eller noen tørkede tomater sammen med oljen og hvitløken, og da blir skålen rosa og får mer spiss. Ha det i panna og ikke i bønnene mens de koker, av grunnen som står i den første merknaden. Hold mengden liten, for bønnene skal fortsatt være det kraftigste i skålen.'}},
    {title:{en:'Beans and greens', no:'Bønner og grønt'},
     body:{en:'The reading names beans and greens together as the winter table. Wilt a head of chicory, some cavolo nero or any bitter green in the oil before the beans go in, and the bowl gains both the bitterness and the colour it otherwise lacks. The same beans are eaten with no pasta at all, with bread beside them.',
           no:'Lesteksten nevner bønner og grønt sammen som vintermaten. Surr en sikorisalat, litt cavolo nero eller et annet bittert grønt i oljen til det faller sammen, før bønnene has i, så får skålen både bitterheten og fargen den ellers mangler. De samme bønnene spises også helt uten pasta, med brød ved siden av.'}},
    {title:{en:'What to drink with it', no:'Hva du skal drikke til'},
     body:{en:'Biferno Rosso, the Montepulciano and Aglianico blend from the river valley below the dam, is the everyday red of the region and the bottle from Molise most likely to sit on a shelf outside it. Serve it at around 16 °C. Tintilia is the better wine and the better match for meat; for a bowl of beans the softer blend is plenty.',
           no:'Biferno Rosso, blandingen av Montepulciano og Aglianico fra elvedalen nedenfor demningen, er regionens hverdagsrødvin og den flasken fra Molise du har størst sjanse til å finne utenfor regionen. Skjenk den ved rundt 16 °C. Tintilia er den bedre vinen og den bedre følgesvennen til kjøtt, men til en skål bønner holder den mykere blandingen.'}},
  ],
},

{
  id:'pampanella', dish:'Pampanella', course:'secondo', lesson:3, serves:4, time:{prep:20, cook:75},
  hero:'peperoni', tags:['pork','paprika','vinegar','oven'],
  title:{en:'Pampanella', no:'Pampanella'},
  blurb:{en:'Pork rubbed with sweet and hot dried red pepper, garlic and vinegar, baked until the outside is brick red and sticky. San Martino in Pensilis sells it by the portion, wrapped in paper.',
         no:'Svinekjøtt gnis inn med søt og sterk tørket paprika, hvitløk og eddik, og bakes til utsiden er teglrød og klebrig. I San Martino in Pensilis selges den i porsjoner, pakket i papir.'},
  heroCaption:{en:'There is no free photograph of pampanella. This is what the rub is made of: sweet red peppers strung up to dry on a house wall.',
               no:'Det finnes ikke noe fritt bilde av pampanella. Dette er råstoffet i krydderet: søte røde paprika hengt til tørk på en husvegg.'},
  wines:['Tintilia del Molise'],
  headnote:{
    en:'<p>Pampanella comes from San Martino in Pensilis, a town on the low hills behind Molise\'s short stretch of coast, and it is the one dish from the region that outsiders remember. Pieces of pork, usually the cheaper cuts and often the ribs, are rubbed with sweet and hot dried red pepper, garlic and vinegar, then baked in a wood oven until the meat is soft and the outside has gone brick red and slightly sticky. It is sold by the portion, wrapped in paper, and eaten with bread and nothing else.</p>'
      + '<p>The name explains the original method. <em>Pampane</em> are vine leaves. The meat was laid on them in the oven, so the leaves took the direct heat of the bricks and gave off steam while the pork cooked. A domestic oven cannot reproduce the falling heat of a bread oven, but it can reproduce the two things that matter: a covered, humid first hour that softens the meat, and a short blast at the end that dries the surface and lacquers it.</p>'
      + '<p>The paprika is the whole seasoning, so it decides the dish. Molise grows its own peppers and dries and grinds them, and the sweet kind there carries more perfume and more heat than the mild Hungarian paprika that fills most Norwegian spice jars. Buy the freshest sweet paprika you can find, use more of it than feels sensible, and make up the missing fire with hot paprika or chilli rather than settling for a pale, dusty rub.</p>',
    no:'<p>Pampanella kommer fra San Martino in Pensilis, en by på de lave åsene bak den korte kyststripen i Molise, og det er den retten fra regionen tilreisende husker best. Biter av svinekjøtt, som regel de billigere stykkene og ofte ribbe, gnis inn med søt og sterk tørket paprika, hvitløk og eddik, og bakes så i vedovn til kjøttet er mørt og utsiden er teglrød og litt klebrig. Den selges i porsjoner, pakket i papir, og spises med brød og ingenting annet.</p>'
      + '<p>Navnet forteller hvordan retten opprinnelig ble laget. <em>Pampane</em> er vinblader. Kjøttet ble lagt på dem i ovnen, slik at bladene tok den direkte varmen fra teglsteinen og ga fra seg damp mens svinet stekte. En vanlig stekeovn kan ikke gjenskape den fallende varmen i en bakerovn, men den kan gjenskape de to tingene som betyr noe: en tildekket og fuktig første time som gjør kjøttet mørt, og en kort omgang på full varme til slutt som tørker overflaten og lakkerer den.</p>'
      + '<p>Paprikaen er hele krydringen, og derfor avgjør den retten. Molise dyrker sine egne paprika og tørker og maler dem selv, og den søte sorten der har mer duft og mer styrke enn den milde ungarske paprikaen som står i de fleste norske krydderhyller. Kjøp den ferskeste søte paprikaen du finner, bruk mer av den enn det virker fornuftig, og hent inn den manglende styrken med sterk paprika eller chili i stedet for å slå deg til ro med en blek og støvete krydderblanding.</p>'},
  ingredients:[
    { group:{en:'The meat', no:'Kjøttet'}, items:[
      {q:1.2, u:'kg', n:{en:'pork on the bone', no:'svinekjøtt med bein'},
       note:{en:'ribs cut into pairs, or shoulder in pieces of about 5 cm, or both. Fat and bone are wanted; a lean loin dries out',
             no:'svineribbe skåret i to og to bein, eller svinebog i biter på rundt 5 cm, eller begge deler. Fett og bein skal være med; en mager svinefilet tørker ut'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'The rub', no:'Krydderblandingen'}, items:[
      {u:'', n:{en:'sweet paprika', no:'søt paprika'},
       note:{en:'ground dried sweet red pepper, as fresh and as red as you can buy. Smoked paprika is a different spice and does not belong here. Reckon on a generous handful for this much meat',
             no:'malt tørket søt paprika, så fersk og så rød som mulig. Røkt paprika er et annet krydder og hører ikke hjemme her. Regn med en romslig neve til denne kjøttmengden'}, scale:'none'},
      {u:'', n:{en:'hot paprika or ground chilli', no:'sterk paprika eller malt chili'},
       note:{en:'to taste. Molisan sweet pepper carries heat of its own, so this is what makes up the difference',
             no:'etter smak. Den søte paprikaen fra Molise har styrke i seg selv, så dette henter inn forskjellen'}, scale:'none'},
      {q:4, u:'', n:{en:'garlic cloves', no:'hvitløksfedd'},
       note:{en:'crushed to a paste with a pinch of salt', no:'knust til en glatt masse med en klype salt'}, round:'half'},
      {q:60, u:'ml', n:{en:'white wine vinegar', no:'hvitvinseddik'}},
      {q:30, u:'ml', n:{en:'extra-virgin olive oil', no:'extra virgin olivenolje'}},
    ]},
    { group:{en:'The dish, and the table', no:'Formen, og bordet'}, items:[
      {q:60, u:'ml', n:{en:'water', no:'vann'}, note:{en:'poured down the side of the dish, not over the meat', no:'helles ned langs kanten av formen, ikke over kjøttet'}},
      {u:'', n:{en:'vine leaves', no:'vinblader'},
       note:{en:'optional, to line the dish. Fig leaves, or nothing at all, also work', no:'valgfritt, til å kle bunnen av formen. Fikenblader, eller ingenting, fungerer også'}, scale:'none'},
      {q:400, u:'g', n:{en:'country bread', no:'grovt landbrød'}, note:{en:'to eat with it', no:'til å spise til'}},
    ]},
  ],
  steps:[
    {en:'Cut the pork into pieces roughly the size of your palm, leaving the bone in wherever there is bone.',
     no:'Skjær svinekjøttet i biter omtrent på størrelse med en håndflate, og la beina sitte igjen der det er bein.'},
    {en:'Crush the garlic with a pinch of salt into a smooth paste.',
     no:'Knus hvitløken med en klype salt til en glatt masse.'},
    {en:'Stir the sweet paprika, the hot paprika, the garlic paste, the vinegar and the oil together into a thick red rub.',
     no:'Rør sammen søt paprika, sterk paprika, hvitløksmassen, eddiken og oljen til en tykk rød krydderblanding.'},
    {en:'Salt the meat, then rub the paste into it with your hands until every piece is coated, working it into the cuts and around the bones.',
     no:'Salt kjøttet, og gni blandingen inn med hendene til hver bit er dekket. Arbeid den inn i snitt og rundt beina.'},
    {en:'Cover the meat and leave it in the fridge for at least four hours, and overnight if you can.',
     no:'Dekk kjøttet til, og sett det kaldt i minst fire timer, gjerne over natten.'},
    {en:'Take it out an hour before cooking so it loses its chill, and heat the oven to 160 °C.',
     no:'Ta det ut en time før steking så det mister kjølen, og varm ovnen til 160 °C.'},
    {en:'Line a deep dish with vine leaves if you have them, lay the meat in one layer and pour the water down the side.',
     no:'Kle bunnen av en dyp form med vinblader hvis du har dem, legg kjøttet i ett lag, og hell vannet ned langs kanten.'},
    {en:'Cover the dish tightly with a lid or foil and bake for an hour, until a fork goes into the meat without resistance.',
     no:'Dekk formen tett med lokk eller folie, og stek i en time, til en gaffel går inn i kjøttet uten motstand.'},
    {en:'Uncover the dish, raise the oven to 220 °C and bake on until the rub darkens, basting once with the juices in the dish.',
     no:'Ta av lokket, skru ovnen opp til 220 °C, og stek videre til krydderet mørkner, mens du én gang øser kraften i formen over kjøttet.'},
    {en:'Watch the last five minutes closely. The surface should turn brick red and tacky, and paprika goes from red to black quickly.',
     no:'Følg nøye med de siste fem minuttene. Overflaten skal bli teglrød og klebrig, og paprika går fort fra rødt til svart.'},
    {en:'Let the meat stand for ten minutes, then serve it in its dish with the juices spooned over.',
     no:'La kjøttet hvile i ti minutter, og server det i formen med kraften øst over.'},
    {en:'Put the bread on the table, and nothing else.',
     no:'Sett brødet på bordet, og ingenting annet.'},
  ],
  notes:[
    {title:{en:'Vinegar, not lemon', no:'Eddik, ikke sitron'},
     body:{en:'The acid has two jobs. It carries the paprika into the meat, because the pigments that make the rub red dissolve in acid and fat rather than in water, and it stops the fat tasting heavy after an hour under a lid. Vinegar also survives the oven: lemon juice cooks down to a flat sweetness, while vinegar stays sharp under the lacquer.',
           no:'Syren har to oppgaver. Den bærer paprikaen inn i kjøttet, for fargestoffene som gjør krydderet rødt, løser seg i syre og fett og ikke i vann, og den hindrer fettet i å smake tungt etter en time under lokk. Eddik tåler dessuten ovnen. Sitronsaft koker inn til en flat sødme, mens eddiken holder seg skarp under lakken.'}},
    {title:{en:'Covered first, open last', no:'Først tildekket, så åpent'},
     body:{en:'An hour under a lid at a low temperature is steaming rather than roasting: the water in the dish keeps the air saturated, the meat stays below 100 °C, and the collagen turns to gelatine without the surface drying out. Only then does the oven go up. Reverse the order and you get a hard red crust over pork that is still tough inside.',
           no:'En time under lokk på lav temperatur er damping og ikke steking. Vannet i formen holder luften mettet, kjøttet holder seg under 100 °C, og kollagenet blir til gelatin uten at overflaten tørker. Først da skal ovnen opp. Gjør du det motsatt, får du en hard rød skorpe over svinekjøtt som fortsatt er seigt inni.'}},
    {title:{en:'Paprika is not a background spice here', no:'Paprika er ikke et bakgrunnskrydder her'},
     body:{en:'Ground pepper loses its aroma within months of milling and keeps only its colour, which is how an old jar produces a dish that looks right and tastes of nothing. Buy a small tin, smell it before you use it — it should smell sweet and faintly of dried fruit — and keep it in the dark. The sweet Hungarian paprika on most Norwegian shelves is milder than the Molisan kind, so add hot paprika or chilli until the rub has an edge to it.',
           no:'Malt paprika mister aromaen i løpet av noen måneder og beholder bare fargen, og derfor gir en gammel krukke en rett som ser riktig ut og ikke smaker noe. Kjøp en liten boks, lukt på den før du bruker den — den skal lukte søtt og svakt av tørket frukt — og oppbevar den mørkt. Den søte ungarske paprikaen i de fleste norske butikker er mildere enn den molisiske, så tilsett sterk paprika eller chili til krydderet har litt bitt.'}},
  ],
  variations:[
    {title:{en:'On the grill', no:'På grillen'},
     body:{en:'Rub ribs the same way, leave them overnight, then cook them slowly over indirect charcoal with the lid down for an hour before finishing them directly over the coals for a few minutes a side. It is further from the bread oven than the oven method, but the wood smoke gives back something an electric oven cannot.',
           no:'Gni inn ribbe på samme måte, la den ligge over natten, og stek den langsomt over indirekte trekull med lokket nede i en time. Avslutt rett over glørne noen minutter på hver side. Det ligger lenger fra bakerovnen enn ovnsmetoden, men vedrøyken gir tilbake noe en elektrisk ovn ikke kan gi.'}},
    {title:{en:'The leaves', no:'Bladene'},
     body:{en:'Vine leaves are the original lining and the reason for the name, but fresh ones are hard to buy in Norway outside late summer. Leaves in brine from a Turkish or Greek shop work if you rinse them well, fig leaves give a coconut-like scent that suits pork, and a bare dish loses nothing but the story.',
           no:'Vinblader er det opprinnelige underlaget og grunnen til navnet, men ferske blader er vanskelige å få kjøpt i Norge utenom sensommeren. Blader på lake fra en tyrkisk eller gresk butikk fungerer hvis du skyller dem godt. Fikenblader gir en duft i retning kokos som kler svinekjøttet, og en form uten blader mister ingenting annet enn historien.'}},
    {title:{en:'What to drink with it', no:'Hva du skal drikke til'},
     body:{en:'The course pairs pampanella with Tintilia del Molise, and the match is acidity against fat and black pepper against paprika. Serve it a little cool. Biferno Rosso does the same job more softly, and a deep-pink Tintilia rosato is the summer answer when the meat comes off a grill.',
           no:'Kurset setter Tintilia del Molise til pampanella, og poenget er syre mot fett og sort pepper mot paprika. Skjenk den litt kjølig. Biferno Rosso gjør den samme jobben mykere, og en dypt rosa Tintilia rosato er sommersvaret når kjøttet kommer fra grillen.'}},
  ],
},

{
  id:'scamorza-alla-griglia', dish:'Scamorza', course:'antipasto', lesson:3, serves:4, time:{prep:5, cook:8},
  hero:'scamorza', tags:['cheese','grill','bread','antipasto'],
  title:{en:'Scamorza alla griglia', no:'Scamorza alla griglia'},
  blurb:{en:'Scamorza on the grill, where it slumps and browns. It is eaten straight off the heat, on bread.',
         no:'Scamorza på grillen, der den siger ut og blir brun. Den spises rett fra varmen, på brød.'},
  heroCaption:{en:'Scamorza, plain and smoked, before it goes near the fire. There is no free photograph of the grilled dish.',
               no:'Scamorza, naturell og røkt, før den kommer i nærheten av ilden. Det finnes ikke noe fritt bilde av den grillede retten.'},
  wines:['Molise Falanghina','Tintilia del Molise'],
  headnote:{
    en:'<p>Molise makes caciocavallo to hang and age, and scamorza from the same stretched curd to eat young. The region\'s reading puts it plainly: scamorza is the one that goes on the grill, where it slumps and browns and is eaten with bread. That is the whole dish. It is less a recipe than a technique, and the technique is worth having, because few cheeses behave this way.</p>'
      + '<p>The curd does the work. <em>Pasta filata</em> means the curd was heated and stretched before it was shaped, which lines the proteins up into long fibres and drives out most of the free water. Heated again over a fire, a cheese like this softens and browns instead of breaking into a puddle of oil and solids the way a young unstretched cheese does. It holds together long enough to be lifted onto bread, and the brown crust comes from the same reaction that browns meat.</p>'
      + '<p>Two things decide whether it works. The cheese must be a whole small scamorza or a thick slab, never thin slices, because a thin slice is liquid before the outside has taken any colour. And the heat must be fierce and short: a couple of minutes a side over hot coals or in a dry ridged pan taken to smoking point, then off, onto bread, and eaten at once. Cold grilled cheese is a different and much worse thing.</p>',
    no:'<p>Molise lager caciocavallo som henges opp til modning, og scamorza av den samme strukne ostemassen til å spises ung. Lesteksten for regionen sier det rett ut: scamorza er den som havner på grillen, der den siger ut og blir brun og spises med brød. Det er hele retten. Dette er snarere en teknikk enn en oppskrift, og teknikken er verdt å kunne, for det er få oster som oppfører seg slik.</p>'
      + '<p>Ostemassen gjør jobben. <em>Pasta filata</em> betyr at massen ble varmet og strukket før den ble formet, og det legger proteinene i lange fibre og presser ut det meste av det frie vannet. Varmes en slik ost opp igjen over ild, mykner den og bruner seg i stedet for å skille seg i en pøl av olje og faste stoffer, slik en ung ost uten strukket masse gjør. Den holder sammen lenge nok til å løftes over på brød, og den brune skorpen kommer av den samme reaksjonen som bruner kjøtt.</p>'
      + '<p>To ting avgjør om det lykkes. Osten må være en hel liten scamorza eller en tykk skive, aldri tynne skiver, for en tynn skive er flytende før utsiden har fått farge. Og varmen må være kraftig og kort: et par minutter på hver side over varme glør eller i en tørr rillepanne varmet til den ryker. Så av varmen, over på brød, og spis den med en gang. Kald grillet ost er noe helt annet og mye verre.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:500, u:'g', n:{en:'scamorza', no:'scamorza'},
     note:{en:'two small whole cheeses, or one cut into slabs a good 2 cm thick. Plain and smoked (affumicata) both work, and half of each is better than either alone',
           no:'to hele små oster, eller én skåret i skiver på gode 2 cm. Både naturell og røkt (affumicata) fungerer, og halvparten av hver er bedre enn bare den ene'}},
    {q:30, u:'ml', n:{en:'extra-virgin olive oil', no:'extra virgin olivenolje'},
     note:{en:'for brushing the cheese, not the grate', no:'til å pensle osten med, ikke risten'}},
    {q:400, u:'g', n:{en:'country bread', no:'grovt landbrød'},
     note:{en:'in thick slices, grilled alongside', no:'i tykke skiver, grillet ved siden av'}},
    {q:1, u:'', n:{en:'garlic clove', no:'hvitløksfedd'},
     note:{en:'halved, to rub over the grilled bread', no:'delt i to, til å gni over det grillede brødet'}, round:'half'},
    {u:'', n:{en:'dried oregano', no:'tørket oregano'},
     note:{en:'a pinch, crumbled between the palms over the hot cheese', no:'en klype, smuldret mellom håndflatene over den varme osten'}, scale:'none'},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
  ]}],
  steps:[
    {en:'Take the cheese out of the fridge an hour ahead, so it is not cold in the middle.',
     no:'Ta osten ut av kjøleskapet en time i forveien, så den ikke er kald i midten.'},
    {en:'Pat the surface dry and brush it lightly with oil.',
     no:'Tørk av overflaten, og pensle den lett med olje.'},
    {en:'Build a hot charcoal fire and let it burn down to glowing coals, or set a ridged cast-iron pan over a high flame until it smokes.',
     no:'Fyr opp et kraftig trekullbål og la det brenne ned til glør, eller sett en rillepanne av støpejern på sterk varme til den ryker.'},
    {en:'Grill the bread first, on both sides, and rub the cut garlic over the hot slices.',
     no:'Grill brødet først, på begge sider, og gni den delte hvitløken over de varme skivene.'},
    {en:'Lay the cheese on the hottest part of the grate and leave it alone until it lifts cleanly, about two minutes.',
     no:'Legg osten på den varmeste delen av risten, og la den ligge i fred til den slipper, omtrent to minutter.'},
    {en:'Turn it once with a thin spatula and grill the second side until it colours and the middle begins to sag.',
     no:'Snu den én gang med en tynn stekespade, og grill den andre siden til den får farge og midten begynner å gi etter.'},
    {en:'Take it off the moment it starts to slump, because a cheese left to collapse loses its fat into the fire.',
     no:'Ta den av i det øyeblikket den begynner å sige ut, for en ost som får kollapse, mister fettet ned i ilden.'},
    {en:'Slide it onto the grilled bread, grind pepper over it and crumble the oregano between your palms above it.',
     no:'Legg den over på det grillede brødet, kvern pepper over, og smuldre oreganoen mellom håndflatene over osten.'},
    {en:'Serve at once, and grill the next piece while this one is being eaten.',
     no:'Server med en gang, og grill neste stykke mens dette blir spist.'},
  ],
  notes:[
    {title:{en:'Why stretched curd browns instead of running', no:'Hvorfor strukket ostemasse bruner seg i stedet for å renne'},
     body:{en:'Stretching aligns the casein into fibres and squeezes out water, so the finished cheese is a dense protein mesh with fat trapped inside it. On the grill the mesh softens without dissolving, and the surface dries enough for browning to begin. A fresh unstretched cheese of the same age has water sitting between its curds, and that water has to boil away before anything can brown — by which time the cheese has already fallen apart.',
           no:'Strekkingen legger kaseinet i fibre og presser ut vann, så den ferdige osten er et tett proteinnett med fett fanget inni. På grillen mykner nettet uten å løse seg opp, og overflaten tørker nok til at bruningen kan begynne. En fersk ost uten strukket masse på samme alder har vann mellom ostekornene, og det vannet må koke bort før noe som helst kan brune seg. Da har osten allerede falt fra hverandre.'}},
    {title:{en:'Smoked or plain', no:'Røkt eller naturell'},
     body:{en:'Smoked scamorza dries a little harder on the outside as it takes the smoke, so it holds its shape a few seconds longer and browns faster. Plain scamorza is milkier and sweeter and slumps sooner. On the same grate the smoked one wants slightly less time, which is a good argument for grilling them in separate batches rather than side by side.',
           no:'Røkt scamorza tørker litt hardere på utsiden mens den tar til seg røyken, og derfor holder den formen noen sekunder lenger og bruner seg fortere. Naturell scamorza er mer melkeaktig og søtere og siger ut tidligere. På samme rist trenger den røkte litt kortere tid, og det er et godt argument for å grille dem i hver sin omgang i stedet for side om side.'}},
    {title:{en:'Bread is not a garnish', no:'Brødet er ikke pynt'},
     body:{en:'Grilled cheese sets hard on a cold plate within a minute. Bread is warm, porous and rough, so it takes up the melted fat that would otherwise pool, and it keeps the cheese soft all the way to the mouth. Grill the bread before the cheese, never after.',
           no:'Grillet ost stivner på et kaldt fat i løpet av et minutt. Brød er varmt, porøst og ru, så det tar opp det smeltede fettet som ellers ville samlet seg i en pøl, og det holder osten myk helt fram til munnen. Grill brødet før osten, aldri etter.'}},
  ],
  variations:[
    {title:{en:'Caciocavallo instead', no:'Caciocavallo i stedet'},
     body:{en:'A young caciocavallo, at three months, is the same curd in a bigger shape and behaves the same way, so cut it into thick slabs. Caciocavallo at a year has dried too far to grill well, because it browns before it softens, and it belongs on the board beside the fire rather than over it.',
           no:'En ung caciocavallo på tre måneder er den samme ostemassen i en større form og oppfører seg likt, så skjær den i tykke skiver. Caciocavallo på et år har tørket for mye til å grilles godt, for den bruner seg før den mykner. Den hører hjemme på fjøla ved siden av ilden, ikke over den.'}},
    {title:{en:'Where scamorza is not sold', no:'Der scamorza ikke selges'},
     body:{en:'Scamorza and caciocavallo reach only the larger Norwegian cities, and mostly the Italian delicatessens in them. Any firm pasta filata cheese does the same thing: provola, the drier mozzarella sold in blocks for pizza, or smoked provolone from an Italian counter. Halloumi survives the same heat but makes a different, saltier dish. Do not try it with fresh mozzarella in brine, which is mostly water.',
           no:'Scamorza og caciocavallo finnes bare i de større norske byene, og stort sett bare i italienske delikatessebutikker der. En hvilken som helst fast ost av strukket masse gjør det samme: provola, den tørrere mozzarellaen som selges i blokk til pizza, eller røkt provolone fra en italiensk disk. Halloumi tåler den samme varmen, men gir en annen og saltere rett. Prøv ikke med fersk mozzarella i lake, som stort sett er vann.'}},
    {title:{en:'What goes on the table with it', no:'Hva som hører til på bordet'},
     body:{en:'In Molise this comes off the grill between courses, with ventricina and bread and a glass of something cold. Molise Falanghina, fresh and lemony, is the white to pour; Tintilia del Molise works too when the cheese is smoked and the sausage is on the board. The order of grilled bread, grilled cheese and cured pork hardly matters.',
           no:'I Molise kommer denne av grillen mellom rettene, med ventricina og brød og et glass av noe kaldt. Molise Falanghina, frisk og sitrusaktig, er hvitvinen å skjenke. Tintilia del Molise fungerer også når osten er røkt og pølsa ligger på fjøla. Rekkefølgen på grillet brød, grillet ost og spekemat betyr ikke stort.'}},
  ],
},

];
