// piemonte recipes. Contract: docs/recipe-format.md. Both languages in one file; never narrated.
// Everything here follows the region's own food reading (content/piemonte.js, lesson 3): tajarin cut by
// hand into 2 mm strands from a dough of up to forty yolks per kilo of flour, agnolotti del plin filled
// with roast veal, pork and rabbit and closed with a pinch of the fingers, bagna cauda as a slow melt of
// garlic and salted anchovy in oil kept warm at the table, vitello tonnato under a sauce of tuna, anchovy,
// capers and egg yolk, and bonet to close the Sunday lunch. Butter, not oil; veal in almost everything.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-21'] = [

{
  id:'tajarin', dish:'Tajarin', course:'primo', lesson:3, serves:4, time:{prep:60, cook:5},
  hero:'tajarin', tags:['pasta','egg','truffle','butter'],
  title:{en:'Tajarin al burro e tartufo', no:'Tajarin al burro e tartufo'},
  blurb:{en:'Hair-thin egg pasta made with four yolks to every hundred grams of flour, dressed with melted butter and, in autumn, white truffle shaved over at the table.',
         no:'Hårtynn eggpasta med fire eggeplommer per hundre gram mel. Den vendes i smeltet smør, og om høsten høvles det hvit trøffel over ved bordet.'},
  heroCaption:{en:'Tajarin: cut by hand into strands about 2 mm wide, and deep gold before they ever meet the butter.',
               no:'Tajarin skjæres for hånd i strimler på omtrent 2 mm, og de er dypt gylne lenge før de møter smøret.'},
  wines:['Barolo',"Barbera d'Asti"],
  headnote:{
    en:'<p>Tajarin are the Piedmontese tagliolini, cut by hand from a thin sheet of egg pasta into strands about 2 mm wide. The yolk count is the whole point. The Langhe go to as many as forty yolks per kilo of flour, which is four to every hundred grams, where Emilia’s sfoglia manages on one whole egg to the same weight. No whites, and no water.</p>'
      + '<p>The fat in the yolks does the work. It makes a stiff, deep yellow dough that has to be kneaded longer than an ordinary pasta dough and rested before it will give, and then rolls out thin enough to see the board through. The pasta is gold long before the butter reaches it, and it cooks in about a minute.</p>'
      + '<p>The dressing is fixed. Melted butter, a little of the cooking water, and between late September and December a few grams of <strong>Tuber magnatum</strong>, the white truffle of Alba, shaved over at the table. The truffle is never cooked: the heat left in the pasta is what lifts the smell out of it. The rest of the year, butter and sage, or the juices of the Sunday roast.</p>',
    no:'<p>Tajarin er Piemontes tagliolini, skåret for hånd fra en tynn leiv eggpasta i strimler på omtrent 2 mm. Eggeplommene er hele poenget. I Langhe går de opp mot førti plommer per kilo mel, altså fire per hundre gram, mens sfogliaen i Emilia klarer seg med ett helt egg til samme mengde. Hvitene er ikke med, og deigen inneholder ikke vann.</p>'
      + '<p>Fettet i plommene gjør jobben. Deigen blir stiv og dypgul, den må eltes lenger enn en vanlig pastadeig og hvile før den gir etter, og da lar den seg kjevle så tynn at bakebordet skinner gjennom. Pastaen er gyllen lenge før smøret kommer, og den koker på omtrent ett minutt.</p>'
      + '<p>Tilbehøret ligger fast. Smeltet smør, litt av kokevannet, og fra slutten av september til desember noen gram <strong>Tuber magnatum</strong>, den hvite trøffelen fra Alba, høvlet over ved bordet. Trøffelen kokes eller stekes aldri, for varmen som sitter igjen i pastaen, er nok til å løse ut duften. Resten av året vender man tajarin i smør og salvie eller i sjyen fra søndagssteken.</p>'},
  ingredients:[
    { group:{en:'The pasta', no:'Pastaen'}, items:[
      {q:300, u:'g', n:{en:'“00” flour', no:'«00»-mel'}, note:{en:'plain wheat flour works; the dough will be a shade less silky', no:'vanlig hvetemel går fint, men deigen blir litt mindre smidig'}},
      {q:12,  u:'', n:{en:'egg yolks', no:'eggeplommer'}, note:{en:'from good eggs — the colour of the pasta comes from nowhere else', no:'fra gode egg, for fargen på pastaen kommer ikke fra noe annet'}, round:'half'},
      {u:'', n:{en:'salt', no:'salt'}, note:{en:'a pinch, in the dough', no:'en klype, i deigen'}, scale:'none'},
    ]},
    { group:{en:'To dress', no:'Til servering'}, items:[
      {q:100, u:'g', n:{en:'butter', no:'smør'}, note:{en:'unsalted, cold from the fridge', no:'usaltet, kaldt fra kjøleskapet'}},
      {q:15,  u:'g', n:{en:'white truffle', no:'hvit trøffel'}, note:{en:'in season only; see the notes if you have one, and the variations if you have not', no:'bare i sesong. Se notatene hvis du har en, og variantene hvis du ikke har noen'}},
      {q:3,   u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:20,  u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
    ]},
  ],
  steps:[
    {en:'Tip the flour onto a board in a mound, hollow out a wide well in the middle and drop the yolks and the salt into it.',
     no:'Hell melet i en haug på bakebordet, lag en vid grop i midten, og ha eggeplommene og saltet ned i den.'},
    {en:'Break the yolks up with a fork and draw in flour from the walls of the well a little at a time, until the middle is too thick to stir.',
     no:'Rør ut plommene med en gaffel, og dra inn litt mel av gangen fra kantene, til midten blir for tykk til å røre i.'},
    {en:'Gather the crumbs into a firm dough and knead it for a good ten minutes, until it is smooth, elastic and evenly yellow. It will feel drier than a dough made with whole eggs; do not add water to it.',
     no:'Samle smulene til en fast deig, og elt den i ti gode minutter, til den er glatt, elastisk og jevnt gul. Den kjennes tørrere enn en deig med hele egg, men ikke tilsett vann.'},
    {en:'Wrap the dough and leave it at room temperature for half an hour, so the gluten relaxes and the sheet will stretch instead of springing back.',
     no:'Pakk inn deigen, og la den ligge en halvtime i romtemperatur, slik at glutenet slapper av og leiven strekker seg i stedet for å trekke seg sammen.'},
    {en:'Roll it out on a lightly floured board into a sheet about 1 mm thick, thin enough to make out the grain of the wood through it.',
     no:'Kjevle den ut på et lett melet bakebord til en leiv på omtrent 1 mm, så tynn at du kan ane treverket gjennom den.'},
    {en:'Dust the sheet generously with flour, let it dry for ten minutes until it feels like soft leather, then roll it up loosely into a flat coil.',
     no:'Strø rikelig med mel over leiven, la den tørke i ti minutter til den kjennes som mykt lær, og rull den så løst sammen til en flat rull.'},
    {en:'Cut across the coil with a long knife into strands about 2 mm wide, then lift them on the back of the knife and shake them out into loose nests.',
     no:'Skjær rullen på tvers med en lang kniv i strimler på omtrent 2 mm, løft dem på knivbladet, og rist dem ut til løse reir.'},
    {en:'Bring the water to a rolling boil and salt it.',
     no:'Kok opp vannet og salt det.'},
    {en:'Melt the butter in a wide pan over low heat with a ladle of the boiling water, swirling the pan until the two turn creamy. Browned butter belongs to another dish.',
     no:'Smelt smøret i en vid panne på svak varme sammen med en øse kokevann, og vipp pannen rundt til det blir kremet. Brunet smør hører til en annen rett.'},
    {en:'Cook the tajarin for about a minute. They rise to the surface almost at once and are done a few seconds later; lift them straight into the butter.',
     no:'Kok tajarinen i omtrent ett minutt. De stiger til overflaten nesten med en gang og er ferdige noen sekunder senere. Løft dem rett over i smøret.'},
    {en:'Toss off the heat until every strand shines, loosening with cooking water if it tightens, then serve on warm plates and shave the truffle over at the table.',
     no:'Vend dem med pannen av platen til hver strimmel skinner, og spe med kokevann hvis det strammer seg. Server på varme tallerkener, og høvl trøffelen over ved bordet.'},
  ],
  notes:[
    {title:{en:'Why only yolks', no:'Hvorfor bare plommer'},
     body:{en:'Egg white is water and protein and sets tough; yolk is fat and lecithin, which shortens the gluten and lets a sheet roll thinner without tearing. That is why a dough this rich behaves stiffly under the hands and tenderly on the plate, and why it needs a longer rest than the whole-egg pasta of Emilia.',
           no:'Eggehvite er vann og protein og stivner seigt, mens plommen er fett og lecitin, som hindrer glutentrådene i å bli lange og seige, slik at leiven blir tynnere uten å revne. Derfor kjennes en så rik deig stiv mellom hendene og likevel mør på tallerkenen, og derfor trenger den lengre hvile enn pastaen med hele egg i Emilia.'}},
    {title:{en:'If you have a truffle', no:'Hvis du har en trøffel'},
     body:{en:'The white truffle is found, never farmed, and it loses aroma from the hour it comes out of the ground. Keep it dry in paper in the coldest part of the fridge, use it within three or four days, brush the earth off rather than washing it, and never let it near a pan. Shave it over hot food at the table with a slicer set fine: the warmth is what releases the smell, and cooking destroys it. The other classic vehicle is a fried egg.',
           no:'Den hvite trøffelen blir funnet, aldri dyrket, og den taper duft fra den timen den kommer opp av jorden. Oppbevar den tørt i papir på den kaldeste plassen i kjøleskapet, bruk den i løpet av tre-fire dager, børst av jorden i stedet for å vaske den, og la den aldri komme i nærheten av en panne. Høvl den over varm mat ved bordet med høvelen stilt fint, for varmen løser ut duften, og koking ødelegger den. Den andre klassiske retten er et speilegg med trøffel høvlet over.'}},
    {title:{en:'Butter with water in it', no:'Smør med vann i'},
     body:{en:'Butter is about a fifth water, and melted alone it splits into oil and milk solids that slide off the pasta. Whisked with a ladle of starchy cooking water it emulsifies instead, and a small amount of butter then coats a large amount of pasta. The same trick dresses any fresh pasta.',
           no:'Smør er omtrent en femtedel vann, og smeltet alene skiller det seg i olje og melketørrstoff som glir av pastaen. Sammen med en øse stivelsesrikt kokevann emulgerer det i stedet, og da dekker lite smør mye pasta. Det samme grepet kler enhver fersk pasta.'}},
  ],
  variations:[
    {title:{en:'Tajarin al ragù', no:'Tajarin al ragù'},
     body:{en:'The everyday version in the Langhe: the same pasta under a meat sauce, or simply under the strained juices of a roast. A young Barbera is the wine for it, and the pasta is cut a shade wider.',
           no:'Hverdagsutgaven i Langhe er den samme pastaen under en kjøttsaus, eller bare under silt sjy fra en stek. En ung Barbera er vinen til den, og pastaen skjæres et hakk bredere.'},
    },
    {title:{en:'Butter and sage', no:'Smør og salvie'},
     body:{en:'Out of truffle season, warm a few sage leaves in the butter until they crisp, and finish with grated Parmigiano or a little aged Castelmagno. Piemonte has more DOP cheeses than any other region and this is where to use one.',
           no:'Utenfor trøffelsesongen kan du varme noen salvieblader i smøret til de blir sprø, og avslutte med revet Parmigiano eller litt lagret Castelmagno. Piemonte har flere DOP-oster enn noen annen region, og her er stedet å bruke en av dem.'},
    },
    {title:{en:'Rolled by machine', no:'Kjevlet med maskin'},
     body:{en:'A pasta machine takes the dough to the second-thinnest setting and its narrow cutter gives an even 2 mm. The strands come out slightly smoother than hand-cut ones and hold a little less butter, which is a fair trade for the half hour saved.',
           no:'En pastamaskin tar deigen til nest tynneste innstilling, og den smaleste kutteren gir jevne 2 mm. Strimlene blir litt glattere enn de håndskårne og holder litt mindre på smøret, og det er en grei pris for den halvtimen du sparer.'},
    },
  ],
},

{
  id:'agnolotti-del-plin', dish:'Agnolotti del plin', course:'primo', lesson:3, serves:6, time:{prep:90, cook:90},
  hero:'agnolotti', tags:['pasta','egg','veal','sunday'],
  title:{en:'Agnolotti del plin', no:'Agnolotti del plin'},
  blurb:{en:'The Langhe’s ravioli: thumbnail parcels of roast veal, pork and rabbit, closed with a pinch of the fingers and served in the juices of the roast.',
         no:'Ravioliene fra Langhe er bittesmå pakker med stekt kalvekjøtt, svin og kanin. De klemmes igjen med et klyp og serveres i sjyen fra steken.'},
  heroCaption:{en:'Agnolotti del plin, pinched shut one by one. The pinch gives them their waist and pushes the air out.',
               no:'Agnolotti del plin klemmes igjen én for én. Klypet gir dem midjen og presser ut luften.'},
  wines:['Barolo','Barbaresco'],
  headnote:{
    en:'<p>Agnolotti are Piemonte’s ravioli, and the ones from the Langhe are the smallest of them: parcels the size of a thumbnail, filled with a mixture of roast meats — usually veal, pork and rabbit — and cabbage, and closed with a <em>plin</em>, which is Piedmontese for a pinch of the fingers. The pinch is the name of the dish.</p>'
      + '<p>The filling began as thrift. A Sunday roast that had already been to the table came back on Monday chopped small, bound with egg and Parmigiano and wrapped in pasta, and the juices left in the roasting pan became the sauce. That is still how they are dressed in the Langhe, or else in butter melted with sage; the oldest way of all is to serve them in a folded napkin with nothing on them at all, so that the filling can be tasted on its own.</p>'
      + '<p>Two things are not negotiable. The meat has to be roasted or braised, never raw mince, because cooked meat is dry and concentrated and raw meat leaks. And the filling has to be cold and firm when it goes into the sheet, or the parcels steam themselves open in the water.</p>',
    no:'<p>Agnolotti er Piemontes ravioli, og de fra Langhe er de minste av dem. Pakkene er på størrelse med en tommelnegl. De fylles med en blanding av stekt kjøtt — som regel kalvekjøtt, svin og kanin — og kål, og klemmes igjen med et <em>plin</em>, som er piemontesisk for et klyp med fingrene. Klypet har gitt retten navn.</p>'
      + '<p>Fyllet oppsto av nøysomhet. En søndagsstek som allerede hadde vært på bordet, kom tilbake på mandag finhakket, bundet med egg og Parmigiano og pakket inn i pasta, og sjyen som lå igjen i stekepannen, ble sausen. Slik serveres de fortsatt i Langhe, eller i smør smeltet med salvie. Den eldste måten er å legge dem i en brettet serviett helt uten noe, slik at fyllet kan smakes for seg.</p>'
      + '<p>To ting ligger fast. Kjøttet må være stekt eller bresert og aldri rå kjøttdeig, for kokt kjøtt er tørt og konsentrert, mens rått kjøtt gir fra seg væske. Og fyllet må være kaldt og fast når det legges på leiven, ellers damper pakkene seg opp i kokevannet.</p>'},
  ingredients:[
    { group:{en:'The filling', no:'Fyllet'}, items:[
      {q:250, u:'g', n:{en:'veal shoulder', no:'kalvebog'}},
      {q:250, u:'g', n:{en:'pork loin or shoulder', no:'svinekam eller svinebog'}},
      {q:200, u:'g', n:{en:'rabbit', no:'kanin'}, note:{en:'off the bone; more veal and pork if you cannot get it', no:'utbeinet. Mer kalvekjøtt og svin hvis du ikke får tak i den'}},
      {q:40,  u:'g', n:{en:'butter', no:'smør'}},
      {q:1,   u:'', n:{en:'sprig of rosemary', no:'kvist rosmarin'}, round:'half'},
      {q:1,   u:'', n:{en:'bay leaf', no:'laurbærblad'}, round:'half'},
      {q:150, u:'ml', n:{en:'dry white wine', no:'tørr hvitvin'}},
      {q:250, u:'g', n:{en:'savoy cabbage', no:'savoykål'}, note:{en:'the leaves only, thick ribs cut out', no:'bare bladene, med de tykke ribbene skåret bort'}},
      {q:60,  u:'g', n:{en:'Parmigiano Reggiano', no:'Parmigiano Reggiano'}, note:{en:'finely grated', no:'finrevet'}},
      {q:2,   u:'', n:{en:'eggs', no:'egg'}, round:'half'},
      {u:'', n:{en:'nutmeg, salt and pepper', no:'muskatnøtt, salt og pepper'}, scale:'none'},
    ]},
    { group:{en:'The dough', no:'Deigen'}, items:[
      {q:350, u:'g', n:{en:'“00” flour', no:'«00»-mel'}},
      {q:3,   u:'', n:{en:'eggs', no:'egg'}, round:'half'},
      {q:2,   u:'', n:{en:'egg yolks', no:'eggeplommer'}, round:'half'},
    ]},
    { group:{en:'To dress', no:'Til servering'}, items:[
      {q:150, u:'ml', n:{en:'roasting juices', no:'stekesjy'}, note:{en:'strained from the pan and skimmed of fat', no:'silt fra pannen og skummet for fett'}},
      {q:50,  u:'g', n:{en:'butter', no:'smør'}, note:{en:'for the sage version', no:'til utgaven med salvie'}},
      {q:8,   u:'', n:{en:'sage leaves', no:'salvieblader'}, round:'half'},
      {q:4,   u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:25,  u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
    ]},
  ],
  steps:[
    {en:'Brown the meats in the butter in a heavy pan with the rosemary and the bay, turning them until every side has colour. Salt and pepper them as they go.',
     no:'Brun kjøttet i smøret i en tykkbunnet gryte sammen med rosmarinen og laurbærbladet, og snu stykkene til alle sider har fått farge. Salt og pepre dem underveis.'},
    {en:'Pour in the wine, let it boil away, then cover the pan and braise over low heat for about an hour, adding a little water whenever the bottom threatens to dry. The meat is ready when it gives to a fork.',
     no:'Hell i vinen, la den koke bort, legg på lokk, og la kjøttet brese på svak varme i omtrent en time. Tilsett litt vann hver gang bunnen holder på å tørke ut. Kjøttet er ferdig når det gir etter for en gaffel.'},
    {en:'Wilt the cabbage leaves in a little of the pan juices until soft, then wring them out in a cloth. A wet filling is the commonest reason these burst.',
     no:'La kålbladene falle sammen i litt av sjyen til de er myke, og vri dem tørre i et klede. Et vått fyll er den vanligste grunnen til at pakkene sprekker.'},
    {en:'Let the meat cool, then chop it and the cabbage very finely. A processor will do it in short pulses, but stop while there is still texture — this is a mince, not a purée.',
     no:'La kjøttet kjølne, og hakk det og kålen svært fint. En foodprosessor klarer det i korte støt, men stopp mens det fortsatt er struktur igjen, for dette skal være en farse og ikke en puré.'},
    {en:'Work the eggs, the Parmigiano and a good grating of nutmeg into the cold filling. It should hold its shape on a spoon; if it slumps, add more cheese. Taste it for salt and chill it.',
     no:'Arbeid eggene, Parmigianoen og godt med revet muskatnøtt inn i det kalde fyllet. Det skal holde formen på en skje, og synker det sammen, tilsetter du mer ost. Smak til med salt, og sett det kaldt.'},
    {en:'Make the dough from the flour, the eggs and the yolks, knead it for ten minutes until smooth, then wrap it and rest it for half an hour.',
     no:'Lag deigen av melet, eggene og plommene, elt den glatt i ti minutter, pakk den inn, og la den hvile en halvtime.'},
    {en:'Roll out a long sheet about 1 mm thick, keeping the rest of the dough covered so it does not dry out.',
     no:'Kjevle ut en lang leiv på omtrent 1 mm, og hold resten av deigen tildekket så den ikke tørker.'},
    {en:'Lay small heaps of filling in a line along the near half of the sheet, a finger apart, and fold the far edge over them.',
     no:'Legg små hauger med fyll på rekke langs den nærmeste halvdelen av leiven, med en fingerbredd mellom, og brett den andre kanten over dem.'},
    {en:'Press the dough down between the heaps to drive the air out, then pinch each parcel at the waist between thumb and forefinger. That pinch is the plin.',
     no:'Trykk deigen ned mellom haugene for å drive ut luften, og klyp så hver pakke sammen i midjen mellom tommel og pekefinger. Det klypet er selve plinet.'},
    {en:'Cut between the pinches with a fluted wheel and lay the parcels on a floured cloth, not touching each other.',
     no:'Skjær mellom klypene med et riflet deighjul, og legg pakkene på et melet klede uten at de rører hverandre.'},
    {en:'Cook them in gently simmering salted water for two to three minutes, lift them out with a slotted spoon, and turn them in the warmed roasting juices, or in butter melted with the sage.',
     no:'Kok dem i så vidt sydende saltet vann i to til tre minutter, løft dem opp med hullsleiv, og vend dem i den oppvarmede stekesjyen eller i smør smeltet med salvien.'},
  ],
  notes:[
    {title:{en:'What the pinch does', no:'Hva klypet gjør'},
     body:{en:'Pinching seals two layers of pasta against each other while squeezing the air out from between them, and trapped air is what makes a filled pasta float early and split. It also leaves a narrow waist and a ruffled edge, and those catch the thin juices that dress the dish where a smooth ravioli would let them run off.',
           no:'Klypet forsegler to lag pasta mot hverandre og presser samtidig ut luften mellom dem, og innestengt luft er grunnen til at fylt pasta flyter opp for tidlig og sprekker. Det gir dessuten en smal midje og en rufsete kant, og de fanger opp den tynne sjyen som en glatt ravioli ville latt renne av.'}},
    {title:{en:'Boil gently', no:'Kok forsiktig'},
     body:{en:'A rolling boil batters filled pasta and tears the seams open; a bare simmer cooks it just as fast. The same goes for lifting them out — a slotted spoon rather than a colander, or half of them will be empty by the time they reach the plate.',
           no:'Full fosskoking slår fylt pasta i stykker og river sømmene opp, mens så vidt sydende vann koker den like fort. Det samme gjelder når de skal opp: bruk hullsleiv og ikke dørslag, ellers er halvparten tomme før de når tallerkenen.'}},
    {title:{en:'The juices are the sauce', no:'Sjyen er sausen'},
     body:{en:'There is no separate sauce to make here, and none is wanted. What is left in the roasting pan is meat juice, wine and melted butter, already seasoned by an hour of braising; strained and skimmed it coats the parcels in a thin gloss and repeats the flavour of the filling instead of covering it.',
           no:'Her lages ingen egen saus, og det trengs heller ingen. I gryten ligger det igjen kjøttsaft, vin og smeltet smør, som en time med bresering allerede har smaksatt. Når sjyen er silt og skummet, legger den seg som en tynn glans rundt pakkene og gjentar smaken i fyllet i stedet for å dekke over den.'}},
  ],
  variations:[
    {title:{en:'Al tovagliolo', no:'Al tovagliolo'},
     body:{en:'The old way: drained, tipped straight into a folded napkin and eaten with the fingers, dressed with nothing whatever. It is a test of the filling and a habit of the Langhe wine cellars, where a glass of Barbera is the only accompaniment.',
           no:'På gamlemåten heller du av vannet, tømmer dem rett i en brettet serviett og spiser dem med fingrene helt uten noe til. Det er en prøve på fyllet og en vane fra vinkjellerne i Langhe, der et glass Barbera er det eneste følget.'}},
    {title:{en:'Butter and sage', no:'Smør og salvie'},
     body:{en:'If there is no roast, melt butter with sage leaves until it smells nutty, slacken it with a ladle of the cooking water and turn the agnolotti in that. Grated Parmigiano at the table, and no more.',
           no:'Har du ingen stek, smelter du smør med salvieblader til det dufter nøtteaktig, sper med en øse kokevann og vender agnolottiene i det. Revet Parmigiano ved bordet, og ikke mer.'}},
    {title:{en:'A larger agnolotto', no:'En større agnolotto'},
     body:{en:'Away from the Langhe the parcels get bigger and squarer, cut with a wheel rather than pinched, and the filling often takes rice or roasted vegetables alongside the meat. The plin is the small, pinched member of the family.',
           no:'Utenfor Langhe blir pakkene større og mer firkantede, skåret med hjul i stedet for klemt igjen, og fyllet får ofte ris eller ovnsbakte grønnsaker ved siden av kjøttet. Plinet er det lille, sammenklemte medlemmet av familien.'}},
  ],
},

{
  id:'bagna-cauda', dish:'Bagna cauda', course:'antipasto', lesson:3, serves:4, time:{prep:25, cook:60},
  hero:'bagnacauda', tags:['anchovy','garlic','winter','shared'],
  title:{en:'Bagna cauda', no:'Bagna cauda'},
  blurb:{en:'The “hot bath”: garlic and salted anchovy melted into olive oil, kept warm over a flame in the middle of the table with raw winter vegetables round it.',
         no:'Det «varme badet» av hvitløk og saltet ansjos som smelter ut i olivenolje. Gryten holdes varm over en flamme midt på bordet, med rå vintergrønnsaker rundt.'},
  heroCaption:{en:'Bagna cauda in its terracotta pot. Everyone dips, and the evening lasts until the pot is empty.',
               no:'Bagna cauda i leirgryten. Alle dypper, og kvelden varer til gryten er tom.'},
  wines:["Barbera d'Asti"],
  headnote:{
    en:'<p>Bagna cauda is Piedmontese for hot bath, and it is the most sociable thing the region cooks. A pot of garlic, salted anchovy and olive oil stands over a candle in the middle of the table, raw winter vegetables go round it, and everybody dips. In the villages there are still bagna cauda nights that run until the pot is empty.</p>'
      + '<p>It came out of the poorest kitchens. Anchovies were the cheap preserved fish that came over the mountains from Liguria, salt-packed in barrels, and the sauce was the way to turn a table of winter vegetables into a feast. Cardoons are the vegetable that matters — the pale, blanched stalks of the Monferrato — but peppers, celery, cabbage leaves and Jerusalem artichokes all belong.</p>'
      + '<p>Nothing in the pot is fried. The garlic is softened until it melts, the anchovy is stirred until it dissolves, and the oil stays warm rather than hot. The quantities are what people argue about: a recipe deposited in 1995 by the Cavalieri del Tartufo e dei Vini d’Alba at Costigliole d’Asti allows a whole head of garlic and fifty grams of anchovy for each person, and Piedmontese cooks have been disagreeing with it ever since. What follows is the gentler version, with the garlic simmered in milk first, which is what most families make.</p>',
    no:'<p>Bagna cauda er piemontesisk for varmt bad, og ingen rett i regionen er mer selskapelig. En gryte med hvitløk, saltet ansjos og olivenolje står over et lys midt på bordet, rå vintergrønnsaker står rundt, og alle dypper. I landsbyene holdes det fortsatt bagna cauda-kvelder som varer til gryten er tom.</p>'
      + '<p>Retten kommer fra de fattigste kjøkkenene. Ansjos var den billige, konserverte fisken som kom over fjellene fra Liguria, saltet ned i tønner, og sausen gjorde et bord med vintergrønnsaker til et festmåltid. Av grønnsakene betyr kardonene mest, de bleke stilkene fra Monferrato som dekkes til mens de vokser, men paprika, selleri, kålblader og jordskokk hører også hjemme.</p>'
      + '<p>Ingenting i gryten skal stekes. Hvitløken mykner til den smelter, ansjosen røres til den er borte, og oljen holder seg varm og ikke het. Mengdene er det man krangler om. En oppskrift som Cavalieri del Tartufo e dei Vini d’Alba skrev ned i Costigliole d’Asti i 1995, regner et helt hvitløkshode og femti gram ansjos på hver person, og piemontesiske kokker har vært uenige med den helt siden. Under står den mildere utgaven, der hvitløken først trekker i melk, og den er det de fleste familier lager.</p>'},
  ingredients:[
    { group:{en:'The bagna cauda', no:'Bagna cauda'}, items:[
      {q:12,  u:'', n:{en:'garlic cloves', no:'hvitløksfedd'}, note:{en:'peeled, halved, the green germ flicked out', no:'skrelt, delt på langs, og med den grønne spiren fjernet'}, round:'half'},
      {q:300, u:'ml', n:{en:'milk', no:'melk'}, note:{en:'for softening the garlic; it is thrown away afterwards', no:'til å mykne hvitløken. Den helles av etterpå'}},
      {q:150, u:'g', n:{en:'salted anchovies', no:'saltet ansjos'}, note:{en:'Italian salt-packed ones, rinsed and boned, or good fillets in oil', no:'italiensk ansjos (sardell) i salt, skylt og renset, eller gode fileter i olje. Ikke norsk krydret ansjos'}},
      {q:250, u:'ml', n:{en:'extra virgin olive oil', no:'ekstra virgin olivenolje'}, note:{en:'a mild one; a peppery oil fights the anchovy', no:'en mild en, for en pepret olje kjemper mot ansjosen'}},
      {q:30,  u:'g', n:{en:'butter', no:'smør'}, note:{en:'optional, stirred in at the end', no:'valgfritt, røres inn til slutt'}},
    ]},
    { group:{en:'To dip', no:'Til dypping'}, items:[
      {q:500, u:'g', n:{en:'cardoons', no:'kardoner'}, note:{en:'strings pulled off, cut into batons, held in water with lemon; celery hearts if there are none', no:'trekk av trådene, skjær dem i staver, og legg dem i vann med sitron. Sellerihjerter hvis du ikke får tak i kardoner'}},
      {q:2,   u:'', n:{en:'sweet peppers', no:'paprika'}, round:'half'},
      {q:200, u:'g', n:{en:'Jerusalem artichokes', no:'jordskokk'}},
      {q:200, u:'g', n:{en:'savoy cabbage leaves', no:'savoykålblader'}},
      {q:4,   u:'', n:{en:'eggs', no:'egg'}, note:{en:'for the end of the evening', no:'til slutten av kvelden'}, round:'half'},
    ]},
  ],
  steps:[
    {en:'Peel the garlic, split each clove down the middle and lift out the green germ. The germ is what turns bitter and repeats on you.',
     no:'Skrell hvitløken, del hvert fedd på langs, og løft ut den grønne spiren. Spiren blir bitter og gjentar seg utover kvelden.'},
    {en:'Simmer the garlic in the milk over the lowest heat you have for twenty to thirty minutes, until a clove crushes to a purée against the side of the pan. Pour the milk away.',
     no:'La hvitløken småkoke i melken på svakest mulig varme i tjue til tretti minutter, til et fedd lar seg mose mot kanten av kjelen. Hell av melken.'},
    {en:'Rinse the salt off the anchovies under cold water, open them along the backbone, pull the bone out and pat the fillets dry.',
     no:'Skyll saltet av ansjosen i kaldt vann, brett den opp langs ryggbeinet, dra ut beinet, og tørk filetene.'},
    {en:'Warm the oil in an earthenware pot or a heavy pan until it is hand-warm. It must never reach frying temperature at any point tonight.',
     no:'Varm oljen i en leirgryte eller en tykkbunnet kjele til den er håndvarm. Den skal aldri komme opp i stekevarme i løpet av kvelden.'},
    {en:'Add the drained garlic and crush it into the oil with the back of a wooden spoon until it disappears.',
     no:'Ha i hvitløken og mos den ut i oljen med baksiden av en tresleiv til den forsvinner.'},
    {en:'Add the anchovies and stir over the lowest heat for twenty to thirty minutes, until no fillet is left whole and the sauce is an even brown. An occasional lazy bubble is all the movement you want.',
     no:'Ha i ansjosen, og rør på svakest mulig varme i tjue til tretti minutter, til ingen filet er hel og sausen er jevnt brun. En og annen doven boble er all bevegelsen du skal ha.'},
    {en:'Taste it. If it looks oily or bites too hard, stir in the butter with the pot off the heat and it will pull together.',
     no:'Smak på den. Ser den oljete ut eller biter for hardt, rører du inn smøret med gryten av platen, og da samler den seg.'},
    {en:'Prepare the vegetables while the sauce cooks: cardoons into batons in lemon water, peppers into wide strips, artichokes into slices, cabbage into leaves that can be held in the fingers.',
     no:'Gjør i stand grønnsakene mens sausen står: kardoner i staver i sitronvann, paprika i brede strimler, jordskokk i skiver, og kålen i blader som kan holdes mellom fingrene.'},
    {en:'Set the pot over a candle or a small burner in the middle of the table, with the vegetables round it and bread within reach.',
     no:'Sett gryten over et telys eller en liten brenner midt på bordet, med grønnsakene rundt og brød innen rekkevidde.'},
    {en:'When the vegetables are gone, break the eggs into what is left in the pot and scramble them over the flame. That is how the evening ends in the Langhe.',
     no:'Når grønnsakene er borte, slår du eggene ut i det som er igjen i gryten, og rører dem sammen over flammen. Slik ender kvelden i Langhe.'},
  ],
  notes:[
    {title:{en:'Why the milk', no:'Hvorfor melken'},
     body:{en:'The harsh, hot compounds in garlic form when a raw clove is cut and are carried off by a long, slow simmer; the milk both dilutes them and stops the cloves colouring, which would bring bitterness of another kind. Garlic treated this way tastes sweet, so a dozen cloves are gentler than four raw ones. Skip the step and you must halve the garlic.',
           no:'De skarpe, hete stoffene i hvitløk dannes når et rått fedd skjæres, og de trekker ut under lang, langsom koking. Melken tynner dem og hindrer samtidig at feddene tar farge, noe som ville gitt en annen slags bitterhet. Hvitløk som er behandlet slik, smaker søtt, og et dusin fedd blir mildere enn fire rå. Dropper du trinnet, må du halvere hvitløken.'}},
    {title:{en:'Warm, never hot', no:'Varm, aldri het'},
     body:{en:'Anchovy dissolves because its flesh has already been broken down by months in salt; gentle warmth finishes the job and the fillets melt into the oil. Real heat does the opposite — the proteins seize, the sauce separates and the whole pot starts tasting of frying instead of the sea. The candle under the pot is not decoration; it is the correct temperature.',
           no:'Ansjos løser seg opp fordi kjøttet allerede er brutt ned av måneder i salt. Mild varme fullfører arbeidet, og filetene smelter inn i oljen. Ordentlig varme gjør det motsatte: proteinene trekker seg sammen, sausen skiller seg, og hele gryten begynner å smake av steking i stedet for av hav. Lyset under gryten er ingen pynt, men den riktige temperaturen.'}},
  ],
  variations:[
    {title:{en:'The full-strength version', no:'Utgaven i full styrke'},
     body:{en:'Leave the milk out, use half again as much garlic and let it soften straight in the oil over an hour. This is the one the confraternity wrote down, and the one that decides what you can do the following day.',
           no:'Sløyf melken, bruk halvparten mer hvitløk, og la den mykne rett i oljen i en times tid. Dette er utgaven broderskapet skrev ned, og den som avgjør hva du kan finne på dagen etter.'}},
    {title:{en:'Softened with cream or butter', no:'Mildnet med fløte eller smør'},
     body:{en:'Some households finish the pot with a little cream or a good knob of butter, which rounds the salt and keeps the sauce from splitting as it stands. Purists call it a compromise; it is also what makes a second helping possible.',
           no:'Noen husholdninger avslutter gryten med litt fløte eller en god klatt smør, som runder av saltet og hindrer at sausen skiller seg mens den står. Purister kaller det et kompromiss, men det er også det som gjør en porsjon nummer to mulig.'}},
    {title:{en:'What else goes round the pot', no:'Hva mer som står rundt gryten'},
     body:{en:'Raw is the tradition, but roasted peppers, boiled potatoes, onions baked whole in their skins and grilled polenta all take the sauce well and make the meal easier on those who find the raw version heavy.',
           no:'Rått er tradisjonen, men ovnsbakt paprika, kokte poteter, hel løk bakt med skallet på og grillet polenta tar sausen godt og gjør måltidet lettere for dem som synes den rå utgaven blir tung.'}},
  ],
},

{
  id:'vitello-tonnato', dish:'Vitello tonnato', course:'antipasto', lesson:3, serves:6, time:{prep:30, cook:70},
  hero:'vitello', tags:['veal','tuna','cold','antipasto'],
  title:{en:'Vitello tonnato', no:'Vitello tonnato'},
  blurb:{en:'Cold veal sliced thin under a sauce of tuna, anchovy, capers and hard-boiled yolk — the older version, with no mayonnaise in it.',
         no:'Tynne skiver kaldt kalvekjøtt under en saus av tunfisk, ansjos, kapers og hardkokt eggeplomme, i den eldre utgaven uten majones.'},
  heroCaption:{en:'Vitello tonnato, the plate that opens a Sunday lunch in the Langhe.',
               no:'Vitello tonnato, tallerkenen som åpner en søndagslunsj i Langhe.'},
  wines:['Gavi'],
  headnote:{
    en:'<p>Vitello tonnato opens the Sunday lunch in the Langhe: cold veal sliced as thin as the kitchen can manage, laid flat on a cold plate and covered with a sauce of tuna, anchovy, capers and egg yolk. It reads oddly and it tastes wonderful. The tuna is the surprising part, a landlocked region reaching for a preserved sea fish exactly as it does for the anchovies in bagna cauda.</p>'
      + '<p>The argument is about the sauce. The older kind has no mayonnaise at all: tuna, anchovy, capers and hard-boiled yolks worked to a paste, let down with oil, lemon and a little of the poaching broth. Pellegrino Artusi printed a version of that sort in 1891. The modern kind folds the tuna into a mayonnaise, which is paler, smoother and much harder to get wrong. The recipe below is the older one, and the first variation is the other.</p>'
      + '<p>Whichever sauce you choose, two things decide the plate and neither is the sauce. The veal has to cool right down in its own poaching liquid, and it has to be sliced cold. Lift the meat out hot and it dries as it cools, then crumbles under the knife.</p>',
    no:'<p>Vitello tonnato åpner søndagslunsjen i Langhe. Kaldt kalvekjøtt skjæres så tynt kjøkkenet klarer, legges flatt på en kald tallerken og dekkes med en saus av tunfisk, ansjos, kapers og eggeplomme. Det høres rart ut og smaker fantastisk. Tunfisken er det overraskende, for en region uten kyst griper etter konservert havfisk på nøyaktig samme måte som den gjør med ansjosen i bagna cauda.</p>'
      + '<p>Uenigheten gjelder sausen. Den eldre typen har ikke majones i det hele tatt. Tunfisk, ansjos, kapers og hardkokte eggeplommer arbeides til en masse og spes med olje, sitron og litt av kraften kjøttet er posjert i. Pellegrino Artusi trykte en slik utgave i 1891. Den moderne typen rører tunfisken inn i en majones, og den blir lysere, glattere og langt lettere å lykkes med. Oppskriften under er den eldre, og den første varianten er den andre.</p>'
      + '<p>Uansett hvilken saus du velger, avgjøres tallerkenen av to andre ting. Kalvekjøttet må kjølne helt ned i sin egen kraft, og det må skjæres kaldt. Løfter du kjøttet ut mens det er varmt, tørker det når det kjølner, og siden smuldrer det under kniven.</p>'},
  ingredients:[
    { group:{en:'The veal', no:'Kalvekjøttet'}, items:[
      {q:800, u:'g', n:{en:'veal from the round', no:'kalvekjøtt fra ytterlåret'}, note:{en:'girello, in one even piece, tied with string', no:'girello, i ett jevnt stykke, bundet opp med hyssing'}},
      {q:1,   u:'', n:{en:'carrot', no:'gulrot'}, round:'half'},
      {q:1,   u:'', n:{en:'onion', no:'løk'}, round:'half'},
      {q:1,   u:'', n:{en:'celery stick', no:'selleristang'}, round:'half'},
      {q:2,   u:'', n:{en:'bay leaves', no:'laurbærblader'}, round:'half'},
      {q:300, u:'ml', n:{en:'dry white wine', no:'tørr hvitvin'}, note:{en:'a Gavi or an Arneis, and drink the rest of it with the dish', no:'en Gavi eller en Arneis, og drikk resten til retten'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'The sauce', no:'Sausen'}, items:[
      {q:200, u:'g', n:{en:'tuna in olive oil', no:'tunfisk i olivenolje'}, note:{en:'drained; the oil it came in can go into the sauce', no:'avrent. Oljen den lå i kan gå i sausen'}},
      {q:4,   u:'', n:{en:'anchovy fillets', no:'ansjosfileter'}, note:{en:'Italian salt- or oil-packed, not Norwegian spiced sprat', no:'italienske, i salt eller olje, ikke norsk krydret ansjos'}, round:'half'},
      {q:3,   u:'', n:{en:'hard-boiled egg yolks', no:'hardkokte eggeplommer'}, round:'half'},
      {q:30,  u:'g', n:{en:'capers', no:'kapers'}, note:{en:'salted, rinsed; keep a few back for the top', no:'i salt, skylt. Spar noen til pynt'}},
      {q:150, u:'ml', n:{en:'mild olive oil', no:'mild olivenolje'}},
      {q:30,  u:'ml', n:{en:'lemon juice', no:'sitronsaft'}},
      {q:100, u:'ml', n:{en:'poaching broth', no:'kokekraft'}, note:{en:'strained and cooled, to loosen the sauce', no:'silt og avkjølt, til å spe sausen med'}},
    ]},
  ],
  steps:[
    {en:'Tie the veal into an even cylinder with kitchen string, so it cooks through at the same rate and holds together under the knife.',
     no:'Bind kalvekjøttet opp til en jevn rull med hyssing, slik at det blir ferdig samtidig hele veien og holder seg samlet under kniven.'},
    {en:'Put it in a pan just wide enough to hold it, with the carrot, onion, celery and bay, pour over the wine and add cold water until the meat is covered.',
     no:'Legg det i en kjele som så vidt rommer det, sammen med gulroten, løken, sellerien og laurbærbladene. Hell over vinen, og fyll på med kaldt vann til kjøttet er dekket.'},
    {en:'Bring it slowly to the point where the surface only shivers, and hold it there for about an hour. Never let it boil; a boil squeezes the juice out of lean veal.',
     no:'Varm det langsomt opp til overflaten så vidt skjelver, og hold det der i omtrent en time. La det aldri fosskoke, for fosskoking presser saften ut av magert kalvekjøtt.'},
    {en:'Salt the liquid towards the end, take the pan off the heat and leave the meat to cool completely in its own broth. This is the step that keeps it moist, and it takes hours.',
     no:'Salt kraften mot slutten, ta kjelen av platen, og la kjøttet kjølne helt i sin egen kraft. Dette trinnet holder kjøttet saftig, og det tar timer.'},
    {en:'Boil the eggs hard, cool them under the tap and keep the yolks; the whites are not wanted here.',
     no:'Kok eggene harde, avkjøl dem under springen, og ta vare på plommene. Hvitene skal ikke brukes her.'},
    {en:'Work the tuna, the anchovy fillets, the capers and the yolks to a smooth paste in a mortar or a blender.',
     no:'Arbeid tunfisken, ansjosfiletene, kapersen og plommene til en jevn masse i morter eller stavmikser.'},
    {en:'Trickle in the oil in a thin stream while the machine runs or the pestle turns, until the sauce is thick and glossy like whipped cream.',
     no:'Hell i oljen i en tynn stråle mens maskinen går eller støteren arbeider, til sausen er tykk og blank som pisket krem.'},
    {en:'Sharpen it with the lemon juice, then let it down with the strained cold broth until it just falls from a spoon. Taste for salt; the anchovy and the capers have usually done the job.',
     no:'Skjerp den med sitronsaften, og spe med den silte, kalde kraften til den så vidt faller av en skje. Smak til med salt, men ansjosen og kapersen har som regel gjort jobben.'},
    {en:'Chill the sauce and the meat separately for at least two hours, or overnight, which is better.',
     no:'Sett sausen og kjøttet kaldt hver for seg i minst to timer, eller til dagen etter, som er bedre.'},
    {en:'Slice the cold veal as thinly as you possibly can, across the grain, and lay the slices overlapping on a cold dish.',
     no:'Skjær det kalde kalvekjøttet så tynt du overhodet klarer, på tvers av fibrene, og legg skivene overlappende på et kaldt fat.'},
    {en:'Spread the sauce over the meat in a thin, even layer, scatter the capers on top, and take the dish out of the fridge a quarter of an hour before it goes on the table.',
     no:'Bre sausen jevnt og tynt utover kjøttet, dryss kapersen over, og ta fatet ut av kjøleskapet et kvarter før det skal på bordet.'},
  ],
  notes:[
    {title:{en:'Cool it in its broth', no:'La det kjølne i kraften'},
     body:{en:'Muscle fibres tighten in the heat and squeeze out liquid, and as they cool they relax and draw some of it back in — but only if the liquid is still there. Meat lifted out hot loses that water to the air instead, which is why so much home-poached veal ends up grey and dry. The broth is also the thing that thins the sauce, so nothing is wasted.',
           no:'Muskelfibrene trekker seg sammen i varmen og presser ut væske, og når de kjølner, slapper de av og trekker noe av den tilbake, men bare hvis væsken fortsatt er der. Kjøtt som løftes ut varmt, gir i stedet vannet til luften, og derfor blir så mye hjemmeposjert kalvekjøtt grått og tørt. Kraften tynner dessuten sausen, så ingenting går til spille.'}},
    {title:{en:'What holds the sauce together', no:'Hva som holder sausen sammen'},
     body:{en:'Cooked yolk is full of lecithin and the tuna carries its own oil, so the two together will take up a good deal of olive oil in a stable suspension without a raw egg anywhere. It is coarser than mayonnaise and tastes more of fish, which is the point of the older version.',
           no:'Kokt eggeplomme er full av lecitin, og tunfisken har med seg sin egen olje, så de to sammen tar opp mye olivenolje i en stabil blanding uten et eneste rått egg. Den blir grovere enn majones og smaker mer av fisk, og nettopp det er poenget med den eldre utgaven.'}},
    {title:{en:'Cool, not cold', no:'Kjølig, ikke kaldt'},
     body:{en:'Straight from the fridge the veal is dulled and the sauce tastes only of salt, because aroma sits in fat and fat gives up almost nothing below about ten degrees. A quarter of an hour on the counter is enough to bring the tuna and the capers back.',
           no:'Rett fra kjøleskapet er kalvekjøttet sløvt og sausen smaker bare av salt, for aromaen sitter i fettet, og fett gir nesten ingenting fra seg under ti grader. Et kvarter på benken er nok til å hente tunfisken og kapersen tilbake.'}},
  ],
  variations:[
    {title:{en:'The modern sauce', no:'Den moderne sausen'},
     body:{en:'Make a mayonnaise with a raw yolk and oil, then beat in the tuna, the anchovy and the capers pounded fine, and let it down with lemon and broth. Paler, sweeter, smoother, and the version most restaurants serve today.',
           no:'Lag en majones av en rå plomme og olje, og pisk så inn tunfisken, ansjosen og finstøtt kapers, og spe med sitron og kraft. Den blir lysere, søtere og glattere, og det er utgaven de fleste restauranter serverer i dag.'}},
    {title:{en:'Roast instead of poached', no:'Stekt i stedet for posjert'},
     body:{en:'Brown the tied piece in butter, then roast it gently until the middle reads 58 °C and let it cool wrapped. The meat is firmer and tastes more of itself, but you have no broth, so thin the sauce with the pan juices and a little water.',
           no:'Brun det oppbundne stykket i smør, stek det så forsiktig ferdig til kjernen viser 58 °C, og la det kjølne innpakket. Kjøttet blir fastere og smaker mer av seg selv, men da har du ingen kraft, så spe sausen med stekesjyen og litt vann.'}},
    {title:{en:'Turkey and other economies', no:'Kalkun og andre innsparinger'},
     body:{en:'Piedmontese households cook the same plate with a poached turkey breast when veal is dear, and the leftovers of a roast do perfectly well too. Slice whatever it is cold and thin, and the sauce carries the rest.',
           no:'Piemontesiske husholdninger lager den samme tallerkenen med posjert kalkunbryst når kalvekjøttet er dyrt, og restene av en stek gjør også nytten. Skjær det du har kaldt og tynt, og sausen bærer resten.'}},
  ],
},

{
  id:'bonet', dish:'Bonet', course:'dolce', lesson:3, serves:6, time:{prep:25, cook:60},
  hero:'bonet', tags:['chocolate','amaretti','custard','make-ahead'],
  title:{en:'Bonet', no:'Bonet'},
  blurb:{en:'The pudding that closes a Langhe Sunday: a baked custard of milk, eggs, cocoa and crushed amaretti, turned out of a caramel-lined mould.',
         no:'Desserten som avslutter en søndag i Langhe, er en ovnsbakt pudding av melk, egg, kakao og knuste amaretti, og den hvelves ut av en form med karamell i bunnen.'},
  heroCaption:{en:'Bonet turned out of its mould, the caramel running down it, with an amaretto biscuit alongside.',
               no:'Bonet hvelves ut av formen, og karamellen renner nedover sidene. Ved siden av ligger en amarettokjeks.'},
  wines:["Moscato d'Asti"],
  headnote:{
    en:'<p>Bonet comes last in the Langhe Sunday lunch, after the agnolotti, the roast and the cheese. It is a baked custard of milk, eggs, sugar, cocoa and crushed amaretti, set in a mould lined with caramel and turned out cold. The name is the Piedmontese word for a hat, and also for the round copper mould shaped like one; which of the two the pudding is named after depends on who is telling you.</p>'
      + '<p>The mechanism is the same as any baked custard. Egg protein sets between roughly 80 and 85 °C, and above that it squeezes out water and the pudding goes grainy and weeps. The water bath is the whole defence: water cannot pass 100 °C, so the mixture creeps up to setting point and stops there instead of racing past it at the edges of the dish.</p>'
      + '<p>The amaretti are not negotiable. They bring the bitter-almond note and the faint grain that separates a bonet from a crème caramel, which is otherwise its close relation. Rum is the usual spirit, Fernet and Marsala are both common, and the pudding has to be made the day before, because it will not leave the mould until it is properly cold.</p>',
    no:'<p>Bonet kommer sist i søndagslunsjen i Langhe, etter agnolottiene, steken og osten. Den er en ovnsbakt pudding av melk, egg, sukker, kakao og knuste amaretti, stivnet i en form med karamell i bunnen og hvelvet ut kald. Navnet er det piemontesiske ordet for en hatt, og også for den runde kobberformen som er formet som en. Hvem av de to desserten har navnet fra, kommer an på hvem som forteller.</p>'
      + '<p>Framgangsmåten er den samme som for enhver ovnsbakt eggekrem. Eggeprotein stivner mellom omtrent 80 og 85 °C, og over det presser det ut vann, slik at puddingen blir kornete og skiller seg. Vannbadet er hele forsvaret, for vann kommer ikke over 100 °C, og da kryper røren opp til stivnepunktet og stanser der i stedet for å fare forbi det langs kanten av formen.</p>'
      + '<p>Amarettiene ligger fast. De gir tonen av bitre mandler og den svake kornetheten som skiller en bonet fra en crème caramel, som den ellers er nær i slekt med. Rom er det vanlige valget, mens Fernet og Marsala begge er utbredt, og desserten må lages dagen før, for den slipper ikke formen før den er ordentlig kald.</p>'},
  ingredients:[
    { group:{en:'The caramel', no:'Karamellen'}, items:[
      {q:100, u:'g', n:{en:'sugar', no:'sukker'}},
      {q:30,  u:'ml', n:{en:'water', no:'vann'}},
    ]},
    { group:{en:'The custard', no:'Røren'}, items:[
      {q:500, u:'ml', n:{en:'whole milk', no:'helmelk'}},
      {q:4,   u:'', n:{en:'eggs', no:'egg'}, round:'half'},
      {q:100, u:'g', n:{en:'sugar', no:'sukker'}},
      {q:25,  u:'g', n:{en:'cocoa powder', no:'kakaopulver'}, note:{en:'unsweetened, sifted', no:'usøtet, siktet'}},
      {q:120, u:'g', n:{en:'amaretti', no:'amaretti'}, note:{en:'the hard, dry kind; keep a few whole for serving', no:'den harde, tørre typen. Spar noen hele til serveringen'}},
      {q:30,  u:'ml', n:{en:'dark rum', no:'mørk rom'}, note:{en:'Fernet or Marsala instead, if you prefer', no:'Fernet eller Marsala i stedet, hvis du heller vil ha det'}},
    ]},
  ],
  steps:[
    {en:'Heat the sugar for the caramel with the water in a small heavy pan over medium heat. Swirl the pan but do not stir it once the sugar has melted, or it will crystallise.',
     no:'Varm sukkeret til karamellen sammen med vannet i en liten, tykkbunnet kjele på middels varme. Vipp kjelen rundt, men ikke rør i den etter at sukkeret har smeltet, ellers krystalliserer sukkeret seg.'},
    {en:'Take it off the heat the moment it turns the colour of dark honey and pour it into the mould, tilting until it coats the base and a little of the sides. It sets hard within a minute.',
     no:'Ta den av platen i samme øyeblikk som den får fargen av mørk honning, og hell den i formen mens du vipper den rundt til bunnen og litt av sidene er dekket. Den stivner på et minutt.'},
    {en:'Crush the amaretti to fine crumbs in a bag with a rolling pin, keeping a few biscuits back whole.',
     no:'Knus amarettiene til fine smuler i en pose med kjevlet, og hold noen kjeks tilbake hele.'},
    {en:'Warm the milk in a pan until it steams, and take it off before it boils.',
     no:'Varm melken i en kjele til den damper, og ta den av før den koker.'},
    {en:'Beat the eggs with the sugar until pale but not foamy. Air beaten in now shows up as bubbles in the set pudding.',
     no:'Visp eggene med sukkeret til blandingen er lys, men ikke skummende. Luft som piskes inn nå, viser seg som bobler i den ferdige puddingen.'},
    {en:'Whisk in the sifted cocoa, then the amaretti crumbs and the rum.',
     no:'Visp inn den siktede kakaoen, og deretter amarettismulene og rommen.'},
    {en:'Pour on the warm milk in a thin stream, stirring all the while, then pass the mixture through a sieve into a jug.',
     no:'Hell på den varme melken i en tynn stråle mens du rører hele tiden, og sil så blandingen over i en mugge.'},
    {en:'Pour it into the caramel-lined mould and skim off any foam that has gathered on the surface.',
     no:'Hell den i formen med karamellen, og skum av det som har lagt seg på overflaten.'},
    {en:'Stand the mould in a roasting tin, pour hot water into the tin until it reaches halfway up the mould, and bake at 160 °C for 50 to 60 minutes.',
     no:'Sett formen i en langpanne, hell varmt vann i pannen til det når halvveis opp på formen, og stek ved 160 °C i 50 til 60 minutter.'},
    {en:'Test it by nudging the tin: the middle should tremble like set jelly, not ripple like liquid. Lift the mould out of the water and let it cool.',
     no:'Prøv den ved å dytte borti pannen. Midten skal skjelve som stivnet gelé, ikke skvulpe som væske. Løft formen ut av vannet, og la den kjølne.'},
    {en:'Chill it overnight, run a thin knife round the edge, and turn it out onto a dish so the caramel runs down the sides. Serve with the whole amaretti.',
     no:'Sett den kaldt til dagen etter, før en tynn kniv rundt kanten, og hvelv den ut på et fat, slik at karamellen renner nedover sidene. Server med de hele amarettiene.'},
  ],
  notes:[
    {title:{en:'Why the water bath', no:'Hvorfor vannbadet'},
     body:{en:'A custard set in a dry oven cooks from the outside in and reaches 100 °C at the wall of the mould long before the middle has set, which is exactly how a pudding ends up curdled at the edge and loose in the centre. Water holds the mould at boiling point and no higher, so the whole thing arrives at setting temperature together.',
           no:'En eggekrem som stivner i tørr ovn, koker utenfra og inn og når 100 °C ved formveggen lenge før midten har satt seg, og nettopp slik ender en pudding opp skilt i kanten og løs i midten. Vannet holder formen ved kokepunktet og ikke høyere, så hele røren når stivnetemperaturen samtidig.'}},
    {title:{en:'Caramel makes its own sauce', no:'Karamellen lager sin egen saus'},
     body:{en:'The hard sheet of caramel in the bottom of the mould draws water out of the custard while the pudding sits overnight and dissolves into a thin bitter syrup, which is why the dessert has to rest before it is turned out and why no sauce is made for it. Stop the caramel a shade darker than looks comfortable: sugar taken only to gold tastes of nothing but sweet.',
           no:'Den harde karamellplaten i bunnen av formen trekker vann ut av puddingen mens den står natten over, og løser seg opp til en tynn, bitter sirup. Derfor må desserten hvile før den hvelves ut, og derfor lages det ingen saus til den. Stans karamellen et hakk mørkere enn det som føles behagelig, for sukker som bare får bli gyllent, smaker ikke annet enn søtt.'}},
    {title:{en:'The crumbs are structure', no:'Smulene er struktur'},
     body:{en:'Amaretti crumbs swell in the milk and hold the custard up, so a bonet cuts more cleanly and stands taller than a plain crème caramel with the same number of eggs. Grind them to dust and you lose the faint grain that tells you which pudding you are eating.',
           no:'Amarettismulene sveller i melken og holder eggekremen oppe, så en bonet lar seg skjære renere og står høyere enn en ren crème caramel med like mange egg. Maler du dem til støv, mister du den svake kornetheten som forteller hvilken dessert du spiser.'}},
  ],
  variations:[
    {title:{en:'Bonet alla monferrina', no:'Bonet alla monferrina'},
     body:{en:'The Monferrato is said to have made the pudding before cocoa reached it, and a pale version without any chocolate is still cooked there: amaretti, milk, eggs and caramel alone, sometimes with a little grated lemon zest. It tastes much more of almond.',
           no:'I Monferrato skal desserten ha vært laget før kakaoen kom dit, og en lys utgave uten sjokolade lages fortsatt: amaretti, melk, egg og karamell alene, iblant med litt revet sitronskall. Den smaker langt mer av mandel.'}},
    {title:{en:'Small moulds', no:'Små former'},
     body:{en:'Ramekins bake in about half the time and unmould without any drama, and they let each person have their own pool of caramel. Start testing them at the twenty-five minute mark; the small ones overshoot quickly.',
           no:'Porsjonsformer stekes på omtrent halve tiden og lar seg hvelve ut uten dramatikk, og hver gjest får sin egen dam med karamell. Sjekk dem allerede etter tjuefem minutter, for de små farer fort forbi.'}},
    {title:{en:'Which bottle goes in it', no:'Hvilken flaske som går i den'},
     body:{en:'Rum is the common choice, but Fernet-Branca gives the bitter, medicinal edge that older Piedmontese cooks prefer, and Marsala makes it rounder and sweeter. Whichever it is, it goes in cold, with the crumbs, and not into the hot milk where the alcohol would carry the aroma off.',
           no:'Rom er det vanlige valget, men Fernet-Branca gir den bitre, apotekaktige kanten som eldre piemontesiske kokker foretrekker, og Marsala gjør den rundere og søtere. Uansett hva du velger, skal den i kald sammen med smulene, og ikke i den varme melken, der alkoholen ville tatt duften med seg ut.'}},
  ],
},

];
