// Puglia recipes. Contract: docs/recipe-format.md. Both languages in one file; never narrated.
// Everything here follows the Puglia food reading (content/puglia.js, lesson 3): durum semolina and
// olive oil rather than egg and butter, orecchiette dragged and turned by thumb in Via dell'Arco Basso,
// cime di rapa boiled in the pasta water, potato in the focaccia dough, taralli boiled before they are
// baked, and the fornello pronto grills of Martina Franca and Cisternino.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-75'] = [

{
  id:'orecchiette-cime-di-rapa', dish:'Orecchiette con cime di rapa', course:'primo', lesson:3, serves:4,
  time:{prep:70, cook:15}, hero:'orecchiette-rapa', tags:['pasta','semolina','greens','vegetable'],
  title:{en:'Orecchiette con cime di rapa', no:'Orecchiette con cime di rapa'},
  blurb:{en:'Semolina pasta turned over a thumb, cooked in one pot with bitter turnip tops and dressed with oil, garlic, chilli and anchovy.',
         no:'Pasta av semule som vrenges over tommelen, kokes i én gryte sammen med bitre nepetopper og serveres med olje, hvitløk, chili og ansjos.'},
  heroCaption:{en:'Orecchiette con cime di rapa: buds, leaves and tender stalks, with toasted breadcrumbs scattered over the top.',
               no:'Orecchiette con cime di rapa med knopper, blader og møre stilker, og ristet brødrasp strødd over.'},
  wines:['Rosato del Salento'],
  headnote:{
    en:'<p>Orecchiette are durum-wheat semolina and water, with no egg anywhere in them. A rope of dough is cut into pieces the size of a fingernail, each piece is dragged across a bare board with a blunt knife until it curls, and then it is turned inside out over the tip of a thumb. What comes off the board is a small cup with a rough outside and a thick middle, and both of those are the point. In the old town of Bari, in <strong>Via dell\'Arco Basso</strong>, women still make them at tables outside their front doors and sell them to whoever walks past.</p>'
      + '<p>To them belongs <strong>cime di rapa</strong>, the flowering tops, buds and leaves of a turnip grown for its greens rather than its root, sold in English as broccoli rabe or rapini. It is properly bitter, and the bitterness is the dish. Garlic, chilli, good oil and a few anchovies are there to stand against it, nothing sweetens it, and in Bari nothing is grated over it either.</p>'
      + '<p>It is all one pot. The greens go into the boiling water first, the pasta follows them in, and the two are lifted out together into a pan where anchovy has melted into warm oil. The water clinging to them carries starch from the pasta and bitterness from the greens, and there is no more sauce than that.</p>',
    no:'<p>Orecchiette er durumsemule og vann, uten egg noe sted. En pølse av deig skjæres i biter på størrelse med en fingernegl, hver bit dras over et bart brett med en butt kniv til den krøller seg, og så vrenges den over tommeltuppen. Av brettet kommer en liten skål med ru utside og tykk midte, og begge deler er poenget. I gamlebyen i Bari, i <strong>Via dell\'Arco Basso</strong>, lager kvinner dem fortsatt på bord utenfor inngangsdørene og selger dem til forbipasserende.</p>'
      + '<p>Til dem hører <strong>cime di rapa</strong>, blomstertoppene, knoppene og bladene av en nepe som dyrkes for det grønne og ikke for roten. På engelsk selges den som broccoli rabe eller rapini. Den er ordentlig bitter, og bitterheten er selve retten. Hvitløk, chili, god olje og noen ansjosfileter står imot den, ingenting søter den, og i Bari rives det heller ikke ost over.</p>'
      + '<p>Alt skjer i én gryte. Det grønne går i det kokende vannet først, pastaen følger etter, og de to løftes sammen over i en panne der ansjosen har smeltet ut i varm olje. Vannet som henger igjen, bærer stivelse fra pastaen og bitterhet fra det grønne, og mer saus finnes ikke.</p>'},
  ingredients:[
    { group:{en:'For the orecchiette', no:'Til orecchiettene'}, items:[
      {q:400, u:'g', n:{en:'fine durum semolina', no:'fin durumsemule'}, note:{en:'semola rimacinata, the twice-milled kind; ordinary coarse semolina will not come together', no:'semola rimacinata, den finmalte typen; vanlig grov semule går ikke sammen til en deig'}},
      {q:200, u:'ml', n:{en:'water', no:'vann'}, note:{en:'lukewarm; hold a little back, semolinas differ', no:'lunkent; hold igjen litt, for semule varierer'}},
      {q:5,   u:'g', n:{en:'salt', no:'salt'}},
    ]},
    { group:{en:'For the dressing', no:'Til sausen'}, items:[
      {q:800, u:'g', n:{en:'cime di rapa', no:'cime di rapa'}, note:{en:'broccoli rabe or rapini; weighed untrimmed, since half of it is stalk', no:'broccoli rabe eller rapini; veid urenset, siden halvparten er stilk'}},
      {q:70,  u:'ml', n:{en:'extra-virgin olive oil', no:'extra virgin olivenolje'}},
      {q:2,   u:'', n:{en:'garlic cloves', no:'hvitløksfedd'}, note:{en:'sliced thin, not crushed', no:'skåret i tynne skiver, ikke knust'}, round:'half'},
      {q:4,   u:'', n:{en:'anchovy fillets', no:'ansjosfileter'}, note:{en:'in Norway a jar labelled ansjos holds spiced sprat; ask for sardeller or acciughe, salted or in oil', no:'i Norge er det krydret brisling som selges på glass merket ansjos; du skal ha sardeller eller acciughe, saltet eller på olje'}, round:'half'},
      {q:1,   u:'', n:{en:'small dried chilli', no:'liten tørket chili'}, round:'half'},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'In the pot', no:'I gryten'}, items:[
      {q:4,  u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:20, u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
    ]},
  ],
  steps:[
    {en:'Stir the salt into the water, pour it into the semolina a little at a time and gather it into a firm dough. It should be harder than a bread dough and just this side of dry.',
     no:'Rør saltet ut i vannet, hell det i semulen litt om gangen, og samle det til en fast deig. Den skal være hardere enn en brøddeig og så vidt ikke tørr.'},
    {en:'Knead for 10 minutes, until the surface is smooth, then cover the dough and rest it for half an hour so the gluten slackens.',
     no:'Elt i 10 minutter, til overflaten er glatt. Dekk så deigen til og la den hvile en halvtime, så gluten slakner.'},
    {en:'Roll a piece of the dough under your palms into a rope about as thick as your little finger, and cut it into pieces the width of a fingernail.',
     no:'Rull et stykke av deigen under håndflatene til en pølse omtrent så tykk som lillefingeren, og skjær den i biter like brede som en fingernegl.'},
    {en:'Drag each piece towards you across a bare wooden board with a blunt round-tipped knife, pressing as you go, until it curls into a shell.',
     no:'Dra hver bit mot deg over et bart trebrett med en butt kniv med rund tupp, og trykk mens du drar, til den krøller seg til et skjell.'},
    {en:'Turn the shell inside out over the tip of your thumb so the rough side ends up outermost, and lay it on a cloth dusted with semolina. Keep going until the dough is used up.',
     no:'Vreng skjellet over tommeltuppen så den ru siden havner ytterst, og legg det på et klede strødd med semule. Hold på til deigen er brukt opp.'},
    {en:'Trim the cime di rapa: keep the buds, the leaves and the slim upper stalks, and throw away anything thicker than a pencil, which stays woody however long it boils.',
     no:'Rens cime di rapa. Behold knoppene, bladene og de tynne øverste stilkene, og kast alt som er tykkere enn en blyant, for det blir trevlete uansett hvor lenge det koker.'},
    {en:'Warm the oil in a wide pan over low heat with the sliced garlic and the whole chilli, until the garlic turns pale gold but no further.',
     no:'Varm oljen i en vid panne på svak varme sammen med hvitløksskivene og den hele chilien, til hvitløken blir svakt gyllen og ikke mer.'},
    {en:'Take the pan off the heat, drop in the anchovies and stir until they dissolve into the oil. On the heat they fry and turn bitter instead.',
     no:'Ta pannen av platen, legg i ansjosen, og rør til den løser seg opp i oljen. Står pannen på platen, blir ansjosen stekt i stedet, og da blir den bitter.'},
    {en:'Bring the water to the boil, salt it, and cook the greens for 4 minutes. Then tip the orecchiette into the same pot.',
     no:'Kok opp vannet, salt det, og kok det grønne i 4 minutter. Ha så orecchiettene i den samme gryten.'},
    {en:'Give them 5 to 7 minutes, until they float and the thick middle is tender to the tooth, and taste one before you trust the clock.',
     no:'Gi dem 5 til 7 minutter, til de flyter opp og den tykke midten er mør mot tannen. Smak på én før du stoler på klokken.'},
    {en:'Lift everything out with a spider, straight into the pan and still dripping, and toss it over medium heat for a minute, loosening with cooking water until the greens coat the pasta.',
     no:'Løft alt opp med hullsleiv og rett over i pannen mens det fortsatt drypper. Vend det på middels varme i ett minutt, og spe med kokevann til det grønne legger seg rundt pastaen.'},
    {en:'Fish out the chilli, taste for salt and serve at once. In Bari nothing is grated over it; toasted breadcrumbs are the only thing that goes on top.',
     no:'Fisk ut chilien, smak til med salt, og server med en gang. I Bari rives det ikke ost over, og ristet brødrasp er det eneste som strøs på.'},
  ],
  notes:[
    {title:{en:'Why the thumb', no:'Derfor tommelen'},
     body:{en:'Turning the shell inside out does two things at once. It leaves the outside rough, torn where the knife dragged it, so a thin oily dressing has something to hold on to. And it leaves a thick dome in the middle against a thin rim, which means one piece has a firm centre and a soft edge after the same five minutes in the water. A smooth machine-pressed orecchietta has neither, which is why the shape is still made by hand.',
           no:'Vrengingen gjør to ting på én gang. Utsiden blir ru og flisete der kniven har dratt i den, så en tynn og oljete saus har noe å henge fast i. Og midten blir en tykk kuppel mot en tynn kant, slik at én og samme bit har fast senter og myk rand etter de samme fem minuttene i vannet. En glatt, maskinpresset orecchietta har ingen av delene, og derfor formes den fortsatt for hånd.'}},
    {title:{en:'One pot, and the water is the sauce', no:'Én gryte, og vannet er sausen'},
     body:{en:'Boiling the greens in the pasta water is not a shortcut. The water takes up their bitterness and gives it back to the pasta, and the pasta gives up starch that thickens what clings to the leaves. Cook them apart and you get pasta in one flavour and greens in another, with olive oil sliding off both. Lift everything out wet rather than draining it dry.',
           no:'Det grønne koker i pastavannet, og det er ikke for å spare oppvask. Vannet tar opp bitterheten og gir den tilbake til pastaen, og pastaen gir fra seg stivelse som tykner det som blir sittende på bladene. Koker du dem hver for seg, får du pasta med én smak og grønnsaker med en annen, og olivenoljen glir av begge. Løft alt opp vått i stedet for å helle av vannet.'}},
    {title:{en:'The anchovy is seasoning', no:'Ansjosen er krydder'},
     body:{en:'Four fillets melted into warm oil do not make the dish taste of fish. They dissolve completely and leave savouriness behind, which is the only thing standing between the bitterness of the greens and a plate that tastes of nothing but oil. The pan must be off the heat, because an anchovy that fries turns sharp and stays in pieces.',
           no:'Noen få fileter som smeltes ut i varm olje, gjør ikke at retten smaker fisk. De løses helt opp og etterlater seg en smaksrik bunn, og den er det eneste som står mellom bitterheten i det grønne og en tallerken som bare smaker olje. Pannen må være av platen, for ansjos som stekes, blir skarp og ligger igjen i biter.'}},
  ],
  variations:[
    {title:{en:'If you cannot find cime di rapa', no:'Får du ikke tak i cime di rapa'},
     body:{en:'Norwegian shops rarely stock it, and it is not the same plant as broccoli. The nearest thing is broccolini, which has the stalks and the buds but almost none of the bitterness; add a head of chicory, some rocket or a few dandelion leaves to bring that back. Turnip tops from your own garden are the real article.',
           no:'Norske butikker fører den sjelden, og den er ikke den samme planten som brokkoli. Nærmest kommer stilkbrokkoli, som har stilkene og knoppene, men nesten ingenting av bitterheten. Ha i et hode sikori, litt ruccola eller noen løvetannblader for å få den tilbake. Nepetopper fra egen hage er den ekte varen.'}},
    {title:{en:'Breadcrumbs instead of cheese', no:'Brødrasp i stedet for ost'},
     body:{en:'Puglia calls fried breadcrumbs <em>mollica</em> and puts them where a richer region would grate cheese. Toast a handful of coarse crumbs from stale bread in oil until they are dark gold and scatter them over each plate; they hold their crunch for about as long as it takes to eat.',
           no:'Puglia kaller stekt brødrasp <em>mollica</em> og bruker den der en rikere region ville revet ost. Rist en håndfull grovt rasp av tørt brød i olje til det er mørkt gyllent, og strø det over hver tallerken. Det holder på sprøheten omtrent så lenge det tar å spise.'}},
    {title:{en:'Dried orecchiette', no:'Tørkede orecchiette'},
     body:{en:'Puglian dried orecchiette are sold well outside the region and are an honest substitute. They need 11 to 13 minutes rather than five, so they go into the pot before the greens instead of after them.',
           no:'Tørkede orecchiette fra Puglia selges langt utenfor regionen og er en ærlig erstatning. De trenger 11 til 13 minutter og ikke fem, så de går i gryten før det grønne og ikke etter.'}},
  ],
},

{
  id:'focaccia-barese', dish:'Focaccia barese', course:'antipasto', lesson:3, serves:6,
  time:{prep:180, cook:30}, hero:'focaccia', tags:['bread','potato','tomato','oven','vegan'],
  title:{en:'Focaccia barese', no:'Focaccia barese'},
  blurb:{en:'A thick, wet, oily focaccia with boiled potato worked into the dough, cherry tomatoes and olives pressed into the top.',
         no:'En tykk, våt og oljerik focaccia der kokt potet er arbeidet inn i deigen, og cherrytomater og oliven er trykket ned i toppen.'},
  heroCaption:{en:'Focaccia barese from a round tin: tomatoes pressed in cut side up, olives between them, oregano and coarse salt over the whole surface.',
               no:'Focaccia barese fra en rund form. Tomatene er trykket ned med snittflaten opp, olivenene ligger imellom, og oregano og grovt salt dekker hele overflaten.'},
  wines:['Verdeca'],
  headnote:{
    en:'<p>Focaccia barese is a bread and not a pizza, and it is thicker and far wetter than either of the Ligurian focacce. Boiled potato is mashed while it is still hot and worked into the flour, Bari uses durum semolina from the Murge alongside soft wheat, and the top is loaded rather than dressed: halved cherry tomatoes pressed in cut side up, whole olives between them, oregano, coarse salt and a great deal of oil.</p>'
      + '<p>The potato is the mechanism. Cooked potato starch holds several times its own weight in water and keeps hold of it through the oven, so the crumb stays open and damp for a day instead of drying out by evening. It also lets the dough carry far more water than flour alone could take, which is why this one is beaten in the bowl with a wet hand and spread in the tin with oiled fingertips rather than kneaded on a board and rolled.</p>'
      + '<p>The tin matters as much as the dough. Bari bakes it round, in a tin swimming in oil, so the underside more or less fries while the top bakes, and it is sold by the slab over the bakery counter and eaten standing up.</p>',
    no:'<p>Focaccia barese er et brød og ingen pizza, og den er tykkere og langt våtere enn begge de liguriske focacciaene. Kokt potet moses mens den ennå er varm og arbeides inn i melet, og deigen har durumsemule fra Murge ved siden av hvetemel. Toppen lesses full i stedet for å pyntes. Halve cherrytomater trykkes ned med snittflaten opp, hele oliven går imellom, og over det hele kommer oregano, grovt salt og rikelig med olje.</p>'
      + '<p>Poteten er mekanismen. Kokt potetstivelse binder flere ganger sin egen vekt i vann og holder på det gjennom ovnen, så krummen blir åpen og fuktig et døgn i stedet for å tørke ut samme kveld. Poteten gjør også at deigen tåler langt mer vann enn mel alene kunne bære, og derfor piskes denne deigen i bollen med våt hånd og bres utover i formen med oljede fingertupper i stedet for å eltes på et brett og kjevles.</p>'
      + '<p>Formen betyr like mye som deigen. I Bari stekes den i en rund form som svømmer i olje, slik at undersiden nesten frityrstekes mens toppen bakes. Den selges i store stykker over bakeridisken og spises stående.</p>'},
  ingredients:[
    { group:{en:'For the dough', no:'Til deigen'}, items:[
      {q:200, u:'g', n:{en:'floury potatoes', no:'melne poteter'}, note:{en:'boiled in their skins, peeled hot and pressed through a ricer', no:'kokt med skallet på, skrelt varme og presset gjennom en potetpresse'}},
      {q:300, u:'g', n:{en:'fine durum semolina', no:'fin durumsemule'}},
      {q:200, u:'g', n:{en:'‘00’ flour', no:'mel type 00'}, note:{en:'plain wheat flour does the same job', no:'vanlig hvetemel gjør den samme jobben'}},
      {q:350, u:'ml', n:{en:'water', no:'vann'}, note:{en:'lukewarm; the dough is meant to be too slack to knead', no:'lunkent; deigen skal være for løs til å eltes'}},
      {q:7,   u:'g', n:{en:'dried yeast', no:'tørrgjær'}, note:{en:'or three times that much fresh yeast', no:'eller tre ganger så mye fersk gjær'}},
      {q:10,  u:'g', n:{en:'salt', no:'salt'}},
      {q:20,  u:'ml', n:{en:'extra-virgin olive oil', no:'extra virgin olivenolje'}},
    ]},
    { group:{en:'On top', no:'På toppen'}, items:[
      {q:300, u:'g', n:{en:'cherry tomatoes', no:'cherrytomater'}, note:{en:'halved; small and ripe, not watery salad ones', no:'delt i to; små og modne, ikke vassne salattomater'}},
      {q:100, u:'g', n:{en:'black olives', no:'sorte oliven'}, note:{en:'Puglia uses celline or leccino, stones left in', no:'Puglia bruker celline eller leccino, med steinen i'}},
      {u:'', n:{en:'dried oregano', no:'tørket oregano'}, scale:'none'},
      {u:'', n:{en:'coarse salt', no:'grovt salt'}, scale:'none'},
      {u:'', n:{en:'olive oil for the tin and the top', no:'olivenolje til formen og toppen'}, note:{en:'more than feels reasonable', no:'mer enn det virker rimelig'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Boil the potatoes whole in their skins until a knife slides through without resistance, then peel them while they are hot and press them through a ricer into a large bowl.',
     no:'Kok potetene hele med skallet på til en kniv går gjennom uten motstand. Skrell dem mens de er varme, og press dem gjennom en potetpresse ned i en stor bolle.'},
    {en:'Whisk the yeast into the lukewarm water and leave it for a few minutes.',
     no:'Visp gjæren ut i det lunkne vannet og la det stå noen minutter.'},
    {en:'Add both flours to the warm potato, pour the yeast water in gradually and work everything to a slack, sticky dough with a wooden spoon.',
     no:'Ha begge meltypene i den varme poteten, hell gjærvannet i litt etter litt, og arbeid alt sammen til en løs og klebrig deig med en tresleiv.'},
    {en:'Add the salt and the oil, then beat the dough against the side of the bowl with a wet hand for 5 minutes, until it stops tearing and starts to pull away in a sheet.',
     no:'Ha i saltet og oljen, og slå så deigen mot bollekanten med våt hånd i 5 minutter, til den slutter å revne og begynner å slippe i ett stykke.'},
    {en:'Cover the bowl and leave it somewhere warm for about 2 hours, until the dough has doubled and the surface is full of bubbles.',
     no:'Dekk bollen til og la den stå varmt i omtrent 2 timer, til deigen er doblet og overflaten er full av bobler.'},
    {en:'Pour a generous film of oil into a round tin about 32 cm across and tilt it until the base and the sides are covered.',
     no:'Hell en raus hinne olje i en rund form på omtrent 32 cm, og vipp formen rundt til både bunn og sider er dekket.'},
    {en:'Tip the dough in without knocking the air out of it, and push it out to the rim with oiled fingertips. Never use a rolling pin here.',
     no:'Hvelv deigen over i formen uten å slå luften ut av den, og skyv den ut til kanten med oljede fingertupper. Bruk aldri kjevle her.'},
    {en:'Cover it again and let it rest for 40 minutes, while you heat the oven to 230 °C.',
     no:'Dekk den til igjen og la den hvile i 40 minutter mens du varmer ovnen til 230 °C.'},
    {en:'Press the tomato halves deep into the dough, cut side up, so that each one sits in its own hollow, and push the olives in between them.',
     no:'Trykk tomathalvdelene godt ned i deigen med snittflaten opp, så hver av dem ligger i sin egen grop, og skyv olivenene ned imellom.'},
    {en:'Scatter oregano and coarse salt over the surface and pour more oil over the whole thing, letting it pool in the dimples.',
     no:'Strø oregano og grovt salt over overflaten, og hell mer olje over det hele, slik at den samler seg i gropene.'},
    {en:'Bake low in the oven for 25 to 30 minutes, until the top is deep gold, the tomatoes have collapsed and the base lifts away crisp when you slide a knife under it.',
     no:'Stek lavt i ovnen i 25 til 30 minutter, til toppen er dypt gyllen, tomatene har falt sammen, og bunnen er sprø når du fører en kniv under den.'},
    {en:'Slide it out onto a rack and let it stand for 10 minutes before you cut it into squares. Straight from the tin the crumb is still steaming and tears rather than slices.',
     no:'Skyv den over på en rist og la den stå i 10 minutter før du skjærer den i firkanter. Rett fra formen damper krummen fortsatt, og da revner den i stedet for å la seg skjære.'},
  ],
  notes:[
    {title:{en:'What the potato does', no:'Hva poteten gjør'},
     body:{en:'Potato starch that has been cooked and burst absorbs several times its own weight in water and does not give it up again in the oven. That is why this dough can be far wetter than a plain bread dough without collapsing, and why the crumb is still soft the next morning. Press the potato while it is hot: cooled and reheated it goes gluey, and a gluey mash makes a heavy focaccia.',
           no:'Potetstivelse som er kokt og har sprukket, suger til seg flere ganger sin egen vekt i vann og gir det ikke fra seg igjen i ovnen. Derfor tåler denne deigen å være langt våtere enn en vanlig brøddeig uten å falle sammen, og derfor er krummen fortsatt myk neste morgen. Press poteten mens den er varm. Har den først kjølnet og blir varmet opp igjen, blir den klissete, og en klissete potetmasse gir en tung focaccia.'}},
    {title:{en:'Oil in the tin, not just on top', no:'Olje i formen, ikke bare på toppen'},
     body:{en:'The pool of oil under the dough reaches oven temperature long before the crumb does and fries the underside on contact. That is where the crisp, almost golden base of a good focaccia barese comes from, and a dry tin gives you a pale, bready bottom instead. The same trick is worth carrying to anything baked shallow in a tin.',
           no:'Oljen som ligger under deigen, når ovnstemperatur lenge før krummen gjør det, og steker undersiden med en gang. Derfra kommer den sprø, nesten gylne bunnen på en god focaccia barese, mens en tørr form gir en blek og brødaktig bunn. Trikset er verdt å ta med seg til alt som stekes tynt i en form.'}},
    {title:{en:'Press the tomatoes in, do not lay them on', no:'Trykk tomatene ned, ikke legg dem oppå'},
     body:{en:'A tomato resting on the surface slides off the first slice and leaves a wet patch behind it. Pushed down until the dough closes round it, it anchors itself, its juice runs into the crumb rather than over the crust, and the hollow it makes fills with oil and salt. Cut side up keeps the skin against the dough, where it stops the juice escaping downwards.',
           no:'En tomat som bare ligger på overflaten, glir av ved første stykke og etterlater en våt flekk. Skyves den ned til deigen lukker seg rundt den, sitter den fast, saften renner inn i krummen i stedet for utover skorpen, og gropen den lager, fylles med olje og salt. Snittflaten opp holder skinnet mot deigen, og der hindrer det saften i å slippe ned.'}},
  ],
  variations:[
    {title:{en:'Onion instead of tomato', no:'Løk i stedet for tomat'},
     body:{en:'Altamura and the towns of the Murge make the same bread with sliced onion softened in oil, sometimes with olives and capers in it and no tomato at all. It is sweeter, browns faster and wants a slightly cooler oven.',
           no:'Altamura og byene på Murge lager det samme brødet med løk i skiver som er myknet i olje, iblant med oliven og kapers i og uten tomat i det hele tatt. Det blir søtere, får farge raskere og vil ha litt lavere ovnstemperatur.'}},
    {title:{en:'Thick or thin', no:'Tykk eller tynn'},
     body:{en:'The same quantity of dough spread in a wider tin gives a thinner, crisper focaccia closer to what many bakeries sell by the slab. A smaller tin gives the tall, damp, cake-like version the home kitchen makes. Neither is wrong; the timing moves by about five minutes either way.',
           no:'Brer du den samme mengden deig utover i en videre form, får du en tynnere og sprøere focaccia, som ligner mer på den mange bakerier selger i store stykker. En mindre form gir den høye, fuktige og nesten kakeaktige varianten som lages hjemme. Ingen av delene er galt, og steketiden flytter seg omkring fem minutter hver vei.'}},
    {title:{en:'The next day', no:'Dagen etter'},
     body:{en:'It is at its best two hours out of the oven and still good the next day. Warm a square through in a dry pan rather than in a microwave, which turns the potato crumb rubbery. It does not freeze well.',
           no:'Den er på sitt beste et par timer etter at den kom ut av ovnen, og fortsatt god dagen etter. Varm et stykke gjennom i en tørr panne og ikke i mikrobølgeovn, for den gjør potetkrummen gummiaktig. Den egner seg ikke for frysing.'}},
  ],
},

{
  id:'taralli', dish:'Taralli', course:'antipasto', lesson:3, serves:8,
  time:{prep:70, cook:25}, hero:'taralli', tags:['snack','fennel','boiled','oven','vegan'],
  title:{en:'Taralli al finocchio', no:'Taralli al finocchio'},
  blurb:{en:'Small rings of flour, oil, white wine and fennel seed, boiled like bagels and then baked until they snap.',
         no:'Små ringer av mel, olje, hvitvin og fennikelfrø som kokes som bagels og deretter stekes til de knekker.'},
  heroCaption:{en:'Two taralli. The overlapped join and the smooth, faintly shiny skin both come from the minute in boiling water.',
               no:'To taralli. Minuttet i kokende vann gir både skjøten der endene er lagt over hverandre, og det glatte, svakt blanke skinnet.'},
  wines:['Verdeca'],
  headnote:{
    en:'<p>Taralli are small rings of dough made from flour, olive oil, dry white wine and salt, with fennel seed in the version Puglia eats most of. They belong to no particular meal. A bowl of them stands on the table beside the wine at any hour of the day, and they keep for weeks in a tin.</p>'
      + '<p>What separates a tarallo from a biscuit is that it is boiled before it is baked, exactly as a bagel is. A minute in boiling water gelatinises the starch on the outside and lays it down as a smooth skin. In the oven that skin sets into a tight, glassy crust that snaps instead of crumbling, and it gives the ring its faint shine. Puglia has a separate name for the boiled ones, <em>scaldatelli</em>.</p>'
      + '<p>There is neither yeast nor water in this dough. Wine and oil carry it, and both of them get in the way of gluten, so the ring stays short and brittle rather than chewy. Nothing about the method is hard. Two things go wrong: the rings are boiled too long, or they go into the oven while the surface is still wet.</p>',
    no:'<p>Taralli er små ringer av deig laget av mel, olivenolje, tørr hvitvin og salt, med fennikelfrø i den varianten Puglia spiser mest av. De hører ikke til noe bestemt måltid. En skål med dem står på bordet ved siden av vinen når som helst på døgnet, og de holder seg i ukevis i en boks.</p>'
      + '<p>En tarallo skiller seg fra en kjeks ved at den kokes før den stekes, akkurat som en bagel. Ett minutt i kokende vann får stivelsen på utsiden til å forklistre og legge seg som et glatt skinn. I ovnen stivner skinnet til en tett, glassaktig skorpe som knekker i stedet for å smuldre, og den gir ringen den svake glansen. Puglia har et eget navn på de kokte, <em>scaldatelli</em>.</p>'
      + '<p>Det er verken gjær eller vann i denne deigen. Vin og olje bærer den, og begge deler kommer i veien for gluten, så ringene blir korte og sprø i stedet for seige. Ingenting ved metoden er vanskelig. To ting går likevel ofte galt. Enten kokes ringene for lenge, eller så settes de i ovnen mens overflaten ennå er våt.</p>'},
  ingredients:[
    { group:{en:'For the dough', no:'Til deigen'}, items:[
      {q:500, u:'g', n:{en:'‘00’ flour', no:'mel type 00'}, note:{en:'a fifth of it durum semolina gives a harder snap', no:'en femtedel durumsemule gir hardere knekk'}},
      {q:120, u:'ml', n:{en:'dry white wine', no:'tørr hvitvin'}, note:{en:'at room temperature; a Puglian Verdeca is the local choice', no:'med romtemperatur; en Verdeca fra Puglia er det lokale valget'}},
      {q:120, u:'ml', n:{en:'extra-virgin olive oil', no:'extra virgin olivenolje'}},
      {q:10,  u:'g', n:{en:'salt', no:'salt'}},
      {q:8,   u:'g', n:{en:'fennel seed', no:'fennikelfrø'}, note:{en:'whole, lightly crushed to wake the oils', no:'hele, lett knust for å vekke oljene'}},
    ]},
    { group:{en:'For the boiling', no:'Til kokingen'}, items:[
      {q:3,  u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:10, u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
    ]},
  ],
  steps:[
    {en:'Crush the fennel seed lightly in a mortar and stir it into the flour with the salt.',
     no:'Knus fennikelfrøene lett i en morter og rør dem inn i melet sammen med saltet.'},
    {en:'Pour in the oil and the wine and work the mixture into a firm dough. It should be harder than a bread dough and should not stick to your fingers at all.',
     no:'Hell i oljen og vinen og arbeid blandingen til en fast deig. Den skal være hardere enn en brøddeig og ikke klistre seg til fingrene i det hele tatt.'},
    {en:'Knead for 10 minutes, until the surface is smooth and elastic, then cover it and rest it for half an hour.',
     no:'Elt i 10 minutter, til overflaten er glatt og elastisk. Dekk deigen til og la den hvile en halvtime.'},
    {en:'Pinch off a piece and roll it under your palms into a rope about 8 mm thick, then cut the rope into lengths of about 10 cm.',
     no:'Klyp av et stykke og rull det under håndflatene til en pølse på omkring 8 mm, og skjær pølsen i lengder på omkring 10 cm.'},
    {en:'Bring the two ends of each length together into a ring, lay one end over the other and press the overlap firmly so it cannot open in the water.',
     no:'Før de to endene på hver lengde sammen til en ring, legg den ene enden over den andre, og trykk skjøten godt sammen så den ikke kan åpne seg i vannet.'},
    {en:'Bring the water to the boil and salt it, then drop in a dozen rings at a time. They will sink.',
     no:'Kok opp vannet og salt det, og legg i et dusin ringer om gangen. De synker.'},
    {en:'Lift each ring out with a slotted spoon the moment it floats, which takes about a minute, and lay it on a dry cloth. Longer in the water and it swells and bakes soft.',
     no:'Løft hver ring opp med hullsleiv i det øyeblikket den flyter opp, og det tar omtrent ett minutt. Legg den på et tørt klede. Blir den liggende lenger i vannet, sveller den og blir myk i ovnen.'},
    {en:'Leave the boiled rings on the cloth for 20 to 30 minutes, until the surface has gone from wet to matt and dry to the touch.',
     no:'La de kokte ringene ligge på kledet i 20 til 30 minutter, til overflaten har gått fra våt til matt og tørr å ta på.'},
    {en:'Set them on a lined baking sheet with a finger between them and bake at 200 °C for 20 to 25 minutes, until they are pale gold all over.',
     no:'Sett dem på et stekebrett med bakepapir, med en fingerbredde mellom hver, og stek på 200 °C i 20 til 25 minutter, til de er svakt gyllne over det hele.'},
    {en:'Turn the oven down to 150 °C and give them 10 minutes more, which drives the last of the water out of the middle.',
     no:'Skru ovnen ned til 150 °C og gi dem 10 minutter til, så det siste vannet drives ut av midten.'},
    {en:'Cool them completely on a rack before you taste one. They are still soft when they come out and crisp as they cool.',
     no:'Avkjøl dem helt på rist før du smaker. De er fortsatt myke når de kommer ut, og de blir sprø mens de kjølner.'},
  ],
  notes:[
    {title:{en:'Boiled, then baked', no:'Først kokt, så stekt'},
     body:{en:'The minute in boiling water cooks only the outermost layer. Starch there swells and bursts, and as it cools it lays down a continuous skin over the ring. That skin browns evenly, keeps its shape in the oven and dries into a hard, glassy shell, which is why a tarallo snaps cleanly instead of crumbling like shortcrust. It is the same trick that gives a bagel and a pretzel their crust, and it is the one step that cannot be left out.',
           no:'Minuttet i kokende vann koker bare det ytterste laget. Stivelsen der sveller og sprekker, og når den kjølner, legger den seg som et sammenhengende skinn rundt ringen. Skinnet brunes jevnt, holder formen i ovnen og tørker til et hardt, glassaktig skall, og derfor knekker en tarallo rent i stedet for å smuldre som mørdeig. Det er det samme trikset som gir bagels og kringler skorpen sin, og det er det ene trinnet du ikke kan hoppe over.'}},
    {title:{en:'Dry them before they bake', no:'Tørk dem før steking'},
     body:{en:'A ring that goes into the oven with water still on it steams instead of browning, and steam keeps the surface below the temperature at which it can colour. Half an hour on a cloth costs nothing and is the difference between pale, tough taralli and gold ones. Turn them once while they dry so the underside dries as well.',
           no:'En ring som settes i ovnen med vann på seg, damper i stedet for å brunes, og dampen holder overflaten under den temperaturen der den kan få farge. En halvtime på et klede koster ingenting og er forskjellen på bleke, seige taralli og gylne. Snu dem én gang mens de tørker, så undersiden også blir tørr.'}},
    {title:{en:'Wine and oil instead of water', no:'Vin og olje i stedet for vann'},
     body:{en:'Fat coats the flour and stops long gluten strands from forming, and alcohol works against gluten too. The result is a dough that is short rather than stretchy, which is exactly what a ring meant to break between the teeth needs. It also means there is no point kneading this dough for longer in the hope of improving it.',
           no:'Fett legger seg rundt melet og hindrer at det dannes lange glutentråder, og alkoholen i vinen gjør det samme. Resultatet blir en deig som er kort og ikke elastisk, og nettopp det trenger en ring som skal knekke mellom tennene. Det betyr også at det ikke nytter å elte denne deigen lenger i håp om å forbedre den.'}},
  ],
  variations:[
    {title:{en:'Chilli, pepper or plain', no:'Chili, pepper eller naturell'},
     body:{en:'Fennel is the Bari standard, but the same dough takes coarsely cracked black pepper, a spoonful of dried chilli flakes, or nothing at all. Whatever goes in has to be dry and finely broken, since anything wet softens the dough and anything large tears the rope as you roll it.',
           no:'Fennikel er standarden i Bari, men den samme deigen tåler grovknust sort pepper, en skje tørket chiliflak eller ingenting i det hele tatt. Alt som går i deigen, må være tørt og finknust, siden noe vått mykner deigen og noe stort river opp pølsen mens du ruller den.'}},
    {title:{en:'Tarallini', no:'Tarallini'},
     body:{en:'Rolled thinner and cut shorter, the same dough makes the small rings sold by the kilo across southern Italy. They boil in seconds and need about a third off the baking time, so watch them from the twelfth minute.',
           no:'Ruller du den tynnere og skjærer kortere lengder, gir den samme deigen de små ringene som selges kilovis i hele Sør-Italia. De koker på sekunder og trenger omtrent en tredel mindre steketid, så følg med fra tolvte minutt.'}},
    {title:{en:'Without the boil', no:'Uten kokingen'},
     body:{en:'Plenty of households in Puglia skip the water and bake the rings straight. They come out lighter, paler and more like a biscuit, and they crumble rather than snap. It is a real Puglian tarallo, only a different one, and it takes 10 minutes less in the oven.',
           no:'Mange husholdninger i Puglia dropper vannet og steker ringene rett. De blir lettere, blekere og mer som kjeks, og de smuldrer i stedet for å knekke. Det er en ekte tarallo fra Puglia, bare en annen, og den trenger 10 minutter mindre i ovnen.'}},
  ],
},

{
  id:'bombette', dish:'Bombette', course:'secondo', lesson:3, serves:4,
  time:{prep:35, cook:15}, hero:'bombette', tags:['pork','cheese','grill','valle-ditria'],
  title:{en:'Bombette di Martina Franca', no:'Bombette di Martina Franca'},
  blurb:{en:'Thin slices of pork neck rolled round caciocavallo and grilled over embers, the speciality of the butchers’ grills of the Valle d’Itria.',
         no:'Tynne skiver svinenakke som rulles rundt caciocavallo og grilles over glør. De er spesialiteten fra slaktergrillene i Valle d’Itria.'},
  heroCaption:{en:'Bombette and sausages in a double grill basket over wood embers, the way the fornello grills of the Valle d’Itria cook them. Nothing sits over the flame.',
               no:'Bombette og pølser i en dobbel grillkurv over glør fra ved, slik fornello-grillene i Valle d’Itria steker dem. Ingenting ligger over flammen.'},
  wines:['Primitivo di Manduria'],
  headnote:{
    en:'<p>Inland from the coast, at <strong>Martina Franca</strong> and <strong>Cisternino</strong> in the Valle d\'Itria, the butchers’ shops turn into restaurants in the evening. You choose your meat at the counter, it goes onto a wood grill behind the shop — the <em>fornello pronto</em>, the ready furnace — and it comes back to a paper-covered table charged by weight. The speciality of those grills is the <strong>bombetta</strong>, a thin slice of pork neck rolled round a piece of cheese.</p>'
      + '<p>Two things decide whether it works, and both are about fat. Pork neck, the cut cured here as capocollo, is heavily marbled, so a slice thin enough to be done in a quarter of an hour bastes itself from the inside instead of drying. And the cheese has to be shut in. Caciocavallo melts at grill heat and will find any gap in the roll; a bombetta that leaks is dry inside and sets the fire flaring underneath.</p>'
      + '<p>They cook over embers and never over flame, threaded several to a skewer so they hold their shape and turn together, and they are eaten with the fingers straight off the grill while the cheese is still running.</p>',
    no:'<p>Inne i landet, i <strong>Martina Franca</strong> og <strong>Cisternino</strong> i Valle d\'Itria, blir slakterbutikkene restauranter om kvelden. Du velger kjøttet i disken, det går på en vedgrill bak butikken, <em>fornello pronto</em>, og kommer tilbake til et papirdekket bord der du betaler etter vekt. Spesialiteten fra disse grillene er <strong>bombetta</strong>, en tynn skive svinenakke som rulles rundt en bit ost.</p>'
      + '<p>To ting avgjør om den lykkes, og begge handler om fett. Svinenakken, stykket som spekes her som capocollo, er godt marmorert, så en skive som er tynn nok til å bli ferdig på et kvarter, holder seg saftig innenfra i stedet for å tørke ut. Og osten må lukkes inne. Caciocavallo smelter i grillvarmen og finner enhver åpning i rullen. En bombetta som lekker, blir tørr inni og får fettet under til å ta fyr.</p>'
      + '<p>De grilles over glør og aldri over åpen flamme, tres flere på hvert spidd så de holder formen og snus samlet, og spises med fingrene rett fra grillen mens osten fortsatt renner.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:800, u:'g', n:{en:'pork neck', no:'svinenakke'}, note:{en:'in 16 slices about 4 mm thick; ask the butcher for collar, not loin', no:'i 16 skiver på omkring 4 mm; be slakteren om nakke, ikke kotelettkam'}},
    {q:200, u:'g', n:{en:'caciocavallo', no:'caciocavallo'}, note:{en:'young scamorza or a mild provolone will do; cut in short batons', no:'ung scamorza eller en mild provolone går også; skåret i korte staver'}},
    {q:10,  u:'g', n:{en:'flat-leaf parsley', no:'bladpersille'}, note:{en:'chopped; optional, and some grills use none', no:'hakket; valgfritt, og noen griller bruker den ikke'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, note:{en:'coarsely cracked, and more than you think', no:'grovknust, og mer enn du tror'}, scale:'none'},
    {q:4, u:'', n:{en:'wooden skewers', no:'trespidd'}, note:{en:'soaked in water for half an hour so they do not burn through', no:'lagt i vann en halvtime så de ikke brenner av'}, round:'half'},
  ]}],
  steps:[
    {en:'Light a charcoal or wood fire early and let it burn right down, until the coals are grey and you can hold a hand over them for three seconds. Bombette are cooked over embers, never over flame.',
     no:'Tenn et bål av grillkull eller ved i god tid og la det brenne helt ned, til kullene er grå og du kan holde en hånd over dem i tre sekunder. Bombette grilles over glør, aldri over åpen flamme.'},
    {en:'Lay each slice of pork between two sheets of baking paper and beat it thin and even with a rolling pin, until it is roughly the size of your palm.',
     no:'Legg hver svineskive mellom to ark bakepapir og bank den tynn og jevn med en kjevle, til den er omtrent på størrelse med håndflaten.'},
    {en:'Cut the cheese into batons short enough to sit well inside the slice with a clear margin of a finger on every side.',
     no:'Skjær osten i staver som er korte nok til å ligge godt innenfor skiven med en fingerbredds margin på alle kanter.'},
    {en:'Season the upper face of each slice with salt, pepper and a pinch of parsley. The outside gets nothing; salt on the surface draws water out and stops it browning.',
     no:'Krydre oversiden av hver skive med salt, pepper og en klype persille. Utsiden får ingenting, for salt på overflaten trekker ut vann og hindrer at kjøttet brunes.'},
    {en:'Lay a baton of cheese across the near end, fold both long sides in over it, and roll the slice up tight away from you so the cheese is sealed in on all four sides.',
     no:'Legg en oststav på tvers i den nærmeste enden, brett begge langsidene inn over den, og rull skiven stramt fra deg, så osten er lukket inne på alle fire sider.'},
    {en:'Squeeze each roll gently in your fist to close the seam, and set it aside seam down.',
     no:'Klem hver rull forsiktig i neven for å lukke skjøten, og sett den til side med skjøten ned.'},
    {en:'Thread four rolls onto each skewer through the seam, close enough to touch so they hold one another shut.',
     no:'Tre fire ruller på hvert spidd gjennom skjøten, tett nok til at de berører hverandre og holder hverandre lukket.'},
    {en:'Lay the skewers on the grill over the embers and cook for 12 to 15 minutes, turning them a quarter turn every three minutes so all four faces colour.',
     no:'Legg spiddene på grillen over glørne og stek i 12 til 15 minutter. Vri dem en kvart omdreining hvert tredje minutt, så alle fire sider får farge.'},
    {en:'Move any skewer that flares to a cooler corner of the grill and never press down on the rolls. Dripping fat is what lights the flame, and pressing squeezes out the fat that is keeping the meat moist.',
     no:'Flytt spiddet til et kaldere hjørne av grillen hvis fettet tar fyr, og trykk aldri ned på rullene. Fett som drypper, er det som tenner flammen, og trykker du, presser du ut det fettet som holder kjøttet saftig.'},
    {en:'Take them off when the outside is deeply browned and a roll feels firm when you press the end of the skewer, and rest them for 3 minutes so the molten cheese thickens enough to stay put.',
     no:'Ta dem av når utsiden er godt brunet og en rull kjennes fast når du trykker på enden av spiddet, og la dem hvile i 3 minutter, så den smeltede osten tykner nok til å bli der den er.'},
    {en:'Eat them hot, off the skewer and with your fingers, with bread and nothing else on the plate.',
     no:'Spis dem varme, rett fra spiddet og med fingrene, med brød og ingenting annet på tallerkenen.'},
  ],
  notes:[
    {title:{en:'Why the neck and no other cut', no:'Derfor nakken og ingen andre stykker'},
     body:{en:'Pork neck is the most marbled cut on the animal, which is why Puglia cures it as capocollo and why it is the only one that works here. The fat sitting inside the muscle melts at grill temperature and runs through the slice, so a piece thin enough to cook in a quarter of an hour is still moist at the end of it. A slice of loin has almost no internal fat and will be dry before the cheese has melted.',
           no:'Svinenakke er det mest marmorerte stykket på dyret, og derfor spekes den i Puglia som capocollo, og derfor er det bare den som fungerer her. Fettet som ligger inne i muskelen, smelter i grillvarmen og renner gjennom skiven, slik at et stykke som er tynt nok til å bli ferdig på et kvarter, fortsatt er saftig når kvarteret er omme. En skive av kotelettkammen har nesten ikke fett inni seg og er tørr lenge før osten har smeltet.'}},
    {title:{en:'Seal the cheese in', no:'Lukk osten inne'},
     body:{en:'Caciocavallo is a stretched-curd cheese and turns liquid at about the temperature the outside of the roll reaches. Liquid cheese finds any opening, and once it is out it burns on the bars and takes the fat with it, leaving the inside dry. A margin of a finger all round, both long sides folded in before the roll starts, and the seam turned inwards on the skewer are what keep it where it belongs.',
           no:'Caciocavallo er en ost av strukket ostemasse og blir flytende omtrent ved den temperaturen utsiden av rullen når. Flytende ost finner enhver åpning, og når den først er ute, brenner den fast på risten og tar fettet med seg, mens innsiden blir tørr. En fingerbredds margin hele veien rundt, begge langsider brettet inn før rullingen begynner, og skjøten vendt innover på spiddet holder den der den skal være.'}},
    {title:{en:'Embers, not flame', no:'Glør, ikke flamme'},
     body:{en:'A flame is hotter at one point and much cooler a hand’s width away, so meat over it chars in patches and stays raw between them. Embers give even radiant heat across the whole grill, which is what a roll needs if the outside is to brown in the same fifteen minutes that the cheese takes to melt through. That is what the wood grill behind the butcher’s shop provides, and it is worth waiting for the fire to die down.',
           no:'En flamme er varmest på ett punkt og langt kaldere en håndsbredd unna, så kjøtt over den blir svidd flekkvis og rått imellom. Glør gir jevn strålevarme over hele grillen, og det er nettopp det en rull trenger hvis utsiden skal brunes i løpet av de samme femten minuttene som osten bruker på å smelte gjennom. Det er dette vedgrillen bak slakterbutikken gir, og det er verdt å vente til bålet har brent ned.'}},
  ],
  variations:[
    {title:{en:'Rolled in breadcrumbs', no:'Rullet i brødrasp'},
     body:{en:'Many of the grills of Cisternino roll the finished bombette in dry breadcrumbs before they go on the fire. The crumb browns fast and shields the meat, so the roll takes a few minutes longer and comes out with a crust. Brush it with a little oil first or the crumb falls off in the basket.',
           no:'Mange av grillene i Cisternino ruller de ferdige bombettene i tørt brødrasp før de går på bålet. Raspen brunes fort og skjermer kjøttet, så rullen trenger noen minutter mer og kommer ut med skorpe. Pensle den med litt olje først, ellers faller raspen av i kurven.'}},
    {title:{en:'What goes in beside the cheese', no:'Hva som går i ved siden av osten'},
     body:{en:'A slice of pancetta laid on the meat before the cheese adds salt and more fat, and works well with a lean piece. Some grills add a leaf of basil or a sliver of sun-dried tomato. Nothing wet goes in, and nothing that needs longer than the pork to cook.',
           no:'En skive pancetta lagt på kjøttet før osten gir salt og mer fett, og passer godt til et magert stykke. Noen griller legger i et basilikumblad eller en strimmel soltørket tomat. Ingenting vått går i, og ingenting som trenger lengre tid enn svinekjøttet.'}},
    {title:{en:'Without a grill', no:'Uten grill'},
     body:{en:'In a very hot oven, 240 °C with the tray high up, the rolls take about 18 minutes and want turning twice. Sear them first in a dry heavy pan so the outside colours, since an oven alone leaves them grey. It is not the same dish, but it is a good weeknight one.',
           no:'I en svært varm ovn på 240 °C, med brettet høyt oppe, trenger rullene omkring 18 minutter og bør snus to ganger. Brun dem først i en tørr, tung panne så utsiden får farge, for ovnen alene gjør dem grå. Det er ikke den samme retten, men den er god på en hverdag.'}},
  ],
},

{
  id:'panzerotti', dish:'Panzerotti', course:'antipasto', lesson:3, serves:4,
  time:{prep:120, cook:15}, hero:'panzerotti', tags:['fried','street food','tomato','mozzarella'],
  title:{en:'Panzerotti baresi', no:'Panzerotti baresi'},
  blurb:{en:'Pockets of yeasted dough folded round tomato and mozzarella and deep-fried until they puff. Fried, never baked.',
         no:'Lommer av gjærdeig som brettes rundt tomat og mozzarella og frityrstekes til de blåser seg opp. De stekes i olje, aldri i ovn.'},
  heroCaption:{en:'Panzerotti on a Puglian stand, fried to order and kept in a hot counter, sold to be eaten standing up.',
               no:'Panzerotti på en pugliesisk stand, stekt på bestilling og holdt varme i disken. De spises stående.'},
  wines:['Rosato del Salento'],
  headnote:{
    en:'<p>A panzerotto is a small pocket of yeasted dough folded round tomato and mozzarella and fried in deep oil. Bari sells them from the <em>friggitorie</em> and over the counter of every pizzeria, and the whole point is that they are fried rather than baked. Baked, the same parcel is a small calzone, and anyone from Bari will say so.</p>'
      + '<p>Frying is what builds the shell. Water in a wet dough dropped into oil at 175 °C turns to steam almost at once, and the steam has nowhere to go except the space between the two layers of dough, so the pocket inflates and the outside sets in blisters before it has time to take up any fat. An oven dries the same dough slowly, and it never lifts.</p>'
      + '<p>One thing has to be right, and it is a dry filling. Mozzarella and tinned tomato are mostly water, and water shut inside a pocket at frying temperature becomes steam faster than a pressed seam can hold. Drain both hard, fill at the last moment and press the air out before you close it, or the panzerotto splits and empties itself into the pan.</p>',
    no:'<p>En panzerotto er en liten lomme av gjærdeig som brettes rundt tomat og mozzarella og stekes i rikelig olje. Bari selger dem fra <em>friggitorie</em> og over disken i hver eneste pizzeria, og hele poenget er at de stekes i olje og ikke i ovn. Bakt i ovn blir den samme pakken en liten calzone, og det vil enhver bareser si deg.</p>'
      + '<p>Frityren bygger skallet. Vannet i en våt deig som slippes i olje på 175 °C, blir til damp nesten med en gang, og dampen har ingen annen vei å gå enn inn i rommet mellom de to deiglagene. Lommen blåser seg opp, og utsiden setter seg i blemmer før den rekker å suge til seg fett. En ovn tørker den samme deigen langsomt, og da løfter den seg aldri.</p>'
      + '<p>Én ting er avgjørende, og det er at fyllet er tørt. Mozzarella og hermetisk tomat består for det meste av vann, og vann som er lukket inne i en lomme i frityrvarme, blir damp raskere enn en sammenklemt kant klarer å holde. La begge deler renne godt av, fyll i siste liten, og press ut luften før du lukker, ellers sprekker panzerottoen og tømmer seg i pannen.</p>'},
  ingredients:[
    { group:{en:'For the dough', no:'Til deigen'}, items:[
      {q:500, u:'g', n:{en:'‘00’ flour', no:'mel type 00'}},
      {q:300, u:'ml', n:{en:'water', no:'vann'}, note:{en:'lukewarm', no:'lunkent'}},
      {q:7,   u:'g', n:{en:'dried yeast', no:'tørrgjær'}, note:{en:'or three times that much fresh yeast', no:'eller tre ganger så mye fersk gjær'}},
      {q:10,  u:'g', n:{en:'salt', no:'salt'}},
      {q:20,  u:'ml', n:{en:'extra-virgin olive oil', no:'extra virgin olivenolje'}},
    ]},
    { group:{en:'For the filling', no:'Til fyllet'}, items:[
      {q:250, u:'g', n:{en:'mozzarella', no:'mozzarella'}, note:{en:'fior di latte, diced and left on a cloth for an hour; buffalo mozzarella carries far too much water', no:'fior di latte, skåret i terninger og lagt på et klede en time; bøffelmozzarella har altfor mye vann i seg'}},
      {q:200, u:'g', n:{en:'peeled plum tomatoes', no:'hermetiske plommetomater'}, note:{en:'drained hard and crushed by hand, not a smooth passata', no:'godt avrent og most med hendene, ikke en glatt passata'}},
      {u:'', n:{en:'dried oregano', no:'tørket oregano'}, scale:'none'},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'To fry', no:'Til steking'}, items:[
      {u:'', n:{en:'sunflower or peanut oil for deep frying', no:'solsikke- eller peanøttolje til frityr'}, note:{en:'enough for the pockets to float; olive oil smokes below the temperature you need', no:'nok til at lommene flyter; olivenolje ryker under den temperaturen du trenger'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Whisk the yeast into the lukewarm water, pour it into the flour and work it into a soft dough.',
     no:'Visp gjæren ut i det lunkne vannet, hell det i melet, og arbeid det til en myk deig.'},
    {en:'Add the salt and the oil and knead for 10 minutes, until the dough is smooth, elastic and only just tacky.',
     no:'Ha i saltet og oljen og elt i 10 minutter, til deigen er glatt, elastisk og bare så vidt klebrig.'},
    {en:'Cover it and leave it to rise for about 90 minutes, until it has doubled.',
     no:'Dekk den til og la den heve i omkring 90 minutter, til den er doblet.'},
    {en:'Meanwhile spread the diced mozzarella on a cloth and leave it to drain, and crush the drained tomatoes with your hands, seasoning them with salt and oregano.',
     no:'Bre imens mozzarellaterningene utover et klede og la dem renne av. Mos de avrente tomatene med hendene, og smak dem til med salt og oregano.'},
    {en:'Divide the dough into pieces the size of an egg and roll each one out into a thin disc, about 3 mm, on a lightly floured board.',
     no:'Del deigen i biter på størrelse med et egg, og kjevle hver av dem ut til en tynn leiv på omkring 3 mm på et lett melet brett.'},
    {en:'Put a spoonful of tomato and a few cubes of cheese on one half of each disc, leaving a clear border of 2 cm all round the edge.',
     no:'Legg en skje tomat og noen ostebiter på den ene halvdelen av hver leiv, og la det stå en tydelig kant på 2 cm hele veien rundt.'},
    {en:'Fold the disc over, press the air out from the filling towards the rim, and seal the edge by pressing it with a fork or rolling it back on itself.',
     no:'Brett leiven over, press luften ut fra fyllet mot kanten, og lukk kanten ved å trykke den sammen med en gaffel eller rulle den tilbake over seg selv.'},
    {en:'Heat the frying oil to 175 °C. A scrap of dough dropped in should rise at once and colour in under a minute.',
     no:'Varm frityroljen til 175 °C. En deigbit som slippes i, skal stige opp med en gang og få farge på under et minutt.'},
    {en:'Fry two or three at a time so the oil stays hot, turning them once, for about 3 minutes in all, until they are puffed and deep gold.',
     no:'Stek to eller tre om gangen så oljen holder varmen. Snu dem én gang, og gi dem omkring 3 minutter til sammen, til de har blåst seg opp og er dypt gyllne.'},
    {en:'Lift them onto kitchen paper and leave them there for a minute. The filling comes out of the oil far hotter than the crust and will burn a mouth.',
     no:'Løft dem over på kjøkkenpapir og la dem ligge der et minutt. Fyllet kommer ut av oljen mye varmere enn skorpen og svir munnen.'},
    {en:'Eat them hot, in your hand. They are best within ten minutes and are never worth reheating.',
     no:'Spis dem varme, i hånden. De er best i løpet av ti minutter, og det er aldri verdt å varme dem opp igjen.'},
  ],
  notes:[
    {title:{en:'Why frying and not baking', no:'Derfor frityr og ikke ovn'},
     body:{en:'Oil carries heat into a surface far faster than air does. The dough seals and colours within seconds, and the water trapped inside flashes to steam that has nowhere to escape, so the two layers separate and the pocket balloons. That is where the hollow, blistered shell comes from. An oven takes minutes to do the same work, and by then the steam has drifted out through the dough and the parcel is simply a small baked calzone.',
           no:'Olje fører varme inn i en overflate langt raskere enn luft gjør. Deigen lukker seg og får farge i løpet av sekunder, og vannet som er stengt inne, går over til damp som ikke kommer noen vei. Da skiller de to lagene seg, og lommen blåser seg opp. Derfra kommer det hule skallet med blemmer. En ovn bruker minutter på den samme jobben, og da har dampen for lengst sivet ut gjennom deigen, og pakken er ikke annet enn en liten bakt calzone.'}},
    {title:{en:'The filling has to be dry', no:'Fyllet må være tørt'},
     body:{en:'Fresh mozzarella is more than half water and tinned tomato is mostly juice. Sealed in and heated to frying temperature, that water becomes steam far faster than a pressed seam can hold, and the panzerotto bursts, floods the pan and spits. Dice the cheese and leave it on a cloth for an hour, drain the tomato in a sieve until it stops dripping, and put the two together only as each pocket is filled.',
           no:'Fersk mozzarella er mer enn halvparten vann, og hermetisk tomat er stort sett saft. Lukkes det inne og varmes til frityrtemperatur, blir vannet damp langt raskere enn en sammenklemt kant kan holde, og panzerottoen sprekker, oversvømmer pannen og spruter. Skjær osten i terninger og la den ligge på et klede en time, la tomaten renne av i en sil til den slutter å dryppe, og sett de to sammen først idet hver lomme fylles.'}},
    {title:{en:'The temperature of the oil', no:'Temperaturen på oljen'},
     body:{en:'Below about 165 °C the dough absorbs oil before it can seal, and the panzerotto comes out heavy and greasy. Above about 185 °C the outside is dark before the middle is hot and the cheese has not melted. Two or three at a time keeps the oil within that window, since each cold pocket takes the temperature down with it.',
           no:'Under omtrent 165 °C suger deigen til seg olje før den rekker å lukke seg, og panzerottoen blir tung og fet. Over omtrent 185 °C er utsiden mørk før midten er varm, og osten har ikke smeltet. To eller tre om gangen holder oljen innenfor det vinduet, siden hver kalde lomme trekker temperaturen ned med seg.'}},
  ],
  variations:[
    {title:{en:'Other fillings', no:'Andre fyll'},
     body:{en:'Tomato and mozzarella is the one Bari means by the word, but ricotta with salami, onion softened in oil, or mozzarella with a slice of cooked ham are all sold from the same counters. The rule is the same for every one of them: nothing wet and nothing that needs cooking, because three minutes in the oil is all it gets.',
           no:'Tomat og mozzarella er det Bari mener med ordet, men ricotta med salami, løk som er myknet i olje, eller mozzarella med en skive kokt skinke selges fra de samme diskene. Regelen er den samme for dem alle. Ingenting vått, og ingenting som må gjennomstekes, for tre minutter i oljen er alt det får.'}},
    {title:{en:'Panzerotti al forno', no:'Panzerotti al forno'},
     body:{en:'The same parcels brushed with oil and baked at 220 °C for about 15 minutes are a real thing and are sold as such, but they are a different food: bread round a filling rather than a hollow fried shell. Puglia keeps the two apart by name and so should you.',
           no:'De samme pakkene, penslet med olje og stekt på 220 °C i omkring 15 minutter, finnes og selges slik, men det er en annen rett. Da får du brød rundt et fyll og ikke et hult, frityrstekt skall. Puglia holder de to fra hverandre med navnet, og det bør du også gjøre.'}},
    {title:{en:'Panzerottini', no:'Panzerottini'},
     body:{en:'Half the size, made from discs the width of a hand, they are what turns up on a tray at a party and at every fair in the region. They fry in about 2 minutes and need the oil a little cooler, since there is less inside to heat through.',
           no:'Panzerottini er halvparten så store og lages av leiver på bredde med en hånd. Det er dem som kommer på fat i selskaper og på hvert eneste marked i regionen. De stekes på omkring 2 minutter og vil ha litt kjøligere olje, siden det er mindre inni som skal varmes gjennom.'}},
  ],
},

];
