// Sardegna recipes. Bilingual in one file: the quantities are written once so English and Norwegian
// cannot drift apart. Contract: docs/recipe-format.md. Checked by tools/recipecheck.py. Never narrated.
// Everything here follows the Sardinian food reading (content/sardegna.js, lesson 3): a pastoral kitchen,
// not a maritime one. Bread that keeps for a year, a pig cooked beside a fire and rested on myrtle, pasta
// of semolina and water without egg, and a cheese course that runs from the antipasto to the dessert.
// Pane carasau itself is bought, not baked: see the pane frattau headnote for why.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-88'] = [

{
  id:'porceddu', dish:'Porceddu', course:'secondo', lesson:3, serves:6, time:{prep:30, cook:200},
  hero:'porceddu', tags:['pork','roast','oven','myrtle'],
  title:{en:'Porceddu, the home version', no:'Porceddu, hjemmeversjonen'},
  blurb:{en:'The real thing is a whole suckling pig beside an open fire. This is a shoulder in an oven, seasoned with nothing but salt and rested on myrtle, which is as close as a kitchen gets.',
         no:'Den ekte varianten er en hel pattegris ved åpen ild. Dette er en bog i stekeovn, krydret med bare salt og hvilt på myrt, og nærmere kommer man ikke på et kjøkken.'},
  heroCaption:{en:'Porceddu as it is actually cooked: split, spitted on a green pole and set beside the fire, not over it. No oven does this.',
               no:'Porceddu slik den faktisk lages. Grisen flekkes, settes på en grønn stang og plasseres ved siden av bålet, ikke over det. Ingen stekeovn gjør dette.'},
  wines:['Cannonau di Sardegna'],
  headnote:{
    en:'<p>Porceddu proper is a suckling pig of four to six kilos, split, spitted on a green pole and set beside a fire of oak or juniper rather than over it, so that it cooks for hours in the radiated heat while its own fat bastes it. There is no marinade and no sauce. The seasoning is salt, and at the end a scattering of <strong>myrtle</strong>: in the old practice the cooked pig was laid on a bed of myrtle branches and covered with more, so that it took the aroma up as it rested.</p>'
      + '<p>A domestic oven does none of that. It has no fire, so there is no smoke and no resin off the wood; the heat arrives from every side instead of from one; and it will not take an animal. So this is not porceddu. It is what a kitchen can honestly borrow from it, and three things do travel: salt as the only seasoning, heat slow enough that the fat renders before the skin sets, and the rest on myrtle, which costs nothing and carries most of the aroma.</p>'
      + '<p>Two temperatures do two different jobs. Hours at 150 °C melt the fat under the skin and turn the collagen in the rind to gelatine. A short spell at 240 °C then flashes the water left in the rind to steam and blows it into blisters. Run them together and you get leather. The rind also has to be dry going in, which is why the meat sits uncovered in the fridge overnight and is salted only at the very end.</p>',
    no:'<p>Ekte porceddu er en pattegris på fire til seks kilo. Den flekkes, settes på en grønn stang og plasseres ved siden av et bål av eik eller einer, ikke over det, og steker i strålevarmen i flere timer mens fettet fra dyret drypper ned over den. Verken marinade eller saus hører med. Krydderet er salt, og til slutt <strong>myrt</strong>: etter gammel skikk ble den ferdige grisen lagt på en seng av myrtegrener og dekket med flere, slik at den trakk til seg aromaen mens den hvilte.</p>'
      + '<p>En vanlig stekeovn gjør ingenting av dette. Den har ingen ild, så røyken og harpiksen fra veden uteblir, varmen kommer fra alle kanter i stedet for fra én, og et helt dyr får uansett ikke plass. Dette er altså ikke porceddu, men det nærmeste et kjøkken ærlig kan komme. Tre ting lar seg overføre: salt som eneste krydder, en varme langsom nok til at fettet smelter ut før svoren stivner, og hvilen på myrt, som ikke koster noe og står for mesteparten av duften.</p>'
      + '<p>To temperaturer gjør to forskjellige jobber. Timene på 150 °C smelter fettet under svoren og gjør bindevevet i den om til gelatin. Den korte perioden på 240 °C koker vannet som er igjen i svoren, til damp og blåser den opp i blemmer. Slår du dem sammen, får du lær. Svoren må dessuten være tørr når den går inn, og derfor står kjøttet utildekket i kjøleskapet natten over og saltes først helt til slutt.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:2.5, u:'kg', n:{en:'shoulder of suckling pig, skin on and bone in', no:'bog av pattegris, med svor og bein'},
     note:{en:'ask the butcher for a piece off an animal of four to six kilos; a pork shoulder with the rind left on works too, and needs longer',
           no:'be slakteren om et stykke fra et dyr på fire til seks kilo. En svinebog med svoren på går også, men trenger lengre tid'}},
    {u:'', n:{en:'coarse salt', no:'grovt salt'}, scale:'none'},
    {q:60, u:'g', n:{en:'myrtle branches', no:'myrtegrener'},
     note:{en:'fresh; a florist or a garden centre will have myrtle. Juniper is the honest stand-in, and juniper is half of what the island burns anyway',
           no:'ferske. Blomsterhandler eller hagesenter har myrt. Einer er den ærlige erstatningen, og einer er halvparten av det øya fyrer med uansett'}},
  ]}],
  steps:[
    {en:'Unwrap the meat the night before, pat the skin dry and leave it uncovered on a rack in the fridge overnight. Dry skin is the only route to skin that shatters.',
     no:'Pakk ut kjøttet kvelden før, tørk av svoren, og la stykket ligge utildekket på rist i kjøleskapet natten over. Tørr svor er den eneste veien til en svor som knuser som glass.'},
    {en:'Take it out an hour before it goes in and let it come to room temperature. A cold centre keeps the whole piece in the oven long after the skin is ready.',
     no:'Ta det ut en time før det skal i ovnen, og la det bli romtemperert. En kald kjerne holder hele stykket i ovnen lenge etter at svoren er ferdig.'},
    {en:'Heat the oven to 150 °C without the fan. Do not score the skin: porceddu rind is left whole, and every cut is a place for the fat to escape.',
     no:'Varm ovnen til 150 °C uten vifte. Ikke skjær ruter i svoren. Svoren på en porceddu får ligge hel, og hvert snitt er et sted fettet kan renne ut.'},
    {en:'Set the meat skin up on a rack over a deep tray, so that air reaches it from every side and the fat drips away instead of frying the underside.',
     no:'Sett kjøttet med svoren opp på en rist over en dyp langpanne, slik at luften når det fra alle kanter og fettet drypper av i stedet for å steke undersiden.'},
    {en:'Roast for about three hours, until a skewer meets no resistance at the thickest part and the fat in the tray has run clear.',
     no:'Stek i omtrent tre timer, til en kjøttnål går uten motstand gjennom det tykkeste partiet og fettet i langpannen er klart.'},
    {en:'Leave the door shut and do not baste. The fat under the skin is already doing that, and every opening takes fifty degrees off the oven.',
     no:'La døren være lukket, og ikke øs over. Fettet under svoren gjør den jobben allerede, og hver åpning tar femti grader av ovnen.'},
    {en:'Pour the rendered fat off the tray and keep it. It is worth more than most of what comes in a jar.',
     no:'Hell det smeltede fettet av langpannen og ta vare på det. Det er verdt mer enn det meste som kommer på glass.'},
    {en:'Turn the oven up to 240 °C, then rub coarse salt over the skin with the flat of your hand. Salted any earlier, it would have drawn water to the surface and kept the rind soft.',
     no:'Skru ovnen opp til 240 °C, og gni grovt salt over svoren med flat hånd. Hadde du saltet tidligere, ville saltet trukket vann ut til overflaten og holdt svoren myk.'},
    {en:'Give it fifteen to twenty minutes high in the oven, watching it the whole time, until the rind blisters right across and taps hollow.',
     no:'Gi det femten til tjue minutter høyt i ovnen mens du følger med hele tiden, til svoren blemmer over hele flaten og høres hul ut når du banker på den.'},
    {en:'Lay half the myrtle on a warm dish, put the meat on it, cover it with the rest and leave it to rest for twenty minutes.',
     no:'Legg halvparten av myrten på et varmt fat, sett kjøttet oppå, dekk det med resten, og la det hvile i tjue minutter.'},
    {en:'Carve it into pieces with a share of skin on each, and bring it to the table with the myrtle still under it. There is no sauce, and the dish does not want one.',
     no:'Skjær det i biter med litt svor på hver, og sett det på bordet med myrten fortsatt under. Det finnes ingen saus, og retten trenger ingen.'},
  ],
  notes:[
    {title:{en:'Why the salt goes on last', no:'Derfor saltes svoren til slutt'},
     body:{en:'Salt draws water. Put on raw rind hours ahead, it pulls moisture up to the surface and holds it there, and wet rind steams instead of blistering. Put on dry rind at the end, it seasons and does nothing else. The same logic explains the night in the fridge: cold dry air removes water from the skin that no oven can drive out in twenty minutes.',
           no:'Salt trekker vann. Legger du det på rå svor timer i forveien, henter det fuktighet opp til overflaten og holder den der, og våt svor damper i stedet for å blemme. Legger du det på tørr svor helt til slutt, krydrer det, og gjør ikke annet. Den samme logikken forklarer natten i kjøleskapet: kald og tørr luft henter ut vann av svoren som ingen ovn rekker å drive ut på tjue minutter.'}},
    {title:{en:'What the fire gives that the oven cannot', no:'Det bålet gir, og ovnen ikke kan gi'},
     body:{en:'A fire radiates from one side only, so the pig turns and every surface dries between passes; it gives smoke and resin off oak and juniper; and fat falls into the embers. An oven gives even heat and no smoke at all. The rest on myrtle is the part of that aroma you can have for nothing, so do it properly — hot meat under a closed lid of branches for twenty minutes, not a sprig laid on the plate.',
           no:'Et bål stråler fra én side, slik at grisen snur seg og hver flate tørker mellom hver runde. Det gir røyk og harpiks fra eik og einer, og fett som faller ned i glørne. Ovnen gir jevn varme og ingen røyk. Hvilen på myrt er den delen av duften du kan få gratis, så gjør den ordentlig: varmt kjøtt under et lukket lag grener i tjue minutter, ikke en kvist lagt på tallerkenen.'}},
    {title:{en:'Salt, and nothing else', no:'Salt, og ingenting annet'},
     body:{en:'The reading is blunt about it: no marinade and no sauce. Rosemary, garlic, fennel and honey all belong to other Italian roasts. A suckling pig has plenty of its own, and whoever seasons it heavily is really saying they do not trust the animal.',
           no:'Lesteksten er tydelig: verken marinade eller saus hører med. Rosmarin, hvitløk, fennikel og honning hører til andre italienske steker. En pattegris har nok av sitt eget, og den som krydrer den kraftig, stoler egentlig ikke på råvaren.'}},
  ],
  variations:[
    {title:{en:'A whole piglet, if your oven takes one', no:'Hel pattegris, hvis ovnen tar den'},
     body:{en:'A butcher will order a suckling pig of four to six kilos. Split it flat along the backbone, roast it skin up at the same two temperatures and allow half as long again. It is still an oven, but the shape is right and it feeds a party.',
           no:'Slakteren kan bestille en pattegris på fire til seks kilo. Flekk den langs ryggraden, stek den med svoren opp på de samme to temperaturene, og regn halvannen gang så lang tid. Det er fortsatt en ovn, men formen stemmer, og den metter et selskap.'}},
    {title:{en:'Juniper for myrtle', no:'Einer i stedet for myrt'},
     body:{en:'The fire itself is oak or juniper, so juniper is not a compromise but the other half of the tradition. It grows everywhere in Norway, and a handful of branches under the resting meat gives resin without the sweetness myrtle carries.',
           no:'Bålet er av eik eller einer, så einer er ingen nødløsning, men den andre halvdelen av tradisjonen. Einer vokser overalt i Norge, og en neve grener under kjøttet mens det hviler, gir harpiks uten sødmen myrten har.'}},
    {title:{en:'The rendered fat', no:'Det smeltede fettet'},
     body:{en:'Keep it in the fridge. Potatoes roasted in it beat anything done in oil, and on Sardinia it goes straight onto bread with a scrape of salt.',
           no:'Ta vare på det i kjøleskapet. Poteter som er stekt i det, slår alt som er stekt i olje, og på Sardinia går det rett på brødet med litt salt.'}},
  ],
},

{
  id:'pane-frattau', dish:'Pane frattau', course:'primo', lesson:3, serves:4, time:{prep:20, cook:30},
  hero:'frattau', tags:['bread','egg','tomato','pecorino'],
  title:{en:'Pane frattau', no:'Pane frattau'},
  blurb:{en:'What a Sardinian kitchen actually does with a sheet of carasau it bought: dip it in hot broth, layer it with tomato and pecorino, and drop a poached egg on top.',
         no:'Slik et sardisk kjøkken faktisk bruker en plate carasau det har kjøpt. Dypp den i varm kraft, legg den lagvis med tomat og pecorino, og legg et posjert egg øverst.'},
  heroCaption:{en:'Pane frattau: softened carasau, tomato, grated pecorino and a poached egg. The yolk is the sauce.',
               no:'Pane frattau: oppbløtt carasau, tomat, revet pecorino og et posjert egg. Plommen er sausen.'},
  wines:['Cannonau di Sardegna'],
  headnote:{
    en:'<p>This recipe starts at the shop, and that is deliberate. <strong>Pane carasau</strong> is durum semolina worked into a disc and baked until it puffs into a balloon; the baker splits the balloon into two paper-thin sheets and bakes each again until it is crisp, which is exactly what <em>carasau</em> means. A baker who splits a scalding balloon in one movement, in an oven far hotter than any kitchen oven, knows a trade. A home version is a poor copy of something sold everywhere for very little, so buy the sheets. They keep for months, which was always the point: shepherds away from the village carried stacks of them.</p>'
      + '<p>Pane frattau is what the island does with them, and it is the closest thing Sardinia has to a national dish. Sheets are dipped in hot broth until they turn pliable, layered with tomato sauce and grated pecorino like a lasagne, and finished with a poached egg. Nothing is baked and nothing is browned. The plate is built in a minute and eaten at once.</p>'
      + '<p>The dip is the only thing that has to be right. Carasau is bone dry and drinks fast. Five seconds in broth held just below a simmer makes a sheet flexible and leaves it some spring; twenty seconds makes paste. Warm the plates, have the sauce, the cheese and the eggs ready before the first sheet goes near the broth, and do not expect to build four plates at leisure.</p>',
    no:'<p>Denne oppskriften begynner i butikken, og det er med vilje. <strong>Pane carasau</strong> er durumsemule arbeidet til en leiv og stekt til den blåser seg opp som en ballong. Bakeren deler ballongen i to papirtynne plater og steker hver av dem en gang til, til de er sprø, og nettopp det betyr <em>carasau</em>. En baker som deler en glovarm ballong i én bevegelse, i en ovn langt varmere enn noen kjøkkenovn, kan faget sitt. En hjemmelaget utgave blir en blek kopi av noe som selges overalt for nesten ingenting, så kjøp platene. De holder seg i månedsvis, og det var alltid poenget, for gjeterne som var borte fra landsbyen, bar med seg stabler av dem.</p>'
      + '<p>Pane frattau er det øya gjør med dem, og det nærmeste Sardinia kommer en nasjonalrett. Platene dyppes i varm kraft til de blir bøyelige, legges lagvis med tomatsaus og revet pecorino som en lasagne, og toppes med et posjert egg. Ingenting stekes, og ingenting brunes. Tallerkenen bygges på et minutt og spises med en gang.</p>'
      + '<p>Dyppet er det eneste som må sitte. Carasau er knusktørt og drikker fort. Fem sekunder i kraft som holdes like under kokepunktet, gjør platen bøyelig og lar den beholde litt spenst, mens tjue sekunder gjør den til grøt. Varm tallerkenene, ha sausen, osten og eggene klare før den første platen kommer i nærheten av kraften, og regn ikke med å bygge fire tallerkener i ro og mak.</p>'},
  ingredients:[
    { group:{en:'For the tomato', no:'Til tomatsausen'}, items:[
      {q:400, u:'g', n:{en:'peeled plum tomatoes', no:'hermetiske plommetomater'},
       note:{en:'crushed by hand; a passata will do at a pinch', no:'most med hendene. En passata går i nødsfall'}},
      {q:30, u:'ml', n:{en:'olive oil', no:'olivenolje'}},
      {q:1, u:'', n:{en:'clove of garlic', no:'hvitløksfedd'}, round:'half'},
      {u:'', n:{en:'a few basil leaves', no:'noen basilikumblader'}, scale:'none'},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'To build', no:'Til oppbyggingen'}, items:[
      {q:8, u:'', n:{en:'sheets of pane carasau', no:'plater pane carasau'}, round:'half',
       note:{en:'bought; Italian shops sell it as carta da musica', no:'kjøpt. Italienske butikker selger det som carta da musica'}},
      {q:1, u:'l', n:{en:'mutton or lamb broth', no:'kraft av sau eller lam'},
       note:{en:'the island uses sheep broth; a light chicken broth is the everyday substitute, and a stock cube is not',
             no:'øya bruker saukraft, og en lys hønsekraft er den vanlige erstatningen. En buljongterning er det ikke'}},
      {q:4, u:'', n:{en:'eggs', no:'egg'}, round:'half',
       note:{en:'as fresh as you can get, or they will not hold together in the water', no:'så ferske du får tak i, ellers holder de ikke sammen i vannet'}},
      {q:100, u:'g', n:{en:'Pecorino Sardo', no:'Pecorino Sardo'},
       note:{en:'the matured kind, finely grated. Pecorino Romano is saltier, so go easy on the salt in the sauce',
             no:'den lagrede typen, finrevet. Pecorino Romano er saltere, så ta det med ro med saltet i sausen'}},
    ]},
  ],
  steps:[
    {en:'Soften the garlic in the oil over low heat until it smells but has taken no colour, then lift it out.',
     no:'La hvitløken mykne i oljen på svak varme til den dufter, men ikke har fått farge, og løft den så ut.'},
    {en:'Crush the tomatoes into the pan, salt them, drop in the basil and simmer for about twenty minutes, until the sauce is thick enough to sit on a spoon.',
     no:'Mos tomatene ned i pannen, salt dem, legg i basilikumen, og la sausen småkoke i omtrent tjue minutter, til den er tykk nok til å bli liggende på en skje.'},
    {en:'Heat the broth in a wide pan and hold it just below a simmer. Broth at a rolling boil turns the bread to paste before you can lift it out.',
     no:'Varm kraften i en vid panne og hold den like under kokepunktet. Kraft som fosskoker, gjør brødet til grøt før du rekker å løfte det opp.'},
    {en:'Warm the plates properly. This dish loses its heat faster than anything else on the island.',
     no:'Varm tallerkenene skikkelig. Denne retten mister varmen fortere enn noe annet på øya.'},
    {en:'Poach the eggs in barely trembling salted water for three minutes, until the white has set and the yolk still runs, then lift them onto a cloth.',
     no:'Posjer eggene i knapt skjelvende, saltet vann i tre minutter, til hviten har stivnet og plommen fortsatt renner, og løft dem så over på et klede.'},
    {en:'Break the sheets into pieces that fit the plate. They snap where they want to, and that is fine.',
     no:'Brekk platene i biter som passer tallerkenen. De knekker der de selv vil, og det gjør ingenting.'},
    {en:'Dip a piece in the hot broth for about five seconds — count it out — and lay it on the plate while it still has some spring.',
     no:'Dypp en bit i den varme kraften i omtrent fem sekunder, og tell mens du gjør det. Legg den på tallerkenen mens den fortsatt har litt spenst.'},
    {en:'Spoon tomato over it and scatter grated pecorino, then build a second and a third layer the same way, finishing with sauce and cheese.',
     no:'Ha tomatsaus over og strø på revet pecorino, og bygg et andre og et tredje lag på samme måte. Avslutt med saus og ost.'},
    {en:'Slide a poached egg on top, add a last handful of cheese and carry the plate to the table immediately.',
     no:'Legg et posjert egg øverst, ha på en siste neve ost, og bær tallerkenen til bordet med en gang.'},
    {en:'Tell whoever gets it to break the yolk down into the layers before they cut. The yolk is the sauce.',
     no:'Be den som får tallerkenen, bryte plommen ned i lagene før den skjæres. Plommen er sausen.'},
  ],
  notes:[
    {title:{en:'Seconds, not minutes', no:'Sekunder, ikke minutter'},
     body:{en:'Carasau was baked twice to drive every trace of water out of it, which is why it keeps for months and why it drinks so fast. Five seconds is enough to make a sheet bend. The pleasure of the dish is layers that still have structure; soak them and you are eating a bowl of wet bread.',
           no:'Carasau ble stekt to ganger for å drive ut hvert spor av vann, og derfor holder det seg i månedsvis, og derfor drikker det så fort. Fem sekunder holder til at platen bøyer seg. Gleden ved retten ligger i lag som fortsatt har struktur, og bløter du dem, spiser du en skål vått brød.'}},
    {title:{en:'Why broth and not water', no:'Derfor kraft og ikke vann'},
     body:{en:'The bread carries almost no salt and no fat at all. Whatever it is dipped in is the only seasoning it will ever get, which is why the island uses sheep broth, and why a stock cube tastes exactly like a stock cube here.',
           no:'Brødet har nesten ikke salt i seg og ikke fett i det hele tatt. Det du dypper platen i, er den eneste smaken den får, og derfor bruker øya saukraft, og derfor smaker en buljongterning nøyaktig som en buljongterning i denne retten.'}},
    {title:{en:'No oven, no browning', no:'Ingen ovn, ingen bruning'},
     body:{en:'Frattau is not a baked lasagne. Everything is hot and cooked before it reaches the plate, and the plate is assembled and carried out. Put it under a grill and the bread dries out again and the egg hardens, and both of the things the dish is for are gone.',
           no:'Frattau er ingen lasagne fra ovnen. Alt er varmt og ferdig før det når tallerkenen, og tallerkenen settes sammen og bæres inn. Setter du den under grillen, tørker brødet ut igjen og egget blir hardt, og da har du mistet begge tingene retten handler om.'}},
  ],
  variations:[
    {title:{en:'Pane guttiau', no:'Pane guttiau'},
     body:{en:'The simplest thing anyone does with carasau. Brush a sheet with olive oil, scatter salt and rosemary over it, and give it two or three minutes in a hot oven until the edges colour. It goes with cheese, salami and a glass of Cannonau, and it is a snack rather than a course.',
           no:'Det enkleste man gjør med carasau. Pensle en plate med olivenolje, strø på salt og rosmarin, og gi den to eller tre minutter i varm ovn til kantene får farge. Det spises med ost, spekepølse og et glass Cannonau, og det er tilbehør, ikke en rett.'}},
    {title:{en:'Without the egg', no:'Uten egg'},
     body:{en:'Some households leave the egg out and put more pecorino between the layers. The dish turns drier and more like a lasagne, and that is how you do it when a crowd has to be fed from one pan.',
           no:'Noen husholdninger dropper egget og har mer pecorino mellom lagene. Retten blir tørrere og mer lik en lasagne, og slik gjør man det når mange skal mettes fra én kjele.'}},
    {title:{en:'Zuppa gallurese', no:'Zuppa gallurese'},
     body:{en:'The northern cousin, from the Gallura. Stale bread rather than carasau, layered with cheese, soaked in broth and then baked until the top browns. The same pastoral logic of bread, cheese and broth, and an entirely different result.',
           no:'Fetteren i nord, fra Gallura. Der brukes gammelt brød i stedet for carasau. Det legges lagvis med ost, trekkes med kraft og bakes til overflaten blir brun. Samme gjeterlogikk med brød, ost og kraft, men et helt annet resultat.'}},
  ],
},

{
  id:'culurgiones', dish:'Culurgiones', course:'primo', lesson:3, serves:4, time:{prep:90, cook:20},
  hero:'culurgiones', tags:['pasta','potato','mint','pecorino','filled'],
  title:{en:"Culurgiones d'Ogliastra", no:"Culurgiones d'Ogliastra"},
  blurb:{en:'Sardinian ravioli filled with potato, pecorino and mint, and closed with a pleat that leaves a raised seam like an ear of wheat.',
         no:'Sardisk ravioli fylt med potet, pecorino og mynte, og lukket med en fold som etterlater en opphøyd søm formet som et kornaks.'},
  heroCaption:{en:'Culurgiones from the Ogliastra. The seam is the spighitta, worked by thumb and finger with no tool at all.',
               no:'Culurgiones fra Ogliastra. Sømmen heter spighitta, og den arbeides fram med tommel og pekefinger, uten redskap.'},
  wines:['Cannonau di Sardegna'],
  headnote:{
    en:'<p>Culurgiones come from the <strong>Ogliastra</strong>, the mountainous strip of the east coast, and they have carried IGP protection since 2015. The filling is the surprise: no meat and no ricotta, but potato mashed with pecorino, mint and olive oil. This is shepherd food dressed as pasta — the cheese is the protein, the potato is the bulk, and the mint keeps the whole thing from sitting heavy.</p>'
      + '<p>The dough is Sardinian in its plainest form, durum semolina and water and no egg. Work it hard and let it rest, and it rolls out thin and stays there instead of springing back. Without that, the pleat cannot be worked at all.</p>'
      + '<p>The pleat, the <em>spighitta</em>, is why people photograph these. It is not decoration. It closes the parcel without a second sheet of dough and without any egg wash, and it leaves a raised zig-zag seam that looks like an ear of wheat, read on the island as a small charm for the harvest to come. It also takes practice. Your first ten will be clumsy, the tenth will be better than the first, and every one of them will taste right.</p>',
    no:'<p>Culurgiones kommer fra <strong>Ogliastra</strong>, det fjellrike beltet på østkysten, og de har hatt IGP-beskyttelse siden 2015. Fyllet overrasker: verken kjøtt eller ricotta, men potetstappe rørt sammen med pecorino, mynte og olivenolje. Dette er gjetermat forkledd som pasta. Osten står for proteinet, poteten for mengden, og mynten hindrer at det hele blir tungt.</p>'
      + '<p>Deigen er sardisk i sin enkleste form, med durumsemule og vann og uten egg. Arbeider du den godt og lar den hvile, kjevles den tynn og blir liggende i stedet for å trekke seg sammen. Uten det lar folden seg ikke arbeide.</p>'
      + '<p>Folden, <em>spighitta</em>, er grunnen til at folk fotograferer disse. Den er ingen pynt. Den lukker pakken uten et ekstra lag deig og uten eggepensling, og den etterlater en opphøyd sikksakksøm som ligner et kornaks. På øya ble den lest som en liten lykkebringer for den kommende innhøstingen. Den krever også øvelse. De ti første blir klossete, den tiende blir bedre enn den første, og hver eneste av dem smaker riktig.</p>'},
  ingredients:[
    { group:{en:'For the dough', no:'Til deigen'}, items:[
      {q:300, u:'g', n:{en:'durum semolina', no:'durumsemule'},
       note:{en:'semola rimacinata, the finely reground kind; plain wheat flour will not hold the pleat', no:'semola rimacinata, den finmalte typen. Vanlig hvetemel holder ikke på folden'}},
      {q:150, u:'ml', n:{en:'warm water', no:'varmt vann'}},
      {q:5, u:'g', n:{en:'salt', no:'salt'}},
    ]},
    { group:{en:'For the filling', no:'Til fyllet'}, items:[
      {q:600, u:'g', n:{en:'floury potatoes', no:'melne poteter'},
       note:{en:'boiled whole in their skins, so that they take up no water', no:'kokes hele med skallet på, slik at de ikke trekker til seg vann'}},
      {q:150, u:'g', n:{en:'Pecorino Sardo', no:'Pecorino Sardo'},
       note:{en:'matured and hard, finely grated', no:'lagret og hard, finrevet'}},
      {q:30, u:'ml', n:{en:'olive oil', no:'olivenolje'}},
      {q:2, u:'', n:{en:'cloves of garlic', no:'hvitløksfedd'}, round:'half'},
      {q:15, u:'g', n:{en:'mint leaves', no:'mynteblader'},
       note:{en:'fresh and finely chopped. The mint is neither a garnish nor optional', no:'friske og finhakket. Mynten er verken pynt eller valgfri'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'To serve', no:'Til servering'}, items:[
      {q:300, u:'g', n:{en:'peeled plum tomatoes', no:'hermetiske plommetomater'}},
      {q:20, u:'ml', n:{en:'olive oil', no:'olivenolje'}},
      {q:40, u:'g', n:{en:'Pecorino Sardo, grated', no:'Pecorino Sardo, revet'}},
      {q:4, u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:20, u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
    ]},
  ],
  steps:[
    {en:'Boil the potatoes whole and unpeeled until a knife slides in without resistance, then peel them while they are still hot and pass them through a ricer.',
     no:'Kok potetene hele med skallet på til en kniv går inn uten motstand. Skrell dem mens de fortsatt er varme, og press dem gjennom en potetpresse.'},
    {en:'Soften the garlic in the oil over low heat, take the garlic out and pour the warm oil over the potato.',
     no:'La hvitløken mykne i oljen på svak varme, ta den ut, og hell den varme oljen over poteten.'},
    {en:'Work in the grated pecorino and the chopped mint and season it. The filling should be a firm paste that holds a shape, not a loose mash.',
     no:'Arbeid inn den revne pecorinoen og den hakkede mynten, og smak til med salt. Fyllet skal bli en fast masse som holder formen, ikke en løs stappe.'},
    {en:'Cover it and let it cool right down to room temperature before you fill anything. Warm filling melts the fat in the cheese, slackens the potato and tears the seam from the inside.',
     no:'Dekk det til og la det kjølne helt til romtemperatur før du fyller noe som helst. Varmt fyll smelter fettet i osten, gjør poteten løs og river sømmen opp innenfra.'},
    {en:'Work the semolina, the water and the salt into a firm dough and knead it for ten minutes, until it is smooth and springs back slowly. Rest it covered for half an hour.',
     no:'Arbeid semulen, vannet og saltet til en fast deig, og elt den i ti minutter, til den er glatt og langsomt fjærer tilbake. La den hvile tildekket i en halvtime.'},
    {en:'Roll the dough about a millimetre thick and cut discs of around nine centimetres.',
     no:'Kjevle deigen til rundt en millimeter og stikk ut sirkler på omtrent ni centimeter.'},
    {en:'Put a walnut of filling in the middle of a disc and hold it in your palm with the opening upwards.',
     no:'Legg en valnøttstor klump fyll midt på en sirkel, og hold den i hånden med åpningen opp.'},
    {en:'Pinch the dough shut at the edge nearest you, then take alternate pinches from the left wall and the right wall, folding each over the one before, and work away from yourself until the parcel closes.',
     no:'Klyp deigen sammen ved kanten nærmest deg, ta så vekselvis et klyp fra venstre og et fra høyre vegg, brett hvert av dem over det forrige, og arbeid deg bortover til pakken lukker seg.'},
    {en:'Lay the finished ones on a tray dusted with semolina, not touching each other, and never stack them.',
     no:'Legg de ferdige på et brett drysset med semule, uten at de rører hverandre, og stable dem aldri.'},
    {en:'Simmer the tomatoes with the oil and a little salt for about a quarter of an hour, until they have collapsed into a light sauce.',
     no:'La tomatene småkoke med oljen og litt salt i omtrent et kvarter, til de har falt sammen til en lett saus.'},
    {en:'Cook them in plenty of gently boiling salted water for five to six minutes, until they float and the seam is tender, and lift them out with a slotted spoon.',
     no:'Kok dem i rikelig, rolig kokende saltet vann i fem til seks minutter, til de flyter opp og sømmen er myk, og løft dem opp med hullsleiv.'},
    {en:'Turn them once in the sauce with the pan off the heat, scatter grated pecorino over them and serve.',
     no:'Vend dem én gang i sausen med pannen av platen, strø revet pecorino over, og server.'},
  ],
  notes:[
    {title:{en:'The seam is the thick part', no:'Sømmen er det tykke partiet'},
     body:{en:'The folded pleat is three or four thicknesses of dough where the rest of the parcel is one. Roll thin enough that the seam still cooks through in the five or six minutes the rest needs, or you serve a raw ridge on a cooked ravioli. This is the real reason the dough is semolina and water: it rolls thinner without tearing than an egg dough does.',
           no:'Den brettede folden er tre eller fire lag deig der resten av pakken er ett. Kjevle tynt nok til at sømmen rekker å bli gjennomkokt på de fem eller seks minuttene resten trenger, ellers serverer du en rå søm på en ferdig ravioli. Her ligger den egentlige grunnen til at deigen er semule og vann: den lar seg kjevle tynnere uten å revne enn en eggedeig gjør.'}},
    {title:{en:'Cool filling, dry filling', no:'Kaldt fyll, tørt fyll'},
     body:{en:'Potatoes boiled in their skins take up almost no water, while peeled and quartered ones take up a great deal, and a wet filling leaks. The cooling matters for the same reason: warm pecorino gives up its fat, and fat in the filling finds its way out through the seam in the water.',
           no:'Poteter kokt med skallet på trekker nesten ikke til seg vann, mens skrelte og delte poteter trekker til seg mye, og et vått fyll lekker. Avkjølingen betyr like mye, for varm pecorino gir fra seg fettet sitt, og fett i fyllet finner veien ut gjennom sømmen i kokevannet.'}},
    {title:{en:'Gentle water', no:'Rolig kokevann'},
     body:{en:'A hard boil throws them against each other, and the pleat is the first thing to open. Keep the water just moving, cook them in batches, and take them out with a slotted spoon rather than tipping them into a colander.',
           no:'Fosskoking kaster dem mot hverandre, og folden er det første som åpner seg. Hold vannet så vidt i bevegelse, kok dem i omganger, og ta dem opp med hullsleiv i stedet for å helle dem i et dørslag.'}},
  ],
  variations:[
    {title:{en:'Oil, or tomato', no:'Olje eller tomat'},
     body:{en:'In the Ogliastra they are served as often with nothing but warm olive oil and grated pecorino. A light tomato sauce is the other classic. A heavy meat ragù buries the mint, and it is the one thing to keep away from them.',
           no:'I Ogliastra serveres de like gjerne med bare varm olivenolje og revet pecorino. En lett tomatsaus er den andre klassikeren. En tung kjøttragù begraver mynten, og det er det eneste man bør holde seg unna.'}},
    {title:{en:'Which mint', no:'Hvilken mynte'},
     body:{en:'Some villages use nepitella, the wild calamint of the Mediterranean hillsides, which is sharper and faintly resinous. Ordinary garden mint is what most kitchens have and what most recipes assume. A few households put a little fresh pecorino in alongside the matured, which makes the filling softer and milder.',
           no:'Noen landsbyer bruker nepitella, den ville kalamynten fra middelhavsåsene, som er skarpere og litt harpiksaktig. Vanlig hagemynte er det de fleste kjøkken har, og det de fleste oppskrifter går ut fra. Enkelte husholdninger har litt fersk pecorino i tillegg til den lagrede, og da blir fyllet mykere og mildere.'}},
    {title:{en:'If the pleat defeats you', no:'Hvis folden blir for vanskelig'},
     body:{en:'Fold the disc in half and press the edge closed with a fork. You have made a half-moon ravioli with a Sardinian filling, which is good to eat and is not a culurgione. Come back to the pleat next time with the dough a little thinner.',
           no:'Brett sirkelen dobbelt og trykk kanten sammen med en gaffel. Da har du laget en halvmåneravioli med sardisk fyll, og det er god mat, men det er ingen culurgione. Prøv folden igjen neste gang, med litt tynnere deig.'}},
  ],
},

{
  id:'fregola-con-arselle', dish:'Fregola', course:'primo', lesson:3, serves:4, time:{prep:30, cook:30},
  hero:'fregolamare', tags:['pasta','shellfish','tomato'],
  title:{en:'Fregola con arselle', no:'Fregola con arselle'},
  blurb:{en:'Toasted semolina pellets cooked like a risotto in the liquor of the clams. The island’s one great meeting of the interior and the lagoon.',
         no:'Ristede semulekuler kokt som en risotto i kraften fra skjellene. Øyas ene store møte mellom innlandet og lagunen.'},
  heroCaption:{en:'Fregola cooked in the shellfish liquor until it is soupy rather than dry. It goes on thickening on the plate.',
               no:'Fregola kokt i skalldyrkraften til den er suppeaktig og ikke tørr. Den tykner videre på tallerkenen.'},
  wines:['Vermentino di Gallura'],
  headnote:{
    en:'<p>Fregola is made the way couscous is made, not the way pasta is. Semolina is rubbed with water in a wide bowl, in circles, with the flat of the hand, until it gathers into small irregular pellets, and the pellets are then dried and toasted in the oven. The toasting is the whole point. It gives the nutty flavour and a firmness that survives long cooking, and it is why fregola can go into a wet pan and come out with a bite still in it.</p>'
      + '<p>Because the pellets are toasted, fregola is cooked in its sauce rather than in a pot of water, which makes this a risotto in method. Liquid goes in a ladle at a time, the grains give up their starch slowly, and the liquid thickens into a sauce of its own. Drain fregola like pasta and you have poured the better half of the dish down the sink.</p>'
      + '<p>The classic version is <em>fregola con arselle</em>, made with the small clams of the lagoons at Cabras and Santa Gilla. Lagoon clams carry sand, which is why they are purged in salted water and why their liquor is strained through a cloth. That strained liquor is the seasoning: there is no fish stock in this dish and no need for one.</p>',
    no:'<p>Fregola lages som couscous, ikke som pasta. Semule gnis med vann i en vid bolle, i sirkler, med flat hånd, til det samler seg i små, ujevne kuler, og kulene tørkes og ristes deretter i ovnen. Ristingen er hele poenget. Den gir den nøtteaktige smaken og en fasthet som tåler lang koking, og derfor kan fregola gå ned i en våt panne og komme opp igjen med tyggemotstanden i behold.</p>'
      + '<p>Siden kulene er ristet, kokes fregola i sausen og ikke i en kjele med vann, og metoden blir dermed den samme som for risotto. Væsken går i en øse om gangen, kornene gir fra seg stivelsen langsomt, og væsken tykner til sin egen saus. Heller du av fregolaen som pasta, har du tømt den beste halvdelen av retten i vasken.</p>'
      + '<p>Den klassiske utgaven heter <em>fregola con arselle</em> og lages med de små skjellene fra lagunene ved Cabras og Santa Gilla. Skjell fra lagunene har sand i seg, og derfor legges de i saltet vann for å rense seg, og derfor siles kraften deres gjennom et klede. Den silte kraften er krydderet, for retten har verken fiskekraft eller behov for det.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:300, u:'g', n:{en:'fregola', no:'fregola'},
     note:{en:'the medium grade, bought already toasted; the darker the pellets, the further the toasting went',
           no:'den mellomgrove typen, kjøpt ferdig ristet. Jo mørkere kulene er, desto lenger har ristingen gått'}},
    {q:1, u:'kg', n:{en:'small clams', no:'små skjell'},
     note:{en:'vongole veraci if you can get them. In Norway they turn up frozen at the fish counter, and mussels are the everyday stand-in',
           no:'vongole veraci hvis du får tak i dem. I Norge dukker de opp fryste i fiskedisken, og blåskjell er den vanlige erstatningen'}},
    {q:300, u:'g', n:{en:'cherry tomatoes', no:'cherrytomater'},
     note:{en:'halved. The sauce should stay pale and orange, not red', no:'delt i to. Sausen skal holde seg lys og oransje, ikke rød'}},
    {q:100, u:'ml', n:{en:'dry white wine', no:'tørr hvitvin'}},
    {q:40, u:'ml', n:{en:'olive oil', no:'olivenolje'}},
    {q:2, u:'', n:{en:'cloves of garlic', no:'hvitløksfedd'}, round:'half'},
    {q:1, u:'', n:{en:'small dried chilli', no:'liten tørket chili'}, round:'half'},
    {q:10, u:'g', n:{en:'flat-leaf parsley', no:'bladpersille'}},
    {q:700, u:'ml', n:{en:'light fish broth or water', no:'lys fiskekraft eller vann'},
     note:{en:'kept hot beside the pan. The grain drinks it, so this is not pasta water and none of it gets thrown away',
           no:'holdes varm ved siden av pannen. Kornet drikker den, så dette er ikke pastavann, og ingenting av det helles ut'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
  ]}],
  steps:[
    {en:'Leave the clams in cold salted water for a couple of hours to purge, then rinse them and throw out any that stay open when you tap them.',
     no:'La skjellene ligge i kaldt, saltet vann et par timer for å rense seg. Skyll dem, og kast dem som blir liggende åpne når du banker på dem.'},
    {en:'Put them in a wide pan over high heat with a splash of the wine and a lid on, and lift each one out as it opens. A clam left in the pan after it has opened turns to rubber.',
     no:'Ha dem i en vid panne på sterk varme med en skvett av vinen og lokk på, og løft ut hvert skjell etter hvert som det åpner seg. Et skjell som blir liggende etter at det har åpnet seg, blir seigt som gummi.'},
    {en:'Strain the liquor left in the pan through a cloth into a bowl. Lagoon clams carry sand, and nothing else in the recipe will take it out.',
     no:'Sil kraften som ligger igjen i pannen, gjennom et klede og over i en bolle. Skjell fra lagunene har sand i seg, og ingenting annet i oppskriften fjerner den.'},
    {en:'Shell most of them and keep a few in the shell for the top of the dish.',
     no:'Ta de fleste ut av skallet, og behold noen med skall til toppen av retten.'},
    {en:'Soften the garlic and the chilli in the oil in a wide pan, until the garlic smells and before it colours.',
     no:'La hvitløken og chilien mykne i oljen i en vid panne, til hvitløken dufter, og før den får farge.'},
    {en:'Add the tomatoes, press them with a spoon and cook them for five minutes, until they collapse and the oil turns orange.',
     no:'Ha i tomatene, trykk dem med en skje, og la dem koke i fem minutter, til de faller sammen og oljen blir oransje.'},
    {en:'Pour in the rest of the wine and let it boil away.',
     no:'Hell i resten av vinen og la den koke bort.'},
    {en:'Stir in the fregola and let it toast for a minute in the oil and tomato, turning it so that every pellet is coated.',
     no:'Rør inn fregolaen og la den riste et minutt i olje og tomat mens du vender den, slik at hver kule blir dekket.'},
    {en:'Add the strained clam liquor and about half the broth, and simmer uncovered for twelve to fifteen minutes, stirring often and adding more broth as it is drunk.',
     no:'Ha i den silte skjellkraften og omtrent halvparten av fiskekraften, og la det småkoke uten lokk i tolv til femten minutter mens du rører ofte og speer med mer kraft etter hvert som den drikkes opp.'},
    {en:'Stop while it still ripples on the plate and the pellets are tender outside and firm in the middle. It thickens as it stands, so a fregola that looks right in the pan is dry by the time it is eaten.',
     no:'Stopp mens den fortsatt bølger på tallerkenen og kulene er myke utenpå og faste i midten. Den tykner mens den står, så en fregola som ser riktig ut i pannen, er tørr når den spises.'},
    {en:'Stir in the clams and the chopped parsley with the pan off the heat, lay the ones in their shells on top and serve at once.',
     no:'Rør inn skjellene og den hakkede persillen med pannen av platen, legg dem med skall på toppen, og server med en gang.'},
  ],
  notes:[
    {title:{en:'Toasted, and therefore it holds', no:'Ristet, og derfor holder den'},
     body:{en:'Toasting sets a dry crust on every pellet. Starch leaves it slowly, which lets the liquid thicken while the middle stays firm through a quarter of an hour of simmering that would reduce ordinary pasta to mush. If your fregola looks pale, spread it on a tray and give it eight minutes at 180 °C before you start.',
           no:'Ristingen setter en tørr skorpe på hver kule. Stivelsen slipper langsomt ut, og da rekker væsken å tykne mens midten holder seg fast gjennom et kvarters småkoking som ville gjort vanlig pasta til grøt. Ser fregolaen din blek ut, kan du spre den utover et brett og gi den åtte minutter på 180 °C før du begynner.'}},
    {title:{en:'The clams open at different times', no:'Skjellene åpner seg til ulik tid'},
     body:{en:'Shellfish of one size still cook at their own rates. Take each one out as it opens and you get clams you can eat instead of clams you chew. The pan is not a timer; it is a queue.',
           no:'Skjell av samme størrelse blir likevel ferdige til ulik tid. Tar du ut hvert skjell etter hvert som det åpner seg, får du skjell du kan spise, i stedet for skjell du må tygge på. Pannen er ingen tidtaker, men en kø.'}},
    {title:{en:"All'onda", no:"All'onda"},
     body:{en:'Sardinian cooks take the pan off while the dish still looks too wet. The pellets go on absorbing on the way to the table and for a minute after it, and a fregola that was perfect in the pan arrives stiff. Aim for a ripple.',
           no:'Sardiske kokker tar pannen av mens retten fortsatt ser for våt ut. Kulene fortsetter å trekke til seg væske på vei til bordet og et minutt etterpå, og en fregola som var perfekt i pannen, kommer stiv fram. Sikt mot en bølge.'}},
  ],
  variations:[
    {title:{en:'Mussels instead of clams', no:'Blåskjell i stedet for vongole'},
     body:{en:'Mussels are what a Norwegian fish counter always has. They give a sweeter, less saline liquor, so taste before you salt and be firmer with the chilli. Rinse and beard them; they need no purging, since rope-farmed mussels carry no sand.',
           no:'Blåskjell er det en norsk fiskedisk alltid har. De gir en søtere og mindre salt kraft, så smak til før du salter, og ta hardere i med chilien. Skyll dem og fjern skjegget. De trenger ingen utvanning, for skjell dyrket på tau har ingen sand i seg.'}},
    {title:{en:'Fregola with sausage and tomato', no:'Fregola med pølse og tomat'},
     body:{en:'The inland version, from the villages that never saw a lagoon. Brown crumbled sausage in place of the clams, use a meat broth, and finish with grated pecorino. Cheese and shellfish do not meet in the same pan on this island.',
           no:'Innlandsvarianten, fra landsbyene som aldri så en lagune. Brun oppsmuldret pølse i stedet for skjellene, bruk kjøttkraft, og avslutt med revet pecorino. Ost og skalldyr møtes ikke i samme panne på denne øya.'}},
    {title:{en:'Making your own', no:'Hjemmelaget fregola'},
     body:{en:'Semolina, a bowl, a hand and about an hour. Sprinkle water over semolina in a wide bowl and rub in circles with the flat of your hand until pellets form, sift out the ones that are the right size, keep going with the rest, dry them, and then toast them at 180 °C until they smell of biscuit. It is a proper Saturday job, and it beats anything that comes in a packet.',
           no:'Semule, en bolle, en hånd og omtrent en time. Dryss vann over semulen i en vid bolle og gni i sirkler med flat hånd til det danner seg kuler. Sikt ut dem som har riktig størrelse, fortsett med resten, tørk dem, og rist dem så på 180 °C til de lukter kjeks. Dette er en ordentlig lørdagsjobb, og resultatet slår alt som kommer i pose.'}},
  ],
},

{
  id:'seadas', dish:'Seadas', course:'dolce', lesson:3, serves:4, time:{prep:60, cook:20},
  hero:'seadasfritta', tags:['dolce','fried','cheese','honey'],
  title:{en:'Seadas', no:'Seadas'},
  blurb:{en:'Thin semolina pastry around fresh sour sheep’s cheese, fried until it blisters and eaten hot under bitter honey. Sweet and savoury at the same moment.',
         no:'Tynn semuledeig rundt fersk, syrlig saueost, fritert til den blemmer og spist varm under bitter honning. Søtt og salt i samme øyeblikk.'},
  heroCaption:{en:'A seada straight out of the pan. The blisters are steam off the water in the dough, and they are the sign the fat was hot enough.',
               no:'En seada rett fra pannen. Blemmene er damp fra vannet i deigen, og de viser at fettet var varmt nok.'},
  wines:['Vernaccia di Oristano'],
  headnote:{
    en:'<p>Seadas close a Sardinian meal, and they are not a dessert in the ordinary sense. A large disc of thin semolina pastry encloses fresh, faintly sour sheep’s cheese with a little lemon zest; it is fried until it blisters and served hot under bitter <strong>corbezzolo</strong> honey, which bees make from the strawberry tree. Sweet and savoury arrive together, and nothing on the mainland tastes like it.</p>'
      + '<p>The cheese is where a foreign kitchen goes wrong. It is a young pecorino, a day or two old, deliberately left to acidify, and that acid is what makes it pull into a stringy cream when it melts. A matured pecorino has lost the water and gained salt; heat it and it breaks into oil and grit. Outside Italy, look for the freshest unripened sheep’s cheese you can find. Failing that, a well-drained low-moisture mozzarella with matured pecorino grated into it and extra lemon zest will give you a cheese that stretches and tastes sour rather than salty, which is what the dish needs.</p>'
      + '<p>The filling is not simply stuffed in raw. The cheese is melted first with a little semolina, poured out to set into a firm sheet and cut into discs, so the parcel goes into the fat with something solid inside it and comes out with something molten. The frying temperature does the rest: 170 °C, and no hotter.</p>',
    no:'<p>Seadas avslutter et sardisk måltid, og de er ingen dessert i vanlig forstand. En stor leiv av tynn semuledeig legges rundt fersk, svakt syrlig saueost med litt sitronskall. Den friteres til den blemmer og serveres varm under bitter <strong>corbezzolo</strong>-honning, som biene henter fra jordbærtreet. Søtt og salt kommer samtidig, og ingenting på fastlandet smaker som dette.</p>'
      + '<p>Osten er stedet der et utenlandsk kjøkken bommer. Den er en ung pecorino på én til to dager, som med vilje har fått surne, og syren gjør at den trekker seg til en trådete krem når den smelter. En lagret pecorino har mistet vannet og fått mer salt. Varmer du den, skiller den seg i olje og korn. Utenfor Italia bør du lete etter den ferskeste umodne saueosten du finner. Får du ikke tak i noen, kan du bruke en godt avrent mozzarella med lavt vanninnhold, rive lagret pecorino i den og ta i ekstra sitronskall. Da får du en ost som trekker seg i tråder og smaker syrlig i stedet for salt, slik retten krever.</p>'
      + '<p>Fyllet stappes ikke inn rått. Osten smeltes først med litt semule, helles ut og får stivne til en fast plate, og skjæres i sirkler. Da går pakken ned i fettet med noe fast inni seg og kommer opp med noe rennende. Resten ordner frityrtemperaturen: 170 °C, og ikke varmere.</p>'},
  ingredients:[
    { group:{en:'For the pastry', no:'Til deigen'}, items:[
      {q:250, u:'g', n:{en:'durum semolina', no:'durumsemule'},
       note:{en:'semola rimacinata, the finely reground kind', no:'semola rimacinata, den finmalte typen'}},
      {q:40, u:'g', n:{en:'lard', no:'svinefett'},
       note:{en:'strutto, melted. Butter works; olive oil gives a softer, less brittle pastry', no:'strutto, smeltet. Smør går også, mens olivenolje gir en mykere og mindre sprø deig'}},
      {q:110, u:'ml', n:{en:'warm water', no:'varmt vann'}},
      {q:4, u:'g', n:{en:'salt', no:'salt'}},
    ]},
    { group:{en:'For the filling', no:'Til fyllet'}, items:[
      {q:400, u:'g', n:{en:"fresh acidic sheep's cheese", no:'fersk, syrlig saueost'},
       note:{en:'a young pecorino a day or two old. The headnote says what to use instead', no:'en ung pecorino på én til to dager. Innledningen sier hva du kan bruke i stedet'}},
      {q:20, u:'g', n:{en:'durum semolina', no:'durumsemule'},
       note:{en:'stirred into the melted cheese to hold it together', no:'røres inn i den smeltede osten for å binde den'}},
      {q:1, u:'', n:{en:'lemon', no:'sitron'}, round:'half',
       note:{en:'the zest only, from an unwaxed one', no:'bare skallet, av en ubehandlet sitron'}},
    ]},
    { group:{en:'To finish', no:'Til servering'}, items:[
      {q:200, u:'g', n:{en:'corbezzolo honey', no:'corbezzolo-honning'},
       note:{en:'bitter strawberry-tree honey. The variations say what to do if you cannot get it', no:'bitter honning fra jordbærtreet. Variantene sier hva du gjør hvis du ikke får tak i den'}},
      {u:'', n:{en:'oil or lard for frying', no:'olje eller svinefett til fritering'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Work the semolina, the salt, the melted lard and enough of the warm water into a firm dough, and knead it for ten minutes until it is smooth. Rest it covered for half an hour.',
     no:'Arbeid semulen, saltet, det smeltede fettet og nok av det varme vannet til en fast deig, og elt den i ti minutter til den er glatt. La den hvile tildekket i en halvtime.'},
    {en:'Grate or dice the cheese and melt it in a heavy pan over low heat with a splash of water, stirring, until it pulls together into one stringy mass.',
     no:'Riv osten eller skjær den i terninger, og smelt den i en tykkbunnet kjele på svak varme med en skvett vann, mens du rører, til den trekker seg sammen til én trådete masse.'},
    {en:'Take the pan off the heat, stir in the lemon zest and the semolina, and work it smooth.',
     no:'Ta kjelen av platen, rør inn sitronskallet og semulen, og arbeid massen glatt.'},
    {en:'Pour it onto an oiled tray, spread it about half a centimetre thick and leave it to set cold and firm.',
     no:'Hell den ut på et oljet brett, bre den ut til rundt en halv centimeter, og la den stivne til den er kald og fast.'},
    {en:'Cut discs of about eight centimetres out of the set sheet.',
     no:'Stikk ut sirkler på omtrent åtte centimeter av den stivnede platen.'},
    {en:'Roll the dough as thin as you can, about a millimetre, and cut discs a good three centimetres wider than the cheese ones.',
     no:'Kjevle deigen så tynn du klarer, rundt en millimeter, og stikk ut sirkler som er en god tre centimeter bredere enn osteskivene.'},
    {en:'Lay a cheese disc on a pastry disc, cover it with a second and press the air out from the middle outwards. Trapped air bursts them in the fat.',
     no:'Legg en osteskive på en deigsirkel, dekk den med en til, og trykk luften ut fra midten og utover. Innestengt luft sprenger dem i fettet.'},
    {en:'Seal the edge hard between finger and thumb, then trim it with a fluted wheel so the rim is even.',
     no:'Klem kanten godt sammen mellom tommel og pekefinger, og skjær den til med et riflet deighjul, slik at randen blir jevn.'},
    {en:'Heat the frying fat to 170 °C, deep enough for a seada to float. Test it with a scrap of dough: it should rise and bubble steadily, not fiercely.',
     no:'Varm frityrfettet til 170 °C, og bruk nok til at en seada flyter. Prøv med en bit deig. Den skal stige opp og boble jevnt, ikke voldsomt.'},
    {en:'Fry them two at a time for about two minutes, spooning hot fat over the tops so that the pastry blisters. They should stay pale gold and never brown.',
     no:'Friter to om gangen i omtrent to minutter mens du øser varmt fett over toppen, slik at deigen blemmer. De skal holde seg lyst gylne og aldri bli brune.'},
    {en:'Lift them onto paper for a few seconds and no longer. They go on cooking, and the cheese sets again as they cool.',
     no:'Løft dem over på papir i noen sekunder, ikke lenger. De steker videre, og osten stivner igjen mens de kjølner.'},
    {en:'Put them on warm plates, spoon warm honey over them and take them straight to the table.',
     no:'Legg dem på varme tallerkener, hell varm honning over, og bær dem rett til bordet.'},
  ],
  notes:[
    {title:{en:'Why the cheese is melted first', no:'Derfor smeltes osten først'},
     body:{en:'Raw cheese in the parcel would still be solid when the pastry was done, or it would leak while you were sealing it. Melt it, let it set and cut discs, and you have a filling of a known thickness that goes molten at exactly the moment the pastry crisps. The spoonful of semolina keeps the melted cheese from separating as it cools.',
           no:'Rå ost inni pakken ville fortsatt vært fast når deigen var ferdig, eller den ville lekket ut mens du lukket den. Smelter du osten, lar den stivne og skjærer den i sirkler, får du et fyll med kjent tykkelse som blir rennende akkurat idet deigen blir sprø. Skjeen med semule hindrer at den smeltede osten skiller seg mens den kjølner.'}},
    {title:{en:'170 °C, and why', no:'170 °C, og hvorfor'},
     body:{en:'Below about 160 the pastry drinks fat instead of sealing, and the seada comes out heavy and greasy. Above about 180 the outside colours before the cheese has melted, and you cut into a solid disc. At 170 the water in the dough flashes to steam fast enough to lift the surface into blisters, while the inside still has a couple of minutes to melt.',
           no:'Under omtrent 160 drikker deigen fett i stedet for å lukke seg, og seadaen blir tung og fet. Over omtrent 180 får utsiden farge før osten har smeltet, og da skjærer du i en fast skive. På 170 fordamper vannet i deigen raskt nok til å løfte overflaten i blemmer, samtidig som innsiden får et par minutter på å smelte.'}},
    {title:{en:'Serve them or lose them', no:'Server dem, ellers mister du dem'},
     body:{en:'A seada is at its best for about three minutes. The cheese sets as it cools and the pastry softens under the honey, so fry them while people are sitting down and carry them out as they come. Nothing here can be made to suit the table’s convenience except the parcels themselves, which freeze raw and fry from frozen.',
           no:'En seada er på sitt beste i omtrent tre minutter. Osten stivner mens den kjølner, og deigen blir myk under honningen, så friter dem mens folk setter seg, og bær dem ut etter hvert. Ingenting her lar seg tilpasse bordets tempo, bortsett fra pakkene selv, som kan fryses rå og friteres rett fra fryseren.'}},
  ],
  variations:[
    {title:{en:'If you cannot get corbezzolo honey', no:'Hvis du ikke får tak i corbezzolo-honning'},
     body:{en:'Corbezzolo is bitter, and the meeting of that bitterness with the sour cheese is the whole idea; a sweet honey leaves the dish with one note. Norwegian heather honey comes closest — dark, resinous, with a faint bitterness of its own. With an ordinary mild honey, grate more lemon zest into the cheese and put a little over the top, or the seada will taste only of sugar.',
           no:'Corbezzolo er bitter, og møtet mellom bitterheten og den syrlige osten er hele ideen. En søt honning gjør retten endimensjonal. Norsk lynghonning kommer nærmest, mørk og harpiksaktig og med et snev av bitterhet i seg. Bruker du en vanlig mild honning, bør du rive mer sitronskall i osten og legge litt på toppen, ellers smaker seadaen bare sukker.'}},
    {title:{en:'Sugar instead of honey', no:'Sukker i stedet for honning'},
     body:{en:'In parts of the Barbagia they are dusted with sugar rather than covered in honey. The dish turns less rich and more direct, and it puts the sour cheese right at the front.',
           no:'I deler av Barbagia strøs de med sukker i stedet for å dekkes med honning. Retten blir mindre fyldig og mer direkte, og den syrlige osten kommer helt fram.'}},
    {title:{en:'Seadas or sebadas', no:'Seadas eller sebadas'},
     body:{en:'Both spellings are used on the island, and one of them is a seada or a sebada. Restaurants that would rather not run a fryer offer a baked version; you get a warm pastry with cheese in it and no blisters, which is a different and lesser thing.',
           no:'Begge skrivemåtene brukes på øya, og i entall heter det en seada eller en sebada. Noen restauranter vil helst slippe å ha frityren i gang, og de tilbyr en ovnsbakt utgave. Da får du en varm deig med ost i, uten blemmer, og det er noe annet og mindre.'}},
  ],
},

];
