// sicilia recipes. Contract: docs/recipe-format.md. Both languages in one file; never narrated.
// Everything here follows the Sicilia food reading (content/sicilia.js, lesson 3): the Arab inheritance
// of rice, sugar, citrus, aubergine, saffron, raisins and almonds; the agrodolce balance of vinegar
// against sugar; street food fried and eaten standing up; and granita descended from sharbat and the
// medieval trade in mountain snow.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-82'] = [

{
  id:'arancini', dish:'Arancini', course:'antipasto', lesson:3, serves:4, time:{prep:45, cook:45},
  hero:'arancini', tags:['street food','rice','fried'],
  title:{en:'Arancini al ragù', no:'Arancini al ragù'},
  blurb:{en:'Saffron rice packed around a meat and pea filling, breaded and deep-fried. Palermo eats them standing up.',
         no:'Safranris pakket rundt et fyll av kjøtt og erter, panert og frityrstekt. I Palermo spises de stående.'},
  heroCaption:{en:'Arancini, named for the little oranges they resemble; rice, saffron and frying all reached Sicily with the Arabs.',
               no:'Arancini har navn etter de små appelsinene de ligner på. Ris, safran og fritering kom alle til Sicilia med araberne.'},
  wines:['Cerasuolo di Vittoria'],
  headnote:{
    en:'<p>Nothing in an arancino is native to Sicily. Rice, saffron and the habit of deep-frying all arrived with the <strong>Emirate of Sicily</strong> between 827 and 1091, and the dish is the neatest summary of that inheritance you can hold in one hand. The name means little oranges, which is what a tray of them looks like.</p>'
      + '<p>The mechanism is not the frying, it is the rice. This is not risotto: the grains have to be cooked dry, by absorption, so that no free liquid is left, and then cooled completely. Cold rice is sticky and holds a seam. Warm rice has no structure at all and will open in the oil and empty the filling into the pan.</p>'
      + '<p>And the argument you cannot avoid. In Palermo they are <em>arancine</em>, feminine and round; in Catania <em>arancini</em>, masculine and often shaped into a cone. People care, and nobody has ever been talked out of the version they grew up with.</p>',
    no:'<p>Ingenting i en arancino er opprinnelig siciliansk. Ris, safran og vanen med å frityrsteke kom alt sammen med <strong>emiratet Sicilia</strong> mellom 827 og 1091, og retten er det ryddigste sammendraget av den arven du kan holde i én hånd. Navnet betyr små appelsiner, og det er nettopp det et fat med dem ligner på.</p>'
      + '<p>Det avgjørende er ikke friteringen, men risen. Dette er ingen risotto. Kornene må kokes tørre, slik at all væsken trekkes inn og ingenting blir liggende igjen, og deretter kjøles helt ned. Kald ris er klebrig og holder på skjøten. Varm ris har ingen struktur i det hele tatt, åpner seg i oljen og tømmer fyllet ut i gryten.</p>'
      + '<p>Og så striden du ikke kommer utenom. I Palermo heter de <em>arancine</em>, hunkjønn og runde, i Catania <em>arancini</em>, hankjønn og ofte formet som en kjegle. Folk tar det på alvor, og ingen har noen gang latt seg overtale bort fra versjonen de vokste opp med.</p>'},
  ingredients:[
    { group:{en:'The rice', no:'Risen'}, items:[
      {q:400, u:'g', n:{en:'risotto rice', no:'risottoris'}, note:{en:'Arborio or Carnaroli', no:'Arborio eller Carnaroli'}},
      {q:900, u:'ml', n:{en:'water', no:'vann'}},
      {q:0.2, u:'g', n:{en:'saffron threads', no:'safrantråder'}, note:{en:'a good pinch, crumbled', no:'en god klype, smuldret'}},
      {q:40,  u:'g', n:{en:'butter', no:'smør'}},
      {q:60,  u:'g', n:{en:'caciocavallo or Pecorino', no:'caciocavallo eller Pecorino'}, note:{en:'finely grated', no:'finrevet'}},
      {q:1,   u:'', n:{en:'egg', no:'egg'}, round:'half'},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'The ragù filling', no:'Ragù-fyllet'}, items:[
      {q:200, u:'g', n:{en:'minced beef', no:'kjøttdeig av storfe'}},
      {q:100, u:'g', n:{en:'onion', no:'løk'}, note:{en:'finely chopped', no:'finhakket'}},
      {q:60,  u:'g', n:{en:'tomato purée', no:'tomatpuré'}},
      {q:60,  u:'ml', n:{en:'red wine', no:'rødvin'}},
      {q:100, u:'g', n:{en:'peas', no:'erter'}, note:{en:'frozen are fine', no:'frosne går fint'}},
      {q:20,  u:'ml', n:{en:'olive oil', no:'olivenolje'}},
    ]},
    { group:{en:'To coat and fry', no:'Til panering og fritering'}, items:[
      {q:80,  u:'g', n:{en:'plain flour', no:'hvetemel'}},
      {q:120, u:'ml', n:{en:'water for the batter', no:'vann til røren'}},
      {q:200, u:'g', n:{en:'fine dry breadcrumbs', no:'fint griljermel'}},
      {u:'', n:{en:'oil for deep-frying', no:'olje til fritering'}, note:{en:'a neutral oil, enough to float them', no:'en nøytral olje, nok til at de flyter'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Bring the water to the boil with the crumbled saffron and a little salt, so the colour goes right through the grains rather than sitting on the outside.',
     no:'Kok opp vannet med den smuldrede safranen og litt salt, slik at fargen trekker helt inn i kornene i stedet for å legge seg utenpå.'},
    {en:'Stir in the rice, cover, and cook over the lowest heat for about 15 minutes, until the water has gone and the grains are soft.',
     no:'Rør inn risen, legg på lokk, og la den koke på svakest mulig varme i omtrent 15 minutter, til vannet er borte og kornene er myke.'},
    {en:'Beat the butter and the grated cheese through the hot rice, then the egg, and spread it on a tray to cool completely. It has to be cold, not lukewarm.',
     no:'Rør smøret og den revne osten inn i den varme risen, deretter egget, og bre den ut på et brett så den kjølner helt. Den skal være kald, ikke lunken.'},
    {en:'Soften the onion in the oil, turn up the heat and brown the mince properly, then pour in the wine and let it evaporate.',
     no:'La løken mykne i oljen, skru opp varmen og brun kjøttdeigen skikkelig, og hell så i vinen og la den fordampe.'},
    {en:'Stir in the tomato purée with a splash of water and simmer for half an hour, until the ragù is dark and thick enough to hold its shape on a spoon. Add the peas for the last five minutes and let it cool.',
     no:'Rør inn tomatpureen med en skvett vann, og la det småkoke en halvtime, til ragùen er mørk og så tykk at den holder formen på en skje. Ha i ertene de siste fem minuttene, og la det kjølne.'},
    {en:'Wet your hands, take a handful of the cold rice and press it into a hollow in your palm.',
     no:'Fukt hendene, ta en neve av den kalde risen, og press den til en skål i håndflaten.'},
    {en:'Spoon the filling into the hollow, close more rice over the top and work it into a ball or a cone with no crack anywhere in the surface.',
     no:'Legg fyllet i fordypningen, dekk med mer ris, og form det til en kule eller en kjegle uten en eneste sprekk i overflaten.'},
    {en:'Whisk the flour and water into a thin, smooth batter, dip each arancino in it and roll it in the breadcrumbs.',
     no:'Visp melet og vannet til en tynn, jevn røre, dypp hver arancino i den, og rull den i griljermelet.'},
    {en:'Heat the frying oil to 175 °C and fry three or four at a time for about four minutes, turning them, until they are deep gold all over.',
     no:'Varm frityroljen til 175 °C, og friter tre eller fire om gangen i omtrent fire minutter mens du snur dem, til de er dypt gylne over alt.'},
    {en:'Drain them on a rack rather than on paper, and leave them five minutes before eating. The middle is far hotter than the crust.',
     no:'La dem renne av på en rist og ikke på papir, og vent fem minutter før du spiser dem. Midten er langt varmere enn skallet.'},
  ],
  notes:[
    {title:{en:'Cold rice, or nothing', no:'Kald ris, ellers ingenting'},
     body:{en:'As cooked rice cools, its starch recrystallises and the mass turns from loose to tacky. That tackiness is the only glue in the dish — there is no pastry and no egg wash holding the ball together. An hour in the fridge is not wasted time; it is the step that decides whether the arancini survive the oil.',
           no:'Når kokt ris kjølner, krystalliserer stivelsen seg på nytt, og massen går fra løs til klebrig. Den klebrigheten er det eneste limet i retten, for verken deig eller eggeglasur holder kulen sammen. En time i kjøleskapet er ikke bortkastet tid, men trinnet som avgjør om kulene overlever oljen.'}},
    {title:{en:'Batter, not egg', no:'Røre, ikke egg'},
     body:{en:'Palermo dips them in a flour-and-water slurry rather than beaten egg. The slurry sets into a seal that keeps oil out and filling in, and because it has no protein it browns slowly, which buys the four minutes the cold centre needs to become hot.',
           no:'I Palermo dyppes de i en røre av mel og vann i stedet for i sammenvispet egg. Røren stivner til en forsegling som holder oljen ute og fyllet inne, og siden den ikke inneholder protein, brunes den langsomt. Det gir de fire minuttene den kalde kjernen trenger for å bli varm.'}},
    {title:{en:'Why 175 °C and not hotter', no:'Hvorfor 175 °C og ikke mer'},
     body:{en:'Everything inside an arancino is already cooked, so the oil has one job: colour the crust while the heat travels to the middle. Hotter oil finishes the outside before the centre has warmed at all; cooler oil soaks in. Fry a few at a time so the temperature does not fall when they go in.',
           no:'Alt inne i en arancino er ferdig kokt, så oljen har bare én oppgave: gi skorpen farge mens varmen vandrer inn mot midten. Varmere olje gjør utsiden ferdig før kjernen har blitt varm i det hele tatt, og kaldere olje trekker inn. Friter noen få om gangen, slik at temperaturen ikke faller når de går i.'}},
  ],
  variations:[
    {title:{en:'Al burro', no:'Al burro'},
     body:{en:'The other classic filling: a thick béchamel with chopped ham and cubes of cheese, which melts into a string when you break the arancino open. It is the one children ask for, and it needs the same cold, firm rice.',
           no:'Det andre klassiske fyllet er en tykk béchamel med hakket skinke og terninger av ost, som smelter til en tråd når du bryter arancinoen. Det er den barna ber om, og den trenger den samme kalde og faste risen.'}},
    {title:{en:'Arancina or arancino', no:'Arancina eller arancino'},
     body:{en:'Round and feminine in Palermo, conical and masculine in Catania, where the shape is said to echo Etna. The rice, the saffron and the frying are identical; only the name and the silhouette change, and only those are worth arguing about.',
           no:'I Palermo er de runde og hunkjønn, i Catania kjegleformede og hankjønn, og formen skal etter sigende peke mot Etna. Risen, safranen og friteringen er de samme, og det er bare navnet og omrisset som skiller, og bare det som er verdt å krangle om.'}},
    {title:{en:'Made ahead', no:'Laget på forhånd'},
     body:{en:'Shape and bread them, then freeze them raw on a tray. Fry from frozen at 165 °C for about eight minutes: the lower temperature gives the ice in the centre time to go before the crust is done.',
           no:'Form dem og paner dem, og frys dem så rå på et brett. Friter dem rett fra fryseren på 165 °C i omtrent åtte minutter. Den lavere temperaturen gir isen i midten tid til å forsvinne før skorpen er ferdig.'}},
  ],
},

{
  id:'pasta-alla-norma', dish:'Pasta alla Norma', course:'primo', lesson:3, serves:4, time:{prep:40, cook:30},
  hero:'norma', tags:['pasta','aubergine','vegetarian'],
  title:{en:'Pasta alla Norma', no:'Pasta alla Norma'},
  blurb:{en:'Catania in four ingredients: tomato, fried aubergine, basil and ricotta salata grated over at the table.',
         no:'Catania i fire ingredienser: tomat, stekt aubergine, basilikum og ricotta salata revet over ved bordet.'},
  heroCaption:{en:'Pasta alla Norma, named after Bellini’s opera by a writer from the composer’s own city.',
               no:'Pasta alla Norma fikk navnet sitt etter Bellinis opera, gitt av en forfatter fra komponistens egen by.'},
  wines:['Etna Rosso (Nerello Mascalese)'],
  headnote:{
    en:'<p>The dish belongs to <strong>Catania</strong>, in the shadow of Etna, and it carries the name of Bellini’s opera because a local writer called a plate of it a masterpiece and the compliment stuck. The composer was born in the city; the pun has fed the restaurants there ever since.</p>'
      + '<p>The aubergine is the Arab half of the plate, and how you treat it is the whole recipe. Aubergine flesh is mostly air held in a foam of cell walls. Dropped into hot oil the foam collapses, the air goes out and the flesh turns silky and almost sweet. Roasted, it dries. Boiled, it slumps. It has to be fried, and it has to be fried properly hot.</p>'
      + '<p><strong>Ricotta salata</strong> is the fourth ingredient and not a garnish: sheep’s ricotta pressed, salted and dried until it can be grated. It goes over the finished plate and never into the pan, because heat turns it to rubber and because its saltiness is what the sweet aubergine is measured against.</p>',
    no:'<p>Retten hører til i <strong>Catania</strong> i skyggen av Etna, og den bærer navnet på Bellinis opera fordi en lokal forfatter kalte en tallerken av den et mesterverk, og komplimentet ble hengende. Komponisten ble født i byen, og ordspillet har holdt liv i restaurantene der siden.</p>'
      + '<p>Auberginen er den arabiske halvdelen av tallerkenen, og hele oppskriften ligger i hvordan du behandler den. Auberginekjøtt består for det meste av luft som holdes oppe av et skum av cellevegger. Slipper du det i varm olje, faller skummet sammen, luften går ut, og kjøttet blir silkemykt og nesten søtt. I ovnen tørker det ut, og i kokende vann faller det sammen til grøt. Det må stekes i olje, og oljen må være ordentlig varm.</p>'
      + '<p><strong>Ricotta salata</strong> er den fjerde ingrediensen og ingen pynt: ricotta av sauemelk som er presset, saltet og tørket til den lar seg rive. Den går over den ferdige retten og aldri oppi pannen, for varme gjør den gummiaktig, og saltet i den er det den søte auberginen måles mot.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:400, u:'g', n:{en:'rigatoni or maccheroni', no:'rigatoni eller maccheroni'}, note:{en:'a ridged shape holds the sauce', no:'en form med riller holder på sausen'}},
    {q:600, u:'g', n:{en:'aubergines', no:'auberginer'}, note:{en:'two large ones, skin left on', no:'to store, med skallet på'}},
    {q:500, u:'g', n:{en:'peeled plum tomatoes', no:'hermetiske plommetomater'}, note:{en:'crushed by hand', no:'most med hendene'}},
    {q:1,   u:'', n:{en:'garlic clove', no:'hvitløksfedd'}, round:'half'},
    {q:80,  u:'g', n:{en:'ricotta salata', no:'ricotta salata'}, note:{en:'pressed, salted, dried sheep’s ricotta', no:'presset, saltet og tørket ricotta av sauemelk'}},
    {u:'', n:{en:'basil', no:'basilikum'}, note:{en:'a good handful of leaves', no:'en god neve blader'}, scale:'none'},
    {u:'', n:{en:'olive oil for frying', no:'olivenolje til steking'}, scale:'none'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {q:3,   u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:15,  u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
  ]}],
  steps:[
    {en:'Cut the aubergines into cubes of about 2 cm, skin and all.',
     no:'Skjær auberginene i terninger på rundt 2 cm, med skall og alt.'},
    {en:'Salt them in a colander and leave them to drain for half an hour, then press them and dry them well. Wet cubes spit and steam instead of frying.',
     no:'Salt dem i et dørslag og la dem renne av seg en halvtime. Klem dem så og tørk dem godt, for våte terninger spruter og damper i stedet for å steke.'},
    {en:'Fry them in a finger’s depth of hot oil, in batches so the pan stays hot, until they are dark gold and soft all the way through. Drain them on a rack and salt them lightly.',
     no:'Stek dem i olje som står en fingerbredd høyt i pannen, i flere omganger så pannen holder på varmen, til de er dypt gylne og myke tvers igjennom. La dem renne av på en rist, og salt dem lett.'},
    {en:'Bruise the garlic clove, warm it in a clean pan with a little oil until it smells, and lift it out before it colours.',
     no:'Knus hvitløksfeddet, varm det i en ren panne med litt olje til det dufter, og løft det ut før det får farge.'},
    {en:'Crush the tomatoes into the pan and simmer over low heat for about 20 minutes, until the sauce darkens and the oil separates at the edges.',
     no:'Mos tomatene ned i pannen, og la sausen småkoke på svak varme i omtrent 20 minutter, til den mørkner og oljen skiller seg ut i kantene.'},
    {en:'Tear in half the basil and fold two thirds of the fried aubergine into the sauce, keeping the rest back.',
     no:'Riv i halvparten av basilikumen, og vend to tredeler av den stekte auberginen inn i sausen. Hold resten tilbake.'},
    {en:'Boil the pasta in salted water and drain it a minute before al dente, keeping some of the water.',
     no:'Kok pastaen i saltet vann, og hell av vannet ett minutt før den er al dente. Ta vare på noe av kokevannet.'},
    {en:'Toss the pasta through the sauce over the heat for a minute, loosening it with the cooking water until every piece is coated.',
     no:'Vend pastaen i sausen over varmen i ett minutt, og spe med kokevann til hver bit er dekket.'},
    {en:'Serve with the reserved aubergine and the rest of the basil on top, and grate the ricotta salata over each plate at the table.',
     no:'Server med auberginen du holdt av og resten av basilikumen på toppen, og riv ricotta salata over hver tallerken ved bordet.'},
  ],
  notes:[
    {title:{en:'Salting is about oil, not bitterness', no:'Saltingen handler om olje, ikke bitterhet'},
     body:{en:'Modern aubergines are bred sweet, so the old reason for salting has gone. The reason that remains is better: salt pulls water out of the cells and collapses the sponge, so the cubes drink a fraction of the oil they otherwise would and fry rather than boil in it.',
           no:'Dagens auberginer er foredlet til å være søte, så den gamle grunnen til å salte dem er borte. Grunnen som står igjen, er bedre: saltet trekker vann ut av cellene og får svampen til å falle sammen, slik at terningene suger til seg en brøkdel av oljen og steker i stedet for å koke i den.'}},
    {title:{en:'Two textures of aubergine', no:'To teksturer av aubergine'},
     body:{en:'Most of the aubergine goes into the sauce and dissolves into it; the handful kept back stays whole and gives the plate something to bite on. Any vegetable sauce is better for holding a little of itself in reserve.',
           no:'Mesteparten av auberginen går i sausen og løser seg opp i den, mens neven du holdt av, blir hel og gir tallerkenen noe å tygge på. Enhver grønnsakssaus blir bedre av at litt av den holdes tilbake.'}},
    {title:{en:'The cheese never meets the heat', no:'Osten møter aldri varmen'},
     body:{en:'Ricotta salata is a fresh cheese that has been dried, not a hard cheese that has been aged, and it has no melting behaviour worth the name. In the pan it tightens into threads. Grated cold onto a hot plate it softens just enough and keeps its salt.',
           no:'Ricotta salata er en fersk ost som er tørket, ikke en fast ost som er lagret, og den smelter ikke på noen brukbar måte. I pannen trekker den seg sammen til tråder. Rives den kald over en varm tallerken, mykner den akkurat passe og beholder saltet sitt.'}},
  ],
  variations:[
    {title:{en:'Cubes or slices', no:'Terninger eller skiver'},
     body:{en:'Catania fries long slices as often as cubes and lays them over the pasta whole, which looks better and eats messier. The frying is identical either way.',
           no:'I Catania stekes lange skiver like ofte som terninger, og de legges hele over pastaen. Det ser bedre ut og er vanskeligere å spise. Stekingen er den samme uansett.'}},
    {title:{en:'Ricotta infornata', no:'Ricotta infornata'},
     body:{en:'Some kitchens use ricotta infornata instead, baked rather than dried, browner and nuttier. It is a fair swap. Parmigiano is not: it is sweeter and cow’s milk, and it turns the dish into a generic aubergine pasta.',
           no:'Noen kjøkken bruker ricotta infornata i stedet, som er bakt og ikke tørket, brunere og mer nøtteaktig. Det er et rimelig bytte. Parmigiano er det ikke, for den er søtere og laget av kumelk, og den gjør retten til en helt vanlig auberginepasta.'}},
    {title:{en:'If you will not deep-fry', no:'Hvis du ikke vil steke i olje'},
     body:{en:'Toss the cubes in oil and roast them at 220 °C until they collapse. You get a good plate of pasta with roast aubergine in it, and it is honest to call it that rather than Norma.',
           no:'Vend terningene i olje og stek dem i ovnen på 220 °C til de faller sammen. Da får du en god tallerken pasta med ovnsbakt aubergine, og det er ærlig å kalle den nettopp det og ikke Norma.'}},
  ],
},

{
  id:'caponata', dish:'Caponata', course:'contorno', lesson:3, serves:6, time:{prep:45, cook:40},
  hero:'caponata', tags:['aubergine','agrodolce','vegetarian'],
  title:{en:'Caponata', no:'Caponata'},
  blurb:{en:'The emblem of Sicilian agrodolce: fried aubergine, celery, olives and capers, sharpened with vinegar and sugar and eaten the next day.',
         no:'Selve symbolet på siciliansk agrodolce: stekt aubergine, selleri, oliven og kapers, skjerpet med eddik og sukker og spist dagen etter.'},
  heroCaption:{en:'Caponata is served at room temperature, and it is better on the second day than on the first.',
               no:'Caponata serveres ved romtemperatur, og den er bedre den andre dagen enn den første.'},
  wines:['Grillo'],
  headnote:{
    en:'<p><em>Agrodolce</em>, sweet and sour, is the signature of the Sicilian kitchen, and caponata is its emblem. The sourness is vinegar, the sweetness is sugar and sometimes raisins, and both sides of the balance are part of what two hundred years of Arab rule left behind, along with the aubergine itself.</p>'
      + '<p>The method looks laborious because every vegetable is cooked on its own before they meet. That is not fussiness. Aubergine wants hot oil, celery wants two minutes of boiling water, onion wants low heat and time. Cook them together in one pan and you get a stew in which nothing is recognisable; cook them apart and you can still tell what you are eating.</p>'
      + '<p>What is not negotiable is the resting. Caponata made an hour before dinner tastes of frying and raw vinegar. Left overnight it tastes of itself, and it is served at room temperature — never straight from the fridge, which shuts the whole thing down.</p>',
    no:'<p><em>Agrodolce</em>, altså det sursøte, er kjennetegnet på det sicilianske kjøkkenet, og caponata er symbolet på det. Det sure er eddik, det søte er sukker og iblant rosiner, og begge sider av balansen hører til arven etter to hundre år med arabisk styre, sammen med auberginen selv.</p>'
      + '<p>Framgangsmåten ser omstendelig ut fordi hver grønnsak tilberedes for seg før de møtes. Det er ikke pirk. Auberginen vil ha varm olje, sellerien vil ha to minutter i kokende vann, og løken vil ha svak varme og tid. Koker du dem sammen i én panne, får du en gryte der ingenting lar seg kjenne igjen. Holder du dem fra hverandre, vet du fortsatt hva du spiser.</p>'
      + '<p>Hviletiden er det ingen vei utenom. Caponata som lages en time før middag, smaker av steking og rå eddik. Får den stå over natten, smaker den av seg selv, og den serveres ved romtemperatur, aldri rett fra kjøleskapet, som lukker igjen hele retten.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:800, u:'g', n:{en:'aubergines', no:'auberginer'}, note:{en:'in cubes of about 2 cm', no:'i terninger på rundt 2 cm'}},
    {q:200, u:'g', n:{en:'celery', no:'stangselleri'}, note:{en:'the pale inner stalks, in slices of 1 cm', no:'de lyse indre stilkene, i skiver på 1 cm'}},
    {q:200, u:'g', n:{en:'onion', no:'løk'}, note:{en:'sliced thin', no:'skåret i tynne skiver'}},
    {q:400, u:'g', n:{en:'peeled plum tomatoes', no:'hermetiske plommetomater'}},
    {q:100, u:'g', n:{en:'green olives', no:'grønne oliven'}, note:{en:'pitted and torn in half', no:'uten stein og revet i to'}},
    {q:40,  u:'g', n:{en:'capers', no:'kapers'}, note:{en:'salted, rinsed and soaked briefly', no:'saltet, skylt og lagt kort i vann'}},
    {q:60,  u:'ml', n:{en:'white wine vinegar', no:'hvitvinseddik'}},
    {q:30,  u:'g', n:{en:'sugar', no:'sukker'}},
    {q:30,  u:'g', n:{en:'pine nuts', no:'pinjekjerner'}},
    {q:30,  u:'g', n:{en:'raisins', no:'rosiner'}, note:{en:'optional, and the eastern half of the island is fonder of them', no:'valgfritt, og den østlige halvdelen av øya er gladere i dem'}},
    {u:'', n:{en:'olive oil for frying', no:'olivenolje til steking'}, scale:'none'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {u:'', n:{en:'basil', no:'basilikum'}, note:{en:'to finish', no:'til slutt'}, scale:'none'},
  ]}],
  steps:[
    {en:'Cube the aubergines, salt them in a colander and leave them for half an hour, then press them and pat them dry.',
     no:'Skjær auberginene i terninger, salt dem i et dørslag og la dem stå en halvtime. Klem dem så og tørk dem.'},
    {en:'Blanch the celery in boiling salted water for two or three minutes, until it bends without snapping, and drain it.',
     no:'Forvell sellerien i kokende, saltet vann i to eller tre minutter, til den bøyer seg uten å knekke, og hell av vannet.'},
    {en:'Fry the aubergine in hot oil in batches until it is dark gold and soft, and drain it on a rack.',
     no:'Stek auberginen i varm olje i flere omganger til den er dypt gylden og myk, og la den renne av på en rist.'},
    {en:'Soften the onion in a little of the same oil over low heat for about ten minutes, without letting it colour.',
     no:'La løken mykne i litt av den samme oljen på svak varme i omtrent ti minutter, uten at den får farge.'},
    {en:'Add the celery, fry it for a few minutes, then crush in the tomatoes and simmer for about ten minutes.',
     no:'Ha i sellerien, stek den et par minutter, mos så tomatene oppi, og la det småkoke i omtrent ti minutter.'},
    {en:'Stir in the olives, capers, pine nuts and raisins and cook for two minutes more.',
     no:'Rør inn oliven, kapers, pinjekjerner og rosiner, og la det koke to minutter til.'},
    {en:'Dissolve the sugar in the vinegar, pour it into the pan and let it boil hard until the sharp smell has gone and what is left is a glaze.',
     no:'Løs sukkeret i eddiken, hell det i pannen, og la det koke kraftig til den skarpe lukten er borte og det bare står igjen en glasur.'},
    {en:'Fold the aubergine back in with a light hand, off the heat, so the cubes stay whole.',
     no:'Vend auberginen forsiktig inn igjen med pannen av platen, slik at terningene holder seg hele.'},
    {en:'Taste for salt and for the balance: it should read sour first and sweet a moment later, not the other way round.',
     no:'Smak til med salt, og kjenn etter balansen. Den skal smake surt først og søtt et øyeblikk etter, ikke omvendt.'},
    {en:'Cool it to room temperature, cover it and leave it at least overnight. Tear basil over it just before it goes to the table.',
     no:'Kjøl den ned til romtemperatur, dekk den til, og la den stå minst natten over. Riv basilikum over den rett før den settes på bordet.'},
  ],
  notes:[
    {title:{en:'Boil the vinegar, do not stir it in', no:'Kok eddiken, ikke bare rør den inn'},
     body:{en:'Acetic acid is volatile and most of the raw, catching smell of vinegar leaves with the steam. What stays behind is the acidity itself, and the sugar dissolved in it reduces to a glaze that coats rather than sweetens. A minute of hard boiling is the difference between a dressing and a sauce.',
           no:'Eddiksyre er flyktig, og det meste av den rå, stikkende lukten forsvinner med dampen. Igjen blir selve syrligheten, og sukkeret som er løst i eddiken, koker inn til en glasur som legger seg rundt grønnsakene i stedet for å søte dem. Ett minutt med kraftig koking er forskjellen på en dressing og en saus.'}},
    {title:{en:'Why the second day is better', no:'Hvorfor den andre dagen er bedre'},
     body:{en:'Fried aubergine goes on drinking for hours after it leaves the pan. Overnight it takes up the vinegar, the oil and the tomato, and the salt spreads evenly through everything, so the separate dishes you cooked finally become one. This is why caponata is made in quantity and never in a hurry.',
           no:'Stekt aubergine fortsetter å suge til seg i timevis etter at den forlater pannen. Over natten trekker den til seg eddiken, oljen og tomaten, og saltet fordeler seg jevnt i alt, slik at de adskilte rettene du laget, endelig blir én. Derfor lages caponata i store mengder og aldri i hui og hast.'}},
    {title:{en:'Room temperature is a temperature', no:'Romtemperatur er en temperatur'},
     body:{en:'Cold blunts both acid and aroma, which is exactly what caponata has instead of richness. Take it out of the fridge a good hour before it is eaten, and it wakes up.',
           no:'Kulde sløver både syre og aroma, og det er nettopp dem caponata har i stedet for fyldighet. Ta den ut av kjøleskapet en god time før den skal spises, så våkner den.'}},
  ],
  variations:[
    {title:{en:'With cocoa or chocolate', no:'Med kakao eller sjokolade'},
     body:{en:'Sicilians argue about this one. Some cooks grate a little bitter chocolate, or dust a spoonful of unsweetened cocoa, into the pan with the vinegar. It darkens the dish and adds a faint bitterness behind the sweet and sour rather than any taste of chocolate. Others regard it as an affectation.',
           no:'Her er sicilianerne uenige. Noen river litt mørk sjokolade eller drysser en skje usøtet kakao i pannen sammen med eddiken. Det gjør retten mørkere og legger en svak bitterhet bak det sursøte, uten at den smaker av sjokolade. Andre ser på det som fine fakter.'}},
    {title:{en:'Raisins and pine nuts', no:'Rosiner og pinjekjerner'},
     body:{en:'The most Arab part of the dish, and the part most often left out. Without them the caponata is sharper and more savoury; with them it leans towards the sweet-and-sour side, which is where the older recipes sit.',
           no:'Dette er den mest arabiske delen av retten, og den som oftest utelates. Uten dem blir caponataen skarpere og mer smaksrik, med dem heller den mot det sursøte, og der ligger de eldste oppskriftene.'}},
    {title:{en:'Peppers, potato, almonds', no:'Paprika, potet, mandler'},
     body:{en:'Almost every town has its own additions: roasted red pepper, cubes of fried potato to stretch it, toasted almonds instead of pine nuts. The frame — fried aubergine, celery, the boiled vinegar — is what makes it caponata.',
           no:'Nesten hver by har sine egne tilskudd: ovnsstekt paprika, terninger av stekt potet for å drøye retten, ristede mandler i stedet for pinjekjerner. Rammen er det som gjør den til caponata: stekt aubergine, selleri og den innkokte eddiken.'}},
  ],
},

{
  id:'pasta-con-le-sarde', dish:'Pasta con le sarde', course:'primo', lesson:3, serves:4, time:{prep:30, cook:35},
  hero:'sarde', tags:['pasta','fish','fennel'],
  title:{en:'Pasta con le sarde', no:'Pasta con le sarde'},
  blurb:{en:'The dish of Palermo: fresh sardines, wild fennel, pine nuts, raisins and saffron on bucatini, with toasted crumbs instead of cheese.',
         no:'Palermos egen rett: ferske sardiner, villfennikel, pinjekjerner, rosiner og safran på bucatini, med ristede brødsmuler i stedet for ost.'},
  heroCaption:{en:'Arab pantry and Sicilian sea in one bowl, with wild fennel running through it.',
               no:'Det arabiske spiskammeret og det sicilianske havet i én tallerken, med villfennikel gjennom det hele.'},
  wines:['Grillo'],
  headnote:{
    en:'<p>If one plate had to stand for Palermo, it would be this one. Fresh sardines come from the sea in front of the city; the pine nuts, the raisins and the saffron come from the Arab pantry that arrived with the emirate; and the wild fennel that binds them grows on every roadside in Sicily in spring. Arab pantry, Sicilian sea, in one bowl.</p>'
      + '<p>The technique worth stealing is what you do with the fennel. Boil it first, keep the green water, and cook the pasta in it. The flavour then comes at the dish from inside the pasta as well as from the sauce, and no amount of chopped herb stirred in at the end can do the same thing.</p>'
      + '<p>Two rules. The sardines must be fresh and filleted, not tinned, because half of them are meant to stay in recognisable pieces. And there is no cheese: toasted breadcrumbs go on top instead, which give the salt and the crunch that cheese would, on a plate where Sicily would never put it.</p>',
    no:'<p>Skulle én tallerken stå for Palermo, måtte det bli denne. De ferske sardinene kommer fra havet rett utenfor byen, pinjekjernene, rosinene og safranen kommer fra det arabiske spiskammeret som kom med emiratet, og villfennikelen som binder det sammen, vokser i hver veikant på Sicilia om våren. Det arabiske spiskammeret og det sicilianske havet på én tallerken.</p>'
      + '<p>Fennikelen gir deg teknikken det er verdt å stjele. Kok den først, ta vare på det grønne vannet, og kok pastaen i det. Da kommer smaken innenfra pastaen og ikke bare fra sausen, og ingen mengde hakkede urter rørt inn til slutt gjør den samme jobben.</p>'
      + '<p>To regler. Sardinene må være ferske og filetert, ikke hermetiske, for halvparten av dem skal bli liggende i biter man kjenner igjen. Og ost er utelukket. I stedet strøs ristede brødsmuler over, og de gir saltet og sprøheten osten ville gitt, på en tallerken der Sicilia aldri ville lagt ost.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:400, u:'g', n:{en:'bucatini', no:'bucatini'}, note:{en:'the hollow strand is traditional here', no:'den hule tråden er det tradisjonelle her'}},
    {q:500, u:'g', n:{en:'fresh sardines', no:'ferske sardiner'}, note:{en:'weight before cleaning; ask the fishmonger to fillet them', no:'vekt før rensing; be fiskehandleren filetere dem'}},
    {q:300, u:'g', n:{en:'wild fennel', no:'villfennikel'}, note:{en:'the green fronds only, thick stalks discarded', no:'bare de grønne toppene, uten de grove stilkene'}},
    {q:4,   u:'', n:{en:'salted anchovy fillets', no:'ansjosfileter i salt'}, note:{en:'rinsed', no:'skylt'}, round:'half'},
    {q:150, u:'g', n:{en:'onion', no:'løk'}, note:{en:'sliced thin', no:'skåret i tynne skiver'}},
    {q:40,  u:'g', n:{en:'raisins', no:'rosiner'}, note:{en:'soaked in warm water and drained', no:'lagt i varmt vann og latt renne av'}},
    {q:40,  u:'g', n:{en:'pine nuts', no:'pinjekjerner'}},
    {q:0.2, u:'g', n:{en:'saffron threads', no:'safrantråder'}, note:{en:'a good pinch', no:'en god klype'}},
    {q:60,  u:'ml', n:{en:'olive oil', no:'olivenolje'}},
    {q:60,  u:'g', n:{en:'coarse breadcrumbs', no:'grove brødsmuler'}, note:{en:'from dry bread, not from a packet', no:'av tørt brød, ikke fra pose'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {q:3,   u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
    {q:15,  u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
  ]}],
  steps:[
    {en:'Boil the fennel fronds in the salted water for about ten minutes, until they are completely limp. Lift them out and keep every drop of the water: the pasta cooks in it.',
     no:'Kok fennikeltoppene i det saltede vannet i omtrent ti minutter, til de er helt slappe. Løft dem ut, og ta vare på hver dråpe av vannet, for pastaen skal koke i det.'},
    {en:'Squeeze the fennel dry and chop it coarsely.',
     no:'Klem fennikelen tørr, og hakk den grovt.'},
    {en:'Steep the saffron in a ladleful of the hot fennel water and leave it to bleed.',
     no:'Legg safranen i en øse med varmt fennikelvann, og la den trekke ut fargen.'},
    {en:'Toast the breadcrumbs in a dry pan with a thread of oil until they are brown and crisp, then tip them onto a plate so they stop cooking.',
     no:'Rist brødsmulene i en tørr panne med en skvett olje til de er brune og sprø, og ha dem over på en tallerken så de slutter å steke.'},
    {en:'Soften the onion in the oil over low heat, then add the anchovies and press them with a wooden spoon until they have melted into the oil.',
     no:'La løken mykne i oljen på svak varme, ha så i ansjosen, og press den med en tresleiv til den har smeltet inn i oljen.'},
    {en:'Add the chopped fennel, the drained raisins, the pine nuts and the saffron water, and cook for five minutes.',
     no:'Ha i den hakkede fennikelen, rosinene, pinjekjernene og safranvannet, og la det koke i fem minutter.'},
    {en:'Lay the sardine fillets on top, cover the pan and cook gently for about five minutes, until they are just opaque.',
     no:'Legg sardinfiletene oppå, legg lokk på pannen, og la dem trekke i omtrent fem minutter, til kjøttet så vidt er blitt hvitt.'},
    {en:'Break them up with a fork, but only half of them; the rest should stay in pieces you can see.',
     no:'Del dem opp med en gaffel, men bare halvparten av dem. Resten skal bli liggende i biter du kan se.'},
    {en:'Boil the bucatini in the fennel water and drain it a minute before al dente, keeping some of the water.',
     no:'Kok bucatinien i fennikelvannet, og hell av vannet ett minutt før den er al dente. Ta vare på noe av det.'},
    {en:'Toss the pasta through the sauce off the heat, loosening it with the cooking water, and serve with the toasted crumbs over the top. No cheese.',
     no:'Vend pastaen i sausen med pannen av platen, spe med kokevann, og server med de ristede brødsmulene over. Ingen ost.'},
  ],
  notes:[
    {title:{en:'Cook the pasta in the fennel water', no:'Kok pastaen i fennikelvannet'},
     body:{en:'Pasta absorbs roughly its own weight in water, and whatever is dissolved in that water goes in with it. Boiling the fennel first turns the pot into a broth and seasons the strands from the inside. The same trick works for broccoli, chard or any strong green you were going to throw the water away from.',
           no:'Pasta tar opp omtrent sin egen vekt i vann, og alt som er løst i det vannet, følger med inn. Ved å koke fennikelen først gjør du kjelen om til en kraft som smaksetter trådene innenfra. Det samme trikset virker med brokkoli, mangold eller enhver kraftig grønnsak du ellers ville ha kastet kokevannet fra.'}},
    {title:{en:'Breadcrumbs are the poor man’s cheese', no:'Brødsmuler er den fattiges ost'},
     body:{en:'Toasted crumbs bring salt, crunch and a roasted savour, which is most of what grated cheese does on a plate of pasta. Sicily uses them wherever there is fish, and once you have tried them there you start reaching for them elsewhere.',
           no:'Ristede brødsmuler gir salt, sprøhet og en ristet smak, og det er stort sett det revet ost gjør på en tallerken pasta. På Sicilia brukes de overalt der det er fisk, og har du først prøvd dem der, begynner du å ty til dem ellers også.'}},
    {title:{en:'Anchovy is seasoning, not fish', no:'Ansjos er krydder, ikke fisk'},
     body:{en:'A salted anchovy pressed into warm oil dissolves completely and leaves no fishiness at all, only depth and salt. Judge the salt of the whole dish after the anchovies have gone in, never before.',
           no:'En saltet ansjos som presses ut i varm olje, løser seg helt opp og etterlater ingen fiskesmak, bare dybde og salt. Smak til saltet i hele retten etter at ansjosen har gått i, aldri før.'}},
  ],
  variations:[
    {title:{en:'Without the wild fennel', no:'Uten villfennikel'},
     body:{en:'Outside Sicily it is hard to find. The nearest thing is the feathery tops of two or three fennel bulbs with a little dill worked in, boiled the same way so you still get the green cooking water. It is not the same herb, but it is the same idea.',
           no:'Utenfor Sicilia er den vanskelig å få tak i. Det nærmeste er de fjærlette toppene fra et par fennikelknoller med litt dill blandet inn. Kok dem på samme måte, slik at du fortsatt får det grønne kokevannet. Det er ikke den samme urten, men det er den samme tanken.'}},
    {title:{en:'A mare, with the sardines at sea', no:'A mare, med sardinene til havs'},
     body:{en:'Palermo has a version called <em>pasta con le sarde a mare</em>, sardines still in the sea: everything else stays, fennel, saffron, raisins, pine nuts, anchovy and crumbs, and the fish is simply left out. It is what people cooked on a day with no money, and it is a good dish in its own right.',
           no:'I Palermo finnes en variant som kalles <em>pasta con le sarde a mare</em>, altså med sardinene fortsatt til havs. Alt annet blir stående, både fennikel, safran, rosiner, pinjekjerner, ansjos og brødsmuler, og fisken utelates ganske enkelt. Slik lagde folk den på en dag uten penger, og den er god i seg selv.'}},
    {title:{en:'Baked', no:'Bakt i ovnen'},
     body:{en:'Some cooks tip the dressed pasta into a dish, cover it with more crumbs and give it twenty minutes at 200 °C, so it sets firm enough to cut. It is what gets made for a crowd, and it can be carried to the table cold.',
           no:'Noen har den ferdig blandede pastaen over i en form, dekker den med flere brødsmuler og gir den tjue minutter på 200 °C, slik at den stivner nok til å kunne skjæres. Det er slik den lages til mange, og den kan settes på bordet kald.'}},
  ],
},

{
  id:'granita-al-limone', dish:'Granita', course:'dolce', lesson:3, serves:4, time:{prep:20, cook:5},
  hero:'granita', tags:['ice','lemon','breakfast'],
  title:{en:'Granita al limone', no:'Granita al limone'},
  blurb:{en:'Three ingredients, a fork and a freezer. In Sicily this is breakfast, eaten with a brioche for dipping.',
         no:'Tre ingredienser, en gaffel og en fryser. På Sicilia er dette frokost, spist med en brioche til å dyppe.'},
  heroCaption:{en:'Granita with a brioche col tuppo. The dish descends from Arab sharbat and the medieval trade in mountain snow.',
               no:'Granita med en brioche col tuppo. Retten stammer fra arabisk sharbat og middelalderens handel med snø fra fjellene.'},
  wines:[],
  headnote:{
    en:'<p>Granita descends from Arab <em>sharbat</em> and from a trade that sounds impossible: snow cut on Etna and the Madonie in winter, packed into insulated pits and sold through the Sicilian summer. Sugar, citrus and the taste for iced drinks all reached the island in the same two centuries, and granita is what they became.</p>'
      + '<p>It is not a slush of shaved ice, and it is not a sorbet. What you are making is a smooth, semi-frozen water ice, and the smoothness comes from two things only: enough dissolved sugar to stop the mixture freezing into a block, and a fork dragged through it every half hour so the crystals stay small.</p>'
      + '<p>The proportion is the recipe — roughly one part sugar to five parts liquid. Less sugar and you get a lemon ice cube you have to chip at. More and it never sets. And in Sicily it is eaten at eight in the morning with a <em>brioche col tuppo</em>, which is the part visitors find hardest to believe.</p>',
    no:'<p>Granita stammer fra arabisk <em>sharbat</em> og fra en handel som høres umulig ut: snø som ble skåret ut på Etna og i Madonie-fjellene om vinteren, pakket i isolerte groper og solgt gjennom hele den sicilianske sommeren. Sukkeret, sitrusen og forkjærligheten for iskalde drikker kom til øya i de samme to århundrene, og granita er det de ble til.</p>'
      + '<p>Dette er verken en slush av knust is eller en sorbet. Du lager en glatt, halvfrossen vannis, og glattheten kommer bare fra to ting: nok oppløst sukker til at blandingen ikke fryser til en blokk, og en gaffel som dras gjennom den hver halvtime slik at krystallene holder seg små.</p>'
      + '<p>Forholdet mellom delene er selve oppskriften, omtrent én del sukker til fem deler væske. Med mindre sukker får du en sitronisbit du må hakke løs, og med mer stivner den aldri. Og på Sicilia spises den klokken åtte om morgenen med en <em>brioche col tuppo</em>, og det er den delen tilreisende har vanskeligst for å tro på.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:600, u:'ml', n:{en:'water', no:'vann'}},
    {q:160, u:'g', n:{en:'sugar', no:'sukker'}},
    {q:200, u:'ml', n:{en:'lemon juice', no:'sitronsaft'}, note:{en:'freshly squeezed and strained, from six or seven lemons', no:'nypresset og silt, fra seks eller sju sitroner'}},
    {q:2,   u:'', n:{en:'unwaxed lemons, for the zest', no:'ubehandlede sitroner, til skallet'}, note:{en:'two of the ones you are juicing', no:'to av dem du likevel skal presse'}, round:'half'},
  ]}],
  steps:[
    {en:'Pare the zest from the lemons in wide strips, taking none of the white pith with it.',
     no:'Skrell skallet av sitronene i brede strimler, uten å få med noe av det hvite.'},
    {en:'Warm the water with the sugar and the strips of zest, stirring only until the sugar has dissolved, then take the pan off the heat.',
     no:'Varm vannet med sukkeret og skallstrimlene, rør bare til sukkeret har løst seg, og ta kjelen av platen.'},
    {en:'Leave the syrup to cool completely with the zest still in it. The oil in the peel is where most of the lemon smell lives.',
     no:'La sukkerlaken kjølne helt med skallet fortsatt i. Oljen i skallet er der det meste av sitronduften sitter.'},
    {en:'Squeeze and strain the juice and stir it into the cold syrup. Never into a warm one, which cooks the juice and flattens it.',
     no:'Press saften, sil den, og rør den inn i den kalde laken. Aldri i en varm, for da kokes saften og blir flat.'},
    {en:'Fish out the zest and taste. It should be a shade too sweet and a shade too sharp, because cold flattens both.',
     no:'Fisk ut skallet og smak. Den skal være et hakk for søt og et hakk for syrlig, siden kulden demper begge deler.'},
    {en:'Pour it into a wide, shallow metal tray and put it in the freezer.',
     no:'Hell den i en vid, grunn form av metall, og sett den i fryseren.'},
    {en:'After half an hour, when a rim of ice has set around the edge, drag a fork through it and scrape that ice back into the liquid.',
     no:'Etter en halvtime, når det har lagt seg en kant av is langs sidene, drar du en gaffel gjennom den og skraper isen tilbake i væsken.'},
    {en:'Repeat every half hour for about three hours, until the whole tray is an even, fine-grained ice with no solid block left in it.',
     no:'Gjenta hver halvtime i omtrent tre timer, til hele formen er en jevn, finkornet is uten en eneste fast klump igjen.'},
    {en:'Serve it soft, in a chilled glass, with a brioche to dip. Granita stiffens if it is left alone, so scrape it once more before it goes out.',
     no:'Server den myk, i et kaldt glass, med en brioche til å dyppe. Granita stivner om den blir stående, så skrap den én gang til før den settes fram.'},
  ],
  notes:[
    {title:{en:'Sugar is antifreeze', no:'Sukker er frostvæske'},
     body:{en:'Dissolved sugar lowers the freezing point of water, so a syrup at this strength never freezes solid: it stays a slurry of ice crystals in a syrup that is still liquid. That is the whole physics of granita, and it is why cutting the sugar to make it healthier produces something you cannot get a spoon into.',
           no:'Oppløst sukker senker frysepunktet til vann, så en lake av denne styrken fryser aldri helt. Den forblir en grøt av iskrystaller i en sirup som ennå er flytende. Det er hele fysikken bak granita, og kutter du sukkeret for helsens skyld, får du noe du ikke får skjeen ned i.'}},
    {title:{en:'Wide, shallow, metal, and scraped often', no:'Vid, grunn, i metall, og skrapt ofte'},
     body:{en:'Metal conducts and a shallow layer freezes fast, and fast freezing grows small crystals. Every scrape breaks the crystals that have formed and mixes the cold edge into the warm middle. Skip two scrapes and you get a block; blitz the block in a machine and you get shards that melt to lemonade in the glass.',
           no:'Metall leder kulden, og et grunt lag fryser fort, og rask frysing gir små krystaller. Hver skraping bryter opp krystallene som har dannet seg, og blander den kalde kanten inn i den varme midten. Hopper du over to skrapinger, får du en blokk, og kjører du blokken i en maskin, får du splinter som smelter til limonade i glasset.'}},
  ],
  variations:[
    {title:{en:'Almond', no:'Mandel'},
     body:{en:'The Palermo favourite, and no cooking at all: blend blanched almonds with water and sugar, leave the milk to stand, strain it and freeze it exactly as above. It comes out white, faintly bitter and the best of them all.',
           no:'Dette er favoritten i Palermo, og den krever ingen koking. Kjør skåldede mandler med vann og sukker, la melken stå og trekke, sil den, og frys den akkurat som over. Den blir hvit, så vidt bitter, og den beste av dem alle.'}},
    {title:{en:'Coffee', no:'Kaffe'},
     body:{en:'Sweeten strong espresso while it is hot, cool it and freeze it the same way. It is served with unsweetened whipped cream both under and over it, and it is what a Sicilian office worker has instead of a hot cup in August.',
           no:'Ha sukker i sterk espresso mens den er varm, kjøl den ned, og frys den på samme måte. Den serveres med usøtet pisket krem både under og over, og det er den en siciliansk kontorarbeider tar i stedet for en varm kopp i august.'}},
    {title:{en:'Whatever is ripe', no:'Det som er modent'},
     body:{en:'Mulberry, strawberry, mandarin, peach: purée the fruit, sieve it and use it in place of the juice. Ripe fruit brings sugar of its own, so taste the mixture before it goes into the freezer and hold back some of the sugar until you have.',
           no:'Morbær, jordbær, mandarin og fersken går alle an. Mos frukten, sil den, og bruk den i stedet for saften. Moden frukt har med seg sukker selv, så smak på blandingen før den går i fryseren, og hold tilbake noe av sukkeret til du har gjort det.'}},
  ],
},

];
