// toscana recipes. Contract: docs/recipe-format.md. Both languages in one file; never narrated.
// Everything here follows the Toscana food reading (content/toscana.js, lesson 4): unsalted pane
// toscano that stales in a day, and a kitchen built on using it up — ribollita, pappa al pomodoro,
// panzanella; beans and green peppery oil; and one enormous steak, grilled rare and salted after.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-52'] = [

{
  id:'bistecca-fiorentina', dish:'Bistecca alla fiorentina', course:'secondo', lesson:4, serves:2, time:{prep:120, cook:25},
  hero:'bistecca', tags:['beef','grill','embers'],
  title:{en:'Bistecca alla fiorentina', no:'Bistecca alla fiorentina'},
  blurb:{en:'One enormous T-bone over wood embers, charred outside and red inside. Everything depends on the thickness of the meat and the temperature you take it off at.',
         no:'Én enorm T-beinbiff over glør av ved, svidd utenpå og rød inni. Alt avhenger av hvor tykk biffen er, og hvilken temperatur du tar den av på.'},
  heroCaption:{en:'Bistecca alla fiorentina: a thick T-bone of Chianina beef, grilled rare over embers, salted afterwards and never with lemon.',
               no:'Bistecca alla fiorentina: en tykk T-beinbiff av Chianina-okse, grillet lite stekt over glør, saltet etterpå og aldri med sitron.'},
  wines:['Chianti Classico'],
  headnote:{
    en:'<p>The bistecca has rules, and Florence enforces them. It is a T-bone or porterhouse cut from a <strong>Chianina</strong> steer, one of the oldest cattle breeds in the world and the huge white animal of the Val di Chiana. It is cut at least four fingers thick, it weighs more than a kilo, and it has been dry-aged. It goes over embers of oak or olive wood, never over flame. Salt and pepper come afterwards, with a thread of new oil. Lemon never comes at all.</p>'
      + '<p>What all of that is arranged around is a single problem. A steak this thick cannot be cooked through in the time its surface can survive, so it is not really cooked — it is scorched on the outside while the middle is brought only just into the rare band. Thickness is what buys you that margin: five centimetres of meat between the fire and the core. A two-centimetre steak given the same fire is grey the whole way through, which is why the bistecca is priced by weight and shared between two people or more.</p>'
      + '<p>So the one thing that is not negotiable is that it is served <em>al sangue</em>, rare. Ask a Florentine waiter for it well done and he will look at you sadly and bring it anyway, and the dish will have been pointless. It is carved off the bone at the table, and it is eaten with cannellini beans and a glass of Chianti Classico, whose acidity was made for this fat.</p>',
    no:'<p>Bistecca har regler, og Firenze håndhever dem. Det skal være en T-bein- eller porterhousebiff av <strong>Chianina</strong>, en av verdens eldste storferaser og det svære hvite dyret fra Val di Chiana. Den skjæres minst fire fingre tykk, veier over en kilo og er tørrmodnet. Den legges over glør av eik eller oliventre, aldri over flammer. Salt og pepper kommer etterpå, med en tynn stråle ny olje. Sitron kommer aldri.</p>'
      + '<p>Alt dette er lagt opp rundt ett eneste problem. En biff som er så tykk, rekker ikke å bli gjennomstekt i den tiden overflaten tåler, og derfor blir den egentlig ikke stekt. Den svis utenpå mens midten så vidt løftes inn i området der kjøttet er lite stekt. Tykkelsen kjøper deg den marginen: fem centimeter kjøtt mellom ilden og kjernen. En biff på to centimeter over den samme ilden blir grå tvers igjennom, og derfor prises bistecca etter vekt og deles mellom to eller flere.</p>'
      + '<p>Én ting kan altså ikke endres: den serveres <em>al sangue</em>, lite stekt. Ber du en florentinsk kelner om den gjennomstekt, ser han trist på deg og henter den likevel, og hele poenget med retten er borte. Den skjæres fra beinet ved bordet, og den spises med cannellinibønner og et glass Chianti Classico, med en syre som er laget for nettopp dette fettet.</p>'},
  ingredients:[
    { group:{en:'The steak', no:'Biffen'}, items:[
      {q:1200, u:'g', n:{en:'T-bone or porterhouse steak', no:'T-bein- eller porterhousebiff'}, note:{en:'Chianina if you can get it, dry-aged, cut a full 5 cm thick — four fingers, as Florence measures it', no:'Chianina hvis du får tak i den, tørrmodnet, skåret hele 5 cm tykk, altså fire fingre slik Firenze måler det'}},
      {u:'', n:{en:'oak or olive-wood charcoal', no:'kull av eik eller oliventre'}, note:{en:'hardwood lump charcoal, not briquettes, and no lighter fluid', no:'kull av løvtre i hele stykker, ikke briketter, og ingen tennvæske'}, scale:'none'},
      {u:'', n:{en:'coarse sea salt', no:'grovt havsalt'}, scale:'none'},
      {u:'', n:{en:'black pepper', no:'sort pepper'}, note:{en:'ground coarsely at the last moment', no:'grovmalt i siste liten'}, scale:'none'},
      {u:'', n:{en:'extra virgin olive oil', no:'ekstra virgin olivenolje'}, note:{en:'Tuscan and new if you can, green and peppery; it is poured raw over the sliced meat', no:'toskansk og ny hvis du får tak i den, grønn og pepret; den helles rå over det oppskårne kjøttet'}, scale:'none'},
    ]},
    { group:{en:'To serve', no:'Til servering'}, items:[
      {q:300, u:'g', n:{en:'cooked cannellini beans', no:'kokte cannellinibønner'}, note:{en:'warm, dressed with oil, salt and pepper and nothing else', no:'lune, vendt med olje, salt og pepper og ingenting annet'}},
    ]},
  ],
  steps:[
    {en:'Take the steak out of the fridge at least two hours ahead and leave it uncovered on a rack at room temperature. A core straight from the fridge cannot warm through in the few minutes the surface can stand.',
     no:'Ta biffen ut av kjøleskapet minst to timer i forveien, og la den ligge udekket på en rist i romtemperatur. En kjerne rett fra kjøleskapet rekker ikke å bli varm i de få minuttene overflaten tåler.'},
    {en:'Light the charcoal and let it burn all the way down to glowing embers with no flame left. Wood that is still flaming coats the meat in soot instead of smoke.',
     no:'Tenn kullet, og la det brenne helt ned til glør uten flammer. Ved som fortsatt brenner med flamme, legger sot på kjøttet i stedet for røyk.'},
    {en:'Set the bars a hand’s width above the embers. You should be able to hold your palm at grill height for about three seconds and no longer.',
     no:'Legg risten en håndsbredd over glørne. Du skal kunne holde håndflaten i grillhøyde i omtrent tre sekunder, ikke lenger.'},
    {en:'Pat the surface of the meat dry and put nothing on it — no oil, no salt, no marinade. Salt on raw meat draws water to the surface, and wet meat steams instead of charring.',
     no:'Tørk overflaten på kjøttet, og ha ingenting på den. Verken olje, salt eller marinade. Salt på rått kjøtt trekker vann ut til overflaten, og vått kjøtt damper i stedet for å svis.'},
    {en:'Lay the steak on the bars and leave it alone for five minutes, until the underside is deeply charred and lifts off the metal without tearing.',
     no:'Legg biffen på risten, og la den ligge i fred i fem minutter, til undersiden er godt svidd og slipper metallet uten å rives i stykker.'},
    {en:'Turn it once with tongs, never a fork, and give the second side the same five minutes. Every hole you make is a channel for the juice to run out of.',
     no:'Snu den én gang med steketang, aldri med gaffel, og gi den andre siden de samme fem minuttene. Hvert hull du lager, blir en kanal som saften renner ut av.'},
    {en:'Stand the steak up on its bone for a final five to seven minutes, so that the thick edge along the spine cooks and the heat reaches the middle from below.',
     no:'Sett til slutt biffen på høykant på beinet i fem til sju minutter, slik at den tykke kanten langs ryggraden blir stekt og varmen når midten nedenfra.'},
    {en:'Push a probe into the thickest part beside the bone. Take the steak off at 48 °C; it will climb to about 52 °C as it rests, which is al sangue. At 60 °C you have an expensive mistake.',
     no:'Stikk et steketermometer inn i den tykkeste delen ved siden av beinet. Ta biffen av ved 48 °C, for den stiger til rundt 52 °C mens den hviler, og da er den al sangue. Ved 60 °C sitter du igjen med en dyr feil.'},
    {en:'Rest it on a warm plate or a board, bone down, for ten minutes somewhere warm but well away from the fire.',
     no:'La den hvile på en varm tallerken eller en fjøl med beinet ned i ti minutter, på et lunt sted godt unna ilden.'},
    {en:'Carve the two muscles off the bone — the fillet on the small side, the sirloin on the large — and slice each of them across the grain, about a finger thick.',
     no:'Skjær de to musklene løs fra beinet. Indrefileten ligger på den smale siden og ytrefileten på den brede. Skjær hver av dem i skiver på tvers av fibrene, omtrent så tykke som en finger.'},
    {en:'Scatter coarse salt over the cut faces, grind pepper on and pour a thread of raw olive oil across. Serve with the beans and the bone, which is the best part and belongs to whoever asks first.',
     no:'Strø grovt salt over snittflatene, kvern pepper på, og hell en tynn stråle rå olivenolje over. Server med bønnene og beinet, som er det beste stykket og tilhører den som spør først.'},
  ],
  notes:[
    {title:{en:'Why the salt waits', no:'Hvorfor saltet må vente'},
     body:{en:'Salt on a raw surface pulls moisture out of the meat within minutes, and a wet surface cannot char — it boils at a hundred degrees until it has dried out, and by then the inside has gone too far. Salting the cut faces afterwards puts the salt where you actually taste it, on the inside of every slice.',
           no:'Salt på en rå overflate trekker fuktighet ut av kjøttet i løpet av minutter, og en våt overflate kan ikke svis. Den koker på hundre grader til den er tørr, og da har innsiden allerede kommet for langt. Salter du snittflatene etterpå, havner saltet der du faktisk kjenner det, på innsiden av hver skive.'}},
    {title:{en:'Thickness is the recipe', no:'Tykkelsen er hele oppskriften'},
     body:{en:'The whole method rests on the distance between the fire and the core. Five centimetres of meat takes so long to warm through that the surface can char first; two centimetres does not, and no amount of care will save it. If your butcher will only cut thin steaks, cook something else.',
           no:'Hele metoden hviler på avstanden mellom ilden og kjernen. Fem centimeter kjøtt bruker så lang tid på å bli gjennomvarmt at overflaten rekker å svis først. To centimeter gjør det ikke, og ingen forsiktighet redder den. Vil slakteren bare skjære tynne biffer, får du lage noe annet.'}},
    {title:{en:'The bone lags behind', no:'Beinet henger etter'},
     body:{en:'Bone conducts heat far more slowly than muscle, so the meat lying against it is always the last to warm. That is why the steak is stood on its bone at the end, and why the probe goes in beside the bone rather than into the middle of the fillet: you want to read the coldest place, not the average.',
           no:'Bein leder varme langt saktere enn muskler, og kjøttet som ligger inntil, blir derfor alltid varmt sist. Derfor settes biffen på høykant på beinet til slutt, og derfor stikkes termometeret inn ved siden av beinet og ikke midt i indrefileten. Du vil lese av det kaldeste stedet, ikke gjennomsnittet.'}},
  ],
  variations:[
    {title:{en:'If you cannot get Chianina', no:'Hvis du ikke får tak i Chianina'},
     body:{en:'Any well-marbled T-bone from a mature animal that has been dry-aged for three weeks or more will do. Age matters more than breed here: a young steer gives thin, white fat that renders to nothing, and it is the fat running down through the meat that keeps a rare middle juicy.',
           no:'En hvilken som helst godt marmorert T-beinbiff av et voksent dyr som er tørrmodnet i tre uker eller mer, gjør nytten. Alderen betyr mer enn rasen her. Et ungt dyr gir tynt og hvitt fett som smelter bort til ingenting, og fettet som renner ned gjennom kjøttet, holder en lite stekt midte saftig.'}},
    {title:{en:'Without a fire', no:'Uten bål'},
     body:{en:'A cast-iron pan heated until it smokes will build the crust, and an oven at 100 °C will bring the core up gently afterwards. It works, and it is a different dish: what you lose is the smoke from the oak, which is not a garnish here but one of the four things the steak actually tastes of.',
           no:'En støpejernspanne som er varmet til den ryker, gir skorpen, og en stekeovn på 100 °C løfter kjernen rolig etterpå. Det fungerer, men det blir en annen rett. Du mister røyken fra eiken, og den er ikke pynt her, men en av de fire tingene biffen faktisk smaker av.'}},
    {title:{en:'Tagliata is not bistecca', no:'Tagliata er ikke bistecca'},
     body:{en:'A boneless sirloin grilled and sliced over rocket with shavings of Parmigiano is <em>tagliata</em>, and it is a good thing to eat. It is not a bistecca, it has no bone and no Chianina in it, and Florence will tell you so.',
           no:'En ytrefilet uten bein som grilles og skjæres opp over ruccola med høvlet Parmigiano, heter <em>tagliata</em>, og den er god å spise. Den er ikke en bistecca, den har verken bein eller Chianina i seg, og det får du høre i Firenze.'}},
  ],
},

{
  id:'ribollita', dish:'Ribollita', course:'primo', lesson:4, serves:6, time:{prep:40, cook:200},
  hero:'ribollita', tags:['beans','bread','vegetarian','winter'],
  title:{en:'Ribollita', no:'Ribollita'},
  blurb:{en:'Beans, cavolo nero and yesterday’s unsalted bread, cooked, left overnight and boiled again until the spoon stands up in it.',
         no:'Bønner, svartkål og gårsdagens usaltede brød, kokt, satt bort til neste dag og kokt om igjen til skjeen står i den.'},
  heroCaption:{en:'Ribollita: cannellini beans, cavolo nero and stale bread, the dish that defines Tuscan cucina povera.',
               no:'Ribollita: cannellinibønner, svartkål og tørt brød, retten som definerer toskansk cucina povera.'},
  wines:['Chianti Classico'],
  headnote:{
    en:'<p>Tuscans call their own cooking <em>cucina povera</em> and say it with pride, and ribollita is the proof. It costs almost nothing: beans, winter greens, a soffritto, peppery green oil, and the loaf that went hard yesterday. <strong>Pane toscano</strong> is baked without salt and stales within a day, and half of Tuscan cooking exists to use it up — ribollita, pappa al pomodoro, panzanella, fettunta. Nothing here is thrown away, and that is not thrift dressed up as virtue; it is where the flavour comes from.</p>'
      + '<p>The name means <em>re-boiled</em>, and it is a description of the method rather than a nickname. On the first day you make a bean and cabbage soup and layer the bread into it. Then you leave it overnight, which is the step that does the work: the dried starch in the bread swells, softens and begins to dissolve. The second boiling finishes the job and turns soup and bread into one thick body, dense enough to stand a spoon in.</p>'
      + '<p>Two things are not negotiable. The bread has to be stale, because fresh crumb goes to glue instead of dissolving. And the beans have to be cooked at home, in water you keep: that cloudy liquid is the only stock in the dish, and pouring it down the sink gives you a thin ribollita that no amount of oil can rescue.</p>',
    no:'<p>Toskanerne kaller sin egen matlaging <em>cucina povera</em> og sier det med stolthet, og ribollita er beviset. Den koster nesten ingenting: bønner, vintergrønt, en soffritto, pepret grønn olje og brødet som ble hardt i går. <strong>Pane toscano</strong> bakes uten salt og blir tørt i løpet av et døgn, og halvparten av toskansk matlaging finnes for å bruke det opp, enten som ribollita, pappa al pomodoro, panzanella eller fettunta. Ingenting kastes her, og det er ikke sparsomhet pyntet som dyd. Det er derfra smaken kommer.</p>'
      + '<p>Navnet betyr <em>kokt på nytt</em>, og det er en beskrivelse av metoden og ikke et kallenavn. Første dagen lager du en suppe av bønner og kål og legger brødet lagvis ned i den. Så setter du den bort til neste dag, og nettopp det trinnet gjør jobben: den tørkede stivelsen i brødet sveller, mykner og begynner å løse seg opp. Den andre kokingen fullfører arbeidet og gjør suppe og brød til én tykk masse, fast nok til at skjeen står.</p>'
      + '<p>To ting kan ikke endres. Brødet må være tørt, for ferskt brød blir til lim i stedet for å løse seg opp. Og bønnene må kokes hjemme, i vann du tar vare på. Den uklare væsken er den eneste kraften i retten, og heller du den i vasken, får du en tynn ribollita som ingen mengde olje kan redde.</p>'},
  ingredients:[
    { group:{en:'The beans', no:'Bønnene'}, items:[
      {q:300, u:'g', n:{en:'dried cannellini beans', no:'tørkede cannellinibønner'}, note:{en:'zolfini if you find them; soak them in cold water overnight', no:'zolfini hvis du finner dem; bløtlegg dem i kaldt vann natten over'}},
      {q:2, u:'l', n:{en:'water for the beans', no:'vann til bønnene'}, note:{en:'unsalted, and every drop of it is kept', no:'usaltet, og hver dråpe tas vare på'}, scale:'sub'},
      {q:1, u:'', n:{en:'garlic clove', no:'hvitløksfedd'}, round:'half'},
      {q:1, u:'', n:{en:'sage sprig', no:'salviekvist'}, round:'half'},
    ]},
    { group:{en:'The soup', no:'Suppen'}, items:[
      {q:120, u:'ml', n:{en:'extra virgin olive oil', no:'ekstra virgin olivenolje'}, note:{en:'half goes into the soffritto and half raw over the bowls', no:'halvparten går i soffritton og halvparten rått over skålene'}},
      {q:200, u:'g', n:{en:'onion', no:'løk'}, note:{en:'chopped fine', no:'finhakket'}},
      {q:150, u:'g', n:{en:'carrot', no:'gulrot'}, note:{en:'chopped fine', no:'finhakket'}},
      {q:150, u:'g', n:{en:'celery', no:'stangselleri'}, note:{en:'chopped fine', no:'finhakket'}},
      {q:2, u:'', n:{en:'garlic cloves', no:'hvitløksfedd'}, round:'half'},
      {q:300, u:'g', n:{en:'peeled plum tomatoes', no:'hermetiske plommetomater'}, note:{en:'crushed by hand', no:'most med hendene'}},
      {q:500, u:'g', n:{en:'cavolo nero', no:'svartkål'}, note:{en:'weighed with the stalks on; strip the leaves off the tough central rib and shred them', no:'veid med stilkene på; dra bladene av den seige midtstilken og skjær dem i strimler'}},
      {q:300, u:'g', n:{en:'Savoy cabbage', no:'savoykål'}, note:{en:'shredded', no:'skåret i strimler'}},
      {q:200, u:'g', n:{en:'floury potato', no:'melne poteter'}, note:{en:'diced; it cooks away and thickens the pot', no:'i terninger; de koker ut og gjør gryten tykkere'}},
      {q:1, u:'', n:{en:'thyme sprig', no:'timiankvist'}, round:'half'},
      {q:400, u:'g', n:{en:'stale pane toscano', no:'tørt pane toscano'}, note:{en:'two or three days old, crusts and all; any dense sourdough will stand in, but then use less salt', no:'to eller tre dager gammelt, med skorpe og alt; et fast surdeigsbrød kan tre inn, men da må du bruke mindre salt'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
      {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Drain the soaked beans and simmer them in fresh unsalted water with the garlic clove and the sage until they are tender all the way through, an hour to an hour and a half. Salt them only at the very end.',
     no:'Hell av bløtevannet, og la bønnene småkoke i friskt, usaltet vann med hvitløksfeddet og salvien til de er møre tvers igjennom, én til halvannen time. Salt dem først helt til slutt.'},
    {en:'Lift out about a third of the beans and pass them through a food mill, or blend them with a ladleful of their liquid. Leave the rest whole and keep all the cooking water.',
     no:'Ta opp omtrent en tredjedel av bønnene, og kjør dem gjennom en passermølle, eller mos dem med stavmikser sammen med en øse av kokevannet. La resten være hele, og ta vare på alt kokevannet.'},
    {en:'Sweat the onion, carrot and celery in half the oil over low heat for fifteen minutes, until they are soft and sweet and have taken no colour at all.',
     no:'La løken, gulroten og sellerien mykne i halvparten av oljen på svak varme i femten minutter, til de er myke og søte og ikke har fått farge i det hele tatt.'},
    {en:'Add the sliced garlic and then the crushed tomatoes, and cook for ten minutes until the sauce darkens and the oil comes back to the surface.',
     no:'Ha i den skivede hvitløken og deretter de mosede tomatene, og la det koke i ti minutter til sausen mørkner og oljen kommer opp til overflaten igjen.'},
    {en:'Stir in the cavolo nero, the Savoy cabbage and the potato, and turn them over in the fat for a few minutes until the leaves have collapsed into the pot.',
     no:'Rør inn svartkålen, savoykålen og potetene, og vend det rundt i fettet i noen minutter til bladene har falt sammen i gryten.'},
    {en:'Pour in the bean liquid and the puréed beans, add the thyme and simmer uncovered for about an hour and a half. Cavolo nero needs that long: the bitterness cooks away and comes back as sweetness.',
     no:'Hell i bønnekraften og de mosede bønnene, ha i timianen, og la det småkoke uten lokk i omtrent halvannen time. Svartkål trenger så lang tid, for bitterheten koker seg bort og blir til sødme.'},
    {en:'Add the whole beans, taste and salt it properly, then take the pot off the heat.',
     no:'Ha i de hele bønnene, smak til og salt skikkelig, og ta så gryten av platen.'},
    {en:'Tear the stale bread into rough pieces and layer it into the pot — a ladle of soup, a layer of bread, and on like that until both are used up.',
     no:'Riv det tørre brødet i grove biter, og legg det lagvis ned i gryten. En øse suppe, et lag brød, og slik videre til begge deler er brukt opp.'},
    {en:'Cover the pot and leave it somewhere cool overnight. This is not resting time; it is when the bread swells and its starch begins to dissolve into the liquid.',
     no:'Legg lokk på gryten, og sett den kjølig til neste dag. Dette er ingen hviletid, men timene da brødet sveller og stivelsen begynner å løse seg opp i væsken.'},
    {en:'The next day set it back over low heat and boil it again, stirring, for twenty minutes or so, until the bread has disappeared into the soup and a spoon will stand up in the middle of the pot.',
     no:'Neste dag setter du den tilbake på svak varme og koker den om igjen i tjue minutters tid mens du rører, til brødet har forsvunnet inn i suppen og skjeen står av seg selv midt i gryten.'},
    {en:'Serve it in warm bowls, pour the rest of the oil raw over each one and grind pepper on top. It should be eaten warm rather than hot.',
     no:'Server den i lune skåler, hell resten av oljen rå over hver porsjon, og kvern pepper på toppen. Den skal spises lun, ikke glovarm.'},
  ],
  notes:[
    {title:{en:'Why it is boiled twice', no:'Hvorfor den kokes to ganger'},
     body:{en:'Dried bread is dried starch, and starch needs both water and time before it will swell and go into solution. One evening of soaking does that; the second boiling then breaks the softened crumb apart and binds it to the liquid. Skip the night and you get soup with lumps of bread in it, which is a perfectly good dish and is not ribollita.',
           no:'Tørt brød er tørket stivelse, og stivelse trenger både vann og tid før den sveller og går i oppløsning. En kveld i væsken gjør nettopp det, og den andre kokingen bryter så det oppbløtte brødet fra hverandre og binder det til væsken. Hopper du over natten, får du en suppe med brødklumper i, og det er en helt god rett, men det er ikke ribollita.'}},
    {title:{en:'The bean water is the stock', no:'Bønnekraften er kraften'},
     body:{en:'There is no meat in this pot and nothing else to give it body. What does the work is the starch that leaches out of the beans as they simmer, which is why they are cooked in plain water at home rather than tipped out of a tin, and why every drop of that cloudy liquid goes back into the soup.',
           no:'Det er ikke kjøtt i denne gryten, og ingenting annet som gir den fylde. Fylden kommer av stivelsen som lekker ut av bønnene mens de småkoker, og derfor kokes de i rent vann hjemme i stedet for å helles ut av en boks, og derfor går hver dråpe av den uklare væsken tilbake i suppen.'}},
    {title:{en:'Bread without salt changes the seasoning', no:'Brød uten salt endrer saltingen'},
     body:{en:'Pane toscano brings none of its own, so the bread in this pot will swallow far more salt than you expect, and it has to be tasted again after the second boiling. If you are using an ordinary salted loaf instead, hold back in the soup and correct at the end.',
           no:'Pane toscano har ikke salt i seg, og brødet i denne gryten sluker derfor langt mer salt enn du venter. Gryten må smakes til på nytt etter den andre kokingen. Bruker du et vanlig, saltet brød i stedet, holder du igjen i suppen og retter opp til slutt.'}},
  ],
  variations:[
    {title:{en:'After the first frost', no:'Etter første frost'},
     body:{en:'Tuscans say ribollita should not be made before the first frost has been on the cavolo nero. There is something in it: cold makes the plant convert starch to sugar as an antifreeze, and frosted leaves really are sweeter and less bitter. Out of season, cook it longer.',
           no:'Toskanerne sier at ribollita ikke bør lages før den første frosten har vært over svartkålen. Det ligger noe i det, for kulden får planten til å gjøre om stivelse til sukker som frostvæske, og frostbitte blader er faktisk søtere og mindre bitre. Utenom sesongen koker du den lenger.'}},
    {title:{en:'Fried in the pan', no:'Stekt i panne'},
     body:{en:'What is left over is often pressed into an oiled frying pan and cooked without stirring until a dark crust forms underneath, then turned out upside down. Tuscans will tell you the third day is better than the second.',
           no:'Restene presses ofte ned i en oljet stekepanne og stekes uten å røres til det danner seg en mørk skorpe under, og så vendes de ut opp ned. Toskanerne vil fortelle deg at den tredje dagen er bedre enn den andre.'}},
    {title:{en:'With tinned beans', no:'Med bønner på boks'},
     body:{en:'It can be done, but the brine they sit in is not a stock and will not stand in for one. Rinse them, purée a third with water, and add a little more potato to make up the body you have lost.',
           no:'Det lar seg gjøre, men laken de ligger i, er ingen kraft og kan ikke tre inn som en. Skyll dem, mos en tredjedel med vann, og ha i litt mer potet for å ta igjen fylden du har mistet.'}},
  ],
},

{
  id:'pappa-al-pomodoro', dish:'Pappa al pomodoro', course:'primo', lesson:4, serves:4, time:{prep:15, cook:45},
  hero:'pappa', tags:['bread','tomato','vegetarian','summer'],
  title:{en:'Pappa al pomodoro', no:'Pappa al pomodoro'},
  blurb:{en:'Stale bread cooked to a porridge with tomatoes, garlic and basil, finished with raw green oil. The other half of what Tuscany does with yesterday’s loaf.',
         no:'Tørt brød kokt til grøt med tomater, hvitløk og basilikum, og til slutt rå, grønn olje. Den andre halvdelen av det Toscana gjør med gårsdagens brød.'},
  heroCaption:{en:'Pappa al pomodoro, thick and orange under torn basil, with bread on the table to go with it.',
               no:'Pappa al pomodoro, tykk og oransje under revet basilikum, med brød på bordet ved siden av.'},
  wines:['Vernaccia di San Gimignano'],
  headnote:{
    en:'<p>Pappa al pomodoro is ribollita’s summer cousin and comes from the same place: a loaf of <strong>pane toscano</strong>, baked without salt, gone hard on the second day and far too good to waste. Where ribollita gives it beans and winter greens, this gives it ripe tomatoes, garlic, basil and a great deal of green oil, and cooks the lot down until the bread has stopped being bread.</p>'
      + '<p><em>Pappa</em> means mush, or the porridge you feed a small child, and the name is not being modest — a proper one is thick, rough and uniform, with no recognisable pieces left in it. That is the whole technique. The bread has to be genuinely stale, because dried starch swells and then breaks up into soft grains, while fresh crumb simply smears into glue. Everything after that is patience and a wooden spoon.</p>'
      + '<p>The oil goes in twice, and that is not carelessness. The first half is cooked with the garlic and the tomato, where it carries flavour through the dish. The second is poured raw over the bowl at the table, so that you taste the oil itself — Tuscan oil is picked early and green and is peppery enough to catch the throat, which Tuscans take as the sign of a good one.</p>',
    no:'<p>Pappa al pomodoro er ribollitas sommerfetter og kommer fra samme sted: et brød av <strong>pane toscano</strong>, bakt uten salt, hardt allerede andre dagen og altfor godt til å kastes. Ribollita gir brødet bønner og vintergrønt, mens denne retten gir det modne tomater, hvitløk, basilikum og rikelig med grønn olje, og koker alt sammen ned til brødet har sluttet å være brød.</p>'
      + '<p><em>Pappa</em> betyr grøt, den slags man mater et lite barn med, og navnet er ikke beskjedent. En ordentlig pappa al pomodoro er tykk, grov og jevn, uten gjenkjennelige biter igjen. Det er hele teknikken. Brødet må være virkelig tørt, for tørket stivelse sveller og faller så fra hverandre i myke korn, mens ferskt brød bare smøres ut til lim. Alt etter det er tålmodighet og en tresleiv.</p>'
      + '<p>Oljen går i to ganger, og det er ikke slurv. Den første halvparten kokes sammen med hvitløken og tomaten og bærer smak gjennom hele retten. Den andre helles rå over skålen ved bordet, slik at du kjenner selve oljen. Toskansk olje høstes tidlig og grønn og er pepret nok til å ta tak i halsen, noe toskanerne tar som tegn på en god olje.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:400, u:'g', n:{en:'stale pane toscano', no:'tørt pane toscano'}, note:{en:'two or three days old, crusts and all, torn rather than cut', no:'to eller tre dager gammelt, med skorpe og alt, revet og ikke skåret'}},
    {q:900, u:'g', n:{en:'ripe tomatoes', no:'modne tomater'}, note:{en:'skinned and roughly chopped; out of season, good tinned plum tomatoes are the better choice', no:'flådde og grovhakket; utenom sesongen er gode plommetomater på boks det beste valget'}},
    {q:4, u:'', n:{en:'garlic cloves', no:'hvitløksfedd'}, note:{en:'sliced thinly', no:'skåret i tynne skiver'}, round:'half'},
    {q:120, u:'ml', n:{en:'extra virgin olive oil', no:'ekstra virgin olivenolje'}, note:{en:'half into the pot and half raw at the table', no:'halvparten i gryten og halvparten rå ved bordet'}},
    {q:600, u:'ml', n:{en:'water or light vegetable stock', no:'vann eller lys grønnsakskraft'}, note:{en:'kept hot; you will want more of it than you think', no:'holdes varm; du trenger mer av den enn du tror'}},
    {q:25, u:'g', n:{en:'basil', no:'basilikum'}, note:{en:'one stalk goes in whole and comes out again; the leaves are torn in at the end', no:'én stilk går i hel og tas ut igjen, og bladene rives i til slutt'}},
    {q:1, u:'', n:{en:'small dried chilli', no:'liten tørket chili'}, note:{en:'optional, and left whole', no:'valgfri, og legges i hel'}, round:'half'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
  ]}],
  steps:[
    {en:'Tear the bread into rough pieces with your hands, crusts and all, and spread them out to dry further if they still give under a thumb. Bread torn by hand has ragged faces that drink more than a knife-cut edge does.',
     no:'Riv brødet i grove biter med hendene, med skorpe og alt, og spre dem utover for å tørke videre hvis de fortsatt gir etter under tommelen. Brød som er revet for hånd, får frynsete flater som suger mer til seg enn en knivskåret kant gjør.'},
    {en:'Warm the sliced garlic in half the oil over low heat until it smells and turns pale gold. Let it brown and the whole pot will taste bitter.',
     no:'Varm den skivede hvitløken i halvparten av oljen på svak varme til den dufter og blir lyst gyllen. Lar du den brunes, smaker hele gryten bittert.'},
    {en:'Drop in the chilli if you are using it, add the tomatoes and cook over medium heat for twenty minutes, until the sauce darkens and the oil separates out at the edges.',
     no:'Legg i chilien hvis du bruker den, ha i tomatene, og la det koke på middels varme i tjue minutter, til sausen mørkner og oljen skiller seg ut i kantene.'},
    {en:'Pour in the hot water or stock, drop in the basil stalk and bring it back to a simmer.',
     no:'Hell i det varme vannet eller kraften, legg i basilikumstilken, og la det så vidt komme til kok igjen.'},
    {en:'Add the bread, stir it once so that every piece is wet, and then leave it alone for ten minutes to swell.',
     no:'Ha i brødet, rør én gang slik at hver bit blir våt, og la det så stå i fred i ti minutter og svelle.'},
    {en:'Beat the pot hard with a wooden spoon until the pieces break down and the whole thing turns into a thick, rough purée with nothing recognisable left in it.',
     no:'Arbeid massen kraftig med en tresleiv til bitene faller fra hverandre og alt sammen blir til en tykk, grov masse uten noe gjenkjennelig igjen.'},
    {en:'Simmer very gently for another ten minutes, stirring often so that it does not catch on the bottom, and loosen it with hot water whenever it tightens too far.',
     no:'La det småkoke svært forsiktig i ti minutter til mens du rører ofte, slik at det ikke svir seg i bunnen, og spe med varmt vann hver gang det blir for stivt.'},
    {en:'Taste it and salt it properly. Unsalted bread brings none of its own and will take more than seems reasonable.',
     no:'Smak til, og salt skikkelig. Usaltet brød har ikke salt i seg og tar imot mer salt enn du skulle tro.'},
    {en:'Fish out the basil stalk and the chilli, take the pot off the heat and stir in the torn basil leaves so that they wilt in the residual warmth rather than boil.',
     no:'Fisk ut basilikumstilken og chilien, ta gryten av platen, og rør inn de revne basilikumbladene, slik at de faller sammen i ettervarmen i stedet for å koke.'},
    {en:'Let it stand for ten minutes, then serve it with the rest of the oil poured raw over each bowl and pepper ground on top. It is eaten warm or at room temperature, never hot, and it is better the next day.',
     no:'La det stå i ti minutter, og server med resten av oljen helt rå over hver skål og pepper kvernet på toppen. Den spises lun eller med romtemperatur, aldri glovarm, og den er bedre dagen etter.'},
  ],
  notes:[
    {title:{en:'Stale bread behaves differently', no:'Tørt brød oppfører seg annerledes'},
     body:{en:'Drying sets the starch in the crumb. Wet it again and it swells, then breaks into soft grains that thicken the liquid around them. Fresh crumb has not set, so it collapses on contact and smears into a gluey paste instead. This is the same mechanism that makes ribollita work, and the reason both dishes want yesterday’s loaf rather than today’s.',
           no:'Tørkingen får stivelsen i brødet til å stivne. Bløter du det opp igjen, sveller det og faller fra hverandre i myke korn som gjør væsken rundt dem tykkere. Ferskt brød har ikke stivnet, og det klapper derfor sammen med en gang og smøres ut til en limaktig masse. Dette er den samme mekanismen som får ribollita til å virke, og grunnen til at begge rettene vil ha gårsdagens brød og ikke dagens.'}},
    {title:{en:'Why the oil is added twice', no:'Hvorfor oljen kommer i to ganger'},
     body:{en:'Heat drives off the aromatic compounds that make good olive oil smell of cut grass and pepper, and what it leaves behind is a cooking fat that carries other flavours well. So half the oil is cooked, to do that job, and half is added raw at the table, where it still tastes of itself. Any dish that ends with a drizzle of oil is doing the same thing.',
           no:'Varme driver ut de aromatiske stoffene som gjør at god olivenolje lukter av nyslått gress og pepper, og det som blir igjen, er et stekefett som bærer andre smaker godt. Derfor kokes halvparten av oljen for å gjøre nettopp den jobben, mens den andre halvparten kommer rå på ved bordet og fortsatt smaker av seg selv. Alle retter som avsluttes med en skvett olje, gjør det samme.'}},
    {title:{en:'Serve it warm, not hot', no:'Server den lun, ikke glovarm'},
     body:{en:'Tomato acidity and basil are both blunted by heat, and a mouthful straight off the stove tastes mostly of bread. Ten minutes standing lets it settle and the flavours come forward, which is also why the leftovers taste better than the pot did.',
           no:'Både syren i tomatene og basilikumen sløves av varme, og en munnfull rett fra platen smaker mest av brød. Ti minutter på benken lar den falle til ro og smakene komme fram, og det er også derfor restene smaker bedre enn gryten gjorde.'}},
  ],
  variations:[
    {title:{en:'Panzanella, the uncooked version', no:'Panzanella, utgaven som ikke kokes'},
     body:{en:'The same bread and the same tomatoes, treated the opposite way: the bread is soaked in water, squeezed dry and tossed with chopped tomato, cucumber, red onion, basil, oil and vinegar. It is the Tuscan answer to a summer too hot to light the stove.',
           no:'Det samme brødet og de samme tomatene, behandlet stikk motsatt: brødet bløtlegges i vann, klemmes tørt og vendes med hakket tomat, agurk, rødløk, basilikum, olje og eddik. Det er det toskanske svaret på en sommer som er for varm til å skru på komfyren.'}},
    {title:{en:'How thick', no:'Hvor tykk'},
     body:{en:'Some cooks want it stiff enough to hold the mark of a spoon, others loose enough to eat from a bowl with a spoon like a soup. Both are eaten in Tuscany and the only lever is water, which is much easier to add than to take out. Start thick.',
           no:'Noen vil ha den så stiv at den holder på merket etter skjeen, andre så løs at den spises av en skål som en suppe. Begge deler spises i Toscana. Vannet er det eneste du kan styre, og det er langt lettere å tilsette enn å fjerne. Begynn tykt.'}},
    {title:{en:'In winter', no:'Om vinteren'},
     body:{en:'Pale supermarket tomatoes make a pale dish. Good tinned plum tomatoes are more honest, and in December the basil is better left out altogether than bought weak — a bay leaf in the pot and a heavier hand with the pepper will carry it.',
           no:'Bleke butikktomater gir en blek rett. Gode plommetomater på boks er ærligere, og i desember er det bedre å droppe basilikumen helt enn å kjøpe en kraftløs potte. Et laurbærblad i gryten og litt tyngre hånd med pepperen bærer den fram.'}},
  ],
},

{
  id:'pici-cacio-e-pepe', dish:'Pici cacio e pepe', course:'primo', lesson:4, serves:4, time:{prep:60, cook:15},
  hero:'pici', tags:['pasta','handmade','vegetarian'],
  title:{en:'Pici cacio e pepe', no:'Pici cacio e pepe'},
  blurb:{en:'Thick strands rolled by hand between the palms, dressed in Tuscan pecorino and cracked pepper. The Sienese answer to a Roman dish.',
         no:'Tykke tråder rullet for hånd mellom håndflatene, vendt i toskansk pecorino og knust pepper. Sienas svar på en romersk rett.'},
  heroCaption:{en:'Pici, thick strands rolled by hand between the palms, the pasta of the hills around Siena.',
               no:'Pici, tykke tråder rullet for hånd mellom håndflatene, pastaen fra åsene ved Siena.'},
  wines:['Chianti Classico'],
  headnote:{
    en:'<p>Tuscany is not a pasta region the way Emilia is, but the hills around Siena have <strong>pici</strong>: fat, uneven strands of flour and water, rolled out one at a time between two flat palms. There is no egg in them and no machine will make them, and the roughness that a hand leaves behind is the reason they hold a sauce that a smooth extruded spaghetti would let slide off.</p>'
      + '<p>Cacio e pepe belongs to Rome, and this is the Tuscan reading of it rather than a copy. Two things change. The first is the pasta: fresh pici shed a great deal more starch into the water than dried spaghetti do, so the liquid you are building the sauce with is already halfway there — the Roman cook’s hardest problem is the Tuscan cook’s free gift. The second is the cheese. <strong>Pecorino Toscano DOP</strong> is milder and fattier than Pecorino Romano, so it melts more kindly and seizes less easily, but it also seasons far less. Salt and pepper by taste here, not by a Roman recipe’s numbers.</p>'
      + '<p>What does not change is the rule the two dishes share: the cheese goes in with the pan off the heat, and it goes in as a paste made with lukewarm water, never as a handful of dry gratings thrown at hot pasta.</p>',
    no:'<p>Toscana er ikke en pastaregion slik Emilia er, men åsene rundt Siena har <strong>pici</strong>: tykke, ujevne tråder av mel og vann, rullet ut én om gangen mellom to flate håndflater. Det er ikke egg i dem, og ingen maskin lager dem, og den ruheten en hånd etterlater seg, er grunnen til at de holder på en saus som ville ha glidd av en glatt, presset spaghetti.</p>'
      + '<p>Cacio e pepe hører Roma til, og dette er den toskanske lesningen av retten, ikke en kopi. To ting er annerledes. Det første er pastaen. Fersk pici gir fra seg langt mer stivelse til vannet enn tørket spaghetti gjør, og væsken du bygger sausen med, er derfor allerede halvveis framme. Det den romerske kokken sliter mest med, får den toskanske kokken gratis. Det andre er osten. <strong>Pecorino Toscano DOP</strong> er mildere og fetere enn Pecorino Romano, og den smelter derfor lettere og klumper seg sjeldnere, men den krydrer også langt mindre. Salt og pepper skal her måles med smaken, ikke etter tallene i en romersk oppskrift.</p>'
      + '<p>Regelen de to rettene deler, står fast: osten skal i med pannen av platen, og den skal i som en masse rørt ut med lunkent vann, aldri som en neve tørt revet ost kastet på varm pasta.</p>'},
  ingredients:[
    { group:{en:'The pici', no:'Picien'}, items:[
      {q:250, u:'g', n:{en:'plain wheat flour', no:'hvetemel'}, note:{en:'tipo 0 if you have it', no:'tipo 0 hvis du har det'}},
      {q:150, u:'g', n:{en:'fine semolina', no:'finmalt semulegryn'}, note:{en:'semola rimacinata; it gives the strands their bite. All plain flour works if you cannot find it', no:'semola rimacinata, som gir trådene tyggemotstand. Bare hvetemel går fint hvis du ikke får tak i det'}},
      {q:200, u:'ml', n:{en:'warm water', no:'lunkent vann'}, note:{en:'held back and added a little at a time; flours drink differently', no:'holdes igjen og has i litt om gangen, for mel suger ulikt'}},
      {q:5, u:'g', n:{en:'salt for the dough', no:'salt i deigen'}},
      {q:10, u:'ml', n:{en:'olive oil', no:'olivenolje'}, note:{en:'for oiling the sheet before it is cut; Sienese cooks argue about whether it belongs in the dough at all', no:'til å pensle deigplaten før den skjæres; kokkene i Siena krangler om den i det hele tatt hører hjemme i deigen'}},
      {u:'', n:{en:'semolina for dusting', no:'semulegryn til drysking'}, scale:'none'},
    ]},
    { group:{en:'The sauce', no:'Sausen'}, items:[
      {q:200, u:'g', n:{en:'Pecorino Toscano', no:'Pecorino Toscano'}, note:{en:'aged (stagionato), grated as finely as you can and left at room temperature; a third of it Pecorino Romano sharpens the dish', no:'lagret (stagionato), revet så fint du klarer og satt fram med romtemperatur; en tredjedel Pecorino Romano skjerper retten'}},
      {q:8, u:'g', n:{en:'black peppercorns', no:'sorte pepperkorn'}, note:{en:'whole, cracked in a mortar at the last moment', no:'hele, knust i morter i siste liten'}},
      {q:3, u:'l', n:{en:'water', no:'vann'}, note:{en:'enough to move the strands and no more; the starch they shed is the sauce', no:'nok til at trådene får bevege seg, og ikke mer; stivelsen de gir fra seg, er sausen'}, scale:'sub'},
      {q:20, u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, note:{en:'more than you would use for a Roman cacio e pepe, because this cheese is milder', no:'mer enn du ville brukt til en romersk cacio e pepe, siden denne osten er mildere'}, scale:'sub'},
    ]},
  ],
  steps:[
    {en:'Mix the flour, the semolina and the salt in a wide bowl, make a well in the middle and work in the warm water a little at a time until a rough, firm ball comes together. It should feel stiffer than a bread dough.',
     no:'Bland hvetemelet, semulegrynene og saltet i en vid bolle, lag en grop i midten, og arbeid inn det lunkne vannet litt om gangen til deigen samler seg til en grov, fast kule. Den skal kjennes stivere ut enn en brøddeig.'},
    {en:'Knead it for ten minutes, until the surface is smooth and a dent pressed into it springs back slowly, then wrap it and let it rest for half an hour.',
     no:'Elt den i ti minutter, til overflaten er glatt og en fordypning du trykker inn, sakte reiser seg igjen. Pakk den så inn, og la den hvile en halvtime.'},
    {en:'Roll the dough out to about a centimetre thick, brush the surface with a film of oil, and cut it into strips of about the same width.',
     no:'Kjevle ut deigen til den er omtrent en centimeter tykk, pensle overflaten med et tynt lag olje, og skjær den i strimler som er omtrent like brede.'},
    {en:'Roll one strip under your flat palms, working from the middle outwards, until it stretches into a strand about as thick as a bootlace and uneven along its length. Do not aim for even; uneven is the whole point.',
     no:'Rull én strimmel under flate håndflater, ut fra midten mot begge sider, til den strekker seg til en tråd omtrent så tykk som en skolisse og ujevn langs hele lengden. Ikke prøv å få den jevn, for ujevnheten er hele poenget.'},
    {en:'Lay the finished strands on a tray dusted with semolina and toss them lightly so they do not stick to each other. Work through the rest of the dough the same way.',
     no:'Legg de ferdige trådene på et brett drysset med semulegryn, og vend dem lett, så de ikke setter seg fast i hverandre. Gjør det samme med resten av deigen.'},
    {en:'Crack the peppercorns coarsely in a mortar and toast them in a dry wide pan over medium heat for half a minute, until the kitchen smells of them.',
     no:'Knus pepperkornene grovt i morter, og rist dem i en tørr, vid panne på middels varme i et halvt minutt, til hele kjøkkenet lukter av dem.'},
    {en:'Boil the pici in well salted water for three to five minutes, until they float and are still chewy at the core. Taste one rather than trusting the clock; hand-rolled strands vary along their own length.',
     no:'Kok picien i godt saltet vann i tre til fem minutter, til trådene flyter opp og fortsatt har tyggemotstand i kjernen. Smak på én i stedet for å stole på klokken, for håndrullede tråder varierer langs sin egen lengde.'},
    {en:'Ladle some of the cooking water into the peppered pan and boil it down to a syrupy film. It should already look thicker than the water a dried pasta leaves behind.',
     no:'Øs litt av kokevannet over i pepperpannen, og kok det inn til en sirupsaktig hinne. Det skal allerede se tykkere ut enn vannet en tørket pasta etterlater seg.'},
    {en:'Work the grated pecorino together with lukewarm cooking water in a bowl, a spoonful at a time, into a thick smooth paste with no lumps left in it. Lukewarm, never hot.',
     no:'Rør den revne pecorinoen sammen med lunkent kokevann i en bolle, en skje om gangen, til en tykk og jevn masse uten klumper. Lunkent, aldri varmt.'},
    {en:'Lift the pici straight into the pan with tongs, add a little more of the water and toss over the heat for a minute until they are coated.',
     no:'Løft picien rett over i pannen med steketang, ha i litt mer av kokevannet, og vend det over varmen i ett minutt til trådene er dekket.'},
    {en:'Take the pan off the heat, count to thirty, then add the cheese paste and toss hard until every strand turns glossy. Loosen with cooking water whenever it tightens, and serve at once with the rest of the pepper.',
     no:'Ta pannen av platen, tell til tretti, og ha så i ostemassen mens du vender kraftig, til hver tråd blir blank. Spe med kokevann hver gang den strammer seg, og server med en gang, med resten av pepperen.'},
  ],
  notes:[
    {title:{en:'Why the hand beats the machine', no:'Hvorfor hånden slår maskinen'},
     body:{en:'A rolled strand is fatter in the middle than at the ends and rough all over, so no two mouthfuls cook to quite the same point — a firm core here, a softer edge there. That variation is half of what people like about pici. The rough surface also sheds far more starch into the water than a smooth extruded pasta does, which is why the sauce comes together so easily.',
           no:'En tråd som rulles for hånd, blir tykkere på midten enn i endene og ru over det hele, og ingen to munnfuller koker derfor helt likt. Her en fast kjerne, der en mykere kant. Den variasjonen er halvparten av det folk liker ved pici. Den ru overflaten gir også fra seg langt mer stivelse til vannet enn en glatt, presset pasta gjør, og derfor går sausen så lett sammen.'}},
    {title:{en:'A milder cheese moves the seasoning', no:'En mildere ost flytter saltingen'},
     body:{en:'Pecorino Romano is salted hard and can season a dish on its own; Pecorino Toscano is milder and fattier. The fat makes it more forgiving in the pan, so the sauce is less likely to break, but the dish will come out flat if you salt the water as lightly as a Roman recipe tells you to. Taste the water before the pasta goes in.',
           no:'Pecorino Romano er kraftig saltet og kan krydre en rett alene, mens Pecorino Toscano er mildere og fetere. Fettet gjør den mer tilgivende i pannen, så sausen sprekker sjeldnere, men retten blir flat om du salter vannet så lett som en romersk oppskrift ber deg om. Smak på vannet før pastaen går i.'}},
    {title:{en:'A stiff dough on purpose', no:'En stiv deig med vilje'},
     body:{en:'A wet dough rolls out thin and tears; a stiff one holds a fat strand and still has bite after five minutes in the water. If it fights you under the palm, give it another quarter of an hour under the wrap rather than more water — resting lets the gluten relax, and adding water only makes a strand that goes limp when it boils.',
           no:'En våt deig rulles tynn og revner, mens en stiv holder på en tykk tråd og fortsatt har tyggemotstand etter fem minutter i vannet. Kjemper den imot under håndflaten, gir du den et kvarter til under plasten heller enn mer vann. Hvilen får gluten til å slappe av, mens mer vann bare gir en tråd som blir slapp når den koker.'}},
  ],
  variations:[
    {title:{en:'Pici all’aglione', no:'Pici all’aglione'},
     body:{en:'The other Sienese classic, and the older one: a slow-cooked sauce of tomato and a great deal of garlic, traditionally the huge mild <em>aglione</em> of the Val di Chiana. Nothing else in it at all.',
           no:'Den andre klassikeren fra Siena, og den eldste: en langkokt saus av tomat og svært mye hvitløk, tradisjonelt den store, milde <em>aglione</em> fra Val di Chiana. Ikke noe annet i det hele tatt.'}},
    {title:{en:'Pici alle briciole', no:'Pici alle briciole'},
     body:{en:'Stale bread crumbled and fried golden in olive oil with garlic, then tossed through the pici in place of cheese. It is the poorest version and the most Tuscan one, and it is the same loaf that ends up in the ribollita.',
           no:'Tørt brød smuldret og stekt gyllent i olivenolje med hvitløk, og så vendt inn i picien i stedet for ost. Det er den fattigste utgaven og den mest toskanske, og det er det samme brødet som havner i ribollitaen.'}},
    {title:{en:'If you buy the pici', no:'Hvis du kjøper picien'},
     body:{en:'Fresh and dried pici are both sold, and they are honest shortcuts. Dried ones take ten to twelve minutes and give back much less starch, so hold more water out of the cheese paste at the start and expect to work the sauce harder.',
           no:'Både fersk og tørket pici selges, og begge deler er ærlige snarveier. De tørkede bruker ti til tolv minutter og gir fra seg mye mindre stivelse, så hold igjen mer vann i ostemassen til å begynne med, og regn med å måtte jobbe hardere med sausen.'}},
  ],
},

{
  id:'cantucci', dish:'Cantucci', course:'dolce', lesson:4, serves:8, time:{prep:25, cook:50},
  hero:'cantucci', tags:['biscuits','almond','baking'],
  title:{en:'Cantucci', no:'Cantucci'},
  blurb:{en:'The almond biscuits of Prato: baked twice, hard on purpose, and built to be dunked in a glass of Vin Santo.',
         no:'Mandelkjeksene fra Prato: bakt to ganger, harde med vilje, og laget for å dyppes i et glass Vin Santo.'},
  heroCaption:{en:'Cantucci with Vin Santo: the almond biscuits of Prato, dunked in the sweet wine to end the meal.',
               no:'Cantucci med Vin Santo: mandelkjeksene fra Prato, dyppet i den søte vinen for å avslutte måltidet.'},
  wines:['Vin Santo'],
  headnote:{
    en:'<p><em>Biscotto</em> means cooked twice, and cantucci are the biscuit that took the word literally. A stiff dough of flour, sugar, eggs and whole unpeeled almonds is baked in logs, sliced on a slant while still warm, and then baked a second time on the cut faces until it is dry all the way through. What comes out will keep in a tin for weeks, which is exactly what it was for.</p>'
      + '<p>The recipe from <strong>Prato</strong> is famously lean. There is no butter and no oil in it, and that is not an oversight. Fat shortens a biscuit and makes it crumble the moment it meets liquid; a dough of flour, sugar, egg and nuts dries into something hard enough to survive being dipped and pulled out again in one piece. These biscuits are not badly made because they are difficult to bite. They are difficult to bite because that is the design.</p>'
      + '<p>Which brings you to the glass. Cantucci end a Tuscan meal with <strong>Vin Santo</strong>, the amber dessert wine dried on the grape and aged for years in small barrels, and the two are one thing rather than two. The biscuit softens in the wine, the wine takes on the almond, and nobody in Tuscany eats one without the other.</p>',
    no:'<p><em>Biscotto</em> betyr kokt to ganger, og cantucci er kjeksen som tok ordet bokstavelig. En stiv deig av mel, sukker, egg og hele, uskrellede mandler stekes i lange emner. De skjæres på skrå mens de fortsatt er lune, og stekes så en gang til på snittflatene til de er tørre tvers igjennom. Resultatet holder seg i en boks i ukevis, og det var nettopp hensikten.</p>'
      + '<p>Oppskriften fra <strong>Prato</strong> er berømt mager. Det er verken smør eller olje i den, og det er ikke en forglemmelse. Fett gjør en kjeks mør og får den til å smuldre i det øyeblikket den møter væske, mens en deig av mel, sukker, egg og nøtter tørker inn til noe som er hardt nok til å tåle å bli dyppet og trukket opp igjen i ett stykke. Disse kjeksene er ikke dårlig laget fordi de er vanskelige å bite i. De er vanskelige å bite i fordi de er laget slik med vilje.</p>'
      + '<p>Og dermed er du framme ved glasset. Cantucci avslutter et toskansk måltid sammen med <strong>Vin Santo</strong>, den ravgule dessertvinen som tørkes på druen og lagres i årevis på små fat, og de to er én ting og ikke to. Kjeksen mykner i vinen, vinen tar til seg mandelen, og ingen i Toscana spiser den ene uten den andre.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:300, u:'g', n:{en:'plain wheat flour', no:'hvetemel'}, note:{en:'tipo 00 if you have it', no:'tipo 00 hvis du har det'}},
    {q:250, u:'g', n:{en:'caster sugar', no:'sukker'}},
    {q:250, u:'g', n:{en:'whole almonds', no:'hele mandler'}, note:{en:'unpeeled and untoasted; they toast inside the dough', no:'uskrellede og uristede, for de ristes inne i deigen'}},
    {q:3, u:'', n:{en:'eggs', no:'egg'}, note:{en:'at room temperature', no:'med romtemperatur'}, round:'half'},
    {q:1, u:'', n:{en:'egg for glazing', no:'egg til pensling'}, round:'half'},
    {q:6, u:'g', n:{en:'baking powder', no:'bakepulver'}, note:{en:'the old Prato recipe uses none at all and is harder still; this makes the dough easier to handle', no:'den gamle oppskriften fra Prato bruker ikke bakepulver i det hele tatt og blir enda hardere; dette gjør deigen lettere å arbeide med'}},
    {q:1, u:'', n:{en:'orange', no:'appelsin'}, note:{en:'the zest only, finely grated', no:'bare skallet, finrevet'}, round:'half'},
    {q:2, u:'g', n:{en:'salt', no:'salt'}},
  ]}],
  steps:[
    {en:'Heat the oven to 170 °C and line two trays with baking paper.',
     no:'Sett stekeovnen på 170 °C, og kle to stekebrett med bakepapir.'},
    {en:'Mix the flour, sugar, baking powder, salt and grated orange zest together in a wide bowl.',
     no:'Bland melet, sukkeret, bakepulveret, saltet og det revne appelsinskallet i en vid bolle.'},
    {en:'Beat the three eggs and work them into the dry mixture with a wooden spoon and then a hand, until a stiff, sticky dough comes together. Add nothing to soften it; there is no butter in this dough and it is not meant to be soft.',
     no:'Pisk de tre eggene, og arbeid dem inn i melblandingen med en tresleiv og deretter med hånden, til deigen samler seg og blir stiv og klebrig. Ikke tilsett noe for å myke den opp, for det er ikke smør i denne deigen, og den skal ikke være myk.'},
    {en:'Work the almonds in whole, spreading them right through the dough rather than letting them cluster at one end.',
     no:'Arbeid inn mandlene hele, og fordel dem gjennom hele deigen i stedet for å la dem samle seg i den ene enden.'},
    {en:'Divide the dough into three and, with wet hands, roll each piece into a log about four centimetres wide. Lay them well apart on the trays, because they spread as they bake.',
     no:'Del deigen i tre, og rull hver del med våte hender til et emne på omtrent fire centimeters bredde. Legg dem godt fra hverandre på brettene, for de flyter ut under stekingen.'},
    {en:'Beat the last egg and brush the logs with it.',
     no:'Pisk det siste egget, og pensle emnene med det.'},
    {en:'Bake for about 25 minutes, until they are pale gold and firm to a fingertip but still soft in the middle.',
     no:'Stek i omtrent 25 minutter, til de er lyst gylne og faste mot en fingertupp, men fortsatt myke i midten.'},
    {en:'Take the trays out, drop the oven to 150 °C and let the logs cool for ten minutes — long enough to firm up, short enough to slice cleanly.',
     no:'Ta ut brettene, skru ovnen ned til 150 °C, og la emnene kjølne i ti minutter. Det er lenge nok til at de stivner, og kort nok til at de lar seg skjære pent.'},
    {en:'Cut each log on a slant into slices about a centimetre and a half thick, using one firm stroke of a serrated knife rather than sawing back and forth.',
     no:'Skjær hvert emne på skrå i skiver på rundt halvannen centimeter, med ett bestemt drag av en brødkniv i stedet for å sage fram og tilbake.'},
    {en:'Lay the slices cut side down on the trays and bake them a second time for 15 to 20 minutes, turning them once halfway, until they are dry and hard right through.',
     no:'Legg skivene med snittflaten ned på brettene, og stek dem en gang til i 15 til 20 minutter. Snu dem én gang underveis, til de er tørre og harde tvers igjennom.'},
    {en:'Cool them completely on a rack before they go into a tin. They keep for weeks, and they are meant to be too hard to eat comfortably on their own — that is what the Vin Santo is for.',
     no:'La dem kjølne helt på rist før de legges i en boks. De holder seg i ukevis, og de skal være for harde til å spises behagelig alene. Det er det Vin Santo er til for.'},
  ],
  notes:[
    {title:{en:'The second bake is the whole idea', no:'Den andre stekingen er hele poenget'},
     body:{en:'The first bake sets the dough into what is really a cake. The second one, at a lower temperature and on the cut faces, drives the remaining water out of the crumb, and it is water that makes a biscuit go soft in the tin. Cut the second bake short and you get something pleasant that goes soft in the tin within three days.',
           no:'Den første stekingen får deigen til å stivne til det som egentlig er en kake. Den andre, på lavere temperatur og på snittflatene, driver det som er igjen av vann ut av kjeksen, og vannet er grunnen til at en kjeks blir bløt i boksen. Korter du ned den andre stekingen, får du noe som smaker godt, men blir bløtt i boksen i løpet av tre dager.'}},
    {title:{en:'Cut them warm', no:'Skjær dem lune'},
     body:{en:'A cold log shatters under the knife and a hot one squashes flat, so the ten minutes out of the oven is a real window rather than a formality. One firm stroke of a serrated blade, angled across the log, cuts the almonds instead of dragging them out and taking half the slice with them.',
           no:'Et kaldt emne smuldrer under kniven, og et glovarmt klemmes flatt, så de ti minuttene utenfor ovnen er et virkelig tidsvindu og ikke en formalitet. Ett bestemt drag med brødkniven, på skrå over emnet, skjærer mandlene i stedet for å dra dem ut og ta med seg halve skiven.'}},
    {title:{en:'Why there is no butter', no:'Hvorfor det ikke er smør i dem'},
     body:{en:'Fat coats the flour and stops long gluten strands forming, which is what makes a shortbread crumble. Crumbling is the last thing you want in a biscuit that is going to be held in a glass of wine. Flour, sugar, egg and nuts dry into a dense structure that softens at the dipped end and stays whole at the other.',
           no:'Fett legger seg rundt melet og hindrer at det danner seg lange glutentråder, og nettopp derfor smuldrer en sandkake. Å smuldre er det siste du vil ha i en kjeks som skal holdes nede i et glass vin. Mel, sukker, egg og nøtter tørker inn til en tett struktur som mykner i den enden som dyppes, og holder seg hel i den andre.'}},
  ],
  variations:[
    {title:{en:'Almonds and pine nuts', no:'Mandler og pinjekjerner'},
     body:{en:'Some Prato bakers put a handful of pine nuts in alongside the almonds. They are softer, sweeter and more resinous, and they turn up as small pale surprises in the cut face.',
           no:'Noen bakere i Prato har i en neve pinjekjerner ved siden av mandlene. De er mykere, søtere og mer harpiksaktige, og de dukker opp som små lyse overraskelser i snittflaten.'}},
    {title:{en:'Cantuccini', no:'Cantuccini'},
     body:{en:'Roll the logs half as wide and you get cantuccini, the small ones that most of Italy sells in bags. They dry faster, so take five minutes off the second bake, and they are easier to hand round with coffee.',
           no:'Ruller du emnene halvparten så brede, får du cantuccini, de små som selges i poser over hele Italia. De tørker raskere, så trekk fem minutter fra den andre stekingen, og de er lettere å by rundt til kaffen.'}},
    {title:{en:'Chocolate and the rest', no:'Sjokolade og resten'},
     body:{en:'Tuscan bakeries now make them with chocolate, pistachio, hazelnut and figs, and some of them are very good. None of them is what the Vin Santo was poured for; keep a plain batch in the tin for that.',
           no:'Toskanske bakerier lager dem nå med sjokolade, pistasj, hasselnøtt og fiken, og noen av dem er svært gode. Ingen av dem er det Vin Santo ble skjenket til, så ha en boks med de vanlige stående til akkurat det.'}},
  ],
},

];
