// Trentino-Alto Adige recipes. Bilingual in one file: the quantities are written once so English and
// Norwegian cannot drift apart. Contract: docs/recipe-format.md. Checked by tools/recipecheck.py. Never narrated.
// Everything here follows the Trentino food reading (content/trentino.js, lesson 3): butter instead of oil,
// rye and buckwheat instead of wheat, stale bread turned into dumplings, speck salted and lightly smoked,
// apples by the million tonne, and strudel dough stretched until the tablecloth shows through.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-32'] = [

{
  id:'canederli', dish:'Canederli', course:'primo', lesson:3, serves:4, time:{prep:35, cook:15},
  hero:'canederli', tags:['bread','speck','dumpling'],
  title:{en:'Canederli (Speckknödel)', no:'Canederli (Speckknödel)'},
  blurb:{en:'Bread dumplings with speck, boiled and served in beef broth or dry with butter. The whole trick is how much milk stale bread will take.',
         no:'Brødboller med speck, kokt og servert i oksekraft eller tørre med smør. Hele kunsten ligger i hvor mye melk gammelt brød vil ta imot.'},
  heroCaption:{en:'Speckknödel with a salad: the everyday dish of every mountain hut in the region.',
               no:'Speckknödel med salat: hverdagsretten på hver eneste fjellhytte i regionen.'},
  wines:['Lagrein'],
  headnote:{
    en:'<p>Nothing was thrown away in a mountain farmhouse, and the dumpling is what happened to yesterday’s bread. Cubes of stale white loaf, milk, egg, a handful of flour and whatever the larder held — speck, spinach or cheese — rolled the size of a tennis ball and boiled. In Alto Adige the menu says <em>Speckknödel</em>; in Trentino the same dumpling is called <em>canederli</em>.</p>'
      + '<p>Everything depends on how much milk the bread will take. A loaf a day or two old has lost its free water, and its starch drinks the milk without turning to paste. Fresh bread collapses instead, and then flour has to hold the dumpling together, which makes it heavy. Add milk until the cubes are damp all the way through and no liquid stands in the bottom of the bowl, and stop there.</p>'
      + '<p>The second rule is not to work the mixture. Bring it together with your fingers only until it holds, then roll one dumpling and cook it on its own before you shape the rest. One that falls apart wants a little more flour; one that comes out rubbery was squeezed too hard. And the water must shiver rather than boil, or the surface tears.</p>',
    no:'<p>På en fjellgård ble ingenting kastet, og melbollen er det som skjedde med gårsdagens brød. Terninger av gammel loff, melk, egg, en neve mel og det spiskammeret hadde å by på — speck, spinat eller ost. Massen rulles på størrelse med en tennisball og kokes. I Alto Adige sier menyen <em>Speckknödel</em>, mens den samme bollen i Trentino heter <em>canederli</em>.</p>'
      + '<p>Alt avhenger av hvor mye melk brødet vil ta imot. Et brød som er en dag eller to gammelt, har mistet det frie vannet sitt, og stivelsen drikker melken uten å bli til deig. Ferskt brød faller sammen i stedet, og da må melet holde bollen sammen, og den blir tung. Spe med melk til terningene er fuktige tvers igjennom og det ikke står væske igjen i bunnen av bollen, og stopp der.</p>'
      + '<p>Den andre regelen er at massen ikke skal arbeides. Samle den med fingrene bare til den henger sammen, rull så én bolle og kok den alene før du former resten. En bolle som går i oppløsning, vil ha litt mer mel, og en som blir seig, er klemt for hardt. Vannet skal sitre og ikke fosskoke, ellers revner overflaten.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:250, u:'g', n:{en:'stale white bread', no:'gammel loff'}, note:{en:'a plain white loaf a day or two old, crusts off, in cubes about 1 cm across', no:'et lyst brød fra dagen før eller to, uten skorpe, i terninger på rundt 1 cm. Grovbrød og rugbrød blir feil her; fjellbrødet bollene bygger på, er lyst'}},
    {q:250, u:'ml', n:{en:'milk', no:'melk'}, note:{en:'warmed to just above blood heat', no:'varmet til litt over kroppstemperatur'}},
    {q:2, u:'', n:{en:'eggs', no:'egg'}, round:'half'},
    {q:120, u:'g', n:{en:'Speck Alto Adige', no:'Speck Alto Adige'}, note:{en:'in small dice; lightly smoked cured ham is the nearest substitute, bacon is not', no:'i små terninger. Lettrøkt spekeskinke er det nærmeste du kommer, bacon er det ikke'}},
    {q:1, u:'', n:{en:'small onion', no:'liten løk'}, note:{en:'finely chopped', no:'finhakket'}, round:'half'},
    {q:20, u:'g', n:{en:'butter', no:'smør'}},
    {q:25, u:'g', n:{en:'plain flour', no:'hvetemel'}, note:{en:'and a little more in reserve', no:'og litt ekstra i reserve'}},
    {q:10, u:'g', n:{en:'flat-leaf parsley or chives', no:'bladpersille eller gressløk'}, note:{en:'chopped', no:'hakket'}},
    {u:'', n:{en:'salt and grated nutmeg', no:'salt og revet muskat'}, scale:'none'},
    {q:2, u:'l', n:{en:'beef broth', no:'oksekraft'}, note:{en:'to serve them in; salted water if you are serving them dry', no:'å servere dem i. Saltet vann holder hvis du serverer dem tørre'}, scale:'sub'},
    {q:50, u:'g', n:{en:'butter to finish', no:'smør til servering'}, note:{en:'only if you serve them dry, with sage', no:'bare hvis du serverer dem tørre, med salvie'}},
    {q:40, u:'g', n:{en:'grated Trentingrana or Parmigiano', no:'revet Trentingrana eller Parmigiano'}},
  ]}],
  steps:[
    {en:'Cut the crusts off the bread and dice it small, then spread the cubes out in a wide bowl.',
     no:'Skjær skorpen av brødet, skjær det i små terninger, og bre terningene utover i en vid bolle.'},
    {en:'Warm the milk until it is just above blood heat, pour it over the bread and turn it through with your hands. Leave it for 20 minutes.',
     no:'Varm melken til den er så vidt over kroppstemperatur, hell den over brødet, og vend det rundt med hendene. La det stå i 20 minutter.'},
    {en:'Melt the butter in a small pan, soften the onion in it without colour, add the diced speck and let it warm through until its fat runs. Leave it to cool.',
     no:'Smelt smøret i en liten panne, la løken bli myk uten å ta farge, ha i speckterningene, og la dem varmes til fettet smelter ut. Sett det til side og la det bli kaldt.'},
    {en:'Press the soaked bread with your palm. It should be damp all the way through with no liquid left standing; if dry crumbs remain, work in a little more warm milk.',
     no:'Trykk på det bløtlagte brødet med håndflaten. Det skal være fuktig tvers igjennom uten at det står væske igjen, og er det tørre smuler igjen, arbeider du inn litt mer varm melk.'},
    {en:'Beat the eggs, pour them over the bread with the speck and onion and the chopped herbs, and season with salt and nutmeg.',
     no:'Pisk sammen eggene, hell dem over brødet sammen med speck og løk og de hakkede urtene, og smak til med salt og muskat.'},
    {en:'Mix with your fingers only until the mass holds together. Do not knead it and do not squeeze it.',
     no:'Bland med fingrene bare til massen henger sammen. Ikke elt den, og ikke klem den.'},
    {en:'Scatter the flour over, fold it through and let the bowl rest for 15 minutes while the bread finishes drinking.',
     no:'Dryss melet over, vend det inn, og la bollen hvile i 15 minutter mens brødet drikker ferdig.'},
    {en:'Wet your hands and roll one dumpling the size of a tennis ball, firm enough to hold its shape but no firmer.',
     no:'Fukt hendene og rull én bolle på størrelse med en tennisball, fast nok til å holde formen, men ikke fastere.'},
    {en:'Lower it into simmering salted water as a test. If it opens up, work a little more flour into the bowl before you roll the others.',
     no:'Senk den ned i saltet vann som så vidt småkoker, som en prøve. Åpner den seg, arbeider du litt mer mel inn i massen før du ruller de andre.'},
    {en:'Roll the rest, drop them in and keep the water at a shiver for about 15 minutes, until they float high and feel light.',
     no:'Rull resten, ha dem i, og hold vannet så vidt sitrende i rundt 15 minutter, til de flyter høyt og kjennes lette.'},
    {en:'Serve two to a bowl in hot beef broth with chives, or drained, with butter browned with sage and a shower of grated cheese.',
     no:'Server to i hver skål i varm oksekraft med gressløk, eller avrent, med smør som er brunet med salvie, og rikelig revet ost på toppen.'},
  ],
  notes:[
    {title:{en:'Why the bread has to be stale', no:'Derfor må brødet være gammelt'},
     body:{en:'Bread that has dried for a day or two has lost its free water, so its starch takes up milk and stays in cubes you can still see in the finished dumpling. Fresh bread is already saturated: it turns to paste, the mixture goes slack, and the only way to save it is flour, which is exactly what makes a dumpling heavy. The flour in the list is insurance, not structure.',
           no:'Brød som har tørket i en dag eller to, har mistet det frie vannet sitt, så stivelsen tar opp melk og terningene holder seg synlige i den ferdige bollen. Ferskt brød er allerede mettet. Det blir til deig, massen blir slapp, og den eneste redningen er mel, som er nettopp det som gjør en bolle tung. Melet i listen er en forsikring, ikke et byggemateriale.'}},
    {title:{en:'Roll one first', no:'Rull én først'},
     body:{en:'The bread decides the recipe, and no two loaves behave the same, so the test dumpling replaces every measurement. It tells you in two minutes what a whole batch would tell you too late, and the fix is small: a spoonful more flour, folded in, never kneaded.',
           no:'Brødet bestemmer oppskriften, og ingen to brød oppfører seg likt, så prøvebollen erstatter alle mål. Den forteller deg på to minutter det en hel porsjon ville ha fortalt deg for sent, og rettelsen er liten: en skje mel til, vendt inn, aldri eltet.'}},
    {title:{en:'A shivering pot', no:'En gryte som sitrer'},
     body:{en:'A dumpling is held together by soaked bread and one egg, and nothing else. A rolling boil knocks the surface apart before the egg has set; water that barely moves lets the outside firm up first and the middle cook through. Use a wide pot so they are not pressed against each other.',
           no:'En bolle holdes sammen av bløtlagt brød og ett egg, og ingenting annet. Fosskoking slår overflaten i stykker før egget har stivnet, mens vann som knapt beveger seg, lar utsiden bli fast først og midten koke gjennom. Bruk en vid gryte, så de ikke presses mot hverandre.'}},
  ],
  variations:[
    {title:{en:'Spinach and cheese', no:'Spinat og ost'},
     body:{en:'The same bread base takes spinach, squeezed dry and chopped, for green Spinatknödel, or diced mountain cheese for Käseknödel. Both are eaten in broth as often as with butter, and both are what a farmhouse made on the days there was no speck to spare.',
           no:'Den samme brødbasen tar imot spinat som er presset tørr og hakket, til grønne Spinatknödel, eller terninger av fjellost til Käseknödel. Begge spises like ofte i kraft som med smør, og begge hører til de dagene en fjellgård ikke hadde speck å avse.'}},
    {title:{en:'Kaspressknödel', no:'Kaspressknödel'},
     body:{en:'Work grated cheese through the mixture, flatten each dumpling to a thick disc and fry it in butter on both sides until the crust is dark. They are floated in clear beef broth, and they are the version that suits a leftover mixture best.',
           no:'Arbeid revet ost inn i massen, klapp hver bolle flat til en tykk skive, og stek den i smør på begge sider til skorpen er mørk. De legges i klar oksekraft, og de er utgaven som passer best når du har en rest av massen til overs.'}},
    {title:{en:'Strangolapreti', no:'Strangolapreti'},
     body:{en:'Trentino makes the same idea with more spinach and less bread, shaped into small ovals rather than balls: <em>strangolapreti</em>, priest-stranglers, served with butter and sage. Treat the mixture with the same care and the same reluctance to knead.',
           no:'Trentino bruker den samme ideen med mer spinat og mindre brød, og former den til små ovaler i stedet for kuler: <em>strangolapreti</em>, prestekvelere, servert med smør og salvie. Behandle massen like forsiktig og med den samme motviljen mot å elte.'}},
  ],
},

{
  id:'schlutzkrapfen', dish:'Schlutzkrapfen', course:'primo', lesson:3, serves:4, time:{prep:75, cook:5},
  hero:'schlutzkrapfen', tags:['pasta','rye','spinach','vegetarian'],
  title:{en:'Schlutzkrapfen', no:'Schlutzkrapfen'},
  blurb:{en:'Half-moons of rye dough filled with spinach and ricotta, dressed in browned butter and chives. The region’s pasta, and it is not Italian pasta.',
         no:'Halvmåner av rugdeig fylt med spinat og ricotta, vendt i brunet smør og gressløk. Regionens pasta, og det er ikke italiensk pasta.'},
  heroCaption:{en:'Schlutzkrapfen, mezzelune on the Italian side of the region: one fold, one seam, butter and chives.',
               no:'Schlutzkrapfen, mezzelune på den italienske siden av regionen: én bretting, én skjøt, smør og gressløk.'},
  wines:['Pinot Grigio'],
  headnote:{
    en:'<p>Schlutzkrapfen are the region’s pasta and they belong to the German-speaking side of it. The dough is half rye, rolled thin, cut in discs and folded once over a filling of spinach and ricotta. Trentino calls the same shape <em>mezzelune</em>, half-moons. They come to the table in browned butter with grated cheese and a great deal of chives, and they are on the long autumn table at Törggelen between the barley soup and the smoked sausage.</p>'
      + '<p>Rye is the point and the problem. It carries almost no gluten, so a sheet of pure rye tears the moment you stretch it; the wheat is the scaffolding, and half and half is about as far as the dough will go. Rye also takes up water slowly, which is why the rest is not a formality. Roll the dough straight away and it is sticky and short. Give it half an hour and it turns supple.</p>'
      + '<p>The filling has one rule: get the water out of the spinach. Wilt it, cool it and wring it in a cloth until you think you have done it harm, then wring it again. Water in the filling becomes steam in the pot, and steam finds the seam.</p>',
    no:'<p>Schlutzkrapfen er regionens pasta, og de hører hjemme på den tysktalende siden av den. Deigen er halvt rug, kjevlet tynn, stukket ut i sirkler og brettet én gang over et fyll av spinat og ricotta. Trentino kaller den samme formen <em>mezzelune</em>, halvmåner. De kommer på bordet i brunet smør med revet ost og rikelig med gressløk, og de står på langbordet under Törggelen om høsten, mellom byggsuppen og de røkte pølsene.</p>'
      + '<p>Rugen er både poenget og problemet. Den har nesten ikke gluten, så en leiv av ren rug revner i det du strekker den. Hveten er stillaset, og halvt om halvt er omtrent så langt deigen strekker seg. Rug tar dessuten opp vann langsomt, og derfor er hvilen ingen formalitet. Kjevler du med en gang, er deigen klissete og kort. Gir du den en halvtime, blir den smidig.</p>'
      + '<p>Fyllet har én regel: få vannet ut av spinaten. Damp den, avkjøl den, og vri den i et klede til du synes du har fart stygt med den, og vri så en gang til. Vann i fyllet blir til damp i gryten, og dampen finner skjøten.</p>'},
  ingredients:[
    { group:{en:'Dough', no:'Deig'}, items:[
      {q:150, u:'g', n:{en:'rye flour', no:'rugmel'}, note:{en:'finely milled and sifted, not coarse wholemeal rye', no:'fint malt og siktet rugmel, ikke sammalt grov rug'}},
      {q:150, u:'g', n:{en:'plain wheat flour', no:'hvetemel'}},
      {q:1, u:'', n:{en:'egg', no:'egg'}, round:'half'},
      {q:110, u:'ml', n:{en:'warm water', no:'varmt vann'}, note:{en:'held back and added a little at a time', no:'holdes igjen og spes i litt om gangen'}},
      {q:15, u:'ml', n:{en:'olive oil or melted butter', no:'olivenolje eller smeltet smør'}},
      {q:5, u:'g', n:{en:'salt', no:'salt'}},
    ]},
    { group:{en:'Filling', no:'Fyll'}, items:[
      {q:500, u:'g', n:{en:'spinach', no:'spinat'}, note:{en:'leaf spinach; frozen works if it is thawed and wrung out hard', no:'bladspinat. Frossen går fint hvis den er tint og vridd godt tørr'}},
      {q:150, u:'g', n:{en:'ricotta', no:'ricotta'}, note:{en:'drained; Norwegian kesam is too wet and needs an hour in a sieve', no:'avrent. Kesam er for våt og trenger en time i sil'}},
      {q:1, u:'', n:{en:'small onion', no:'liten løk'}, note:{en:'finely chopped', no:'finhakket'}, round:'half'},
      {q:20, u:'g', n:{en:'butter', no:'smør'}},
      {q:30, u:'g', n:{en:'grated Trentingrana or Parmigiano', no:'revet Trentingrana eller Parmigiano'}},
      {u:'', n:{en:'salt, pepper and grated nutmeg', no:'salt, pepper og revet muskat'}, scale:'none'},
    ]},
    { group:{en:'To finish', no:'Til servering'}, items:[
      {q:70, u:'g', n:{en:'butter', no:'smør'}},
      {q:30, u:'g', n:{en:'grated Trentingrana or Parmigiano', no:'revet Trentingrana eller Parmigiano'}},
      {q:15, u:'g', n:{en:'chives', no:'gressløk'}, note:{en:'finely cut, and more than looks sensible', no:'finklippet, og mer enn det ser fornuftig ut'}},
      {q:4, u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:20, u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
    ]},
  ],
  steps:[
    {en:'Mix the two flours with the salt, heap them on the table and make a well in the middle.',
     no:'Bland de to meltypene med saltet, samle dem i en haug på bordet, og lag en brønn i midten.'},
    {en:'Beat the egg with the oil and most of the warm water, pour it into the well and bring the flour in from the edges until you have a firm dough. Add the rest of the water only if it stays dry and crumbly.',
     no:'Pisk sammen egget med oljen og mesteparten av det varme vannet, hell det i brønnen, og dra melet inn fra kantene til du har en fast deig. Spe med resten av vannet bare hvis den holder seg tørr og smuldrete.'},
    {en:'Knead for 10 minutes, until the dough is smooth and springs back slowly. Wrap it and leave it at room temperature for 30 minutes.',
     no:'Elt i 10 minutter, til deigen er glatt og fjærer langsomt tilbake. Pakk den inn, og la den ligge i romtemperatur i 30 minutter.'},
    {en:'Wilt the spinach in a covered pan with nothing but the water on the leaves, then cool it under the cold tap and wring it dry in a cloth. Chop it fine.',
     no:'Damp spinaten i en gryte med lokk, uten annet vann enn det som sitter på bladene, avkjøl den under kaldt vann, og vri den tørr i et klede. Hakk den fin.'},
    {en:'Soften the onion in butter without letting it colour, stir in the spinach and let any last moisture steam off.',
     no:'La løken bli myk i smør uten å ta farge, rør inn spinaten, og la den siste fuktigheten dampe bort.'},
    {en:'Take the pan off the heat, cool the mixture, then fold in the ricotta and the grated cheese and season with salt, pepper and nutmeg. The filling should sit in a mound on a spoon without slumping.',
     no:'Ta pannen av platen, la blandingen bli kald, vend så inn ricottaen og den revne osten, og smak til med salt, pepper og muskat. Fyllet skal ligge som en topp på skjeen uten å skli utover.'},
    {en:'Roll the dough out very thin, a quarter at a time, keeping the rest covered so it does not skin over.',
     no:'Kjevle ut deigen svært tynn, en fjerdedel om gangen, og hold resten tildekket, så den ikke tørker på overflaten.'},
    {en:'Cut out discs about 8 cm across, put a small mound of filling slightly off centre on each and brush the rim with water.',
     no:'Stikk ut sirkler på rundt 8 cm, legg en liten topp med fyll litt til side for midten på hver, og pensle kanten med vann.'},
    {en:'Fold each disc into a half-moon and press the edge closed from the fold outwards, driving the air out ahead of your thumb.',
     no:'Brett hver sirkel til en halvmåne, og trykk kanten sammen fra bretten og utover, slik at luften presses foran tommelen.'},
    {en:'Cook them in salted water that is barely simmering for 4 minutes, until they lift to the surface. A hard boil will burst the seam.',
     no:'Kok dem i saltet vann som så vidt småkoker, i 4 minutter, til de stiger til overflaten. Fosskoking sprenger skjøten.'},
    {en:'Brown the butter in a wide pan until it smells of hazelnuts, lift the half-moons in with a slotted spoon and turn them once.',
     no:'Brun smøret i en vid panne til det lukter hasselnøtt, løft halvmånene over med hullsleiv, og vend dem én gang.'},
    {en:'Scatter the grated cheese and the chives over, and eat them straight away.',
     no:'Strø den revne osten og gressløken over, og spis dem med en gang.'},
  ],
  notes:[
    {title:{en:'What the wheat is doing there', no:'Hva hveten gjør i deigen'},
     body:{en:'Rye protein does not build a gluten network, so a rye sheet has nothing holding it and splits as it thins. The wheat supplies that network and the rye supplies the flavour and the grey colour. Push the rye above half and you will not get the dough thin enough; drop it below a third and you have made ordinary ravioli.',
           no:'Rugprotein bygger ikke et glutennettverk, så en leiv av rug har ingenting som holder den, og den sprekker etter hvert som den blir tynn. Hveten leverer nettverket, og rugen leverer smaken og den grå fargen. Går rugandelen over halvparten, får du ikke deigen tynn nok, og faller den under en tredel, har du laget helt vanlig ravioli.'}},
    {title:{en:'Dry filling, whole parcel', no:'Tørt fyll, hel pakke'},
     body:{en:'Spinach is nine tenths water and gives most of it up in the pot. Trapped inside a parcel it turns to steam, the parcel inflates and the seam is the weakest place, so that is where it goes. Wringing the spinach out and cooling the filling before it is wrapped removes both the water and the steam pressure.',
           no:'Spinat er ni tideler vann og gir fra seg mesteparten i gryten. Når vannet er fanget inne i en pakke, blir det til damp, pakken blåser seg opp, og skjøten er det svakeste stedet, så det er der den ryker. Vrir du spinaten og lar fyllet bli kaldt før det pakkes inn, fjerner du både vannet og damptrykket.'}},
    {title:{en:'One fold, one seam', no:'Én bretting, én skjøt'},
     body:{en:'A half-moon is folded from a single disc, so it has one edge to seal instead of the four of a square ravioli. That is why the shape survives a rye dough that would give way on a longer seam, and why the fold at the top is thicker and takes the butter better.',
           no:'En halvmåne brettes av én sirkel og har dermed én kant å lukke i stedet for de fire på en firkantet ravioli. Derfor tåler formen en rugdeig som ville gitt etter langs en lengre skjøt, og derfor er bretten på toppen tykkere og tar bedre imot smøret.'}},
  ],
  variations:[
    {title:{en:'Sauerkraut or potato', no:'Surkål eller potet'},
     body:{en:'The same dough is filled with sauerkraut squeezed dry and fried with onion, or with mashed potato worked with chives and a little cheese. Both belong to the winter end of the year, when there was no spinach in the garden.',
           no:'Den samme deigen fylles med surkål som er presset tørr og stekt med løk, eller med potetstappe rørt med gressløk og litt ost. Begge hører til vinterhalvåret, da det ikke sto spinat i hagen.'}},
    {title:{en:'All wheat', no:'Bare hvete'},
     body:{en:'Restaurants that want a paler, silkier half-moon leave the rye out and use only wheat. It rolls thinner and handles more easily, and it tastes of the filling rather than of the mountains. The rye is the reason a Schlutzkrapfen does not taste like a raviolo.',
           no:'Restauranter som vil ha en lysere og silkemykere halvmåne, dropper rugen og bruker bare hvete. Deigen lar seg kjevle tynnere og er lettere å håndtere, og den smaker av fyllet i stedet for av fjellet. Rugen er grunnen til at en Schlutzkrapfen ikke smaker som en raviolo.'}},
    {title:{en:'Butter, or broth', no:'Smør, eller kraft'},
     body:{en:'Browned butter is the everyday dressing, but the same half-moons are also served a few to a bowl in clear beef broth, the way the dumplings are. Roll them a little smaller for that, and leave the grated cheese on the table.',
           no:'Brunet smør er den vanlige måten å servere dem på, men de samme halvmånene kommer også noen få i hver skål i klar oksekraft, slik melbollene gjør. Lag dem litt mindre til det, og la den revne osten stå på bordet.'}},
  ],
},

{
  id:'polenta-con-funghi', dish:'Polenta with mushrooms', course:'primo', lesson:3, serves:4, time:{prep:25, cook:50},
  hero:'polenta', tags:['maize','mushroom','vegetarian'],
  title:{en:'Polenta with mushrooms', no:'Polenta med sopp'},
  blurb:{en:'Coarse maize stirred for three quarters of an hour, with porcini fried hard in butter. The staple of the Italian-speaking half of the region.',
         no:'Grovmalt mais rørt i tre kvarter, med steinsopp stekt hardt i smør. Basismaten i den italiensktalende halvdelen av regionen.'},
  heroCaption:{en:'Polenta with porcini. Trentino eats polenta with everything, and the woods above the vineyards supply the rest.',
               no:'Polenta med steinsopp. Trentino spiser polenta til alt, og skogene ovenfor vinmarkene leverer resten.'},
  wines:['Teroldego Rotaliano'],
  headnote:{
    en:'<p>Polenta is what the Italian half of the region eats with everything. Bolzano’s pantry is Austrian and reaches for a dumpling; Trento’s reaches for a spoonful of maize, and puts it under game, under sausages, under braised beef and under mushrooms out of the chestnut and beech woods that climb behind the vineyards.</p>'
      + '<p>Coarse stone-ground maize and three quarters of an hour of stirring, and nothing else will do it. Maize starch gelatinises slowly and the grain is large, so under about forty minutes polenta tastes raw and chalky. It goes on improving until it comes cleanly away from the side of the pan, which is the only doneness test worth having. Instant polenta is pre-cooked and dried; it is ready in five minutes and has neither the chew nor the sweetness.</p>'
      + '<p>The mushrooms want the opposite handling. A hot pan, plenty of room and no salt until the end: salt early and they give up their water and stew in it, grey. Dried porcini are not a fallback but a seasoning. Soak them, chop them into the pan, and use the soaking liquid, poured carefully off the grit, because that is where most of the flavour went.</p>',
    no:'<p>Polenta er det den italienske halvdelen av regionen spiser til alt. Spiskammeret i Bolzano er østerriksk og griper etter en melbolle, mens Trento griper etter en skje mais og legger den under viltkjøtt, under pølser, under grytestekt oksekjøtt og under sopp fra kastanje- og bøkeskogene som klatrer bak vinmarkene.</p>'
      + '<p>Grovmalt mais og tre kvarters røring, og ingenting annet gjør jobben. Maisstivelsen forkleistrer langsomt og kornet er stort, så under omtrent førti minutter smaker polentaen rå og krittaktig. Den blir bare bedre helt til den slipper kanten av kjelen, og den prøven er den eneste som er verdt noe. Hurtigpolenta er forkokt og tørket. Den er ferdig på fem minutter, og den har verken tyggemotstanden eller sødmen.</p>'
      + '<p>Soppen vil ha stikk motsatt behandling: varm panne, god plass og ikke salt før helt til slutt. Salter du tidlig, gir den fra seg vannet og koker grått i det. Tørket steinsopp er ingen nødløsning, men et krydder. Bløtlegg den, hakk den ned i pannen, og bruk bløtleggingsvannet, som du heller forsiktig av grumset, for det er dit mesteparten av smaken har gått.</p>'},
  ingredients:[
    { group:{en:'Polenta', no:'Polenta'}, items:[
      {q:250, u:'g', n:{en:'coarse maize flour', no:'grovmalt maismel'}, note:{en:'stone-ground bramata; read the packet, because most polenta sold in Norway is the instant kind', no:'steinmalt bramata. Les pakken, for det meste av polentaen som selges i Norge, er hurtigpolenta'}},
      {q:1200, u:'ml', n:{en:'water', no:'vann'}},
      {q:12, u:'g', n:{en:'salt', no:'salt'}},
      {q:30, u:'g', n:{en:'butter', no:'smør'}},
      {q:50, u:'g', n:{en:'grated Trentingrana or Parmigiano', no:'revet Trentingrana eller Parmigiano'}},
    ]},
    { group:{en:'Mushrooms', no:'Sopp'}, items:[
      {q:400, u:'g', n:{en:'fresh mushrooms', no:'fersk sopp'}, note:{en:'porcini if you can get them, otherwise chestnut mushrooms with a few chanterelles', no:'steinsopp om du får tak i den, ellers aromasopp med noen kantareller innimellom'}},
      {q:20, u:'g', n:{en:'dried porcini', no:'tørket steinsopp'}, note:{en:'soaked in warm water; keep the liquid', no:'bløtlagt i varmt vann. Ta vare på vannet'}},
      {q:1, u:'', n:{en:'garlic clove', no:'hvitløksfedd'}, note:{en:'crushed but left whole', no:'knust, men holdt helt'}, round:'half'},
      {q:30, u:'g', n:{en:'butter', no:'smør'}},
      {q:15, u:'ml', n:{en:'olive oil', no:'olivenolje'}},
      {q:10, u:'g', n:{en:'flat-leaf parsley', no:'bladpersille'}, note:{en:'chopped at the last moment', no:'hakket i siste liten'}},
      {u:'', n:{en:'salt and pepper', no:'salt og pepper'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Pour warm water over the dried porcini and leave them for 20 minutes. Lift them out, chop them, and pour the liquid carefully off the grit that has settled.',
     no:'Hell varmt vann over den tørkede steinsoppen, og la den stå i 20 minutter. Løft den opp, hakk den, og hell væsken forsiktig av grumset som har lagt seg.'},
    {en:'Bring the water to the boil in a heavy pan with a thick base and salt it.',
     no:'Kok opp vannet i en tykkbunnet kjele, og salt det.'},
    {en:'Rain the maize in with one hand while you whisk steadily with the other, so it never has a chance to clump.',
     no:'La maisen risle ned med den ene hånden mens du visper jevnt med den andre, så den aldri får sjansen til å klumpe seg.'},
    {en:'Turn the heat as low as it will go, change to a wooden spoon and cook for 45 minutes, stirring often and scraping the base and the corners.',
     no:'Skru varmen så lavt den går, bytt til tresleiv, og la det koke i 45 minutter mens du rører ofte og skraper bunn og hjørner.'},
    {en:'Meanwhile brush the fresh mushrooms clean and trim them. Do not wash them under the tap; they take up water and will not brown.',
     no:'Børst i mellomtiden den ferske soppen ren, og rens den. Ikke vask den under springen, for da suger den til seg vann og lar seg ikke brune.'},
    {en:'Slice the mushrooms thickly and heat the butter and oil in a wide pan with the garlic until the butter foams.',
     no:'Skjær soppen i tykke skiver, og varm smøret og oljen i en vid panne sammen med hvitløken til smøret bruser.'},
    {en:'Fry the mushrooms in one uncrowded layer, in batches if you must, without touching them until they have taken colour on the underside.',
     no:'Stek soppen i ett lag med god plass, i flere omganger om nødvendig, uten å røre den før den har fått farge på undersiden.'},
    {en:'Add the chopped soaked porcini and a little of the strained liquid, and let it bubble down until it is syrupy and coats the pieces.',
     no:'Ha i den hakkede, bløtlagte steinsoppen og litt av den avsilte væsken, og la det koke inn til det er sirupsaktig og legger seg rundt bitene.'},
    {en:'Fish out the garlic, season with salt and pepper now and not before, take the pan off the heat and stir the parsley through.',
     no:'Fisk opp hvitløken, smak til med salt og pepper nå og ikke før, ta pannen av platen, og rør inn persillen.'},
    {en:'The polenta is ready when it pulls away from the side of the pan in one mass. Beat in the butter and the grated cheese.',
     no:'Polentaen er ferdig når den slipper kanten av kjelen i én masse. Pisk inn smøret og den revne osten.'},
    {en:'Spoon it onto warm plates, press a hollow in the middle of each and spoon the mushrooms and their juices in.',
     no:'Øs den opp på varme tallerkener, trykk en grop i midten av hver, og legg soppen og kraften fra den oppi.'},
  ],
  notes:[
    {title:{en:'Why it takes three quarters of an hour', no:'Derfor tar det tre kvarter'},
     body:{en:'Coarse maize is milled to particles many times the size of wheat flour, and each one has to swell and burst before the polenta stops tasting of raw grain. Heat cannot hurry that; only time and water get to the middle of the particle. The moment the mass comes away from the pan in one piece, the starch has done what it is going to do.',
           no:'Grovmalt mais er kvernet til partikler som er mange ganger større enn dem i hvetemel, og hver enkelt må svelle og sprekke før polentaen slutter å smake av rått korn. Varme kan ikke få fart på det, for bare tid og vann når inn til midten av partikkelen. I det øyeblikket massen slipper kjelen i ett stykke, har stivelsen gjort det den skal.'}},
    {title:{en:'Brown before you salt', no:'Brun før du salter'},
     body:{en:'A mushroom is mostly water held in a soft structure, and salt pulls that water straight out. In a crowded or lukewarm pan the water pools, the temperature falls to boiling point and nothing browns. Give them room and a hot pan and the surface dries and colours first, and the flavour that colour builds cannot be got any other way.',
           no:'En sopp er for det meste vann som sitter i en myk struktur, og salt trekker vannet rett ut. I en overfylt eller lunken panne samler vannet seg, temperaturen faller til kokepunktet, og ingenting brunes. Gi soppen plass og varm panne, så tørker og farges overflaten først, og smaken den fargen bygger, kan ikke skaffes på noen annen måte.'}},
  ],
  variations:[
    {title:{en:'Polenta the next day', no:'Polenta dagen etter'},
     body:{en:'Spread what is left on a board and let it set cold and firm, then cut it in slices and fry or grill them until the outside crusts. Slices like these are what a mountain kitchen served under a stew, and they are better than the fresh polenta for it.',
           no:'Bre resten utover en fjøl, og la den stivne kald og fast. Skjær den så i skiver, og stek eller grill dem til utsiden får skorpe. Et fjellkjøkken serverte nettopp slike skiver under en gryte, og de passer bedre til det enn fersk polenta gjør.'}},
    {title:{en:'A darker grain', no:'Et mørkere korn'},
     body:{en:'The mountains grow rye and buckwheat as well as maize, and replacing a fifth of the maize with buckwheat flour gives a grey, nutty polenta that stands up to game. Stir it in with the maize at the start; buckwheat carries no starch worth the name and will not thicken on its own.',
           no:'Fjellene dyrker rug og bokhvete i tillegg til mais, og bytter du ut en femdel av maisen med bokhvetemel, får du en grå og nøtteaktig polenta som tåler viltkjøtt. Rør det inn sammen med maisen fra starten, for bokhvete har ikke stivelse verdt navnet og tykner ikke på egen hånd.'}},
    {title:{en:'With cheese instead', no:'Med ost i stedet'},
     body:{en:'Leave the mushrooms out and melt cubes of a washed-rind mountain cheese into the finished polenta instead — Puzzone di Moena from the Val di Fassa if you can find it, a young Trentingrana if you cannot. Serve it with nothing but pepper.',
           no:'Dropp soppen, og smelt i stedet terninger av en fjellost med vasket skorpe inn i den ferdige polentaen: Puzzone di Moena fra Val di Fassa om du finner den, ung Trentingrana om du ikke gjør det. Server den med bare pepper til.'}},
  ],
},

{
  id:'apfelstrudel', dish:'Apfelstrudel', course:'dolce', lesson:3, serves:6, time:{prep:70, cook:40},
  hero:'strudel', tags:['apple','pastry','dessert'],
  title:{en:'Apfelstrudel', no:'Apfelstrudel'},
  blurb:{en:'A single sheet of dough stretched until you can read through it, rolled round apples, cinnamon, raisins and buttered crumbs.',
         no:'Én leiv deig strukket til du kan lese gjennom den, rullet rundt epler, kanel, rosiner og brødsmuler stekt i smør.'},
  heroCaption:{en:'Apple strudel: the dough stretched thin enough to read through, rolled around apples, raisins and cinnamon.',
               no:'Eplestrudel: deigen strukket tynn nok til å lese gjennom, rullet rundt epler, rosiner og kanel.'},
  wines:[],
  headnote:{
    en:'<p>The floor of the Adige valley is one orchard from Merano to Trento, and Alto Adige alone grows about a tenth of all the apples in Europe. Strudel is the natural end of that. Like Kaiserschmarrn and Krapfen it came over the Brenner from Vienna, and like them it is better here than where it started.</p>'
      + '<p>Strudel dough is not puff pastry and shares nothing with it. No butter is folded in and nothing is laminated: one sheet of lean flour-and-water dough is stretched over the backs of the hands until the pattern of the tablecloth shows through, and the layers of the finished roll are that single sheet wrapped round itself. The stretch comes from gluten, which means strong flour, a long knead, a little oil and a warm rest of about three quarters of an hour. Dough that is cold or under-kneaded tears, and it tears in the middle where you cannot mend it.</p>'
      + '<p>The fried breadcrumbs are not padding. They lie between the pastry and the fruit and drink the juice as it runs, and without them the underside of the roll steams itself soggy. Fry them until they smell toasted, because raw crumbs taste of raw flour.</p>',
    no:'<p>Bunnen av Adige-dalen er én sammenhengende eplehage fra Merano til Trento, og Alto Adige alene dyrker rundt en tidel av alle epler i Europa. Strudelen er den naturlige følgen. Som Kaiserschmarrn og Krapfen kom den over Brenner fra Wien, og som dem er den bedre her enn der den startet.</p>'
      + '<p>Strudeldeig er ikke butterdeig og har ingenting til felles med den. Ikke noe smør brettes inn, og ingenting lamineres. Én leiv av mager deig med mel og vann strekkes over håndbaken til mønsteret i duken synes gjennom, og lagene i den ferdige rullen er den ene leiven rullet rundt seg selv. Strekkbarheten kommer fra gluten, og det betyr sterkt mel, lang elting, litt olje og en varm hvile på tre kvarter. Kald eller dårlig eltet deig revner, og den revner på midten, der du ikke kan reparere den.</p>'
      + '<p>De stekte brødsmulene er ingen fyllmasse. De ligger mellom deigen og frukten og drikker saften etter hvert som den renner, og uten dem damper undersiden av rullen seg bløt. Stek dem til de lukter ristet, for rå smuler smaker rått mel.</p>'},
  ingredients:[
    { group:{en:'Dough', no:'Deig'}, items:[
      {q:220, u:'g', n:{en:'strong white bread flour', no:'sterkt hvetemel'}, note:{en:'high in protein; ordinary plain flour tears before the sheet is thin enough', no:'med høyt proteininnhold, altså brødmel. Vanlig hvetemel revner før leiven er tynn nok'}},
      {q:110, u:'ml', n:{en:'warm water', no:'varmt vann'}},
      {q:25, u:'ml', n:{en:'neutral oil', no:'nøytral olje'}, note:{en:'plus a little more to oil the ball of dough', no:'og litt ekstra til å smøre deigkulen med'}},
      {q:5, u:'ml', n:{en:'white wine vinegar', no:'hvitvinseddik'}, note:{en:'optional; it relaxes the gluten and makes the stretch easier', no:'valgfritt. Den slapper av glutenet og gjør strekkingen lettere'}},
      {q:3, u:'g', n:{en:'salt', no:'salt'}},
    ]},
    { group:{en:'Filling', no:'Fyll'}, items:[
      {q:1000, u:'g', n:{en:'apples', no:'epler'}, note:{en:'firm and tart, so they hold their shape; the valley grows Golden Delicious above all, but it cooks to mush', no:'faste og syrlige, så de holder formen. Aroma eller Discovery gjør nytten. Golden Delicious, som dalen dyrker mest av, koker fort i stykker'}},
      {q:80, u:'g', n:{en:'sugar', no:'sukker'}},
      {q:5, u:'g', n:{en:'ground cinnamon', no:'malt kanel'}},
      {q:60, u:'g', n:{en:'raisins', no:'rosiner'}, note:{en:'steeped in rum or warm apple juice for half an hour, then drained', no:'satt i rom eller varm eplejuice i en halvtime, og deretter avrent'}},
      {q:40, u:'g', n:{en:'pine nuts', no:'pinjekjerner'}},
      {q:1, u:'', n:{en:'lemon', no:'sitron'}, note:{en:'the zest and the juice', no:'skallet og saften'}, round:'half'},
      {q:80, u:'g', n:{en:'dry breadcrumbs', no:'tørre brødsmuler'}},
      {q:60, u:'g', n:{en:'butter for the crumbs', no:'smør til brødsmulene'}},
    ]},
    { group:{en:'To finish', no:'Til servering'}, items:[
      {q:50, u:'g', n:{en:'melted butter', no:'smeltet smør'}, note:{en:'for brushing the sheet and the roll', no:'til pensling av leiven og rullen'}},
      {u:'', n:{en:'icing sugar', no:'melis'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Work the flour, salt, warm water, oil and vinegar into a soft, slightly sticky dough, then knead it for 10 minutes until it is smooth, glossy and springs back when you pull it.',
     no:'Arbeid mel, salt, varmt vann, olje og eddik sammen til en myk og litt klissete deig, og elt den i 10 minutter til den er glatt og blank og fjærer tilbake når du drar i den.'},
    {en:'Shape it into a ball, oil it all over, cover it with a warm upturned bowl and leave it for 45 minutes. Warm dough stretches; cold dough tears.',
     no:'Form den til en kule, smør den inn med olje, sett en varm bolle opp ned over den, og la den hvile i 45 minutter. Varm deig lar seg strekke, kald deig revner.'},
    {en:'Fry the breadcrumbs in butter over medium heat until they are golden and smell toasted, then tip them out to cool.',
     no:'Stek brødsmulene i smør på middels varme til de er gylne og lukter ristet, og hell dem ut på en tallerken så de kjølner.'},
    {en:'Peel, quarter and core the apples, slice them thin, and turn them with the sugar, cinnamon, lemon zest and juice, the drained raisins and the pine nuts.',
     no:'Skrell eplene, del dem i båter, fjern kjernehuset, skjær dem i tynne skiver, og vend dem med sukker, kanel, sitronskall og sitronsaft, de avrente rosinene og pinjekjernene.'},
    {en:'Spread a clean cotton cloth over the whole table and flour it lightly.',
     no:'Legg et rent bomullsklede utover hele bordet, og strø litt mel på det.'},
    {en:'Roll the dough out on the cloth as far as the pin will take it, then slide the backs of your floured hands underneath and stretch it outwards from the middle, moving round the table as you go.',
     no:'Kjevle deigen ut på kledet så langt kjevlen rekker, og strekk den så utover fra midten med håndbaken under leiven mens du flytter deg rundt bordet.'},
    {en:'Keep stretching until the sheet covers the cloth and you can read print through it, then trim away the thick rim.',
     no:'Fortsett å strekke til leiven dekker kledet og du kan lese trykt tekst gjennom den, og skjær så bort den tykke kanten.'},
    {en:'Brush the sheet with melted butter and scatter the cooled crumbs over the third nearest you, leaving a hand’s width clear along the sides.',
     no:'Pensle leiven med smeltet smør, og strø de avkjølte smulene over den tredelen som ligger nærmest deg, med en håndsbredd fri langs sidene.'},
    {en:'Spoon the apples in a line along the near edge, on top of the crumbs, and fold the clear sides in over the ends of the filling.',
     no:'Legg eplene i en stripe langs den nærmeste kanten, oppå smulene, og brett de frie sidene inn over endene av fyllet.'},
    {en:'Lift the far side of the cloth and let it roll the strudel over on itself, keeping it snug, and finish with the seam underneath.',
     no:'Løft den bortre siden av kledet, og la det rulle strudelen over seg selv mens du holder den stram, og avslutt med skjøten ned.'},
    {en:'Roll it straight onto a lined tray, curving it into a horseshoe if it is too long, brush it with butter and bake at 180 °C for 40 minutes, brushing once more halfway, until it is deep golden.',
     no:'Rull den rett over på et bakepapirkledd stekebrett, bøy den til en hestesko hvis den er for lang, pensle den med smør, og stek den ved 180 °C i 40 minutter. Pensle en gang til underveis, og la den bli dypt gyllen.'},
    {en:'Let it settle for 10 minutes, dust it with icing sugar and serve it warm, with vanilla sauce or cream.',
     no:'La den hvile i 10 minutter, sikt melis over, og server den varm med vaniljesaus eller fløte.'},
  ],
  notes:[
    {title:{en:'Why it stretches at all', no:'Hvorfor den lar seg strekke'},
     body:{en:'Strudel dough has almost nothing in it but flour and water, so the gluten network is everything. Kneading lines the proteins up, the oil lets the sheets slide over each other, and the warm rest lets the network relax so it lengthens instead of springing back. Skip the rest and the dough will fight you and win.',
           no:'Strudeldeig inneholder nesten ikke annet enn mel og vann, så glutennettverket er alt. Eltingen retter proteinene inn, oljen lar sjiktene gli over hverandre, og den varme hvilen lar nettverket slappe av, slik at det strekker seg i stedet for å fjære tilbake. Dropper du hvilen, kjemper deigen mot deg og vinner.'}},
    {title:{en:'The crumbs are the waterproofing', no:'Smulene er tettingen'},
     body:{en:'A kilo of apples releases a great deal of juice in a hot oven, and the pastry underneath is a fraction of a millimetre thick. Buttered crumbs absorb that juice and hold the fat that keeps it off the dough, which is why a strudel with crumbs is crisp underneath and one without is grey and wet.',
           no:'Epler gir fra seg svært mye saft i en varm ovn, og deigen under er en brøkdel av en millimeter tykk. Brødsmuler som er stekt i smør, suger opp saften og holder på fettet som holder den unna deigen, og derfor er en strudel med smuler sprø under, mens en uten blir grå og våt.'}},
    {title:{en:'Slice the apples, do not chop them', no:'Skjær eplene i skiver'},
     body:{en:'Thin slices lie flat and let the roll close tightly around them, so the pastry is supported everywhere. Chunks leave air pockets, the sheet has nothing to rest on and the roll collapses along the top when it cools.',
           no:'Tynne skiver ligger flatt og lar rullen lukke seg tett rundt dem, så deigen har støtte overalt. Grove biter etterlater luftlommer, leiven har ikke noe å hvile på, og rullen faller sammen langs toppen når den kjølner.'}},
  ],
  variations:[
    {title:{en:'Is bought filo an honest shortcut?', no:'Er ferdigkjøpt filodeig en ærlig snarvei?'},
     body:{en:'Half honest. Filo is stretched by machine to roughly the same thinness, so it will carry the filling and the crumbs, and three sheets buttered together make a passable roll — bake it 10 minutes shorter. But filo is drier and carries no oil, so it shatters into flakes instead of staying faintly chewy where the juice has reached it, and that chew is half of what a strudel is. Frozen puff pastry is not a shortcut at all: it is a different pastry making a different dessert.',
           no:'Halvveis ærlig. Filodeig er strukket maskinelt til omtrent samme tynnhet, så den bærer både fyll og smuler, og legger du tre leiver oppå hverandre med smør imellom, får du en brukbar rull. Stek den 10 minutter kortere. Men filodeigen er tørrere og inneholder ikke olje, så den smuldrer i flak i stedet for å holde seg så vidt seig der saften har nådd inn, og den seigheten er halve strudelen. Frossen butterdeig er ingen snarvei i det hele tatt, men en annen deig som gir en annen dessert.'}},
    {title:{en:'Nuts and rum', no:'Nøtter og rom'},
     body:{en:'Higher up the valleys the pine nuts give way to chopped walnuts and the raisins are steeped in rum rather than juice. Both make a heavier, more wintry strudel, and both want a sharper apple to balance them.',
           no:'Lenger opp i dalene viker pinjekjernene for hakkede valnøtter, og rosinene settes i rom i stedet for juice. Begge deler gir en tyngre og mer vinterlig strudel, og begge trenger et syrligere eple som motvekt.'}},
    {title:{en:'Which apple', no:'Hvilket eple'},
     body:{en:'The valley grows fifteen varieties or more, Golden Delicious above all, but the apple that is best to eat raw is rarely the best to bake. Mix two: a firm tart one for the shape and a sweeter one for the flavour, and cut the sugar if the fruit is already sweet.',
           no:'Dalen dyrker femten sorter eller flere, Golden Delicious framfor alle, men eplet som er best å spise rått, er sjelden det beste å bake med. Bland to sorter: ett fast og syrlig eple for formens skyld og ett søtere for smakens, og reduser sukkeret hvis frukten allerede er søt.'}},
  ],
},

{
  id:'gerstsuppe', dish:'Gerstsuppe', course:'primo', lesson:3, serves:4, time:{prep:20, cook:85},
  hero:'gerstsuppe', tags:['soup','barley','speck'],
  title:{en:'Gerstsuppe', no:'Gerstsuppe'},
  blurb:{en:'Barley soup with speck and root vegetables, on every menu in the region. The barley thickens it by itself; no flour and no cream.',
         no:'Byggsuppe med speck og rotgrønnsaker, på hver eneste meny i regionen. Byggen jevner den selv, uten mel og uten fløte.'},
  heroCaption:{en:'Gerstsuppe on a hut table. Barley, root vegetables and speck, cooked until the spoon stands up in it.',
               no:'Gerstsuppe på et hyttebord. Bygg, rotgrønnsaker og speck, kokt til skjeen står i den.'},
  wines:['Gewürztraminer'],
  headnote:{
    en:'<p><em>Gerstsuppe</em> — <em>zuppa d’orzo</em> on the Italian side — is on every menu in the region, from the huts at two thousand metres to the farm taverns that open for Törggelen in the autumn, where it starts the meal ahead of the Schlutzkrapfen and the smoked sausage. Barley, root vegetables and speck, and nothing that would have had to be bought.</p>'
      + '<p>Barley is the thickener. Pearl barley sheds starch steadily into the pot, so the soup binds itself with no flour, no cream and no blender. That also means it goes on thickening after it leaves the stove and will be nearly solid by morning; loosen it with water rather than with more broth, or the salt climbs with every reheating.</p>'
      + '<p>The speck seasons the whole pot, so leave the salt until the end and taste first. If you can buy a piece rather than slices, cut the rind off and cook it in the soup — it gives more than the meat does — and fish it out before you serve.</p>',
    no:'<p><em>Gerstsuppe</em>, eller <em>zuppa d’orzo</em> på den italienske siden, står på hver eneste meny i regionen, fra hyttene i to tusen meters høyde til gårdskroene som åpner for Törggelen om høsten. Der innleder den måltidet, før Schlutzkrapfen og de røkte pølsene. I gryten går bygg, rotgrønnsaker og speck, og ingenting som måtte kjøpes inn.</p>'
      + '<p>Byggen er jevningen. Perlebygg gir jevnt og trutt fra seg stivelse til gryten, så suppen binder seg selv uten mel, uten fløte og uten stavmikser. Det betyr også at den fortsetter å tykne etter at den er tatt av platen, og at den er nesten stiv til frokost. Spe den med vann og ikke med mer kraft, ellers stiger saltet for hver oppvarming.</p>'
      + '<p>Specken krydrer hele gryten, så vent med saltet til slutt og smak først. Får du kjøpt et stykke i stedet for skiver, skjærer du av svoren og koker den med i suppen, for den gir mer enn kjøttet gjør. Fisk den opp før du serverer.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:150, u:'g', n:{en:'pearl barley', no:'perlebygg'}, note:{en:'rinsed; the ordinary Norwegian byggryn is the same grain', no:'skylt. Vanlige norske byggryn er det samme kornet'}},
    {q:150, u:'g', n:{en:'Speck Alto Adige', no:'Speck Alto Adige'}, note:{en:'in one piece if you can, diced small, and keep the rind', no:'helst i ett stykke, skåret i små terninger, og ta vare på svoren'}},
    {q:1, u:'', n:{en:'onion', no:'løk'}, note:{en:'finely chopped', no:'finhakket'}, round:'half'},
    {q:20, u:'g', n:{en:'butter', no:'smør'}},
    {q:2, u:'l', n:{en:'water or light beef broth', no:'vann eller lys oksekraft'}, scale:'sub'},
    {q:1, u:'', n:{en:'bay leaf', no:'laurbærblad'}, round:'half'},
    {q:150, u:'g', n:{en:'carrot', no:'gulrot'}, note:{en:'in small dice', no:'i små terninger'}},
    {q:150, u:'g', n:{en:'celeriac', no:'sellerirot'}, note:{en:'in small dice; celery sticks do the same job', no:'i små terninger. Stangselleri gjør samme nytten'}},
    {q:100, u:'g', n:{en:'leek', no:'purre'}, note:{en:'the white and pale green, sliced', no:'det hvite og lysegrønne, i skiver'}},
    {q:250, u:'g', n:{en:'potato', no:'potet'}, note:{en:'a floury variety, in dice', no:'melen sort, i terninger'}},
    {q:10, u:'g', n:{en:'chives or parsley', no:'gressløk eller persille'}, note:{en:'cut fine, added at the table', no:'finklippet, strøs over ved bordet'}},
    {u:'', n:{en:'salt and pepper', no:'salt og pepper'}, scale:'none'},
  ]}],
  steps:[
    {en:'Rinse the barley under cold water until the water runs clear, which takes off the loose starch that would make the soup cloudy from the start.',
     no:'Skyll byggen under kaldt vann til vannet renner klart. Det tar bort den løse stivelsen som ellers ville gjort suppen grumsete fra første stund.'},
    {en:'Cut the rind off the speck, keep it, and dice the meat and its fat small.',
     no:'Skjær svoren av specken, ta vare på den, og skjær kjøttet og fettet i små terninger.'},
    {en:'Melt the butter in a heavy pot and let the speck sweat over low heat until its fat has run and the pieces are barely coloured.',
     no:'Smelt smøret i en tykkbunnet gryte, og la fettet smelte langsomt ut av specken på svak varme, til bitene så vidt har tatt farge.'},
    {en:'Add the onion and let it soften in the fat without browning.',
     no:'Ha i løken, og la den bli myk i fettet uten å ta farge.'},
    {en:'Stir the barley in and let it toast for a minute or two, until the grains are coated and smell nutty.',
     no:'Rør inn byggen, og la den riste et minutt eller to, til kornene er dekket av fett og lukter nøtteaktig.'},
    {en:'Pour in the water or broth, add the bay leaf and the reserved rind, and bring it to the barest simmer.',
     no:'Hell i vannet eller kraften, ha i laurbærbladet og svoren du tok vare på, og la det så vidt småkoke.'},
    {en:'Cook with the lid ajar for 45 minutes, skimming the surface once or twice and stirring the base so nothing catches.',
     no:'La det koke med lokket på gløtt i 45 minutter mens du skummer overflaten en gang eller to og rører i bunnen, så ingenting brenner seg fast.'},
    {en:'Add the carrot, celeriac and leek and cook for 20 minutes more.',
     no:'Ha i gulrot, sellerirot og purre, og la det koke i 20 minutter til.'},
    {en:'Add the potato and cook for a final 20 minutes, until the barley is soft and swollen and the soup has thickened on its own.',
     no:'Ha i poteten, og la det koke 20 minutter til, til byggen er myk og oppsvulmet og suppen har tyknet av seg selv.'},
    {en:'Lift out the rind and the bay leaf, then taste before you reach for the salt; the speck has done most of the seasoning already. Grind pepper over.',
     no:'Fisk opp svoren og laurbærbladet, og smak til før du griper etter saltet, for specken har allerede stått for det meste av krydringen. Kvern pepper over.'},
    {en:'Ladle it out, scatter the chives over each bowl and put rye bread on the table.',
     no:'Øs den opp, strø gressløk over hver skål, og sett rugbrød på bordet.'},
  ],
  notes:[
    {title:{en:'The barley is the roux', no:'Byggen er jevningen'},
     body:{en:'Pearl barley has had its hull and most of its bran polished off, which leaves the starchy endosperm exposed to the water. It leaks starch for the whole cook, and that is what binds the soup. It is also why the soup must be started early and cannot be rushed, and why a spoonful of flour in the pot only makes it pasty.',
           no:'Perlebygg har fått skallet og det meste av kliet polert bort, så den stivelsesrike kjernen ligger åpen mot vannet. Den lekker stivelse hele koketiden, og stivelsen binder suppen. Derfor må suppen settes over i god tid, derfor lar den seg ikke jage fram, og derfor gjør en skje mel i gryten den bare klissete.'}},
    {title:{en:'Vegetables in order of toughness', no:'Grønnsaker etter hvor mye de tåler'},
     body:{en:'Barley takes well over an hour and a diced potato takes twenty minutes, so everything cannot go in together. Root vegetables added at the start turn to threads and give the soup a flat, boiled sweetness; added in two waves they keep their edges and still have something to bite.',
           no:'Byggen trenger godt over en time, og en potet i terninger trenger tjue minutter, så alt kan ikke gå i samtidig. Rotgrønnsaker som går i gryten fra starten, blir til tråder og gir suppen en flat, utkokt sødme. Kommer de i to omganger, beholder de kantene og har fortsatt tyggemotstand.'}},
    {title:{en:'Salt last', no:'Salt til slutt'},
     body:{en:'Speck is cured with salt for weeks before it is smoked, and a soup reduces while it cooks, so both the salt in the pot and the concentration climb. Season only when the pot comes off the heat and only when the barley has taken up all the liquid it is going to.',
           no:'Speck spekes i salt i ukevis før den røykes, og en suppe koker inn mens den står, så den blir saltere jo lenger den står på platen. Smak til først når gryten er av platen, og først når byggen har tatt opp all væsken den kommer til å ta.'}},
  ],
  variations:[
    {title:{en:'Without the speck', no:'Uten speck'},
     body:{en:'A smoked pork hock cooked in the pot and pulled apart at the end gives more body than the diced speck does. For a meatless pot, soak dried porcini and use them and their strained liquid instead; the smoke is gone but the savour is not.',
           no:'En røkt knoke som koker med i gryten og plukkes fra hverandre til slutt, gir mer fylde enn terninger av speck. Vil du ha den uten kjøtt, bløtlegger du tørket steinsopp og bruker soppen og den avsilte væsken i stedet. Røyken forsvinner, men det smaksrike gjør ikke det.'}},
    {title:{en:'At Törggelen', no:'Under Törggelen'},
     body:{en:'On the autumn table the soup opens the meal and the bowls are small, ahead of Schlutzkrapfen, smoked sausage with sauerkraut and roast chestnuts at the end. Thin it a little for that, and leave the potato out so it stays a soup rather than a supper.',
           no:'På høstbordet innleder suppen måltidet i små skåler, før Schlutzkrapfen, røkte pølser med surkål og ristede kastanjer til sist. Spe den litt til det, og dropp poteten, så den forblir en suppe og ikke et kveldsmåltid.'}},
    {title:{en:'A dumpling in the bowl', no:'En melbolle i skålen'},
     body:{en:'A fried Kaspressknödel floated in a thinner version of this soup is a meal in itself and the commonest thing on a hut menu. Keep the soup looser than the recipe leaves it, or the dumpling has nowhere to sit.',
           no:'En stekt Kaspressknödel i en tynnere utgave av denne suppen er et måltid i seg selv og det vanligste på en hyttemeny. Hold suppen løsere enn den blir her, ellers har bollen ingen steder å ligge.'}},
  ],
},

];
