// umbria recipes. Contract: docs/recipe-format.md. Both languages in one file; never narrated.
// Everything here follows the Umbria food reading (content/umbria.js, lesson 3): Norcia's norcini and
// their pork, the black winter truffle that takes heat and is used generously, the thin-skinned lentils
// of the Piano Grande, strangozzi of flour and water with no egg in it, and porchetta with wild fennel.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-55'] = [

{
  id:'strangozzi-al-tartufo-nero', dish:'Strangozzi', course:'primo', lesson:3, serves:4, time:{prep:60, cook:15},
  hero:'strangozzi', tags:['pasta','truffle','hand-made','no-egg'],
  title:{en:'Strangozzi al tartufo nero', no:'Strangozzi al tartufo nero'},
  blurb:{en:'The plainest pasta in Italy — flour, water and a rolling pin — under a great deal of grated black truffle in warm oil.',
         no:'Den enkleste pastaen i Italia er bare mel, vann og kjevle. Over den kommer rikelig med revet svart trøffel i lun olje.'},
  heroCaption:{en:'Strangozzi, cut thick by hand. Here with tomato and oil, the everyday dressing; in winter it is the truffle.',
               no:'Strangozzi, skåret tykt for hånd. Her med tomat og olje, som er hverdagsvarianten. Om vinteren er det trøffelen som gjelder.'},
  wines:['Orvieto Classico','Grechetto'],
  headnote:{
    en:'<p>Strangozzi is the plainest pasta in Italy, and that is meant as a compliment. Flour and water, no egg and no filling, rolled out by hand and cut into thick, slightly uneven strands. In the south of Umbria the same pasta is called <em>strozzapreti</em>, around Perugia and Lake Trasimeno <em>umbricelli</em>; the difference is mostly the name and how thick the strand ends up.</p>'
      + '<p>The dressing that matters here is the <strong>black winter truffle</strong>, <em>Tuber melanosporum</em>, hunted with dogs from November to March on the limestone soils around Norcia and Spoleto. It is a different proposition from the white truffle of Alba. Less overwhelming in scent, but it takes heat, so Umbria cooks it: a great deal of it grated into warm olive oil with a little garlic and an anchovy, and turned through the pasta.</p>'
      + '<p>Two things are not negotiable. The oil must stay warm and never hot, because above roughly 60 °C the aroma leaves the pan instead of dissolving into the fat. And there is no cheese on this plate. Pecorino would bury the whole thing.</p>',
    no:'<p>Strangozzi er den enkleste pastaen i Italia, og det er ment som ros. Deigen er mel og vann, uten egg og uten fyll, og den kjevles ut for hånd og skjæres i tykke, litt ujevne tråder. Sør i Umbria kalles den samme pastaen <em>strozzapreti</em>, rundt Perugia og Trasimenosjøen <em>umbricelli</em>, og forskjellen ligger mest i navnet og i hvor tykk tråden blir.</p>'
      + '<p>Om vinteren dresses den med <strong>svart vintertrøffel</strong>, <em>Tuber melanosporum</em>, som jaktes med hund fra november til mars i kalkrik jord rundt Norcia og Spoleto. Den er noe annet enn den hvite trøffelen fra Alba. Duften er mindre overveldende, men den tåler varme, og derfor blir den varmebehandlet i Umbria. Rikelig av den rives ned i lun olivenolje med litt hvitløk og en ansjos, og vendes gjennom pastaen.</p>'
      + '<p>To ting er ikke til forhandling. Oljen skal være lun og aldri varm, for over rundt 60 °C forsvinner duften ut av pannen i stedet for å løse seg i fettet. Og det skal ikke ost på denne tallerkenen. Pecorino ville begravd hele retten.</p>'},
  ingredients:[
    { group:{en:'The pasta', no:'Pastaen'}, items:[
      {q:400, u:'g', n:{en:'durum wheat semolina', no:'durumsemule'}, note:{en:'semola rimacinata; plain wheat flour works and gives a softer strand', no:'semola rimacinata; vanlig hvetemel går også og gir en mykere tråd'}},
      {q:200, u:'ml', n:{en:'water', no:'vann'}, note:{en:'lukewarm', no:'lunkent'}},
      {q:5, u:'g', n:{en:'salt for the dough', no:'salt i deigen'}},
    ]},
    { group:{en:'The truffle sauce', no:'Trøffelsausen'}, items:[
      {q:60, u:'g', n:{en:'black winter truffle', no:'svart vintertrøffel'}, note:{en:'Tuber melanosporum, firm and dry to the touch', no:'Tuber melanosporum, fast og tørr å ta på'}},
      {q:100, u:'ml', n:{en:'extra virgin olive oil', no:'ekstra virgin olivenolje'}},
      {q:2, u:'', n:{en:'garlic cloves', no:'hvitløksfedd'}, round:'half'},
      {q:4, u:'', n:{en:'anchovy fillets', no:'ansjosfileter'}, note:{en:'salted or in oil, drained', no:'saltet eller i olje, avrent'}, round:'half'},
      {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
      {q:3, u:'l', n:{en:'water', no:'vann'}, scale:'sub'},
      {q:30, u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub'},
    ]},
  ],
  steps:[
    {en:'Heap the semolina on a board, make a well in the middle and pour in the lukewarm salted water a little at a time, drawing the flour in with a fork.',
     no:'Ha semulen i en haug på benken, lag en brønn i midten, og hell i det lunkne, saltede vannet litt om gangen mens du drar melet inn med en gaffel.'},
    {en:'Knead for ten minutes, until the dough is firm, smooth and springs back when you press it. It should feel tighter than a bread dough.',
     no:'Kna i ti minutter, til deigen er fast, glatt og spretter tilbake når du trykker på den. Den skal kjennes strammere enn en brøddeig.'},
    {en:'Wrap the dough and let it rest for half an hour. Resting is what lets it roll out without pulling back.',
     no:'Pakk deigen inn, og la den hvile en halvtime. Hvilen er grunnen til at den lar seg kjevle uten å trekke seg tilbake.'},
    {en:'Roll it out to a sheet about 3 mm thick, thicker than you would for tagliatelle.',
     no:'Kjevle den ut til en plate på rundt 3 mm, tykkere enn du ville gjort til tagliatelle.'},
    {en:'Dust the sheet well, roll it up loosely and cut strands about 3 mm wide. Shake them apart and leave them on a floured cloth.',
     no:'Strø godt med mel over platen, rull den løst sammen, og skjær tråder på rundt 3 mm. Rist dem fra hverandre, og legg dem på et melet klede.'},
    {en:'Brush the truffle clean with a dry, stiff brush. Never rinse it under the tap; it drinks water and loses aroma.',
     no:'Børst trøffelen ren med en tørr, stiv børste. Skyll den aldri under springen, for den suger til seg vann og mister duft.'},
    {en:'Grate two thirds of it on the finest side of the grater and cut the rest into thin slices for the top.',
     no:'Riv to tredjedeler av den på den fineste siden av rivjernet, og skjær resten i tynne skiver til toppen.'},
    {en:'Warm the oil gently with the crushed garlic until the kitchen smells of it, and take the garlic out before it colours.',
     no:'Varm oljen forsiktig med den knuste hvitløken til hele kjøkkenet dufter, og ta ut hvitløken før den får farge.'},
    {en:'Mash the anchovy fillets into the warm oil with a fork until they dissolve completely.',
     no:'Rør ansjosfiletene ut i den lune oljen med en gaffel til de går helt i oppløsning.'},
    {en:'Take the pan off the heat, stir the grated truffle into the oil and let it stand for five minutes while the pasta cooks.',
     no:'Ta pannen av platen, rør den revne trøffelen inn i oljen, og la den stå og trekke i fem minutter mens pastaen koker.'},
    {en:'Boil the strands in plenty of salted water for three to four minutes, until they float and still have some chew, and keep a ladle of the water.',
     no:'Kok trådene i rikelig saltet vann i tre til fire minutter, til de flyter opp og fortsatt har tyggemotstand, og ta vare på en øse med kokevannet.'},
    {en:'Toss the pasta through the truffle oil with a splash of the cooking water until it turns glossy, lay the sliced truffle over and serve without cheese.',
     no:'Vend pastaen i trøffeloljen med en skvett kokevann til den blir blank, legg trøffelskivene over, og server uten ost.'},
  ],
  notes:[
    {title:{en:'The black truffle takes heat', no:'Den svarte trøffelen tåler varme'},
     body:{en:'Tuber melanosporum gives its aroma up to fat and survives gentle warmth, which is why Umbria cooks it rather than only shaving it. The white truffle of Alba is the opposite: its scent is gone above blood heat, and it is shaved raw over something hot at the table. Warm oil here, and the pan never allowed to get properly hot.',
           no:'Tuber melanosporum gir fra seg duften til fett og tåler mild varme, og derfor blir den varmebehandlet i Umbria i stedet for bare høvlet. Den hvite trøffelen fra Alba er det motsatte. Duften er borte så snart den kommer over kroppstemperatur, og den høvles rå over noe varmt ved bordet. Her skal oljen være lun, og pannen skal aldri bli ordentlig varm.'}},
    {title:{en:'The anchovy is not there to taste of fish', no:'Ansjosen skal ikke smake fisk'},
     body:{en:'It dissolves completely and leaves salt and glutamate behind, which lengthen the truffle instead of competing with it. Leave it out and the sauce tastes thin, and you end up adding salt to say the same thing less well.',
           no:'Den løser seg helt opp og etterlater salt og glutamat, som forlenger trøffelen i stedet for å konkurrere med den. Utelater du den, blir sausen tynn i smaken, og du ender med å salte mer for å oppnå det samme, bare dårligere.'}},
    {title:{en:'Flour and water, and no grater on the table', no:'Mel og vann, og ikke noe rivjern på bordet'},
     body:{en:'Semolina and water give a strand with real chew that carries a thin oil dressing. Egg pasta is softer and richer and pulls attention towards itself, and pecorino would cover the truffle outright. An Umbrian plate of strangozzi al tartufo arrives without cheese and nobody asks for any.',
           no:'Semule og vann gir en tråd med ordentlig tyggemotstand som bærer en tynn oljedressing. Eggpasta er mykere og fetere og trekker oppmerksomheten mot seg selv, og pecorino ville dekket trøffelen helt. En umbrisk tallerken strangozzi al tartufo kommer inn uten ost, og ingen ber om noen.'}},
  ],
  variations:[
    {title:{en:'Umbricelli and strozzapreti', no:'Umbricelli og strozzapreti'},
     body:{en:'The same dough under other names. Umbricelli, around Perugia and the lake, are rolled thicker and rounder under the palm, like a short fat spaghetti; strozzapreti, in the south of the region, are cut shorter. Neither changes the sauce.',
           no:'Samme deig under andre navn. Umbricelli, rundt Perugia og sjøen, rulles tykkere og rundere under håndflaten, som en kort og fyldig spaghetti, mens strozzapreti sør i regionen skjæres kortere. Ingen av dem endrer sausen.'}},
    {title:{en:'From a packet', no:'Fra pose'},
     body:{en:'Dried strangozzi are sold all over Umbria and are perfectly respectable; cook them as the packet says, which is far longer than the fresh ones need. The sauce is unchanged, and the cooking water is starchier, which helps it cling.',
           no:'Tørkede strangozzi selges over hele Umbria og er fullt ut brukbare. Kok dem så lenge posen sier, og det er langt lenger enn de ferske trenger. Sausen er den samme, og kokevannet blir mer stivelsesrikt, noe som hjelper den å henge seg fast.'}},
    {title:{en:'Tomato and oil', no:'Tomat og olje'},
     body:{en:'The everyday dressing, and what the photograph above shows: garlic warmed in oil, peeled tomatoes cooked down for twenty minutes, and a hard grating of pecorino, which is welcome here because there is no truffle to protect.',
           no:'Dette er hverdagsvarianten, og den ser du på bildet over. Hvitløk varmes i olje, flådde tomater kokes inn i tjue minutter, og så rives det rikelig med pecorino over. Osten er velkommen her, for det er ingen trøffel å beskytte.'}},
  ],
},

{
  id:'lenticchie-di-castelluccio', dish:'Lentils of Castelluccio', course:'secondo', lesson:3, serves:4, time:{prep:15, cook:50},
  hero:'lentils', tags:['lentils','sausage','one-pot','mountain'],
  title:{en:'Lenticchie di Castelluccio con la salsiccia', no:'Lenticchie di Castelluccio con la salsiccia'},
  blurb:{en:'Italy’s most prized lentils, grown at 1,400 metres and cooked straight from the bag, with plain pork sausages sunk into them.',
         no:'Italias mest ettertraktede linser vokser på 1 400 meter og går rett i gryta, med enkle svinepølser nedi.'},
  heroCaption:{en:'Castelluccio lentils: small, thin-skinned, and cooked without soaking.',
               no:'Linser fra Castelluccio. De er små, tynnskallede, og de kokes uten bløtlegging.'},
  wines:['Montefalco Rosso'],
  headnote:{
    en:'<p>An hour above Norcia the road climbs to <strong>Castelluccio</strong>, a village on a ridge over the Piano Grande, a flat upland basin at about 1,400 metres ringed by bare mountains. The plain grows the most famous lentils in Italy. <strong>Lenticchia di Castelluccio di Norcia IGP</strong> are tiny and thin-skinned, they hold their shape, and they go into the pot straight from the bag.</p>'
      + '<p>The thin skin is the whole point. It lets water in immediately, so the lentils are done in half an hour, and it means soaking is not only unnecessary but harmful — waterlogged lentils split and go to mush. Umbrians eat them with sausage, with pasta, or with <em>cotechino</em> on New Year’s Eve, when they are compulsory and, by tradition, the small round seeds are supposed to stand for coins in the year ahead.</p>'
      + '<p>Nothing else here is complicated. A soffritto, a plain pork sausage for its fat, water rather than stock, and the tomato and the salt held back until the lentils are already tender, because acid and salt both toughen the skins if they arrive early.</p>',
    no:'<p>En time over Norcia klatrer veien opp til <strong>Castelluccio</strong>, en landsby på en rygg over Piano Grande, en flat høyslette på rundt 1 400 meter omkranset av nakne fjell. Sletten gir de mest kjente linsene i Italia. <strong>Lenticchia di Castelluccio di Norcia IGP</strong> er bittesmå og tynnskallede, de holder formen, og de går rett fra posen og ned i gryta.</p>'
      + '<p>Det tynne skallet er hele poenget. Det slipper vannet inn med en gang, så linsene er ferdige på en halvtime, og bløtlegging blir ikke bare unødvendig, men skadelig. Gjennomvåte linser sprekker og går i oppløsning. Umbrere spiser dem med pølse, med pasta, eller med <em>cotechino</em> på nyttårsaften, da de er obligatoriske, og etter tradisjonen skal de små, runde frøene bety mynter i året som kommer.</p>'
      + '<p>Resten er ukomplisert. Du trenger en soffritto, en enkel svinepølse for fettets skyld og vann framfor kraft. Tomaten og saltet holdes tilbake til linsene allerede er møre, for både syre og salt gjør skallet seigt hvis de kommer for tidlig.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:300, u:'g', n:{en:'Castelluccio lentils', no:'linser fra Castelluccio'}, note:{en:'do not soak; tip them onto a tray first and pick out any grit', no:'skal ikke bløtlegges; hell dem først ut på et brett, og plukk ut småstein'}},
    {q:400, u:'g', n:{en:'fresh pork sausages', no:'ferske svinepølser'}, note:{en:'coarse plain pork, salt and pepper only — in Norway ask for an unsmoked, unspiced grillpølse of pure pork, never a smoked or a potato-flour one', no:'grovmalt rent svinekjøtt med bare salt og pepper; i Norge må du be om en urøkt grillpølse av rent svinekjøtt, aldri en røkt eller en med potetmel'}},
    {q:1, u:'', n:{en:'onion', no:'løk'}, round:'half'},
    {q:1, u:'', n:{en:'carrot', no:'gulrot'}, round:'half'},
    {q:1, u:'', n:{en:'stick of celery', no:'stilk selleri'}, round:'half'},
    {q:2, u:'', n:{en:'garlic cloves', no:'hvitløksfedd'}, round:'half'},
    {q:40, u:'ml', n:{en:'extra virgin olive oil', no:'ekstra virgin olivenolje'}},
    {q:200, u:'g', n:{en:'tomato passata', no:'tomatpuré, passata'}, note:{en:'sieved tomatoes, not concentrate', no:'silte tomater, ikke konsentrat'}},
    {q:1, u:'', n:{en:'bay leaf', no:'laurbærblad'}, round:'half'},
    {q:4, u:'', n:{en:'sage leaves', no:'salvieblader'}, round:'half'},
    {q:900, u:'ml', n:{en:'water', no:'vann'}, note:{en:'hot, kept beside the pan for topping up', no:'varmt, og sett ved siden av gryta til å spe med'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
    {u:'', n:{en:'olive oil to finish', no:'olivenolje til slutt'}, scale:'none'},
  ]}],
  steps:[
    {en:'Tip the lentils onto a tray, pick out any small stones, then rinse and drain them. Do not soak them.',
     no:'Hell linsene ut på et brett, plukk ut småstein, skyll dem, og la dem renne av. De skal ikke bløtlegges.'},
    {en:'Chop the onion, carrot and celery finely and keep them together.',
     no:'Finhakk løk, gulrot og selleri, og hold dem samlet.'},
    {en:'Warm the oil in a wide, heavy pan and sweat the vegetables with the bay leaf over low heat for ten minutes, until soft but not coloured.',
     no:'Varm oljen i en vid, tung gryte, og la grønnsakene svette med laurbærbladet på svak varme i ti minutter, til de er myke uten å ta farge.'},
    {en:'Push them to one side, lay the sausages in whole and colour them all over, turning them with tongs rather than pricking them.',
     no:'Skyv dem til side, legg pølsene hele oppi, og brun dem på alle sider mens du snur dem med en klype i stedet for å stikke hull på dem.'},
    {en:'Add the crushed garlic and let it warm through for a minute.',
     no:'Ha i den knuste hvitløken, og la den varmes gjennom i et minutt.'},
    {en:'Stir in the lentils and turn them in the fat for a minute so every one is coated.',
     no:'Rør inn linsene, og vend dem i fettet i et minutt så alle blir dekket.'},
    {en:'Pour in enough hot water to cover everything by two fingers and bring it to a bare simmer, not a rolling boil.',
     no:'Hell over så mye varmt vann at alt er dekket med to fingerbredder, og la det så vidt småkoke. Det skal ikke fosskoke.'},
    {en:'Simmer uncovered for twenty minutes, topping up with hot water whenever the lentils rise above the surface.',
     no:'La det småkoke uten lokk i tjue minutter, og spe med varmt vann hver gang linsene stikker opp over overflaten.'},
    {en:'Stir in the passata and the sage and cook for another ten to fifteen minutes, until the lentils are tender but still whole.',
     no:'Rør inn passataen og salvien, og la det koke videre i ti til femten minutter, til linsene er møre, men fortsatt hele.'},
    {en:'Salt now, off the heat, taste, and let the pot stand for ten minutes so the lentils drink the last of the liquid.',
     no:'Salt først nå, med gryta av platen, smak til, og la gryta stå i ti minutter så linsene drikker opp resten av væsken.'},
    {en:'Slice the sausages thickly, lay them back on top, grind over pepper and pour a thin stream of raw olive oil across the pot before it goes to the table.',
     no:'Skjær pølsene i tykke skiver, legg dem tilbake på toppen, kvern over pepper, og hell en tynn stråle rå olivenolje over gryta før den settes på bordet.'},
  ],
  notes:[
    {title:{en:'Why they are never soaked', no:'Derfor bløtlegges de aldri'},
     body:{en:'Big lentils and dried beans are soaked because water has to get through a thick skin before the starch inside will soften. Castelluccio lentils are grown short and small at altitude and their skins are thin enough that water is already inside within minutes. A soak only waterlogs them, and they burst in the pot instead of holding their shape.',
           no:'Store linser og tørre bønner bløtlegges fordi vannet må gjennom et tykt skall før stivelsen inni blir myk. Linsene fra Castelluccio vokser seg små i høyden, og skallet er så tynt at vannet er inne i løpet av minutter. Bløtlegging gjør dem bare gjennomvåte, og de sprekker i gryta i stedet for å holde formen.'}},
    {title:{en:'Salt and tomato at the end', no:'Salt og tomat til slutt'},
     body:{en:'Acid sets the pectin in a lentil skin, and salt in the cooking water pulls water out of the seed before it has swollen. Both make the skins tough and the cooking time unpredictable. Once the lentils are already soft neither can do any harm, which is why the passata goes in late and the salt later still.',
           no:'Syre får pektinet i linseskallet til å stivne, og salt i kokevannet trekker vann ut av frøet før det har svellet. Begge deler gjør skallet seigt og koketiden uforutsigbar. Når linsene først er myke, kan ingen av delene gjøre skade, og derfor kommer passataen sent og saltet enda senere.'}},
    {title:{en:'The sausage is the stock', no:'Pølsa er kraften'},
     body:{en:'There is no stock cube in this and there should not be. The fat that leaves the sausages carries the seasoning through the whole pot, and the soffritto supplies the sweetness, so water is the right liquid. A meat stock on top of both makes it heavy and tastes of the shop.',
           no:'Det er ingen buljongterning i dette, og det skal det ikke være. Fettet som går ut av pølsene, bærer smaken gjennom hele gryta, og grønnsakene i bunnen gir sødmen, så vann er riktig væske. Kjøttkraft i tillegg gjør retten tung og gir den butikksmak.'}},
  ],
  variations:[
    {title:{en:'With strangozzi, as a soup', no:'Med strangozzi, som suppe'},
     body:{en:'Add half again as much water, leave the sausage out or crumble it, and drop broken strangozzi into the pot for the last few minutes so they cook in the lentils. This is the lentil-and-pasta dish the reading shows, and it is what the mountains eat in February.',
           no:'Ha i halvparten mer vann, utelat pølsa eller smuldre den opp, og legg strangozzi brukket i biter i gryta de siste minuttene så de koker i linsene. Dette er linse- og pastaretten som vises i lesestykket, og oppe i fjellene spiser de den i februar.'}},
    {title:{en:'New Year’s Eve, with cotechino', no:'Nyttårsaften, med cotechino'},
     body:{en:'Swap the sausages for a cotechino, the big soft boiling sausage, simmered separately in its own water for the time the packet gives and sliced over the lentils at the table. Cook the lentils plainer for this: no tomato, more sage.',
           no:'Bytt ut pølsene med en cotechino, den store, myke kokepølsa, som kokes for seg i sitt eget vann så lenge pakken sier, og skjæres opp over linsene ved bordet. Kok linsene enklere til dette, uten tomat og med mer salvie.'}},
    {title:{en:'Without meat', no:'Uten kjøtt'},
     body:{en:'Leave the sausages out, double the oil in the soffritto and finish with a great deal more raw oil and a rubbed clove of garlic on toasted unsalted bread. Umbria eats it this way in Lent and does not think of it as a lesser dish.',
           no:'Sløyf pølsene, doble oljen i grønnsaksbunnen, og avslutt med mye mer rå olje og et gnidd hvitløksfedd på ristet, usaltet brød. I Umbria spises den slik i fasten, og den regnes ikke som en dårligere rett.'}},
  ],
},

{
  id:'torta-al-testo', dish:'Torta al testo', course:'antipasto', lesson:3, serves:4, time:{prep:45, cook:20},
  hero:'testo', tags:['bread','griddle','flatbread','no-oven'],
  title:{en:'Torta al testo', no:'Torta al testo'},
  blurb:{en:'Umbria’s everyday bread: a thick flat round cooked dry on hot iron, split while warm and filled with ham, cheese or greens.',
         no:'Umbrias hverdagsbrød. En tykk, flat deigplate stekes tørt på varmt jern, deles mens den er varm og fylles med skinke, ost eller grønne blader i olje og hvitløk.'},
  heroCaption:{en:'Torta al testo split while warm and filled with prosciutto, cheese and tomato.',
               no:'Her er torta al testo delt mens den er varm og fylt med prosciutto, ost og tomat.'},
  wines:['Grechetto'],
  headnote:{
    en:'<p>The food reading for Umbria covers the truffle, the ham and the lentils. The bread a family in Perugia actually eats most days is this one. A <em>testo</em> is a heavy disc — soapstone, terracotta or, now, cast iron — heated in the hearth until it is too hot to touch, and the <em>torta</em> is a thick flat round of dough cooked dry on it, turned once, then split through the middle with a knife and filled.</p>'
      + '<p>It belongs to the same family as Gubbio’s <em>crescia</em> and the flatbreads of the Marche over the mountains, and every valley claims a slightly different one. The fillings are whatever the region already has: <em>prosciutto</em> and a young sheep’s cheese, sausage from the grill, or <em>erbe di campo</em> — wild greens, boiled and then turned through oil and garlic.</p>'
      + '<p>Two things decide it. The heat comes only from the metal, with no fat between, so the surface dries and browns in patches instead of frying; and the round must be thick enough — about a centimetre — to have a crumb worth splitting. Roll it thin and you have made a cracker.</p>',
    no:'<p>Lesestykket om maten i Umbria handler om trøffelen, skinken og linsene. Til daglig spiser en familie i Perugia likevel dette brødet. En <em>testo</em> er en tung skive av kleberstein, terrakotta eller, i dag, støpejern, som varmes i peisen til den ikke lar seg ta på, og <em>tortaen</em> er en tykk, flat deigplate som stekes tørt på den, snus én gang, og så deles i to lag med kniv og fylles.</p>'
      + '<p>Den hører til samme familie som <em>crescia</em> fra Gubbio og flatbrødene i Marche på andre siden av fjellet, og hver dal hevder å ha sin egen variant. Fyllet er det traktene allerede har: <em>prosciutto</em> og en ung saueost, grillet pølse, eller <em>erbe di campo</em>, altså viltvoksende blader som kokes og deretter vendes i olje og hvitløk.</p>'
      + '<p>To ting avgjør resultatet. Varmen kommer bare fra metallet, uten fett imellom, så overflaten tørker og blir flekkvis brun i stedet for å bli stekt. Og platen må være tykk nok, rundt en centimeter, til å ha en krumme det er verdt å dele. Kjevler du den tynn, har du laget en kjeks.</p>'},
  ingredients:[
    { group:{en:'The dough', no:'Deigen'}, items:[
      {q:500, u:'g', n:{en:'plain wheat flour', no:'hvetemel'}, note:{en:'Italian tipo 0; ordinary Norwegian hvetemel behaves the same', no:'italiensk tipo 0; vanlig norsk hvetemel oppfører seg likt'}},
      {q:260, u:'ml', n:{en:'water', no:'vann'}, note:{en:'lukewarm', no:'lunkent'}},
      {q:10, u:'g', n:{en:'salt', no:'salt'}},
      {q:10, u:'g', n:{en:'baking powder', no:'bakepulver'}, note:{en:'or fresh yeast and an hour’s rise; see the variations', no:'eller fersk gjær og en time med heving; se variantene'}},
      {q:25, u:'ml', n:{en:'extra virgin olive oil', no:'ekstra virgin olivenolje'}},
    ]},
    { group:{en:'To fill', no:'Til fyllet'}, items:[
      {q:150, u:'g', n:{en:'prosciutto crudo', no:'prosciutto crudo'}, note:{en:'Prosciutto di Norcia if you can find it; any dry-cured ham otherwise', no:'Prosciutto di Norcia om du finner den, ellers en hvilken som helst spekeskinke'}},
      {q:150, u:'g', n:{en:'young pecorino or caciotta', no:'ung pecorino eller caciotta'}, note:{en:'sliceable, not hard and grating-dry', no:'til å skjære i skiver, ikke hard og tørr som rivost'}},
      {q:400, u:'g', n:{en:'chard or spinach', no:'mangold eller spinat'}, note:{en:'stalks and all, in place of the Umbrian wild greens', no:'stilker og det hele, i stedet for de umbriske markbladene'}},
      {q:2, u:'', n:{en:'garlic cloves', no:'hvitløksfedd'}, round:'half'},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Mix the flour, the salt and the baking powder together dry, so the raising agent is spread evenly before any water reaches it.',
     no:'Bland mel, salt og bakepulver tørt, så hevemiddelet er jevnt fordelt før det møter vann.'},
    {en:'Pour in the lukewarm water and the oil and bring it together into a soft dough with your hand.',
     no:'Hell i det lunkne vannet og oljen, og samle det til en myk deig med hånden.'},
    {en:'Knead on a floured board for five minutes, until it is smooth and just short of sticky. It should stay softer than a bread dough.',
     no:'Kna deigen på en melet benk i fem minutter, til den er glatt og så vidt ikke klissete. Den skal være mykere enn en brøddeig.'},
    {en:'Cover the bowl and let the dough rest for half an hour, so it will roll out without springing back.',
     no:'Dekk bollen, og la deigen hvile en halvtime, så den lar seg kjevle uten å trekke seg tilbake.'},
    {en:'Boil the greens for a few minutes, drain them hard, then turn them through warm oil with the crushed garlic and salt.',
     no:'Kok bladene i noen minutter, klem dem godt tørre, og vend dem så i lun olje med den knuste hvitløken og salt.'},
    {en:'Heat a heavy cast-iron pan or flat griddle over medium heat, dry and with no fat at all, until a drop of water skitters across it.',
     no:'Varm en tung støpejernspanne eller en takke på middels varme. Den skal være helt tørr, uten fett av noe slag, og klar når en vanndråpe danser over den.'},
    {en:'Divide the dough in two and roll each half into a round the size of the pan, about a centimetre thick.',
     no:'Del deigen i to, og kjevle hver halvdel til en rund plate på størrelse med pannen, rundt en centimeter tykk.'},
    {en:'Prick the round all over with a fork so it cannot dome up and lift off the metal.',
     no:'Stikk hull i hele platen med en gaffel, så den ikke buler opp og slipper metallet.'},
    {en:'Lay it on the hot dry surface and cook it for seven minutes, until the underside is patched brown and the round lifts freely.',
     no:'Legg den på den varme, tørre flaten, og stek i sju minutter, til undersiden er flekkvis brun og platen slipper lett.'},
    {en:'Turn it and cook the other side for the same time, pressing the edges down now and then with a folded cloth so they colour too.',
     no:'Snu den, og stek den andre siden like lenge mens du innimellom presser kantene ned med et brettet klede, så de også får farge.'},
    {en:'Wrap each round in a cloth for five minutes while the next one cooks, then split it through the middle with a serrated knife and fill it while it is still warm.',
     no:'Pakk hver plate inn i et klede i fem minutter mens den neste steker, del den så i to lag med brødkniv, og fyll den mens den fortsatt er varm.'},
  ],
  notes:[
    {title:{en:'Dry metal, no fat', no:'Tørt metall, uten fett'},
     body:{en:'The testo cooks by contact. Oil between the dough and the iron would fry the surface, seal it and trap the steam inside, and the round would stay pale and damp. On dry metal the moisture leaves slowly through the top while the base browns in patches, which is the look and the texture you are after.',
           no:'En testo steker ved kontakt. Olje mellom deigen og jernet ville stekt overflaten, forseglet den og stengt dampen inne, og platen ville blitt blek og klam. På tørt metall slipper fuktigheten sakte ut gjennom toppen mens undersiden blir flekkvis brun, og det er både utseendet og konsistensen du er ute etter.'}},
    {title:{en:'Thickness is the recipe', no:'Tykkelsen er hele oppskriften'},
     body:{en:'A centimetre of dough gives about seven minutes a side: long enough for the outside to set into a crust and short enough that the middle stays bready and can be split. Thinner and it dries all the way through into a cracker; much thicker and the crust is dark before the centre is cooked.',
           no:'En centimeter deig gir rundt sju minutter på hver side, som er lenge nok til at utsiden setter seg til skorpe, og kort nok til at midten forblir brødaktig og lar seg dele. Kjevler du den tynnere, tørker den helt gjennom til en kjeks. Gjør du den mye tykkere, blir skorpen mørk før midten er gjennomstekt.'}},
    {title:{en:'The cloth is not sentimental', no:'Kledet er ikke bare gammel vane'},
     body:{en:'Wrapping the hot round traps the steam still leaving it and lets that moisture soften the crust from the inside. A torta left bare on a rack sets hard and tears when the knife goes in, instead of opening cleanly into two halves.',
           no:'Når du pakker inn den varme platen, holder du igjen dampen som fortsatt går ut av den, og fuktigheten myker opp skorpen innenfra. En torta som blir liggende udekket på rist, stivner hardt og revner når kniven går inn, i stedet for å åpne seg pent i to.'}},
  ],
  variations:[
    {title:{en:'Crescia di Gubbio', no:'Crescia di Gubbio'},
     body:{en:'Gubbio’s version is richer: eggs and a good deal of ground pepper go into the dough, and the fat is lard rather than oil. It comes off the iron softer and yellower, and it is filled the same way.',
           no:'Varianten fra Gubbio er fetere. Egg og rikelig med malt pepper går i deigen, og fettet er smult i stedet for olje. Den kommer mykere og gulere av jernet, og den fylles på samme måte.'}},
    {title:{en:'Yeast instead of baking powder', no:'Gjær i stedet for bakepulver'},
     body:{en:'Dissolve fresh yeast in the lukewarm water, leave the kneaded dough to rise for an hour and roll it out then. The crumb is looser and tastes of bread rather than of soda, and the round puffs more on the iron. It is the older method and the slower one.',
           no:'Løs opp fersk gjær i det lunkne vannet, la den ferdigknadde deigen heve i en time, og kjevle den ut da. Krummen blir løsere og smaker brød i stedet for bakepulver, og platen buler mer opp på jernet. Dette er den eldre metoden, og den tar lengre tid.'}},
    {title:{en:'What goes inside', no:'Hva som går inni'},
     body:{en:'Prosciutto with a slice of young cheese is the standard; grilled sausage split lengthways is the version sold at fairs; and the greens above, oily and garlicky and slightly bitter, are the one Umbrians will tell you is the real thing. Nothing is spread on the bread and there is no sauce.',
           no:'Prosciutto med en skive ung ost er standarden, og grillet pølse delt på langs er varianten som selges på markeder. Men bladene i olje og hvitløk, litt bitre i smaken, er den varianten umbrere selv kaller den ekte. Ingenting smøres på brødet, og det følger ingen saus med.'}},
  ],
},

{
  id:'porchetta', dish:'Porchetta', course:'secondo', lesson:3, serves:8, time:{prep:40, cook:200},
  hero:'porchetta', tags:['pork','roast','fennel','oven','crackling'],
  title:{en:'Porchetta, the home version', no:'Porchetta, hjemmeversjonen'},
  blurb:{en:'A whole boned pig is what a porchetta van sells. This is the same seasoning and the same geometry on a belly rolled round a loin.',
         no:'En hel utbeinet gris er det porchetta-bilene selger. Dette er samme krydring og samme oppbygning på et sideflesk som er rullet rundt en kam.'},
  heroCaption:{en:'A home porchetta: the belly rolled round the loin, tied, and roasted until the rind blisters.',
               no:'Porchetta laget hjemme. Sideflesket er rullet rundt kammen, bundet opp og stekt til svoren har boblet seg opp.'},
  wines:['Montefalco Rosso'],
  headnote:{
    en:'<p>Porchetta proper is a whole pig, boned, packed with wild fennel, garlic and pepper and roasted on a spit until the rind is one sheet of crackling. It is an Umbrian invention as much as a Roman one, and the wild fennel is the tell: the Roman version leans on rosemary. No domestic oven will take an animal, so what follows is the version a household actually cooks — a pork belly rolled tightly round a loin, which reproduces the geometry that matters, fat outside and lean in the middle, in a piece that fits a roasting tray.</p>'
      + '<p>The geometry is the point. The loin on its own would dry out long before the skin crisped; wrapped in belly it cooks inside a jacket of fat that bastes it for three hours. Meanwhile the belly’s collagen melts, and the roll slices without falling apart because the string held the section round while it set.</p>'
      + '<p>Two temperatures do two different jobs, and they cannot be combined. Hours at 150 °C render the fat and soften the connective tissue. Then a short blast at 240 °C puffs the rind — but only if the rind is dry, which is why it goes uncovered into the fridge the night before and is salted at the last minute.</p>',
    no:'<p>Ekte porchetta er en hel gris som er beinet ut, pakket med viltvoksende fennikel, hvitløk og pepper, og stekt på spidd til svoren er én sammenhengende plate. Den er like mye en umbrisk oppfinnelse som en romersk, og fennikelen er kjennetegnet, for den romerske varianten lener seg på rosmarin. Ingen vanlig stekeovn tar et helt dyr, så her får du varianten en husholdning faktisk lager. Et sideflesk rulles stramt rundt en kam, og da gjenskaper du oppbygningen som betyr noe, med fett utenpå og magert kjøtt i midten, i et stykke som får plass i en langpanne.</p>'
      + '<p>Oppbygningen er hele poenget. Kammen alene ville tørket ut lenge før svoren ble sprø, men når den er pakket inn i sideflesk, steker den inne i en fettkappe som øser over den i tre timer. Samtidig smelter bindevevet i sideflesket, og rullen lar seg skjære uten å falle fra hverandre, fordi hyssingen holdt snittet rundt mens det stivnet.</p>'
      + '<p>To temperaturer gjør to forskjellige jobber, og de lar seg ikke slå sammen. Timer på 150 °C smelter fettet og myker opp bindevevet. Så gir et kort støt på 240 °C svoren de boblene den skal ha, men bare hvis svoren er tørr. Derfor står stykket udekket i kjøleskapet natten over og saltes i siste liten.</p>'},
  ingredients:[
    { group:{en:'The meat', no:'Kjøttet'}, items:[
      {q:2.5, u:'kg', n:{en:'pork belly, rind on, boned', no:'sideflesk med svor, uten bein'}, note:{en:'in one rectangular piece, rind unscored — Norwegian shops sell tynnribbe already scored and salted for Christmas, so ask for an untreated piece', no:'i ett rektangulært stykke med urutet svor; norske butikker selger tynnribbe ferdig rutet og saltet til jul, så be om et ubehandlet stykke'}},
      {q:1, u:'kg', n:{en:'pork loin', no:'svinekam'}, note:{en:'off the bone and skinned, trimmed to an even cylinder', no:'utbeinet og uten svor, renskåret til en jevn sylinder'}},
    ]},
    { group:{en:'The seasoning', no:'Krydringen'}, items:[
      {q:15, u:'g', n:{en:'fennel seeds', no:'fennikelfrø'}, note:{en:'wild fennel seed if you can get it; fennel pollen is better still', no:'frø av viltvoksende fennikel om du får tak i det; fennikelpollen er enda bedre'}},
      {q:10, u:'g', n:{en:'black peppercorns', no:'sorte pepperkorn'}},
      {q:15, u:'g', n:{en:'rosemary leaves', no:'rosmarinnåler'}, note:{en:'stripped off the stalk', no:'plukket av stilken'}},
      {q:8, u:'', n:{en:'garlic cloves', no:'hvitløksfedd'}, round:'half'},
      {q:35, u:'g', n:{en:'coarse salt for the meat', no:'grovt salt til kjøttet'}},
      {q:15, u:'g', n:{en:'fine salt for the rind', no:'fint salt til svoren'}},
    ]},
  ],
  steps:[
    {en:'Lay the belly rind down and score the meat side in a shallow lattice, cutting into the flesh but nowhere near the rind.',
     no:'Legg sideflesket med svoren ned, og rut opp kjøttsiden med grunne snitt som går ned i kjøttet, men ikke i nærheten av svoren.'},
    {en:'Toast the fennel seeds and the peppercorns in a dry pan until they smell, then crush them coarsely in a mortar.',
     no:'Rist fennikelfrøene og pepperkornene i en tørr panne til de dufter, og knus dem så grovt i morter.'},
    {en:'Pound the garlic and rosemary with the coarse salt into a rough paste and work the crushed spices into it.',
     no:'Stamp hvitløken og rosmarinen sammen med det grove saltet til en grov masse, og arbeid de knuste krydderne inn i den.'},
    {en:'Rub the paste hard into the scored meat and all over the loin, and keep every trace of it off the rind, where salt and herbs would burn.',
     no:'Gni massen godt inn i det oppkuttede kjøttet og rundt hele kammen, og hold hvert spor av den unna svoren, der salt og urter ville brent seg.'},
    {en:'Lay the loin along one long edge of the belly and roll the belly tightly round it, keeping the rind on the outside.',
     no:'Legg kammen langs den ene langsiden av sideflesket, og rull sideflesket stramt rundt den, med svoren ytterst.'},
    {en:'Tie the roll with butcher’s string at intervals of about 3 cm, tight enough that the cut end stays round when you stand it up.',
     no:'Bind rullen med kjøtthyssing med rundt 3 cm mellomrom, stramt nok til at snittflaten holder seg rund når du setter den på høykant.'},
    {en:'Stand the roll on a rack over a tray and leave it uncovered in the fridge overnight, until the rind feels dry and papery to the hand.',
     no:'Sett rullen på rist over en langpanne, og la den stå udekket i kjøleskapet natten over, til svoren kjennes tørr og papiraktig mot hånden.'},
    {en:'Take it out an hour before cooking, then rub the fine salt evenly over the rind just as the oven comes up to 150 °C.',
     no:'Ta den ut en time før steking, og gni det fine saltet jevnt utover svoren akkurat idet ovnen når 150 °C.'},
    {en:'Roast on the rack for about three hours, until a thermometer pushed into the centre of the loin reads 75 °C.',
     no:'Stek på risten i rundt tre timer, til termometeret viser 75 °C midt inne i kammen.'},
    {en:'Turn the oven up to 240 °C and give it fifteen to twenty-five minutes more, turning the tray, until the rind has blistered and crackles all the way round.',
     no:'Skru ovnen opp til 240 °C, og gi den femten til tjuefem minutter til mens du snur langpannen, til svoren har boblet seg opp og er sprø hele veien rundt.'},
    {en:'Rest the roll for twenty minutes before it is cut, so the juices settle back into the meat instead of running out onto the board.',
     no:'La rullen hvile i tjue minutter før den skjæres, så kraften trekker tilbake i kjøttet i stedet for å renne ut på fjøla.'},
    {en:'Cut the string away and slice the roll about a centimetre thick with a serrated knife, sawing through the rind first.',
     no:'Klipp bort hyssingen, og skjær rullen i skiver på rundt en centimeter med brødkniv. Sag deg gjennom svoren først.'},
  ],
  notes:[
    {title:{en:'Two temperatures, two jobs', no:'To temperaturer, to jobber'},
     body:{en:'Fat renders and collagen turns to gelatine slowly, over hours, somewhere around 150 °C; the rind only puffs when its remaining water flashes to steam, which needs well over 200 °C. Attempt both at one temperature and you either burn the outside long before the middle is done, or you cook it through and take out a leathery skin.',
           no:'Fett smelter og bindevev blir til gelatin langsomt, over timer, et sted rundt 150 °C. Svoren bobler først opp når vannet som er igjen i den, går over til damp, og det krever godt over 200 °C. Prøver du begge deler på én temperatur, brenner du enten utsiden lenge før midten er ferdig, eller du steker den gjennom og tar ut et seigt skinn.'}},
    {title:{en:'A dry rind, salted late', no:'Tørr svor, saltet sent'},
     body:{en:'Water in the surface of the rind boils away as steam and cools it, so a damp skin simply cannot reach the temperature at which it puffs. A night uncovered in the fridge dries it out; salt put on early would draw moisture back to the surface and undo the night’s work, which is why it goes on at the door of the oven.',
           no:'Vann i overflaten av svoren koker bort som damp og kjøler den ned, så et fuktig skinn klarer rett og slett ikke å nå temperaturen der det bobler opp. En natt udekket i kjøleskapet tørker det ut. Salt som legges på tidlig, ville trukket fuktighet tilbake til overflaten og ødelagt nattens arbeid, og derfor kommer det på i ovnsdøren.'}},
    {title:{en:'The rind is not scored', no:'Svoren skal ikke rutes'},
     body:{en:'A Norwegian ribbe is cut into squares so the fat can run and the pieces separate into crisp tiles. Porchetta wants the opposite — one unbroken sheet that lifts off the meat as it puffs — so the rind is left whole and only the meat underneath is scored. Cut through it and the fat escapes, the roll dries and the crackling comes out in strips.',
           no:'En norsk ribbe rutes opp så fettet kan renne og bitene skiller seg fra hverandre som sprø fliser. Porchetta vil ha det motsatte, nemlig én sammenhengende plate som løfter seg fra kjøttet mens den bobler opp, så svoren får ligge hel, og bare kjøttet under skjæres opp. Skjærer du gjennom den, slipper fettet ut, rullen tørker, og svoren kommer ut i strimler.'}},
  ],
  variations:[
    {title:{en:'Panino con la porchetta', no:'Panino con la porchetta'},
     body:{en:'What the vans by the roadside sell, and the reason to make more than you can eat hot. Cold slices with a piece of the crackling, pressed into unsalted bread, with nothing on it — no butter, no mustard, no sauce of any kind.',
           no:'Dette er det bilene langs veien selger, og grunnen til å lage mer enn du klarer å spise varmt. Kalde skiver med en bit av svoren, presset inn i usaltet brød, uten noe som helst på. Verken smør, sennep eller saus.'}},
    {title:{en:'Belly alone', no:'Bare sideflesk'},
     body:{en:'Leave the loin out and roll the belly on itself. The roll is thinner, needs about two thirds of the low roasting time, and gives a fattier, softer slice with a spiral of crackling through the middle. Everything else is the same.',
           no:'Sløyf kammen, og rull sideflesket rundt seg selv. Rullen blir tynnere, trenger rundt to tredjedeler av tiden på lav varme, og gir en fetere og mykere skive med en spiral av svor gjennom midten. Alt annet er likt.'}},
    {title:{en:'Rome’s version', no:'Den romerske varianten'},
     body:{en:'Porchetta di Ariccia, from the hills south of Rome, is seasoned mainly with rosemary, garlic and pepper. Both are the same animal cooked the same way; the wild fennel is the Umbrian signature, and swapping the two is how you tell the regions apart on the plate.',
           no:'Porchetta di Ariccia, fra åsene sør for Roma, krydres først og fremst med rosmarin, hvitløk og pepper. Begge er samme dyr tilberedt på samme måte, men den viltvoksende fennikelen er det umbriske kjennetegnet, og bytter du krydderet, bytter du region.'}},
  ],
},

{
  id:'uova-al-tartufo-nero', dish:'Uova al tartufo', course:'antipasto', lesson:3, serves:4, time:{prep:15, cook:10},
  hero:'uovatartufo', tags:['truffle','egg','quick'],
  title:{en:'Uova al tartufo nero', no:'Uova al tartufo nero'},
  blurb:{en:'The Umbrian way with a black truffle when there is no occasion: grate most of it into eggs, cook them barely, and eat it on toast.',
         no:'Slik umbrere bruker en svart trøffel når det ikke er noen anledning. Riv mesteparten ned i egg, la dem så vidt stivne, og spis alt på ristet brød.'},
  heroCaption:{en:'Soft-set egg with black truffle sliced over it, and a truffled toast alongside.',
               no:'Løs eggerøre med svart trøffel i skiver over, og en ristet brødskive med trøffel ved siden av.'},
  wines:['Grechetto'],
  headnote:{
    en:'<p>Around Norcia and Spoleto the black truffle is not a garnish, and the Umbrian way with it is generous and plain: a great deal of it grated into warm oil and turned through pasta, laid on toasted bread, or beaten into eggs. The eggs are the cheapest of the three and probably the best, because egg has almost no flavour of its own to fight with and a great deal of fat to carry the aroma.</p>'
      + '<p>The trick that costs nothing is to shut the eggs and the truffle in a jar together the day before. Eggshell is porous, the aroma passes straight through it, and by morning the eggs smell of truffle before any has touched them. Restaurants have done this for as long as there have been restaurants in Norcia.</p>'
      + '<p>Everything else is the low-heat scrambled egg you already know: constant movement, small wet curds, the pan lifted off the heat before the eggs look done, and salt only at the end. And note which truffle this is — the black winter truffle is cooked, while the white one of Alba is only ever shaved raw over a hot plate.</p>',
    no:'<p>Rundt Norcia og Spoleto er den svarte trøffelen ikke pynt, og umbrere bruker den rundhåndet og enkelt. Rikelig av den rives ned i lun olje og vendes gjennom pasta, legges på ristet brød, eller piskes inn i egg. Egg er det rimeligste av de tre og trolig det beste, for egg har nesten ingen egen smak å kjempe mot og mye fett til å bære duften.</p>'
      + '<p>Legg eggene og trøffelen i et lukket glass sammen dagen før. Det koster ingenting. Eggeskall er porøst, duften går rett gjennom det, og til neste morgen lukter eggene trøffel før noe har rørt dem. Restaurantene har gjort dette så lenge det har vært restauranter i Norcia.</p>'
      + '<p>Resten er vanlig eggerøre på svak varme. Stadig bevegelse, små og fuktige klumper, pannen løftet av platen før eggene ser ferdige ut, og salt først til slutt. Merk deg også hvilken trøffel dette er. Den svarte vintertrøffelen varmebehandles, mens den hvite fra Alba bare høvles rå over noe varmt.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:8, u:'', n:{en:'eggs', no:'egg'}, note:{en:'as fresh as you can get, and stored with the truffle the day before', no:'så ferske som mulig, og oppbevart sammen med trøffelen dagen før'}, round:'half'},
    {q:40, u:'g', n:{en:'black winter truffle', no:'svart vintertrøffel'}, note:{en:'Tuber melanosporum, brushed clean and never washed', no:'Tuber melanosporum, børstet ren og aldri vasket'}},
    {q:50, u:'ml', n:{en:'extra virgin olive oil', no:'ekstra virgin olivenolje'}},
    {q:20, u:'g', n:{en:'butter', no:'smør'}, note:{en:'optional, for a rounder texture', no:'valgfritt, for en rundere konsistens'}},
    {q:4, u:'', n:{en:'slices of country bread', no:'skiver landbrød'}, round:'half'},
    {q:1, u:'', n:{en:'garlic clove', no:'hvitløksfedd'}, round:'half'},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
  ]}],
  steps:[
    {en:'The day before, shut the eggs and the whole truffle in a jar together and leave it in the fridge. Skip this and the dish still works; do it and it doubles.',
     no:'Dagen før legger du eggene og hele trøffelen i et lukket glass sammen og setter det i kjøleskapet. Dropper du det, blir retten god likevel, men gjør du det, blir den dobbelt så god.'},
    {en:'Brush the truffle clean with a dry brush, working into the folds. Water washes the aroma out of it and it never comes back.',
     no:'Børst trøffelen ren med en tørr børste, og gå inn i foldene. Vann skyller duften ut av den, og den kommer aldri tilbake.'},
    {en:'Grate half of it on the fine side of the grater and cut the other half into thin slices.',
     no:'Riv halvparten av den på den fine siden av rivjernet, og skjær den andre halvparten i tynne skiver.'},
    {en:'Beat the eggs only until the yolks and whites merge. Whisking air into them gives a foam that collapses in the pan.',
     no:'Visp eggene bare til plommer og hviter går sammen. Pisker du luft inn i dem, får du et skum som faller sammen i pannen.'},
    {en:'Stir the grated truffle into the beaten eggs and leave them to stand for ten minutes.',
     no:'Rør den revne trøffelen inn i de sammenvispede eggene, og la dem stå i ti minutter.'},
    {en:'Warm most of the oil and the butter in a heavy pan over the lowest heat, with the garlic clove in it, and take the garlic out as soon as it smells.',
     no:'Varm mesteparten av oljen og smøret i en tung panne på den svakeste varmen du har, med hvitløksfeddet oppi, og ta ut hvitløken så snart den dufter.'},
    {en:'Pour in the eggs and stir them slowly and without stopping, scraping the base of the pan with a spatula.',
     no:'Hell i eggene, og rør sakte og uten å stoppe mens du skraper bunnen av pannen med en slikkepott.'},
    {en:'Lift the pan on and off the heat as it thickens, so the curds stay small and wet rather than setting into a sheet.',
     no:'Løft pannen av og på platen mens massen tykner, så klumpene holder seg små og fuktige i stedet for å stivne til en plate.'},
    {en:'Take the pan off the heat while the eggs still look a little underdone, and only now stir in salt and pepper. They go on setting on the way to the table.',
     no:'Ta pannen av platen mens eggene fortsatt ser litt løse ut, og rør først nå inn salt og pepper. De stivner videre på vei til bordet.'},
    {en:'Toast the bread, rub it with the cut garlic clove and trickle the last of the oil over it.',
     no:'Rist brødet, gni det med det oppskårne hvitløksfeddet, og drypp resten av oljen over.'},
    {en:'Spoon the eggs onto the toast and lay the sliced truffle over them at the table, where the warmth will lift the smell.',
     no:'Fordel eggene over brødet med en skje, og legg trøffelskivene over ved bordet, der varmen vil løfte duften.'},
  ],
  notes:[
    {title:{en:'Fat is the solvent', no:'Fettet er løsemiddelet'},
     body:{en:'The compounds that make a truffle smell of a truffle dissolve in fat and hardly at all in water. Egg yolk and olive oil pick them up and hold them; a broth or a tomato sauce lets most of them straight past. That single fact explains why truffle in Italy nearly always arrives on eggs, on butter, on oil or on cheese.',
           no:'Stoffene som gir trøffelen duften sin, løser seg i fett og nesten ikke i vann. Eggeplomme og olivenolje tar dem opp og holder på dem, mens en kraft eller en tomatsaus slipper det meste rett forbi. Det forklarer hvorfor trøffel i Italia nesten alltid kommer på egg, på smør, på olje eller på ost.'}},
    {title:{en:'Salt last, heat low', no:'Salt til slutt, svak varme'},
     body:{en:'Salt beaten into raw egg starts pulling water out of the proteins, and the scramble weeps in the pan. High heat does the same thing faster and knots the protein into rubber. Low heat, constant movement and salt at the end are three ways of solving the same problem.',
           no:'Salt som vispes inn i rå egg, begynner å trekke vann ut av proteinene, og eggerøren skiller seg i pannen. Sterk varme gjør det samme raskere og knyter proteinet sammen til gummi. Svak varme, stadig bevegelse og salt til slutt er tre måter å løse det samme problemet på.'}},
    {title:{en:'Which truffle, and what you can do to it', no:'Hvilken trøffel, og hva du kan gjøre med den'},
     body:{en:'The black winter truffle of Norcia can be warmed, which is why half of it goes into the eggs; the white truffle of Alba loses everything above blood heat and is shaved raw at the table over something already hot. Buying one and treating it as the other wastes a great deal of money.',
           no:'Den svarte vintertrøffelen fra Norcia tåler å bli varmet, og derfor går halvparten av den ned i eggene. Den hvite fra Alba mister alt over kroppstemperatur og høvles rå ved bordet over noe som allerede er varmt. Kjøper du den ene og behandler den som den andre, kaster du bort mye penger.'}},
  ],
  variations:[
    {title:{en:'As a frittata', no:'Som frittata'},
     body:{en:'Same eggs, same truffle, but let the base set in the pan over low heat, finish the top under the grill and cut it into wedges. It travels, and it is what goes into a lunch box in truffle season.',
           no:'Samme egg og samme trøffel, men la bunnen sette seg i pannen på svak varme, gi toppen litt grill til slutt, og skjær den i båter. Den tåler transport, og den havner i matboksen i trøffelsesongen.'}},
    {title:{en:'On toast alone', no:'Bare på ristet brød'},
     body:{en:'Skip the eggs. Warm the grated truffle in oil with a crushed garlic clove and an anchovy, spoon it over toasted unsalted bread and eat it standing up. This is the third of the three Umbrian uses and the fastest.',
           no:'Sløyf eggene. Varm den revne trøffelen i olje med et knust hvitløksfedd og en ansjos, legg den over ristet, usaltet brød med en skje, og spis den stående. Dette er den tredje av de tre umbriske bruksmåtene, og den raskeste.'}},
    {title:{en:'Butter instead of oil', no:'Smør i stedet for olje'},
     body:{en:'Butter carries the aroma just as well and gives a rounder, sweeter result; it is how Piedmont handles truffle. Umbria reaches for olive oil, and the reading says the region uses it with a heaviness that would alarm a Ligurian.',
           no:'Smør bærer duften like godt og gir et rundere og søtere resultat, og slik gjør de det i Piemonte. I Umbria brukes olivenolje, og lesestykket sier at regionen bruker den med en tyngde som ville skremt en ligurer.'}},
  ],
},

];
