// valledaosta recipes. Contract: docs/recipe-format.md. Both languages in one file; never narrated.
// Everything here follows the Valle d'Aosta food reading (content/valledaosta.js, lesson 3): Fontina is
// the through-line, the fat is butter rather than olive oil, the bread is rye and hard, and the cheese
// goes in at a temperature low enough that it melts instead of splitting.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-23'] = [

{
  id:'carbonada', dish:'Carbonada', course:'secondo', lesson:3, serves:4, time:{prep:25, cook:150},
  hero:'carbonada', tags:['beef','stew','winter','polenta'],
  title:{en:'Carbonada', no:'Carbonada'},
  blurb:{en:'Salt beef, as much onion as meat, red wine and two slow hours. The valley’s winter stew, eaten over polenta.',
         no:'Saltet oksekjøtt, like mye løk som kjøtt, rødvin og to langsomme timer. Dalens vintergryte, spist over polenta.'},
  heroCaption:{en:'Carbonada at Arpy in the upper valley, with a pot of polenta and a dish of mushrooms beside it.',
               no:'Carbonada i Arpy øverst i dalen, med en kjele polenta og en skål sopp ved siden av.'},
  wines:['Torrette','Fumin'],
  headnote:{
    en:'<p>Carbonada is the Aosta valley’s stew, and it began as a way of eating meat that had been salted to get through a winter. Before refrigeration a household salted what it could not eat at once, and salt beef is not something you roast. It is something you soak, and then cook for hours with onions and red wine until the salt has spread through the whole pot and the meat falls apart. The name is the same word as coal, and a finished pot is very nearly that colour.</p>'
      + '<p>Two things are not negotiable. The fat is butter, because there is almost no olive oil in this kitchen, and there must be as much onion as there is meat. Nothing is added to thicken the sauce: the onions collapse over two hours and become it.</p>'
      + '<p>Salt belongs at the end, or not at all, and that is the one instruction that catches out a cook working from a salt-beef recipe with fresh beef in the pan. Taste before you reach for the salt, and taste again before it goes to the table. It is served over polenta, and in the valley that often means polenta concia, which makes a very rich plate indeed.</p>',
    no:'<p>Carbonada er gryteretten i Aostadalen, og den begynte som en måte å spise kjøtt på som var saltet for å komme gjennom vinteren. Før kjøleskapet saltet husholdningen det den ikke rakk å spise, og saltet oksekjøtt egner seg ikke til steking. Det må vannes ut og deretter koke i timevis med løk og rødvin, til saltet har fordelt seg i hele gryten og kjøttet faller fra hverandre. Navnet er det samme ordet som kull, og en ferdig gryte har omtrent den fargen.</p>'
      + '<p>To ting ligger fast. Fettet er smør, for det finnes nesten ikke olivenolje i dette kjøkkenet, og det skal være like mye løk som kjøtt. Ingenting tilsettes for å jevne sausen. Løken koker seg i stykker i løpet av to timer og blir til den.</p>'
      + '<p>Saltet hører hjemme til slutt, eller ikke i det hele tatt. Den som lager retten av ferskt kjøtt etter en oppskrift skrevet for saltet kjøtt, går lett i den fella. Smak før du tar saltbøssen, og smak en gang til før retten går på bordet. Den serveres over polenta, og i dalen betyr det ofte polenta concia, som gir en svært fyldig tallerken.</p>'},
  ingredients:[
    { group:{en:'The pot', no:'Gryten'}, items:[
      {q:1000, u:'g', n:{en:'beef chuck or shin', no:'oksekjøtt av høyrygg eller bog'},
       note:{en:'traditionally salt-cured; fresh meat works, and the first step says what changes',
             no:'tradisjonelt saltet; ferskt kjøtt fungerer, og første steg sier hva som er annerledes da'}},
      {q:800, u:'g', n:{en:'onions', no:'løk'}, note:{en:'thinly sliced', no:'i tynne skiver'}},
      {q:70, u:'g', n:{en:'butter', no:'smør'}},
      {q:30, u:'g', n:{en:'plain flour', no:'hvetemel'},
       note:{en:'to dust the meat; it browns, it does not thicken', no:'til å vende kjøttet i; det gir farge, ikke jevning'}},
      {q:400, u:'ml', n:{en:'dry red wine', no:'tørr rødvin'},
       note:{en:'a mountain red such as Torrette, or any dry red without oak on it',
             no:'en fjellrødvin som Torrette, eller en annen tørr rødvin uten preg av fat'}},
      {q:250, u:'ml', n:{en:'beef broth or water', no:'oksekraft eller vann'}},
    ]},
    { group:{en:'The spices', no:'Krydderet'}, items:[
      {q:2, u:'', n:{en:'bay leaves', no:'laurbærblad'}, round:'half'},
      {q:8, u:'', n:{en:'juniper berries', no:'einerbær'}, note:{en:'lightly crushed', no:'lett knust'}, round:'half'},
      {q:2, u:'', n:{en:'cloves', no:'nellikspiker'}, round:'half'},
      {q:1, u:'', n:{en:'small cinnamon stick', no:'liten kanelstang'}, round:'half'},
      {u:'', n:{en:'nutmeg', no:'muskatnøtt'}, note:{en:'grated over at the end of the spicing', no:'revet over til slutt'}, scale:'none'},
      {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
      {u:'', n:{en:'salt', no:'salt'}, note:{en:'at the end, and only if it needs it', no:'på slutten, og bare hvis retten trenger det'}, scale:'none'},
    ]},
    { group:{en:'To serve', no:'Til servering'}, items:[
      {u:'', n:{en:'polenta, plain or concia', no:'polenta, vanlig eller concia'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'If the beef is salt-cured, soak it in cold water overnight, changing the water a couple of times, then drain it and pat it dry. Fresh beef needs no soaking.',
     no:'Er kjøttet saltet, legger du det i kaldt vann natten over og skifter vann et par ganger. Renn av og tørk det. Ferskt kjøtt trenger ingen utvanning.'},
    {en:'Cut the meat into cubes the size of a walnut, leaving the sinew and the fat where they are; both dissolve into the sauce.',
     no:'Skjær kjøttet i terninger på størrelse med en valnøtt, og la sener og fett sitte igjen. Begge deler løser seg opp i sausen.'},
    {en:'Turn the cubes in the flour and shake off whatever does not stick.',
     no:'Vend terningene i melet og rist av det som ikke sitter fast.'},
    {en:'Melt half the butter in a heavy casserole over medium heat and brown the meat a small handful at a time, so the pan keeps its heat. Lift each batch out as it colours.',
     no:'Smelt halvparten av smøret i en tung gryte på middels varme, og brun kjøttet i små porsjoner, slik at gryten holder på varmen. Løft hver porsjon ut når den har fått farge.'},
    {en:'Add the rest of the butter and the onions, turn the heat low, and let them soften for twenty minutes while you scrape up what the meat left on the bottom.',
     no:'Ha i resten av smøret og løken, skru ned varmen, og la den mykne i tjue minutter mens du skraper løs det kjøttet har satt igjen i bunnen.'},
    {en:'Return the meat, raise the heat and pour in the wine. Let it bubble for a few minutes until the raw smell of it has gone.',
     no:'Legg kjøttet tilbake, skru opp varmen og hell i vinen. La den boble noen minutter til råsmaken er borte.'},
    {en:'Add the broth, the bay, the juniper, the cloves and the cinnamon, and grate a little nutmeg over. The liquid should come halfway up the meat and no further.',
     no:'Ha i kraften, laurbærbladene, einerbærene, nellikspikrene og kanelstangen, og riv litt muskat over. Væsken skal gå halvveis opp på kjøttet og ikke lenger.'},
    {en:'Cover the pot and let it tremble rather than simmer for two hours, on the lowest ring or in the oven at 150 °C, stirring now and then.',
     no:'Legg på lokk og la gryten skjelve snarere enn koke i to timer, på den svakeste platen eller i ovnen ved 150 °C. Rør om nå og da.'},
    {en:'Take the lid off for the last half hour and let the sauce reduce until it is dark and clings to the meat.',
     no:'Ta lokket av den siste halvtimen og la sausen koke inn til den er mørk og legger seg rundt kjøttet.'},
    {en:'Fish out the cinnamon, the bay and the cloves. Taste, and only now add pepper and, if it needs it, salt.',
     no:'Fisk ut kanelstangen, laurbærbladene og nellikspikrene. Smak, og først nå har du i pepper og eventuelt salt.'},
    {en:'Serve it over hot polenta, with the sauce spooned around rather than over, so the polenta stays visible.',
     no:'Server over varm polenta, med sausen skjedd rundt og ikke over, så polentaen fortsatt synes.'},
  ],
  notes:[
    {title:{en:'Salted first, seasoned last', no:'Saltet først, krydret sist'},
     body:{en:'A salt-cured piece of beef gives up salt to the pot for as long as it cooks, and there is no taking it out again. Even with fresh meat, two hours of reduction concentrates everything that went in at the start. Season at the end, when the sauce is at the strength it will be eaten at.',
           no:'Et saltet stykke oksekjøtt gir fra seg salt til gryten hele tiden mens det koker, og det lar seg ikke ta ut igjen. Selv med ferskt kjøtt konsentrerer to timers innkoking alt som gikk i tidlig. Smak til på slutten, når sausen har den styrken den skal spises med.'}},
    {title:{en:'The onions are the sauce', no:'Løken er sausen'},
     body:{en:'As much onion as meat looks like far too much for the first twenty minutes, and then it disappears. Slow heat breaks the onion down until nothing in the pot is recognisable as onion, and the sauce thickens because of that and not because of flour or cream. The dusting of flour on the meat is there to brown; it is not a thickener, and high heat under the onions browns them instead of melting them, which leaves the sauce thin.',
           no:'Like mye løk som kjøtt ser ut som altfor mye de første tjue minuttene, og så forsvinner den. Langsom varme bryter løken ned til ingenting i gryten er til å kjenne igjen som løk, og sausen tykner av det og ikke av mel eller fløte. Melet på kjøttet er der for å gi farge og er ingen jevning, og sterk varme under løken bruner den i stedet for å smelte den. Da blir sausen tynn.'}},
    {title:{en:'Why long and low', no:'Hvorfor lenge og lavt'},
     body:{en:'Chuck and shin are full of collagen, which stays tough at any temperature until it has had hours just below a simmer. Then it turns to gelatine and gives the sauce its body. A rolling boil does the opposite: it tightens the muscle fibres and squeezes the water out of them, which is why the pot must never do more than tremble.',
           no:'Høyrygg og bog er fulle av bindevev som er seigt uansett temperatur helt til det har fått timer like under kokepunktet. Da blir det til gelatin og gir sausen fylde. Fosskoking gjør det motsatte: den strammer kjøttfibrene og presser vannet ut av dem, og derfor skal gryten aldri gjøre mer enn å skjelve.'}},
  ],
  variations:[
    {title:{en:'Salt the beef yourself', no:'Salt kjøttet selv'},
     body:{en:'Rub the cubes with coarse salt, leave them covered in the fridge for a day and rinse them well before they go in the pan. You get some of the older, firmer flavour without curing anything for weeks.',
           no:'Gni terningene inn med grovt salt, la dem ligge tildekket i kjøleskapet et døgn, og skyll dem godt før de går i gryten. Du får noe av den gamle, fastere smaken uten å speke kjøtt i ukevis.'}},
    {title:{en:'With game', no:'Med vilt'},
     body:{en:'Game belongs in this kitchen, and a shoulder of venison or elk takes the same treatment. Both are leaner than beef, so give them less time and a little more butter, and check them after an hour and a half.',
           no:'Vilt hører hjemme i dette kjøkkenet, og bog av hjort eller elg tåler den samme behandlingen. Begge deler er magrere enn oksekjøtt, så gi dem kortere tid og litt mer smør, og kjenn etter allerede etter halvannen time.'}},
    {title:{en:'What to put it on', no:'Hva du har den til'},
     body:{en:'Plain polenta is the sober choice, polenta concia the generous one, and boiled potatoes are the third. All three are there for the same reason, which is to take up the sauce.',
           no:'Vanlig polenta er det nøkterne valget, polenta concia det rause, og kokte poteter er det tredje. Alle tre er der av samme grunn, nemlig for å ta opp sausen.'}},
  ],
},

{
  id:'polenta-concia', dish:'Polenta concia', course:'primo', lesson:3, serves:4, time:{prep:10, cook:55},
  hero:'polentaconcia', tags:['polenta','fontina','vegetarian','winter'],
  title:{en:'Polenta concia', no:'Polenta concia'},
  blurb:{en:'Polenta beaten with butter and cubes of Fontina until a spoon will stand up in it.',
         no:'Polenta pisket med smør og terninger av Fontina til skjeen blir stående.'},
  heroCaption:{en:'Polenta and Fontina browned in the oven — the baked version of the dish, served in the dish it was baked in.',
               no:'Polenta og Fontina brunet i ovnen — den ovnsbakte utgaven av retten, servert i formen den ble stekt i.'},
  wines:['Torrette'],
  headnote:{
    en:'<p>Polenta concia is polenta that has been dressed — <em>conciare</em> is to season or to treat — until it is barely polenta any more. Maize meal cooks in salted water for the better part of an hour, and then butter and cubes of Fontina are beaten into it until, as they say in the valley, a spoon will stand up in it.</p>'
      + '<p>It works because of the cheese. Fontina is semi-soft, made from whole raw milk, around 45% fat in dry matter, and it melts into a smooth thread instead of separating into fat and rubber. A hard grating cheese in the same place gives you strings and a pool of oil.</p>'
      + '<p>The maize matters nearly as much. Coarse stone-ground meal cooked slowly keeps a little grain to it, so the dish stays rich without turning into paste. The quick-cooking meal sold in most Norwegian supermarkets has been cooked and dried already, and it gives a smooth result that sets like a brick as it cools.</p>',
    no:'<p>Polenta concia er polenta som er blitt beriket — <em>conciare</em> betyr å tilberede eller krydre — til den knapt er polenta lenger. Maismel koker i saltet vann i nærmere en time, og deretter piskes smør og terninger av Fontina inn, til skjeen blir stående, slik de sier i dalen.</p>'
      + '<p>Osten er grunnen til at retten fungerer. Fontina er halvmyk, laget av rå helmelk, med rundt 45 % fett i tørrstoffet, og den smelter til en jevn tråd i stedet for å skille seg i fett og gummi. En hard revet ost på samme plass gir tråder og en pytt av olje.</p>'
      + '<p>Maisen betyr nesten like mye. Grovmalt mel fra steinkvern som får koke langsomt, beholder litt tygg, så retten blir fyldig uten å bli en klissen masse. Hurtigpolentaen som står i de fleste norske butikker, er allerede kokt og tørket, og den gir et glatt resultat som stivner som en murstein når det kjølner.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:300, u:'g', n:{en:'coarse maize meal', no:'grovmalt maismel'},
     note:{en:'stone-ground bramata, not the quick-cooking kind', no:'grovmalt bramata fra steinkvern, ikke hurtigpolenta'}},
    {q:1400, u:'ml', n:{en:'water', no:'vann'}},
    {q:12, u:'g', n:{en:'salt', no:'salt'}},
    {q:200, u:'g', n:{en:'Fontina DOP', no:'Fontina DOP'},
     note:{en:'rind cut off, in small cubes, left out of the fridge', no:'uten skorpe, i små terninger, tatt ut av kjøleskapet i god tid'}},
    {q:100, u:'g', n:{en:'butter', no:'smør'}, note:{en:'half into the polenta, half browned over the top', no:'halvparten i polentaen, halvparten brunet over'}},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
  ]}],
  steps:[
    {en:'Bring the water to the boil in a heavy pan and salt it.',
     no:'Kok opp vannet i en tung kjele og salt det.'},
    {en:'Let the meal fall in through your fingers in a thin stream, whisking without stopping, so that no lump ever forms.',
     no:'La melet falle ned mellom fingrene i en tynn stråle mens du visper uten stans, så det ikke rekker å klumpe seg.'},
    {en:'Turn the heat as low as it will go once the mixture thickens, and let it cook for three quarters of an hour.',
     no:'Skru varmen så lavt som den går når massen tykner, og la den koke i tre kvarter.'},
    {en:'Stir every few minutes with a wooden spoon, always reaching the bottom of the pan, which is where it catches first.',
     no:'Rør med tresleiv med noen minutters mellomrom, og gå alltid helt ned i bunnen, for det er der den setter seg først.'},
    {en:'Cut the rind off the Fontina and cut the cheese into small cubes while the polenta cooks. Leave them out of the fridge.',
     no:'Skjær skorpen av Fontinaen og osten i små terninger mens polentaen koker. La dem stå framme.'},
    {en:'Taste the polenta. It is done when no grain is chalky any more and it pulls away from the side of the pan.',
     no:'Smak på polentaen. Den er ferdig når ingen korn kjennes melne lenger, og når den slipper kanten av kjelen.'},
    {en:'Take the pan off the heat and beat in half the butter until it has disappeared.',
     no:'Ta kjelen av platen og pisk inn halvparten av smøret til det er borte.'},
    {en:'Add the cheese a handful at a time, beating between each, until it has melted into threads and the polenta turns glossy.',
     no:'Ha i osten en håndfull om gangen, og pisk mellom hver, til den har smeltet i tråder og polentaen blir blank.'},
    {en:'Grind pepper over and taste for salt. The cheese brings a good deal of its own.',
     no:'Kvern pepper over og smak på saltet. Osten tar med seg mye av sitt eget.'},
    {en:'Brown the rest of the butter in a small pan until it smells of nuts, pour it over the polenta and serve straight away, on warm plates.',
     no:'Brun resten av smøret i en liten panne til det lukter nøtter, hell det over polentaen, og server med en gang på varme tallerkener.'},
  ],
  notes:[
    {title:{en:'Why Fontina and not a hard cheese', no:'Hvorfor Fontina og ikke en hard ost'},
     body:{en:'Fontina is young, moist and fatty, and its protein network is loose enough to soften and flow at a low temperature while the fat stays evenly suspended in it. A hard, dry, long-aged cheese has a tight protein mesh that contracts in the heat and squeezes out both fat and water, which is what strings and grease are. The same property is the reason fonduta, polenta concia and seupa à la Vapelenentse all work with this one cheese.',
           no:'Fontina er ung, fuktig og fet, og proteinnettet i den er løst nok til å mykne og flyte ved lav temperatur mens fettet blir liggende jevnt fordelt. En hard, tørr og lenge lagret ost har et stramt proteinnett som trekker seg sammen i varmen og presser ut både fett og vann, og det er nettopp det trådene og fettet på overflaten er. Den samme egenskapen er grunnen til at fonduta, polenta concia og seupa à la Vapelenentse alle fungerer med denne ene osten.'}},
    {title:{en:'Coarse meal, slow heat', no:'Grovt mel, lav varme'},
     body:{en:'Polenta thickens because the starch granules take up water and burst, and that takes both time and heat. Quick-cooking meal has been through it already: it swells in minutes but has nothing left to give, so it is smooth at once, gluey five minutes later and hard as a paving stone when cold.',
           no:'Polenta tykner ved at stivelseskornene tar opp vann og sprekker, og det krever både tid og varme. Hurtigpolenta har vært gjennom det allerede. Den sveller på minutter, men har ingenting igjen å gi, så den er glatt med en gang, klissen fem minutter etter og hard som en stein når den er kald.'}},
    {title:{en:'It stiffens as it cools', no:'Den stivner mens den kjølner'},
     body:{en:'The cheese keeps the polenta soft only while it is hot; below about 50 °C it firms up and the dish turns heavy. Warm the plates, serve it out of the pan, and do not let it wait for anybody.',
           no:'Osten holder polentaen myk bare så lenge den er varm. Under omtrent 50 °C stivner den, og retten blir tung. Varm tallerkenene, server rett fra kjelen, og la den ikke vente på noen.'}},
  ],
  variations:[
    {title:{en:'Polenta grassa', no:'Polenta grassa'},
     body:{en:'Layer plain polenta and slices of Fontina in a buttered dish and bake at 200 °C until the top is brown and blistered. That is the version in the photograph above, and unlike polenta concia in the pan it will happily wait half an hour for its guests.',
           no:'Legg vanlig polenta og skiver av Fontina lagvis i en smurt form og stek det ved 200 °C til toppen er brun og bobler. Det er utgaven på bildet over, og i motsetning til polenta concia i kjelen tåler den å vente en halvtime på gjestene.'}},
    {title:{en:'The leftovers', no:'Restene'},
     body:{en:'Spread what is left in a cold tray, let it set, cut it into slabs and fry them in butter or lay them on a grill. With carbonada beside them that is a meal in its own right.',
           no:'Bre ut det som er igjen i et kaldt fat, la det stivne, skjær det i skiver og stek dem i smør eller legg dem på grillen. Med carbonada ved siden av er det et måltid i seg selv.'}},
    {title:{en:'If you cannot find Fontina', no:'Hvis du ikke får tak i Fontina'},
     body:{en:'Look for the consortium’s Matterhorn stamp; without it the cheese is an imitation and often pasteurised. Raclette is the nearest thing in Norwegian shops and behaves the same way, young and fat and willing. A mild yellow supermarket cheese melts but tastes of very little, and anything hard and long-aged will split.',
           no:'Se etter konsortiets Matterhorn-stempel. Uten det er osten en etterligning, og ofte pasteurisert. Raclette ligger nærmest i norske butikker og oppfører seg likt, ung og fet og smeltevillig. En mild gulost smelter, men smaker svært lite, og alt som er hardt og lenge lagret, skiller seg.'}},
  ],
},

{
  id:'seupa-a-la-vapelenentse', dish:'Seupa à la Vapelenentse', course:'primo', lesson:3, serves:4, time:{prep:30, cook:45},
  hero:'merenda', tags:['bread','cabbage','fontina','baked'],
  title:{en:'Seupa à la Vapelenentse', no:'Seupa à la Vapelenentse'},
  blurb:{en:'A baked soup of hard rye bread, cabbage and Fontina, soaked in broth and browned in the oven.',
         no:'En ovnsbakt suppe av hardt rugbrød, kål og Fontina, lagt i kraft og brunet i ovnen.'},
  heroCaption:{en:'There is no free photograph of the soup itself. This is what it is built from: hard rye bread and Fontina, cut in the open air.',
               no:'Det finnes ikke noe fritt bilde av selve suppen. Dette er det den bygger på: hardt rugbrød og Fontina, skåret i det fri.'},
  wines:['Torrette'],
  headnote:{
    en:'<p>Valpelline is a side valley north of Aosta, and the soup that carries its name was made from the three things a house always had: rye bread too hard to bite into, cabbage, and Fontina. Broth soaks the bread, the oven browns the cheese, and an hour later there is a dish nobody would call poor.</p>'
      + '<p>Rye bread here was baked hard, only a few times a year, in a communal village oven, and then stored on wooden racks until it was wanted. That is why the recipe asks for bread that has dried out rather than fresh bread. Dry slices drink the broth and keep their shape; soft bread turns to porridge under the cheese.</p>'
      + '<p>It is built in layers and it is never stirred. Bread, cabbage, cheese, and again, with the broth poured down the side of the dish until it reaches the top layer without covering it. Whatever stands above the liquid browns, and whatever lies under it becomes a savoury bread pudding.</p>',
    no:'<p>Valpelline er en sidedal nord for Aosta, og suppen som bærer navnet til dalen, ble laget av de tre tingene et hus alltid hadde: rugbrød som var for hardt å bite i, kål og Fontina. Kraften bløter opp brødet, ovnen bruner osten, og en time senere står det en rett på bordet som ingen ville kalt fattig.</p>'
      + '<p>Rugbrødet her ble bakt hardt, bare noen få ganger i året, i en felles landsbyovn, og deretter lagret på trehyller til det trengtes. Derfor vil oppskriften ha brød som har tørket, og ikke ferskt brød. Tørre skiver drikker kraften og holder formen, mens mykt brød blir til grøt under osten.</p>'
      + '<p>Retten bygges i lag, og den røres aldri i. Brød, kål, ost, og så en gang til, med kraften helt langs kanten av formen til den når det øverste laget uten å dekke det. Det som stikker opp av væsken, bruner seg, og det som ligger under, blir til en smaksrik brødpudding.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:300, u:'g', n:{en:'dark rye bread', no:'mørkt rugbrød'},
     note:{en:'two or three days old and dry right through, in thin slices', no:'to–tre dager gammelt og tørt tvers igjennom, i tynne skiver'}},
    {q:600, u:'g', n:{en:'Savoy cabbage', no:'savoykål'}, note:{en:'the thick ribs cut out, the leaves in wide strips', no:'uten de grove stilkene, bladene i brede strimler'}},
    {q:300, u:'g', n:{en:'Fontina DOP', no:'Fontina DOP'}, note:{en:'rind cut off, in thin slices', no:'uten skorpe, i tynne skiver'}},
    {q:1200, u:'ml', n:{en:'beef broth', no:'oksekraft'}, note:{en:'a real one; the soup tastes of it', no:'helst hjemmelaget, for suppen smaker av kraften'}},
    {q:80, u:'g', n:{en:'butter', no:'smør'}},
    {u:'', n:{en:'nutmeg', no:'muskatnøtt'}, scale:'none'},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
  ]}],
  steps:[
    {en:'Slice the rye bread thin. If it is not dry all the way through, spread the slices on a tray and dry them in the oven at 120 °C until they are hard.',
     no:'Skjær rugbrødet i tynne skiver. Er det ikke tørt tvers igjennom, legger du skivene på et stekebrett og tørker dem i ovnen ved 120 °C til de er harde.'},
    {en:'Fry the dry slices in a little of the butter until the edges take colour, and set them aside.',
     no:'Stek de tørre skivene i litt av smøret til kantene får farge, og sett dem til side.'},
    {en:'Cut the thick ribs out of the cabbage leaves and cut the leaves into wide strips.',
     no:'Skjær de grove stilkene ut av kålbladene, og skjær bladene i brede strimler.'},
    {en:'Bring the broth to the boil and blanch the cabbage in it for five minutes. Lift it out, let it drain, and keep the broth; the cabbage has flavoured it.',
     no:'Kok opp kraften og forvell kålen i den i fem minutter. Løft den ut, la den renne av, og ta vare på kraften, for kålen har gitt smak til den.'},
    {en:'Heat the oven to 180 °C and butter a deep dish.',
     no:'Sett ovnen på 180 °C og smør en dyp form.'},
    {en:'Lay a layer of bread in the bottom, then a layer of cabbage, then a layer of Fontina.',
     no:'Legg et lag brød i bunnen, så et lag kål og så et lag Fontina.'},
    {en:'Carry on in that order until everything is used up, and finish with cheese.',
     no:'Fortsett i den rekkefølgen til alt er brukt opp, og avslutt med ost.'},
    {en:'Pour the hot broth slowly down the side of the dish until it stands level with the top layer without covering it.',
     no:'Hell den varme kraften langsomt langs kanten av formen til den står i høyde med det øverste laget uten å dekke det.'},
    {en:'Dot the rest of the butter over the top, grate a little nutmeg over and grind pepper over that.',
     no:'Del resten av smøret i biter over toppen, riv litt muskat over og kvern pepper over der igjen.'},
    {en:'Bake for forty minutes, until the top is brown and blistered and the edges are bubbling.',
     no:'Stek i førti minutter, til toppen er godt brun og det bobler i kantene.'},
    {en:'Let it stand for ten minutes, then serve it from the dish with a spoon.',
     no:'La formen hvile i ti minutter, og server suppen rett fra den, med skje.'},
  ],
  notes:[
    {title:{en:'The bread is the structure', no:'Brødet er stillaset'},
     body:{en:'Dry bread has lost its water and its crumb has set hard, so it can take up several times its own weight in broth and still hold together in slices. Fresh bread is already saturated and simply falls apart. That is why the dish belongs to a place that baked a few times a year and stored the loaves hard.',
           no:'Tørt brød har mistet vannet sitt, og krummen har stivnet, så det kan suge til seg mange ganger sin egen vekt i kraft og likevel holde sammen i skiver. Ferskt brød er allerede mettet og går rett i oppløsning. Derfor hører retten hjemme et sted der man bakte noen få ganger i året og lagret brødet hardt.'}},
    {title:{en:'Where the broth stops', no:'Hvor kraften skal stoppe'},
     body:{en:'The level of the liquid is the difference between the two ways this goes wrong. Too much and it is a soup with lumps in it; too little and the bread at the bottom stays hard. Pour down the side rather than over the top, so the layers are left alone and the cheese keeps a dry surface to brown on.',
           no:'Væskenivået er forskjellen mellom de to måtene dette kan gå galt på. For mye, og du får suppe med klumper i; for lite, og brødet nederst blir hardt. Hell langs kanten og ikke over toppen, så får lagene ligge i fred og osten beholder en tørr overflate å brune seg på.'}},
    {title:{en:'Why the cabbage is blanched first', no:'Hvorfor kålen forvelles først'},
     body:{en:'Raw cabbage gives up a lot of water in the oven and thins the dish out from the inside. Five minutes in boiling broth gets most of that out of the way, and the water it loses ends up in the broth you are going to use anyway.',
           no:'Rå kål gir fra seg mye vann i ovnen og tynner ut retten innenfra. Fem minutter i kokende kraft tar unna det meste, og vannet kålen slipper, havner i kraften du likevel skal bruke.'}},
  ],
  variations:[
    {title:{en:'A scrape of cinnamon', no:'Litt kanel'},
     body:{en:'Several versions put a little cinnamon between the layers along with the nutmeg. It sounds odd next to cabbage and is not, and it is the same instinct that puts cinnamon and cloves in carbonada.',
           no:'Flere utgaver har litt kanel mellom lagene sammen med muskaten. Det høres rart ut ved siden av kål, men er det ikke, og det er den samme tanken som setter kanel og nellik i carbonada.'}},
    {title:{en:'A layer of cured meat', no:'Et lag spekemat'},
     body:{en:'Some cooks lay thin slices of Lard d\'Arnad or raw ham between the bread and the cabbage. The dish gets heavier and the fat melts down into the bread, which is either the point or a step too far, depending on whose grandmother you ask.',
           no:'Noen legger tynne skiver Lard d\'Arnad eller spekeskinke mellom brødet og kålen. Retten blir kraftigere, og fettet smelter ned i brødet. Om det er selve poenget eller ett skritt for langt, kommer an på hvilken bestemor du spør.'}},
    {title:{en:'If there is no dark rye', no:'Hvis du ikke får mørkt rugbrød'},
     body:{en:'Use a close-textured sourdough loaf, dried in the oven the same way. The soup comes out milder and paler but holds together just as well. Sliced bread from a bag does not: it dissolves.',
           no:'Bruk et fast surdeigsbrød, tørket i ovnen på samme måte. Suppen blir mildere og lysere, men holder like godt sammen. Formbrød fra pose gjør ikke det; det løser seg opp.'}},
  ],
},

{
  id:'fonduta-alla-valdostana', dish:'Fonduta alla valdostana', course:'antipasto', lesson:3, serves:4, time:{prep:15, cook:20},
  hero:'fontinaslice', tags:['fontina','cheese','egg','truffle'],
  title:{en:'Fonduta alla valdostana', no:'Fonduta alla valdostana'},
  blurb:{en:'Fontina soaked in milk and finished with egg yolks into a warm cream. Not a fondue: nothing is dipped, and it is eaten with a spoon.',
         no:'Fontina bløtlagt i melk og avsluttet med eggeplommer til en varm krem. Dette er ingen fondue; ingenting dyppes, og den spises med skje.'},
  heroCaption:{en:'A wedge of Fontina, which is very nearly the whole recipe. There is no free photograph of the finished dish.',
               no:'En bit Fontina, som nærmest er hele oppskriften. Det finnes ikke noe fritt bilde av den ferdige retten.'},
  wines:['Petite Arvine'],
  headnote:{
    en:'<p>Fonduta is what Valle d’Aosta does with its cheese when it wants nothing else on the plate. Fontina is diced and left to soak in milk, then melted with butter and finished with egg yolks into a warm cream thick enough to coat a spoon, and poured over polenta or toast. In the grand version, white truffle from over the border in Piedmont is shaved on at the table.</p>'
      + '<p>It is not Swiss fondue and it is not built like one. There is no wine, no kirsch and no starch in it, nothing is dipped into it, and it is eaten with a spoon. The yolks do the work that wine and cornflour do in a fondue: they hold fat and liquid together as one cream.</p>'
      + '<p>Temperature is the whole discipline. Yolks set into scrambled egg above about 70 °C, and cheese that gets too hot squeezes its fat straight out again. A bowl over barely simmering water keeps you below both limits, and that is why nobody makes this over a direct flame.</p>',
    no:'<p>Fonduta er det Valle d’Aosta gjør med osten sin når den ikke vil ha noe annet på tallerkenen. Fontina skjæres i terninger og får ligge i melk, smeltes så med smør og avsluttes med eggeplommer til en varm krem som er tykk nok til å legge seg rundt skjeen, og helles over polenta eller ristet brød. I storutgaven høvles hvit trøffel fra andre siden av grensen i Piemonte over ved bordet.</p>'
      + '<p>Dette er ikke sveitsisk fondue, og den bygges ikke opp som en. Her er det verken vin, kirsebærbrennevin eller stivelse, ingenting dyppes i den, og den spises med skje. Eggeplommene gjør jobben vinen og maisstivelsen gjør i en fondue: de holder fett og væske sammen i én krem.</p>'
      + '<p>Temperaturen er hele disiplinen. Eggeplommer stivner til eggerøre over omtrent 70 °C, og ost som blir for varm, presser fettet rett ut igjen. En bolle over vann som så vidt småkoker, holder deg under begge grensene, og derfor lager ingen denne retten rett på platen.</p>'},
  ingredients:[
    { group:{en:'The cream', no:'Kremen'}, items:[
      {q:400, u:'g', n:{en:'Fontina DOP', no:'Fontina DOP'}, note:{en:'rind cut off, in small dice', no:'uten skorpe, i små terninger'}},
      {q:300, u:'ml', n:{en:'whole milk', no:'helmelk'}, note:{en:'enough to cover the cheese; what is left over goes back in', no:'nok til å dekke osten; det som blir til overs, sper du med'}},
      {q:4, u:'', n:{en:'egg yolks', no:'eggeplommer'}, round:'half'},
      {q:40, u:'g', n:{en:'butter', no:'smør'}},
      {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
    ]},
    { group:{en:'To serve', no:'Til servering'}, items:[
      {u:'', n:{en:'hot polenta or toasted rye bread', no:'varm polenta eller ristet rugbrød'}, scale:'none'},
      {u:'', n:{en:'white truffle', no:'hvit trøffel'}, note:{en:'if the year and the wallet allow', no:'hvis året og lommeboken tillater det'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Cut the rind off the Fontina and cut the cheese into small dice.',
     no:'Skjær skorpen av Fontinaen og osten i små terninger.'},
    {en:'Put the dice in a bowl, pour the milk over until they are just covered, and leave them in the fridge for at least two hours, or overnight.',
     no:'Legg terningene i en bolle, hell melken over til de akkurat er dekket, og sett bollen kaldt i minst to timer, gjerne natten over.'},
    {en:'Drain the cheese and keep the milk. It will have thickened and taken up some of the flavour of the cheese.',
     no:'Hell av melken og ta vare på den. Den har tyknet og tatt opp noe av smaken fra osten.'},
    {en:'Set a bowl or a heavy pan over a pan of barely simmering water, with the base clear of the water itself.',
     no:'Sett en bolle eller en tung kjele over en kjele med vann som så vidt småkoker, slik at bunnen ikke rører vannet.'},
    {en:'Melt the butter in it, add the drained cheese and a little of the milk, and stir with a wooden spoon.',
     no:'Smelt smøret i den, ha i osten og litt av melken, og rør med tresleiv.'},
    {en:'Keep stirring while the cheese melts into a thick, even cream, adding more of the milk whenever it is too stiff to move. Never let the water underneath boil.',
     no:'Fortsett å røre mens osten smelter til en tykk og jevn krem, og spe med mer av melken hver gang den blir for stiv å røre i. La aldri vannet under koke opp.'},
    {en:'Beat the yolks in a separate bowl and slacken them with a spoonful of the warm cheese, stirring hard as it goes in.',
     no:'Pisk sammen eggeplommene i en egen bolle, og spe dem med en skje av den varme osten mens du rører kraftig.'},
    {en:'Pour the yolks back into the cheese and stir steadily for two or three minutes, until the cream thickens and coats the back of the spoon.',
     no:'Hell plommene tilbake i osten og rør jevnt i to–tre minutter, til kremen tykner og legger seg på baksiden av skjeen.'},
    {en:'Lift it off the water at once, grind pepper over and taste for salt. The cheese usually brings enough.',
     no:'Løft den av vannbadet med en gang, kvern pepper over og smak om den trenger salt. Som regel har osten nok.'},
    {en:'Pour it over hot polenta or toast, shave truffle over if you have it, and serve immediately with spoons.',
     no:'Hell den over varm polenta eller ristet brød, høvle trøffel over hvis du har, og server straks, med skjeer.'},
  ],
  notes:[
    {title:{en:'What the soak does', no:'Hva bløtleggingen gjør'},
     body:{en:'Dry dice of cheese dropped into hot milk melt unevenly and clump. Hours in cold milk let the curd take up water, so the protein network is already loose when the heat arrives and the cheese flows at a temperature low enough for the yolks to survive it.',
           no:'Tørre osteterninger som slippes ned i varm melk, smelter ujevnt og klumper seg. Timer i kald melk lar ostemassen ta opp vann, slik at proteinnettet allerede er løst når varmen kommer, og osten flyter ved en temperatur som er lav nok til at eggeplommene tåler den.'}},
    {title:{en:'A yolk binds, and then it sets', no:'Plommen binder, og så stivner den'},
     body:{en:'The lecithin in an egg yolk is an emulsifier and keeps fat suspended in liquid, while the proteins in the same yolk coagulate at around 70 °C. A yolk stirred in away from direct heat gives you a cream; a yolk that meets a boil gives you lumps. Slackening it with a spoonful of the warm cheese first raises its temperature slowly enough to stay on the right side of that line.',
           no:'Lecitinet i en eggeplomme er et emulgeringsmiddel og holder fettet svevende i væsken, mens proteinene i den samme plommen koagulerer ved rundt 70 °C. En plomme som røres inn utenfor direkte varme, gir krem, og en plomme som møter et oppkok, gir klumper. Når du sper den med en skje varm ost først, hever du temperaturen langsomt nok til å holde deg på riktig side av den grensen.'}},
    {title:{en:'If it splits', no:'Hvis den skiller seg'},
     body:{en:'Take the bowl off the water immediately, add a spoonful of cold milk and whisk hard. It usually comes back together. If it will not, it has been too hot, and nothing brings it back.',
           no:'Ta bollen av vannbadet med en gang, ha i en skje kald melk og visp hardt. Som regel samler kremen seg igjen. Vil den ikke det, har den vært for varm, og da er den ikke til å redde.'}},
  ],
  variations:[
    {title:{en:'With white truffle', no:'Med hvit trøffel'},
     body:{en:'The grand version takes white truffle from Alba, just over the border in Piedmont, shaved on at the table. It is never heated; it only meets the warm cream, which is enough to carry the smell across the room.',
           no:'Storutgaven får hvit trøffel fra Alba, rett over grensen i Piemonte, høvlet over ved bordet. Den varmes aldri, men møter bare den varme kremen, og det holder til å fylle rommet med duft.'}},
    {title:{en:'On rye instead of polenta', no:'På rugbrød i stedet for polenta'},
     body:{en:'Polenta is the usual bed for it, but the valley’s own dark rye, toasted hard, is just as correct and gives something to bite on under all that softness.',
           no:'Polenta er det vanlige underlaget, men dalens eget mørke rugbrød, ristet hardt, er like riktig og gir noe å tygge på under all mykheten.'}},
    {title:{en:'What is left over', no:'Det som blir igjen'},
     body:{en:'Loosen it with milk over the lowest heat and use it as a sauce for boiled potatoes or for gnocchi. It will not stand a second real heating, so warm it only to the point where it moves.',
           no:'Spe den med melk på svakeste varme og bruk den som saus til kokte poteter eller gnocchi. Den tåler ingen ny skikkelig oppvarming, så varm den bare til den så vidt blir flytende.'}},
  ],
},

{
  id:'coppa-dell-amicizia', dish:'', course:'dolce', lesson:3, serves:4, time:{prep:10, cook:5},
  hero:'coppa', tags:['drink','coffee','grappa','after dinner'],
  title:{en:'Coppa dell’amicizia', no:'Coppa dell’amicizia'},
  blurb:{en:'Hot coffee, grappa, sugar and lemon peel in a wooden cup with several spouts, lit for a moment and passed round the table.',
         no:'Varm kaffe, grappa, sukker og sitronskall i et trebeger med flere tuter, tent på et øyeblikk og sendt rundt bordet.'},
  heroCaption:{en:'A coppa dell’amicizia in use at Cogne: sugared rim, peel inside, and a spout for each drinker.',
               no:'En coppa dell’amicizia i bruk i Cogne, med sukkerkant, skall oppi og en tut til hver som drikker.'},
  headnote:{
    en:'<p>The coppa dell’amicizia is not a dish but the end of a meal: a low, round wooden bowl with a lid and several spouts, filled with hot coffee, grappa, sugar and lemon peel, lit for a moment and then passed from hand to hand so that each person drinks from the spout nearest them. Tradition says the cup is not put down until it is empty.</p>'
      + '<p>The cups are turned and carved in the valley, and the number of spouts is the number of people it is meant for. The related grolla, a taller carved goblet, is the same idea with more ceremony around it.</p>'
      + '<p>Making it is simple, but the coffee has to be genuinely hot, and that is the part people forget. Wood pulls the heat out of a drink quickly, so scald the cup with boiling water first and pour the water away.</p>',
    no:'<p>Coppa dell’amicizia er ingen rett, men slutten på et måltid: en lav, rund treskål med lokk og flere tuter, fylt med varm kaffe, grappa, sukker og sitronskall, tent på et øyeblikk og deretter sendt fra hånd til hånd, slik at hver enkelt drikker av tuten nærmest seg. Tradisjonen sier at begeret ikke skal settes ned før det er tomt.</p>'
      + '<p>Begrene dreies og skjæres ut i dalen, og antallet tuter er antallet mennesker begeret er ment for. Den beslektede grollaen, et høyere, utskåret beger, er den samme tanken med mer seremoni rundt seg.</p>'
      + '<p>Tilberedningen er enkel, men kaffen må være virkelig varm, og det er den delen folk glemmer. Tre trekker varmen ut av en drikk fort, så skåld begeret med kokende vann først og hell vannet ut.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:500, u:'ml', n:{en:'strong hot coffee', no:'sterk, varm kaffe'}, note:{en:'moka pot or espresso, and properly hot', no:'fra mokakanne eller espressomaskin, og ordentlig varm'}},
    {q:150, u:'ml', n:{en:'grappa', no:'grappa'}},
    {q:60, u:'g', n:{en:'sugar', no:'sukker'}},
    {q:1, u:'', n:{en:'lemon', no:'sitron'}, note:{en:'the peel only, pared in wide strips', no:'bare skallet, skåret av i brede strimler'}, round:'half'},
    {u:'', n:{en:'sugar for the rims', no:'sukker til kantene'}, scale:'none'},
  ]}],
  steps:[
    {en:'Scald the cup with boiling water, let it stand a minute and pour the water away.',
     no:'Skåld begeret med kokende vann, la det stå et minutt, og hell vannet ut.'},
    {en:'Pare the lemon peel off in wide strips and leave the white pith on the fruit, because it is bitter.',
     no:'Skjær sitronskallet av i brede strimler, og la det hvite sitte igjen på frukten, for det er bittert.'},
    {en:'Rub the rim of each spout with a strip of peel and press it into sugar, so that it dries into a crust.',
     no:'Gni kanten rundt hver tut med en strimmel skall og press den ned i sukker, så den tørker til en skorpe.'},
    {en:'Make the coffee and keep it hot until the moment it goes in.',
     no:'Trakt kaffen og hold den varm til det øyeblikket den skal i.'},
    {en:'Put the sugar, the peel and the grappa into the cup and stir until the sugar has dissolved.',
     no:'Ha sukkeret, skallet og grappaen i begeret og rør til sukkeret har løst seg opp.'},
    {en:'Pour the hot coffee in and stir once.',
     no:'Hell den varme kaffen i og rør én gang.'},
    {en:'Light the surface with a long match, give the flame a few seconds and put the lid on to smother it. Do it with clear space around you, and never lean over the cup.',
     no:'Tenn på overflaten med en lang fyrstikk, la flammen få noen sekunder, og legg på lokket for å kvele den. Gjør det med god plass rundt deg, og bøy deg aldri over begeret.'},
    {en:'Set the cup in the middle of the table with the lid on and leave it a moment to settle.',
     no:'Sett begeret midt på bordet med lokket på, og la det stå et øyeblikk.'},
    {en:'Pass it from hand to hand, each person drinking from the spout in front of them, and do not set it down until it is empty.',
     no:'Send det fra hånd til hånd, la hver enkelt drikke av tuten foran seg, og ikke sett det ned før det er tomt.'},
  ],
  notes:[
    {title:{en:'The flame is meant to be short', no:'Flammen skal være kort'},
     body:{en:'A few seconds burns off a little alcohol and caramelises the sugar on the rims, which is the whole point of lighting it. Left to burn, it heats the wood, takes more of the grappa with it than you intended and leaves the drink bitter. The lid is the extinguisher, and that is why it comes with the cup.',
           no:'Noen sekunder brenner av litt alkohol og karamelliserer sukkeret på kantene, og det er hele poenget med å tenne på. Får flammen brenne lenge, varmer den opp treet, tar med seg mer av grappaen enn du hadde tenkt, og etterlater en bitter drikk. Lokket er slokkeredskapet, og derfor følger det med begeret.'}},
    {title:{en:'Why the cup is scalded', no:'Hvorfor begeret skåldes'},
     body:{en:'Wood insulates well and holds heat once it has it, but a cold cup takes the first heat straight out of the drink. Warm it through and the coffee arrives hot and is still hot on the third time round the table.',
           no:'Tre isolerer godt og holder på varmen når det først har fått den, men et kaldt beger tar den første varmen rett ut av drikken. Varm det gjennom, så kommer kaffen varm i og er fortsatt varm tredje gang begeret går rundt bordet.'}},
    {title:{en:'It is less than it looks', no:'Det er mindre enn det ser ut til'},
     body:{en:'With four to eight people round a table the cup goes round three or four times and every mouthful is small. The rule about not setting it down governs the pace of an evening better than any agreement about how much anyone is drinking.',
           no:'Med fire til åtte rundt bordet går begeret tre–fire runder, og hver slurk er liten. Regelen om at det ikke settes ned, styrer tempoet i kvelden bedre enn noen avtale om hvor mye hver enkelt skal drikke.'}},
  ],
  variations:[
    {title:{en:'With génépy', no:'Med génépy'},
     body:{en:'Replace part of the grappa with génépy, the pale green liqueur made from alpine wormwood. The drink turns more herbal and less sharp, and the two are often on the same table anyway.',
           no:'Bytt ut en del av grappaen med génépy, den blekgrønne likøren laget på alpemalurt. Drikken blir mer urtepreget og mindre skarp, og de to står gjerne på samme bord likevel.'}},
    {title:{en:'Without the flame', no:'Uten flamme'},
     body:{en:'Plenty of houses skip the lighting altogether. The drink tastes much the same, the alcohol stays where you put it, and the cup lasts longer.',
           no:'Mange hus dropper påtenningen helt. Drikken smaker omtrent det samme, alkoholen blir der du helte den, og begeret varer lenger.'}},
    {title:{en:'The grolla', no:'Grollaen'},
     body:{en:'The taller carved goblet takes the same filling and goes round the same way, with rather more ceremony attached to it. It is the version brought out when there is something to mark.',
           no:'Det høyere, utskårne begeret fylles med det samme og går rundt på samme måte, med atskillig mer seremoni knyttet til seg. Det er utgaven som kommer fram når det er noe å markere.'}},
  ],
},

];
