// veneto recipes. Contract: docs/recipe-format.md. Both languages in one file; never narrated.
// Everything here follows the Veneto food reading (content/veneto.js, lesson 3): Venetian cooking is
// built on preserving — saor is a sweet-sour onion-and-vinegar cure, baccalà in Veneto means Norwegian
// stockfish and not salt cod, bigoli in salsa is a fast-day sauce of onion and salted fish, and risi e
// bisi is neither soup nor risotto.
window.RECIPES = window.RECIPES || {};
window.RECIPES['IT-34'] = [

{
  id:'risi-e-bisi', dish:'Risi e bisi', course:'primo', lesson:3, serves:4, time:{prep:25, cook:50},
  hero:'risibisi', tags:['rice','peas','spring'],
  title:{en:'Risi e bisi', no:'Risi e bisi'},
  blurb:{en:'The Doge’s spring dish: rice and the first peas, thicker than a soup and looser than a risotto, eaten with a spoon.',
         no:'Dogens vårrett: ris og de første ertene, tykkere enn en suppe og løsere enn en risotto, spist med skje.'},
  heroCaption:{en:'Risi e bisi should ripple when you tilt the bowl — all’onda, on the wave.',
               no:'Risi e bisi skal bevege seg når du vipper på skålen — all’onda, på bølgen.'},
  wines:['Soave Classico'],
  headnote:{
    en:'<p>Risi e bisi belonged to the Doge. It was carried up to the Palazzo Ducale on 25 April, the feast of St Mark, when the first peas came in from the lagoon islands — Sant’Erasmo, Vignole, Mazzorbo — and the sweetest of them were kept for the table of the state. Venice is a rice city rather than a pasta city, and this is its spring dish.</p>'
      + '<p>It is neither a soup nor a risotto, and the course reading is firm about that: thicker than one, looser than the other, and eaten with a spoon. Venetians call the texture <em>all’onda</em>, on the wave — tilt the bowl and the surface should move. You get there with liquid rather than with technique: more broth than a risotto takes, and no reduction at the end.</p>'
      + '<p>The pods are the point. Podding peas leaves a heap of green husks that most kitchens throw out; simmered for half an hour they give the broth its whole flavour, and the dish then tastes of pea twice over. Out of season, frozen peas work, but you will need a light vegetable broth instead, because there are no pods to make one from.</p>',
    no:'<p>Risi e bisi hørte dogen til. Retten ble båret opp til Palazzo Ducale 25. april, på markusdagen, når de første ertene kom inn fra øyene i lagunen — Sant’Erasmo, Vignole, Mazzorbo — og de søteste av dem ble holdt av til statens bord. Venezia er en risby og ingen pastaby, og dette er byens vårrett.</p>'
      + '<p>Den er verken suppe eller risotto, og leseteksten er tydelig på det: tykkere enn en suppe, løsere enn en risotto, og den spises med skje. Venetianerne kaller konsistensen <em>all’onda</em>, på bølgen. Vipper du på skålen, skal overflaten bevege seg. Dit kommer du med væske, ikke med teknikk. Du bruker mer kraft enn en risotto tar, og du damper ikke inn til slutt.</p>'
      + '<p>Belgene er poenget. Når du belger erter, sitter du igjen med en haug grønne skall som de fleste kjøkken kaster. Kok dem i en halvtime, så gir de kraften hele smaken, og retten smaker av ert to ganger. Utenom sesongen går det med frosne erter, men da trenger du en lett grønnsakkraft i stedet, for du har ingen belger å koke på.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:1.2, u:'kg', n:{en:'fresh peas in the pod', no:'ferske erter i belg'}, note:{en:'keep the pods — they make the broth', no:'ta vare på belgene, de blir til kraften'}},
    {q:320, u:'g', n:{en:'Vialone Nano rice', no:'Vialone Nano-ris'}, note:{en:'the Veneto rice; Carnaroli will do', no:'risen fra Veneto; Carnaroli gjør også nytten'}},
    {q:100, u:'g', n:{en:'pancetta', no:'pancetta'}, note:{en:'in small dice', no:'i små terninger'}},
    {q:1, u:'', n:{en:'white onion', no:'hvit løk'}, round:'half', note:{en:'finely chopped', no:'finhakket'}},
    {q:40, u:'g', n:{en:'butter', no:'smør'}},
    {q:20, u:'ml', n:{en:'olive oil', no:'olivenolje'}},
    {q:30, u:'g', n:{en:'cold butter, to finish', no:'kaldt smør, til slutt'}},
    {q:60, u:'g', n:{en:'Grana Padano', no:'Grana Padano'}, note:{en:'finely grated', no:'finrevet'}},
    {q:10, u:'g', n:{en:'flat-leaf parsley', no:'bladpersille'}, note:{en:'chopped', no:'hakket'}},
    {q:1.6, u:'l', n:{en:'water, for the pod broth', no:'vann til belgkraften'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
  ]}],
  steps:[
    {en:'Pod the peas and keep every pod.',
     no:'Belg ertene, og ta vare på hver eneste belg.'},
    {en:'Put the pods in a pan with the water, bring it to a simmer and cook for 30 minutes.',
     no:'Legg belgene i en kjele med vannet, kok opp, og la det småkoke i 30 minutter.'},
    {en:'Strain the broth, pressing the pods against the sieve as you go, and keep it barely simmering on a back ring.',
     no:'Sil kraften, og press belgene mot silen mens du gjør det. La kraften stå og småputre videre.'},
    {en:'Chop the onion finely and dice the pancetta.',
     no:'Hakk løken fint, og skjær pancettaen i terninger.'},
    {en:'Melt the butter with the oil in a wide pan and sweat the onion and pancetta over low heat for 10 minutes, until they are soft and still pale.',
     no:'Smelt smøret sammen med oljen i en vid kjele, og la løken og pancettaen surre på svak varme i 10 minutter, til de er myke og fortsatt lyse.'},
    {en:'Add the peas and a ladleful of broth and cook for 5 minutes, until they lose their raw taste.',
     no:'Ha i ertene og en øse med kraft, og kok i 5 minutter, til råsmaken er borte.'},
    {en:'Stir in the rice and let it take up the fat for a minute. Do not fry it hard the way you would for a risotto.',
     no:'Rør inn risen, og la den trekke til seg fettet et minutt. Ikke stek den hardt slik du ville gjort til en risotto.'},
    {en:'Pour in most of the hot broth at once, season lightly and simmer for about 15 minutes, stirring now and then.',
     no:'Hell i mesteparten av den varme kraften på én gang, smak til med litt salt, og la det småkoke i omtrent 15 minutter. Rør av og til.'},
    {en:'Add the rest of the broth as the rice drinks it up. Keep the dish soup-loose, because it tightens as it stands.',
     no:'Spe med resten av kraften etter hvert som risen drikker den opp. Hold retten suppeløs, for den strammer seg mens den står.'},
    {en:'Take the pan off the heat, beat in the cold butter and the grated cheese, and let it rest for two minutes.',
     no:'Ta kjelen av platen, pisk inn det kalde smøret og den revne osten, og la retten hvile et par minutter.'},
    {en:'Stir through the parsley, grind over pepper and serve in deep bowls, with spoons.',
     no:'Vend inn persillen, kvern over pepper, og server i dype skåler, med skje.'},
  ],
  notes:[
    {title:{en:'The pods are the stock', no:'Belgene er kraften'},
     body:{en:'A pea starts turning its sugar into starch the moment it is picked, and much of the green, grassy aroma sits in the pod rather than in the pea. Simmer the pods and use that water as the cooking liquid, and every grain of rice tastes of pea. The same trick works with broad-bean pods, corn cobs, prawn shells and the rind of a hard cheese.',
           no:'En ert begynner å gjøre sukkeret sitt om til stivelse i det øyeblikket den plukkes, og mye av den grønne, gressaktige aromaen sitter i belgen og ikke i erten. Kok belgene, og bruk vannet som kokevæske, så smaker hvert eneste riskorn av ert. Det samme knepet virker med bønnebelger, maiskolber, rekeskall og skorpen av en fast ost.'}},
    {title:{en:'All’onda is not risotto', no:'All’onda er ikke risotto'},
     body:{en:'A risotto is built by adding liquid a little at a time and stirring hard, so the grains grind against each other and release the starch that thickens the dish. Risi e bisi takes most of its broth in one go and is never reduced at the end, so less starch comes out and the grains sit in liquid rather than in a paste. That is the whole difference, and it is a difference of method rather than of ingredients.',
           no:'En risotto bygges ved at du sper med væske litt om gangen og rører hardt, slik at kornene gnis mot hverandre og gir fra seg stivelsen som tykner retten. Risi e bisi får mesteparten av kraften på én gang og dampes aldri inn til slutt, så mindre stivelse slipper ut, og kornene ligger i væske og ikke i en jevn masse. Der ligger hele forskjellen, og den ligger i metoden, ikke i ingrediensene.'}},
    {title:{en:'Why Veneto rice is looser', no:'Derfor er risen fra Veneto løsere'},
     body:{en:'Vialone Nano is a short, round semifino grown on the spring-fed plain south of Verona. It drinks more liquid than Carnaroli and holds its shape while doing it, which is why Veneto rice dishes are wetter than Lombard ones and why a Venetian eats them with a spoon.',
           no:'Vialone Nano er en kort, rund semifino som dyrkes på sletten sør for Verona, der kildene holder rismarkene under vann. Den drikker mer væske enn Carnaroli og holder likevel fasongen, og derfor er risrettene fra Veneto våtere enn de lombardiske, og derfor spiser en venetianer dem med skje.'}},
  ],
  variations:[
    {title:{en:'Out of season', no:'Utenom sesongen'},
     body:{en:'Frozen peas are honest here and often sweeter than tired fresh ones. Use a light vegetable broth in place of the pod broth and add the peas late, in the last few minutes, or they go grey and floury.',
           no:'Frosne erter er et hederlig valg her, og de er ofte søtere enn slappe ferske. Bruk en lett grønnsakkraft i stedet for belgkraften, og ha ertene i sent, i de siste minuttene, ellers blir de grå og melne.'}},
    {title:{en:'Without the pork', no:'Uten svinekjøtt'},
     body:{en:'Leave the pancetta out and the dish becomes a lean-day version: a little more butter at the start, a little more cheese at the end, and the pea flavour comes forward rather than back.',
           no:'Sløyfer du pancettaen, blir retten en fastedagsversjon: litt mer smør i begynnelsen, litt mer ost til slutt, og ertesmaken kommer fram i stedet for å tre tilbake.'}},
    {title:{en:'The rest of the family', no:'Resten av familien'},
     body:{en:'Venice builds the same dish around whatever the season gives, and the name simply changes with it — rice and eel, rice and pumpkin, rice and sausage. The construction never varies: soffritto, one main ingredient, rice, and far more broth than a risotto would take.',
           no:'Venezia bygger den samme retten rundt det årstiden gir, og navnet skifter med den — ris og ål, ris og gresskar, ris og pølse. Oppbygningen er alltid den samme: soffritto, én hovedråvare, ris og langt mer kraft enn en risotto ville tatt.'}},
  ],
},

{
  id:'baccala-mantecato', dish:'Baccalà mantecato', course:'antipasto', lesson:3, serves:6, time:{prep:40, cook:25},
  hero:'baccala', tags:['stockfish','cicchetti','emulsion'],
  title:{en:'Baccalà mantecato', no:'Baccalà mantecato'},
  blurb:{en:'Norwegian stockfish, soaked for days and beaten with olive oil into a white cream. No cream, no butter, no potato.',
         no:'Norsk tørrfisk, vannet ut i dagevis og pisket med olivenolje til en hvit krem. Ingen fløte, intet smør, ingen potet.'},
  heroCaption:{en:'Baccalà mantecato on rounds of grilled white polenta, the standard cicchetto of every bàcaro in Venice.',
               no:'Baccalà mantecato på skiver av grillet hvit polenta, standardcicchettoen i enhver bàcaro i Venezia.'},
  wines:['Prosecco Superiore','Soave Classico'],
  headnote:{
    en:'<p>In 1432 the Venetian merchant Pietro Querini was wrecked on Røst, at the outer edge of Lofoten, wintered with the islanders and came home with a description of the fish they hung on racks to dry in the wind. Venice needed food that kept — for Lent, and for ships — and took <em>stoccafisso</em> up wholesale. That is why in Veneto, and nowhere else in Italy, the word <em>baccalà</em> means stockfish rather than salt cod.</p>'
      + '<p>The distinction matters more in a Norwegian kitchen than anywhere, because both are on sale here. Stockfish, <em>tørrfisk</em>, is cod air-dried on racks without any salt, hard as a plank, and it needs days in cold water. Salt cod, <em>klippfisk</em>, is salted first and dried afterwards; it soaks out in a day and stays firmer and saltier. Only the unsalted kind gives the pale, airy cream this recipe is named for.</p>'
      + '<p><em>Mantecare</em> means to work something into a cream, and that is the whole method: soaked fish, poached gently, then beaten with olive oil until it turns white and holds a peak on a spoon. Nothing else goes in. On a bàcaro counter it is spread on a round of grilled white polenta and eaten standing up.</p>',
    no:'<p>I 1432 forliste den venetianske kjøpmannen Pietro Querini ved Røst, ytterst i Lofoten, overvintret hos øyboerne og kom hjem med en beskrivelse av fisken de hengte på hjell for å tørke i vinden. Venezia trengte mat som holdt seg, både gjennom fasten og om bord, og tok <em>stoccafisso</em> til seg for fullt. Derfor betyr ordet <em>baccalà</em> tørrfisk og ikke klippfisk i Veneto, og bare der.</p>'
      + '<p>Forskjellen betyr mer på et norsk kjøkken enn noe annet sted, for begge deler selges her. Tørrfisk er torsk som henger på hjell og tørker i luft uten salt, hard som en planke, og den må vannes ut i dagevis. Klippfisk saltes først og tørkes etterpå, den er utvannet på et døgn og blir fastere og saltere. Bare den usaltede fisken gir den bleke, luftige kremen som retten har navn etter.</p>'
      + '<p><em>Mantecare</em> betyr å arbeide noe til en krem, og det er hele metoden: utvannet fisk som trekker forsiktig, og som deretter piskes med olivenolje til den blir hvit og står i en topp på skjeen. Ingenting annet skal i. På disken i en bàcaro smøres den på en skive grillet hvit polenta og spises stående.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:400, u:'g', n:{en:'stockfish', no:'tørrfisk'}, note:{en:'dried without salt — tørrfisk, not klippfisk; ask for a piece of loin', no:'tørket uten salt — tørrfisk, ikke klippfisk; be om et stykke av loinen'}},
    {q:250, u:'ml', n:{en:'extra virgin olive oil', no:'ekstra virgin olivenolje'}, note:{en:'mild; a peppery oil fights the fish', no:'mild; en pepret olje slåss mot fisken'}},
    {q:1, u:'', n:{en:'bay leaf', no:'laurbærblad'}, round:'half'},
    {q:1, u:'', n:{en:'garlic clove', no:'hvitløksfedd'}, round:'half', note:{en:'optional, poached whole with the fish and thrown away', no:'valgfritt, trekkes helt sammen med fisken og kastes'}},
    {q:5, u:'g', n:{en:'flat-leaf parsley', no:'bladpersille'}, note:{en:'chopped', no:'hakket'}},
    {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    {u:'', n:{en:'white pepper', no:'hvit pepper'}, scale:'none'},
    {u:'', n:{en:'grilled white polenta or good bread, to serve', no:'grillet hvit polenta eller godt brød, til servering'}, scale:'none'},
  ]}],
  steps:[
    {en:'Saw or cut the stockfish into pieces that fit a bowl and cover them with plenty of cold water.',
     no:'Sag eller skjær tørrfisken i biter som får plass i en bolle, og dekk dem med rikelig kaldt vann.'},
    {en:'Keep the bowl in the fridge for two to three days, changing the water two or three times a day. The fish should swell to more than twice its dry weight and give under a finger.',
     no:'Sett bollen i kjøleskapet i to til tre døgn, og skift vann to eller tre ganger om dagen. Fisken skal svelle til mer enn dobbelt vekt og gi etter for en finger.'},
    {en:'Drain it, put it in a pan with fresh cold water to cover, and add the bay leaf and the garlic.',
     no:'Hell av vannet, legg fisken i en kjele med nytt kaldt vann som dekker, og ha i laurbærbladet og hvitløken.'},
    {en:'Bring it to the point where the surface only trembles and hold it there for 20 minutes. A hard boil shreds the fish and drives out the gelatin you need.',
     no:'Varm opp til overflaten så vidt skjelver, og hold den der i 20 minutter. Fosskoking river fisken i stykker og driver ut gelatinen du trenger.'},
    {en:'Lift the fish out and save a little of the poaching liquid.',
     no:'Løft fisken opp, og ta vare på litt av kraften.'},
    {en:'Pull the skin off while the fish is still warm and go through the flesh with your fingers for bones. Miss none.',
     no:'Dra av skinnet mens fisken ennå er varm, og gå gjennom kjøttet med fingrene etter bein. Ikke overse ett eneste.'},
    {en:'Put the warm flakes in a bowl and work them with a wooden spoon until they break down into threads.',
     no:'Legg de varme flakene i en bolle, og arbeid dem med en tresleiv til de går opp i tråder.'},
    {en:'Begin adding the oil in a thin thread, beating hard and without stopping, exactly as you would build a mayonnaise.',
     no:'Begynn å spe med oljen i en tynn stråle mens du pisker hardt og uten å stoppe, nøyaktig som når du lager majones.'},
    {en:'Loosen it with a spoonful of the poaching liquid whenever it tightens or starts to look oily.',
     no:'Spe med en skje av kraften hver gang massen strammer seg eller begynner å se oljete ut.'},
    {en:'Keep beating until it turns pale, glossy and thick enough to hold a peak. By hand that takes 15 to 20 minutes; a mixer with the paddle does it in five.',
     no:'Pisk videre til massen blir blek, blank og så tykk at den holder en topp. For hånd tar det 15 til 20 minutter, mens en kjøkkenmaskin med flatblander klarer det på fem.'},
    {en:'Season with salt, white pepper and parsley, and let it stand at room temperature for an hour before you serve it on polenta.',
     no:'Smak til med salt, hvit pepper og persille, og la kremen stå en time i romtemperatur før du serverer den på polenta.'},
  ],
  notes:[
    {title:{en:'Tørrfisk, not klippfisk', no:'Tørrfisk, ikke klippfisk'},
     body:{en:'Air drying takes the water out and leaves the protein and the connective tissue as they were. Salting does not: it draws water out by force, firms the muscle and changes its texture for good. Soak klippfisk as long as you like and it will still come out of the pan firm and salty, and it will never beat up into a mousse. The two words are not two names for one thing, and every Norwegian fish counter sells both.',
           no:'Lufttørking trekker ut vannet og lar proteinet og bindevevet være som de var. Salting gjør ikke det: den driver vannet ut med makt, gjør muskelen fast og endrer strukturen for godt. Du kan vanne ut klippfisk så lenge du vil, men den kommer likevel fast og salt opp av kjelen, og den lar seg aldri piske til en mousse. De to ordene er ikke to navn på samme sak, og enhver norsk fiskedisk fører begge deler.'}},
    {title:{en:'Why it creams with nothing but oil', no:'Derfor blir den kremet av bare olje'},
     body:{en:'While the fish poaches, the collagen in the skin and between the muscle blocks turns to gelatin and stays in the flesh. Gelatin is a surfactant: it sits at the boundary between oil and water and stops the two from separating. The fibres beaten into threads build a mesh that holds the droplets in place. It is a mayonnaise with gelatin doing the work of egg yolk, which is why it splits for the same reasons — oil added too fast, or fish that has gone cold. If it does split, start again in a clean bowl with a spoonful of warm fish and beat the broken mass back in slowly.',
           no:'Mens fisken trekker, går kollagenet i skinnet og mellom muskelblokkene over til gelatin og blir værende i kjøttet. Gelatin er et overflateaktivt stoff: det legger seg i grensen mellom olje og vann og hindrer at de to skiller lag. Fibrene som piskes til tråder, bygger et nett som holder dråpene på plass. Dette er en majones der gelatinen gjør jobben til eggeplommen, og derfor skiller den seg av de samme grunnene — olje som går i for fort, eller fisk som har blitt kald. Skiller den seg likevel, begynner du på nytt i en ren bolle med en skje varm fisk og pisker den skilte massen sakte inn igjen.'}},
    {title:{en:'Salt at the end', no:'Salt til slutt'},
     body:{en:'Stockfish carries no added salt, but it does carry its own, and the oil masks it until the cream is finished. Taste only when the last of the oil has gone in, and remember the polenta underneath is usually seasoned as well.',
           no:'Tørrfisk har ikke tilsatt salt, men den har sitt eget, og oljen dekker over det til kremen er ferdig. Smak til først når den siste oljen har gått i, og husk at polentaen under som regel også er saltet.'}},
  ],
  variations:[
    {title:{en:'Baccalà alla vicentina', no:'Baccalà alla vicentina'},
     body:{en:'The other road for the same fish, and Vicenza’s own: soaked stockfish cooked slowly with onion, anchovy, milk and Parmesan, and served with polenta as a main course rather than spread on it as a snack.',
           no:'Den andre veien å gå med den samme fisken, og Vicenzas egen: utvannet tørrfisk kokt langsomt med løk, ansjos, melk og parmesan, servert med polenta som hovedrett i stedet for å smøres på den som en småbit.'}},
    {title:{en:'A little milk', no:'Litt melk'},
     body:{en:'The old Venetian recipes use oil and nothing else. Many modern kitchens beat in a spoonful or two of cold whole milk at the very end, which whitens the cream and rounds off the salt. Venetians argue about it, and the argument is old enough that both sides can claim tradition.',
           no:'De gamle venetianske oppskriftene bruker olje og ikke noe annet. Mange moderne kjøkken pisker inn en skje eller to kald helmelk helt til slutt, og det gjør kremen hvitere og runder av saltet. Venetianerne krangler om det, og krangelen er gammel nok til at begge sider kan påberope seg tradisjonen.'}},
    {title:{en:'If you buy it ready-soaked', no:'Hvis du kjøper den ferdig utvannet'},
     body:{en:'Italian delicatessens sell <em>baccalà bagnato</em>, and Norwegian shops sell ready-soaked tørrfisk around Christmas. Both go straight into the poaching pan. Check it first: properly soaked fish is white, supple and smells of the sea rather than of the loft.',
           no:'Italienske delikatesseforretninger selger <em>baccalà bagnato</em>, og norske butikker selger ferdig utvannet tørrfisk rundt jul. Begge deler går rett i kjelen. Sjekk den først: riktig utvannet fisk er hvit og myk og lukter av sjø, ikke av loft.'}},
  ],
},

{
  id:'sarde-in-saor', dish:'Sarde in saor', course:'antipasto', lesson:3, serves:6, time:{prep:40, cook:45},
  hero:'sarde', tags:['fish','preserving','sweet-sour'],
  title:{en:'Sarde in saor', no:'Sarde in saor'},
  blurb:{en:'Fried sardines buried in vinegared onions with raisins and pine nuts, and left for a day. Preserving that turned into a flavour.',
         no:'Friterte sardiner gravd ned i eddikkokt løk med rosiner og pinjekjerner, og satt bort et døgn. Konservering som ble til en smak.'},
  heroCaption:{en:'Sarde in saor: as much onion as fish, and never eaten on the day it is made.',
               no:'Sarde in saor: like mye løk som fisk, og aldri spist samme dag som den lages.'},
  wines:['Prosecco Superiore'],
  headnote:{
    en:'<p><em>Saor</em> is the Venetian form of <em>sapore</em>, flavour, and it names a method rather than a single dish: fish fried, then buried in onions cooked soft in vinegar and left to stand for a day or two. It began as a boat’s larder. The acid held the fish through a voyage with no ice on board, and the onions carried enough vitamin C to keep scurvy off the crew.</p>'
      + '<p>The sweet half arrived later, along the routes the republic controlled. Raisins and pine nuts, and in the grander versions a little cinnamon, come from Byzantium and the Arab kitchen, and they are the reason a preserving trick tastes like a relative of a dessert. Everything about the dish follows from the mechanism: fry the fish so it can stand two days in liquid, use as much onion as fish, and do not eat it on the day you make it.</p>'
      + '<p>Venetians still eat it cold from boats on the lagoon on the night of the Redentore in July, under the fireworks over the Giudecca. The rest of the year it is a saucer on a bàcaro counter, on bread or beside a slab of white polenta.</p>',
    no:'<p><em>Saor</em> er den venetianske formen av <em>sapore</em>, smak, og ordet står for en metode og ikke for én enkelt rett: fisk som friteres og så graves ned i løk kokt myk i eddik og får stå en dag eller to. Det begynte som et spiskammer om bord. Syren holdt fisken gjennom en reise uten is, og løken bar nok C-vitamin til å holde skjørbuken borte fra mannskapet.</p>'
      + '<p>Den søte halvdelen kom senere, langs rutene republikken kontrollerte. Rosiner og pinjekjerner, og i de flottere versjonene litt kanel, kommer fra Bysants og det arabiske kjøkkenet, og de er grunnen til at et konserveringsknep smaker som en slektning av en dessert. Alt ved retten følger av mekanismen: friter fisken så den tåler to døgn i væske, bruk like mye løk som fisk, og spis den ikke samme dag som du lager den.</p>'
      + '<p>Venetianerne spiser den fortsatt kald fra båter på lagunen natten til Redentore i juli, under fyrverkeriet over Giudecca. Resten av året står den som et fat på disken i en bàcaro, på brød eller ved siden av en skive hvit polenta.</p>'},
  ingredients:[
    { group:{en:'For the fish', no:'Til fisken'}, items:[
      {q:800, u:'g', n:{en:'fresh sardines', no:'ferske sardiner'}, note:{en:'scaled and gutted, heads off, backbone lifted out', no:'skjellet og renset, uten hoder, med ryggbeinet tatt ut'}},
      {q:80, u:'g', n:{en:'plain flour', no:'hvetemel'}, note:{en:'for dusting', no:'til vending'}},
      {u:'', n:{en:'oil for frying', no:'olje til fritering'}, scale:'none'},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'For the saor', no:'Til saoren'}, items:[
      {q:800, u:'g', n:{en:'white onions', no:'hvit løk'}, note:{en:'sliced as thin as you can; the same weight as the fish', no:'skåret i så tynne skiver du klarer; samme vekt som fisken'}},
      {q:80, u:'ml', n:{en:'olive oil', no:'olivenolje'}},
      {q:200, u:'ml', n:{en:'white wine vinegar', no:'hvitvinseddik'}},
      {q:50, u:'g', n:{en:'raisins', no:'rosiner'}},
      {q:30, u:'g', n:{en:'pine nuts', no:'pinjekjerner'}},
      {q:2, u:'', n:{en:'bay leaves', no:'laurbærblad'}, round:'half'},
      {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
    ]},
  ],
  steps:[
    {en:'Scale the sardines under running water, pull the heads off and take the guts out with a thumb.',
     no:'Skrap skjellene av sardinene under rennende vann, riv av hodene, og ta ut innmaten med tommelen.'},
    {en:'Open each fish out flat, lift the backbone away from the tail end and pat the fillets dry.',
     no:'Brett hver fisk flat, løsne ryggbeinet fra halen og oppover, og tørk filetene med papir.'},
    {en:'Cover the raisins with warm water and leave them to swell while the onions cook.',
     no:'Dekk rosinene med varmt vann, og la dem svelle mens løken koker.'},
    {en:'Slice the onions as thinly as you can manage.',
     no:'Skjær løken i så tynne skiver du klarer.'},
    {en:'Cook them in the olive oil over low heat with the bay and a little salt, covered, for 30 minutes, until they are translucent and collapsed and have taken no colour at all.',
     no:'Kok den i olivenoljen på svak varme med laurbær og litt salt, under lokk, i 30 minutter, til den er blank og falt sammen uten å ha tatt farge i det hele tatt.'},
    {en:'Pour in the vinegar, raise the heat and let it bubble for three or four minutes, then take the pan off the heat.',
     no:'Hell i eddiken, skru opp varmen, og la det boble i tre–fire minutter. Ta så kjelen av platen.'},
    {en:'Dust the sardines with flour and shake every loose grain off them.',
     no:'Vend sardinene i mel, og rist av hvert løse korn.'},
    {en:'Fry them in hot oil, about 180 °C, for a minute or two a side, until the crust has set and is pale gold. Drain them on paper and salt them at once.',
     no:'Friter dem i varm olje, omtrent 180 °C, i ett til to minutter på hver side, til skorpen har satt seg og er lyst gyllen. Legg dem på papir, og salt dem med en gang.'},
    {en:'Lay a bed of onions in a deep dish, then a layer of sardines, then drained raisins and pine nuts. Repeat, and finish with onions so that nothing is left uncovered.',
     no:'Legg et lag løk i bunnen av et dypt fat, så et lag sardiner, så avrente rosiner og pinjekjerner. Gjenta, og avslutt med løk slik at ingenting blir liggende udekket.'},
    {en:'Press the surface flat with the back of a spoon until liquid rises, cover the dish and refrigerate it for at least a day. Two is better.',
     no:'Press overflaten flat med baksiden av en skje til væsken stiger, dekk fatet, og sett det kaldt i minst ett døgn. To er bedre.'},
    {en:'Take it out an hour before the meal, grind pepper over it and serve at room temperature, never hot, with bread or polenta.',
     no:'Ta det ut en time før måltidet, kvern pepper over, og server ved romtemperatur, aldri varmt, med brød eller polenta.'},
  ],
  notes:[
    {title:{en:'Why saor keeps fish', no:'Derfor holder saor på fisken'},
     body:{en:'Vinegar takes the marinade below about pH 4,5, and the bacteria that spoil oily fish cannot work there. The sugar in the raisins takes the edge off the acid, and the film of oil on top keeps the air out. Refrigeration has made the preserving unnecessary, so what is left is the flavour — but the proportions still come from the job the dish used to do, and that is why they are not negotiable.',
           no:'Eddik tar marinaden ned under omtrent pH 4,5, og bakteriene som ødelegger fet fisk, klarer seg ikke der. Sukkeret i rosinene tar brodden av syren, og oljefilmen på toppen holder luften ute. Kjøleskapet har gjort konserveringen unødvendig, og igjen står bare smaken — men proporsjonene kommer fortsatt fra jobben retten en gang gjorde, og derfor kan de ikke forhandles bort.'}},
    {title:{en:'The onion is the cure, not the garnish', no:'Løken er kuren, ikke pynten'},
     body:{en:'Weight for weight with the fish. Cooked slowly under a lid it gives up its own water and takes vinegar in return, so it becomes the marinade instead of sitting in one. Brown it and you add a caramel bitterness that fights the acid rather than balancing it, and no amount of standing time will take that out again.',
           no:'Vekt for vekt med fisken. Kokes den langsomt under lokk, gir den fra seg sitt eget vann og tar opp eddik i stedet, og dermed blir den selve marinaden i stedet for å ligge i en. Bruner du den, får du en karamellbitterhet som slåss mot syren i stedet for å balansere den, og ingen ståtid får den ut igjen.'}},
    {title:{en:'Fry, do not poach', no:'Friter, ikke trekk'},
     body:{en:'The thin flour crust and the dry, set surface are what let a fillet stand in liquid for two days without falling apart. A poached sardine is already fragile on the first evening and has gone to shreds by the second morning. This is worth carrying to any marinated fish: seal the outside first, then marinate.',
           no:'Den tynne melskorpen og den tørre, satte overflaten er grunnen til at en filet tåler å ligge to døgn i væske uten å gå i oppløsning. En sardin som bare har trukket, er skjør allerede første kveld og er gått i filler til andre morgen. Dette er verdt å ta med seg til all marinert fisk: forsegl utsiden først, marinér etterpå.'}},
  ],
  variations:[
    {title:{en:'Other things in saor', no:'Andre ting i saor'},
     body:{en:'Small sole go the same way and are called <em>sfogi in saor</em>; so do prawns. There is a meatless version made with fried pumpkin or courgette instead of the fish, which needs a shorter stand because there is nothing to preserve.',
           no:'Små sjøtunger behandles på samme måte og kalles <em>sfogi in saor</em>, og det samme gjør reker. Det finnes en kjøttfri variant med stekt gresskar eller squash i stedet for fisk, og den trenger kortere ståtid, for det er ingenting der som må konserveres.'}},
    {title:{en:'The plainer, older version', no:'Den enklere og eldre versjonen'},
     body:{en:'Leave out the raisins and the pine nuts and you have onion, vinegar and fish and nothing else — the fisherman’s saor, before the spice trade dressed it up. It is sharper, and it goes better with a glass of Soave than the sweet version does.',
           no:'Sløyfer du rosinene og pinjekjernene, sitter du igjen med løk, eddik og fisk og ikke noe mer — fiskerens saor, slik den var før krydderhandelen pyntet den opp. Den er skarpere, og den kler et glass Soave bedre enn den søte versjonen gjør.'}},
    {title:{en:'Spiced, in the Renaissance manner', no:'Krydret, på renessansevis'},
     body:{en:'A short stick of cinnamon and two cloves in the onions while they cook take the dish towards the version the great houses served, when spice on the table was a statement about where your money came from. Use less than you think; the fish is delicate.',
           no:'En kort kanelstang og to nellikspikre i løken mens den koker, tar retten mot den versjonen de store husene serverte, den gangen krydder på bordet var en beskjed om hvor pengene kom fra. Bruk mindre enn du tror, for fisken er sart.'}},
  ],
},

{
  id:'bigoli-in-salsa', dish:'Bigoli in salsa', course:'primo', lesson:3, serves:4, time:{prep:20, cook:50},
  hero:'bigoli', tags:['pasta','anchovy','fast-day'],
  title:{en:'Bigoli in salsa', no:'Bigoli in salsa'},
  blurb:{en:'The fast-day pasta of Veneto: onions cooked to a purée, salted fish stirred in until it vanishes, and no cheese anywhere.',
         no:'Venetos fastedagspasta: løk kokt til puré, saltfisk rørt inn til den forsvinner, og ikke ost noe sted.'},
  heroCaption:{en:'Bigoli in salsa: thick wholemeal strands and a sauce with two ingredients.',
               no:'Bigoli in salsa: tykke strenger av sammalt hvete og en saus med to ingredienser.'},
  wines:['Soave Classico'],
  headnote:{
    en:'<p><em>Salsa</em> here means nothing more than sauce, and this sauce has two ingredients: onions cooked until they fall apart, and salted fish stirred in until it disappears. No meat, no cheese, no tomato, no garlic. Bigoli in salsa is what Veneto ate on the days the church allowed none of those — Ash Wednesday, Good Friday, Christmas Eve — and it is still on the table on all three.</p>'
      + '<p>Bigoli are the region’s own pasta: thick, rough strands pushed through a bronze die called a <em>bigolaro</em>, made from soft wheat, often wholemeal, sometimes enriched with duck egg. The roughness has a job. A sauce this thin and this smooth finds nothing to hold on to on a slippery machine-drawn spaghetti, but it grips a bigolo the way paint grips sandpaper.</p>'
      + '<p>The fish is <em>sardèle salae</em>, whole sardines packed in salt, rinsed and boned at the last minute. Anchovy fillets are the usual substitute and give a sharper, saltier sauce, so use fewer of them. And there is a Norwegian trap worth naming: what a Norwegian shop sells in a jar as <em>ansjos</em> is spiced sprat and belongs to another dish entirely. What you want is proper anchovy, sold in Norway as sardeller.</p>',
    no:'<p><em>Salsa</em> betyr ikke annet enn saus her, og denne sausen har to ingredienser: løk som kokes til den faller fra hverandre, og saltfisk som røres inn til den forsvinner. Ikke kjøtt, ikke ost, ikke tomat, ikke hvitløk. Bigoli in salsa er det Veneto spiste på dagene da kirken forbød alt dette — askeonsdag, langfredag og julaften — og retten står fortsatt på bordet alle tre dagene.</p>'
      + '<p>Bigoli er regionens egen pasta: tykke, ru strenger presset gjennom en bronsedyse som kalles <em>bigolaro</em>, laget av hvetemel, ofte sammalt, iblant med andeegg i deigen. Ruheten har en oppgave. En saus som er så tynn og så glatt, finner ingenting å holde seg fast i på maskintrukket spaghetti, men den griper en bigolo slik maling griper sandpapir.</p>'
      + '<p>Fisken er <em>sardèle salae</em>, hele sardiner lagt ned i salt, som skylles og benes i siste liten. Ansjosfileter er den vanlige erstatningen og gir en skarpere og saltere saus, så bruk færre av dem. Og her er det en norsk felle verdt å nevne: <em>ansjos</em> på glass i norske butikker er krydret brisling og hører til en helt annen rett. Du trenger ekte ansjos, som selges som sardeller.</p>'},
  ingredients:[{ group:{en:'', no:''}, items:[
    {q:400, u:'g', n:{en:'bigoli', no:'bigoli'}, note:{en:'or a thick wholemeal spaghetti, bronze-drawn', no:'eller en tykk spaghetti av sammalt hvete, bronsetrukket'}},
    {q:600, u:'g', n:{en:'white onions', no:'hvit løk'}, note:{en:'sliced paper-thin', no:'skåret i papirtynne skiver'}},
    {q:8, u:'', n:{en:'salt-cured sardines', no:'saltede sardiner'}, round:'half', note:{en:'sardèle salae, packed whole in salt', no:'sardèle salae, hele sardiner lagt ned i salt'}},
    {q:80, u:'ml', n:{en:'olive oil', no:'olivenolje'}},
    {q:100, u:'ml', n:{en:'water, for the onions', no:'vann til løken'}, note:{en:'added a splash at a time', no:'spes i litt om gangen'}},
    {u:'', n:{en:'black pepper', no:'sort pepper'}, scale:'none'},
    {q:3, u:'l', n:{en:'water, for the pasta', no:'vann til pastaen'}, scale:'sub'},
    {q:10, u:'g', n:{en:'salt for the water', no:'salt i kokevannet'}, scale:'sub', note:{en:'less than usual, because the salsa brings its own', no:'mindre enn vanlig, for sausen har rikelig salt i seg'}},
  ]}],
  steps:[
    {en:'Rinse the salted sardines under cold running water and rub the salt off with your fingers.',
     no:'Skyll de saltede sardinene under kaldt, rennende vann, og gni saltet av med fingrene.'},
    {en:'Open each fish along the belly, lift out the backbone and the fins, and leave the fillets to drain.',
     no:'Åpne hver fisk langs buken, løft ut ryggbein og finner, og la filetene renne av.'},
    {en:'Slice the onions as thinly as you can. Thickness alone decides how long the next step takes.',
     no:'Skjær løken i så tynne skiver du klarer. Tykkelsen alene avgjør hvor lang tid neste trinn tar.'},
    {en:'Cook them in the olive oil in a wide pan over the lowest heat you have, covered, stirring often.',
     no:'La løken koke i olivenoljen i en vid panne på den svakeste varmen du har, under lokk, og rør ofte.'},
    {en:'Add a splash of water whenever the pan looks dry, and keep going for 40 minutes, until the onions have collapsed into a pale purée. Do not let them take colour.',
     no:'Spe med en skvett vann hver gang pannen ser tørr ut, og hold på i 40 minutter, til løken har falt sammen til en blek puré. Den skal ikke ta farge.'},
    {en:'Chop the drained fillets and stir them into the onions.',
     no:'Hakk de avrente filetene, og rør dem inn i løken.'},
    {en:'Work the pan with a wooden spoon over low heat until not one piece of fish is left whole and the sauce is even and greyish brown.',
     no:'Arbeid pannen med en tresleiv på svak varme til ikke én bit av fisken er hel, og sausen er jevn og gråbrun.'},
    {en:'Bring the water to the boil and salt it lightly.',
     no:'Kok opp vannet, og salt det lett.'},
    {en:'Cook the bigoli — fresh ones take three or four minutes, dried ones whatever the packet says — and keep some of the cooking water.',
     no:'Kok bigoliene — ferske tar tre–fire minutter, tørkede den tiden pakken sier — og ta vare på litt av kokevannet.'},
    {en:'Drain, turn the pasta into the pan with a little of that water, and toss over medium heat for a minute until every strand is coated.',
     no:'Hell av vannet, ha pastaen i pannen med en skvett kokevann, og vend det på middels varme et minutt, til hver streng er dekket.'},
    {en:'Grind pepper over it and serve. No cheese goes anywhere near this dish.',
     no:'Kvern pepper over, og server. Ost skal ikke i nærheten av denne retten.'},
  ],
  notes:[
    {title:{en:'The onion is the sauce', no:'Løken er sausen'},
     body:{en:'A big weight of raw onion cooks down to a few spoonfuls of purée. Lid on, lowest heat, and water rather than more oil, so it steams and sweetens instead of frying and browning. Browning would bring a caramel bitterness that fights salted fish, and there is no stock and no cheese in this dish to hide behind. Onion sugar, fish salt and the glutamate the curing has built up are the entire seasoning.',
           no:'En stor mengde rå løk koker inn til noen få skjeer puré. Lokk på, svakest mulig varme, og vann i stedet for mer olje, slik at den damper og blir søt i stedet for å steke og brune seg. Bruning ville gitt en karamellbitterhet som slåss mot saltfisken, og i denne retten finnes verken kraft eller ost å gjemme seg bak. Sukkeret i løken, saltet i fisken og glutamatet som modningen har bygd opp, er hele krydringen.'}},
    {title:{en:'Why a fast-day dish has no cheese', no:'Derfor er det ingen ost i en fastedagsrett'},
     body:{en:'The lean days of the church year barred meat, and in the strict Venetian reading dairy with it. What remained in the house was oil, onions and preserved fish, and the recipe was built to be good inside that rule rather than to apologise for it. Grating Parmesan over it does not improve the dish; it covers the fish, which is the only thing in it worth tasting.',
           no:'Kirkeårets magre dager forbød kjøtt, og i den strenge venetianske tolkningen meieriprodukter med på kjøpet. I huset var det bare olje, løk og konservert fisk igjen, og oppskriften ble bygd for å være god innenfor den regelen, ikke for å be om unnskyldning for den. Å rive parmesan over gjør ikke retten bedre. Osten legger seg bare over fisken, og fisken er det eneste her som er verdt å smake.'}},
    {title:{en:'Rinse well, salt last', no:'Skyll godt, salt sist'},
     body:{en:'Salted sardines vary enormously from one tub to the next, so rinse thoroughly, taste the finished salsa, and only then decide how much salt the pasta water needs. This is the general rule for any cured-fish sauce: the fish seasons the dish, and you season around it.',
           no:'Saltede sardiner varierer voldsomt fra spann til spann, så skyll grundig, smak på den ferdige sausen, og bestem først da hvor mye salt kokevannet trenger. Dette er den generelle regelen for enhver saus med speket fisk: fisken krydrer retten, og du krydrer rundt den.'}},
  ],
  variations:[
    {title:{en:'With anchovies', no:'Med ansjos'},
     body:{en:'Anchovy fillets in oil are the everyday substitute. Drain them, use fewer than you would sardines because they are sharper and saltier, and expect them to melt into the onions in half the time.',
           no:'Ansjosfileter i olje er den daglige erstatningen. La dem renne av, bruk færre enn du ville brukt sardiner, siden de er skarpere og saltere, og regn med at de smelter inn i løken på halve tiden.'}},
    {title:{en:'A splash of white wine', no:'En skvett hvitvin'},
     body:{en:'Some households pour a little dry white wine into the onions before the water goes in and let it cook away. It lifts the sweetness and makes the sauce taste less flat on a day when there is no fat from meat in the pan.',
           no:'Noen husholdninger heller litt tørr hvitvin over løken før vannet går i, og lar den koke bort. Det løfter sødmen og gjør at sausen smaker mindre flat på en dag da det ikke er kjøttfett i pannen.'}},
    {title:{en:'Breadcrumbs instead of cheese', no:'Brødsmuler i stedet for ost'},
     body:{en:'Cheese is out, but a spoonful of coarse breadcrumbs toasted in oil until they crackle gives the crunch and the toasted note that cheese would have supplied. It is the poor kitchen’s answer all down the Adriatic coast, and it belongs here.',
           no:'Ost er utelukket, men noen grove brødsmuler ristet i olje til de knitrer, gir sprøheten og det ristede preget som osten ellers ville stått for. Det er det fattige kjøkkenets svar hele Adriaterhavskysten nedover, og det hører hjemme her.'}},
  ],
},

{
  id:'tiramisu', dish:'Tiramisù', course:'dolce', lesson:3, serves:6, time:{prep:30, cook:5},
  hero:'tiramisu', tags:['dessert','coffee','raw egg'],
  title:{en:'Tiramisù', no:'Tiramisù'},
  blurb:{en:'Treviso, early 1970s: savoiardi, coffee, mascarpone, egg and cocoa. Nothing else, and the eggs go in raw.',
         no:'Treviso, tidlig på 1970-tallet: savoiardi, kaffe, mascarpone, egg og kakao. Ikke noe annet, og eggene går i rå.'},
  heroCaption:{en:'The Treviso original has no cream, no gelatine and no alcohol in it.',
               no:'Originalen fra Treviso inneholder verken fløte, gelatin eller alkohol.'},
  wines:[],
  headnote:{
    en:'<p>Tiramisù — <em>tira mi sù</em>, pick me up — appeared on the menu of Le Beccherie in Treviso in the early 1970s, and although other towns claim it, Treviso’s is the version the world eats. It is very young for an Italian classic, which is why the argument about who invented it is still running and why no one can settle it with a document from a century ago.</p>'
      + '<p>The Treviso recipe is short: savoiardi, espresso, mascarpone, egg, sugar, cocoa. No cream, no gelatine, no Marsala, no rum. Every one of those is a later addition, and each of them makes the dessert softer and blander. Mascarpone is already close to half fat, so it needs no help from anything else in the fridge.</p>'
      + '<p>The eggs go in raw. Nothing in this recipe is heated, so let it be said plainly: this is an uncooked-egg dessert. Keep it cold, eat it within two days, and think before serving it to anyone pregnant, very young, very old or immunocompromised. Norwegian eggs come out of a national salmonella-control programme, which is why raw egg is ordinary in a Norwegian kitchen. If you would rather not take it on, the syrup variation below solves the problem properly instead of ignoring it.</p>',
    no:'<p>Tiramisù — <em>tira mi sù</em>, løft meg opp — dukket opp på menyen til Le Beccherie i Treviso tidlig på 1970-tallet, og selv om andre byer gjør krav på den, er det Trevisos versjon verden spiser. Den er svært ung til å være en italiensk klassiker, og striden om hvem som fant den opp, er fortsatt levende. Ingen kan avgjøre den med et dokument fra hundre år tilbake.</p>'
      + '<p>Oppskriften fra Treviso er kort: savoiardi, espresso, mascarpone, egg, sukker og kakao. Ingen fløte, ingen gelatin, ingen marsala, ingen rom. Alt dette er senere tilskudd, og hvert av dem gjør desserten løsere og flatere i smaken. Mascarpone er allerede nesten halvparten fett og trenger ingen hjelp fra noe annet i kjøleskapet.</p>'
      + '<p>Eggene går i rå. Ingenting i denne oppskriften varmes opp, så la det bli sagt rett ut: dette er en dessert med rått egg. Hold den kald, spis den innen to døgn, og tenk deg om før du serverer den til gravide, små barn, eldre eller folk med svekket immunforsvar. Norske egg kommer fra et nasjonalt salmonellaprogram, og derfor er rått egg helt vanlig på norske kjøkken. Vil du likevel ikke ta sjansen, løser sukkerlaken lenger nede problemet ordentlig i stedet for å overse det.</p>'},
  ingredients:[
    { group:{en:'For the cream', no:'Til kremen'}, items:[
      {q:500, u:'g', n:{en:'mascarpone', no:'mascarpone'}, note:{en:'straight from the fridge', no:'rett fra kjøleskapet'}},
      {q:4, u:'', n:{en:'eggs', no:'egg'}, round:'half', note:{en:'as fresh as you can buy, separated, at room temperature', no:'så ferske som mulig, delt, med romtemperatur'}},
      {q:100, u:'g', n:{en:'caster sugar', no:'finkornet sukker'}},
      {u:'', n:{en:'salt', no:'salt'}, scale:'none'},
    ]},
    { group:{en:'To assemble', no:'Til montering'}, items:[
      {q:250, u:'g', n:{en:'savoiardi', no:'savoiardi'}, note:{en:'dry Italian ladyfingers; a soft sponge finger will not survive the coffee', no:'tørre italienske kjeks; en myk sukkerbrødsfinger overlever ikke kaffen'}},
      {q:300, u:'ml', n:{en:'espresso', no:'espresso'}, note:{en:'strong, unsweetened and completely cold', no:'sterk, usøtet og helt kald'}},
      {q:15, u:'g', n:{en:'cocoa powder', no:'kakaopulver'}, note:{en:'unsweetened, for dusting', no:'usøtet, til sikting'}},
    ]},
  ],
  steps:[
    {en:'Brew the espresso, pour it into a shallow dish and leave it to go completely cold. Warm coffee melts the cream on contact.',
     no:'Trakt espressoen, hell den i et grunt fat, og la den bli helt kald. Varm kaffe smelter kremen med en gang.'},
    {en:'Separate the eggs, putting the whites into a bowl with no trace of fat in it.',
     no:'Del eggene, og ha hvitene i en bolle uten spor av fett.'},
    {en:'Beat the yolks with two thirds of the sugar until they are pale, thick and no longer feel gritty between finger and thumb.',
     no:'Pisk plommene med to tredeler av sukkeret til de er lyse og tykke og ikke lenger kjennes grynete mellom fingrene.'},
    {en:'Loosen the mascarpone on its own, then work it into the yolks a spoonful at a time until it is smooth. Stop there: beaten too long, mascarpone splits and weeps.',
     no:'Rør mascarponen løs for seg, og arbeid den inn i eggeplommene en skje om gangen til blandingen er jevn. Stopp der, for pisker du mascarpone for lenge, skiller den seg.'},
    {en:'Whisk the whites with a pinch of salt, adding the rest of the sugar as they take, to soft peaks that flop over. Stiff whites cannot be folded in without tearing the cream.',
     no:'Pisk hvitene med en klype salt, og spe med resten av sukkeret etter hvert som de tar seg opp. De skal stå i myke topper som faller over. Stive hviter lar seg ikke vende inn uten å rive opp kremen.'},
    {en:'Fold the whites into the mascarpone in three goes, cutting down through the middle with a spatula and lifting, until no white streaks are left.',
     no:'Vend hvitene inn i mascarponen i tre omganger. Skjær ned gjennom midten med en slikkepott og løft, til ingen hvite striper er igjen.'},
    {en:'Dip each savoiardo in the coffee for about a second a side. They drink far more than you expect, and a soaked biscuit turns to paste.',
     no:'Dypp hver savoiardo i kaffen omtrent ett sekund på hver side. De drikker langt mer enn du tror, og en gjennombløt kjeks blir til grøt.'},
    {en:'Lay a close layer of dipped biscuits in the dish and spread half the cream evenly over them.',
     no:'Legg et tett lag med dyppede kjeks i formen, og bre halvparten av kremen jevnt utover.'},
    {en:'Repeat with the rest of the biscuits and the rest of the cream, and smooth the top.',
     no:'Gjenta med resten av kjeksene og resten av kremen, og glatt toppen.'},
    {en:'Cover it and refrigerate for at least six hours, better overnight, until the biscuits have turned from biscuit into cake.',
     no:'Dekk formen, og sett den kaldt i minst seks timer, helst natten over, til kjeksene har gått fra kjeks til kake.'},
    {en:'Dust the cocoa over through a fine sieve at the table, not before. Cocoa put on early draws damp out of the cream and goes grey.',
     no:'Sikt kakaoen over ved bordet, ikke før. Kakao som legges på tidlig, trekker fuktighet ut av kremen og blir grå.'},
  ],
  notes:[
    {title:{en:'Raw egg is a choice with a consequence', no:'Rått egg er et valg med en konsekvens'},
     body:{en:'Nothing in the cream is ever heated, so nothing in it is ever killed. Sugar and cold slow bacteria down; they do not remove them. That is why the dessert is at its best on the day after it is made and should be finished on the day after that, and why the pasteurised version below exists. Made with fresh eggs, kept covered and cold, and eaten inside two days, it is the same risk a Norwegian kitchen already takes with a raw egg yolk on a beef tartare.',
           no:'Ingenting i kremen varmes opp, og derfor drepes ingenting i den heller. Sukker og kulde bremser bakterier, men fjerner dem ikke. Derfor er desserten på sitt beste dagen etter at den er laget, og bør være spist opp dagen etter der igjen, og derfor finnes den pasteuriserte varianten nedenfor. Lager du den med ferske egg, holder den tildekket og kald og spiser den innen to døgn, tar du den samme risikoen som et norsk kjøkken allerede tar med en rå eggeplomme på en biff tartar.'}},
    {title:{en:'Whipped white, not whipped cream', no:'Pisket hvite, ikke pisket fløte'},
     body:{en:'A whipped white is air held in a protein film, and it lifts the mascarpone without adding any fat or any dairy sweetness of its own. Cream does the opposite: it adds fat to something already rich and dilutes the cheese flavour that the dessert is built on. The Treviso cream is firmer, tastes more of mascarpone and coffee, and cuts cleanly with a spoon instead of sagging.',
           no:'En pisket eggehvite er luft holdt oppe av en proteinhinne, og den løfter mascarponen uten å tilføre fett eller sødme fra meieriet. Fløte gjør det motsatte: den legger fett til noe som allerede er fett, og tynner ut ostesmaken hele desserten er bygd på. Kremen fra Treviso er fastere, smaker mer av mascarpone og kaffe, og lar seg dele rent med en skje i stedet for å skli ut.'}},
    {title:{en:'One second in the coffee', no:'Ett sekund i kaffen'},
     body:{en:'Savoiardi are a dry, fatless sponge riddled with open pores, so they pull coffee in by capillary action far faster than a cake would. They then go on taking moisture out of the cream all night in the fridge. A biscuit that felt only just damp when you laid it down will be right by morning; one that felt properly soaked will be sludge. Under-dip, always.',
           no:'Savoiardi er en tørr, fettfri sukkerbrødskjeks full av åpne porer, og derfor suger de til seg kaffe ved kapillærkraft langt raskere enn en kake ville gjort. Så fortsetter de å trekke fuktighet ut av kremen hele natten i kjøleskapet. En kjeks som kjentes så vidt fuktig da du la den ned, er akkurat passe om morgenen, mens en som kjentes ordentlig gjennombløt, er blitt til søle. Dypp alltid for lite.'}},
  ],
  variations:[
    {title:{en:'Pasteurised, without raw egg', no:'Pasteurisert, uten rått egg'},
     body:{en:'Cook the sugar for the yolks with a little water until it reaches 121 °C, then pour it in a slow thread onto the yolks while they beat. The hot syrup takes them past 70 °C without scrambling them and they whip on into a thick, stable foam. Do the same with the whites for an Italian meringue. The cream comes out sweeter and firmer, it holds for four days, and there is no raw egg left in the dish.',
           no:'Kok sukkeret til plommene med litt vann til det når 121 °C, og hell det så i en tynn stråle over plommene mens de piskes. Den varme laken tar dem forbi 70 °C uten at de koagulerer, og de piskes videre til et tykt og stabilt skum. Gjør det samme med hvitene, så får du en italiensk marengs. Kremen blir søtere og fastere, den holder seg i fire dager, og det er ikke rått egg igjen i retten.'}},
    {title:{en:'Marsala or rum', no:'Marsala eller rom'},
     body:{en:'A splash in the coffee, or a spoonful beaten into the yolks, is standard almost everywhere outside Treviso and is what most Italian households actually do. It is not the original, and it does cover some of the coffee, so add less than the recipe you copied it from suggests.',
           no:'En skvett i kaffen, eller en skje pisket inn i eggeplommene, er standard nesten overalt utenfor Treviso, og det er dette de fleste italienske husholdninger faktisk gjør. Det er ikke originalen, og det legger seg litt over kaffesmaken, så bruk mindre enn de fleste oppskrifter foreslår.'}},
    {title:{en:'Cream in place of the whites', no:'Fløte i stedet for hvitene'},
     body:{en:'Whipped cream folded in instead of the egg whites is the restaurant compromise: softer, sweeter, less egg on the palate, and it stands up on a buffet for hours. It is also what most tiramisù outside Italy turns out to be.',
           no:'Pisket fløte vendt inn i stedet for eggehvitene er restaurantkompromisset: løsere, søtere, mindre eggsmak, og den står seg i timevis på et koldtbord. Det er også dette de fleste tiramisù utenfor Italia viser seg å være.'}},
  ],
},

];
